SF-1231 Handle when using a share link while offline
sillsdev/web-xforge pull request #1001
Opened 2021-04-05 21:22 UTC by RaymondLuong3

* separate out scenarios when activating projects route
* if offline show a dialog message
* navigate to the last project upon closing the dialog

![join_project_offline](https://user-images.githubusercontent.com/17931130/113628645-6d324e80-9622-11eb-8ec4-30702dc9bb27.PNG)

2021-04-05 21:51 UTC, marksvc commented
:eyes:

2021-04-05 22:27 UTC, marksvc requested changes
Thanks for your work on this. I approve, minus comments.

> Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1001#-:-MXZ4yQNDGtL6-u9X9Xp:brygscm)* status: all files reviewed, 5 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts, line 36 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1001#-MXZ0Sc31iXyvwXwlN31:-MXZ0Sc31iXyvwXwlN32:b-c48zeb) ([raw file](https://github.com/sillsdev/web-xforge/blob/ebccac63ffe16caf4f642a701ca30769c1892f5e/src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts#L36)):*
> ```XML
>   }
> 
>   ngOnInit(): void {
> ```

Thank you so much for refactoring this method.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts, line 42 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1001#-MXZ14eM0NJj7OIqYX8O:-MXZ14eM0NJj7OIqYX8P:bi5e6y) ([raw file](https://github.com/sillsdev/web-xforge/blob/ebccac63ffe16caf4f642a701ca30769c1892f5e/src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts#L42)):*
> ```
> .pipe
> ```
Isn't .pipe() for when you have a bunch of things to do? Here you just filter.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts, line 49 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1001#-MXZ3xAO1843cHK_Luq3:-MXZ3xAO1843cHK_Luq4:b-8pql1z) ([raw file](https://github.com/sillsdev/web-xforge/blob/ebccac63ffe16caf4f642a701ca30769c1892f5e/src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts#L49)):*
> ```XML
>     );
>     this.subscribe(checkLinkSharing$, projectId => this.checkLinkSharing(projectId));
>     const showOfflineMessage$ = combineLatest([projectId$, this.pwaService.onlineStatus]).pipe(
> ```

Thumbs up for using variable names, exposing more meaning, rather than chaining together the subject and subscribe in the same line. 
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts, line 56 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1001#-MXZ7v4_C16fW6AA9Z2G:-MXZ7v4_C16fW6AA9Z2H:bhhezup) ([raw file](https://github.com/sillsdev/web-xforge/blob/55c203b59ad96dea77b1bd84a573f4c24038ebf8/src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts#L56)):*
> ```
>   this.loadingFinished();
> ```
And later `this.loadingFinished();`, I think.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts, line 139 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1001#-MXYyhNf8LrZdsCduS7G:-MXYyhNg4bWvu0tkzFCo:bopyomt) ([raw file](https://github.com/sillsdev/web-xforge/blob/c8a190a3be0eae7b3fe72921993687d416672921/src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts#L139)):*
> ```XML
> 
>     verify(mockedSFProjectService.onlineCheckLinkSharing('project01', undefined)).once();
>     verify(mockedRouter.navigate(deepEqual(['./', 'translate', 'MRK']), anything())).once();
> ```

Should it navigate? Maybe verify that navigate(..).never() if not ?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts, line 173 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1001#-MXYzOMZ9IuhtQPny_pa:-MXYzOMZ9IuhtQPny_pb:b-lc8hrs) ([raw file](https://github.com/sillsdev/web-xforge/blob/ebccac63ffe16caf4f642a701ca30769c1892f5e/src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts#L173)):*
> ```
> and user not on project'
> ```

I had to think about this for a bit to understand. Perhaps word it as "and redirect user if not on any project" ?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts, line 185 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1001#-MXZ6R_e0dqIpBsVQbw9:-MXZ6R_f9NKLzyCx8_yE:b-5zynr2) ([raw file](https://github.com/sillsdev/web-xforge/blob/ebccac63ffe16caf4f642a701ca30769c1892f5e/src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts#L185)):*
> ```XML
>     verify(mockedRouter.navigateByUrl('/projects', anything())).once();
>     expect().nothing();
>   }));
> ```

Can we specify what happens if the user clicks an invitation link, is offline, and _is_ already on the project (and their web browser knows it)? 

For example, if they are a member of project01 and project02, and  they are trying to go to project02 and sharing=true. The result should probably be that they land at the project02 page. It may be significant that project01 is first in their user's projects list because of the logic of start.component.ts.

Also, if a user clicks their invitation in their email each time they want to go do their work, should they get the dialog when they are offline? Or maybe they dialog should not be shown and they just sent to the project?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts, line 286 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1001#-MXZ-2Bo8iNInYL0sOGG:-MXZ-2Bo8iNInYL0sOGH:b-s5cnbr) ([raw file](https://github.com/sillsdev/web-xforge/blob/ebccac63ffe16caf4f642a701ca30769c1892f5e/src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts#L286)):*
> ```XML
>   ): void {
>     if (args.projectId != null) {
>       when(mockedActivatedRoute.params).thenReturn(of({ projectId: args.projectId }));
> ```

Good job figuring something out here :)
___
*[src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json, line 279 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1001#-MXZ4jErCImo4pARr_jO:-MXZ4jEs3AFS-3GoUQrO:b-d932bz) ([raw file](https://github.com/sillsdev/web-xforge/blob/ebccac63ffe16caf4f642a701ca30769c1892f5e/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json#L279)):*
> ```
> internet
> ```

Some users reading may think this is written incorrectly since it doesn't have a capital `I`.  But I won't here complain since the dictionary does say lower-case is growing in usage and is more predominant in UK.


<!-- Sent from Reviewable.io -->

2021-04-06 16:33 UTC, RaymondLuong3 reviewed
Thanks for the review. I've made the requested changes.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1001#-:-MXc0izn1vwLwAnoVA9r:b-40up16)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @marksvc)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts, line 42 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1001#-MXZ14eM0NJj7OIqYX8O:-MXc-tIr4VjQkwGPHc1W:b7ayb8o) ([raw file](https://github.com/sillsdev/web-xforge/blob/ebccac63ffe16caf4f642a701ca30769c1892f5e/src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts#L42)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
> .pipe
> ```
Isn't .pipe() for when you have a bunch of things to do? Here you just filter.
</blockquote></details>

I have been using pipe to chain together operations. In this case it is just the filter operation. I don't know if the `projectId$` observable has a built in filter operation so I just use pipe.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts, line 56 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1001#-MXZ7v4_C16fW6AA9Z2G:-MXc0QPBE4cw4EfK4RzR:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/55c203b59ad96dea77b1bd84a573f4c24038ebf8/src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts#L56)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
>   this.loadingFinished();
> ```
And later `this.loadingFinished();`, I think.
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts, line 139 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1001#-MXYyhNf8LrZdsCduS7G:-MXc0RK1BEdUhPCyw2Lj:b7k2y54) ([raw file](https://github.com/sillsdev/web-xforge/blob/c8a190a3be0eae7b3fe72921993687d416672921/src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts#L139)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Should it navigate? Maybe verify that navigate(..).never() if not ?
</blockquote></details>

Yes, it should navigate. I have included that spec now.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts, line 173 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1001#-MXYzOMZ9IuhtQPny_pa:-MXc0XRoCr-5N1RTpzgx:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/ebccac63ffe16caf4f642a701ca30769c1892f5e/src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts#L173)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
> and user not on project'
> ```

I had to think about this for a bit to understand. Perhaps word it as "and redirect user if not on any project" ?
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts, line 185 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1001#-MXZ6R_e0dqIpBsVQbw9:-MXc0_Q9BcCyjeDL3nJb:bkjaas9) ([raw file](https://github.com/sillsdev/web-xforge/blob/ebccac63ffe16caf4f642a701ca30769c1892f5e/src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts#L185)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Can we specify what happens if the user clicks an invitation link, is offline, and _is_ already on the project (and their web browser knows it)? 

For example, if they are a member of project01 and project02, and  they are trying to go to project02 and sharing=true. The result should probably be that they land at the project02 page. It may be significant that project01 is first in their user's projects list because of the logic of start.component.ts.

Also, if a user clicks their invitation in their email each time they want to go do their work, should they get the dialog when they are offline? Or maybe they dialog should not be shown and they just sent to the project?
</blockquote></details>

Good thinking. That is a much better experience for anybody who uses the link to get to the project each time.


<!-- Sent from Reviewable.io -->

2021-04-06 16:41 UTC, marksvc requested changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1001)* status: all files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts, line 84 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1001#-MXc1W564jPNiKtiWC0F:-MXc1W576zqUKmTmgWSn:b-9tnei0) ([raw file](https://github.com/sillsdev/web-xforge/blob/53a3cfe945cdf89f28c4b607880e2508fd6a7ed2/src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts#L84)):*
> ```
> .noticeService
> ```
The other occurrences just use `this.loadingFinished();`. Is there a reason to have `.noticeService` here?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts, line 188 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1001#-MXc2BjL5RgB5QfnRxT-:-MXc2BjL5RgB5QfnRxT0:bn87wke) ([raw file](https://github.com/sillsdev/web-xforge/blob/53a3cfe945cdf89f28c4b607880e2508fd6a7ed2/src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts#L188)):*
> ```XML
>   }));
> 
>   it('check sharing link directs user to project offline when user is already a member', fakeAsync(() => {
> ```

This is good. 
Because we have a preference for the first project in the list, I think it will be more useful to put this user on both project01 and project 02 (in that order), have them click an invitation link to project02, and assert that they end up at the project02 page.
If that sounds bizarre, I can explain more :) (It's basically because of start.component.ts's 
```ts
  } else if (site.projects.length > 0) {
    projectId = site.projects[0];
  }
```
)


<!-- Sent from Reviewable.io -->

2021-04-06 18:28 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1001)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @marksvc)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts, line 84 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1001#-MXc1W564jPNiKtiWC0F:-MXcQv3l8vCVPBvda7jF:b-m58icc) ([raw file](https://github.com/sillsdev/web-xforge/blob/53a3cfe945cdf89f28c4b607880e2508fd6a7ed2/src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts#L84)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
> .noticeService
> ```
The other occurrences just use `this.loadingFinished();`. Is there a reason to have `.noticeService` here?
</blockquote></details>

Ah yes, basically the same thing, but I'll stick to the convention.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts, line 188 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1001#-MXc2BjL5RgB5QfnRxT-:-MXcR4E33tuo5agJE26Y:b-bidsnx) ([raw file](https://github.com/sillsdev/web-xforge/blob/53a3cfe945cdf89f28c4b607880e2508fd6a7ed2/src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts#L188)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

This is good. 
Because we have a preference for the first project in the list, I think it will be more useful to put this user on both project01 and project 02 (in that order), have them click an invitation link to project02, and assert that they end up at the project02 page.
If that sounds bizarre, I can explain more :) (It's basically because of start.component.ts's 
```ts
  } else if (site.projects.length > 0) {
    projectId = site.projects[0];
  }
```
)
</blockquote></details>

Ok, now that there are two valid projects and we test that we specifically navigate to the second one.


<!-- Sent from Reviewable.io -->

2021-04-06 20:03 UTC, marksvc approved these changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1001)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts, line 188 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1001#-MXc2BjL5RgB5QfnRxT-:-MXcjX7W9ZiY_KMG38Ie:bv328r3) ([raw file](https://github.com/sillsdev/web-xforge/blob/53a3cfe945cdf89f28c4b607880e2508fd6a7ed2/src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts#L188)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Ok, now that there are two valid projects and we test that we specifically navigate to the second one.
</blockquote></details>

That's great; thank you.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts, line 152 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1001#-MXclXjB9ax6lOJz8TZA:-MXclXjB9ax6lOJz8TZB:bdw8qp3) ([raw file](https://github.com/sillsdev/web-xforge/blob/25935d788ea3f555b42fcb4e39c8852979f69765/src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts#L152)):*
> ```XML
> 
>     verify(mockedSFProjectService.onlineCheckLinkSharing('project01', 'secret123')).once();
>     verify(mockedRouter.navigate(deepEqual(['projects', 'project01', 'translate', 'MAT']), anything())).once();
> ```

Hey, what's with this change? I didn't see/understand elsewhere in the patch why this would start to be different.


<!-- Sent from Reviewable.io -->

2021-04-06 20:12 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1001)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts, line 152 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1001#-MXclXjB9ax6lOJz8TZA:-MXcni7b8QChSty6Wpcs:b-spu9wa) ([raw file](https://github.com/sillsdev/web-xforge/blob/25935d788ea3f555b42fcb4e39c8852979f69765/src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts#L152)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Hey, what's with this change? I didn't see/understand elsewhere in the patch why this would start to be different.
</blockquote></details>

Initially the setup wasn't right (with a defined projectUserConfig before the user was on the project). So to better mimic what actually happens, the user config isn't set initially, and this meant that I had to tweak the navigation, which defaults to the translate app if a selected task is not set.


<!-- Sent from Reviewable.io -->

2021-04-06 21:11 UTC, Nateowami reviewed
@marksvc Is this ready to merge?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1001#-:-MXd0_BOASSIAjLMYng0:bpp7oor)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc)



<!-- Sent from Reviewable.io -->

2021-04-06 22:00 UTC, marksvc approved these changes
Yes. Good to go. Hmm; because it refactors project component ngOnInit, Raymond do you think it would be just as well to merge it to develop rather than to master? 

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1001#-:-MXdBL2L-ypCuOoTmmiO:b77pe2p)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2021-04-07 18:11 UTC, Nateowami reviewed
@marksvc It's fixing an issue that is present on master, right? I don't think I follow the reasoning for merging to develop instead. Is it because of possible unintended consequences/regressions due to the refactoring? (If so, perhaps I should review it closely and test it).

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1001#-:-MXhUdzR7bghZsBBIMJQ:b-tpasvw)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2021-04-07 19:22 UTC, RaymondLuong3 reviewed
I plan on merging it to master as soon as the beta migration things go through. There is at least one other PR approved (SF-1201) that will be merged then.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1001#-:-MXhlfnnErEVt-VjCBjj:bj6b9i2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2021-04-08 16:47 UTC, marksvc commented
> @marksvc It's fixing an issue that is present on master, right? I don't think I follow the reasoning for merging to develop instead. Is it because of possible unintended consequences/regressions due to the refactoring? (If so, perhaps I should review it closely and test it).

Nathaniel: Yes it fixes an issue that is on master. My reasoning is because of unforeseen regressions. I think it would be easier to just say it's not in the scope for the 3.4.0 release, and include it in the following release. Don't you think?

2021-04-23 22:26 UTC, Nateowami commented
@RaymondLuong3 If I'm not mistaken, I think this is now ready to merge?

2021-04-24 04:05 UTC, irahopkinson approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1001)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json, line 279 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1001#-MXZ4jErCImo4pARr_jO:-MZ122za3YjEhxJ8HvzK:b86iptv) ([raw file](https://github.com/sillsdev/web-xforge/blob/ebccac63ffe16caf4f642a701ca30769c1892f5e/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json#L279)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
> internet
> ```

Some users reading may think this is written incorrectly since it doesn't have a capital `I`.  But I won't here complain since the dictionary does say lower-case is growing in usage and is more predominant in UK.
</blockquote></details>

We only have one usage with capital and the other 2 usages are lower case.


<!-- Sent from Reviewable.io -->

2021-04-24 04:05 UTC, merged