SF-1219: Fix memory leaks
sillsdev/web-xforge pull request #1073
Opened 2021-06-21 05:28 UTC by pmachapman

This pull request should help reduce out of memory issues by fixing the following memory leaks:
 - The event handler for `ParatextSyncRunner.UseNewProgress()` was not being deregistered, resulting in the `ParatextSyncRunner`, the `Connection`, and any `Document` objects remaining in memory after sync. The GC can now dispose of these objects correctly when required (commit 006e4b3).
 - `ScrText` objects are now scoped to a sync action, resulting in the correct disposal of these objects and excessive `ScrText` objects no longer being created in memory (commit 3a1bf15).
 - The `RealtimeJsonService` now uses `JsonSerializer` instead of `JToken` to reduce memory use and object creation (commit 21899a6).

2021-06-21 20:18 UTC, marksvc requested changes
I reviewed two of the commits separately, which was nice for isolation in review; thank you. 

Thanks for your work on this. 

> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1073#-:-Mck8DGZ6w2XHrJ9Mmgk:be2c0dz)* status: all files reviewed, 10 unresolved discussions (waiting on @pmachapman)

___
*[src/SIL.XForge/Realtime/RealtimeJsonService.cs, line 40 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1073#-McjU9Xo2blT7fjgARwf:-McjU9Xp5330VM2szr88:b-2137yt) ([raw file](https://github.com/sillsdev/web-xforge/blob/006e4b31061979f8ccf386a4eb747cf6c759915d/src/SIL.XForge/Realtime/RealtimeJsonService.cs#L40)):*
> ```Smalltalk
>             using StreamWriter sw = new StreamWriter(stream, System.Text.Encoding.Default, 1024, true);
>             using JsonWriter writer = new JsonTextWriter(sw);
>             _serializer.Serialize(writer, value);
> ```

Yeah okay. @irahopkinson , is there a reason why (git log says) you  used JToken to read+write? I'm assuming not because it was doing something that .Deserialize and .Serialize weren't handling, and that this way is fine.
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 478 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1073#-MckA05J5OhxUTMw2Asm:-MckA05J5OhxUTMw2Asn:b-3pwlzn) ([raw file](https://github.com/sillsdev/web-xforge/blob/006e4b31061979f8ccf386a4eb747cf6c759915d/src/SIL.XForge.Scripture/Services/ParatextService.cs#L478)):*
> ```Smalltalk
>         /// <summary> Write up-to-date book text from mongo database to Paratext project folder. </summary>
>         public async Task PutBookText(UserSecret userSecret, string projectId, int bookNum, string usx,
>             IScrTextCollection scrTextCollection, Dictionary<int, string> chapterAuthors = null)
> ```

I don't like that `class ParatextService` is now pushing responsibility for maintaining a ScrTextCollection to the clients of ParatextService. A ScrText and a ScrTextCollection are Paratext classes* and it would be nice to contain them within the ParatextService. 

* Well, IScrTextCollection isn't technically, but it's trying to be like a Paratext class :). 

Hmm. But what to do. Maybe this would be good to talk about in our meeting.
___
*[src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, line 92 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1073#-Mck3CIJCOOkFK-iBG7s:-Mck3CIJCOOkFK-iBG7t:b-atf1la) ([raw file](https://github.com/sillsdev/web-xforge/blob/006e4b31061979f8ccf386a4eb747cf6c759915d/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L92)):*
> ```Smalltalk
>         public async Task RunAsync(string projectId, string userId, bool trainEngine)
>         {
>             using ScopedScrTextCollection scrTextCollection = new ScopedScrTextCollection(_fileSystemService);
> ```

It may be that every sync job makes a new ParatextSyncRunner object and then calls RunAsync() on it. Notice that there are _projectDoc and _projectSecret and _userSecret objects, so a given ParatextSyncRunner object is only operating on one project, as requested by one user, at a time. 

Because of this, you could put the scrTextCollection in a private class field rather than pass it around. 

An option if desired.
___
*[src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, line 166 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1073#-McjY2UR7SaCvvQAuoPF:-McjY2US60DKeG3o9KC-:b-9t4e8l) ([raw file](https://github.com/sillsdev/web-xforge/blob/006e4b31061979f8ccf386a4eb747cf6c759915d/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L166)):*
> ```Smalltalk
> 
>                 // Create the handler
>                 progress.ProgressUpdated += handler;
> ```

I assume that placing the code above inline here, rather than in the UseNewProgress() method, is helping with GC because when  the handler is removed from ProgressUpdated, and RunAsync() is finished,  the `handler` itself goes out of scope. Is that what's helping GC here?

It's too bad to inline this since ParatextSyncRunner has generally suffered from too-long methods. I wonder if there's a clever way to get  some GC-friendly functionality like this but keep this progress code out in its own method. We could modify UseNewProgress() so it was something like

```cs
void UseNewProgressWhlieRunning(lambda) 
{
  handler = new handler();
  progress += handler;
  try {
    lambda();
  }
  finally {
    progress -= handler;
  }
}
```

and then call it here with

```cs
UseNewProgressWhileRunning(() => {
  // perform Paratext send/receive
  await _paratextService.SendReceiveAsync(_userSecret, targetParatextId, scrTextCollection, progres
});
```

(with appropriate async/await sprinkled in).

This doesn't need to be done as part of the PR at hand. But do you have any thoughts about how to  avoid inlining UseNewProgress(), yet still have the GC benefit?
___
*[src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, line 172 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1073#-Mck5hhVCeTgM5QZxtix:-Mck5hhVCeTgM5QZxtiy:b-re0fhn) ([raw file](https://github.com/sillsdev/web-xforge/blob/006e4b31061979f8ccf386a4eb747cf6c759915d/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L172)):*
> ```Smalltalk
> 
>                 // Deregister the handler
>                 progress.ProgressUpdated -= handler;
> ```

Come to think of it, this isn't protected by a `finally`. And so when we  get a crash in SR, we will still be keeping these in memory. What do you think about doing the `-= handler`  down in `CompleteSync()`?

I suppose that would mean making at least `progress` into a field, if not also `handler` (tho we can probably iterate thru progress.ProgressUpdated and `-=` all its contents). 

I see that SyncProgress is ours. Maybe SyncProgress could be made to implement IDisposable, on dispose it could dump its ProgressUpdated handlers, and in ParatextSyncRunner we could `using progress = new SyncProgress();`. Then we wouldn't need to add `progress` or `handler` as class fields.

So, class SyncProgress could maybe have

```cs
public class SyncProgress ... 
{
  private _listOfListenersIfOtherwiseAPainToFigureOut = new List();
  public AddProgressUpdatedListener(listener) 
  {
    _listOfListeners += listener;
    ProgressUpdated += listener;
  }
  public override ManagedDispose()
  {
    ...
    for each listener in _listOfListeners
    {
      ProgressUpdated -= listener;
    }
  }
}
```
___
*[src/SIL.XForge.Scripture/Services/ScopedScrTextCollection.cs, line 15 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1073#-McjiAQM-ydD3yzVgwJm:-McjiAQN8U0qtrfuUdYk:b-co8nai) ([raw file](https://github.com/sillsdev/web-xforge/blob/006e4b31061979f8ccf386a4eb747cf6c759915d/src/SIL.XForge.Scripture/Services/ScopedScrTextCollection.cs#L15)):*
> ```
>  using a simple cache.
> ```

Irony. So it might be good to add some more info to maintain a bit of knowledge about what is going on here. 

IIRC: 

The LazyScrTextCollection allowed us to specify our own FindById() method that would fetch a ScrText _for a specific user_, to help us in the multi-user environment. Probably the Paratext ScrTextCollection.FindById() was fetching a ScrText, caching it, and then different users in SF who tried to fetch a ScrText for the same project would then get the same ScrText but now they are using a ScrText that doesn't have the right understanding of _who_ is using it. So writing, as the old class comment said, "A class that can be used to get a ScrText without using a cache" had let us provide ScrText objects that were for a specific user, as they weren't grabbed from a cached that had made them with respect to the wrong user.  (A brief glance at ScrText.cs makes me wonder if that's the right explanation tho :). 
The _cache_ isn't so much the problem, as trouble when multi-users use the same cached objects. 

Let's record some of this into the class comment. Perhaps we could use a class comment like the following:

> A class prov [...]

2021-06-21 22:17 UTC, pmachapman reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1073)* status: 11 of 13 files reviewed, 10 unresolved discussions (waiting on @marksvc and @pmachapman)

___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 478 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1073#-MckA05J5OhxUTMw2Asm:-MckQdPiDthjq2tq1SA2:bble3ee) ([raw file](https://github.com/sillsdev/web-xforge/blob/006e4b31061979f8ccf386a4eb747cf6c759915d/src/SIL.XForge.Scripture/Services/ParatextService.cs#L478)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I don't like that `class ParatextService` is now pushing responsibility for maintaining a ScrTextCollection to the clients of ParatextService. A ScrText and a ScrTextCollection are Paratext classes* and it would be nice to contain them within the ParatextService. 

* Well, IScrTextCollection isn't technically, but it's trying to be like a Paratext class :). 

Hmm. But what to do. Maybe this would be good to talk about in our meeting.
</blockquote></details>

Yes, totally. The other option is to create/dispose the `ScrText` objects in each method that requires them. I tried this first off the bat, and it worked...mostly...some methods passed on parts of the object that were lost when the dispose was hit, but I'm sure I can sort this out properly if that is the way we want to go.

Using the `ScopedScrTextCollection` and effectively passing around the same `ScrText` object only saved a couple of seconds for the entire execution time.
___
*[src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, line 92 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1073#-Mck3CIJCOOkFK-iBG7s:-MckRE7G8aF1cbqIhb2F:bpd4xkt) ([raw file](https://github.com/sillsdev/web-xforge/blob/006e4b31061979f8ccf386a4eb747cf6c759915d/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L92)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

It may be that every sync job makes a new ParatextSyncRunner object and then calls RunAsync() on it. Notice that there are _projectDoc and _projectSecret and _userSecret objects, so a given ParatextSyncRunner object is only operating on one project, as requested by one user, at a time. 

Because of this, you could put the scrTextCollection in a private class field rather than pass it around. 

An option if desired.


</blockquote></details>

Yes, that is more logical, especially since the permissions code moved to `SFProjectService` creates its own `ScopedScrTextCollection` there. If we choose to keep the `ScopedScrTextCollection`, I'll do that.
___
*[src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, line 166 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1073#-McjY2UR7SaCvvQAuoPF:-MckRWr7Djbzl_TbauD1:bk543e) ([raw file](https://github.com/sillsdev/web-xforge/blob/006e4b31061979f8ccf386a4eb747cf6c759915d/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L166)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I assume that placing the code above inline here, rather than in the UseNewProgress() method, is helping with GC because when  the handler is removed from ProgressUpdated, and RunAsync() is finished,  the `handler` itself goes out of scope. Is that what's helping GC here?

It's too bad to inline this since ParatextSyncRunner has generally suffered from too-long methods. I wonder if there's a clever way to get  some GC-friendly functionality like this but keep this progress code out in its own method. We could modify UseNewProgress() so it was something like

```cs
void UseNewProgressWhlieRunning(lambda) 
{
  handler = new handler();
  progress += handler;
  try {
    lambda();
  }
  finally {
    progress -= handler;
  }
}
```

and then call it here with

```cs
UseNewProgressWhileRunning(() => {
  // perform Paratext send/receive
  await _paratextService.SendReceiveAsync(_userSecret, targetParatextId, scrTextCollection, progres
});
```

(with appropriate async/await sprinkled in).

This doesn't need to be done as part of the PR at hand. But do you have any thoughts about how to  avoid inlining UseNewProgress(), yet still have the GC benefit?

</blockquote></details>

I've cleaned it up a bit, but haven't gone with the IDisposable pattern you mentioned below, as everything stayed in memory (even with appropriate dereferencing) when I implemented it.
___
*[src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, line 172 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1073#-Mck5hhVCeTgM5QZxtix:-MckRk-I1JRMYhDxFVIl:b30pqgs) ([raw file](https://github.com/sillsdev/web-xforge/blob/006e4b31061979f8ccf386a4eb747cf6c759915d/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L172)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Come to think of it, this isn't protected by a `finally`. And so when we  get a crash in SR, we will still be keeping these in memory. What do you think about doing the `-= handler`  down in `CompleteSync()`?

I suppose that would mean making at least `progress` into a field, if not also `handler` (tho we can probably iterate thru progress.ProgressUpdated and `-=` all its contents). 

I see that SyncProgress is ours. Maybe SyncProgress could be made to implement IDisposable, on dispose it could dump its ProgressUpdated handlers, and in ParatextSyncRunner we could `using progress = new SyncProgress();`. Then we wouldn't need to add `progress` or `handler` as class fields.

So, class SyncProgress could maybe have

```cs
public class SyncProgress ... 
{
  private _listOfListenersIfOtherwiseAPainToFigureOut = new List();
  public AddProgressUpdatedListener(listener) 
  {
    _listOfListeners += listener;
    ProgressUpdated += listener;
  }
  public override ManagedDispose()
  {
    ...
    for each listener in _listOfListeners
    {
      ProgressUpdated -= listener;
    }
  }
}
```
</blockquote></details>

Yes, I remembered last night while try to sleep that I forgot the finally... :-)

The `IDisposable` pattern still kept all of the objects in memory, so I have just gone with the try/finally pattern, but cleaned it up a bit.
___
*[src/SIL.XForge.Scripture/Services/ScopedScrTextCollection.cs, line 15 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1073#-McjiAQM-ydD3yzVgwJm:-MckUvnT02wPzDRcbV9t:b-rofdzz) ([raw file](https://github.com/sillsdev/web-xforge/blob/006e4b31061979f8ccf386a4eb747cf6c759915d/src/SIL.XForge.Scripture/Services/ScopedScrTextCollection.cs#L15)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
>  using a simple cache.
> ```

Irony. So it might be good to add some more info to maintain a bit of knowledge about what is going on here. 

IIRC: 

The LazyScrTextCollection allowed us to specify our own FindById() method that would fetch a ScrText _for a specific user_, to help us in the multi-user environment. Probably the Paratext ScrTextCollection.FindById() was fetching a ScrText, caching it, and then different users in SF who tried to fetch a ScrText for the same project would then get the same ScrText but now they are using a ScrText that doesn't have the right understanding of _who_ is using it. So writing, as the old class comment said, "A class that can be used to get a ScrText without using a cache" had let us provide ScrText objects that were for a specific user, as they weren't grabbed from a cached that had made them with respect to the wrong user.  (A brief glance at ScrText.cs makes me wonder if that's the right explanation tho :). 
The _cache_ isn't so much the problem, as trouble when multi-users use the same cached objects. 

Let's record some of this into the class comment. Perhaps we could use a class comment like the following:

> A class providing a multi-user-capable replacement for some of ParatextData.ScrTextCollection, specifically FindById(), which does not allow specifying which user to associate with the ScrText and is not for use in a multi- [...]

2021-06-21 22:54 UTC, marksvc reviewed
Thanks for your work on this. So basically I approve, except for some API reservations regarding ParatextService. 

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1073#-:-McklrJ04jhD_87Hi2hY:bo949l6)* status: all files reviewed, 2 unresolved discussions (waiting on @pmachapman)

___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 478 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1073#-MckA05J5OhxUTMw2Asm:-Mcklm7p4KVU_vOTnecR:b-xiegov) ([raw file](https://github.com/sillsdev/web-xforge/blob/006e4b31061979f8ccf386a4eb747cf6c759915d/src/SIL.XForge.Scripture/Services/ParatextService.cs#L478)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Yes, totally. The other option is to create/dispose the `ScrText` objects in each method that requires them. I tried this first off the bat, and it worked...mostly...some methods passed on parts of the object that were lost when the dispose was hit, but I'm sure I can sort this out properly if that is the way we want to go.

Using the `ScopedScrTextCollection` and effectively passing around the same `ScrText` object only saved a couple of seconds for the entire execution time.
</blockquote></details>

Hm, ok. Yeah let's talk more about it. 
___
*[src/SIL.XForge.Scripture/Services/ScopedScrTextCollection.cs, line 15 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1073#-McjiAQM-ydD3yzVgwJm:-MckhunZ-CTQOmnMq9W5:b-mkphzh) ([raw file](https://github.com/sillsdev/web-xforge/blob/006e4b31061979f8ccf386a4eb747cf6c759915d/src/SIL.XForge.Scripture/Services/ScopedScrTextCollection.cs#L15)):*
> It is meant to mean that the ScrText objects are scoped to the lifetime of this class.
> ...
> It is meant to avoid the issues that Paratext's ScrTextCellection has by instead of scoping to app lifetime via a static, we can scope them to a service action (i.e. syncing or updating permissions).

Ahh, right. 
Hmm. "ShortLivedScrTextCollection"? "EphemeralScrTextCollection"?
I don't think the class name actually needs to reveal that it's not expected to hang around for the life of the application run*. If we just used the equivalent of calling it "ScrTextCollection", then it's a collection of ScrTexts, and we construct it, use it, and maybe destroy it, in which case another ScrTextCollection that is later constructed isn't going to have all of the ScrText objects in it. 

`*` Although I guess if ScrTextCollection is the name of something in ParatextData that _is_ expected to hang around for the life of the application, it could be confusing if our similarly named one isn't. 


> I didn't do this per user, as the code for pushing chapters to Paratext will sudo as another user if required, hence why the collection has the user id.

So, the dictionary is keyed in part by user ID. And when we construct a ScrText we specify the user to associate it with, to ParatextData. I'm not sure I understand what you mean.



The class comment looks good. 


<!-- Sent from Reviewable.io -->

2021-06-26 02:40 UTC, pmachapman reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1073)* status: 1 of 15 files reviewed, 2 unresolved discussions (waiting on @marksvc and @pmachapman)

___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 478 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1073#-MckA05J5OhxUTMw2Asm:-Md59nkQ7kQP-vFXyfO0:b-y204fx) ([raw file](https://github.com/sillsdev/web-xforge/blob/006e4b31061979f8ccf386a4eb747cf6c759915d/src/SIL.XForge.Scripture/Services/ParatextService.cs#L478)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Hm, ok. Yeah let's talk more about it. 
</blockquote></details>

Making the `ParatextService` a scoped service failed quite badly due to how initialisation and how it interacts with the file system. I couldn't get it working without a really drastic and inefficient refactor.

So, I have wrapped the `ScrText`'s in using statements, and updated the unit tests to handle this. As the `ScrText` is not passed outside of the `ParatextService` (with the exception of one minor helper service), it works well. Although it doesn't have the object reuse of `ScopedScrTextCollection`, it is no more inefficient that the current implementation.


<!-- Sent from Reviewable.io -->

2021-06-29 22:58 UTC, marksvc requested changes
I am posting my comments so far. 

> Reviewed 1 of 14 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1073#-:-MdOzaYS0leAoXNjDvSg:b-ftbv3h)* status: 2 of 15 files reviewed, 3 unresolved discussions (waiting on @marksvc and @pmachapman)

___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 478 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1073#-MckA05J5OhxUTMw2Asm:-MdOvtES9HRYve7yF5MW:b-9hpahz) ([raw file](https://github.com/sillsdev/web-xforge/blob/006e4b31061979f8ccf386a4eb747cf6c759915d/src/SIL.XForge.Scripture/Services/ParatextService.cs#L478)):*
And I see that previously we observed that 

> The other option is to create/dispose the ScrText objects in each method that requires them. I tried this first off the bat, and it worked...mostly...some methods passed on parts of the object that were lost when the dispose was hit, but I'm sure I can sort this out properly if that is the way we want to go.

Is this something we need to look into more?
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 489 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1073#-MdOwwZx2oMh3hb67Vj7:-MdOwwZx2oMh3hb67Vj8:bd79m9q) ([raw file](https://github.com/sillsdev/web-xforge/blob/6d2f1385138df1dc7ad4a8d9341b9ef35d2e4689/src/SIL.XForge.Scripture/Services/ParatextService.cs#L489)):*
> ```Smalltalk
> 
>                 // We add this here so we can dispose in the finally
>                 scrTexts.Add(userSecret.Id, scrText);
> ```

So, this makes _sure_ that the scrText is in the dictionary, for us to dispose of it later, right. 
userSecret.Id might not exist in chapterAuthors, I would think, and so we might not do this Add() with the current/older code.
It looks like later lines in the method then consider cases of whether scrTexts.Count == 1 or not, which this would influence. 
I need to send my comments-in-progress now without more time to think more about what's happening here or if that's a problem.


<!-- Sent from Reviewable.io -->

2021-06-29 23:29 UTC, pmachapman reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1073)* status: 1 of 15 files reviewed, 3 unresolved discussions (waiting on @marksvc and @pmachapman)

___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 478 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1073#-MckA05J5OhxUTMw2Asm:-MdP-FNr3O3_V6oP5AhP:bxnrnhl) ([raw file](https://github.com/sillsdev/web-xforge/blob/006e4b31061979f8ccf386a4eb747cf6c759915d/src/SIL.XForge.Scripture/Services/ParatextService.cs#L478)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

And I see that previously we observed that 

> The other option is to create/dispose the ScrText objects in each method that requires them. I tried this first off the bat, and it worked...mostly...some methods passed on parts of the object that were lost when the dispose was hit, but I'm sure I can sort this out properly if that is the way we want to go.

Is this something we need to look into more?
</blockquote></details>

No - I dug into it, and my problems were solely with the unit tests - I have sorted out the unit tests to function correctly.

I fixed the broken tests by keeping the FileManager in the scope of the test, and implementing the ComparableProjectPermissionManager to provide the permission object comparison (rather than the simple object reference comparison that was used previously).
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 489 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1073#-MdOwwZx2oMh3hb67Vj7:-MdP1rpVDsTcJ3EJhGEC:b-qoxqcr) ([raw file](https://github.com/sillsdev/web-xforge/blob/6d2f1385138df1dc7ad4a8d9341b9ef35d2e4689/src/SIL.XForge.Scripture/Services/ParatextService.cs#L489)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

So, this makes _sure_ that the scrText is in the dictionary, for us to dispose of it later, right. 
userSecret.Id might not exist in chapterAuthors, I would think, and so we might not do this Add() with the current/older code.
It looks like later lines in the method then consider cases of whether scrTexts.Count == 1 or not, which this would influence. 
I need to send my comments-in-progress now without more time to think more about what's happening here or if that's a problem.
</blockquote></details>

I sought to minimize the number of changes to the existing logic as far as possible - the line right after - `UsxFragmenter.FindFragments(scrText.ScrStylesheet(bookNum)` - will cause a crash (which my sync rollback code will sort out), if the ScrText was null, so I don't think it is an issue currently.

That said....I've just added a null check in the finally, as no one likes exceptions in finally blocks.

I haven't added null checks when adding the ScrText objects to the collection as these should not be null, and if they are something is really wrong, so a crash (which the sync-rollback will sort out) is appropriate, and this is what would currently happen in this scenario.

Let me know if you are happy with this, or if I should be a bit heavier with my refactor and include more null checks.


<!-- Sent from Reviewable.io -->

2021-07-02 16:48 UTC, marksvc approved these changes
Thanks for your work on this. I approve. :ship: 

I compiled the code and smoke tested connecting a project, looking at text docs, looking at Settings, and Synchronizing a project.

> Reviewed 12 of 14 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1073#-:-Mdc6OoWCxvMxF4BfYoU:b-wa9tk6)* status: all files reviewed, 2 unresolved discussions (waiting on @pmachapman)

___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 489 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1073#-MdOwwZx2oMh3hb67Vj7:-Mdbw1SxACRYUhb4ZunD:b-64x7gj) ([raw file](https://github.com/sillsdev/web-xforge/blob/6d2f1385138df1dc7ad4a8d9341b9ef35d2e4689/src/SIL.XForge.Scripture/Services/ParatextService.cs#L489)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

I sought to minimize the number of changes to the existing logic as far as possible - the line right after - `UsxFragmenter.FindFragments(scrText.ScrStylesheet(bookNum)` - will cause a crash (which my sync rollback code will sort out), if the ScrText was null, so I don't think it is an issue currently.

That said....I've just added a null check in the finally, as no one likes exceptions in finally blocks.

I haven't added null checks when adding the ScrText objects to the collection as these should not be null, and if they are something is really wrong, so a crash (which the sync-rollback will sort out) is appropriate, and this is what would currently happen in this scenario.

Let me know if you are happy with this, or if I should be a bit heavier with my refactor and include more null checks.
</blockquote></details>

Sorry; my concern isn't about scrText being null. Rather, in the old code, we conditionally add scrText to scrTexts, below with

```cs
                Dictionary<string, ScrText> scrTexts = new Dictionary<string, ScrText>();
                foreach (string userId in chapterAuthors.Values.Distinct())
                {
                    if (userId == userSecret.Id)
                    {
                        scrTexts.Add(userId, scrText);
                    }
                    else
                    {
```

But now we _unconditionally_ add scrText to scrTexts in the line above:

```cs
scrTexts.Add(userSecret.Id, scrText);
```

It looks like this would only have a change of how the execution flowed if...
- `chapterAuthors` is not null.
- userSecret.Id is not in chapterAuthors.Values.

And so the scrTexts.Count would be 2 now instead of 1 in that case. And it looks like the only impact is that now instead of writing out the whole book text in that case with 

```cs
                    if (scrTexts.Count == 1)
                    {
                        scrTexts.Values.First().PutText(bookNum, 0, false, usfm, null);
```

we would instead write out each chapter individually, as the single author, with

```cs
                        // Put the individual chapters
                        foreach ((int chapterNum, string authorUserId) in chapterAuthors)
                        {
                            if ((chapterNum - 1) < chapters.Count)
                            {
                                // The ScrText permissions will be the same as the last sync's permissions, so no need to check
                                scrTexts[authorUserId].PutText(bookNum, chapterNum, false, chapters[chapterNum - 1], null);
```

So I guess that's not actually a problem. 

Ok.
___
*[test/SIL.XForge.Scripture.Tests/Services/ComparableProjectPermissionManager.cs, line 27 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1073#-Mdc3Rn_9j1ZDNwyArYw:-Mdc3Rn_9j1ZDNwyArYx:b-2dwrwh) ([raw file](https://github.com/sillsdev/web-xforge/blob/0caa1c8dcd2dff7122b4f8a822bf8d71369520a4/test/SIL.XForge.Scripture.Tests/Services/ComparableProjectPermissionManager.cs#L27)):*
> ```Smalltalk
>         /// This is based on the code for <see cref="PermissionManager.Clone" />.
>         /// </remarks>
>         public string XmlData => Memento.ToXmlString(Data, false, true);
> ```

Nice. Would it be good for this to be `private` , since it's a helper to facilitate Equals(), rather than something we expect clients to call?


<!-- Sent from Reviewable.io -->

2021-07-02 21:22 UTC, pmachapman reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1073)* status: 14 of 15 files reviewed, 2 unresolved discussions (waiting on @marksvc and @pmachapman)

___
*[test/SIL.XForge.Scripture.Tests/Services/ComparableProjectPermissionManager.cs, line 27 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1073#-Mdc3Rn_9j1ZDNwyArYw:-Mdd5Dho586GrYfIYP-I:b-fc35fl) ([raw file](https://github.com/sillsdev/web-xforge/blob/0caa1c8dcd2dff7122b4f8a822bf8d71369520a4/test/SIL.XForge.Scripture.Tests/Services/ComparableProjectPermissionManager.cs#L27)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Nice. Would it be good for this to be `private` , since it's a helper to facilitate Equals(), rather than something we expect clients to call?
</blockquote></details>

Have made it private - apologies for that slipping through - it was a hangover from a previous attempted solution where I used a separate IComparer.


<!-- Sent from Reviewable.io -->

2021-07-02 22:21 UTC, marksvc approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1073)* status: all files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[test/SIL.XForge.Scripture.Tests/Services/ComparableProjectPermissionManager.cs, line 27 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1073#-Mdc3Rn_9j1ZDNwyArYw:-MddImGB5dxAIe8H9FUq:b-s1agie) ([raw file](https://github.com/sillsdev/web-xforge/blob/0caa1c8dcd2dff7122b4f8a822bf8d71369520a4/test/SIL.XForge.Scripture.Tests/Services/ComparableProjectPermissionManager.cs#L27)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Have made it private - apologies for that slipping through - it was a hangover from a previous attempted solution where I used a separate IComparer.
</blockquote></details>

No worries :)


<!-- Sent from Reviewable.io -->

2021-07-07 03:56 UTC, irahopkinson reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1073)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

___
*[src/SIL.XForge/Realtime/RealtimeJsonService.cs, line 40 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1073#-McjU9Xo2blT7fjgARwf:-Mdz5yIFDAOfMziT7UBS:bomt8cv) ([raw file](https://github.com/sillsdev/web-xforge/blob/006e4b31061979f8ccf386a4eb747cf6c759915d/src/SIL.XForge/Realtime/RealtimeJsonService.cs#L40)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Yeah okay. @irahopkinson , is there a reason why (git log says) you  used JToken to read+write? I'm assuming not because it was doing something that .Deserialize and .Serialize weren't handling, and that this way is fine.
</blockquote></details>

No reason that I recall.


<!-- Sent from Reviewable.io -->

2021-07-07 03:56 UTC, merged