SF-1357: Translators can now sync
sillsdev/web-xforge pull request #1082
Opened 2021-07-05 00:27 UTC by pmachapman

This pull request adds support for translators who are not administrators to sync.

As well as the UI change, the primary change reads the id of the last user to modify a chapter from MongoDB, and uses that user to synchronize the chapter they edited from SF to the local Paratext repo. This means that the correct permissions are employed, as the `ScrText` is used, utilizing the permission user who made the modification rather than the user who is performing the synchronization.

2021-07-07 06:50 UTC, ddaspit requested changes
> Reviewed 15 of 15 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1082)* status: all files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, line 425 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1082#-MdzgSS9EI9t3rj3v7aQ:-MdzgSS9EI9t3rj3v7aR:b-6yocqt) ([raw file](https://github.com/sillsdev/web-xforge/blob/f41583a82b75e4b86f0e5ae8eeeaa3b035d7a5f9/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L425)):*
> ```Smalltalk
>                     // The Id is the value from TextData.GetTextDocId()
>                     string textId = textDoc.Id;
>                     userId = await _realtimeService.GetLastModifiedUserIdAsync<TextData>(textId);
> ```

Because we are retrieving the user that last modified the document after retrieving the document snapshot, it is possible that we will get the wrong user. This can happen if a document is modified in between fetching the snapshot and getting the user. If we pass in the version of the snapshot to `GetLastModifiedUserIdAsync`, then we can query for the user that last modified the document up to the specified version.


<!-- Sent from Reviewable.io -->

2021-07-07 14:15 UTC, irahopkinson requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1082)* status: all files reviewed, 3 unresolved discussions (waiting on @pmachapman)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html, line 238 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1082#-Me0GwALDcd_RLQw_E0f:-Me0GwALDcd_RLQw_E0g:bijwx03) ([raw file](https://github.com/sillsdev/web-xforge/blob/44de1a549f20be12e1bc9f2f007881704ea3d763/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html#L238)):*
> ```
> isProjectTranslator$
> ```
This is not something I would expect you to know but we are moving away from using roles directly in HMTL but to using permissions instead so this should be renamed `canSync$`. Its totally fine that in the TS its implemented by checking the *Translator* role. That way we can change the implementation as needed knowing what permission we are granting.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html, line 249 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1082#-Me0Id_i2rsXoc8uftiI:-Me0Id_i2rsXoc8uftiJ:b-55mnda) ([raw file](https://github.com/sillsdev/web-xforge/blob/44de1a549f20be12e1bc9f2f007881704ea3d763/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html#L249)):*
> ```
> isProjectAdmin$
> ```
As above this should be split into `canSeeSettings$` and `canSeeUsers$` even though its implemented in TS by checking they are an *Administrator*.


<!-- Sent from Reviewable.io -->

2021-07-08 02:25 UTC, pmachapman reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1082)* status: 5 of 16 files reviewed, 3 unresolved discussions (waiting on @ddaspit and @irahopkinson)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html, line 238 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1082#-Me0GwALDcd_RLQw_E0f:-Me2lR0y15QxXCotVkNr:b7ry8a) ([raw file](https://github.com/sillsdev/web-xforge/blob/44de1a549f20be12e1bc9f2f007881704ea3d763/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html#L238)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> isProjectTranslator$
> ```
This is not something I would expect you to know but we are moving away from using roles directly in HMTL but to using permissions instead so this should be renamed `canSync$`. Its totally fine that in the TS its implemented by checking the *Translator* role. That way we can change the implementation as needed knowing what permission we are granting.
</blockquote></details>

No problem - makes sense going forward.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html, line 249 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1082#-Me0Id_i2rsXoc8uftiI:-Me2lKZHAHC0ye11CaQE:btnlvtl) ([raw file](https://github.com/sillsdev/web-xforge/blob/44de1a549f20be12e1bc9f2f007881704ea3d763/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html#L249)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> isProjectAdmin$
> ```
As above this should be split into `canSeeSettings$` and `canSeeUsers$` even though its implemented in TS by checking they are an *Administrator*.
</blockquote></details>

Sounds great - I have done this, and split the auth guards with it too.
___
*[src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, line 425 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1082#-MdzgSS9EI9t3rj3v7aQ:-Me2lVZp8b3ly9ZPQlk9:b-7str7z) ([raw file](https://github.com/sillsdev/web-xforge/blob/f41583a82b75e4b86f0e5ae8eeeaa3b035d7a5f9/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L425)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Because we are retrieving the user that last modified the document after retrieving the document snapshot, it is possible that we will get the wrong user. This can happen if a document is modified in between fetching the snapshot and getting the user. If we pass in the version of the snapshot to `GetLastModifiedUserIdAsync`, then we can query for the user that last modified the document up to the specified version.
</blockquote></details>

I have added that parameter - the only weird thing I have noticed is that the latest snapshot version is always one more than the document version in MongoDB.


<!-- Sent from Reviewable.io -->

2021-07-09 08:47 UTC, ddaspit approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 11 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1082#-:-Me9R9O9EPLoS6y2jXxe:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)



<!-- Sent from Reviewable.io -->

2021-07-09 09:41 UTC, irahopkinson approved these changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1082)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)



<!-- Sent from Reviewable.io -->

2021-07-09 09:56 UTC, merged