SF-1322 Support multiple note thread in a segment
sillsdev/web-xforge pull request #1122
Opened 2021-08-10 22:32 UTC by RaymondLuong3

* remove the obselete note in line format from quill
* introduce note thread embed format to quill
* record embedded paratext note thread positions in text-view-model
* account for embedded note threads when sending ops to text doc
* account for note threads embedded into blank segments
* strip away note threads when switching texts

![image](https://user-images.githubusercontent.com/17931130/128943346-746027de-5939-4a30-9392-11473ca88adb.png)

2021-08-12 03:19 UTC, nigel-wells requested changes
Nice work - big effort to get this far. I can already see I'm going to have to refactor my two branches after reviewing this. 
Do you know if it all works fine when testing offline mode and then receiving changes to the text doc when coming back online i.e. will the notes move to their new positions?

> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1122#-:-MgsMQJ45YeT9Y6pIX87:b-d0nk95)* status: all files reviewed, 13 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts, line 41 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1122#-MgsAmQq7-TDzhvkXOkG:-MgsAmQq7-TDzhvkXOkH:bxc664d) ([raw file](https://github.com/sillsdev/web-xforge/blob/df9a5ab1f719b15460f1c89e04ac628d9e4b2657/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts#L41)):*
> ```XML
>   iconsrc: string;
>   preview: string;
>   embedid: string;
> ```

Do you think we should call this `threadId` as it refers to a thread rather than the embed which is just referring to the type of blot it is?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts, line 286 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1122#-MgsD0xn6qyM867D1TiA:-MgsD0xn6qyM867D1TiB:br8bsmf) ([raw file](https://github.com/sillsdev/web-xforge/blob/df9a5ab1f719b15460f1c89e04ac628d9e4b2657/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts#L286)):*
> ```
>       node.setAttribute('style', value.iconsrc);
>       node.setAttribute('title', value.preview);
>       node.setAttribute('embed-id', value.embedid);
> ```
Need to wrap the style key in `customAttributeName()` so that the get created as `data-` attributes
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts, line 469 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1122#-MgsEPtE4sf6lYtFgwRq:-MgsEPtE4sf6lYtFgwRr:b-s02isk) ([raw file](https://github.com/sillsdev/web-xforge/blob/df9a5ab1f719b15460f1c89e04ac628d9e4b2657/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L469)):*
> ```XML
>               const id = op.attributes != null && op.attributes['embedid'];
>               this._embeddedElements.set(id, curIndex + curSegment.length);
>               curSegment.notesCount = curSegment.notesCount + 1;
> ```

Can this be made `curSegment.notesCount++`
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts, line 545 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1122#-MgsFvy5AYd9BO5eXD6K:-MgsFvy5AYd9BO5eXD6L:b-k2hgga) ([raw file](https://github.com/sillsdev/web-xforge/blob/df9a5ab1f719b15460f1c89e04ac628d9e4b2657/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L545)):*
> ```XML
>         curIndex += cloneOp.retain;
>         let curNoteIndex = indices[embedTracker];
>         while (curNoteIndex <= curIndex) {
> ```

Could you use a for loop to iterate over the indices as then you don't need to keep track of the index.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts, line 547 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1122#-MgsFZZ19IEXe-xI53Nt:-MgsFZZ19IEXe-xI53Nu:bo4d6h0) ([raw file](https://github.com/sillsdev/web-xforge/blob/df9a5ab1f719b15460f1c89e04ac628d9e4b2657/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L547)):*
> ```XML
>         while (curNoteIndex <= curIndex) {
>           // remove this note from the retain op
>           cloneOp.retain -= 1;
> ```

Could be `cloneOp.retain--`
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 495 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1122#-MgsGmz-31Rs9jG1f0JX:-MgsGmz-31Rs9jG1f0JY:b81lblj) ([raw file](https://github.com/sillsdev/web-xforge/blob/df9a5ab1f719b15460f1c89e04ac628d9e4b2657/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L495)):*
> ```XML
>     let noteRange: RangeStatic | undefined = this.getSegmentRange(verseSegments[0]);
>     let startPosition = 0;
>     if (Array.from(this.viewModel.embeddedElements.keys()).includes(id)) {
> ```

Perhaps not for this PR but I believe Paratext will just keep stacking flags next to each other if there are multiple ones for the same position.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 711 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1122#-MgsIGOkCYQNDK4xd4VZ:-MgsIGOkCYQNDK4xd4V_:btyba75) ([raw file](https://github.com/sillsdev/web-xforge/blob/df9a5ab1f719b15460f1c89e04ac628d9e4b2657/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L711)):*
> ```XML
>         delta.ops[0].retain != null
>       ) {
>         if (delta.ops[1].insert['note-thread-embed'] != null) {
> ```

Any reason this if statement isn't part of the previous statements?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 714 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1122#-MgsIM_dBTv08hcx579b:-MgsIM_dBTv08hcx579c:bd4foy1) ([raw file](https://github.com/sillsdev/web-xforge/blob/df9a5ab1f719b15460f1c89e04ac628d9e4b2657/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L714)):*
> ```
>           // Embedding notes into quill makes quill emit deltas when it registers that content has changed
>           // but quill incorrectly interprets the change when the selection is within the updated segment.
>           // Content coming after the selection gets moved before the selection. This moves the selection back.
> ```
Assume this all relates to dealing with blank segments?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 825 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1122#-MgsJWATEr4x0UeV8WsN:-MgsJWATEr4x0UeV8WsO:b-6ilcj) ([raw file](https://github.com/sillsdev/web-xforge/blob/df9a5ab1f719b15460f1c89e04ac628d9e4b2657/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L825)):*
> ```XML
>     if (this._segment.text === '') {
>       // always select at the end of blank so the cursor is inside the segment and not between the segment and verse
>       const notesCount = this._segment.range.length - 1;
> ```

Make this a getter on `Segment`
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 618 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1122#-MgsKPHtBsQHH2gnUuy7:-MgsKPHtBsQHH2gnUuy8:b-j9f0tt) ([raw file](https://github.com/sillsdev/web-xforge/blob/df9a5ab1f719b15460f1c89e04ac628d9e4b2657/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L618)):*
> ```XML
>     );
> 
>     if (value) {
> ```

Could move in to the `if(value) {` below this
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 577 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1122#-MgsKuoI5qSuQFOnojnT:-MgsKuoI5qSuQFOnojnU:b6d3lbs) ([raw file](https://github.com/sillsdev/web-xforge/blob/df9a5ab1f719b15460f1c89e04ac628d9e4b2657/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L577)):*
> ```XML
>       expect(env.component.target!.segmentRef).toEqual('verse_1_1');
>       verify(env.mockedRemoteTranslationEngine.getWordGraph(anything())).once();
>       console.log(env.targetEditor.getSelection());
> ```

Can remove this log output
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 998 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1122#-MgsLLhHC-q3csFDS6_7:-MgsLLhHC-q3csFDS6_8:b-18xk9r) ([raw file](https://github.com/sillsdev/web-xforge/blob/df9a5ab1f719b15460f1c89e04ac628d9e4b2657/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L998)):*
> ```XML
>       const note  [...]

2021-08-16 20:19 UTC, RaymondLuong3 reviewed
This change so is responsible for getting multiple notes to appear within a segment. Improving where notes are anchored will be more work in SF-1327. As it currently is, if a note has selected text that cannot be found exactly in the verse segment, the note will default to the beginning of the segment.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1122#-:-MhFaVLsEoTWwVvAY-1X:bsosfwk)* status: all files reviewed, 13 unresolved discussions (waiting on @nigel-wells)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts, line 41 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1122#-MgsAmQq7-TDzhvkXOkG:-MhElPJa6ZB109tyBGmM:bq90ana) ([raw file](https://github.com/sillsdev/web-xforge/blob/df9a5ab1f719b15460f1c89e04ac628d9e4b2657/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts#L41)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Do you think we should call this `threadId` as it refers to a thread rather than the embed which is just referring to the type of blot it is?
</blockquote></details>

It would make sense to name it threadId since that is what it will be. I was being too ambitious in my generic naming.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts, line 286 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1122#-MgsD0xn6qyM867D1TiA:-MhF_ZoZ37cSTk_cWgKo:bcqtwsq) ([raw file](https://github.com/sillsdev/web-xforge/blob/df9a5ab1f719b15460f1c89e04ac628d9e4b2657/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts#L286)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

> ```
>       node.setAttribute('style', value.iconsrc);
>       node.setAttribute('title', value.preview);
>       node.setAttribute('embed-id', value.embedid);
> ```
Need to wrap the style key in `customAttributeName()` so that the get created as `data-` attributes
</blockquote></details>

Paratext notes technically aren't part of the usx structure. When I set the `style` attribute, I am really sneakily adding a css variable as a style on the node in the html. Then that css variable (--icon-file) can be accessible in the css. If I wrap the style key in `customAttributeName()` the styling is lost and notes are hidden. Could you clarify what you mean?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts, line 469 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1122#-MgsEPtE4sf6lYtFgwRq:-MhFbHr23lc3cRyhVdM-:b-pgbl7r) ([raw file](https://github.com/sillsdev/web-xforge/blob/df9a5ab1f719b15460f1c89e04ac628d9e4b2657/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L469)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Can this be made `curSegment.notesCount++`
</blockquote></details>

Yes it does work. Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts, line 545 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1122#-MgsFvy5AYd9BO5eXD6K:-MhFbKv78-FiAi_YvCX2:b409rpk) ([raw file](https://github.com/sillsdev/web-xforge/blob/df9a5ab1f719b15460f1c89e04ac628d9e4b2657/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L545)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Could you use a for loop to iterate over the indices as then you don't need to keep track of the index.
</blockquote></details>

I played around with the algorithm. I ended up with another way of adjusting the `modelOp`. It is no less complex, but I believe it is slightly clearer in its approach.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts, line 547 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1122#-MgsFZZ19IEXe-xI53Nt:-MhFbbsr9GHFKfQs6HY1:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/df9a5ab1f719b15460f1c89e04ac628d9e4b2657/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L547)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Could be `cloneOp.retain--`
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 495 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1122#-MgsGmz-31Rs9jG1f0JX:-MhF_GCdDLI9MSrZPWsC:b5nr61l) ([raw file](https://github.com/sillsdev/web-xforge/blob/df9a5ab1f719b15460f1c89e04ac628d9e4b2657/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L495)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Perhaps not for this PR but I believe Paratext will just keep stacking flags next to each other if there are multiple ones for the same position.
</blockquote></details>

You are correct in that we would see flags inserted side-by-side. As it stand side-by-side flags is working because each flag will have its own unique thread id.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 711 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1122#-MgsIGOkCYQNDK4xd4VZ:-MhEwxiU09RqnzaoO0qE:b-4nowv7) ([raw file](https://github.com/sillsdev/web-xforge/blob/df9a5ab1f719b15460f1c89e04ac628d9e4b2657/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L711)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Any reason this if statement isn't part of the previous statements?
</blockquote></details>

Nice catch. Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 714 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1122#-MgsIM_dBTv08hcx579b:-MhEx-gw0j0Bn2AO1q4k:bvd4jf5) ([raw file](https://github.com/sillsdev/web-xforge/blob/df9a5ab1f719b15460f1c89e04ac628d9e4b2657/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L714)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

> ```
>           // Embedding notes into quill makes quill emit deltas when it registers that content has changed
>           // but quill incorrectly interprets the change when the selection is within the updated segment.
>           // Content coming after the selection gets moved before the selection. This moves the selection back.
> ```
Assume this all relates to dealing with blank segments?
</blockquote></details>

It seems so. Inserting text or deleting text in a blank segment appears to get the quill editor confused even on master branch. Extra inserts ops are emitted with deletion ops. The data fortunately stays consistent this way, but the selection is not. I need to investigate further, so for now this is a work-a-round.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 825 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1122#-MgsJWATEr4x0UeV8WsN:-MhF09XnDutluc-yiZLg:b-pyv13u) ([raw file](https://github.com/sillsdev/web-xforge/blob/df9a5ab1f719b15460f1c89e04ac628d9e4b2657/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L825)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Make this a getter on `Segment`
</blockquote></details>

I've adjusted the code to be simpler.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 618 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1122#-MgsKPHtBsQHH2gnUuy7:-MhF0l7dEtEynhIMWmwM:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/df9a5ab1f719b15460f1c89e04ac628d9e4b2657/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L618)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Could move in to the `if(value) {` below this
</blockquote></detail [...]

2021-08-17 11:06 UTC, nigel-wells requested changes
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1122)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts, line 286 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1122#-MgsD0xn6qyM867D1TiA:-MhIky-97rVrTmgyl0Mj:b-ma9nxm) ([raw file](https://github.com/sillsdev/web-xforge/blob/df9a5ab1f719b15460f1c89e04ac628d9e4b2657/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts#L286)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Paratext notes technically aren't part of the usx structure. When I set the `style` attribute, I am really sneakily adding a css variable as a style on the node in the html. Then that css variable (--icon-file) can be accessible in the css. If I wrap the style key in `customAttributeName()` the styling is lost and notes are hidden. Could you clarify what you mean?
</blockquote></details>

Yes I guess `style` can remain as is as that is a valid attribute as well as `title` so long as it is used as an actual title and not just something to store information. It looks like you intended it as a title so it pops up the text on hover so that is fine. The `embed-id` is not a valid attribute though so it could be switched over to `node.setAttribute(customAttributeName('embed-id'), value);`. All that really does is sets the attribute name to `data-embed-id` which is then a valid attribute. You can then use `return node.getAttribute(customAttributeName('embed-id'));` to retrieve the value. Refer to `SegmentInline` as an example.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts, line 545 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1122#-MgsFvy5AYd9BO5eXD6K:-MhImQ2eDfXqnjy5PJHf:bjhzz8a) ([raw file](https://github.com/sillsdev/web-xforge/blob/df9a5ab1f719b15460f1c89e04ac628d9e4b2657/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L545)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I played around with the algorithm. I ended up with another way of adjusting the `modelOp`. It is no less complex, but I believe it is slightly clearer in its approach.
</blockquote></details>

Looks good thanks and the extra comments are helpful for understanding the why behind the code as well :)
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 495 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1122#-MgsGmz-31Rs9jG1f0JX:-MhIkLBp1V5gH4NWmdMO:btojbfd) ([raw file](https://github.com/sillsdev/web-xforge/blob/df9a5ab1f719b15460f1c89e04ac628d9e4b2657/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L495)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

You are correct in that we would see flags inserted side-by-side. As it stand side-by-side flags is working because each flag will have its own unique thread id.
</blockquote></details>

Great!


<!-- Sent from Reviewable.io -->

2021-08-17 20:45 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1122)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts, line 286 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1122#-MgsD0xn6qyM867D1TiA:-MhKqui_7C9bCOUsQ6kK:b8hc6em) ([raw file](https://github.com/sillsdev/web-xforge/blob/df9a5ab1f719b15460f1c89e04ac628d9e4b2657/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts#L286)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Yes I guess `style` can remain as is as that is a valid attribute as well as `title` so long as it is used as an actual title and not just something to store information. It looks like you intended it as a title so it pops up the text on hover so that is fine. The `embed-id` is not a valid attribute though so it could be switched over to `node.setAttribute(customAttributeName('embed-id'), value);`. All that really does is sets the attribute name to `data-embed-id` which is then a valid attribute. You can then use `return node.getAttribute(customAttributeName('embed-id'));` to retrieve the value. Refer to `SegmentInline` as an example.
</blockquote></details>

Ok, I see now. I had forgotten that the convention was to add `data-` to your attributes when they are custom. Thanks for catching that. Done.


<!-- Sent from Reviewable.io -->

2021-08-17 23:03 UTC, nigel-wells approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1122#-:-MhLLiLgA1I0OqfTT7Tf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2021-08-18 03:32 UTC, merged