SF-1327 Anchor notes in quill that mimics Paratext notes
sillsdev/web-xforge pull request #1128
Opened 2021-08-24 22:26 UTC by RaymondLuong3

* TODO: Get the ops from the paratext project to calculate
* the current context of a segment to place the note selection

2021-09-01 22:18 UTC, marksvc commented
:eyes:

2021-09-10 18:33 UTC, marksvc requested changes
Thanks for this. I have thoughts regarding naming, especially "CurrentContextSelection". I began reviewing and commenting on the C# files first, so if you start looking at my comments there it may make more sense than if you start with the TS files.

I would be happy to have discussion about the comments, and to work with you on any that will benefit from action. 

> Reviewed 6 of 15 files at r1, 6 of 10 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-:-MjB5H4PCbqf088lhxRX:b-unbwc3)* status: all files reviewed, 61 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/RealtimeServer/scriptureforge/models/sf-project-rights.ts, line 11 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-Mj5knRg369UFjrl5hHy:-Mj5knRg369UFjrl5hHz:bdmkg1j) ([raw file](https://github.com/sillsdev/web-xforge/blob/abdbbf95787b7082267852da5142071713a553bf/src/RealtimeServer/scriptureforge/models/sf-project-rights.ts#L11)):*
> ```
>   ParatextNoteThreads = 'note_threads',
>   Notes = 'notes'
> ```

So, my understanding is that a ParatextNoteThread is a set of Notes in SF that corresponds to a PT CommentThread (excluding "ANSWER_" items).
And that a Note is a Note in SF that corresponds to a PT Comment.
Is that accurate?

Why the `Paratext` in `ParatextNoteThreads`? What about `NoteThreads` instead?
___
*[src/RealtimeServer/scriptureforge/models/sf-project-rights.ts, line 64 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-Mj6-ID356nZJBDKbOLH:-Mj6-ID356nZJBDKbOLI:b1qx23c) ([raw file](https://github.com/sillsdev/web-xforge/blob/abdbbf95787b7082267852da5142071713a553bf/src/RealtimeServer/scriptureforge/models/sf-project-rights.ts#L64)):*
> ```XML
> 
>       { projectDomain: SFProjectDomain.ParatextNoteThreads, operation: Operation.Create },
>       { projectDomain: SFProjectDomain.ParatextNoteThreads, operation: Operation.Edit },
> ```

What would it mean to be able to edit a thread? I see that although a translator has the right to edit a thread, the only have the right to EditOwn notes. 
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/segment.ts, line 11 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-MjB43yX75XCfP6387yX:-MjB43yX75XCfP6387yY:b-qaxb8f) ([raw file](https://github.com/sillsdev/web-xforge/blob/abdbbf95787b7082267852da5142071713a553bf/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/segment.ts#L11)):*
> ```XML
>   private _checksum?: number;
>   private initialTextLen: number = -1;
>   private _embeddedElements: Map<string, number> = new Map<string, number>();
> ```

Unfortunately the type doesn't let us explain very well what the content is, so what do you think about having a comment saying : Mapping of treadId to position in editor.
   
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 59 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-MjB4OolC16VmN9yfVYx:-MjB4OolC16VmN9yfVYy:bn7njpv) ([raw file](https://github.com/sillsdev/web-xforge/blob/abdbbf95787b7082267852da5142071713a553bf/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L59)):*
> ```XML
> }
> 
> export interface FeaturedVerseRefInfo {
> ```

What is a "featured" verse ref info? One that we are drawing the user's attention to? Like the highlighted verses in the source that match what a user clicks in the target pane?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 63 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-MjB4Xr70EHNlpOZ0Dkr:-MjB4Xr70EHNlpOZ0Dks:b-5o6fih) ([raw file](https://github.com/sillsdev/web-xforge/blob/abdbbf95787b7082267852da5142071713a553bf/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L63)):*
> ```
> segmentSelection
> ```

So I think that here too we should use different naming, like `location` or `locationInSegment`. Although I'm a bit confused because I thought that verses contained segments, not the other way around. Maybe it is true that a segment can contain the end of one verse and the beginning of another, and so the segmentSelection here tells us where in a segment the verse begins?
Oh maybe a FeaturedVerseRefInfo refers to a range _within_ a verse to 'feature' to the user, and the segmentSelection defines that range? (Although we would need to know which segment the segmentSelection regards). 


   
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 334 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-Mj5Sf1r0q-lo_d84kaM:-Mj5Sf1r0q-lo_d84kaN:b38ccgm) ([raw file](https://github.com/sillsdev/web-xforge/blob/abdbbf95787b7082267852da5142071713a553bf/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L334)):*
> ```
>   // Useful for testing
>   get embeddedElements(): Readonly<Map<string, number>> {
> ```

It looks like this is used for more than just testing, so we could drop that comment. Also, let's say that the values are positions within the editor. Sometimes we have positions in a segment, and sometimes we have positions in the editor, so it can add clarity to say.

Perhaps

```ts
/**
 * Mapping of threadId to position in editor.
 */
get embeddedElementns...
```

Actually, because this just returns viewModel.embeddedElements, and because I think it needs this explanation _there_, then instead of putting that information here you could just write it there in text-view-model.ts. (Adding to the existing comment on the field there.).
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 488 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-Mj5VtEW0hMxBrypqFQr:-Mj5VtEX53yMbNr3DIPK:bx5lzr7) ([raw file](https://github.com/sillsdev/web-xforge/blob/abdbbf95787b7082267852da5142071713a553bf/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L488)):*
> ```
> embedElementInline(
> ```

I'm looking at what this method is doing and how it's called, to understand what it's purpose is. So far I've described it as "Embed part of a segment into the editor using the specified formatting.". Is that accurate? Oh  it _adds_ something to the editor, and another method is removing. I see it calls an `insertEmbed` method, so maybe it could be described as "Insert an embedded item, with the specified format, into the editor at position ___".
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 510 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-Mj5a4Or1p4GdfXTCZr0:-Mj5a4Or1p4GdfXTCZr1:bnxr5at) ([raw file](https://github.com/sillsdev/web-xforge/blob/abdbbf95787b7082267852da5142071713a553bf/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L510)):*
> ```XML
>     for (const vs of verseSegments) {
>       const range: RangeStatic | undefined = this.getSegmentRange(vs);
>       if (range != null) {
> ```

Is there a reason that range would ever be null? Would this be a surprising thing to happen? Maybe we should invert the if to reduce nesting, and give a warning message by doing something like the following. What do you think?

```ts
if (range == null) {
  console.warn(`Warning: Unexpectedly did not find range for verse segment: ${vs}`);
  continue;
}
if (range.length > selectionStart) {
  ...
```
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 511 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-Mj5boHK5UBg0rWYWKNe:-Mj5boHK5UBg0rWYWKNf:bs2qyen) ([raw file](https://github.com/sillsdev/web-xforge/blob/abdbbf95787b7082267852da5142071713a553bf/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L511)):*
> ```XML
>       const range: RangeStatic | undefined = this.getSegmentRange(vs);
>       if (range != null) {
>         if (range.length > selectionStart) {
> ```

So, my understanding so far is that `getSegmentRange(some_segment)` will return [...]

2021-09-17 22:32 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1128)* status: 2 of 21 files reviewed, 61 unresolved discussions (waiting on @marksvc and @RaymondLuong3)

___
*[src/RealtimeServer/scriptureforge/models/sf-project-rights.ts, line 11 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-Mj5knRg369UFjrl5hHy:-MjpUhZ9BEpZUq7fU0rv:bu417nu) ([raw file](https://github.com/sillsdev/web-xforge/blob/abdbbf95787b7082267852da5142071713a553bf/src/RealtimeServer/scriptureforge/models/sf-project-rights.ts#L11)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
>   ParatextNoteThreads = 'note_threads',
>   Notes = 'notes'
> ```

So, my understanding is that a ParatextNoteThread is a set of Notes in SF that corresponds to a PT CommentThread (excluding "ANSWER_" items).
And that a Note is a Note in SF that corresponds to a PT Comment.
Is that accurate?

Why the `Paratext` in `ParatextNoteThreads`? What about `NoteThreads` instead?
</blockquote></details>

Originally, the names were ParatextNoteThreads and ParatextNotes. But it was then simplified to Notes after Damien's suggestion. I don't mind just NoteThreads, I could go either way.
___
*[src/RealtimeServer/scriptureforge/models/sf-project-rights.ts, line 64 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-Mj6-ID356nZJBDKbOLH:-MjpVA0Y7fXUiP6F9zWE:bfyljw5) ([raw file](https://github.com/sillsdev/web-xforge/blob/abdbbf95787b7082267852da5142071713a553bf/src/RealtimeServer/scriptureforge/models/sf-project-rights.ts#L64)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

What would it mean to be able to edit a thread? I see that although a translator has the right to edit a thread, the only have the right to EditOwn notes. 
</blockquote></details>

The position of the thread can be edited by translators and others who have the ability to edit the text.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/segment.ts, line 11 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-MjB43yX75XCfP6387yX:-MjpVWiRBFt5-qC1BHzF:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/abdbbf95787b7082267852da5142071713a553bf/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/segment.ts#L11)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Unfortunately the type doesn't let us explain very well what the content is, so what do you think about having a comment saying : Mapping of treadId to position in editor.
   
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 59 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-MjB4OolC16VmN9yfVYx:-MjpVa7gAcdeM0oiDdO-:b-iqvyj9) ([raw file](https://github.com/sillsdev/web-xforge/blob/abdbbf95787b7082267852da5142071713a553bf/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L59)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

What is a "featured" verse ref info? One that we are drawing the user's attention to? Like the highlighted verses in the source that match what a user clicks in the target pane?
</blockquote></details>

The featured verse ref is the verse that has some distinguishing mark such as a community checking question or a note. And this info is used to markup the verse.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 63 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-MjB4Xr70EHNlpOZ0Dkr:-MjpVu398OITP7DssHVr:b-emundy) ([raw file](https://github.com/sillsdev/web-xforge/blob/abdbbf95787b7082267852da5142071713a553bf/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L63)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
> segmentSelection
> ```

So I think that here too we should use different naming, like `location` or `locationInSegment`. Although I'm a bit confused because I thought that verses contained segments, not the other way around. Maybe it is true that a segment can contain the end of one verse and the beginning of another, and so the segmentSelection here tells us where in a segment the verse begins?
Oh maybe a FeaturedVerseRefInfo refers to a range _within_ a verse to 'feature' to the user, and the segmentSelection defines that range? (Although we would need to know which segment the segmentSelection regards). 


   
</blockquote></details>

How does text anchor sound?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 334 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-Mj5Sf1r0q-lo_d84kaM:-MjpWL3H6YXhTAC-WOgR:bwjq945) ([raw file](https://github.com/sillsdev/web-xforge/blob/abdbbf95787b7082267852da5142071713a553bf/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L334)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
>   // Useful for testing
>   get embeddedElements(): Readonly<Map<string, number>> {
> ```

It looks like this is used for more than just testing, so we could drop that comment. Also, let's say that the values are positions within the editor. Sometimes we have positions in a segment, and sometimes we have positions in the editor, so it can add clarity to say.

Perhaps

```ts
/**
 * Mapping of threadId to position in editor.
 */
get embeddedElementns...
```

Actually, because this just returns viewModel.embeddedElements, and because I think it needs this explanation _there_, then instead of putting that information here you could just write it there in text-view-model.ts. (Adding to the existing comment on the field there.).


</blockquote></details>

That's right. There is some documentation in text-view-model.ts.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 488 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-Mj5VtEW0hMxBrypqFQr:-MjpWX1l-v8x27fE4-l8:bi71mhe) ([raw file](https://github.com/sillsdev/web-xforge/blob/abdbbf95787b7082267852da5142071713a553bf/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L488)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
> embedElementInline(
> ```

I'm looking at what this method is doing and how it's called, to understand what it's purpose is. So far I've described it as "Embed part of a segment into the editor using the specified formatting.". Is that accurate? Oh  it _adds_ something to the editor, and another method is removing. I see it calls an `insertEmbed` method, so maybe it could be described as "Insert an embedded item, with the specified format, into the editor at position ___".
</blockquote></details>

That's right, notes are embedded into the quill editor in line with the text. They then have to be stripped out of the equation when submitted text changes to the text docs.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 510 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-Mj5a4Or1p4GdfXTCZr0:-MjpWzSn8dbNT3otjqAy:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/abdbbf95787b7082267852da5142071713a553bf/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L510)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Is there a reason that range would ever be null? Would this be a surprising thing to happen? Maybe we should invert the if to reduce nesting, and give a warning message by doing something like the following. What do you think?

```ts
if (range == null) {
  console.warn(`Warning: Unexpectedly did not find range for verse segment: ${vs}`);
  continue;
}
if (range.length > selectionStart) {
  ...
```

</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 511 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-Mj5boHK5UB [...]

2021-09-20 17:37 UTC, RaymondLuong3 reviewed
Thanks for the careful feedback. With these changes, I'm much more confident that the behaviour of Paratext notes in SF will be less buggy. Some things I have not addressed include handling the deletion of text at across the start boundary of the note. This involves deleting the note icon, which I have created another branch for work on this.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-:-Mk3GKz_0MOJHiR3-nB9:be1zi7d)* status: 2 of 21 files reviewed, 61 unresolved discussions (waiting on @marksvc)

___
*[test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs, line 725 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-MjBcBDh6jp8t0HrC31z:-Mk2w30MC0qdYx5g90Kz:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/abdbbf95787b7082267852da5142071713a553bf/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L725)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Let's add a thread with a couple comments, in both the AddParatextNoteThreadData, and in AddParatextComments, that will experience no changes, and show that it _doesn't_ experience a change.
</blockquote></details>

Done.
___
*[test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs, line 746 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-MjBb0-9C7VG3uzyuXYn:-Mk2wDOkD099nDHwkem9:b2yo8tb) ([raw file](https://github.com/sillsdev/web-xforge/blob/abdbbf95787b7082267852da5142071713a553bf/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L746)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
> string date = new DateTimeOffset(change01.NotesUpdated[0].DateCreated).ToString("o");
> ```

We don't appear to do anything with this; is it something that should be checked?
</blockquote></details>

Nice, apparently it has been left around without purpose. Removed
___
*[test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs, line 758 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-MjBaq_m05NW9Wn1eqyB:-Mk34c9356_mYf0KV2kW:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/abdbbf95787b7082267852da5142071713a553bf/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L758)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

What about a test for adding a comment to an existing thread?
</blockquote></details>

Done.
___
*[test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs, line 1198 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-MjBWtR9BlA7V4lXJyX3:-Mk34eVYDROKcmf3xGBg:b-a9vvjw) ([raw file](https://github.com/sillsdev/web-xforge/blob/abdbbf95787b7082267852da5142071713a553bf/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L1198)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Is there a PT Comment concept, that a PT Comment can "apply to a verse"?
</blockquote></details>

I have not seen that concept, but I assume that Paratext is able to tell if a note applies to the verse. It's possible this is done if the start position is 0, but I can't say for certain.
___
*[test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs, line 1754 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-MjBYaT6DuBQM1SvmKN3:-Mk3Gvqn3JnjFY_wGUnE:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/abdbbf95787b7082267852da5142071713a553bf/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L1754)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
>  note 1: EDITED
> ```

I think we want to use `{i}` not `1` here. I know that wasn't introduced by this PR, but now is a good time to find out if it would make anything fail. 
</blockquote></details>

Done.
___
*[test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs, line 1857 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-MjBXXof4GtbUp7EmO6x:-Mk3H2Fd0Or6_D8DYGuT:btt0uf) ([raw file](https://github.com/sillsdev/web-xforge/blob/abdbbf95787b7082267852da5142071713a553bf/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L1857)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
>                             ContextBefore = "Context before ",
>                             ContextAfter = " context after",
> ```

If `appliesToVerse` is true, shouldn't `ContextBefore` and `ContextAfter` both be string.Empty, perhaps?
</blockquote></details>

Yes, that's correct. Done.
___
*[test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs, line 1927 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-MjBXpUp5gce8yWpnYCt:-Mk3C76B46EeFCCactN0:bg3d6qh) ([raw file](https://github.com/sillsdev/web-xforge/blob/abdbbf95787b7082267852da5142071713a553bf/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L1927)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
> "\"attributes\": { \"segment\": \"verse_" + chapterNum + "_" + i + "\" } }";
> ```

I observe that this test data is using verses that are a single segment. Our actual data is more complicated than that, and the note anchor system appears to concern itself with segments. Would we be able to add a test that uses a verse containing multiple segments, say 3, and that has a PT Comment located in what corresponds to the SF segment 2 (the segment in the middle), and we show that our code correctly works still?
</blockquote></details>

I've updated our understanding of Text Anchor to apply to the verse and not the specific segment, so this is no longer a relevant convern.
___
*[test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs, line 1188 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-Mic3ALnEzLQuggLz2Ef:-Mk3CKBI-aH6rHVqSZTD:bwzh78o) ([raw file](https://github.com/sillsdev/web-xforge/blob/ee01d4cb491c276c676021055956aae86c83c57c/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L1188)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
>             Assert.That(thread02.StartPosition, Is.EqualTo(17));
> ```

Why is this removing the check for `17`?

Actually, if I break here I observe that thread02.StartPosition is 17. And since thread02.CurrentContextSelection.Start is 0, it seems that thread02.StartPosition is wrong, right?
</blockquote></details>

I've removed start position altogether now.
___
*[test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs, line 1742 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-Mic2YBh8tDRHkIsVPl9:-Mk3FjKeAoLWnRKEVbaU:bss4a2b) ([raw file](https://github.com/sillsdev/web-xforge/blob/abdbbf95787b7082267852da5142071713a553bf/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L1742)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
> t.
> ```

I think maybe you don't want a period at the end of this string? Maybe it happens not to matter in the cases at hand.
</blockquote></details>

Removed.
___
*[test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs, line 1783 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-Mj0qdj45ygtUaMYCIm9:-Mk3G2Tk4z0eDYjEN3SS:b-ai3wdc) ([raw file](https://github.com/sillsdev/web-xforge/blob/abdbbf95787b7082267852da5142071713a553bf/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L1783)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
>                 var noteThreadChange = new ParatextNoteThreadChange(threadId, verseRef, $"Scripture text in project",
>                     "Context before ", " context after", 17, "icon1");
>                 noteThreadChange.CurrentContextSelection = new SegmentSelection { Start = 0, End = 0 };
> ```

Shouldn't the `17` above be 0 instead, since SegmentSelection Start==0?

</blockquote></details>

The start p [...]

2021-09-20 20:09 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1128)* status: 1 of 21 files reviewed, 60 unresolved discussions (waiting on @marksvc)

___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 1499 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-Mj1L-XA5SOVWCG_gLXD:-Mk3muHz7Y7eAYtuQKOO:boj6bze) ([raw file](https://github.com/sillsdev/web-xforge/blob/abdbbf95787b7082267852da5142071713a553bf/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1499)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I'll make a note to test this at a later date.
</blockquote></details>

Ok, I agree that it would be nice to move this out instead of doing this as a side effect. I chose to keep this in `ParatextService` since it would be complicated to have `SFNotesToCommentChangeListAsync` to return another object that represents the changes needed for all the note threads. I've pulled it out into its own method so it is clear what it is doing.


<!-- Sent from Reviewable.io -->

2021-09-27 22:28 UTC, marksvc requested changes
> Reviewed 12 of 19 files at r4, 2 of 4 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1128)* status: 20 of 21 files reviewed, 37 unresolved discussions (waiting on @marksvc and @RaymondLuong3)

___
*[src/RealtimeServer/scriptureforge/models/sf-project-rights.ts, line 11 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-Mj5knRg369UFjrl5hHy:-MkdEMOaAQxoqUcb50Z6:bsz2pzt) ([raw file](https://github.com/sillsdev/web-xforge/blob/abdbbf95787b7082267852da5142071713a553bf/src/RealtimeServer/scriptureforge/models/sf-project-rights.ts#L11)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Originally, the names were ParatextNoteThreads and ParatextNotes. But it was then simplified to Notes after Damien's suggestion. I don't mind just NoteThreads, I could go either way.
</blockquote></details>

Yeah, I think we should use "NoteThreads", as I think I discuss in another comment.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/segment.ts, line 35 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-MkOfHsaB_35PtVLAgyy:-MkOfHsaB_35PtVLAgyz:ba0jf41) ([raw file](https://github.com/sillsdev/web-xforge/blob/4a3334489b1b9b84713e9e114ca0999c2692f1e3/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/segment.ts#L35)):*
> ```
> embeddedElement():
> ```

Shouldn't this be plural, as `embeddedElements()`? I was a little confused by that when reading it elsewhere.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts, line 100 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-MkJWgooEzoDoeay6T_m:-MkJWgooEzoDoeay6T_n:b-n8md7a) ([raw file](https://github.com/sillsdev/web-xforge/blob/4a3334489b1b9b84713e9e114ca0999c2692f1e3/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L100)):*
> ```
> A mapping of elements embedded into the quill editor
> ```

Sorry to be picky. How about "A mapping **of IDs** of elements embedded into the quill editor"
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 63 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-MjB4Xr70EHNlpOZ0Dkr:-MkcB5_L1uE7s86tvJtj:bb18at) ([raw file](https://github.com/sillsdev/web-xforge/blob/abdbbf95787b7082267852da5142071713a553bf/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L63)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

How does text anchor sound?
</blockquote></details>

Good, thank you. 
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 515 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-Mkcp5lw3nhGNokHjSt7:-MkcTG4y6nKlyVHEm1SF:blp37j) ([raw file](https://github.com/sillsdev/web-xforge/blob/4a3334489b1b9b84713e9e114ca0999c2692f1e3/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L515)):*
> ```XML
>         break;
>       }
>       if (range.length > startIndexInSegment) {
> ```

Don't we need to account for embeds here? Because suppose the `range` segment has text "##########" (where each # is an embed), and the _following_ segment has text "#In the beginning". startIndexInSegment (a text-only position) is "In ".Length=3 , and range.length = "##########".Length=10. And `range.length > startIndexInSegment`, and so we incorrectly match to the current segment when we should have matched to the following segment. So here instead we want to do something like `if (range.length > startIndexInSegment + count_of_all_embeds_leading_up_to_beginning_of_anchoring) {`. Right?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 521 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-Mkd5Eu39R4XPHha1-r5:-Mkd5Eu4Bj01D6HyxMar:b5bh3rr) ([raw file](https://github.com/sillsdev/web-xforge/blob/4a3334489b1b9b84713e9e114ca0999c2692f1e3/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L521)):*
> ```
> this.getEmbedCountInSegmentBefore(range.length - 1, range.index);
> ```

Won't `- 1` give the wrong result because it won't count an embed right at the end of a segment? Don't we want `(range.length, range.index)` instead? I tried it that way with no unit test failures, if that tells us anything.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 531 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-Mkd79ti1ZIgZK9h8IMY:-Mkd79ti1ZIgZK9h8IMZ:b-6mbdc5) ([raw file](https://github.com/sillsdev/web-xforge/blob/4a3334489b1b9b84713e9e114ca0999c2692f1e3/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L531)):*
> ```
> this.getEmbedCountInSegmentBefore(startIndexInSegment,
> ```

Doesn't this fail to take into account a segment with a bunch of embeds at the beginning, because we are passing a text-position value, `startIndexInSegment` in. And let's suppose the segment contains "##########In the beginning", where each of the # characters are an embed, and we want to find "the", the startIndexInSegment would be "In ".Length=3. And so then in getEmbedCountInSegmentBeforePosition() it would look for embeds that lead up to segmentRange.index+3. And so it would look at the first three embeds and return 3. But the answer that we wanted to get is "##########In ".Length=13. Is that right?

Oh no that's probably related to the part of getEmbedCountInSegmentBefore() that was removed in an iteration.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 754 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-Mkcp_MD7r5OedYh2Y8M:-Mkcp_ME1DgZ3JBXBzJm:b-ok2gyz) ([raw file](https://github.com/sillsdev/web-xforge/blob/4a3334489b1b9b84713e9e114ca0999c2692f1e3/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L754)):*
> ```XML
> 
>     Promise.resolve().then(() => this.adjustSelection());
>     this.updated.emit({ delta, prevSegment, segment: this._segment, oldSegmentEmbeds: oldSegmentEmbeds });
> ```

(Yeah it seems like when this fires saying that there was an update, the segment embed list that is sent would make sense to be the _current_ segment embed list. But it's an 'old' segment embed list?)
(I discuss this in another comment.)
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 850 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-Mkcs0MA35_GRMUYC3l2:-Mkcs0MA35_GRMUYC3l3:bpydfmr) ([raw file](https://github.com/sillsdev/web-xforge/blob/4a3334489b1b9b84713e9e114ca0999c2692f1e3/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L850)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>       if (newStart === this._segment.range.index || embedIndices.includes(newStart - 1)) {
>         // if the selection is before an embed at the start of the segment or
>         // the selection is between embeds, move the selection behind it
>         while (embedIndices.includes(newStart)) {
>           newStart++;
>         }
> ```
</details>


I had to think about this and read it a couple times. Good job being able to write that logic in so few lines. And thank you for putting in a comment :)
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 432 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-MkJbrqkD0LXCQiLtlev:-MkJbrqkD0LXCQiLtlew:bj3sowt) ([raw file](https://github.com/sillsdev/web-xforge/blob/4a3334489b1b9b84713e9e114ca0999c2692f1e3/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L432)):*
> ```XML
>     delta?: DeltaStatic,
>     prevSegment?: Segment,
>     oldSegmentEmbeds?: Map<string, number>
> ```

What makes these "old" segment embeds? Are they out of date and going to get refreshed in a moment or something? 
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/tr [...]

2021-09-28 22:27 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1128)* status: 20 of 21 files reviewed, 37 unresolved discussions (waiting on @marksvc and @RaymondLuong3)

___
*[src/RealtimeServer/scriptureforge/models/sf-project-rights.ts, line 11 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-Mj5knRg369UFjrl5hHy:-Mkh9s3l6LbfFoz95I-1:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/abdbbf95787b7082267852da5142071713a553bf/src/RealtimeServer/scriptureforge/models/sf-project-rights.ts#L11)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Yeah, I think we should use "NoteThreads", as I think I discuss in another comment.
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/segment.ts, line 35 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-MkOfHsaB_35PtVLAgyy:-MkhABux5ThE1a7u6FeW:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/4a3334489b1b9b84713e9e114ca0999c2692f1e3/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/segment.ts#L35)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
> embeddedElement():
> ```

Shouldn't this be plural, as `embeddedElements()`? I was a little confused by that when reading it elsewhere.
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts, line 100 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-MkJWgooEzoDoeay6T_m:-MkhAW-V0mcrnEbovBUB:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/4a3334489b1b9b84713e9e114ca0999c2692f1e3/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L100)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
> A mapping of elements embedded into the quill editor
> ```

Sorry to be picky. How about "A mapping **of IDs** of elements embedded into the quill editor"
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 512 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-MkhAmOg1HGg_eXtWHu5:-MkhAmOg1HGg_eXtWHu6:b-qmcm13) ([raw file](https://github.com/sillsdev/web-xforge/blob/4a3334489b1b9b84713e9e114ca0999c2692f1e3/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L512)):*
> ```
> console.warn(`Warning: Could not find range for verse segment: ${vs}`);
> ```
It seems this will pop up each time a user loads the component or switches text. I've removed it now.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 515 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-Mkcp5lw3nhGNokHjSt7:-MkhKIA52Z_8LLDxNwh3:bhesdx4) ([raw file](https://github.com/sillsdev/web-xforge/blob/4a3334489b1b9b84713e9e114ca0999c2692f1e3/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L515)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Don't we need to account for embeds here? Because suppose the `range` segment has text "##########" (where each # is an embed), and the _following_ segment has text "#In the beginning". startIndexInSegment (a text-only position) is "In ".Length=3 , and range.length = "##########".Length=10. And `range.length > startIndexInSegment`, and so we incorrectly match to the current segment when we should have matched to the following segment. So here instead we want to do something like `if (range.length > startIndexInSegment + count_of_all_embeds_leading_up_to_beginning_of_anchoring) {`. Right?
</blockquote></details>

Even better, I get the text only length by subtracting the embeds, and compare the start position to the text only length of the segment. I've added a test for it too.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 521 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-Mkd5Eu39R4XPHha1-r5:-MkhKpLqEH-Ts5CO5I5A:bk84r23) ([raw file](https://github.com/sillsdev/web-xforge/blob/4a3334489b1b9b84713e9e114ca0999c2692f1e3/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L521)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
> this.getEmbedCountInSegmentBefore(range.length - 1, range.index);
> ```

Won't `- 1` give the wrong result because it won't count an embed right at the end of a segment? Don't we want `(range.length, range.index)` instead? I tried it that way with no unit test failures, if that tells us anything.
</blockquote></details>

I believe you are right. I've removed the -1. Since notes really will never show up at the end of a segment (notes are automatically before the last word) this wouldn't matter too much in real life. But I've corrected it now.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 531 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-Mkd79ti1ZIgZK9h8IMY:-MkhReK01qPK7I2gziVa:bji1rx0) ([raw file](https://github.com/sillsdev/web-xforge/blob/4a3334489b1b9b84713e9e114ca0999c2692f1e3/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L531)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
> this.getEmbedCountInSegmentBefore(startIndexInSegment,
> ```

Doesn't this fail to take into account a segment with a bunch of embeds at the beginning, because we are passing a text-position value, `startIndexInSegment` in. And let's suppose the segment contains "##########In the beginning", where each of the # characters are an embed, and we want to find "the", the startIndexInSegment would be "In ".Length=3. And so then in getEmbedCountInSegmentBeforePosition() it would look for embeds that lead up to segmentRange.index+3. And so it would look at the first three embeds and return 3. But the answer that we wanted to get is "##########In ".Length=13. Is that right?

Oh no that's probably related to the part of getEmbedCountInSegmentBefore() that was removed in an iteration.
</blockquote></details>

Good thinking. I've added a method called getIndexForTextAnchorPosition() that accounts for the leading embeds and offsets the insert index accordingly.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 754 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-Mkcp_MD7r5OedYh2Y8M:-MkhRvXHEShOWTxOWUq2:b-w9yxyq) ([raw file](https://github.com/sillsdev/web-xforge/blob/4a3334489b1b9b84713e9e114ca0999c2692f1e3/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L754)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

(Yeah it seems like when this fires saying that there was an update, the segment embed list that is sent would make sense to be the _current_ segment embed list. But it's an 'old' segment embed list?)
(I discuss this in another comment.)
</blockquote></details>

That's correct. This makes it much easier to know how the edit has affected our embedded elements. Otherwise, by the time the editor hears about the change, we have lost the original state of the editor and the embedded elements. I suppose we could still iterate through the notes on this given chapter, and apply the changes between where the current quill editor locates the note against the outdated note thread.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 432 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-MkJbrqkD0LXCQiLtlev:-MkhTn1SDsCimd-ZJufm:blufz6r) ([raw file](https://github.com/sillsdev/web-xforge/blob/4a3334489b1b9b84713e9e114ca0999c2692f1e3/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L432)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

What makes these "old" segment embeds? Are they out of date and going to get refreshed in a moment or something? 
</blockquote></details>

That's rig [...]

2021-09-29 17:15 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1128)* status: 20 of 21 files reviewed, 37 unresolved discussions (waiting on @marksvc)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 1053 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-MkNwLBXA3rX4W0JIa9r:-MkmWW3L9_adarxlRL30:b-z8xyos) ([raw file](https://github.com/sillsdev/web-xforge/blob/4a3334489b1b9b84713e9e114ca0999c2692f1e3/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1053)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
>  index <= endIndex
> ```

Shouldn't this instead be `<`, because otherwise we will add to the count for embeds that occur immediately after the anchor range? 

I note that changing it to `<` doesn't fail any tests.


</blockquote></details>

Good thinking. For languages with spaces, this would not be an issue since it is not possible to start a new note on punctuation or a space (and so it is note possible to have a note embedded immediately after a note anchor.) So to test this, I've added a scenario where a note is attached to the "." immediately after another text anchor selection. I'm glad to test reasonable edge cases.
___
*[test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs, line 725 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-MjBcBDh6jp8t0HrC31z:-MkmMFAb4qpekVM0OOsr:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/abdbbf95787b7082267852da5142071713a553bf/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L725)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Can we add a threadNum=9 with noteCount=3 and expect it not to report a change? Sorry to be picky. Then we test that a 1-note case, and a multi-note case, both do as expected for not changing.
</blockquote></details>

Done.
___
*[test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs, line 1857 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-MjBXXof4GtbUp7EmO6x:-MkmPLSU9dsSMDR7Mn_D:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/abdbbf95787b7082267852da5142071713a553bf/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L1857)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I see that that was done up in  AddParatextNoteThreadData. But presumably it should be done here too?
</blockquote></details>

Done.
___
*[test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs, line 819 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-MkJAidX6cLaI9bXlv8Y:-MkmN6dc959-54jr8254:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/4a3334489b1b9b84713e9e114ca0999c2692f1e3/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L819)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Before the SUT we should probably first assert that it _doesn't_ find the thread.
</blockquote></details>

Done.
___
*[test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs, line 826 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-MkIzHhX8bf1xmf9ZRtX:-MkmNHb_4GAG9Hd7E7h6:b-jeqar9) ([raw file](https://github.com/sillsdev/web-xforge/blob/4a3334489b1b9b84713e9e114ca0999c2692f1e3/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L826)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Okay, so this is syncuser02, and not 01, because the comment is owned by user02 and when we wanted to set a syncuser for the SF note, we therefore decided to use syncuser02 is that right? I'm still slightly confused where this comes from; there is a lot going on in this file :)
</blockquote></details>

That's correct. The comment gets created in Paratext, and then we can set the sync user on the Note that is owned by user 2. FYI this will not be exercised in production until we allow users to edit and create notes in SF. This will come a few months down the road.
___
*[test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs, line 1764 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-MkJBr646etCFLzDm-X0:-MkmO02E7nsZgF4IcOUo:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/4a3334489b1b9b84713e9e114ca0999c2692f1e3/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L1764)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
>  Start = 15, Length = 22 }
> ```

Can we switch `15` with `before.Length` and `22` with `text.Length` to de-magic-number?



</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-01 22:19 UTC, marksvc requested changes
> Reviewed 22 of 26 files at r7, 1 of 1 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1128)* status: 28 of 30 files reviewed, 21 unresolved discussions (waiting on @marksvc and @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 512 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-MkhAmOg1HGg_eXtWHu5:-MkxZ-ENDt7aWbZpWZpt:b4c9lyr) ([raw file](https://github.com/sillsdev/web-xforge/blob/4a3334489b1b9b84713e9e114ca0999c2692f1e3/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L512)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> console.warn(`Warning: Could not find range for verse segment: ${vs}`);
> ```
It seems this will pop up each time a user loads the component or switches text. I've removed it now.
</blockquote></details>

:thumbsup: 
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 515 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-Mkcp5lw3nhGNokHjSt7:-MkxZh5A1EVFxQRVD09Y:b4c9lyr) ([raw file](https://github.com/sillsdev/web-xforge/blob/4a3334489b1b9b84713e9e114ca0999c2692f1e3/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L515)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Even better, I get the text only length by subtracting the embeds, and compare the start position to the text only length of the segment. I've added a test for it too.
</blockquote></details>

:thumbsup: 
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 880 at r8](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-MkxdUlx6iA4UcestSxj:-MkxdUlx6iA4UcestSxk:b-x3e10m) ([raw file](https://github.com/sillsdev/web-xforge/blob/ccbbb190abe170d30eca8963aabf2c0fb7d1cb3a/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L880)):*
> ```XML
>     }
>     return textIndex;
>   }
> ```

Okay let's see. So if position is 5, segmentStartIndex is 100, and quill at 100 is "#a#b#c#d#e#f#g", then we do
```ts
let textIndex = segmentStartIndex 100 + position 5 = 105
let notesInSegmentBefore = this.get..(position 5, segmentStartIndex 100) = the 3 embeds in "#a#b#".
while (notesInSegmentBefore 3 > 0 ) {
  textIndex += notesInSegmentBefore 3, so textIndex=108
  position 5 -= position 5 - notesInSegmentBefore 3, so position = position 5 - (position 5 - notesInSegmentBefore 3), position = 3
  notesInSegmentBefore = this.get..(position 3, segmentStartIndex 100 + notesInSegmentBefore 3) = the 1 embed in "b#c"
}
```
then
```ts
while(notesInSegmentBefore 1 > 0) {
  textIndex += 1, so 109
  position = notesInSegmentBefore 1 
  notesInSegmentBefore = this.get..(position 1, segmentStartIndex 100 + notesInSegmentBefore 1) = 0 embeds in "a" // something is wrong here
}
return textIndex 109
```
But we should have returned 111, to return the quill position  immediately before 'f'. 

I didn't spend a whole lot of time here, but I think there is something wrong with this method, isn't there?

BTW While seeking to understand, I re-wrote the method name, comment, and argument names on my computer as:
```ts
  /**
   * Returns the quill editor position that corresponds to a specified text-only character that is past a
   * segment start quill editor position.
   */
  private getIndexForTextOnlyPosition(charPosition: number, segmentStartQuillPosition: number): number {
```
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 1083 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-MkJm2d5BU0GoeXKgldQ:-Mkn2tFn7MIbliH1Kl-C:b-crr9pz) ([raw file](https://github.com/sillsdev/web-xforge/blob/4a3334489b1b9b84713e9e114ca0999c2692f1e3/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1083)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

In paratext, I see that if you are typing to expand the last word in the text anchor, paratext considers that as part of the selection. I've chosen to include that last position as part of the text anchor to mimic this behaviour. The user will be able to see the text anchor expand to include the inserted text (once we get that underlined like in paratext). If the user decides it does not need to be part of the note, he can begin his edits outside the text anchor (after the trailing space after the last word.)
</blockquote></details>

Okay. But what if a verse is "In the beginning", and a text anchor is on "beginning". And the user wants to append text to the verse that isn't part of the anchor range. They will click to type after the 'g', but there is no where they could type that would do what they wanted, right? Okay I see that Paratext 9 is doing that tho. 

Well, okay, so I then tried it with appending ", but" and I see that the comma is included in the range but not the " but".
And I tried instead appending " but" and I see that the range did not ultimately increase; " but" is not included in the range.

This maybe should be followup rather than as part of this PR. Perhaps a space should be detected in our code and we break the anchor there? I'm not sure that makes sense tho. :) I guess PT and SF can't know what the user is thinking. 
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 1103 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-MkOv_fO8e1dv_A-B1hQ:-MkxRV9dDyDw3dArnPkm:bohjmya) ([raw file](https://github.com/sillsdev/web-xforge/blob/4a3334489b1b9b84713e9e114ca0999c2692f1e3/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1103)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Actually, this is not obvious, but the edit length also includes embeds. So if the delete is a range of 5 characters and there happens to be embeds deleted, they count toward the 5 characters. So there is no need to consider the length that embeds take up. I'll add a comment.
</blockquote></details>

Okay I'm convinced. I run thru a couple scenaries below which convinced me.

----

 
`editLength` may take into account embeds, but oldTextAnchor.length doesn't, I don't think.

If we have a verse of "abc#defg###hijk" and the user deletes "fg###hjk", then editIndex is the quill position of "f" (say 100), and editLength is "fg###hjk".length === 8. Let's say that a note is anchored to "defg" and after it are some .. images or some other embed. "def" is at position 100-2=98. "#defg" starts at position 98-1=97.
"defg".length === 4.

We set charIndex = editIndex for the loop. Here we check 
```ts
} else if (100 > 97 && 100 <= 97 + 4) {
```
and increase lengthWithin. 
So we loop again with charIndex incremented.
```ts
} else if (101 > 97 && 101 <= 97 + 4) {
```
, incremente lengthWithin, increment charIndex, only loop if `charIndex 102 < editIndex 100 + editLength 8`,
so again checking 
```ts
} else if (102 > 97 && 102 <= 97 + 4) {
```
which is false, and so break out of the for loop.



What if there is an embed in the note anchor range. 
So the verse is "abc#def#ghijk". Say the embedIndex is to position 97, which starts "#d", and the textAnchor length is 6, in quill spanning over "def#ghi".  And the user deletes "f#g". "f#g" starts at quill position 100.
We have 
```ts
for (let charIndex = editIndex 100 ; charIndex 100 < editIndex 100 + editLength 3; charIndex++) {
...
} else if (charIndex 100 > embedIndex 97 && charIndex 100 <= 97 + oldTextAnchor.length 6) {
  lengthWithin++
```
Then with charIndex=101,
```
if (embedPositions.has(charIndex) { true! continue}
```
Then with charIndex=102
```
} else if (charIndex 102 > 97 && 102 <= 97+6) {
  lengthWithin++
```
With charIndex=103
```
for (..; charIndex 103 < editIndex 100 + editLength 3; )
```
fails [...]

2021-10-04 23:11 UTC, marksvc requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1128)* status: 23 of 30 files reviewed, 21 unresolved discussions (waiting on @marksvc and @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 880 at r11](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-MlCVl1q-JrWHNw8Mo4T:-MlCVl1q-JrWHNw8Mo4U:bej8mcm) ([raw file](https://github.com/sillsdev/web-xforge/blob/7a68ecd7ba30ebd50057f297df12f3a579c80bcc/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L880)):*
> ```XML
>       }
>       textIndex++;
>     }
> ```

Great, this can be much simpler!
Let's see, so if startPosition is 5, segmentStartIndex is 100, and quill at 100 is "#a#b#c#d#e#f#g", then we do the following and return 110. But we should have returned 111, which corresponds to text-position 5 in the above, which is 'f'.
(Unless I did this wrong?)
I think it needs more adjustment?

```ts
let textCharactersFound = 0;
let textIndex = segmentStartIndex 100;
..
while (textCharactersFound 0 < startPosition 5) {
  if (!embedIndices.includes(textIndex 100), i.e. !true, so false) {}
  textIndex++  so 101
}
```
then 
```ts
while (textCharactersFound 0 < startPosition 5) {
  if (!embedIndices.includes(textIndex 101), so true) {
    textCharactersFound++ so 1
  }
  textIndex++ so 102
}
```
then 
```ts
while (textCharactersFound 1 < startPosition 5) {
  if (!embedIndices.includes(textIndex 102), so false) {
  }
  textIndex++ so 103
}
```
then 
```ts
while (textCharactersFound 1 < startPosition 5) {
  if (!embedIndices.includes(textIndex 103), so true) {
    textCharactersFound++ so 2
  }
  textIndex++ so 104
}
```
then 
```ts
while (textCharactersFound 2 < startPosition 5) {
  if (!embedIndices.includes(textIndex 104), so false) {
  }
  textIndex++ so 105
}
```
then 
```ts
while (textCharactersFound 2 < startPosition 5) {
  if (!embedIndices.includes(textIndex 105), so true) {
    textCharactersFound++ so 3
  }
  textIndex++ so 106
}
```
then 
```ts
while (textCharactersFound 3 < startPosition 5) {
  if (!embedIndices.includes(textIndex 106), so false) {
  }
  textIndex++ so 107
}
```
then 
```ts
while (textCharactersFound 3 < startPosition 5) {
  if (!embedIndices.includes(textIndex 107), so true) {
    textCharactersFound++ so 4
  }
  textIndex++ so 108
}
```
then 
```ts
while (textCharactersFound 4 < startPosition 5) {
  if (!embedIndices.includes(textIndex 108), so false) {
  }
  textIndex++ so 109
}
```
then 
```ts
while (textCharactersFound 4 < startPosition 5) {
  if (!embedIndices.includes(textIndex 109), so true) {
    textCharactersFound++ so 5
  }
  textIndex++ so 110
}
```
then 
```ts
while (textCharactersFound 5 < startPosition 5) {
}
return textIndex 110
```


<!-- Sent from Reviewable.io -->

2021-10-05 02:08 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1128)* status: 23 of 30 files reviewed, 21 unresolved discussions (waiting on @marksvc)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 880 at r8](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-MkxdUlx6iA4UcestSxj:-MlB2V8X9XTSWTPHGo_B:b2gxx2p) ([raw file](https://github.com/sillsdev/web-xforge/blob/ccbbb190abe170d30eca8963aabf2c0fb7d1cb3a/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L880)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Okay let's see. So if position is 5, segmentStartIndex is 100, and quill at 100 is "#a#b#c#d#e#f#g", then we do
```ts
let textIndex = segmentStartIndex 100 + position 5 = 105
let notesInSegmentBefore = this.get..(position 5, segmentStartIndex 100) = the 3 embeds in "#a#b#".
while (notesInSegmentBefore 3 > 0 ) {
  textIndex += notesInSegmentBefore 3, so textIndex=108
  position 5 -= position 5 - notesInSegmentBefore 3, so position = position 5 - (position 5 - notesInSegmentBefore 3), position = 3
  notesInSegmentBefore = this.get..(position 3, segmentStartIndex 100 + notesInSegmentBefore 3) = the 1 embed in "b#c"
}
```
then
```ts
while(notesInSegmentBefore 1 > 0) {
  textIndex += 1, so 109
  position = notesInSegmentBefore 1 
  notesInSegmentBefore = this.get..(position 1, segmentStartIndex 100 + notesInSegmentBefore 1) = 0 embeds in "a" // something is wrong here
}
return textIndex 109
```
But we should have returned 111, to return the quill position  immediately before 'f'. 

I didn't spend a whole lot of time here, but I think there is something wrong with this method, isn't there?

BTW While seeking to understand, I re-wrote the method name, comment, and argument names on my computer as:
```ts
  /**
   * Returns the quill editor position that corresponds to a specified text-only character that is past a
   * segment start quill editor position.
   */
  private getIndexForTextOnlyPosition(charPosition: number, segmentStartQuillPosition: number): number {
```

</blockquote></details>

Thanks for catching that. I've updated the algorithm to simply count up until the number of text characters found is equivalent to the text anchor start position.

```
```

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 880 at r11](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-MlCVl1q-JrWHNw8Mo4T:-MlDBBYN41uSBvsVy1wa:bd20plo) ([raw file](https://github.com/sillsdev/web-xforge/blob/7a68ecd7ba30ebd50057f297df12f3a579c80bcc/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L880)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Great, this can be much simpler!
Let's see, so if startPosition is 5, segmentStartIndex is 100, and quill at 100 is "#a#b#c#d#e#f#g", then we do the following and return 110. But we should have returned 111, which corresponds to text-position 5 in the above, which is 'f'.
(Unless I did this wrong?)
I think it needs more adjustment?

```ts
let textCharactersFound = 0;
let textIndex = segmentStartIndex 100;
..
while (textCharactersFound 0 < startPosition 5) {
  if (!embedIndices.includes(textIndex 100), i.e. !true, so false) {}
  textIndex++  so 101
}
```
then 
```ts
while (textCharactersFound 0 < startPosition 5) {
  if (!embedIndices.includes(textIndex 101), so true) {
    textCharactersFound++ so 1
  }
  textIndex++ so 102
}
```
then 
```ts
while (textCharactersFound 1 < startPosition 5) {
  if (!embedIndices.includes(textIndex 102), so false) {
  }
  textIndex++ so 103
}
```
then 
```ts
while (textCharactersFound 1 < startPosition 5) {
  if (!embedIndices.includes(textIndex 103), so true) {
    textCharactersFound++ so 2
  }
  textIndex++ so 104
}
```
then 
```ts
while (textCharactersFound 2 < startPosition 5) {
  if (!embedIndices.includes(textIndex 104), so false) {
  }
  textIndex++ so 105
}
```
then 
```ts
while (textCharactersFound 2 < startPosition 5) {
  if (!embedIndices.includes(textIndex 105), so true) {
    textCharactersFound++ so 3
  }
  textIndex++ so 106
}
```
then 
```ts
while (textCharactersFound 3 < startPosition 5) {
  if (!embedIndices.includes(textIndex 106), so false) {
  }
  textIndex++ so 107
}
```
then 
```ts
while (textCharactersFound 3 < startPosition 5) {
  if (!embedIndices.includes(textIndex 107), so true) {
    textCharactersFound++ so 4
  }
  textIndex++ so 108
}
```
then 
```ts
while (textCharactersFound 4 < startPosition 5) {
  if (!embedIndices.includes(textIndex 108), so false) {
  }
  textIndex++ so 109
}
```
then 
```ts
while (textCharactersFound 4 < startPosition 5) {
  if (!embedIndices.includes(textIndex 109), so true) {
    textCharactersFound++ so 5
  }
  textIndex++ so 110
}
```
then 
```ts
while (textCharactersFound 5 < startPosition 5) {
}
return textIndex 110
```

</blockquote></details>

In Paratext, if two notes are anchored to the same start position, there is no guarantee what order they are in. My guess is that the one created last will be the second note. I haven't explored this very thoroughly, but to my understanding, there is no advantage of ordering the note icons. The underlines in PT will overlap too without a way to distinguish the actual text that a note relates to. So anchoring the note at position 110 seems acceptable to me.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 1083 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-MkJm2d5BU0GoeXKgldQ:-MlC8I407XhXPyrv8dle:b-mohm1g) ([raw file](https://github.com/sillsdev/web-xforge/blob/4a3334489b1b9b84713e9e114ca0999c2692f1e3/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1083)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Okay. But what if a verse is "In the beginning", and a text anchor is on "beginning". And the user wants to append text to the verse that isn't part of the anchor range. They will click to type after the 'g', but there is no where they could type that would do what they wanted, right? Okay I see that Paratext 9 is doing that tho. 

Well, okay, so I then tried it with appending ", but" and I see that the comma is included in the range but not the " but".
And I tried instead appending " but" and I see that the range did not ultimately increase; " but" is not included in the range.

This maybe should be followup rather than as part of this PR. Perhaps a space should be detected in our code and we break the anchor there? I'm not sure that makes sense tho. :) I guess PT and SF can't know what the user is thinking. 


</blockquote></details>

It's true. This will be something we can adjust later. I'm not so concerned about getting this perfect because we can't say for sure what the user intends to do. In reality, I'm not sure that a user will pay too much attention to whether the selection includes or excludes their edits. But for the ones that do care, we can adjust based on their feedback. And Paratext will change it when users do a sync anyways.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 1089 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-MkxrKeT4UbesCX4QWrW:-MlC9XlZ6Cy44-5tekjV:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/eb21f75a903b266f26d2eb6529ea03edc6a3a908/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1089)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
> // The user inserted text at the end of this note anchor
> ```

I am glad for the comment, but I think we need to change it to something like "Note that if the user inserted" since this block accounts for both that case as well as generally if they inserted text "in" the anchor range at all.

</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 1564  [...]

2021-10-05 02:48 UTC, irahopkinson reviewed
@raymondluong3 and @marksvc thanks for both of your good work on this PR. Since it is holding up other work on this feature (sub-project SF-1192) and this feature is our critical path, consider creating another issue to deal with remaining issues and merge this one.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-:-MlDKvMG4w6zowW48SZW:b-kmwkn7)* status: 23 of 30 files reviewed, 21 unresolved discussions (waiting on @marksvc)



<!-- Sent from Reviewable.io -->

2021-10-05 21:30 UTC, marksvc reviewed
> Reviewed 5 of 5 files at r10, 2 of 2 files at r11.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1128)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 880 at r11](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-MlCVl1q-JrWHNw8Mo4T:-MlFvvB_9kO9V5LGh90Z:bbrqveu) ([raw file](https://github.com/sillsdev/web-xforge/blob/7a68ecd7ba30ebd50057f297df12f3a579c80bcc/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L880)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

In Paratext, if two notes are anchored to the same start position, there is no guarantee what order they are in. My guess is that the one created last will be the second note. I haven't explored this very thoroughly, but to my understanding, there is no advantage of ordering the note icons. The underlines in PT will overlap too without a way to distinguish the actual text that a note relates to. So anchoring the note at position 110 seems acceptable to me.
</blockquote></details>

Okay. And a way to think about it is that if we have text "a###b", starting at quill-position 0, and 'a' is at text-position 0 and 'b' is at text-position 1, the resolution of text-position 1 to quill-position will give any value in the range of (quill position of 'a', quill position of 'b'], so (0,4], so 1,2,3,or 4. 
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 1499 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1128#-Mj1L-XA5SOVWCG_gLXD:-MlGfneW9Tx0PctCofao:bkj7x3c) ([raw file](https://github.com/sillsdev/web-xforge/blob/abdbbf95787b7082267852da5142071713a553bf/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1499)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Ok, I agree that it would be nice to move this out instead of doing this as a side effect. I chose to keep this in `ParatextService` since it would be complicated to have `SFNotesToCommentChangeListAsync` to return another object that represents the changes needed for all the note threads. I've pulled it out into its own method so it is clear what it is doing.
</blockquote></details>

But it's still happening as a side effect, right, where a caller of `SFNotesToCommentChangeListAsync()` or a caller of `UpdateParatextCommentsAsync()` won't be expecting their SF DB noteThread records to be changed. Maybe we can look more at how we could pull this up and out so it's not a side effect.


<!-- Sent from Reviewable.io -->

2021-10-05 21:32 UTC, marksvc approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1128)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2021-10-05 22:22 UTC, marksvc approved these changes
> Reviewed 1 of 1 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1128)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2021-10-05 22:47 UTC, merged