Fix resource query incorrectly implemented in #1154
sillsdev/web-xforge pull request #1155
Opened 2021-09-29 19:36 UTC by Nateowami

Also include resource name so it can be searched for on system administration page

The way I originally wrote the script worked, but then I modified the first query (line 7) to fetch objects, rather than an array of string ids. That broke line 15. Unfortunately I didn't catch that until after it was merged.

2021-09-30 02:21 UTC, irahopkinson requested changes
Thanks for working on this.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1155#-:-MkoVFXBDGHSLtFShHOg:b-4v1jp5)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[mongodb/Projects/UnusedResources.mongodb, line 15 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1155#-MkoUhk75kWj7ZELQIke:-MkoUhk75kWj7ZELQIkf:b9e9qbm) ([raw file](https://github.com/sillsdev/web-xforge/blob/b24d083e1347cc52c362fe97c8a49cdacf2489cf/mongodb/Projects/UnusedResources.mongodb#L15)):*
> ```
> 
> resources.filter(
>   resource => !projectsBasedOnOthers.some(project => project.translateConfig.source.projectRef === resource._id)
> ```

You should also check `project.translateConfig.translationSuggestionsEnabled`. If the suggestions aren't enabled it doesn't matter if a project is specified since the resource should still be free to be deleted.


<!-- Sent from Reviewable.io -->

2021-09-30 18:19 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1155)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[mongodb/Projects/UnusedResources.mongodb, line 15 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1155#-MkoUhk75kWj7ZELQIke:-MkrmE5504LXO98dFyiA:bro1o7z) ([raw file](https://github.com/sillsdev/web-xforge/blob/37a7e4e768a10886c7c3d0cc2fb3829184f47236/mongodb/Projects/UnusedResources.mongodb#L15)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

You should also check `project.translateConfig.translationSuggestionsEnabled`. If the suggestions aren't enabled it doesn't matter if a project is specified since the resource should still be free to be deleted.
</blockquote></details>

What happens when someone re-enables translation suggestions? Are we certain it will properly reconnect the resource? I didn't look for projects with a connected resource and translation suggestions disabled, because I wasn't sure about this, and also because the problem is proliferation of unused resources, not a need to remove every unused resource.


<!-- Sent from Reviewable.io -->

2021-10-01 03:11 UTC, irahopkinson approved these changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1155)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

___
*[mongodb/Projects/UnusedResources.mongodb, line 15 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1155#-MkoUhk75kWj7ZELQIke:-Mkt_1UH4Py5gX5nJp_x:b-k4mobb) ([raw file](https://github.com/sillsdev/web-xforge/blob/adab30edeadee40d3b4fce1fa4bad2d289deed64/mongodb/Projects/UnusedResources.mongodb#L15)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

What happens when someone re-enables translation suggestions? Are we certain it will properly reconnect the resource? I didn't look for projects with a connected resource and translation suggestions disabled, because I wasn't sure about this, and also because the problem is proliferation of unused resources, not a need to remove every unused resource.
</blockquote></details>

I haven't tested this personably but our "delete project" dialog allows deleting resources as long as the suggestions are disabled even if its still referenced. I'm pretty sure at that point it removes the reference. So since we won't be doing that here we shouldn't included it so good to go then.


<!-- Sent from Reviewable.io -->

2021-10-01 03:31 UTC, merged

2021-10-04 11:54 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1155)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[mongodb/Projects/UnusedResources.mongodb, line 15 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1155#-MkoUhk75kWj7ZELQIke:-MlA30t8-kcDysskreO5:b-2m5jaj) ([raw file](https://github.com/sillsdev/web-xforge/blob/adab30edeadee40d3b4fce1fa4bad2d289deed64/mongodb/Projects/UnusedResources.mongodb#L15)):*
> So since we won't be doing that here we shouldn't included it so good to go then.
We're not actually deleting them here; we're listing resource that can be deleted. The actual deleting happens via the settings page, which properly cleans things up if I understand correctly.


<!-- Sent from Reviewable.io -->

2021-10-04 11:57 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1155)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[mongodb/Projects/UnusedResources.mongodb, line 15 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1155#-MkoUhk75kWj7ZELQIke:-MlA9EHy158z3GodYDRy:bvnyprk) ([raw file](https://github.com/sillsdev/web-xforge/blob/adab30edeadee40d3b4fce1fa4bad2d289deed64/mongodb/Projects/UnusedResources.mongodb#L15)):*
Previous comment was formatted incorrectly. Should have been as below:

>So since we won't be doing that here we shouldn't included it so good to go then.

We're not actually deleting them here; we're listing resource that can be deleted. The actual deleting happens via the settings page, which properly cleans things up if I understand correctly.


<!-- Sent from Reviewable.io -->