SF-1413 Notes respond to realtime remote edits
sillsdev/web-xforge pull request #1172
Opened 2021-10-25 22:11 UTC by RaymondLuong3

* detect when an update is local
* apply remote updates to current editor content
* update adjustDeltaForEmbeddedElements to handle converting to text doc and from text doc
* move method for getting the editor position to text view model

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1172)

2021-11-01 04:12 UTC, irahopkinson requested changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1172)* status: all files reviewed, 6 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts, line 574 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-MmutC3LDkPqPKxtQZIW:-MnOgER83dmyM_ZCG7Lj:b3f9f0s) ([raw file](https://github.com/sillsdev/web-xforge/blob/46215c7f760e8f117dab880aa711754afc5885ad/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L574)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I wrestled to decide whether to make two separate methods, or just one. I see that with two separate method, it would be clearer what is happening. removeEmbeddedElementsFromDelta will remove any embedded elements from the delta so that the delta can be applied to the text doc (since text docs are unaware of embeded notes). AddEmbeddedElementsToDelta will add the embeds to the retain and delete ops in a delta so the delta can be applied to the current view of the content in the editor. Since the editor may contain note embeds, we need to account for that.
</blockquote></details>

I think splitting helps with the readability, however I don't understand enough of what is going on conceptually. Either you could walk me through it or another developer who understands the concepts should review it.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts, line 652 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-MnOdB_y5cabFhHkbx9v:-MnOdB_y5cabFhHkbx9w:b-pjoxnp) ([raw file](https://github.com/sillsdev/web-xforge/blob/ee17dae3dc6df82fb625f5479be4ccb4f518c5ca/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L652)):*
> ```
> const indices: number[] = Array.from(this._embeddedElements.values());
> ```
I don't think you need to use `Array.from` since the `values90` method already gives you an iterable. Is this a hangover from the previous refactor?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 617 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-Mmufq_42DgkJeklv3HA:-MnOEjlU-zo-1AdIdzWB:bdxzsq8) ([raw file](https://github.com/sillsdev/web-xforge/blob/46215c7f760e8f117dab880aa711754afc5885ad/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L617)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I took a look at how involved it would be to make a subclass of Editor component. It soon became obvious it would not be trivially easy. I might be tempted to do it, but it seems that exposing this method as public won't do us any harm. What do you think?
</blockquote></details>

Yeah, I think you are right.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1529 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-Mmukjd1DijuZ3iXHIwG:-MnOKySZ1tOGe8sRWkUh:b-ym8my5) ([raw file](https://github.com/sillsdev/web-xforge/blob/46215c7f760e8f117dab880aa711754afc5885ad/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1529)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Hey, it turns out if I think of it differently, and use a note icon as a reference point for where a selection begins, I can explain why a remote edit is at the index that it is in a clear way. I was thinking about it in a totally upside-down way.
</blockquote></details>

Great, that's much clearer (and maintainable).
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1532 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-MnOVchA8ah96UGqXONo:-MnOVchA8ah96UGqXONp:bsdpeh3) ([raw file](https://github.com/sillsdev/web-xforge/blob/ee17dae3dc6df82fb625f5479be4ccb4f518c5ca/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1532)):*
> ```
> let remoteEditPosition: number = notePosition + positionRelativeToNote - localNoteCount;
> ```
You could make this DRY-er since it's used 3 times and the formulae shouldn't change. Perhaps use a getter or a function call directly?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1543 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-MnORQQpE6-ETktc3yDn:-MnORQQpE6-ETktc3yDo:b-7k717g) ([raw file](https://github.com/sillsdev/web-xforge/blob/ee17dae3dc6df82fb625f5479be4ccb4f518c5ca/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1543)):*
> ```
> // (1)target: + (2)$ + (3)chapabcter 1 + (4), verse 1.
> ```
I don't immediately understand what the parenthesis, numbers and plus mean? From the comment above I have inferred that $ is a note and | is the insert position. After a bit, it looks like you are indicating the 4 ops. Perhaps a commenting key would help?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1549 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-MnOUwgt4TORNPpIXSqS:-MnOUwgt4TORNPpIXSqT:b-dekf2x) ([raw file](https://github.com/sillsdev/web-xforge/blob/ee17dae3dc6df82fb625f5479be4ccb4f518c5ca/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1549)):*
> ```
> localNoteCount = 2;
> ```
The comment below has 3 local notes but there is only one before the selection. Why is this 2?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1551 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-MnOVL_o-mT_MFxUyP7X:-MnOVL_o-mT_MFxUyP7Y:bk4qkvk) ([raw file](https://github.com/sillsdev/web-xforge/blob/ee17dae3dc6df82fb625f5479be4ccb4f518c5ca/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1551)):*
> ```
> // $targ|->et: chap<-|ter 1, $$verse 3.
> ```
Looks like the end selection is too far to the right by one character 'p'.


<!-- Sent from Reviewable.io -->

2021-11-01 20:50 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1172)* status: all files reviewed, 6 unresolved discussions (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts, line 574 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-MmutC3LDkPqPKxtQZIW:-MnSFy5QDph9zwJxQGZ0:b-dl9ni2) ([raw file](https://github.com/sillsdev/web-xforge/blob/46215c7f760e8f117dab880aa711754afc5885ad/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L574)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I think splitting helps with the readability, however I don't understand enough of what is going on conceptually. Either you could walk me through it or another developer who understands the concepts should review it.
</blockquote></details>

I'll see if I can poke Mark into reviewing this.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts, line 652 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-MnOdB_y5cabFhHkbx9v:-MnSBPXv2u0wx7s_Djeb:b-cxwlbi) ([raw file](https://github.com/sillsdev/web-xforge/blob/ee17dae3dc6df82fb625f5479be4ccb4f518c5ca/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L652)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> const indices: number[] = Array.from(this._embeddedElements.values());
> ```
I don't think you need to use `Array.from` since the `values90` method already gives you an iterable. Is this a hangover from the previous refactor?
</blockquote></details>

Good thinking. I've flattened this out.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1532 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-MnOVchA8ah96UGqXONo:-MnSFdJk2GsBEyGy43mg:b6pm8eo) ([raw file](https://github.com/sillsdev/web-xforge/blob/ee17dae3dc6df82fb625f5479be4ccb4f518c5ca/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1532)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> let remoteEditPosition: number = notePosition + positionRelativeToNote - localNoteCount;
> ```
You could make this DRY-er since it's used 3 times and the formulae shouldn't change. Perhaps use a getter or a function call directly?
</blockquote></details>

I've created a method that can be reused.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1543 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-MnORQQpE6-ETktc3yDn:-MnSDr409-Samubc-NGo:b2o1jax) ([raw file](https://github.com/sillsdev/web-xforge/blob/ee17dae3dc6df82fb625f5479be4ccb4f518c5ca/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1543)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> // (1)target: + (2)$ + (3)chapabcter 1 + (4), verse 1.
> ```
I don't immediately understand what the parenthesis, numbers and plus mean? From the comment above I have inferred that $ is a note and | is the insert position. After a bit, it looks like you are indicating the 4 ops. Perhaps a commenting key would help?
</blockquote></details>

I made it a little more obvious by using square brackets and 0-based numbering. Any clearer?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1549 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-MnOUwgt4TORNPpIXSqS:-MnSEY0z1KV787h33sRs:b-w4mcst) ([raw file](https://github.com/sillsdev/web-xforge/blob/ee17dae3dc6df82fb625f5479be4ccb4f518c5ca/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1549)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> localNoteCount = 2;
> ```
The comment below has 3 local notes but there is only one before the selection. Why is this 2?
</blockquote></details>

This is the number of notes that come before a desired position. In this case, there is a note on verse 1, and a note at the beginning of verse 3. Those 2 notes come before our desired selection. To get the position in the text doc corresponding to that same position in the editor, the 2 notes would need to be subtracted. I've updated the name to be more descriptive.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1551 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-MnOVL_o-mT_MFxUyP7X:-MnSFYPD62MmcVoFHIpL:b-34yyl6) ([raw file](https://github.com/sillsdev/web-xforge/blob/ee17dae3dc6df82fb625f5479be4ccb4f518c5ca/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1551)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> // $targ|->et: chap<-|ter 1, $$verse 3.
> ```
Looks like the end selection is too far to the right by one character 'p'.
</blockquote></details>

Good eye, you are right.


<!-- Sent from Reviewable.io -->

2021-11-02 07:26 UTC, irahopkinson requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1172)* status: all files reviewed, 3 unresolved discussions (waiting on @irahopkinson and @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1543 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-MnORQQpE6-ETktc3yDn:-MnUUH7d4MG9yGVvQecC:br4fuc5) ([raw file](https://github.com/sillsdev/web-xforge/blob/ee17dae3dc6df82fb625f5479be4ccb4f518c5ca/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1543)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I made it a little more obvious by using square brackets and 0-based numbering. Any clearer?
</blockquote></details>

Better
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1549 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-MnOUwgt4TORNPpIXSqS:-MnUUwIh3UUu1hG4Zszc:b-4eafnl) ([raw file](https://github.com/sillsdev/web-xforge/blob/ee17dae3dc6df82fb625f5479be4ccb4f518c5ca/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1549)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This is the number of notes that come before a desired position. In this case, there is a note on verse 1, and a note at the beginning of verse 3. Those 2 notes come before our desired selection. To get the position in the text doc corresponding to that same position in the editor, the 2 notes would need to be subtracted. I've updated the name to be more descriptive.
</blockquote></details>

Ok, but there are 2 notes before 'verse 3', not just one like you have described. It's still not obvious why only one of those last 2 notes counts? And it appears from your comment that the selection range is way before those last 2 notes anyway? In the test below the range covers the last 2 notes but there is only the first 2 notes counted still?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1548 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-MnUULiT4cw7kPcjDu2p:-MnUULiT4cw7kPcjDu2q:bq3jzy0) ([raw file](https://github.com/sillsdev/web-xforge/blob/00577bcd002cf35e9f79e2a5c99ddf3cc8b628b7/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1548)):*
> ```
> target:,
> ```
Missing a space, i.e. should be 'target: ,'


<!-- Sent from Reviewable.io -->

2021-11-03 16:54 UTC, marksvc requested changes
Thanks for your work on this. 

> Reviewed 3 of 5 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-:-MnagJee117WpoZRWAv_:btksj3a)* status: all files reviewed, 16 unresolved discussions (waiting on @irahopkinson and @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts, line 586 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-MnXg-XZ9CrDxqZS-MSP:-MnXg-XZ9CrDxqZS-MSQ:bko06lh) ([raw file](https://github.com/sillsdev/web-xforge/blob/00577bcd002cf35e9f79e2a5c99ddf3cc8b628b7/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L586)):*
> ```XML
>       let cloneOp: DeltaOperation | undefined = cloneDeep(op);
>       if (cloneOp.retain != null) {
>         const embedsInRange: number = this.getEmbedsInEditorRange(curIndex, cloneOp.retain);
> ```

Yay. I like that the method name makes it clear that it's using editor positioning, and that it's now using (index,length).
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts, line 597 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-MnXgObS4F1t4sJytDQn:-MnXgObS4F1t4sJytDQo:bgnc9ip) ([raw file](https://github.com/sillsdev/web-xforge/blob/00577bcd002cf35e9f79e2a5c99ddf3cc8b628b7/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L597)):*
> ```XML
>         if (cloneOp.delete < 1) {
>           cloneOp = undefined;
>         }
> ```

Hmm, would there not be an insert op that would include the embeds, that might also need accounted for here?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts, line 620 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-MnXYLp28HZJNEuR99iD:-MnXYLp3C54FrMymOLxG:byk6oz3) ([raw file](https://github.com/sillsdev/web-xforge/blob/00577bcd002cf35e9f79e2a5c99ddf3cc8b628b7/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L620)):*
> ```XML
>     let embedsUpToIndex: number = 0;
>     for (const op of modelDelta.ops) {
>       let cloneOp: DeltaOperation | undefined = cloneDeep(op);
> ```

Why are you cloning and making a new DeltaStatic instead of re-using the existing DeltaStatic object and its ops?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts, line 635 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-MnXbwT93OBZQb7e3Jvu:-MnXbwT93OBZQb7e3Jvv:byewp0e) ([raw file](https://github.com/sillsdev/web-xforge/blob/00577bcd002cf35e9f79e2a5c99ddf3cc8b628b7/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L635)):*
> ```XML
>         // add to the delete op the number of embedded elements contained in its content
>         cloneOp.delete += embedsInRange;
>         if (cloneOp.delete < 1) {
> ```

Wow does that happen that there is a delete but it is for <=0 characters?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts, line 669 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-MnXhzibBsHx1WSPU5vi:-MnXhzibBsHx1WSPU5vj:b-f7r8wz) ([raw file](https://github.com/sillsdev/web-xforge/blob/00577bcd002cf35e9f79e2a5c99ddf3cc8b628b7/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L669)):*
> ```
>  positionWithoutEmbeds 
> ```

I think this variable name is misleading, because `editorStartIndex` will include embeds in its position information (if I'm correct). 
What do you think about re-working the method like the following?

```ts
// End position that includes embeds
const editorEndPos:number = this.getEditorPositionPlusTextPosition(editorStartIndex, length);
const lengthWithEmbeds:number = editorEndPos - editorStartIndex    
const countOfEmbeds:number = lengthWithEmbeds - length
return countOfEmbeds
```
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 562 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-MnadoIg1PIGJqW0wZAE:-MnadoIg1PIGJqW0wZAF:bgd9ar7) ([raw file](https://github.com/sillsdev/web-xforge/blob/00577bcd002cf35e9f79e2a5c99ddf3cc8b628b7/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L562)):*
> ```
>  endPosition
> ```

I do find that it's easier to think of the "position" in the editor rather than the "index" in the editor.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 580 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-MnafoBS1XfTwY71ZBKD:-MnafoBS1XfTwY71ZBKE:b-76cgga) ([raw file](https://github.com/sillsdev/web-xforge/blob/00577bcd002cf35e9f79e2a5c99ddf3cc8b628b7/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L580)):*
> ```XML
>     if (delta.ops != null && delta.ops.some(op => op.insert != null || op.delete != null)) {
>       const isUserEdit: boolean = source === 'user';
>       this.update(delta, isUserEdit);
> ```

Hmm. It might be worth showing in the spec that when `onContentChanged()` is called, we `updated.emit({islocalUpdate:true})`.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 115 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-MnackRO-B9BJFyl1zZF:-MnackRO-B9BJFyl1zZG:b-usq6uw) ([raw file](https://github.com/sillsdev/web-xforge/blob/46215c7f760e8f117dab880aa711754afc5885ad/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L115)):*
> ```
> private shouldNoteThreadsRespondToEdits: boolean = false;
> ```

Ahh, I like this renaming.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 491 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-MnaXf9zDL-7Vjd-biie:-MnaXf9zDL-7Vjd-biif:b-hx7vna) ([raw file](https://github.com/sillsdev/web-xforge/blob/46215c7f760e8f117dab880aa711754afc5885ad/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L491)):*
> ```
>  && isLocalUpdate)
> ```

I had to think and remember why the reason for this is: It's that the remote user, who authored the edit, their computer will have recomputed note positions and sent them separately (via probably a NoteThreadDoc). And so we don't process the anchor updating again on every client. Hmm. I'm undecided as to whether there should be a comment about that. 
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 491 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-MnaYWe37_GOu6Z73aOj:-MnaYWe37_GOu6Z73aOk:b-mpdp1u) ([raw file](https://github.com/sillsdev/web-xforge/blob/46215c7f760e8f117dab880aa711754afc5885ad/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L491)):*
> ```
>  && isLocalUpdate
> ```

This would be good to show in the spec, that:
- a remote edit coming in for the current segment does not result in locally updating thread anchors, but does re-create deleted note thread embeds  
  - when the 'current segment' === the previous segment.
  - when the 'current segment' !== the previous segment.
- A remote edit coming in for a _different_ segment than the "current" one does not result in localy updating thread anchors, but does re-create deleted note thread embeds 
  - when the 'current segment' === the previous segment.
  - when the 'current segment' !== the previous segment.
- A local edit coming in for the current segment does result, and does result.
  - when the 'current segment' === the previous segment.
  - when the 'current segment' !== the previous segment.

And.. maybe after we think about those permutations a bit we'll end up re-writing parts of this method :/ ?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 617 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-Mmufq_42DgkJeklv3HA:-MnXlG2A4GjcK45iCIyM:b-9phlw) ([raw file](https://github.com/sillsdev/web-xforge/blob/46215c7f760e8f117dab880aa711754afc5885ad/src/SIL.XForge.Scripture/C [...]

2021-11-04 21:29 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1172)* status: all files reviewed, 16 unresolved discussions (waiting on @irahopkinson and @marksvc)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts, line 597 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-MnXgObS4F1t4sJytDQn:-MnfcQCa9oa06kHagmfv:b-nn6nqx) ([raw file](https://github.com/sillsdev/web-xforge/blob/00577bcd002cf35e9f79e2a5c99ddf3cc8b628b7/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L597)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Hmm, would there not be an insert op that would include the embeds, that might also need accounted for here?
</blockquote></details>

There could be embeds if a user decides to undo the deletion of an embed. That will come in another task I am working on.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts, line 620 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-MnXYLp28HZJNEuR99iD:-MnfdoiL1ntYvrn4KW-v:b8gagpr) ([raw file](https://github.com/sillsdev/web-xforge/blob/00577bcd002cf35e9f79e2a5c99ddf3cc8b628b7/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L620)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Why are you cloning and making a new DeltaStatic instead of re-using the existing DeltaStatic object and its ops?
</blockquote></details>

I don't remember why I made that choice to clone and an entirely new DeltaStatic. I wouldn't be opposed to modifying the original DeltaStatic rather than creating a new one. I believe meant to follow the example of viewToData() which modifies a copy of the delta.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts, line 635 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-MnXbwT93OBZQb7e3Jvu:-MnfeWGPBS5x_kJLXgsm:b-wf359i) ([raw file](https://github.com/sillsdev/web-xforge/blob/00577bcd002cf35e9f79e2a5c99ddf3cc8b628b7/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L635)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Wow does that happen that there is a delete but it is for <=0 characters?
</blockquote></details>

The delete could be 0, in the case that a user deletes an embedded note. If it is 0, I've seen something strange happen, where the operation deletes the range of text in the previous retain op. Very strange indeed.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts, line 669 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-MnXhzibBsHx1WSPU5vi:-Mnfiz_kAytz8NBvO4h2:b-9fmn3c) ([raw file](https://github.com/sillsdev/web-xforge/blob/00577bcd002cf35e9f79e2a5c99ddf3cc8b628b7/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L669)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
>  positionWithoutEmbeds 
> ```

I think this variable name is misleading, because `editorStartIndex` will include embeds in its position information (if I'm correct). 
What do you think about re-working the method like the following?

```ts
// End position that includes embeds
const editorEndPos:number = this.getEditorPositionPlusTextPosition(editorStartIndex, length);
const lengthWithEmbeds:number = editorEndPos - editorStartIndex    
const countOfEmbeds:number = lengthWithEmbeds - length
return countOfEmbeds
```
</blockquote></details>

Good suggestion. Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 562 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-MnadoIg1PIGJqW0wZAE:-Mnfj4OtByMlG7VT15Lw:b9m0o6r) ([raw file](https://github.com/sillsdev/web-xforge/blob/00577bcd002cf35e9f79e2a5c99ddf3cc8b628b7/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L562)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
>  endPosition
> ```

I do find that it's easier to think of the "position" in the editor rather than the "index" in the editor.
</blockquote></details>

Yes, I used to think in terms of index, but now I am finding that consistently using position has helps me to think in that term now.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 580 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-MnafoBS1XfTwY71ZBKD:-MnfmQEw8Bc6DVDTxv74:b-bbs27z) ([raw file](https://github.com/sillsdev/web-xforge/blob/00577bcd002cf35e9f79e2a5c99ddf3cc8b628b7/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L580)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Hmm. It might be worth showing in the spec that when `onContentChanged()` is called, we `updated.emit({islocalUpdate:true})`.
</blockquote></details>

I think this is reasonably covered. If I reverse the check for isLocalUpdate in `editor.component.ts` and check that it is not a local update, I get 10 test failure. That should be enough to show that it is emitting as expected.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 491 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-MnaXf9zDL-7Vjd-biie:-Mnfn2mJ3NJ3oRKdsYks:bs49sb9) ([raw file](https://github.com/sillsdev/web-xforge/blob/46215c7f760e8f117dab880aa711754afc5885ad/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L491)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
>  && isLocalUpdate)
> ```

I had to think and remember why the reason for this is: It's that the remote user, who authored the edit, their computer will have recomputed note positions and sent them separately (via probably a NoteThreadDoc). And so we don't process the anchor updating again on every client. Hmm. I'm undecided as to whether there should be a comment about that. 
</blockquote></details>

That's correct, only for the user who makes the edits will the text anchor be updated. I'll add a comment so that we don't forget the reasoning.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 491 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-MnaYWe37_GOu6Z73aOj:-MngqHNT5ea7y-K5h8kw:b-jic3k9) ([raw file](https://github.com/sillsdev/web-xforge/blob/46215c7f760e8f117dab880aa711754afc5885ad/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L491)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
>  && isLocalUpdate
> ```

This would be good to show in the spec, that:
- a remote edit coming in for the current segment does not result in locally updating thread anchors, but does re-create deleted note thread embeds  
  - when the 'current segment' === the previous segment.
  - when the 'current segment' !== the previous segment.
- A remote edit coming in for a _different_ segment than the "current" one does not result in localy updating thread anchors, but does re-create deleted note thread embeds 
  - when the 'current segment' === the previous segment.
  - when the 'current segment' !== the previous segment.
- A local edit coming in for the current segment does result, and does result.
  - when the 'current segment' === the previous segment.
  - when the 'current segment' !== the previous segment.

And.. maybe after we think about those permutations a bit we'll end up re-writing parts of this method :/ ?

</blockquote></details>

Ok, I did some testing and I could not come up with a scenario where a remote edit occurs, and current segment !== previous segment. In this case, we can stick to testing the scenario where the current segment === previous segment. I've added a test for the remote edit scenarios. The local edit scenario is already covered by tests.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor [...]

2021-11-08 05:15 UTC, irahopkinson reviewed
This looks good. I haven't marked any files as read so @marksvc can finish his review.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-:-Mnxxwn04PMyBMQVZn-d:b-umit17)* status: 1 of 5 files reviewed, 14 unresolved discussions (waiting on @irahopkinson, @marksvc, and @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 617 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-Mmufq_42DgkJeklv3HA:-MnxrcMACsS98_dYDB-7:b-28wm3p) ([raw file](https://github.com/sillsdev/web-xforge/blob/46215c7f760e8f117dab880aa711754afc5885ad/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L617)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Another option is to keep private here: 
```ts
private removeEmbeddedElements()
```
and in the test, call the method after casting the object: 
```ts
(env.component as any).removeEmbeddedElements()
```

</blockquote></details>

@marksvc your suggestion works but because it breaks type checking we should only use it where necessary. Generally if a method doesn't need to be public we keep it private and only make it public if it needs to be used externally. But there are really good reasons to keep some things private even though it makes testing hard - that would be a good reason to use your suggestion. In this case though, although there is no reason other than testing to make it public, there is also no reasons to want to keep it private.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1549 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-MnOUwgt4TORNPpIXSqS:-Mnxwe-U2-DRjaAjRk0Y:b580kfp) ([raw file](https://github.com/sillsdev/web-xforge/blob/ee17dae3dc6df82fb625f5479be4ccb4f518c5ca/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1549)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

You may be confusing the notes in the comment with the notes I'm referring to. There are 3 notes in verse 3, but only the first note counts as being BEFORE the selection. As you pointed out, those two notes on `verse 3` do not count to be before the selection. So that is one note at the beginning of verse 3, and one note on VERSE 1. Two notes in total that come BEFORE the selection.
</blockquote></details>

Got it, thanks, the note count is per chapter, not per verse. How about a comment that says the count of 2 is 1 from verse 1 and 1 from the note in this verse (3) that is before the selection point?


<!-- Sent from Reviewable.io -->

2021-11-08 21:59 UTC, marksvc requested changes
I have some naming + clarity comments, and then good to go. 

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-:-Mo0YrLxAH4cepniLvgi:b923czp)* status: all files reviewed, 4 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 617 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-Mmufq_42DgkJeklv3HA:-Mo0XA815Abqsm23VR4z:b7x9iti) ([raw file](https://github.com/sillsdev/web-xforge/blob/46215c7f760e8f117dab880aa711754afc5885ad/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L617)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

@marksvc your suggestion works but because it breaks type checking we should only use it where necessary. Generally if a method doesn't need to be public we keep it private and only make it public if it needs to be used externally. But there are really good reasons to keep some things private even though it makes testing hard - that would be a good reason to use your suggestion. In this case though, although there is no reason other than testing to make it public, there is also no reasons to want to keep it private.
</blockquote></details>

Okay. Thanks. 
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1591 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-Mo0Nu6AD7pFxlzlaLmy:-Mo0Nu6AD7pFxlzlaLmz:bt7f6vd) ([raw file](https://github.com/sillsdev/web-xforge/blob/9f8ffea1d70335a4f79f3eea7c88e68979680f19/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1591)):*
> ```
>  6 characters deleted locally
> ```

If we want to say 6 somethings get deleted here, it may be inconsistent or not helpful to say "characters". It is 4 characters that are deleted (well, 4 .. things that have text codepoints), and two embeds of length 1. "Characters" may be nice to reserve for referring to things that would also show up in the text doc. 
What do you think of changing this comment to something like one of the following? 
- editor range deleted
- editor range of 6 deleted
- 4 characters, and the 2 embeds between them, deleted
- 6 editor positions deleted
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1627 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-Mo0RSGB65vGlDw4FB4v:-Mo0RSGCEEvmZSGRv-Dv:b-b7hu5g) ([raw file](https://github.com/sillsdev/web-xforge/blob/9f8ffea1d70335a4f79f3eea7c88e68979680f19/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1627)):*
> ```
> AfterNote
> ```

Oh, naming. So what we mean here is the position _relative to the beginning of the note embed_, right? Because the editor position _after_ the note embed is 1 (I think). `v` would be 0 after it, and `e` would be 1 after it. And I'm the one who gave the variable name `remoteEditPositionAfterNote`; what can you do? :-)
I must not have counted last time to see the discrepancy. 
Your earlier variable name,  positionRelativeToNote, captured some good aspects of this. 
I'm trying to think of a better variable name to use, but I think we are being limited by the helper function. 
I don't want to be too pedantic :), but what do you think about changing `getRemoteEditPosition()` to instead `    return notePosition + 1 + positionAfter - noteCount;`, and then make the `remoteEditPositionAfterNote` variable keep the same variable name, but decrease all their values by 1? (For example here, it would say `let remoteEditPositionAfterNote: number = 1;`.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1628 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-Mo0Rp7PB8nDDAo4Th3s:-Mo0Rp7PB8nDDAo4Th3t:b-v0pvay) ([raw file](https://github.com/sillsdev/web-xforge/blob/9f8ffea1d70335a4f79f3eea7c88e68979680f19/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1628)):*
> ```
> noteCountBeforePosition: number = 4;
> ```

That's kind of confusing. Maybe a comment should say `// (Including a note before this verse)` if that's the reason for 4 instead of 3.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1660 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-Mo0SWYF5b8bo7iraas5:-Mo0SWYF5b8bo7iraas6:bn1m3qc) ([raw file](https://github.com/sillsdev/web-xforge/blob/9f8ffea1d70335a4f79f3eea7c88e68979680f19/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1660)):*
> ```
> ('target: c' + 'def' + 'hapter 1, v
> ```

This, and the `|` character in 
>    // target: $c|hapter 1, verse 1.

provide helpful clarity.


<!-- Sent from Reviewable.io -->

2021-11-12 21:10 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1172)* status: all files reviewed, 4 unresolved discussions (waiting on @irahopkinson and @marksvc)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1549 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-MnOUwgt4TORNPpIXSqS:-MoKwE_5D828BIam0USC:b-rfkwhz) ([raw file](https://github.com/sillsdev/web-xforge/blob/ee17dae3dc6df82fb625f5479be4ccb4f518c5ca/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1549)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Got it, thanks, the note count is per chapter, not per verse. How about a comment that says the count of 2 is 1 from verse 1 and 1 from the note in this verse (3) that is before the selection point?
</blockquote></details>

I can add a comment.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1591 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-Mo0Nu6AD7pFxlzlaLmy:-MoKwQFMAXeRpa48JCJF:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/9f8ffea1d70335a4f79f3eea7c88e68979680f19/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1591)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
>  6 characters deleted locally
> ```

If we want to say 6 somethings get deleted here, it may be inconsistent or not helpful to say "characters". It is 4 characters that are deleted (well, 4 .. things that have text codepoints), and two embeds of length 1. "Characters" may be nice to reserve for referring to things that would also show up in the text doc. 
What do you think of changing this comment to something like one of the following? 
- editor range deleted
- editor range of 6 deleted
- 4 characters, and the 2 embeds between them, deleted
- 6 editor positions deleted


</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1627 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-Mo0RSGB65vGlDw4FB4v:-MoKxf5n85TE4WA8NaAG:b-soahpz) ([raw file](https://github.com/sillsdev/web-xforge/blob/9f8ffea1d70335a4f79f3eea7c88e68979680f19/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1627)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
> AfterNote
> ```

Oh, naming. So what we mean here is the position _relative to the beginning of the note embed_, right? Because the editor position _after_ the note embed is 1 (I think). `v` would be 0 after it, and `e` would be 1 after it. And I'm the one who gave the variable name `remoteEditPositionAfterNote`; what can you do? :-)
I must not have counted last time to see the discrepancy. 
Your earlier variable name,  positionRelativeToNote, captured some good aspects of this. 
I'm trying to think of a better variable name to use, but I think we are being limited by the helper function. 
I don't want to be too pedantic :), but what do you think about changing `getRemoteEditPosition()` to instead `    return notePosition + 1 + positionAfter - noteCount;`, and then make the `remoteEditPositionAfterNote` variable keep the same variable name, but decrease all their values by 1? (For example here, it would say `let remoteEditPositionAfterNote: number = 1;`.


</blockquote></details>

Ok, I'll add the + 1 to the position so that positions are 0-indexed positions again.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1628 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-Mo0Rp7PB8nDDAo4Th3s:-MoKyByK2xGRO7UXMbIf:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/9f8ffea1d70335a4f79f3eea7c88e68979680f19/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1628)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
> noteCountBeforePosition: number = 4;
> ```

That's kind of confusing. Maybe a comment should say `// (Including a note before this verse)` if that's the reason for 4 instead of 3.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-12 21:30 UTC, marksvc approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1172)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)



<!-- Sent from Reviewable.io -->

2021-11-13 05:20 UTC, irahopkinson approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1172#-:-MoMjEX850dWX3XbeyJm:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2021-11-13 05:20 UTC, merged