Consider text footnotes length when calculating text anchor positions on sync
sillsdev/web-xforge pull request #1175
Opened 2021-10-28 18:22 UTC by RaymondLuong3

Footnotes, endnotes and cross references appear in the text with a special symbol. The quill editor has been designed to show this symbol as an embed in the editor. The embed takes up a length of 1, which means that on the backend when we synchronize and update our note thread text anchors, the text anchor position should also account for the symbol.

This uses a space "\0" on the backend to represent a non-text insert e.g. blanks, footnote, endnote or cross reference.
![image](https://user-images.githubusercontent.com/17931130/139313269-50b86774-aac1-4df2-86ed-92703e18f816.png)

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1175)

2021-11-01 05:56 UTC, irahopkinson requested changes
AFAIR we already handle these and we don't just use an asterisk, we use the symbol specified in PT.
In PT, ft:
![image copy 1.png](https://files.reviewableusercontent.io/images/reviewable/5582153/72rvs_QHdxsAptElv-sdUeMF/image.png)
and xo:
![image.png](https://files.reviewableusercontent.io/images/reviewable/5582153/sti0M49h-lGR94teLbYcuBd0/image.png)

In SF, ft:
![image copy 2.png](https://files.reviewableusercontent.io/images/reviewable/5582153/63WZFOQwNnZCFFwN85PSPinI/image.png)
and xo:
![image copy 3.png](https://files.reviewableusercontent.io/images/reviewable/5582153/qbsEY6xhKjMK73wws2XtVVYJ/image.png)

Is this just fixing how we sync notes or how the text is reported for the notes?

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1175#-:-MnOhVzLBr3YBytPbqag:bnusigj)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 1587 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1175#-MnOxhkk76FUmkORnO6e:-MnOxhkk76FUmkORnO6f:b-uz6usv) ([raw file](https://github.com/sillsdev/web-xforge/blob/516563f8e09ffc8476e6d6db3810df60ac6dc76b/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1587)):*
> ```
> bldr.Append("*");
> ```
Should this insert the actual note symbol rather than assuming an asterisk? I.e. use `(string)segmentObj["insert"]["note"]["caller"]`.


<!-- Sent from Reviewable.io -->

2021-11-01 05:58 UTC, irahopkinson requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1175)* status: all files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 1587 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1175#-MnP3pPz2IHqmbmPLS8P:-MnP3pPz2IHqmbmPLS8Q:bqlo7sn) ([raw file](https://github.com/sillsdev/web-xforge/blob/516563f8e09ffc8476e6d6db3810df60ac6dc76b/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1587)):*
> ```
> bldr.Append("*");
> ```
When I ran this code it only ran for `ft` elements and not for `xo`. I didn't check endnotes.


<!-- Sent from Reviewable.io -->

2021-11-18 18:47 UTC, RaymondLuong3 reviewed
Thanks for these screenshots. SF already displays cross references and footnotes. The issue that this addresses is the extra length that a footnote represents when a user syncs their project and the note thread text anchors get updated. Previously, if a verse has a footnote, the note threads would be anchored 1 character too soon. This makes it so that text anchors are updated correctly at synchronize time. footnotes, blanks, cross-references and any non-text inserts will be represented as a space "\0".
I've updated the Delta class to provide a way to filter for all ops in a verse so we can get the verse text that we give String.Utils.MatchContext to calculate the text anchor position using PtxUtils.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1175#-:-MooJSTV3A4iD0g2WYwr:bgsz5ts)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 1587 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1175#-MnOxhkk76FUmkORnO6e:-MooKuGR582_YZ9GvwD8:bnd91pu) ([raw file](https://github.com/sillsdev/web-xforge/blob/516563f8e09ffc8476e6d6db3810df60ac6dc76b/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1587)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> bldr.Append("*");
> ```
Should this insert the actual note symbol rather than assuming an asterisk? I.e. use `(string)segmentObj["insert"]["note"]["caller"]`.
</blockquote></details>

I've updated this functionality. It appears that the Delta class already provides a method to concatenate the ops of a verse. This now uses that existing functionality. The default substitute character for non-text insert ops will be \0. This is ok, since we are only interested in getting the verse text that can be used to calculate the note thread text anchor. Note thread text selections cannot include the non-text inserts (paratext does not allow this), so we do not need to be exact about the actual caller symbol. Only the existence of the symbol is important.
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 1587 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1175#-MnP3pPz2IHqmbmPLS8P:-MooM7VZAPLYAZy7ZeUn:bx7lft4) ([raw file](https://github.com/sillsdev/web-xforge/blob/516563f8e09ffc8476e6d6db3810df60ac6dc76b/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1587)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> bldr.Append("*");
> ```
When I ran this code it only ran for `ft` elements and not for `xo`. I didn't check endnotes.
</blockquote></details>

In my testing, this works for footnotes, endnotes and cross references. Any non-text element will be detected and represented by '\0'. Try inserting notes in a chapter with these markers, and let me know if you observe note threads in the correct places in text.


<!-- Sent from Reviewable.io -->

2021-11-18 18:56 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1175)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 1015 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1175#-MooO6705Dmgh3T6rhri:-MooO6705Dmgh3T6rhrj:b-936sq0) ([raw file](https://github.com/sillsdev/web-xforge/blob/2b29d2497f0b0fffd45de59db40ff3a60ab4d9e4/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1015)):*
> ```
>       deleteLength = delta.ops[1].delete;
> ```
We no longer need to check that the op occurred where the user's cursor is. That was here to prevent the deletion of a blank insert from being included into the text anchor positioning. But now blank ops are considered to have a text length of 1, so we if a blank is inserted or removed, we will correctly trigger the text anchor position to update.


<!-- Sent from Reviewable.io -->

2021-11-24 02:06 UTC, irahopkinson approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1175#-:-MpEgHx40-flrtbePxRx:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 1015 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1175#-MooO6705Dmgh3T6rhri:-MpEfnPIAsHMDFZ1QEpQ:b-2cak4l) ([raw file](https://github.com/sillsdev/web-xforge/blob/2b29d2497f0b0fffd45de59db40ff3a60ab4d9e4/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1015)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
>       deleteLength = delta.ops[1].delete;
> ```
We no longer need to check that the op occurred where the user's cursor is. That was here to prevent the deletion of a blank insert from being included into the text anchor positioning. But now blank ops are considered to have a text length of 1, so we if a blank is inserted or removed, we will correctly trigger the text anchor position to update.
</blockquote></details>

Perhaps consider a comment similar to the above in the code?
BTW your comment here is blocking. I guess that was unintentional but you should watch that when adding comments on your own PR.
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 1587 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1175#-MnP3pPz2IHqmbmPLS8P:-MpEdAtNEnXAn2IIPFDt:b-k6934c) ([raw file](https://github.com/sillsdev/web-xforge/blob/516563f8e09ffc8476e6d6db3810df60ac6dc76b/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1587)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

In my testing, this works for footnotes, endnotes and cross references. Any non-text element will be detected and represented by '\0'. Try inserting notes in a chapter with these markers, and let me know if you observe note threads in the correct places in text.
</blockquote></details>

I simply put a breakpoint on this code and then gave it a project with footnotes and cross references. It only hit the breakpoint on the footnotes. Your changes are specifically for notes so I didn't test it that way. So, if you have tested it and are happy with it that's good enough.


<!-- Sent from Reviewable.io -->

2021-11-26 16:31 UTC, RaymondLuong3 reviewed
Thanks for the review. I will do some testing on cross references and then I'll merge it once I confirm it is working.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1175#-:-MpS4JDL8wMOCgsoNf3S:b-2fgn5q)* status: 2 of 6 files reviewed, all discussions resolved (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 1015 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1175#-MooO6705Dmgh3T6rhri:-MpS410z9DArUeKbIEGs:b-t6cuba) ([raw file](https://github.com/sillsdev/web-xforge/blob/2b29d2497f0b0fffd45de59db40ff3a60ab4d9e4/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1015)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Perhaps consider a comment similar to the above in the code?
BTW your comment here is blocking. I guess that was unintentional but you should watch that when adding comments on your own PR.
</blockquote></details>

This is getting updated in the fix/duplicate-notes-undo branch, so I'll leave this as-is.
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 1587 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1175#-MnP3pPz2IHqmbmPLS8P:-MpS4AxwCYg2nj1A9maG:b7gk6s1) ([raw file](https://github.com/sillsdev/web-xforge/blob/516563f8e09ffc8476e6d6db3810df60ac6dc76b/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1587)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

I simply put a breakpoint on this code and then gave it a project with footnotes and cross references. It only hit the breakpoint on the footnotes. Your changes are specifically for notes so I didn't test it that way. So, if you have tested it and are happy with it that's good enough.
</blockquote></details>

Ok, I'll also give this a try and see if I get the same result.


<!-- Sent from Reviewable.io -->

2021-11-30 17:35 UTC, merged