SF-1323 - Hide note thread when a thread is resolved
sillsdev/web-xforge pull request #1189
Opened 2021-11-16 02:01 UTC by nigel-wells

- Sync note/comment status as well as thread status
- Hide resolved threads from translate app
- Show relevant note icon if one is set on the note
- Force a maximum width on note dialog

Existing notes may need to be deleted before a sync - I had hit this issue but it may have just been a bug that I fixed afterwards. I had concluded that this was fine as, once rolled out, no one would have had notes in the first place so it isn't an issue.

This is one of my first real PRs for working in the backend so please be gentle with your replies for changes :) Do let me know if there are much better ways in C# to tackle anything. One thing I wanted to do but couldn't figure out is have an array/list of strings that I iterate through to compare changes from a document to a PT comment. We appear to use the same names so it made sense. What I've currently done is copy & paste more or less the same IF statement when checking for updates - you'll see what I mean during the review.

2021-11-17 19:50 UTC, RaymondLuong3 requested changes
It looks like the coverage for the notes dialog could be improved. Other than that, I just have some minor requested changes. BTW your backend understanding not nearly as poor as you led on. Good work.

> Reviewed 18 of 19 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1189#-:-MojRVCs7m1CEiXW3cDx:b-ws45pt)* status: all files reviewed, 7 unresolved discussions (waiting on @nigel-wells)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts, line 124 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1189#-MojDmoV52T37OCUxqlp:-MojDmoV52T37OCUxqlq:biq2jti) ([raw file](https://github.com/sillsdev/web-xforge/blob/b707e9734bdf3f96b7980d3595a9560bd912ebce/src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts#L124)):*
> ```
>       [obj<NoteThread>().pathStr(t => t.status)]: NoteStatus.Todo
> ```
So this will hide notes with the unspecified status. I think this is ok, but good to keep in mind if there is a reason a note should be unspecified.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts, line 23 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1189#-MojHNEc6eYqiStJsa39:-MojHNEc6eYqiStJsa3A:bh7803s) ([raw file](https://github.com/sillsdev/web-xforge/blob/b707e9734bdf3f96b7980d3595a9560bd912ebce/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts#L23)):*
> ```
>   get iconResolved(): NoteThreadIcon {
> ```
When do you see the resolved note icon in Paratext? I haven't found a scenario where it shows in text, but I do see it if I open the notes list in Paratext. I must not be bumping into the correct scenario.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts, line 222 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1189#-MojJSt2BY2q3hXgZmJz:-MojJSt2BY2q3hXgZmK-:bbkvfi5) ([raw file](https://github.com/sillsdev/web-xforge/blob/b707e9734bdf3f96b7980d3595a9560bd912ebce/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts#L222)):*
> ```
>         dataId: 'note03',
> ```
Should this be note04? If so, then the test needs to be updated too.
___
*[src/SIL.XForge.Scripture/Models/NoteThreadChange.cs, line 55 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1189#-MojKpZADh2Nx91ca182:-MojKpZADh2Nx91ca183:b-2exa7h) ([raw file](https://github.com/sillsdev/web-xforge/blob/b707e9734bdf3f96b7980d3595a9560bd912ebce/src/SIL.XForge.Scripture/Models/NoteThreadChange.cs#L55)):*
> ```
>             Status = status;
> ```
This is here so that we can persist the current status of the note thread when something changes, correct? So if a note is added or edited, we can use this status to update the note thread doc status, regardless of if the status has been changed? Good.
___
*[src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, line 784 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1189#-MojQuxk1LGMFmPUSvyB:-MojQuxk1LGMFmPUSvyC:b-wubpai) ([raw file](https://github.com/sillsdev/web-xforge/blob/b707e9734bdf3f96b7980d3595a9560bd912ebce/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L784)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>                     if (threadDoc.Data.Status != change.Status)
>                     {
>                         op.Set(td => td.Status, change.Status);
>                     }
> ```
</details>

There are some brace inconsistencies in this method. Could you update this to not use braces for single line execution instructions under the if?
___
*[test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs, line 1833 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1189#-MojOct0-yzyitxFXJsX:-MojOct0-yzyitxFXJsY:b-8qgn6n) ([raw file](https://github.com/sillsdev/web-xforge/blob/b707e9734bdf3f96b7980d3595a9560bd912ebce/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L1833)):*
> ```
> "todo"
> ```
This should be NoteStatus.Todo.InternalValue.
___
*[test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs, line 1846 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1189#-MojOpZx4Mgtg5QU0MrW:-MojOpZx4Mgtg5QU0MrX:b-oifw1t) ([raw file](https://github.com/sillsdev/web-xforge/blob/b707e9734bdf3f96b7980d3595a9560bd912ebce/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L1846)):*
> ```
>  "deleted",
> ```
This should be NoteStatus.Deleted.InternalValue


<!-- Sent from Reviewable.io -->

2021-11-23 01:34 UTC, nigel-wells reviewed
Thanks for the feedback. I've addressed everything except the coverage which I'm looking in to now - will check on Slack as to the best way to view that in VS Code so I can see which paths I'm missing.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1189#-:-Mp9QN934EoQxYCLPdjC:b-u0gazs)* status: 15 of 19 files reviewed, 7 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts, line 124 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1189#-MojDmoV52T37OCUxqlp:-Mp9LgY7EuYx7G8YqPcL:b-ijvxrm) ([raw file](https://github.com/sillsdev/web-xforge/blob/b707e9734bdf3f96b7980d3595a9560bd912ebce/src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts#L124)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
>       [obj<NoteThread>().pathStr(t => t.status)]: NoteStatus.Todo
> ```
So this will hide notes with the unspecified status. I think this is ok, but good to keep in mind if there is a reason a note should be unspecified.
</blockquote></details>

Yep from my testing this seemed pretty consistent. It is also PT telling us the status of the thread rather than us deciding which is probably a good thing as well.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts, line 23 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1189#-MojHNEc6eYqiStJsa39:-Mp9LxStAzD5kV48Yx1g:bb1has5) ([raw file](https://github.com/sillsdev/web-xforge/blob/b707e9734bdf3f96b7980d3595a9560bd912ebce/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts#L23)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
>   get iconResolved(): NoteThreadIcon {
> ```
When do you see the resolved note icon in Paratext? I haven't found a scenario where it shows in text, but I do see it if I open the notes list in Paratext. I must not be bumping into the correct scenario.
</blockquote></details>

If you resolve the note and close the box it will then hide the flag from the text. You can then view a list of all notes in a table (in mine it appears under the text) and change the filter to `Resolved` or any other status/assignment. From there you can open it again to review the notes and, if you add a new one, the thread will become `todo` again.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts, line 222 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1189#-MojJSt2BY2q3hXgZmJz:-Mp9MUfkApSVT3hYeDMF:b-xexiza) ([raw file](https://github.com/sillsdev/web-xforge/blob/b707e9734bdf3f96b7980d3595a9560bd912ebce/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts#L222)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
>         dataId: 'note03',
> ```
Should this be note04? If so, then the test needs to be updated too.
</blockquote></details>

Copy and paste gets me again :) Fixed.
___
*[src/SIL.XForge.Scripture/Models/NoteThreadChange.cs, line 55 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1189#-MojKpZADh2Nx91ca182:-Mp9McdLCSuoqbjMXIMC:b-2b68q4) ([raw file](https://github.com/sillsdev/web-xforge/blob/b707e9734bdf3f96b7980d3595a9560bd912ebce/src/SIL.XForge.Scripture/Models/NoteThreadChange.cs#L55)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
>             Status = status;
> ```
This is here so that we can persist the current status of the note thread when something changes, correct? So if a note is added or edited, we can use this status to update the note thread doc status, regardless of if the status has been changed? Good.
</blockquote></details>

Correct and this appears to be how PT treats it as well.
___
*[src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, line 784 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1189#-MojQuxk1LGMFmPUSvyB:-Mp9MxtP3-9XE7UPnBnV:b4ubxe) ([raw file](https://github.com/sillsdev/web-xforge/blob/b707e9734bdf3f96b7980d3595a9560bd912ebce/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L784)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
>                     if (threadDoc.Data.Status != change.Status)
>                     {
>                         op.Set(td => td.Status, change.Status);
>                     }
> ```
There are some brace inconsistencies in this method. Could you update this to not use braces for single line execution instructions under the if?
</blockquote></details>

Done. What is the best practice for when there is an `if/else` and the `if` has multiple lines but the `else` doesn't - would we still add braces for the `else`?
___
*[test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs, line 1833 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1189#-MojOct0-yzyitxFXJsX:-Mp9NEAX3iyPJJnwGfB9:b-4pk5a8) ([raw file](https://github.com/sillsdev/web-xforge/blob/b707e9734bdf3f96b7980d3595a9560bd912ebce/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L1833)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> "todo"
> ```
This should be NoteStatus.Todo.InternalValue.
</blockquote></details>

I did initially try that but I got the error `Default parameter value for 'status' must be a compile-time constant`. I've tried again now and that error occurs if I try and set it as the default value in the method but not if I pass it to the method. Not sure why but at least I can change it where it is passed.
___
*[test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs, line 1846 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1189#-MojOpZx4Mgtg5QU0MrW:-Mp9OZR2-cwsJUM3O-Wq:b-aaibzu) ([raw file](https://github.com/sillsdev/web-xforge/blob/b707e9734bdf3f96b7980d3595a9560bd912ebce/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L1846)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
>  "deleted",
> ```
This should be NoteStatus.Deleted.InternalValue
</blockquote></details>

As per other note - have updated.


<!-- Sent from Reviewable.io -->

2021-11-23 03:22 UTC, nigel-wells reviewed
The backend coverage misses don't appear to be related to what I've been working on. I'll take a further look at the frontend ones.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1189#-:-Mp9o7Bn05PpS9gv4U4X:b-ilk0u6)* status: 15 of 19 files reviewed, 7 unresolved discussions (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2021-11-24 02:30 UTC, nigel-wells reviewed
I've added some extra testing. Interestingly when I checked coverage locally it reported better than what Codecov did above - perhaps it has moved on a bit since then? Anyway, it is better again.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1189#-:-MpElaJr4jT4TJXEwHQ1:b-eehp3a)* status: 14 of 19 files reviewed, 7 unresolved discussions (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2021-11-25 19:57 UTC, RaymondLuong3 approved these changes
Thanks for your work on this. I officially resolve this note :D

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1189#-:-MpNdfFqBE3TEkTvD5Np:b2tscgl)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts, line 23 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1189#-MojHNEc6eYqiStJsa39:-MpNdoFjAZiR9PgWeqDh:bhc43q5) ([raw file](https://github.com/sillsdev/web-xforge/blob/b707e9734bdf3f96b7980d3595a9560bd912ebce/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts#L23)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

If you resolve the note and close the box it will then hide the flag from the text. You can then view a list of all notes in a table (in mine it appears under the text) and change the filter to `Resolved` or any other status/assignment. From there you can open it again to review the notes and, if you add a new one, the thread will become `todo` again.
</blockquote></details>

Will this note ever appear in the text editor? I have seen it in Paratext just like you mentioned, but not in SF. It would be good to future-proof this though, so I'll be happy to make change.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts, line 222 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1189#-MojJSt2BY2q3hXgZmJz:-MpNe9ULADkcxo3_ZM-X:br72xz3) ([raw file](https://github.com/sillsdev/web-xforge/blob/b707e9734bdf3f96b7980d3595a9560bd912ebce/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts#L222)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Copy and paste gets me again :) Fixed.
</blockquote></details>

Haha, gotta beware the dreaded copy-paste :^D
___
*[src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs, line 784 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1189#-MojQuxk1LGMFmPUSvyB:-MpNeKpz0N2eqDhZ3nhO:b-8i5q53) ([raw file](https://github.com/sillsdev/web-xforge/blob/b707e9734bdf3f96b7980d3595a9560bd912ebce/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L784)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Done. What is the best practice for when there is an `if/else` and the `if` has multiple lines but the `else` doesn't - would we still add braces for the `else`?
</blockquote></details>

The approach I take is to match the style that is in the file (which is hopefully consistent). When I start a fresh file, I tend to only use braces where necessary, but others say to always use braces because it can be simpler to read. So it is hard to say which is better.


<!-- Sent from Reviewable.io -->

2021-11-25 20:42 UTC, nigel-wells reviewed
Thanks - I'll rebase it now so we can get it merged.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1189#-:-MpNpN90E6TA207IyvZy:b-fsi6q3)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts, line 23 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1189#-MojHNEc6eYqiStJsa39:-MpNp6390ZdDjVhtTpZe:bkfv0i) ([raw file](https://github.com/sillsdev/web-xforge/blob/b707e9734bdf3f96b7980d3595a9560bd912ebce/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts#L23)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Will this note ever appear in the text editor? I have seen it in Paratext just like you mentioned, but not in SF. It would be good to future-proof this though, so I'll be happy to make change.
</blockquote></details>

If the thread status is `resolved` then it won't appear. If the thread status is then reopened the status changes back to `todo` and it will appear in the text editor after the next sync.


<!-- Sent from Reviewable.io -->

2021-11-25 21:11 UTC, merged