SF-1428 Duplicate notes detected and cleaned up
sillsdev/web-xforge pull request #1198
Opened 2021-11-26 16:17 UTC by RaymondLuong3

When a note icon is deleted by the user in SF, the note icon's position will be recalculated and will reappear as it does in Paratext. When a user triggers an undo, the recreated note must be deleted so the previous note can be reinserted. The change performs two steps: (1) deleting the note that was recreated when the user first deleted a note. (2) reverts the position of the text anchor for the reinserted note and for all notes affected by the undo operation.

This change also refactors how we update a note's text anchor. The update method now accepts the update delta and uses it to calculate the note's updated position.

2021-12-03 07:29 UTC, irahopkinson requested changes
I'd prefer we didn't _reduce_ code coverage. What can you do to increase it?

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1198#-:-MpyyeLL-N1pijANbd2W:b-49lrrr)* status: all files reviewed, 4 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 939 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1198#-MpyzYSw-VYVpYNg_iKF:-MpyzYSw-VYVpYNg_iKG:b-85g9fr) ([raw file](https://github.com/sillsdev/web-xforge/blob/7cb53dbb9938edf20ac012fbe5f194a6fed7fb36/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L939)):*
> ```
> * Delete existing notes in the quill editor when the delta includes inserting a note.
> ```
How about adding 'so they won't end up being duplicated' to the end of this comment, otherwise the method name doesn't quite make sense. Perhaps there is a better method name since its not actually deleting duplicates but deletes in advance so that there doesn't end up being duplicates (unless I'm misunderstanding the order of things).
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 954 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1198#-Mpz-wps27hbuR-Tv9XB:-Mpz-wptCz8q9749IXaC:b-961vnw) ([raw file](https://github.com/sillsdev/web-xforge/blob/7cb53dbb9938edf20ac012fbe5f194a6fed7fb36/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L954)):*
> ```
> any
> ```
I would prefer you didn't use `any` here (and the next line) but if you have to, at least use `any[]` such that the `push` method is not excluded from type checking. 

Better yet, what about just creating the ops and then create the `Delta`, i.e.
```
          const noteDeleteOps: DeltaOperation[] = [];
          noteDeleteOps.push({ retain: deletePosition } as DeltaOperation);
          noteDeleteOps.push({ delete: 1 } as DeltaOperation);
          const noteDeleteOpDelta = new Delta(noteDeleteOps);
```
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 964 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1198#-Mpz2bQMDGN79IM_16bl:-Mpz2bQMDGN79IM_16bm:bs6f1bx) ([raw file](https://github.com/sillsdev/web-xforge/blob/7cb53dbb9938edf20ac012fbe5f194a6fed7fb36/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L964)):*
> ```
>       Promise.resolve(notesDeletionDelta).then(del => {
>         this.editor?.updateContents(del, 'api');
>       });
> ```
Is there some reason to return before fully dealing with this? Otherwise perhaps use async/await, i.e.:
```
      const updatedDelta = await Promise.resolve(notesDeletionDelta);
      this.editor?.updateContents(updatedDelta , 'api');
```
Also don't use `del` as shorthand for delta, `del` is short for delete usually. In general, don't use abbreviations unless they are well know.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1702 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1198#-Mpz8ZmmCwkfMFVkYyqa:-Mpz8ZmmCwkfMFVkYyqb:b-o1hbp0) ([raw file](https://github.com/sillsdev/web-xforge/blob/7cb53dbb9938edf20ac012fbe5f194a6fed7fb36/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1702)):*
> ```
> undo deleting a note icon removes the duplicate recreated icon
> ```
This is hard to understand outside the context of this PR. Can you clarify it? Perhaps adding dashes would be enough, i.e. 'undo deleting-a-note-icon removes the duplicate recreated icon' to clarify the thing being undone - if that is what is meant?


<!-- Sent from Reviewable.io -->

2021-12-06 21:03 UTC, RaymondLuong3 reviewed
Thanks for the review. I agree, I do not prefer when test coverage goes down. In this case, I observed that all of the uncovered lines were null checks and early return statements. Sometimes that is worth testing, but for these instances, the value would be minimal. With that said, it appears this revision no longer reduces the coverage.
I also found that the text doc was being updated with the note thread embeds. This should never happen. I had not been detecting inserting of note thread embeds in the text-view-model. So I have added that now.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1198#-:-MqGWLlV1OYF8a_rVn5A:bubz4z)* status: 5 of 9 files reviewed, 4 unresolved discussions (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 939 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1198#-MpyzYSw-VYVpYNg_iKF:-MqGXFQa4-XgS-arDcRg:bw9gw80) ([raw file](https://github.com/sillsdev/web-xforge/blob/7cb53dbb9938edf20ac012fbe5f194a6fed7fb36/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L939)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> * Delete existing notes in the quill editor when the delta includes inserting a note.
> ```
How about adding 'so they won't end up being duplicated' to the end of this comment, otherwise the method name doesn't quite make sense. Perhaps there is a better method name since its not actually deleting duplicates but deletes in advance so that there doesn't end up being duplicates (unless I'm misunderstanding the order of things).
</blockquote></details>

How does this sound?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 954 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1198#-Mpz-wps27hbuR-Tv9XB:-MqGXRdQDntpwB19lwVS:b-mm3fe7) ([raw file](https://github.com/sillsdev/web-xforge/blob/7cb53dbb9938edf20ac012fbe5f194a6fed7fb36/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L954)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> any
> ```
I would prefer you didn't use `any` here (and the next line) but if you have to, at least use `any[]` such that the `push` method is not excluded from type checking. 

Better yet, what about just creating the ops and then create the `Delta`, i.e.
```
          const noteDeleteOps: DeltaOperation[] = [];
          noteDeleteOps.push({ retain: deletePosition } as DeltaOperation);
          noteDeleteOps.push({ delete: 1 } as DeltaOperation);
          const noteDeleteOpDelta = new Delta(noteDeleteOps);
```
</blockquote></details>

I did one better. I can simply declare the noteDeleteOps with the array elements.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts, line 964 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1198#-Mpz2bQMDGN79IM_16bl:-MqGXack1igIvl-svcn7:b-6i4xvc) ([raw file](https://github.com/sillsdev/web-xforge/blob/7cb53dbb9938edf20ac012fbe5f194a6fed7fb36/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L964)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
>       Promise.resolve(notesDeletionDelta).then(del => {
>         this.editor?.updateContents(del, 'api');
>       });
> ```
Is there some reason to return before fully dealing with this? Otherwise perhaps use async/await, i.e.:
```
      const updatedDelta = await Promise.resolve(notesDeletionDelta);
      this.editor?.updateContents(updatedDelta , 'api');
```
Also don't use `del` as shorthand for delta, `del` is short for delete usually. In general, don't use abbreviations unless they are well know.
</blockquote></details>

Thanks for pointing this out. In principle, the delete delta must wait for the current delta to be applied. The current delta applies to the current state of the editor content. We cannot modify the editor content before we finish processing the current delta. Then the delete delta can be applied. I've updated the spec file so that we get a test failure if we do not defer this updateContents call.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1702 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1198#-Mpz8ZmmCwkfMFVkYyqa:-MqGYOun3-7t21nU-td5:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/7cb53dbb9938edf20ac012fbe5f194a6fed7fb36/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1702)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> undo deleting a note icon removes the duplicate recreated icon
> ```
This is hard to understand outside the context of this PR. Can you clarify it? Perhaps adding dashes would be enough, i.e. 'undo deleting-a-note-icon removes the duplicate recreated icon' to clarify the thing being undone - if that is what is meant?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-07 08:08 UTC, irahopkinson approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1198#-:-MqIvoyE2X0r8Md7TwJk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2021-12-07 10:08 UTC, irahopkinson approved these changes
@raymondluong3 I'll let you rebase this and merge since when I tried it had conflicts.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1198#-:-MqJML1yDFlEH3d-l7af:by50q1w)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2021-12-08 17:54 UTC, merged