SF-1424 Reattached notes in Paratext appear in the reattached location
sillsdev/web-xforge pull request #1204
Opened 2021-12-08 23:08 UTC by RaymondLuong3

When notes have been reattached in the chapter, notes in SF need to appear in the updated location. The backend had to be updated to add the Reattached property to Note.cs. Using the Reattached property, the backend can determine what is the new verse that the note is attached to, and update the Position property of the NoteThread.
On the frontend, the majority of the changes involve updating the note dialog to correctly display Notes in the NoteThread to reflect the reattachment of the note thread.

![Note reattached](https://user-images.githubusercontent.com/17931130/145305548-185c8a31-1fef-4698-b8e2-17c5b2ed7afc.png)

2021-12-13 22:48 UTC, marksvc commented
Examining.

2021-12-14 19:16 UTC, marksvc requested changes
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1204)* status: all files reviewed, 20 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts, line 38 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1204#-Mqtcs0J-N_p1LMGK7ND:-Mqtcs0M3gNNCcNEXxit:b-k3bx0t) ([raw file](https://github.com/sillsdev/web-xforge/blob/f7941886fbac112ea1cfa34380cadb90101a75b0/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts#L38)):*
> ```
>   currentVerseRef(noteThread: NoteThread):
> ```

Is there a special reason that this method takes a `NoteThread` rather than operate on `this.data`?
There are only a couple places this method is called, and in both we write something like `foo.currentVerseRef(foo.data)`, which seems odd. 
That's kind of more of a static usage. What do you think about re-writing the method signature and beginning as 
```ts
currentVerseRef(): VerseRef {
  if (this.data==null) {
    ?
  }
  noteThread: NoteThread == this.data
```
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts, line 41 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1204#-Mqpp_s-66l-TQSqani5:-Mqpp_s-66l-TQSqani6:b88duv4) ([raw file](https://github.com/sillsdev/web-xforge/blob/f7941886fbac112ea1cfa34380cadb90101a75b0/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts#L41)):*
> ```
> d!)
> ```


That's too bad for the compiler not to understand that reattached would always be not-null here. But I don't like the introduction of `!` :). 

I played with this a bit and came up with the following. What do you think about doing something like this so we don't introduce `!` into the production code? 

It didn't look like `.map()` had a way to _not_ return/set a value. I didn't try throwing from inside the map lambda, which may have been similar to the following code. 

And I noticed that we don't need `map` anyway and we can just query the `.reattached` property on the filtered array (or on the single resulting hit in the code below).

Maybe I should always just think of a `foo!` related crash as a "Programming error" and so short-hand for what I did in the following code. But I think I'm inclined to just not put `!` into the production code.


```ts
  currentVerseRef(noteThread: NoteThread): VerseRef {
    const lastReattach: Note | undefined = this.notesInOrderClone(noteThread.notes)
      .reverse()
      .find((n: Note) => n.reattached != null);
    if (lastReattach == null) {
      return toVerseRef(noteThread.verseRef);
    }
    if (lastReattach.reattached == null) {
      throw new Error('Programming error');
    }
    const verseStr: string = lastReattach.reattached.split(REATTACH_SEPARATOR)[0];
    return VerseRef.parse(verseStr);
  }

  /** Returns notes sorted by creation date from earlier to later. */
  notesInOrderClone(notes: Note[]): Note[] {
    ...
  }
```
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts, line 51 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1204#-MqtbYQk518hylGZFjCA:-MqtbYQo2IZY4gmbJ_v0:b3dhiyd) ([raw file](https://github.com/sillsdev/web-xforge/blob/f7941886fbac112ea1cfa34380cadb90101a75b0/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts#L51)):*
> ```
> this.data == null
> ```

Oops, I think here we want `notes == null`.

Actually. This method is acting like a static method as well, and every call to it looks something like `foo.notesInOrderClone(foo.data.notes)`. What do you think about re-writing it as
```ts
notesInOrderClone(): Note[] {
  if (this.data == null || this.data.notes == null) {
    return []
  }
  notes: Notes[] = this.data.notes
  ...
}
```
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.spec.ts, line 199 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1204#-MqtfrxfBXRjORl-HWEe:-Mqtfrxi5iTnX-2Nt-iu:b2s83zj) ([raw file](https://github.com/sillsdev/web-xforge/blob/f7941886fbac112ea1cfa34380cadb90101a75b0/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.spec.ts#L199)):*
> ```
> currentVerseRef
> ```

It looks like we don't test the other path of this method: When there is no re-attached note. Let's have a test specify what the output is when there are no re-attached notes, i.e. the noteThread.verseRef.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1243 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1204#-Mqu7MLc0aAYTuM_Chg-:-Mqu7MLh4mVZthvp5By3:b-1kuyk9) ([raw file](https://github.com/sillsdev/web-xforge/blob/f7941886fbac112ea1cfa34380cadb90101a75b0/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1243)):*
> ```XML
>       const note4Position: number = env.getNoteThreadEditorPosition('thread04');
>       const note4Anchor: TextAnchor = env.getNoteThreadDoc('project01', 'thread04')!.data!.position;
>       expect(note4Anchor).toEqual({ start: 19, length: 5 });
> ```

It's not clear from the test if 19,5 is new and different, or the same thing as before the note was re-attached. Maybe that could be made more clear somehow?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 2611 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1204#-Mqu1hG66u2gPeDi711F:-Mqu1hG66u2gPeDi711G:bbcnq2c) ([raw file](https://github.com/sillsdev/web-xforge/blob/f7941886fbac112ea1cfa34380cadb90101a75b0/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L2611)):*
> ```
> 19, length: 5 };
> ```

Can we replace this with explanatory constants or derived values?
I don't suppose it's arbitrary and just needs to match the numbers in the unit test ?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts, line 140 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1204#-MquKYx41y5zRFXjZIGb:-MquKYx54l5TbhogaBso:b-ro8mb8) ([raw file](https://github.com/sillsdev/web-xforge/blob/f7941886fbac112ea1cfa34380cadb90101a75b0/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L140)):*
> ```XML
>       return '';
>     }
>     if (note.reattached != null) {
> ```

Hmm. It seems that the fact that the note is re-attached would be less important than whether it's a "todo" or "done" or other meaningful icon. What's the thinking behind prioritizing the reattached icon? 
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts, line 155 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1204#-MquKw7K7QwCcHhKI0ZT:-MquKw7K7QwCcHhKI0ZU:bp8giun) ([raw file](https://github.com/sillsdev/web-xforge/blob/f7941886fbac112ea1cfa34380cadb90101a75b0/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L155)):*
> ```XML
>   noteTitle(note: Note) {
>     if (note.reattached != null) {
>       return translate('note_dialog.note_reattached');
> ```

Hmm, same thing here as with the icon. Isn't it more important if the note has status ToDo or Resolved, than whether it was moved to a different verse?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts, line 172 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1204#-MquEo6i3SSuqHJYnouV:-MquEo6kC2Enlky8OFA-:b-nchpe2) ([raw file](https://github.com/sillsdev/web-xforge/blob/f7941886fbac112ea1cfa34380cadb90101a75b0/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L172)):*
> ```
> reattachedParts[3]
> ```

It's hard to know if [3] here and [1] there etc makes any sense :)
Can we assign these to meaningfully named variables first, like
```ts
const contextBefore = reattachedParts[n]
const something = reattachedParts[m]
```
before usin [...]

2021-12-15 21:38 UTC, RaymondLuong3 reviewed
I've made some changes, but there are a few more I need to make before this is ready for re-review

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1204#-:-MqztE9C208xBoWZdGr_:brvg850)* status: all files reviewed, 20 unresolved discussions (waiting on @marksvc and @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts, line 38 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1204#-Mqtcs0J-N_p1LMGK7ND:-MqzDSTK9XKDHDo2NJLf:bl5ccbp) ([raw file](https://github.com/sillsdev/web-xforge/blob/f7941886fbac112ea1cfa34380cadb90101a75b0/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts#L38)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
>   currentVerseRef(noteThread: NoteThread):
> ```

Is there a special reason that this method takes a `NoteThread` rather than operate on `this.data`?
There are only a couple places this method is called, and in both we write something like `foo.currentVerseRef(foo.data)`, which seems odd. 
That's kind of more of a static usage. What do you think about re-writing the method signature and beginning as 
```ts
currentVerseRef(): VerseRef {
  if (this.data==null) {
    ?
  }
  noteThread: NoteThread == this.data
```
</blockquote></details>

Ok, I've changed a few things around to make this work. currentVerseRef now returns VerseRef | undefined.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts, line 41 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1204#-Mqpp_s-66l-TQSqani5:-MqzFS2q10Kn3zzSl5Eo:bi4lwu8) ([raw file](https://github.com/sillsdev/web-xforge/blob/f7941886fbac112ea1cfa34380cadb90101a75b0/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts#L41)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
> d!)
> ```


That's too bad for the compiler not to understand that reattached would always be not-null here. But I don't like the introduction of `!` :). 

I played with this a bit and came up with the following. What do you think about doing something like this so we don't introduce `!` into the production code? 

It didn't look like `.map()` had a way to _not_ return/set a value. I didn't try throwing from inside the map lambda, which may have been similar to the following code. 

And I noticed that we don't need `map` anyway and we can just query the `.reattached` property on the filtered array (or on the single resulting hit in the code below).

Maybe I should always just think of a `foo!` related crash as a "Programming error" and so short-hand for what I did in the following code. But I think I'm inclined to just not put `!` into the production code.


```ts
  currentVerseRef(noteThread: NoteThread): VerseRef {
    const lastReattach: Note | undefined = this.notesInOrderClone(noteThread.notes)
      .reverse()
      .find((n: Note) => n.reattached != null);
    if (lastReattach == null) {
      return toVerseRef(noteThread.verseRef);
    }
    if (lastReattach.reattached == null) {
      throw new Error('Programming error');
    }
    const verseStr: string = lastReattach.reattached.split(REATTACH_SEPARATOR)[0];
    return VerseRef.parse(verseStr);
  }

  /** Returns notes sorted by creation date from earlier to later. */
  notesInOrderClone(notes: Note[]): Note[] {
    ...
  }
```
</blockquote></details>

I've updated the code to follow your suggestion. It is certainly nice when we can avoid `!` assertions in our production code. I did not include the programming error line, I think we can keep going if the lastReattach.reattached is null.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts, line 51 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1204#-MqtbYQk518hylGZFjCA:-MqzGI_y2BRvJ42J649j:bu02aup) ([raw file](https://github.com/sillsdev/web-xforge/blob/f7941886fbac112ea1cfa34380cadb90101a75b0/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts#L51)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
> this.data == null
> ```

Oops, I think here we want `notes == null`.

Actually. This method is acting like a static method as well, and every call to it looks something like `foo.notesInOrderClone(foo.data.notes)`. What do you think about re-writing it as
```ts
notesInOrderClone(): Note[] {
  if (this.data == null || this.data.notes == null) {
    return []
  }
  notes: Notes[] = this.data.notes
  ...
}
```

</blockquote></details>

Turns out we do not need the null check at all.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.spec.ts, line 199 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1204#-MqtfrxfBXRjORl-HWEe:-MqzQe0A90RdySv6Olin:brrvei6) ([raw file](https://github.com/sillsdev/web-xforge/blob/f7941886fbac112ea1cfa34380cadb90101a75b0/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.spec.ts#L199)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
> currentVerseRef
> ```

It looks like we don't test the other path of this method: When there is no re-attached note. Let's have a test specify what the output is when there are no re-attached notes, i.e. the noteThread.verseRef.
</blockquote></details>

Good thinking. I added two checks on previous tests. One for a thread with existing notes, one with no existing notes.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1243 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1204#-Mqu7MLc0aAYTuM_Chg-:-MqzTCKDALsKhNbRuII5:b-ddr6nz) ([raw file](https://github.com/sillsdev/web-xforge/blob/f7941886fbac112ea1cfa34380cadb90101a75b0/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1243)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

It's not clear from the test if 19,5 is new and different, or the same thing as before the note was re-attached. Maybe that could be made more clear somehow?
</blockquote></details>

The position of a note thread will always be the up-to-date value. I've adjust the test a little, so we use the expected position value to detect if the position in-editor is correct.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 2611 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1204#-Mqu1hG66u2gPeDi711F:-MqzUYPj046qUATx18H-:b-xms6cj) ([raw file](https://github.com/sillsdev/web-xforge/blob/f7941886fbac112ea1cfa34380cadb90101a75b0/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L2611)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
> 19, length: 5 };
> ```

Can we replace this with explanatory constants or derived values?
I don't suppose it's arbitrary and just needs to match the numbers in the unit test ?
</blockquote></details>

Good thinking. The reattachNote method now accepts the position as a param.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts, line 140 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1204#-MquKYx41y5zRFXjZIGb:-MqzWXif29wl8Trgr162:b-v2hjnf) ([raw file](https://github.com/sillsdev/web-xforge/blob/f7941886fbac112ea1cfa34380cadb90101a75b0/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L140)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Hmm. It seems that the fact that the note is re-attached would be less important than whether it's a "todo" or "done" or other meaningful icon. What's the thinking behind prioritizing the reattached icon? 
</blockquote></details>

It seems kind of overloaded for a comment to both have content, and represent a reattachment. But this seems to be the case. So I have had to rethink how we handle reattached notes. In this case, [...]

2021-12-16 18:32 UTC, RaymondLuong3 reviewed
Ok, the comments have been addressed and is now ready for re-review.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1204#-:-Mr3W1Bl5rifG1jSAuXS:b-byshey)* status: all files reviewed, 20 unresolved discussions (waiting on @marksvc)

___
*[test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs, line 848 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1204#-MqpeAXV0sYz7j2UQfmt:-Mr3Ggg4DSDW5-qpafW3:b-8f42pb) ([raw file](https://github.com/sillsdev/web-xforge/blob/f7941886fbac112ea1cfa34380cadb90101a75b0/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L848)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I am able to make a thread with a comment, then add a reattach with comment, then remove the reattach+comment comment. And so then the thread goes  back to its original position. Can we add to our tests this situation?
- SF knows about a thread that has a reference, but is re-attached to a different reference. 
- SF receives a change from PT where the Comment with Reattached is no longer present.
- SF now places the thread at its original reference.


</blockquote></details>

How does this sound. The SF NoteThreadDocs start with a thread5 with the second note being a reattached note. The Paratext commentThread for thread5 contains just one comment (the second comment is assumed to be deleted). Then after the operation, test that thread5's second second noteThread in SF is marked for removal.
___
*[test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs, line 2041 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1204#-Mqphp6o4PKOUQmVdlNR:-Mr3HE0FDYF8VygwFEEt:bjho6q) ([raw file](https://github.com/sillsdev/web-xforge/blob/f7941886fbac112ea1cfa34380cadb90101a75b0/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L2041)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

And shouldn't this instead be rnt.selectedText ? I guess the test should be checking that the reattached comment item has rnt.SelectedText, rnt.before, and rnt.after.
</blockquote></details>

No, these properties never change on the Comment thread. The only thing that changes is the content and the reattached string.
___
*[test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs, line 2044 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1204#-MqpgxWX6NYjR0cZS8jd:-Mr3HT8J9ac21XqhI7Nk:b2nreh6) ([raw file](https://github.com/sillsdev/web-xforge/blob/f7941886fbac112ea1cfa34380cadb90101a75b0/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L2044)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
>                             ContextBefore = comp.appliesToVerse ? "" : before,
>                             ContextAfter = comp.appliesToVerse ? "" : after,
>                             StartPosition = comp.appliesToVerse ? 0 : before.Length,
> ```

Shouldn't this instead be using rnt.before, rnt.after, rnt.before.Length ?
</blockquote></details>

Same as above.
___
*[test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs, line 2104 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1204#-Mqpi-B36xItv-wJ_W6x:-Mr3UHSFD7-tGpc1DGxw:b-nh1smh) ([raw file](https://github.com/sillsdev/web-xforge/blob/f7941886fbac112ea1cfa34380cadb90101a75b0/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L2104)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
>                 string before = "Context before ";
>                 string after = " context after.";
> ```

How about changing these so they are different for the re-attached verse than for the original verse, so we can check that we used the new values? eg 
```
string before = "Reattached context before "
string after = " reattached context after."
```
</blockquote></details>

I've created three new constants for reattached selected text, an alternate context before and after. This allows us to confirm that the changed position matches what we expect.
___
*[test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs, line 2131 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1204#-MqpiwEE9uAD9t_JV5nj:-Mr3VzS8BnBKDFL1EDZg:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/f7941886fbac112ea1cfa34380cadb90101a75b0/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L2131)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
>                     if (i == 7)
>                         noteSelectedText = "reattached text";
> ```

Hmm, okay. What do you think about adding a comment before this like
// Make one of the verses have different text to optionally use to re-attach to. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-17 18:01 UTC, marksvc requested changes
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1204)* status: all files reviewed, 4 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1243 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1204#-Mqu7MLc0aAYTuM_Chg-:-Mr4HL0u7vt-mpWgNCBG:b-qggjd4) ([raw file](https://github.com/sillsdev/web-xforge/blob/f7941886fbac112ea1cfa34380cadb90101a75b0/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1243)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

The position of a note thread will always be the up-to-date value. I've adjust the test a little, so we use the expected position value to detect if the position in-editor is correct.
</blockquote></details>

Hmm, okay. I have been puzzled by this test today and think it could use some clarity. Could we assert earlier in the test that the note text position is not equal to {start:19,length:5}, and that thread4 is in verse 3? For example:

```
expect(initial thread 4 text anchoring != `position`) (and I guess quite significantly that .start is different between them)
expect(thread 4 editor position === (getSegmentRange('verse_1_3')).index + (initial thread 4 text anchoring).start)
reattachNote(thread04 to 'MAT 1:4', newTextPosition)
expect(new thread 4 text anchoring === `position`)
expect(thread 4 editor position === (getSegmentRange('verse_1_4')).index + (new thread 4 text anchoring).start)
```

As the test is written now, the significance of {start:19,length:5} is not obvious. Was it {start:19,length:5} before and it is still {start:19,length:5} now? Was it some other value and we changed it to {start:19,length:5}? Is it significant that it be 19,5 or if we wrote 100,200, would that still make the test pass? Presumably 19,5 relates to text of MAT 1:4, but does it relate the same way to the text of MAT 1:3?

I can see that we assert that thread04 is in verse_1_4, but the test doesn't show that it wasn't there before. 

I'm also a bit confused about where the action happens. Is there a line that would be a good place to label as SUT?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts, line 172 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1204#-MquEo6i3SSuqHJYnouV:-Mr4NpKl1PAonrDr3RuR:b5ugbmh) ([raw file](https://github.com/sillsdev/web-xforge/blob/f7941886fbac112ea1cfa34380cadb90101a75b0/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L172)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Much easier to read!
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts, line 175 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1204#-Mr4MiI-AioOR1-xywZQ:-Mr4MiI1-2N20zK_l_So:b-lz7mfg) ([raw file](https://github.com/sillsdev/web-xforge/blob/aa831ebb90f6dae82e539a9867da8141fdec3d11/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L175)):*
> ```XML
>     const reattached: string = translate('note_dialog.reattached');
>     let noteContent: string = this.parseNote(note.content);
>     noteContent = noteContent === '' ? '' : `<br>${noteContent}`;
> ```

I find this kind of awkward. What do you think about something like this instead? 
```ts
if (noteContent !== '') {
  noteContent = `<br>${noteContent}`
}
```

Also, I'm guessing it might benefit from `<p>` rather than `<br>`, but haven't seen at how it looks yet.



_Code quote:_
```XML
  noteContent = noteContent === '' ? '' : `<br>${noteContent}`;
```
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts, line 177 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1204#-Mr4OD-0-mLIduOFAbMK:-Mr4OD-0-mLIduOFAbML:b-tqer1e) ([raw file](https://github.com/sillsdev/web-xforge/blob/aa831ebb90f6dae82e539a9867da8141fdec3d11/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L177)):*
> ```XML
>     noteContent = noteContent === '' ? '' : `<br>${noteContent}`;
> 
>     return `${verseRef} ${reattached}<br>${reattachedText}${noteContent}`;
> ```

```diff
-</br>
+<br>
```

Oops, good catch.
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 1528 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1204#-MqpL2so1w7C9XNGPboQ:-Mr4S0vI-a0EDbY995SV:bo9cv1s) ([raw file](https://github.com/sillsdev/web-xforge/blob/f7941886fbac112ea1cfa34380cadb90101a75b0/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1528)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Good thinking. I don't know enough about comment status, but to be safe, I've updated this as per your suggestion.
</blockquote></details>

Ha, ya know, as I look at this more I am wondering if we can simplify it a lot. What do you think about changing it to this? (I'm not as familiar with these values, so it may not make sense to do it this way tho.)

```diff
             // Check if fields have been updated in Paratext
-            bool statusExists = !string.IsNullOrEmpty(comment.Status.InternalValue) ||
-                !string.IsNullOrEmpty(note.Status);
-            bool statusChanged = statusExists && comment.Status.InternalValue != note.Status;
-            bool contentExists = !string.IsNullOrEmpty(note.Content) ||
-                !string.IsNullOrEmpty(comment.Contents?.InnerXml);
-            bool contentChanged = contentExists && comment.Contents.InnerXml != note.Content;
+            bool statusChanged = comment.Status.InternalValue != note.Status;
+            bool contentChanged = comment.Contents?.InnerXml != note.Content;
             if (contentChanged || statusChanged)
                 return ChangeType.Updated;
             return ChangeType.None;
```

When I did this, I noticed that the test setup code wasn't setting Status for a Note or a Comment when Reattached is set. But it didn't look like that would be so in production. So I modified the ParatextServiceTests.cs with

```diff
+++ b/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
@@ -1929,6 +1929,7 @@ namespace SIL.XForge.Scripture.Services
                             ExtUserId = "user02",
                             SyncUserRef = "syncuser01",
                             DateCreated = new DateTime(2019, 1, 20, 8, 0, 0, DateTimeKind.Utc),
+                            Status = NoteStatus.Unspecified.InternalValue,
                             Reattached = ReattachedThreadInfoStr(rti)
                         });
                         noteThread.Position = new TextAnchor
@@ -2069,6 +2070,7 @@ namespace SIL.XForge.Scripture.Services
                             ContextAfter = comp.appliesToVerse ? "" : after,
                             StartPosition = comp.appliesToVerse ? 0 : before.Length,
                             Date = "2019-01-20T08:00:00.0000000+00:00",
+                            Status = NoteStatus.Unspecified,
                             Reattached = ReattachedThreadInfoStr(rti)
                         });
                     }
```

and the tests are passing.
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 1547 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1204#-MqpXBqnAlo-nzhHvqGq:-Mr8M6Zi3JdQkEMbyG0M:b-k77929) ([raw file](https://github.com/sillsdev/web-xforge/blob/f7941886fbac112ea1cfa34380cadb90101a75b0/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1547)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Initially I used comment.AddTextToContent() to guarantee that comment.Contents is not null because AddTextToCont [...]

2021-12-17 23:14 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1204)* status: 6 of 14 files reviewed, 4 unresolved discussions (waiting on @marksvc)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1243 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1204#-Mqu7MLc0aAYTuM_Chg-:-Mr9FFkb3OILv0qwI2Ju:bltt5v5) ([raw file](https://github.com/sillsdev/web-xforge/blob/f7941886fbac112ea1cfa34380cadb90101a75b0/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1243)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Hmm, okay. I have been puzzled by this test today and think it could use some clarity. Could we assert earlier in the test that the note text position is not equal to {start:19,length:5}, and that thread4 is in verse 3? For example:

```
expect(initial thread 4 text anchoring != `position`) (and I guess quite significantly that .start is different between them)
expect(thread 4 editor position === (getSegmentRange('verse_1_3')).index + (initial thread 4 text anchoring).start)
reattachNote(thread04 to 'MAT 1:4', newTextPosition)
expect(new thread 4 text anchoring === `position`)
expect(thread 4 editor position === (getSegmentRange('verse_1_4')).index + (new thread 4 text anchoring).start)
```

As the test is written now, the significance of {start:19,length:5} is not obvious. Was it {start:19,length:5} before and it is still {start:19,length:5} now? Was it some other value and we changed it to {start:19,length:5}? Is it significant that it be 19,5 or if we wrote 100,200, would that still make the test pass? Presumably 19,5 relates to text of MAT 1:4, but does it relate the same way to the text of MAT 1:3?

I can see that we assert that thread04 is in verse_1_4, but the test doesn't show that it wasn't there before. 

I'm also a bit confused about where the action happens. Is there a line that would be a good place to label as SUT?


</blockquote></details>

I think the biggest part of the confusion is that reattachNote sounds like it is in realtime. And it is, but this test is not concerned about the realtime behaviour of notes (since editing notes is note yet a SF feature).
So read this as note loading behaviour. The editor is loaded after the wait() is called, and everything before that is setup.
If you read it that way, they you will see that we are testing that a note is loaded at the correct position, and `position` is the up-to-date position in the verse to load the note. So there is no "before" and "after" sense to this test. Only the "on load" sense.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts, line 175 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1204#-Mr4MiI-AioOR1-xywZQ:-Mr9f4yP8SrY8GS0rjxq:b-uff1ei) ([raw file](https://github.com/sillsdev/web-xforge/blob/aa831ebb90f6dae82e539a9867da8141fdec3d11/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L175)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I find this kind of awkward. What do you think about something like this instead? 
```ts
if (noteContent !== '') {
  noteContent = `<br>${noteContent}`
}
```

Also, I'm guessing it might benefit from `<p>` rather than `<br>`, but haven't seen at how it looks yet.


</blockquote></details>

Even better. I've updated the note dialog so that the content will show up like such.
![image.png](https://files.reviewableusercontent.io/images/reviewable/17931130/vuJVdRpbQLPX-taav0eukYtx/image.png)
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 1528 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1204#-MqpL2so1w7C9XNGPboQ:-Mr9LYT_EK1WzqXr8gCc:b-wanonu) ([raw file](https://github.com/sillsdev/web-xforge/blob/f7941886fbac112ea1cfa34380cadb90101a75b0/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1528)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Ha, ya know, as I look at this more I am wondering if we can simplify it a lot. What do you think about changing it to this? (I'm not as familiar with these values, so it may not make sense to do it this way tho.)

```diff
             // Check if fields have been updated in Paratext
-            bool statusExists = !string.IsNullOrEmpty(comment.Status.InternalValue) ||
-                !string.IsNullOrEmpty(note.Status);
-            bool statusChanged = statusExists && comment.Status.InternalValue != note.Status;
-            bool contentExists = !string.IsNullOrEmpty(note.Content) ||
-                !string.IsNullOrEmpty(comment.Contents?.InnerXml);
-            bool contentChanged = contentExists && comment.Contents.InnerXml != note.Content;
+            bool statusChanged = comment.Status.InternalValue != note.Status;
+            bool contentChanged = comment.Contents?.InnerXml != note.Content;
             if (contentChanged || statusChanged)
                 return ChangeType.Updated;
             return ChangeType.None;
```

When I did this, I noticed that the test setup code wasn't setting Status for a Note or a Comment when Reattached is set. But it didn't look like that would be so in production. So I modified the ParatextServiceTests.cs with

```diff
+++ b/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
@@ -1929,6 +1929,7 @@ namespace SIL.XForge.Scripture.Services
                             ExtUserId = "user02",
                             SyncUserRef = "syncuser01",
                             DateCreated = new DateTime(2019, 1, 20, 8, 0, 0, DateTimeKind.Utc),
+                            Status = NoteStatus.Unspecified.InternalValue,
                             Reattached = ReattachedThreadInfoStr(rti)
                         });
                         noteThread.Position = new TextAnchor
@@ -2069,6 +2070,7 @@ namespace SIL.XForge.Scripture.Services
                             ContextAfter = comp.appliesToVerse ? "" : after,
                             StartPosition = comp.appliesToVerse ? 0 : before.Length,
                             Date = "2019-01-20T08:00:00.0000000+00:00",
+                            Status = NoteStatus.Unspecified,
                             Reattached = ReattachedThreadInfoStr(rti)
                         });
                     }
```

and the tests are passing.
</blockquote></details>

Yes, that looks like an improvement. Note that it is no longer expected that comments with null content will map to the empty string in SF data.
___
*[test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs, line 901 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1204#-Mr8VxMx63knFNE7d6aT:-Mr9NmmK8BQXsvSfKWus:b2jof0n) ([raw file](https://github.com/sillsdev/web-xforge/blob/aa831ebb90f6dae82e539a9867da8141fdec3d11/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L901)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Right. That's good. I think it would be good to tack in the following change as well. The usefulness of the `Assert.That(change5.Position, Is.EqualTo(originalAnchor));` partly relies on our test setup having helpful values for some of these items (like you have done by introducing TestEnvironment.AlternateBefore/After). 


```diff
+++ b/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs
@@ -898,6 +898,9 @@ namespace SIL.XForge.Scripture.Services
                 NoteThreadChange change5 = changes.Single(c => c.ThreadId == "thread5");
                 Assert.That(change5.NoteIdsRemoved.Count, Is.EqualTo(1));
                 Assert.That(change5.NoteIdsRemoved[0], Is.EqualTo("reattachedthread5"));
+                // The thread is un-reattached back to its original position.
+                Assert.That(change5.ContextBefore, Is.Not.EqualTo(rnt.contextBefore), "test framework");
+                Assert.That(change5.SelectedText, Is.Not.EqualTo(r [...]

2021-12-20 18:05 UTC, marksvc requested changes
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1204)* status: all files reviewed, 3 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1243 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1204#-Mqu7MLc0aAYTuM_Chg-:-MrNzTKE1anPADeHRTVj:b-b1c5c1) ([raw file](https://github.com/sillsdev/web-xforge/blob/f7941886fbac112ea1cfa34380cadb90101a75b0/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1243)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I think the biggest part of the confusion is that reattachNote sounds like it is in realtime. And it is, but this test is not concerned about the realtime behaviour of notes (since editing notes is note yet a SF feature).
So read this as note loading behaviour. The editor is loaded after the wait() is called, and everything before that is setup.
If you read it that way, they you will see that we are testing that a note is loaded at the correct position, and `position` is the up-to-date position in the verse to load the note. So there is no "before" and "after" sense to this test. Only the "on load" sense.
</blockquote></details>

That's helpful, thank you.
What is the meaning of {start: 19, length:5}? Is it the anchoring that was determined when the thread was first created, which would be used to anchor the thread to a particular part of the verse 3 text? Are they values that somehow relate to verse 4? 
Would it be accurate to give `position` a comment above it saying something like: // Original anchoring of thread 4 in verse 3
or something like // Anchoring of tread 4 in verse 4
?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts, line 175 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1204#-Mr4MiI-AioOR1-xywZQ:-MrNlmem-4kdw1uPsmzE:bb6wk0y) ([raw file](https://github.com/sillsdev/web-xforge/blob/aa831ebb90f6dae82e539a9867da8141fdec3d11/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L175)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Even better. I've updated the note dialog so that the content will show up like such.
![image.png](https://files.reviewableusercontent.io/images/reviewable/17931130/vuJVdRpbQLPX-taav0eukYtx/image.png)

</blockquote></details>

Good
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts, line 122 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1204#-MrNmaBE9T-cQAbR9SCx:-MrNmaBE9T-cQAbR9SCy:bpeijz9) ([raw file](https://github.com/sillsdev/web-xforge/blob/9814097969bd73d8d7dee7c411ad3dfa1cc87525/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts#L122)):*
> ```XML
>   }));
> 
>   it('should show notes for reattachment', fakeAsync(() => {
> ```

How about also here (or in the below test) asserting that the re-attached location verse reference appears where it should?
___
*[test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs, line 901 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1204#-Mr8VxMx63knFNE7d6aT:-MrNnjvDEvZZU3xHHPy4:b5otyvi) ([raw file](https://github.com/sillsdev/web-xforge/blob/aa831ebb90f6dae82e539a9867da8141fdec3d11/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L901)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Actually, the NoteThreadChange.ContextBefore will never be different regardless of whether the note is attached or not. Those properties are needed to create a note thread, but they are meaningless when the note thread doc already exists. Same with ContextBefore.
</blockquote></details>

Hmm. But why then do we earlier do

```cs
                TextAnchor expectedAnchor = new TextAnchor
                {
                    Start = rnt.contextBefore.Length,
                    Length = rnt.selectedText.Length
                };
                Assert.That(change1.Position, Is.EqualTo(expectedAnchor));
```
is this the same as asserting that change1.Position is equal to originalAnchor?


<!-- Sent from Reviewable.io -->

2021-12-20 23:09 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1204)* status: all files reviewed, 3 unresolved discussions (waiting on @marksvc)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1243 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1204#-Mqu7MLc0aAYTuM_Chg-:-MrP0aA2DKBlqFKWs84H:b-55y2mk) ([raw file](https://github.com/sillsdev/web-xforge/blob/f7941886fbac112ea1cfa34380cadb90101a75b0/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1243)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

That's helpful, thank you.
What is the meaning of {start: 19, length:5}? Is it the anchoring that was determined when the thread was first created, which would be used to anchor the thread to a particular part of the verse 3 text? Are they values that somehow relate to verse 4? 
Would it be accurate to give `position` a comment above it saying something like: // Original anchoring of thread 4 in verse 3
or something like // Anchoring of tread 4 in verse 4
?
</blockquote></details>

The position could have been any position, we just need to give our test a place to anchor the note thread after it is reattached to verse 4. I left a comment saying "active position of thread04 when reattached to verse 4.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts, line 122 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1204#-MrNmaBE9T-cQAbR9SCx:-MrP2mta0S8LCXQ2EyI_:bjjp38z) ([raw file](https://github.com/sillsdev/web-xforge/blob/9814097969bd73d8d7dee7c411ad3dfa1cc87525/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts#L122)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

How about also here (or in the below test) asserting that the re-attached location verse reference appears where it should?
</blockquote></details>

I've added that to both.
___
*[test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs, line 901 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1204#-Mr8VxMx63knFNE7d6aT:-MrP3RTQAZmVMUKOQ6m0:b-lwj00j) ([raw file](https://github.com/sillsdev/web-xforge/blob/aa831ebb90f6dae82e539a9867da8141fdec3d11/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L901)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Hmm. But why then do we earlier do

```cs
                TextAnchor expectedAnchor = new TextAnchor
                {
                    Start = rnt.contextBefore.Length,
                    Length = rnt.selectedText.Length
                };
                Assert.That(change1.Position, Is.EqualTo(expectedAnchor));
```
is this the same as asserting that change1.Position is equal to originalAnchor?
</blockquote></details>

I think you are asking why it appears that the note thread anchor looks important and relates the reattached note thread position, but the ContextBefore and SelectedText appear to be meaningless.
In the NoteThreadChange class, the ContextBefore and SelectedText are only necessary if the note thread doc does not yet exist, it needs to be created with these values. These properties do not change on comments in a thread for any reason, so we never have to check what values they hold apart from creation time. However, other properties like Position do have meaning. If they exist, it means that these values are new and need to be stored. 


<!-- Sent from Reviewable.io -->

2021-12-21 17:48 UTC, marksvc approved these changes
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1204)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts, line 141 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1204#-MrT269P1Segxyjb2KJJ:-MrT269P1Segxyjb2KJK:b2brqnz) ([raw file](https://github.com/sillsdev/web-xforge/blob/b7d0128149215b74d5634253f6d33e9a00edb717/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L141)):*
> ```XML
>     }
>     return note.reattached != null ? this.threadDoc.iconReattached.url : this.threadDoc.getNoteIcon(note).url;
>   }
> ```

This seems like a strange fall thru. We do
```py
if note status is Todo
  return whatever the note icon is supposed to be
if note status is Done or Resolved,
  return the resolved icon
if the note is reattached,
  return the reattached url
In any other case not already handled above,
  return whatever the note icon is supposed to be
```
Hmm. Okay :)



_Code quote:_
```XML
    switch (note.status) {
      case NoteStatus.Todo:
        return this.threadDoc.getNoteIcon(note).url;
      case NoteStatus.Done:
      case NoteStatus.Resolved:
        return this.threadDoc.getNoteResolvedIcon(note).url;
    }
    return note.reattached != null ? this.threadDoc.iconReattached.url : this.threadDoc.getNoteIcon(note).url;
  }
```


<!-- Sent from Reviewable.io -->

2021-12-21 18:22 UTC, merged