Update note icon click subscriptions for all icons in the verse
sillsdev/web-xforge pull request #1217
Opened 2021-12-22 23:42 UTC by RaymondLuong3

The click subscriptions were not being updated correctly when a user deletes a note, and then they undo the deletion. This change records the note icon click subscription and refreshes all of the subscriptions when a note is deleted, and then the user undoes the deletion. In order to get it to work, it was also necessary to strip away the formatting on the note thread embed that gets re-embedded so that it wouldn't cause our formatting in quill to be in a bad state.
There was another bug where undo deleting-a-note would revert the position to a previous position even when it should not. So now it checks that there was a measurable text edit in addition to the note deletion before performing the undo and reverting the note thread position.

2022-01-06 20:13 UTC, Nateowami requested changes
Raymond and I looked at this together and it needs some changes. I'm putting this here so no one starts code review not knowing that this is actually being reworked.

> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1217#-:-Msl-ryD0wP24QGbeM5f:bnszjbp)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @Nateowami)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts, line 678 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1217#-Msl02RCD8QNVMdcp4LA:-Msl02RCD8QNVMdcp4LB:bdwwmor) ([raw file](https://github.com/sillsdev/web-xforge/blob/d56dd91f7065b9c97b28f989492864261d97345a/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts#L678)):*
> ```XML
>           modelOp.insert['note-thread-embed'] != null
>         ) {
>           attrs = undefined;
> ```

This is a no-op, and changing it to `modelOp.attributes = undefined` (which is what it should be) causes some formatting issues.


<!-- Sent from Reviewable.io -->

2022-01-07 21:24 UTC, RaymondLuong3 reviewed
Ok, it turns out that the formatting issue we saw was a new problem. But I've added the work to re-apply the text-anchor class to the notes that get inserted when a user undoes deleting-a-note.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1217#-:-MsqPw0GAQh6u0yUSGVN:bip9n5a)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @Nateowami)



<!-- Sent from Reviewable.io -->

2022-01-08 01:07 UTC, Nateowami requested changes
> Reviewed 1 of 4 files at r2, 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1217)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @Nateowami and @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts, line 669 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1217#-Msr7e_29SuWT8glNzBk:-Msr7e_29SuWT8glNzBl:b-7s0bm8) ([raw file](https://github.com/sillsdev/web-xforge/blob/d37dd0a15c35df62d6f80a26946190048c76be65/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts#L669)):*
> ```XML
>       for (const op of delta.ops) {
>         const modelOp: DeltaOperation = cloneDeep(op);
>         let attrs = modelOp.attributes;
> ```

I think this should be back to const?


<!-- Sent from Reviewable.io -->

2022-01-11 16:52 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1217)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts, line 678 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1217#-Msl02RCD8QNVMdcp4LA:-Mt92YgnCEHGIP6-BtH7:b-n12gm0) ([raw file](https://github.com/sillsdev/web-xforge/blob/d56dd91f7065b9c97b28f989492864261d97345a/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts#L678)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This is a no-op, and changing it to `modelOp.attributes = undefined` (which is what it should be) causes some formatting issues.
</blockquote></details>

I have now addressed this. Thanks for catching it!
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts, line 669 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1217#-Msr7e_29SuWT8glNzBk:-Mt92WyP4muvxqCgb-ia:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/d37dd0a15c35df62d6f80a26946190048c76be65/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts#L669)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I think this should be back to const?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-11 21:25 UTC, Nateowami approved these changes
Looks good. Just two minor suggestions.

> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1217#-:-MtA0qv-8w4pGi0gg6xu:b-fezh2m)* status: all files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 1056 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1217#-Mt96Bmo-IztKpAVDgio:-Mt96Bmo-IztKpAVDgip:bdnw5gu) ([raw file](https://github.com/sillsdev/web-xforge/blob/ba0ba6559c0848c72b459d572103faf1ad0ab749/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1056)):*
> ```XML
>     const reinsertedNoteIds: string[] = [];
>     reinsertedNoteEmbeds.forEach(n => {
>       if (n.attributes != null && n.attributes['threadid'] != null) {
> ```

I think this could be `n.attributes?.['threadid'] != null`
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 1061 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1217#-Mt9NscxBiqVP4mp72B0:-Mt9Nscy9WiGFlzID9KS:bvzdtcd) ([raw file](https://github.com/sillsdev/web-xforge/blob/ba0ba6559c0848c72b459d572103faf1ad0ab749/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1061)):*
> ```XML
>     });
>     const textInsertOps: DeltaOperation[] = delta.filter(
>       ops => ops.insert != null && ops.insert['note-thread-embed'] == null
> ```

Perhaps `ops.insert?.['note-thread-embed'] != null`?


<!-- Sent from Reviewable.io -->

2022-01-12 16:54 UTC, merged