SF-1454 Handle dropping in more nodes
sillsdev/web-xforge pull request #1223
Opened 2022-01-11 17:51 UTC by marksvc

- discernTarget() still returns the <usx-segment> that is dropped
into, but also the specific element inside the usx-segment that was
dropped into, such as a <display-text-anchor>. This allows text to be
dropped into a thread anchoring area.
- determineInsertionPosition() processes a tree of nodes to determine
the length from the beginning of a <usx-segment> thru to the position
of the drop as reported by the browser.
- New tests specify behaviour for dropping into a note thread
anchoring area as well as a location that is in the anchoring area of
two note threads.

===

Handling of `<usx-blank>` elements can be somewhat rolled into this, but I want to do that in followup after this initial change is reviewed.

2022-01-11 22:50 UTC, RaymondLuong3 requested changes
Just beginning to review now. I'll add comments as they arise.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1223#-:-MtAKS9g2k7EyF_bn-nX:b-jeocj8)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @marksvc and @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts, line 983 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1223#-MtAJ0gq-cyyoS8wQaWV:-MtAJ0gq-cyyoS8wQaWW:bo6k187) ([raw file](https://github.com/sillsdev/web-xforge/blob/7a19e071f7384ff935485683505195ae5bc02172/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L983)):*
> ```XML
> 
>     it('can drag-and-drop into note thread anchoring area', fakeAsync(() => {
>       // The user drags into the region of the editor that is anchored to by a thread's text anchor. The dragged text
> ```

Doesn't the user drag into 



_Code quote:_
```XML
      // The user drags into the region of the editor that is anchored to by a thread's text anchor. The dragged text
      // should appear where it's dropped.
```
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts, line 994 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1223#-MtAJqqm3W3pP_5-auZ5:-MtAJqqm3W3pP_5-auZ6:b-xjcbb4) ([raw file](https://github.com/sillsdev/web-xforge/blob/7a19e071f7384ff935485683505195ae5bc02172/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L994)):*
> ```XML
>       const textLeadingUpToSelection_1_1 = 'target: ';
>       const initialTextInDoc_1_1 = 'target: chapter 1, verse 1.';
>       //                          move this ---------   ^^^^ thread anchoring
> ```

This isn't correct. The underlined text should just be on 'chapter'. What do the ^^^^ mean? 



_Code quote:_
```XML
      //                          move this ---------   ^^^^ thread anchoring
```
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts, line 999 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1223#-MtAI35-5nyMY9KraBMR:-MtAI35-5nyMY9KraBMS:blu5il5) ([raw file](https://github.com/sillsdev/web-xforge/blob/7a19e071f7384ff935485683505195ae5bc02172/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L999)):*
> ```XML
>       const expectedTextInDoc_1_1 = 'target: , verchapter 1se 1.';
>       const textLeadingUpToTargetLocationAfterEvent_1_1 = 'target: , ver';
>       const textNodeTextBeforeEvent_1_1 = 'erse';
> ```

From the name of the variable, I would have expected this to be ', verse 1.'



_Code quote:_
```XML
const textNodeTextBeforeEvent_1_1 = 'erse';
```
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts, line 1003 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1223#-MtAILF171rVmS2K3eMb:-MtAILF171rVmS2K3eMc:bgg6rtx) ([raw file](https://github.com/sillsdev/web-xforge/blob/7a19e071f7384ff935485683505195ae5bc02172/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L1003)):*
> ```XML
>       // The drop location is in a text node in a display-text-anchor element. These are the characters in the text
>       // node that lead up to the drop location.
>       const textNodeTextLeadingUpToTargetLocationAfterEvent_1_1 = 'er';
> ```

Same with this, isn't the 'chapter 1' text moved to be between ', ver' and 'se 1.' So I would have expected this to be ', ver'.



_Code quote:_
```XML
      const textNodeTextLeadingUpToTargetLocationAfterEvent_1_1 = 'er';
```


<!-- Sent from Reviewable.io -->

2022-01-12 03:16 UTC, RaymondLuong3 requested changes
Good work figuring out how to do this. What about testing whether dragging text from within a note anchor? Are note threads correctly updated? I assume this already has tests in editor.component but just wanted to be sure you had thought of that.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1223#-:-MtBCNCV32vbq3z87hxb:b-d51tql)* status: all files reviewed, 6 unresolved discussions (waiting on @marksvc)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/drag-and-drop.ts, line 171 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1223#-MtBE3nQEKbWYAVs2Wxs:-MtBE3nQEKbWYAVs2Wxt:b-9obsib) ([raw file](https://github.com/sillsdev/web-xforge/blob/7a19e071f7384ff935485683505195ae5bc02172/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/drag-and-drop.ts#L171)):*
> ```XML
>     }
>     if (element == null || element.localName != 'usx-segment') {
>       console.warn('Warning: DragEvent never found a needed usx-segment ancestor for drop target:', targetElement);
> ```

I wonder if it would be worth using a loop to discover if any parent is a usx-segment. It could be useful if we ever add more elements within a usx-segment.



_Code quote:_
```XML
      console.warn('Warning: DragEvent never found a needed usx-segment ancestor for drop target:', targetElement);
```
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/drag-and-drop.ts, line 249 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1223#-MtBFMxg6c_4xiPDbZNb:-MtBFMxg6c_4xiPDbZNc:bftjqje) ([raw file](https://github.com/sillsdev/web-xforge/blob/7a19e071f7384ff935485683505195ae5bc02172/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/drag-and-drop.ts#L249)):*
> ```XML
>       return 0;
>     }
>     if (node.nodeName.toLowerCase() === 'display-note') {
> ```

There can also be nodes such as usx-note or usx-figure that are embed just like the display-note. I believe those should be addressed here.



_Code quote:_
```XML
    if (node.nodeName.toLowerCase() === 'display-note') {
```
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/drag-and-drop.ts, line 255 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1223#-MtBFruoBiQ5lO22yKdV:-MtBFruoBiQ5lO22yKdW:b-b461de) ([raw file](https://github.com/sillsdev/web-xforge/blob/7a19e071f7384ff935485683505195ae5bc02172/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/drag-and-drop.ts#L255)):*
> ```XML
>     if (node.nodeType === Node.TEXT_NODE) {
>       if (node.nodeValue == null) {
>         throw new Error('Did not expect a text node to have a null value.');
> ```

Does this need to be an error? I guess it would prevent the user from possibly doing something that results in corrupted data.



_Code quote:_
```XML
        throw new Error('Did not expect a text node to have a null value.');
```
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts, line 983 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1223#-MtAJ0gq-cyyoS8wQaWV:-MtB2XK748QUNwZI_UE4:btslkkp) ([raw file](https://github.com/sillsdev/web-xforge/blob/7a19e071f7384ff935485683505195ae5bc02172/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L983)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Doesn't the user drag into 
</blockquote></details>

Nvm, it doesn't look like it is relevant.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts, line 994 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1223#-MtAJqqm3W3pP_5-auZ5:-MtB2pGx41jyYsMYcGE_:b-7m1p2s) ([raw file](https://github.com/sillsdev/web-xforge/blob/7a19e071f7384ff935485683505195ae5bc02172/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L994)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This isn't correct. The underlined text should just be on 'chapter'. What do the ^^^^ mean? 
</blockquote></details>

I see now that ------- denotes the text selection and the ^^^^ denotes the text anchor. I would have swapped those since a note anchor is represented by dashed lines. Ok good I'm starting to understand this.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts, line 999 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1223#-MtAI35-5nyMY9KraBMR:-MtBBemyB_zjUNSt_lik:bn7de1y) ([raw file](https://github.com/sillsdev/web-xforge/blob/7a19e071f7384ff935485683505195ae5bc02172/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L999)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

From the name of the variable, I would have expected this to be ', verse 1.'
</blockquote></details>

Nvm, I see I had it swapped in my head what --- and ^^^ means
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts, line 1003 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1223#-MtAILF171rVmS2K3eMb:-MtBBrQi7mzwTMkCAepe:b-uo3i1k) ([raw file](https://github.com/sillsdev/web-xforge/blob/7a19e071f7384ff935485683505195ae5bc02172/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L1003)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Same with this, isn't the 'chapter 1' text moved to be between ', ver' and 'se 1.' So I would have expected this to be ', ver'.
</blockquote></details>

Nvm, I had it swapped around --- vs ^^^
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts, line 1146 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1223#-MtB6b3E9LGkqOf255Ug:-MtB6b3F7ZahmKg67rAk:bi7seps) ([raw file](https://github.com/sillsdev/web-xforge/blob/7a19e071f7384ff935485683505195ae5bc02172/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L1146)):*
> ```XML
>       // <display-text-anchor> elements for the area of overlapping anchoring. The text node that the drop happens in
>       // will be the thread2 text node.
>       const textNodeTextLeadingUpToTargetLocationAfterEvent_1_1 = 'r';
> ```

In this case, since the text anchor overlaps beginning at this character, it is a distinct text node from the letter 'e' that comes right before. Ok.



_Code quote:_
```XML
      const textNodeTextLeadingUpToTargetLocationAfterEvent_1_1 = 'r';
```
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts, line 1528 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1223#-MtBC4cA8PmiHCrXIC5G:-MtBC4cA8PmiHCrXIC5H:bb5fmhu) ([raw file](https://github.com/sillsdev/web-xforge/blob/7a19e071f7384ff935485683505195ae5bc02172/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L1528)):*
> ```XML
> 
>   /** Where reference is like 'MAT 1:2'. */
>   embedThreadAt(reference: string, textAnchor: TextAnchor): void {
> ```

This could be private



_Code quote:_
```XML
  embedThreadAt(reference: string, textAnchor: TextAnchor): void {
```


<!-- Sent from Reviewable.io -->

2022-01-21 18:15 UTC, marksvc reviewed
Thank you. I wrote to you in chat about what to do regarding dragging from a note thread anchoring area, and the existing tests for thread anchoring.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1223#-:-MtdoTl_1XkO4gTKF9Dx:b6b7d0v)* status: all files reviewed, 4 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/drag-and-drop.ts, line 171 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1223#-MtBE3nQEKbWYAVs2Wxs:-MtEcibk-ibtVXtpeytW:bjypqnt) ([raw file](https://github.com/sillsdev/web-xforge/blob/7a19e071f7384ff935485683505195ae5bc02172/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/drag-and-drop.ts#L171)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I wonder if it would be worth using a loop to discover if any parent is a usx-segment. It could be useful if we ever add more elements within a usx-segment.
</blockquote></details>

Yes! So we do this a few lines above when we do 
```ts
    while (element.localName != 'usx-segment' && element.parentElement != null) {
      element = element.parentElement;
    }
```
which will walk up the tree until we find the containing usx-segment element, or until we get to the root and never found a usx-segment. 
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/drag-and-drop.ts, line 249 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1223#-MtBFMxg6c_4xiPDbZNb:-MtdnkUB5KdfR98UWKvO:bnr310d) ([raw file](https://github.com/sillsdev/web-xforge/blob/7a19e071f7384ff935485683505195ae5bc02172/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/drag-and-drop.ts#L249)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

There can also be nodes such as usx-note or usx-figure that are embed just like the display-note. I believe those should be addressed here.
</blockquote></details>

I'll mention that a couple ways to approach this would be:

- if we recognize an element of fixed length, return its known length and don't descend into its children. 
- otherwise, descend into any other element, looking for children elements and text nodes.

or

- If we recognize an element as having children we want to measure, descend into the element and examine its children.
- otherwise, assume the element is length 1 and don't process it further.

I suspect that in our case, the second one is more likely to do the right thing when we encounter an element we didn't plan for. I am posting a revision of the code which does this.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/drag-and-drop.ts, line 255 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1223#-MtBFruoBiQ5lO22yKdV:-MtEdl7y5NvbtCg_-5YE:b7qe5wz) ([raw file](https://github.com/sillsdev/web-xforge/blob/7a19e071f7384ff935485683505195ae5bc02172/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/drag-and-drop.ts#L255)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Does this need to be an error? I guess it would prevent the user from possibly doing something that results in corrupted data.
</blockquote></details>

This situation should never happen. Well, based on looking at https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeValue
As an alternative, we could detect and return: `if nodeValue is null then return 0`. But it shouldn't happen.
We could write a new class to represent a text node that that specifies that its nodeValue is always a non-null string.

The error message is perhaps not worded well since it's not clear if it means "It is possible that the text node could have a null value, but we didn't expect that it was going to happen in this situation" or "The programmer thought this situation was impossible and did not expect it to happen!". 

Good point tho that it doesn't need to be an error. I ended up changing to return 0 if nodeValue is null here, with a comment about the situation.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts, line 994 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1223#-MtAJqqm3W3pP_5-auZ5:-MtEigqA539PyV6ywAdq:bmdmld5) ([raw file](https://github.com/sillsdev/web-xforge/blob/7a19e071f7384ff935485683505195ae5bc02172/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L994)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I see now that ------- denotes the text selection and the ^^^^ denotes the text anchor. I would have swapped those since a note anchor is represented by dashed lines. Ok good I'm starting to understand this.
</blockquote></details>

Sorry about the misunderstandings! I don't mean for the characters here to be mimicking our UI, but just pointing to things to show what's happening where, and where some boundaries and pieces are. I changed some dashes to the caret so it's all just pointing rather than underlying. I see why that was confusing. 

I meant for the text next to the carets (or dashes) to describe what was being marked. For example, the 'chapter 1' section of text that is marked has a label "move this", and the 'erse' section of text that is marked has a label "thread anchoring". But I guess it wasn't without some getting used to. 

Ok I also put in horizontal lines from the labels, to the arrows they relate to. 
Well, and in some further work I ended up removing the labels since it was getting too complex.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts, line 1146 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1223#-MtB6b3E9LGkqOf255Ug:-MtEl8ox5NtqtUu1Y7hP:b-4ws3g8) ([raw file](https://github.com/sillsdev/web-xforge/blob/7a19e071f7384ff935485683505195ae5bc02172/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L1146)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

In this case, since the text anchor overlaps beginning at this character, it is a distinct text node from the letter 'e' that comes right before. Ok.
</blockquote></details>

Yes. There is a text node for `e` and another text node for `rse 1`. Between the text nodes is a `display-note` element showing the flag icon. The drop occurs just after the `r` in the `rse 1` text node. And so after the drag-and-drop event(s), the text in the text node where the drop occurred, has text of `r` leading up to the location of the drop.
This variable is later on used to specify what the web browser will return for the position on the text node at which the drop occurred. Hm I guess it should be "BeforeEvent" not "AfterEvent". I'll change that. 
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts, line 1528 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1223#-MtBC4cA8PmiHCrXIC5G:-MtEpg7B-k1KsAk90Nv2:bfhaoox) ([raw file](https://github.com/sillsdev/web-xforge/blob/7a19e071f7384ff935485683505195ae5bc02172/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L1528)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This could be private
</blockquote></details>

Thanks. I just gave that a try but it looks like a few places call `env.embedThreadAt()` from outside the class.


<!-- Sent from Reviewable.io -->

2022-01-22 00:46 UTC, RaymondLuong3 approved these changes
Looks like it needs a rebase, then it looks good to me.

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1223#-:-MtzEo6A-RDfrJ660gof:b-hk79oh)* status: all files reviewed, 2 unresolved discussions (waiting on @marksvc)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/drag-and-drop.ts, line 171 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1223#-MtBE3nQEKbWYAVs2Wxs:-MtzCVJfEQYH9VLz7Vq4:byzvq5z) ([raw file](https://github.com/sillsdev/web-xforge/blob/7a19e071f7384ff935485683505195ae5bc02172/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/drag-and-drop.ts#L171)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Yes! So we do this a few lines above when we do 
```ts
    while (element.localName != 'usx-segment' && element.parentElement != null) {
      element = element.parentElement;
    }
```
which will walk up the tree until we find the containing usx-segment element, or until we get to the root and never found a usx-segment. 
</blockquote></details>

Good, glad this is here for future-proofing.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/drag-and-drop.ts, line 249 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1223#-MtBFMxg6c_4xiPDbZNb:-MtzCiBP4hMdShv-qY9m:b-6xawy6) ([raw file](https://github.com/sillsdev/web-xforge/blob/7a19e071f7384ff935485683505195ae5bc02172/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/drag-and-drop.ts#L249)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I'll mention that a couple ways to approach this would be:

- if we recognize an element of fixed length, return its known length and don't descend into its children. 
- otherwise, descend into any other element, looking for children elements and text nodes.

or

- If we recognize an element as having children we want to measure, descend into the element and examine its children.
- otherwise, assume the element is length 1 and don't process it further.

I suspect that in our case, the second one is more likely to do the right thing when we encounter an element we didn't plan for. I am posting a revision of the code which does this.



</blockquote></details>

Yes, I believe the second is the case we should be prepared for. I haven't looked too closely at this, but from looking at these changes I get the understanding that most non-text elements have a length of 1, except for `usx-char` elements which have a length based on the enclosed text.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/drag-and-drop.ts, line 255 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1223#-MtBFruoBiQ5lO22yKdV:-MtzD9bT-e_zN7gfy_BE:bl34lks) ([raw file](https://github.com/sillsdev/web-xforge/blob/7a19e071f7384ff935485683505195ae5bc02172/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/drag-and-drop.ts#L255)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

This situation should never happen. Well, based on looking at https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeValue
As an alternative, we could detect and return: `if nodeValue is null then return 0`. But it shouldn't happen.
We could write a new class to represent a text node that that specifies that its nodeValue is always a non-null string.

The error message is perhaps not worded well since it's not clear if it means "It is possible that the text node could have a null value, but we didn't expect that it was going to happen in this situation" or "The programmer thought this situation was impossible and did not expect it to happen!". 

Good point tho that it doesn't need to be an error. I ended up changing to return 0 if nodeValue is null here, with a comment about the situation.


</blockquote></details>

Ok, good.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts, line 994 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1223#-MtAJqqm3W3pP_5-auZ5:-MtzDBp_4dx24AY0YxSR:b-96514h) ([raw file](https://github.com/sillsdev/web-xforge/blob/7a19e071f7384ff935485683505195ae5bc02172/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L994)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Sorry about the misunderstandings! I don't mean for the characters here to be mimicking our UI, but just pointing to things to show what's happening where, and where some boundaries and pieces are. I changed some dashes to the caret so it's all just pointing rather than underlying. I see why that was confusing. 

I meant for the text next to the carets (or dashes) to describe what was being marked. For example, the 'chapter 1' section of text that is marked has a label "move this", and the 'erse' section of text that is marked has a label "thread anchoring". But I guess it wasn't without some getting used to. 

Ok I also put in horizontal lines from the labels, to the arrows they relate to. 
Well, and in some further work I ended up removing the labels since it was getting too complex.
</blockquote></details>

Thanks, I think this helps to clarify things.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts, line 1528 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1223#-MtBC4cA8PmiHCrXIC5G:-MtzCI6bBk-tL3MD7JeM:b-o4tfnc) ([raw file](https://github.com/sillsdev/web-xforge/blob/7a19e071f7384ff935485683505195ae5bc02172/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L1528)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Thanks. I just gave that a try but it looks like a few places call `env.embedThreadAt()` from outside the class.
</blockquote></details>

Good job testing that. Ok.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts, line 1597 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1223#-Mtz9ibU1cVkweTFTjpU:-Mtz9ibU1cVkweTFTjpV:b-qqrpun) ([raw file](https://github.com/sillsdev/web-xforge/blob/95fb5fc96fe6cc45bedde4256758f32c5c51a141/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L1597)):*
> ```XML
>       const expectedElementCountNugget = initialNuggetElementCount;
> 
>       const sourceSegmentRange: RangeStatic | undefined = env.component.getSegmentRange(sourceSegmentRef);
> ```

Consider renaming this so that someone else won't mistake this to be the source text, as in the mother translation segment range. Maybe dragStartSegmentRange.



_Code quote:_
```XML
 const sourceSegmentRange
```
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts, line 1662 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1223#-MtzB50q8oa6VWsY0YdL:-MtzB50q8oa6VWsY0YdM:b2f38r8) ([raw file](https://github.com/sillsdev/web-xforge/blob/95fb5fc96fe6cc45bedde4256758f32c5c51a141/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L1662)):*
> ```XML
>         textLeadingUpToTargetLocationAfterEvent.length +
>         args.nuggetEditorLength -
>         args.nuggetTextDocText!.length;
> ```

Why is this subtracted from the desiredSelectionStart? I see that when we assign textLeadingUpToTargetLocationAfterEvent, we use the length of thenuggetTextDocText. Is this trying to say that the nuggetTextDocText length is somehow excluded when we call getSelection()?



_Code quote:_
```XML
       args.nuggetTextDocText!.length;
```


<!-- Sent from Reviewable.io -->

2022-01-24 21:06 UTC, marksvc reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1223)* status: all files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts, line 1597 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1223#-Mtz9ibU1cVkweTFTjpU:-MuCrPBz8BW3scSpDWyd:b20g0fx) ([raw file](https://github.com/sillsdev/web-xforge/blob/95fb5fc96fe6cc45bedde4256758f32c5c51a141/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L1597)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Consider renaming this so that someone else won't mistake this to be the source text, as in the mother translation segment range. Maybe dragStartSegmentRange.
</blockquote></details>

How about "origin"?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts, line 1662 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1223#-MtzB50q8oa6VWsY0YdL:-MuCnyQB-8_mt4WdR56r:b-aub6w8) ([raw file](https://github.com/sillsdev/web-xforge/blob/95fb5fc96fe6cc45bedde4256758f32c5c51a141/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L1662)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Why is this subtracted from the desiredSelectionStart? I see that when we assign textLeadingUpToTargetLocationAfterEvent, we use the length of thenuggetTextDocText. Is this trying to say that the nuggetTextDocText length is somehow excluded when we call getSelection()?
</blockquote></details>

No,
The selection start needs to be in terms of editor position. And so it needs to include editor-only items that may be present in `args.nuggetEditorLength` but not in `args.nuggetTextDocText!.length`, like a footnote marker. 

I am revising it to try to clarify what is happening, by introducing variable `editorLengthToTargetLocationAfterEvent`.

Another way to clarify may have been to write:
```ts
const lengthOnlyInEditor: number = args.nuggetEditorLength - args.nuggettextDocText.length
const desiredSelectionstart = targetSegmentRange.index + textLeadingUpToTargetLocationAfterEvent.length + lengthOnlyInEditor
```


<!-- Sent from Reviewable.io -->

2022-01-24 22:33 UTC, RaymondLuong3 approved these changes
> Reviewed 1 of 3 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1223)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts, line 1597 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1223#-Mtz9ibU1cVkweTFTjpU:-MuCyq2u5Wf8kyeZQfMP:b-speyhe) ([raw file](https://github.com/sillsdev/web-xforge/blob/95fb5fc96fe6cc45bedde4256758f32c5c51a141/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L1597)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

How about "origin"?
</blockquote></details>

I like origin!
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts, line 1662 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1223#-MtzB50q8oa6VWsY0YdL:-MuCzBZoEj_w-VJAyVNH:b-nbajas) ([raw file](https://github.com/sillsdev/web-xforge/blob/95fb5fc96fe6cc45bedde4256758f32c5c51a141/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L1662)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

No,
The selection start needs to be in terms of editor position. And so it needs to include editor-only items that may be present in `args.nuggetEditorLength` but not in `args.nuggetTextDocText!.length`, like a footnote marker. 

I am revising it to try to clarify what is happening, by introducing variable `editorLengthToTargetLocationAfterEvent`.

Another way to clarify may have been to write:
```ts
const lengthOnlyInEditor: number = args.nuggetEditorLength - args.nuggettextDocText.length
const desiredSelectionstart = targetSegmentRange.index + textLeadingUpToTargetLocationAfterEvent.length + lengthOnlyInEditor
```

</blockquote></details>

Hmm, I think I understand. The textLeadingUpToTargetLocationAfterEvent including text in the nugget, but not non-text length that the nugget includes. I like they updated name much better, because it represents all the length of the text and non-text objects that come before the selection.


<!-- Sent from Reviewable.io -->

2022-01-24 22:36 UTC, merged