SF-1442 Show assigned users for note threads
sillsdev/web-xforge pull request #1227
Opened 2022-01-21 23:56 UTC by RaymondLuong3

* add assigned usernames and refs to note thread model
* record assigned usernames and user refs during synchronize
* determine a paratext user's userId if it exists
* display the assigned user for notes that are assigned
* gray out note icons when a thread is assigned to a different user

<img width="302" alt="Notes_Grayout" src="https://user-images.githubusercontent.com/17931130/150614712-82d70983-3bf7-4ade-a659-a2c13977f69d.png">
<img width="425" alt="Notes_Dialog_Assigned" src="https://user-images.githubusercontent.com/17931130/150614717-5f1af6b3-9de4-40e9-8715-e81bbc9457ab.png">

2022-01-24 22:16 UTC, marksvc commented
:eyes:

2022-01-25 23:24 UTC, marksvc requested changes
Thanks for your work on this. It seems like adding the SF user Id of the assigned user is an unfortunate little piece to need to add. 

An alternative would be to add a `ptUsername?` field to the user model. (Then to determine if a thread or note is assigned to the current user, we check if the thread.assignedPTUsername === me.ptUsername.) I wonder if that information would be useful in other places, too, like we could tell the user what Paratext account their SF account is connected to, on some appropriate page. 

Hmm.

We can talk more about it. It may be something good to throw out on chat.

Some of my comments below will become irrelevant if we do away with writing the assigned SF user Id on the threads and notes :)

> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-:-MuIWXZe6pepWSCcSbW9:b-836o59)* status: all files reviewed, 17 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts, line 39 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MuIOebI4P6tlARwbB1h:-MuIOebI4P6tlARwbB1i:bmpk176) ([raw file](https://github.com/sillsdev/web-xforge/blob/828acb160a60b65014e5ae39ad0ce3c4a5d6567d/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts#L39)):*
> ```XML
>   }
> 
>   getIcon(grayOut?: boolean): NoteThreadIcon {
> ```

BTW I think it would have been okay to leave `get icon()`, and add in another getter like `get iconGrayed()`or `get iconDimmed()`. 
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts, line 41 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MuIPwfG2Ay9rsWy9VOV:-MuIPwfG2Ay9rsWy9VOW:b-yf5ey0) ([raw file](https://github.com/sillsdev/web-xforge/blob/828acb160a60b65014e5ae39ad0ce3c4a5d6567d/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts#L41)):*
> ```XML
>   getIcon(grayOut?: boolean): NoteThreadIcon {
>     let tag: string = this.getTag();
>     if (grayOut) {
> ```

Hey, none of the tests actually try setting greyOut=true tho :)
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts, line 90 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MuINQX363KMgtLpmWcW:-MuINQX363KMgtLpmWcX:b-g8aw5k) ([raw file](https://github.com/sillsdev/web-xforge/blob/828acb160a60b65014e5ae39ad0ce3c4a5d6567d/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts#L90)):*
> ```XML
>   private grayOutTag(iconTag: string): string {
>     if (iconTag !== '') {
>       iconTag = iconTag.slice(0, iconTag.length - 1) + '4';
> ```

Let's see. So if '4' is a standard suffix for greyed-out icons, then maybe
```ts
const grayedOutSuffix: string = '4';
```

Oh, or it could use a comment like in the method above.



_Code quote:_
```XML
 '4';
```
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 1025 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MuIS-WM8x8wx2VitxrV:-MuIS-WM8x8wx2VitxrW:bbq51lv) ([raw file](https://github.com/sillsdev/web-xforge/blob/828acb160a60b65014e5ae39ad0ce3c4a5d6567d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1025)):*
> ```XML
>       id: threadDoc.data.dataId,
>       preview,
>       icon: threadDoc.getIcon(this.isAssignedToOtherUser(threadDoc)),
> ```

In the spec can we run into this with there being an assignment to another user, and specify the outcome of having a dimmed icon?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 1324 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MuITGGwEAHCoR6nWlyM:-MuIQS8H3yGrwQOKsE58:b-na5ybv) ([raw file](https://github.com/sillsdev/web-xforge/blob/828acb160a60b65014e5ae39ad0ce3c4a5d6567d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1324)):*
> ```XML
>   private isAssignedToOtherUser(thread: NoteThreadDoc): boolean {
>     if (thread.data?.assignedUserRef != null && thread.data.assignedUserRef.length > 0) {
>       return thread.data.assignedUserRef !== this.userService.currentUserId;
> ```

I'm glad that checking for a dimmed icon is in the spec. And I see that the current user's SF user Id must not equal the PT username "user02", which is a convenient way to make this return true. But can we test a situation where the PT usernames and SF user Ids are not in the same pool and matching each other (eg where the SF user Id for User 01 (eg "user01") does not equal the PT username for User 01 (eg "user01")), and specify the resulting icon being dimmed or not from the following situations:
- Thread has PT username for the current user, and SF user Id for the current user.
- Thread has PT username for another user, and SF user Id for another user.
- Thread has PT username that doesn't match the current user, and SF user Id is null.
- Thread has PT username of team or unspecified, and SF user Id is null.

Also, it wasn't clear in the editor.component.spec.ts test who the current user was (to know if it made sense that "user02" wasn't the current user). I assume it's user01. Maybe that can be stated?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html, line 4 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MuIHM872WkzY_uqhfAm:-MuIHM872WkzY_uqhfAn:b-pwlulm) ([raw file](https://github.com/sillsdev/web-xforge/blob/828acb160a60b65014e5ae39ad0ce3c4a5d6567d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.html#L4)):*
> ```HTML
>   <h1 mat-dialog-title>
>     <img [src]="flagIcon" alt="" /> <span>{{ verseRef }}</span>
>     <div *ngIf="threadAssignedUser != null" id="assignedUser" class="assigned-user">
> ```

This means a _Paratext_ username, right? What do you think about sticking  `PT` in there? I was a bit confused at first when I later saw `note.AssignedPTUsername`, and came back up here and was wondering if it is a SF user...name/id.  

Actually, with respect to user name/id, it would benefit from having `Username` in the variable, I think. Maybe `threadAssignedPTUsername`.



_Code quote:_
```HTML
"threadAssignedUser 
```
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.scss, line 54 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MuILldx9_88y2PV2X3N:-MuILldx9_88y2PV2X3O:b-eci6fq) ([raw file](https://github.com/sillsdev/web-xforge/blob/828acb160a60b65014e5ae39ad0ce3c4a5d6567d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.scss#L54)):*
> ```SCSS
>   }
> }
> .assigned-user {
> ```

If the note or thread is assigned to the user who is viewing it, it might be nice for for the assigned-user display to be bolded or in red or something. 
___
*[src/SIL.XForge.Scripture/Services/IParatextService.cs, line 42 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MuHVhCB32HKlJ7jXKeS:-MuHVhCB32HKlJ7jXKeT:b-x557h1) ([raw file](https://github.com/sillsdev/web-xforge/blob/828acb160a60b65014e5ae39ad0ce3c4a5d6567d/src/SIL.XForge.Scripture/Services/IParatextService.cs#L42)):*
> ```Smalltalk
>         IEnumerable<NoteThreadChange> GetNoteThreadChanges(UserSecret userSecret, string projectId, int bookNum,
>             IEnumerable<IDocument<NoteThread>> noteThreadDocs, Dictionary<int, ChapterDelta> chapterDeltas,
>             Dictionary<string, SyncUser> syncUsers, IReadOnlyDictionary<string, string> userIdsToUsername);
> ```

Isn't this variable the wrong way around? (should be something like `ptUsernameToSFUserIdMapping`)



_Code quote:_
```Smalltalk
 userIdsToUsername)
```
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 367 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MuDHKMh-0VIljlGH8GM:-MuDHKMh-0VIljlGH8GN:b-8zbo8f) ([raw file](https://github.com/sillsdev/web-xforge/blob/8 [...]

2022-02-22 21:36 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1227)* status: 1 of 69 files reviewed, 16 unresolved discussions (waiting on @marksvc)

___
*[test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs, line 885 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MuI04pNEqu9Im4at3Hj:-MwYLsZ85LHh4M8ralD3:bvq5cnt) ([raw file](https://github.com/sillsdev/web-xforge/blob/828acb160a60b65014e5ae39ad0ce3c4a5d6567d/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L885)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

This means something, right? (it's not just text to appear in the note?) Can we use an enum or something, like 
```
enum Tags {
  Important = "1",
  Research = "2",
  Something = "3"
}
```

Or at least a meaningfully named variable, like
```cs
const string noteTypeResearch = "2"
```
</blockquote></details>

Actually, the tests were set up so that the thread num was also the default notes added. This really wasn't helpful anymore, so I've removed it.


<!-- Sent from Reviewable.io -->

2022-02-25 11:09 UTC, ddaspit approved these changes
I did a quick review of the `sf-projects-profile` projection changes. The changes look really clean. Good job.

> Reviewed 37 of 65 files at r2, 2 of 2 files at r3, 7 of 7 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-:-MwkYhDH4z9L4tsXVAVZ:b-cmh7xw)* status: 50 of 69 files reviewed, 16 unresolved discussions (waiting on @ddaspit and @marksvc)



<!-- Sent from Reviewable.io -->

2022-02-28 16:55 UTC, RaymondLuong3 reviewed
Thanks! I'll let @marksvc do a final review of these changes.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-:-Mx0FRE5B28-LXSeF42r:b-q6d0x8)* status: 50 of 69 files reviewed, 16 unresolved discussions (waiting on @ddaspit and @marksvc)



<!-- Sent from Reviewable.io -->

2022-03-02 16:29 UTC, marksvc commented
:eyes:

2022-03-02 16:43 UTC, marksvc commented
___
*[src/SIL.XForge.Scripture/Models/Note.cs, line 12 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxAVfni9qsljjBk63sa:-MxAVfni9qsljjBk63sb:b-4czdsd) ([raw file](https://github.com/sillsdev/web-xforge/blob/2f3b18b6ee568cfddb1431baa77f6dd30348f184/src/SIL.XForge.Scripture/Models/Note.cs#L12)):*
> ```Smalltalk
>         public string TagIcon { get; set; }
>         public string Reattached { get; set; }
>         public string AssignedNoteUserRef { get; set; }
> ```

I haven't read the rest of the patches yet, and this will probably make sense at that time. But what does this mean? Does it mean the same thing as `AssignedUserRef` did? There is a "project-user"; I don't suppose there is a note-user now. 



_Code quote:_
```Smalltalk
AssignedNoteUserRef 
```


<!-- Sent from Reviewable.io -->

2022-03-02 17:18 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1227)* status: 50 of 69 files reviewed, 17 unresolved discussions (waiting on @ddaspit and @marksvc)

___
*[src/SIL.XForge.Scripture/Models/Note.cs, line 12 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxAVfni9qsljjBk63sa:-MxAcf4N-29p3b4R3hHM:bluzkun) ([raw file](https://github.com/sillsdev/web-xforge/blob/2f3b18b6ee568cfddb1431baa77f6dd30348f184/src/SIL.XForge.Scripture/Models/Note.cs#L12)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I haven't read the rest of the patches yet, and this will probably make sense at that time. But what does this mean? Does it mean the same thing as `AssignedUserRef` did? There is a "project-user"; I don't suppose there is a note-user now. 
</blockquote></details>

That's right. It is the same as `AssignedUserRef`. This could be `team` and `unassigned`too.


<!-- Sent from Reviewable.io -->

2022-03-02 21:13 UTC, marksvc requested changes
> Reviewed 8 of 65 files at r2, 2 of 7 files at r4, 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1227)* status: 56 of 69 files reviewed, 29 unresolved discussions (waiting on @ddaspit, @marksvc, and @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/Models/Note.cs, line 12 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxAVfni9qsljjBk63sa:-MxAfSVS8WDVYuUNPYDz:b-havqvm) ([raw file](https://github.com/sillsdev/web-xforge/blob/2f3b18b6ee568cfddb1431baa77f6dd30348f184/src/SIL.XForge.Scripture/Models/Note.cs#L12)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

That's right. It is the same as `AssignedUserRef`. This could be `team` and `unassigned`too.
</blockquote></details>

Hmm, okay. And is this going to be the string of the ParatextUserProfile.OpaqueUserId ?
I think "AssignedNoteUserRef" is confusing about what is being meant.
I think "AssignedUserRef" seems like it might be the SF user id. 
I'm tying to think what we could call it that makes it clear what it is, and that it's not an SF user id :). 
I think `AssignedOpaquePTUserId` might be quite descriptive, but unpleasant. Hey, since this can be other descriptions, like "team" and "unassigned", I suggest that this property be called `Assignment`, and have a comment saying 'Who this note is assigned to. This may be a ParatextUserProfile OpaqueUserId, or a category such as "team" or "unassigned".'
___
*[src/SIL.XForge.Scripture/Models/ParatextUserProfile.cs, line 4 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxAdN1fBuMIA0NvFoY0:-MxAdN1fBuMIA0NvFoY1:b2j9the) ([raw file](https://github.com/sillsdev/web-xforge/blob/2f3b18b6ee568cfddb1431baa77f6dd30348f184/src/SIL.XForge.Scripture/Models/ParatextUserProfile.cs#L4)):*
> ```Smalltalk
> {
>     /// <summary>
>     /// The paratext users on a project including users that do not have an sf account.
> ```

If this model is for a single user, let's adjust the comment to not describe it as a plural set. For example, "One of the Paratext users on a project, including users that do not have an SF account." or "A Paratext user on a project (whether or not they have an SF account).".

Can we say whether there will ever be more than one of these for a given Paratext user/username? What I mean is, if Paratext user "Bob" is on project 1 and project 2, will there be _two_ ParatextUserProfile objects for "Bob", or will there only ever be one "Bob" ParatextUserProfile? You might write, "A ParatextUserProfile can be used by more than one project." if that's true.



_Code quote:_
```Smalltalk
The paratext users on a project including users t
```
___
*[src/SIL.XForge.Scripture/Models/ParatextUserProfile.cs, line 8 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxAe40p8Ml3n5lv8aUD:-MxAe40p8Ml3n5lv8aUE:b45pe0h) ([raw file](https://github.com/sillsdev/web-xforge/blob/2f3b18b6ee568cfddb1431baa77f6dd30348f184/src/SIL.XForge.Scripture/Models/ParatextUserProfile.cs#L8)):*
> ```Smalltalk
>     public class ParatextUserProfile
>     {
>         public string Username { get; set; }
> ```

SF often has references to "user id" or "project id" or "user name". Sometimes it's really clear if it's an SF user id, or a PT user id. Sometimes I need to look at how the data is used to know. But I know right away if we write "sf" or "pt" in the variable name. Can we either (1) write a comment saying "Paratext username", or (2) change the property to `PTUsername`. 



_Code quote:_
```Smalltalk
Username
```
___
*[src/SIL.XForge.Scripture/Models/ParatextUserProfile.cs, line 9 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxAej9eAvZaPdgiLxqg:-MxAej9eAvZaPdgiLxqh:bajfdh6) ([raw file](https://github.com/sillsdev/web-xforge/blob/2f3b18b6ee568cfddb1431baa77f6dd30348f184/src/SIL.XForge.Scripture/Models/ParatextUserProfile.cs#L9)):*
> ```Smalltalk
>     {
>         public string Username { get; set; }
>         // A unique id that can be used to associate an project component (e.g. a note) to this paratext user
> ```

Oops. s/an/a/



_Code quote:_
```Smalltalk
n
```
___
*[src/SIL.XForge.Scripture/Models/ParatextUserProfile.cs, line 9 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxAen9x0NgWkvzzhZdT:-MxAen9x0NgWkvzzhZdU:b8omy3v) ([raw file](https://github.com/sillsdev/web-xforge/blob/2f3b18b6ee568cfddb1431baa77f6dd30348f184/src/SIL.XForge.Scripture/Models/ParatextUserProfile.cs#L9)):*
> ```Smalltalk
>     {
>         public string Username { get; set; }
>         // A unique id that can be used to associate an project component (e.g. a note) to this paratext user
> ```

Let's use `/// <summary>...</summary>` to benefit from intellisense showing the docs.



_Code quote:_
```Smalltalk
// 
```
___
*[src/SIL.XForge.Scripture/Models/ParatextUserProfile.cs, line 11 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxAeyJn3L8mMg7OR5qX:-MxAeyJn3L8mMg7OR5qY:b91jdth) ([raw file](https://github.com/sillsdev/web-xforge/blob/2f3b18b6ee568cfddb1431baa77f6dd30348f184/src/SIL.XForge.Scripture/Models/ParatextUserProfile.cs#L11)):*
> ```Smalltalk
>         // A unique id that can be used to associate an project component (e.g. a note) to this paratext user
>         public string OpaqueUserId { get; set; }
>         public string SfUserId { get; set; }
> ```

IIRC we capitalize two-letter acronymns, so this would be `SFUserId`. You might also write `userSFId`.



_Code quote:_
```Smalltalk
 SfUserId 
```
___
*[src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs, line 260 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxBSAjj6ckNljbAjyZi:-MxBSAjj6ckNljbAjyZj:b2ilrbf) ([raw file](https://github.com/sillsdev/web-xforge/blob/2f3b18b6ee568cfddb1431baa77f6dd30348f184/src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs#L260)):*
> ```Smalltalk
>             Dictionary<string, ParatextUserProfile> ptProjectUsers)
>         {
>             Console.WriteLine($"returning (note mapper) for: {paratextUsername}");
> ```

Let's omit this or convert it to a trace-level log item.



_Code quote:_
```Smalltalk
Console.WriteLine($"returning 
```
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 817 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxAzm9g3_7jHGSs9L-E:-MxAzm9g3_7jHGSs9L-F:b-t46rln) ([raw file](https://github.com/sillsdev/web-xforge/blob/2f3b18b6ee568cfddb1431baa77f6dd30348f184/src/SIL.XForge.Scripture/Services/ParatextService.cs#L817)):*
> ```Smalltalk
>                     threadChange.AddChange(CreateNoteFromComment(
>                         _guidService.NewObjectId(), comment, commentIconTag, ptProjectUsers), ChangeType.Added);
>                     Console.WriteLine($"created note: {threadChange.NotesAdded[0].DataId}");
> ```

Let's omit this or log it at a specific level, like trace or debug.



_Code quote:_
```Smalltalk
Console.WriteLine($"created note:
```
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 842 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxB-2dwD0OLnKDTs_um:-MxB-2dwD0OLnKDTs_un:bd5ktt3) ([raw file](https://github.com/sillsdev/web-xforge/blob/2f3b18b6ee568cfddb1431baa77f6dd30348f184/src/SIL.XForge.Scripture/Services/ParatextService.cs#L842)):*
> ```Smalltalk
>                 newThread.Position = GetThreadTextAnchor(thread, chapterDeltas);
>                 newThread.Status = thread.Status.InternalValue;
>                 newThread.AssignedNoteUserRef = GetAssignedUserRef(thread.AssignedUser, ptProjectUsers);
> ```

A thread assignment is based on the latest note assignment, right?



_Code quote:_
```Smalltalk
GetAssignedUserRef(thread.AssignedUser,
```
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 1538 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxB00lmDlUR0ztdW-a6:-MxB00lmDlUR0ztdW-a7:b-if5ros) ([raw file](https://github.com/sillsdev/web-xforge/blob/2f3b18b6ee568cfddb1431baa77f6dd30348f184/ [...]

2022-03-02 23:26 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1227)* status: 56 of 69 files reviewed, 29 unresolved discussions (waiting on @ddaspit and @marksvc)

___
*[src/SIL.XForge.Scripture/Models/Note.cs, line 12 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxAVfni9qsljjBk63sa:-MxBlQr7CJQWSarVJ5Ih:bfkfocc) ([raw file](https://github.com/sillsdev/web-xforge/blob/2f3b18b6ee568cfddb1431baa77f6dd30348f184/src/SIL.XForge.Scripture/Models/Note.cs#L12)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Hmm, okay. And is this going to be the string of the ParatextUserProfile.OpaqueUserId ?
I think "AssignedNoteUserRef" is confusing about what is being meant.
I think "AssignedUserRef" seems like it might be the SF user id. 
I'm tying to think what we could call it that makes it clear what it is, and that it's not an SF user id :). 
I think `AssignedOpaquePTUserId` might be quite descriptive, but unpleasant. Hey, since this can be other descriptions, like "team" and "unassigned", I suggest that this property be called `Assignment`, and have a comment saying 'Who this note is assigned to. This may be a ParatextUserProfile OpaqueUserId, or a category such as "team" or "unassigned".'


</blockquote></details>

I like the Assignment name since it opens it up to be assigned to a specific user or to team or unassigned.
___
*[src/SIL.XForge.Scripture/Models/ParatextUserProfile.cs, line 4 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxAdN1fBuMIA0NvFoY0:-MxBm-Ap5HF2xqVSwYix:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/2f3b18b6ee568cfddb1431baa77f6dd30348f184/src/SIL.XForge.Scripture/Models/ParatextUserProfile.cs#L4)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

If this model is for a single user, let's adjust the comment to not describe it as a plural set. For example, "One of the Paratext users on a project, including users that do not have an SF account." or "A Paratext user on a project (whether or not they have an SF account).".

Can we say whether there will ever be more than one of these for a given Paratext user/username? What I mean is, if Paratext user "Bob" is on project 1 and project 2, will there be _two_ ParatextUserProfile objects for "Bob", or will there only ever be one "Bob" ParatextUserProfile? You might write, "A ParatextUserProfile can be used by more than one project." if that's true.
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/Models/ParatextUserProfile.cs, line 8 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxAe40p8Ml3n5lv8aUD:-MxBmQhp99fVulEA-3qD:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/2f3b18b6ee568cfddb1431baa77f6dd30348f184/src/SIL.XForge.Scripture/Models/ParatextUserProfile.cs#L8)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

SF often has references to "user id" or "project id" or "user name". Sometimes it's really clear if it's an SF user id, or a PT user id. Sometimes I need to look at how the data is used to know. But I know right away if we write "sf" or "pt" in the variable name. Can we either (1) write a comment saying "Paratext username", or (2) change the property to `PTUsername`. 
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/Models/ParatextUserProfile.cs, line 9 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxAej9eAvZaPdgiLxqg:-MxBmDcnCx52UV18bNXN:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/2f3b18b6ee568cfddb1431baa77f6dd30348f184/src/SIL.XForge.Scripture/Models/ParatextUserProfile.cs#L9)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Oops. s/an/a/
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/Models/ParatextUserProfile.cs, line 9 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxAen9x0NgWkvzzhZdT:-MxBmELnDtQZVKGTbe4u:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/2f3b18b6ee568cfddb1431baa77f6dd30348f184/src/SIL.XForge.Scripture/Models/ParatextUserProfile.cs#L9)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Let's use `/// <summary>...</summary>` to benefit from intellisense showing the docs.
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/Models/ParatextUserProfile.cs, line 11 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxAeyJn3L8mMg7OR5qX:-MxBwsip7IrQtL63aqxi:b-ax42gm) ([raw file](https://github.com/sillsdev/web-xforge/blob/2f3b18b6ee568cfddb1431baa77f6dd30348f184/src/SIL.XForge.Scripture/Models/ParatextUserProfile.cs#L11)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

IIRC we capitalize two-letter acronymns, so this would be `SFUserId`. You might also write `userSFId`.
</blockquote></details>

I'll look into this further, but right now I'm getting an error saying that it cannot map `sfUserId` when I capitalize the 'f'.
___
*[src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs, line 260 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxBSAjj6ckNljbAjyZi:-MxBmu2Z6zC1VvCDE2sD:b-7cga8w) ([raw file](https://github.com/sillsdev/web-xforge/blob/2f3b18b6ee568cfddb1431baa77f6dd30348f184/src/SIL.XForge.Scripture/Services/ParatextNotesMapper.cs#L260)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Let's omit this or convert it to a trace-level log item.
</blockquote></details>

Whoops, left that in there by accident.
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 817 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxAzm9g3_7jHGSs9L-E:-MxBmxOV5jTwtrPpI732:bujj58) ([raw file](https://github.com/sillsdev/web-xforge/blob/2f3b18b6ee568cfddb1431baa77f6dd30348f184/src/SIL.XForge.Scripture/Services/ParatextService.cs#L817)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Let's omit this or log it at a specific level, like trace or debug.
</blockquote></details>

Also left in by accident.
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 842 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxB-2dwD0OLnKDTs_um:-MxBn8mkAP1KUwKlJLeP:b-ht0ukm) ([raw file](https://github.com/sillsdev/web-xforge/blob/2f3b18b6ee568cfddb1431baa77f6dd30348f184/src/SIL.XForge.Scripture/Services/ParatextService.cs#L842)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

A thread assignment is based on the latest note assignment, right?
</blockquote></details>

That's right.
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 1538 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxB00lmDlUR0ztdW-a6:-MxBnGyt0koT6acvmDia:blkstuk) ([raw file](https://github.com/sillsdev/web-xforge/blob/2f3b18b6ee568cfddb1431baa77f6dd30348f184/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1538)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

It's too bad we don't get to describe the meaning/usage of the types with something in the  language. Because by now I don't remember what the `string` part of `Dictionary<string, ParatextUserProfile>` is for :)

I see from below that it's probably the PT username.
</blockquote></details>

Haha, it's true. I'll lose track of what the keys or values in a dictionary is frequently.
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 1581 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxB169yBvj9AeSQI4sq:-MxBnU9I-b2V2aTS8bat:b-3g827q) ([raw file](https://github.com/sillsdev/web-xforge/blob/2f3b18b6ee568cfddb1431baa77f6dd30348f184/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1581)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Wait, is that going to work? The sync user needs to be a user who has both a SF account and a PT account. `comment.User` is (presumably) a PT username, but without guarantee that they have an SF account [...]

2022-03-03 17:28 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1227)* status: 45 of 70 files reviewed, 29 unresolved discussions (waiting on @ddaspit and @marksvc)

___
*[src/SIL.XForge.Scripture/Models/ParatextUserProfile.cs, line 11 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxAeyJn3L8mMg7OR5qX:-MxFoHidCMyWWnxltzUL:bhlfzqm) ([raw file](https://github.com/sillsdev/web-xforge/blob/2f3b18b6ee568cfddb1431baa77f6dd30348f184/src/SIL.XForge.Scripture/Models/ParatextUserProfile.cs#L11)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I'll look into this further, but right now I'm getting an error saying that it cannot map `sfUserId` when I capitalize the 'f'.
</blockquote></details>

So I'm not sure why reading 'sfUserId' from the database was causing issues for mongo, but I suspect that when we capitalize the 'f' in SFUserId, the automapping doesn't catch that correctly. I've added a line to specifically map 'sfUserId' to `ParatextUserProfile.SFUserId`.


<!-- Sent from Reviewable.io -->

2022-03-03 20:39 UTC, marksvc requested changes
> Reviewed 7 of 65 files at r2, 3 of 7 files at r4, 9 of 18 files at r6.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1227)* status: 56 of 70 files reviewed, 18 unresolved discussions (waiting on @ddaspit, @marksvc, and @RaymondLuong3)

___
*[src/RealtimeServer/scriptureforge/services/sf-project-service.ts, line 18 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxGRJ4CBtfNWGRTqT8y:-MxGRJ4CBtfNWGRTqT8z:b-hygk56) ([raw file](https://github.com/sillsdev/web-xforge/blob/1db9c3dbabb1dc1df719b367a16614e18b5b1d3a/src/RealtimeServer/scriptureforge/services/sf-project-service.ts#L18)):*
> ```XML
> import { SF_PROJECT_MIGRATIONS } from './sf-project-migrations';
> 
> const SF_PROJECT_PROFILE_FIELDS: ShareDB.ProjectionFields = {
> ```

I notice that this list does not include
- sync
- paratextId
which are present in the new interface `SFProjectProfile`. Was that intentional? 



_Code quote:_
```XML
SF_PROJECT_PROFILE_FIELDS
```
___
*[src/RealtimeServer/scriptureforge/services/sf-project-service.ts, line 42 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxGMhMT9QwNoxi2QDKs:-MxGMhMT9QwNoxi2QDKt:bv56emr) ([raw file](https://github.com/sillsdev/web-xforge/blob/1db9c3dbabb1dc1df719b367a16614e18b5b1d3a/src/RealtimeServer/scriptureforge/services/sf-project-service.ts#L42)):*
> ```XML
>     super(SF_PROJECT_MIGRATIONS);
> 
>     const immutableProps = [
> ```

Should this  set now contain the paratextUsers list?



_Code quote:_
```XML
immutableProps 
```
___
*[src/RealtimeServer/scriptureforge/services/sf-project-service.ts, line 64 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxGRq_O1MSoB2chMfQ-:-MxGRq_O1MSoB2chMfQ0:b-pocrmr) ([raw file](https://github.com/sillsdev/web-xforge/blob/1db9c3dbabb1dc1df719b367a16614e18b5b1d3a/src/RealtimeServer/scriptureforge/services/sf-project-service.ts#L64)):*
> ```XML
>     }
>     if (this.hasRight(session.userId, doc, Operation.View)) {
>       return true;
> ```

Does this somehow discern whether the user is or isn't allowed to read the new `paratextUsers` set?



_Code quote:_
```XML
    if (this.hasRight(session.userId, doc, Operation.View)) {
      return true;
```
___
*[src/RealtimeServer/scriptureforge/services/sf-project-service.ts, line 67 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxGN4UB-yMGqEIgaBEV:-MxGN4UB-yMGqEIgaBEW:bq9ktoi) ([raw file](https://github.com/sillsdev/web-xforge/blob/1db9c3dbabb1dc1df719b367a16614e18b5b1d3a/src/RealtimeServer/scriptureforge/services/sf-project-service.ts#L67)):*
> ```XML
>     }
>     for (const key of Object.keys(doc)) {
>       if (!Object.prototype.hasOwnProperty.call(SF_PROJECT_PROFILE_FIELDS, key)) {
> ```

Can you explain this? (Just here in reviewable)



_Code quote:_
```XML
 if (!Object.prototype.hasOwnProperty.call(SF_PROJECT_PROFILE_FIELDS, key)) {
```
___
*[src/RealtimeServer/scriptureforge/services/sf-project-service.ts, line 75 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxGPWap2uXxyJyD3PJv:-MxGPWap2uXxyJyD3PJw:b-csogjy) ([raw file](https://github.com/sillsdev/web-xforge/blob/1db9c3dbabb1dc1df719b367a16614e18b5b1d3a/src/RealtimeServer/scriptureforge/services/sf-project-service.ts#L75)):*
> ```XML
> 
>   protected setupDomains(): ProjectDomainConfig[] {
>     return [{ projectDomain: SFProjectDomain.Project, pathTemplate: this.pathTemplate() }];
> ```

I have much to learn in this area. But I'll mention from looking at other files that maybe this would have also contained a SFProjectProfile domain.



_Code quote:_
```XML
 SFProjectDomain.Project
```
___
*[src/SIL.XForge.Scripture/Models/ParatextUserProfile.cs, line 8 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxAe40p8Ml3n5lv8aUD:-MxFvRglCgNKBts6DlDc:b-ezrofh) ([raw file](https://github.com/sillsdev/web-xforge/blob/2f3b18b6ee568cfddb1431baa77f6dd30348f184/src/SIL.XForge.Scripture/Models/ParatextUserProfile.cs#L8)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Great! And can it be in `/// <summary>` so intellisense shows it?
___
*[src/SIL.XForge.Scripture/Models/ParatextUserProfile.cs, line 11 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxAeyJn3L8mMg7OR5qX:-MxFvfUv4KRBHvV1d7sK:b-8rcjoo) ([raw file](https://github.com/sillsdev/web-xforge/blob/2f3b18b6ee568cfddb1431baa77f6dd30348f184/src/SIL.XForge.Scripture/Models/ParatextUserProfile.cs#L11)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

So I'm not sure why reading 'sfUserId' from the database was causing issues for mongo, but I suspect that when we capitalize the 'f' in SFUserId, the automapping doesn't catch that correctly. I've added a line to specifically map 'sfUserId' to `ParatextUserProfile.SFUserId`.
</blockquote></details>

Good job figuring out how to do that :)
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 842 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxB-2dwD0OLnKDTs_um:-MxFvxAt0Qg6z-BmSmvJ:b-h6u25f) ([raw file](https://github.com/sillsdev/web-xforge/blob/2f3b18b6ee568cfddb1431baa77f6dd30348f184/src/SIL.XForge.Scripture/Services/ParatextService.cs#L842)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

That's right.
</blockquote></details>

I'll mention in case it's helpful to keep in mind, that we could chose to not store the thread assignment, and instead always derive it from the latest note assignment, if found to be helpful.
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 1581 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxB169yBvj9AeSQI4sq:-MxFwN4cElExicDtTK7C:ba9vpck) ([raw file](https://github.com/sillsdev/web-xforge/blob/2f3b18b6ee568cfddb1431baa77f6dd30348f184/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1581)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

That's right, a user on the paratext project will have ParatextUserProfile created for them here. But they will not necessarily be on the SF project. So they will not have an `SFUserId` property, but they always have the `OpaqueUserId` defined.
</blockquote></details>

But we can only use a sync user successfully if we have their token or something, right? Oh, maybe do we not need a token for them, but we use our own authentication and just make a record that the sync user did it? In other words, we could give any paratext username, and the sync user set helps us give one that's a good choice?


<!-- Sent from Reviewable.io -->

2022-03-03 22:03 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1227)* status: 56 of 70 files reviewed, 18 unresolved discussions (waiting on @ddaspit and @marksvc)

___
*[src/RealtimeServer/scriptureforge/services/sf-project-service.ts, line 18 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxGRJ4CBtfNWGRTqT8y:-MxGXAcZEKy335Tt6BTt:b-m1e86a) ([raw file](https://github.com/sillsdev/web-xforge/blob/1db9c3dbabb1dc1df719b367a16614e18b5b1d3a/src/RealtimeServer/scriptureforge/services/sf-project-service.ts#L18)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I notice that this list does not include
- sync
- paratextId
which are present in the new interface `SFProjectProfile`. Was that intentional? 
</blockquote></details>

Good catch. I must have been thinking that paratextId and sync were not necessary for the typical user. That is still true, but there is no reason to hide those fields.
___
*[src/RealtimeServer/scriptureforge/services/sf-project-service.ts, line 42 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxGMhMT9QwNoxi2QDKs:-MxGY-6F3YY0XuxaMwGz:bea4scg) ([raw file](https://github.com/sillsdev/web-xforge/blob/1db9c3dbabb1dc1df719b367a16614e18b5b1d3a/src/RealtimeServer/scriptureforge/services/sf-project-service.ts#L42)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Should this  set now contain the paratextUsers list?
</blockquote></details>

Yes, I think that is what we want to do.
___
*[src/RealtimeServer/scriptureforge/services/sf-project-service.ts, line 64 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxGRq_O1MSoB2chMfQ-:-MxGY5GV2iqqYMoPTBLs:b-afsrjo) ([raw file](https://github.com/sillsdev/web-xforge/blob/1db9c3dbabb1dc1df719b367a16614e18b5b1d3a/src/RealtimeServer/scriptureforge/services/sf-project-service.ts#L64)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Does this somehow discern whether the user is or isn't allowed to read the new `paratextUsers` set?
</blockquote></details>

This checks that the user has a role that allows them to see the doc (a paratext role). And only if they are a paratext user on the project can they see the sf-project.
___
*[src/RealtimeServer/scriptureforge/services/sf-project-service.ts, line 67 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxGN4UB-yMGqEIgaBEV:-MxGZ00UDmyqcnGMcD_d:bx67y0u) ([raw file](https://github.com/sillsdev/web-xforge/blob/1db9c3dbabb1dc1df719b367a16614e18b5b1d3a/src/RealtimeServer/scriptureforge/services/sf-project-service.ts#L67)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Can you explain this? (Just here in reviewable)
</blockquote></details>

It is similar to what was happening in userProfile. It checks that the doc only has the allowed properties. If the doc hasn't been projected correctly, then this will see the `ParatextUsers` property exists in this doc, and will not allow the non-partext user to see the doc.
___
*[src/RealtimeServer/scriptureforge/services/sf-project-service.ts, line 75 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxGPWap2uXxyJyD3PJv:-MxGZzAV7Tip0yA8cdc7:b9fbzcf) ([raw file](https://github.com/sillsdev/web-xforge/blob/1db9c3dbabb1dc1df719b367a16614e18b5b1d3a/src/RealtimeServer/scriptureforge/services/sf-project-service.ts#L75)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I have much to learn in this area. But I'll mention from looking at other files that maybe this would have also contained a SFProjectProfile domain.
</blockquote></details>

Right, I didn't think about adding the SFProjectProfile domain here. When you specify a domain, I believe you are saying that certain operations can be performed on it. But we really don't won't users to be modifying SFProjectProfile. If they need to modify anything, they must have access to the SFProject.
___
*[src/SIL.XForge.Scripture/Models/ParatextUserProfile.cs, line 8 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxAe40p8Ml3n5lv8aUD:-MxGlI2f0d3yqFXmHz0f:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/2f3b18b6ee568cfddb1431baa77f6dd30348f184/src/SIL.XForge.Scripture/Models/ParatextUserProfile.cs#L8)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Great! And can it be in `/// <summary>` so intellisense shows it?
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/Models/ParatextUserProfile.cs, line 11 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxAeyJn3L8mMg7OR5qX:-MxGlJj05S0EZtTYBfX6:bgez85m) ([raw file](https://github.com/sillsdev/web-xforge/blob/2f3b18b6ee568cfddb1431baa77f6dd30348f184/src/SIL.XForge.Scripture/Models/ParatextUserProfile.cs#L11)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Good job figuring out how to do that :)
</blockquote></details>

Thanks, I'm glad the serializer is as extensible as it is.
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 842 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxB-2dwD0OLnKDTs_um:-MxGlue20ZgwpekJOMeM:b-fco98x) ([raw file](https://github.com/sillsdev/web-xforge/blob/2f3b18b6ee568cfddb1431baa77f6dd30348f184/src/SIL.XForge.Scripture/Services/ParatextService.cs#L842)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I'll mention in case it's helpful to keep in mind, that we could chose to not store the thread assignment, and instead always derive it from the latest note assignment, if found to be helpful.
</blockquote></details>

I have thought of that too. At the moment I could go either way.
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 1581 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxB169yBvj9AeSQI4sq:-MxGmHFl-hLlVLECnPjR:b-n6khgq) ([raw file](https://github.com/sillsdev/web-xforge/blob/2f3b18b6ee568cfddb1431baa77f6dd30348f184/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1581)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

But we can only use a sync user successfully if we have their token or something, right? Oh, maybe do we not need a token for them, but we use our own authentication and just make a record that the sync user did it? In other words, we could give any paratext username, and the sync user set helps us give one that's a good choice?
</blockquote></details>

I think I understand your question as, "do we use a specific Paratext user's token to authenticate the updates to the notes?" To my understanding, when we write text to a project from Scripture Forge, there are limitations on who can write, and I believe that we get the correct user with permission to write to a book. But when we write notes, users without permission are written by the user doing the sync. The SyncUserRef just helps us to know which authorized user synced which note.


<!-- Sent from Reviewable.io -->

2022-03-08 21:05 UTC, marksvc requested changes
> Reviewed 1 of 18 files at r6, 3 of 7 files at r7.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1227)* status: 55 of 70 files reviewed, 12 unresolved discussions (waiting on @ddaspit, @marksvc, and @RaymondLuong3)

___
*[src/RealtimeServer/scriptureforge/services/sf-project-service.ts, line 64 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxGRq_O1MSoB2chMfQ-:-MxeoPZgDm72BAOC6e5w:b-gdjiw) ([raw file](https://github.com/sillsdev/web-xforge/blob/1db9c3dbabb1dc1df719b367a16614e18b5b1d3a/src/RealtimeServer/scriptureforge/services/sf-project-service.ts#L64)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This checks that the user has a role that allows them to see the doc (a paratext role). And only if they are a paratext user on the project can they see the sf-project.
</blockquote></details>

Now, if the user is trying to view something on the new SFProjectProfile,  that decided by the next bit of code, the for loop, right. So we here would check and see that the non-paratext user doesn't have View access to the SFProject doc, and so we don't return true. But then we get to the for loop and we check if the doc object in question is actually not a SFProject object, but really a SFProjectProfile object, and if so then we call `super.allowRead()` and perhaps return true. Is that so?

Hmm. Because `allowRead()` here receives a `doc: SFProject`, and because according to sf-project.ts, `interface SFProject extends SFProjectProfile` and not the other way around, aren't we expecting that  `SFProject` objects will be passed for `doc`, and  we aren't expecting that `doc` will ever be just a `SFProjectProfile`? (Unless something interesting happens at runtime). 
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 1581 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxB169yBvj9AeSQI4sq:-MxeyV8SEl65LnUAgg4F:bbtr0tt) ([raw file](https://github.com/sillsdev/web-xforge/blob/2f3b18b6ee568cfddb1431baa77f6dd30348f184/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1581)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I think I understand your question as, "do we use a specific Paratext user's token to authenticate the updates to the notes?" To my understanding, when we write text to a project from Scripture Forge, there are limitations on who can write, and I believe that we get the correct user with permission to write to a book. But when we write notes, users without permission are written by the user doing the sync. The SyncUserRef just helps us to know which authorized user synced which note.
</blockquote></details>

If we use credentials of the SyncUser to write to Paratext, then I wouldn't think it would be adequate to just create a SyncUser here. But regarding whether we do use credentials of a sync user to write to Paratext, I haven't learned what I want from looking around in the code today to say :).

Do you understand what I mean? If this line is going to _create_ a syncuser, to match a paratext user for which we do not have a token and who does not have an SF user account, then the syncuser that is created won't be of any help to authorize to write a note/thread. And so if we were relying on having an authorization token for such a syncuser, we won't have what we need.


<!-- Sent from Reviewable.io -->

2022-03-08 23:44 UTC, marksvc requested changes
> Reviewed 4 of 65 files at r2, 2 of 2 files at r3, 2 of 7 files at r4, 1 of 18 files at r6, 2 of 7 files at r7.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1227)* status: 58 of 70 files reviewed, 13 unresolved discussions (waiting on @ddaspit, @marksvc, and @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts, line 52 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxfoOQC7T--hk6uKfUE:-MxfoOQC7T--hk6uKfUF:bh9wrny) ([raw file](https://github.com/sillsdev/web-xforge/blob/b22dd353641b71adbc93af0709afe9c80c574be2/src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts#L52)):*
> ```XML
>    * otherwise returns undefined.
>    */
>   async tryGetForRole(id: string, role: string): Promise<SFProjectDoc | undefined> {
> ```

It seems strange that we have this method in the client that lets the client specify the role to use. 
I'm supposing that this is a preflight check where we only call `this.get(id)` if we think we will have access, and if we think we won't have access, we don't call `this.get(id)`. And that the role/access is checked again on the backend somewhere down the line of calling `this.get(id)`.
And so if a user modifies their client to replace `role` with "Super Administrator Role", then even if `.roleHasRight()` returns true, when we run `await this.get(id)` it will none the less fail. 
Is that accurate?



_Code quote:_
```XML
 async tryGetForRole(id: string, role: string):
```
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 333 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-Mxfq2VdDxfTWPevc-4-:-Mxfq2VdDxfTWPevc-40:b1wdhs1) ([raw file](https://github.com/sillsdev/web-xforge/blob/b22dd353641b71adbc93af0709afe9c80c574be2/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L333)):*
> ```XML
>           const userRole: string | undefined = this.projectDoc.data?.userRoles[this.userService.currentUserId];
>           if (userRole != null) {
>             const projectDoc: SFProjectDoc | undefined = await this.projectService.tryGetForRole(projectId, userRole);
> ```

Hmm it seems like we could instead call like
```ts
const projectDoc: SFProjectDoc | undefined = await this.projectService.tryGet(projectId);
```
and it would call project service code of
```ts
async tryGet(projectSFId: string) {
  const projectDoc = this.getProfile(projectSFId);
  const requestingUserRole = projectDoc.data.userRoles[userService.currentUserId]
  if requestingUserRole is good to View,
    return await this.get(id)
  return undefined
}
```
But if we did that, then project service would need to know about and use user service, and the way we have it here, they don't need to know about how to use each other.



_Code quote:_
```XML
await this.projectService.tryGetForRole(projectId, userRole);
```


<!-- Sent from Reviewable.io -->

2022-03-08 23:50 UTC, marksvc reviewed
> Reviewed 3 of 65 files at r2, 1 of 18 files at r6.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1227)* status: 59 of 70 files reviewed, 13 unresolved discussions (waiting on @ddaspit, @marksvc, and @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2022-03-09 17:40 UTC, marksvc requested changes
> Reviewed 2 of 65 files at r2, 1 of 18 files at r6.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1227)* status: 62 of 70 files reviewed, 14 unresolved discussions (waiting on @ddaspit, @marksvc, and @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts, line 204 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxjkEO99_myttGuHzPH:-MxjkEO99_myttGuHzPI:bn7ru9f) ([raw file](https://github.com/sillsdev/web-xforge/blob/b22dd353641b71adbc93af0709afe9c80c574be2/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L204)):*
> ```XML
>       u => u.opaqueUserId === assignedNoteUserRef
>     );
>     return paratextUser?.username || translate('note_dialog.paratext_user');
> ```

For this fallback in the case of an undefined, let's be specific and use `??` rather than checking for falsy with ||.



_Code quote:_
```XML
|| 
```


<!-- Sent from Reviewable.io -->

2022-03-09 17:58 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1227)* status: 62 of 70 files reviewed, 14 unresolved discussions (waiting on @ddaspit and @marksvc)

___
*[src/RealtimeServer/scriptureforge/services/sf-project-service.ts, line 64 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxGRq_O1MSoB2chMfQ-:-MxjkuRj26Okk7ISWQ9G:b-b8r8wa) ([raw file](https://github.com/sillsdev/web-xforge/blob/1db9c3dbabb1dc1df719b367a16614e18b5b1d3a/src/RealtimeServer/scriptureforge/services/sf-project-service.ts#L64)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Now, if the user is trying to view something on the new SFProjectProfile,  that decided by the next bit of code, the for loop, right. So we here would check and see that the non-paratext user doesn't have View access to the SFProject doc, and so we don't return true. But then we get to the for loop and we check if the doc object in question is actually not a SFProject object, but really a SFProjectProfile object, and if so then we call `super.allowRead()` and perhaps return true. Is that so?

Hmm. Because `allowRead()` here receives a `doc: SFProject`, and because according to sf-project.ts, `interface SFProject extends SFProjectProfile` and not the other way around, aren't we expecting that  `SFProject` objects will be passed for `doc`, and  we aren't expecting that `doc` will ever be just a `SFProjectProfile`? (Unless something interesting happens at runtime). 
</blockquote></details>

So what you are saying is correct, it seems like the `doc` would be an SFProject, but the reality is that when we hit the db for the `SFProjectProfile` projection, the `doc` will be the `SFProjectProfile`. (At least that's what I've observed) You can see the inspiration for this in `src/RealtimeServer/common/services/user-service.ts` 
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts, line 52 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxfoOQC7T--hk6uKfUE:-MxjlaqHEL7a67Px2C3C:bv1pktn) ([raw file](https://github.com/sillsdev/web-xforge/blob/b22dd353641b71adbc93af0709afe9c80c574be2/src/SIL.XForge.Scripture/ClientApp/src/app/core/sf-project.service.ts#L52)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

It seems strange that we have this method in the client that lets the client specify the role to use. 
I'm supposing that this is a preflight check where we only call `this.get(id)` if we think we will have access, and if we think we won't have access, we don't call `this.get(id)`. And that the role/access is checked again on the backend somewhere down the line of calling `this.get(id)`.
And so if a user modifies their client to replace `role` with "Super Administrator Role", then even if `.roleHasRight()` returns true, when we run `await this.get(id)` it will none the less fail. 
Is that accurate?
</blockquote></details>

That's correct, this is the front-end check, but the Realtime server also checks whether the user is allowed to read the doc. So if ever we call `this.get(id)` and the user really does not have access to read, an error will be thrown.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts, line 333 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-Mxfq2VdDxfTWPevc-4-:-MxjluIj0vEgbVow6l0H:b-bprayq) ([raw file](https://github.com/sillsdev/web-xforge/blob/b22dd353641b71adbc93af0709afe9c80c574be2/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L333)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Hmm it seems like we could instead call like
```ts
const projectDoc: SFProjectDoc | undefined = await this.projectService.tryGet(projectId);
```
and it would call project service code of
```ts
async tryGet(projectSFId: string) {
  const projectDoc = this.getProfile(projectSFId);
  const requestingUserRole = projectDoc.data.userRoles[userService.currentUserId]
  if requestingUserRole is good to View,
    return await this.get(id)
  return undefined
}
```
But if we did that, then project service would need to know about and use user service, and the way we have it here, they don't need to know about how to use each other.


</blockquote></details>

I believe I thought the same thing. It would be neat to encapsulate the `tryGet` all in the `projectService` but then project service would need to access the `userService` when it is not necessary since it is already available to `editor.component`
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts, line 204 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxjkEO99_myttGuHzPH:-MxjmkW272voleYJ9tyv:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/b22dd353641b71adbc93af0709afe9c80c574be2/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.ts#L204)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

For this fallback in the case of an undefined, let's be specific and use `??` rather than checking for falsy with ||.
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 1581 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxB169yBvj9AeSQI4sq:-MxjmlRi9zjFirm1aEbL:bgp8a4t) ([raw file](https://github.com/sillsdev/web-xforge/blob/2f3b18b6ee568cfddb1431baa77f6dd30348f184/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1581)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

If we use credentials of the SyncUser to write to Paratext, then I wouldn't think it would be adequate to just create a SyncUser here. But regarding whether we do use credentials of a sync user to write to Paratext, I haven't learned what I want from looking around in the code today to say :).

Do you understand what I mean? If this line is going to _create_ a syncuser, to match a paratext user for which we do not have a token and who does not have an SF user account, then the syncuser that is created won't be of any help to authorize to write a note/thread. And so if we were relying on having an authorization token for such a syncuser, we won't have what we need.
</blockquote></details>

Maybe I should have been more clear. We do not need any access tokens to write a note. The only thing we need to write a note is the author's username. You can see `ParatextService.PutCommentThreads` to see what I mean.


<!-- Sent from Reviewable.io -->

2022-03-09 21:31 UTC, marksvc commented
___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 1581 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxB169yBvj9AeSQI4sq:-MxkNu0OB-DlGBxVrZEc:bdo8lx9) ([raw file](https://github.com/sillsdev/web-xforge/blob/2f3b18b6ee568cfddb1431baa77f6dd30348f184/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1581)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Maybe I should have been more clear. We do not need any access tokens to write a note. The only thing we need to write a note is the author's username. You can see `ParatextService.PutCommentThreads` to see what I mean.
</blockquote></details>

Thank you. 

Hmm.
So our NoteThread.cs has or inherits fields of:
- ParatextUser
- OwnerRef

And our Note.cs has or inherits fields of:
- ExtUserId
- OwnerRef
- SyncUserRef

I'm looking to see how these fields are used in SF.
For NoteThread.ParatextUser, this appears to be unused? I can't tell that it's used in SF. :)
For Note.ExtUserId, it appears that this is basically only written to and never used for anything useful by SF? I see it's also perhaps written to in ParatextNoteSmapper.AddCommentIfChangedAsync() with some XML.
For Note.OwnerRef, it appears to be: SF user id of the note author, or as a fallback, the user who syncd the note.

Note.SyncUserRef is interesting. I see that this is the OpaqueUserId of a ParatextUserProfile, and either:
- This will refer to the note author, if they are also a SF user on the SF project containing the note, or to some other SF user on the project with a PT account, such as a user who has synchronized the note. 
- It can also be set to the OpaqueUserId of a ParatextUserProfile that records a PT username (of the note author) but has no corresponding SF user. (!)  
Would the following be an accurate description for it, do you think? "The OpaqueUserId of a ParatextUserProfile. This can refer to the note author, whether or not there is an associated SF user on the SF project containing the note, or to some other SF user on the project with a PT account, such as a user who has synchronized the note. It is used to correlate comments between PT and SF."


<!-- Sent from Reviewable.io -->

2022-03-09 22:11 UTC, marksvc reviewed
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1227)* status: 62 of 70 files reviewed, 11 unresolved discussions (waiting on @ddaspit, @marksvc, and @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2022-03-09 22:57 UTC, marksvc requested changes
> Reviewed 1 of 65 files at r2, 1 of 7 files at r7.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1227)* status: 64 of 70 files reviewed, 10 unresolved discussions (waiting on @ddaspit, @marksvc, and @RaymondLuong3)

___
*[test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs, line 731 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxknLr7AfYktca37sDm:-MxknLr7AfYktca37sDn:b-skoqnn) ([raw file](https://github.com/sillsdev/web-xforge/blob/828acb160a60b65014e5ae39ad0ce3c4a5d6567d/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L731)):*
> ```Smalltalk
>                 await env.NotesMapper.DidNotReceiveWithAnyArgs().GetNotesChangelistAsync(Arg.Any<XElement>(),
>                     Arg.Any<IEnumerable<IDocument<Question>>>(), Arg.Any<Dictionary<string, SyncUser>>());
>                 // We should have then called SR
> ```

Have you considered whether SFProjectSecret.cs should still have a SyncUsers property, and whether we should still have a SyncUsers.cs file?
___
*[test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs, line 1178 at r8](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxkoPVF19m_-_FPVE9V:-MxkoPVF19m_-_FPVE9W:b-sgwkt4) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f8fbf503a91628a56582751546028addd2923b9/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L1178)):*
> ```Smalltalk
>                 new[] { "User 1", "User 2", "User 3" }));
>             Assert.That(project.ParatextUsers.Single(u => u.Username == "User 1").SFUserId, Is.EqualTo("user01"));
>             Assert.That(project.ParatextUsers.Single(u => u.Username == "User 3").SFUserId, Is.EqualTo("user03"));
> ```

Is there a reason that "User 2" was omitted from these 2 additions?



_Code quote:_
```Smalltalk
"User 3").SFUserId, Is.EqualTo("user03"));
```


<!-- Sent from Reviewable.io -->

2022-03-10 19:36 UTC, marksvc requested changes
> Reviewed 21 of 65 files at r2, 3 of 18 files at r6, 1 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1227)* status: all files reviewed, 8 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/RealtimeServer/scriptureforge/services/sf-project-service.spec.ts, line 13 at r8](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-Mxp18Hg47RLWgPzl2q7:-Mxp18Hg47RLWgPzl2q8:by8xrza) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f8fbf503a91628a56582751546028addd2923b9/src/RealtimeServer/scriptureforge/services/sf-project-service.spec.ts#L13)):*
> ```XML
> import { SFProjectService } from './sf-project-service';
> 
> describe('SFProjectService', () => {
> ```

Thank you for creating a new spec file. 
BTW I like that this spec has a very clean/simple set of tests.
___
*[src/RealtimeServer/scriptureforge/services/sf-project-service.spec.ts, line 38 at r8](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-Mxozn97DynS37BQDv1g:-Mxozn97DynS37BQDv1h:b3p1nu5) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f8fbf503a91628a56582751546028addd2923b9/src/RealtimeServer/scriptureforge/services/sf-project-service.spec.ts#L38)):*
> ```XML
>   });
> 
>   it('allows system admin user to see project', async () => {
> ```

Could we assert before the SUT that 'sys_admin' is not a user on the project?
___
*[src/RealtimeServer/scriptureforge/services/sf-project-service.spec.ts, line 66 at r8](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-Mxp0ZUTDwO6w2B1Bd3l:-Mxp0ZUU-wWq1dcvWxPz:bej9550) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f8fbf503a91628a56582751546028addd2923b9/src/RealtimeServer/scriptureforge/services/sf-project-service.spec.ts#L66)):*
> new RealtimeServer(

Hmm. Yeah, okay. I would have expected there to be an established Test or Mock for this, but I am getting it mixed up with some of our other pieces.



_Code quote:_
```XML
= new RealtimeServer(
```
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.service.spec.ts, line 200 at r8](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-Mxp68M-DwuRiQHy67bi:-Mxp68M-DwuRiQHy67bj:b9glvjy) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f8fbf503a91628a56582751546028addd2923b9/src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.service.spec.ts#L200)):*
> ```XML
>     paratextUsers: [
>       { sfUserId: this.adminUser.id, username: `pt${this.adminUser.id}`, opaqueUserId: `opaque${this.adminUser.id}` }
>     ],
> ```

Okay. Although because there is a helper method with a specific way to do this activity, you might use it instead, via something like the following, to benefit if something else needs introduced across the board in that area.
```ts
paratextUsers: ptUsersFromRoles_helper_method({[this.adminUser.id]: this.adminUser.role})
```



_Code quote:_
```XML
    paratextUsers: [
      { sfUserId: this.adminUser.id, username: `pt${this.adminUser.id}`, opaqueUserId: `opaque${this.adminUser.id}` }
    ],
```
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/test-utils.ts, line 94 at r8](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-Mxp2NRv25SAu8ufiEMU:-Mxp2NRv25SAu8ufiEMV:b8eau52) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f8fbf503a91628a56582751546028addd2923b9/src/SIL.XForge.Scripture/ClientApp/src/app/shared/test-utils.ts#L94)):*
> ```XML
> }
> 
> export function paratextUsersFromRoles(userRoles: { [id: string]: string }): ParatextUserProfile[] {
> ```

I like it.



_Code quote:_
```XML
n paratextUsersFromRoles
```
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 2797 at r8](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-Mxp9nsv85C_f-RO3rZ2:-Mxp9nsv85C_f-RO3rZ3:bra1ch5) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f8fbf503a91628a56582751546028addd2923b9/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L2797)):*
> ```XML
>     userIds: string[],
>     status: NoteStatus = NoteStatus.Todo,
>     assignedUserRef?: string
> ```

With the different kinds of ids going around, let's give this a name that makes it clear what is being expected, like `assignedSFUserId` or similar.



_Code quote:_
```XML
 assignedUserRef?: string
```
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts, line 410 at r8](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxpHi7818v3mzTyJ-qk:-MxpHi7818v3mzTyJ-ql:b-cvzakg) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f8fbf503a91628a56582751546028addd2923b9/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts#L410)):*
> ```XML
>         id: configData.projectId,
>         data: TestEnvironment.testProjectProfile
>       });
> ```

I might have thought we would have a single chunk of data for the project, and we would have a projection that gives us a subset of it. But presumably we are doing this because of limitations in what TestRealtimeService can handle.



_Code quote:_
```XML
      this.realtimeService.addSnapshot<SFProjectProfile>(SFProjectProfileDoc.COLLECTION, {
        id: configData.projectId,
        data: TestEnvironment.testProjectProfile
      });
```
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.spec.ts, line 484 at r8](https://reviewable.io/reviews/sillsdev/web-xforge/1227#-MxpIgHt7_u6w27u2LoA:-MxpIgHt7_u6w27u2LoB:b6vflwm) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f8fbf503a91628a56582751546028addd2923b9/src/SIL.XForge.Scripture/ClientApp/src/app/users/collaborators/collaborators.component.spec.ts#L484)):*
> ```XML
>     );
>     when(mockedProjectService.getProfile(anything())).thenCall(projectId =>
>       this.realtimeService.subscribe(SFProjectDoc.COLLECTION, projectId)
> ```

This should probably be SFProjectProfileDoc.COLLECTION ?



_Code quote:_
```XML
(SFProjectDoc.COLLECTION
```


<!-- Sent from Reviewable.io -->

2022-03-14 18:59 UTC, marksvc approved these changes
> Reviewed 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1227)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2022-03-14 19:24 UTC, merged