SF-1451b Fix infinite loading indicator when importing offline
sillsdev/web-xforge pull request #1242
Opened 2022-02-12 06:06 UTC by Nateowami

Previously the front end was trying to make sure it had a completely up to date list of existing questions before starting the import. This isn't possible while offline, so it never completed.

The root problem was a wrong assumption by me about what a realtime query's `ready$` really does (caused in turn by a lack of documentation). Hence the change to the test; I was mocking my wrong assumption into the test. It would have taken an actual e2e test to properly test this without my wrong assumption getting in the way.

2022-02-14 19:32 UTC, RaymondLuong3 requested changes
Something I found odd was that if I was offline and I imported a question, the overview page did not update. But if I navigate to the community checking view, the imported question appears in the list. I did this by turning my network to offline. This might be its own issue, but just raising it here.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1242#-:-Mvthg6F7PaqdkJrF2hc:bze784f)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts, line 218 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1242#-Mvth8z85MJl8H0n2Cc8:-Mvth8z85MJl8H0n2Cc9:b-rfap38) ([raw file](https://github.com/sillsdev/web-xforge/blob/39ffcde1a137737dc1333bdb0a932230fdc2f16f/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts#L218)):*
> ```XML
>       await questionQuery.ready$.pipe(first()).toPromise();
>     }
>     questionQuery.dispose();
> ```

Interesting that this was disposed here, but was used a few lines down. I think we need to dispose the questionQuery when the component is disposed. I did a quick search, and all components that use a questionQuery disposes them in a ngOnDestroy lifecycle hook.



_Code quote:_
```XML
    questionQuery.dispose();
```


<!-- Sent from Reviewable.io -->

2022-02-14 22:16 UTC, Nateowami reviewed
Interesting. I just tried this and can't reproduce that issue. I think I've seen it in the past, though I didn't think it was related to being offline.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1242#-:-MvuIULg8BGVFtHgkmmN:b-wdjpur)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts, line 218 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1242#-Mvth8z85MJl8H0n2Cc8:-MvuF_v1BOTnEOtll8uD:b-dqcaho) ([raw file](https://github.com/sillsdev/web-xforge/blob/39ffcde1a137737dc1333bdb0a932230fdc2f16f/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts#L218)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Interesting that this was disposed here, but was used a few lines down. I think we need to dispose the questionQuery when the component is disposed. I did a quick search, and all components that use a questionQuery disposes them in a ngOnDestroy lifecycle hook.
</blockquote></details>

That's a great point. I'll work on this.


<!-- Sent from Reviewable.io -->

2022-02-14 23:18 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1242)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts, line 218 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1242#-Mvth8z85MJl8H0n2Cc8:-MvuVB44950afaZuisBx:b-571dpc) ([raw file](https://github.com/sillsdev/web-xforge/blob/39ffcde1a137737dc1333bdb0a932230fdc2f16f/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts#L218)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

That's a great point. I'll work on this.
</blockquote></details>

Thanks; that was a good catch. Fixed.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts, line 202 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1242#-MvuVKoi2JqFG2atv5QU:-MvuVKoi2JqFG2atv5QV:b5kbjb4) ([raw file](https://github.com/sillsdev/web-xforge/blob/8f6d72d1fc77152757bb33f28663d9f81fe18c61/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts#L202)):*
> ```XML
>   ngOnDestroy(): void {
>     super.ngOnDestroy();
>     this.promiseForQuestionDocQuery.then(query => query.dispose());
> ```

This promise can take a while to resolve, and it's easy to close the dialog before it has resolved. Hence waiting for it if it's not available yet.


<!-- Sent from Reviewable.io -->

2022-02-16 17:17 UTC, RaymondLuong3 approved these changes
Yes, I've also seen it in the past too, and it is very possible it is intermittent. I think it would be worth asking the testers to also test that the questions appear in the overview page after importing while offline.

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1242#-:-Mw2WzFG7OPyKm_H3Nkq:b-nq3u90)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts, line 202 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1242#-MvuVKoi2JqFG2atv5QU:-Mw2WY5Y-PpvtRgWx-qb:b-mbcpfk) ([raw file](https://github.com/sillsdev/web-xforge/blob/8f6d72d1fc77152757bb33f28663d9f81fe18c61/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts#L202)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This promise can take a while to resolve, and it's easy to close the dialog before it has resolved. Hence waiting for it if it's not available yet.
</blockquote></details>

Good thinking.


<!-- Sent from Reviewable.io -->

2022-02-16 18:09 UTC, merged