SF-1471b Remove have-read note refs when remove noteThread
sillsdev/web-xforge pull request #1268
Opened 2022-03-17 22:08 UTC by marksvc

Respond to a noteThread deletion just before it happens, so we still
have access to the noteThread's notes list.

---

**Stack**:
- #1267
- #1266

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2022-03-17 23:04 UTC, marksvc commented
Converting to draft. Not behaving the way I want.

2022-03-22 16:53 UTC, RaymondLuong3 requested changes
I'm glad it was fairly straight forward to hook into the apply event hook. I have one blocking comment.

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1268#-:-MymXpY1DK8qoR-AKOxd:behwx8n)* status: all files reviewed, 2 unresolved discussions (waiting on @marksvc)

___
*[src/RealtimeServer/common/services/project-data-service.ts, line 54 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1268#-MymVN6I-fPITfL8kjO6:-MymVN6I-fPITfL8kjO7:b-d27ppq) ([raw file](https://github.com/sillsdev/web-xforge/blob/b5c48b40b070de85c8a16cb558c4daf167a57e60/src/RealtimeServer/common/services/project-data-service.ts#L54)):*
> ```XML
>     if (this.listenForUpdates) {
>       // Middleware actions are described at https://github.com/share/sharedb/blob/master/docs/middleware/actions.md
>       server.use('apply', (context, callback) => {
> ```

Nice work figuring out the middleware functions.



_Code quote:_
```XML
      server.use('apply', (context, callback) => {
```
___
*[src/RealtimeServer/scriptureforge/services/note-thread-service.spec.ts, line 115 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1268#-MymWcgR6A7YcDchk1n6:-MymWcgR6A7YcDchk1n7:b9ewif8) ([raw file](https://github.com/sillsdev/web-xforge/blob/b5c48b40b070de85c8a16cb558c4daf167a57e60/src/RealtimeServer/scriptureforge/services/note-thread-service.spec.ts#L115)):*
> ```XML
>     await env.setHaveReadNoteRefs(conn);
> 
>     // Assert that data is set up as expected for testing.
> ```

Let's move these expects out into a function, since they are basically identical to a previous test. Then in both test you can call the function.



_Code quote:_
```XML
    // Assert that data is set up as expected for testing.
```
___
*[src/RealtimeServer/scriptureforge/services/note-thread-service.spec.ts, line 132 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1268#-MymWv7h9xowz5FAa-Dn:-MymWv7h9xowz5FAa-Do:b-s6xkig) ([raw file](https://github.com/sillsdev/web-xforge/blob/b5c48b40b070de85c8a16cb558c4daf167a57e60/src/RealtimeServer/scriptureforge/services/note-thread-service.spec.ts#L132)):*
> ```XML
>     expect(adminProjectUserConfig.noteRefsRead).toContain('noteThread01note01');
>     expect(adminProjectUserConfig.noteRefsRead).toContain('noteThread01note03');
>     expect(adminProjectUserConfig.noteRefsRead).toContain('noteThread02note01');
> ```

This looks like a mistake. It's identical to two lines above.



_Code quote:_
```XML
    expect(adminProjectUserConfig.noteRefsRead).toContain('noteThread02note01');
```


<!-- Sent from Reviewable.io -->

2022-03-22 22:18 UTC, marksvc reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1268)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/RealtimeServer/scriptureforge/services/note-thread-service.spec.ts, line 115 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1268#-MymWcgR6A7YcDchk1n6:-Myne26s2bFJqFqaw9_S:bpct3g6) ([raw file](https://github.com/sillsdev/web-xforge/blob/b5c48b40b070de85c8a16cb558c4daf167a57e60/src/RealtimeServer/scriptureforge/services/note-thread-service.spec.ts#L115)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Let's move these expects out into a function, since they are basically identical to a previous test. Then in both test you can call the function.
</blockquote></details>

Okay. Tho with some disadvantage of not seeing the before-and-after in the test itself.
___
*[src/RealtimeServer/scriptureforge/services/note-thread-service.spec.ts, line 132 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1268#-MymWv7h9xowz5FAa-Dn:-MyngFad77VAi4wi4E7e:b-lt1cm3) ([raw file](https://github.com/sillsdev/web-xforge/blob/b5c48b40b070de85c8a16cb558c4daf167a57e60/src/RealtimeServer/scriptureforge/services/note-thread-service.spec.ts#L132)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This looks like a mistake. It's identical to two lines above.
</blockquote></details>

Close! This one is in a different thread (note the `02`, and is present as part of showing that have-read references in another thread (not being removed) are not removed. 


<!-- Sent from Reviewable.io -->

2022-03-22 22:31 UTC, RaymondLuong3 approved these changes
Thanks for the work. Let :ship: 

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1268#-:-MynkExc33PvAWZyeHdb:bp5uc64)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @marksvc)

___
*[src/RealtimeServer/scriptureforge/services/note-thread-service.spec.ts, line 132 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1268#-MymWv7h9xowz5FAa-Dn:-Mynk4tN8SI6PsPR9E8S:b-q14roy) ([raw file](https://github.com/sillsdev/web-xforge/blob/b5c48b40b070de85c8a16cb558c4daf167a57e60/src/RealtimeServer/scriptureforge/services/note-thread-service.spec.ts#L132)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Close! This one is in a different thread (note the `02`, and is present as part of showing that have-read references in another thread (not being removed) are not removed. 
</blockquote></details>

Ok good. Thanks for clarifying.


<!-- Sent from Reviewable.io -->

2022-03-23 16:40 UTC, closed without merging