SF-1524 Apply relevant attributes when applying remote text changes
sillsdev/web-xforge pull request #1292
Opened 2022-03-30 21:55 UTC by RaymondLuong3

There appears to be a difference in the result of a text editor position getFormat and calling getFormat on a string of text. This results in the remote inserts being applied with insufficient format attributes. This improves on that situation by grabbing all formatting of a character and adding it onto the formatting retrieved from a text editor position (excluding the text-anchoring info that appears to be working correctly).

2022-04-11 03:11 UTC, nigel-wells requested changes
Remove edits are always interesting to deal with - well done getting this figured out.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1292#-:-N-Lac-R3liB3yb1Ey5D:byuqigr)* status: all files reviewed, 3 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts, line 762 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1292#-N-LY43H5n6CNQIvBIxH:-N-LY43H5n6CNQIvBIxI:b-jh76rs) ([raw file](https://github.com/sillsdev/web-xforge/blob/80bb3345dea488d68e98851aeb8e9d3daf2fe4c7/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L762)):*
> ```XML
>     // The format of the insertion point lacks some properties that we have to get from the following editor position
>     const insertionFormat: StringMap = editor.getFormat(editorPosition);
>     const characterFormat: StringMap = editor.getFormat(editorPosition, 1);
> ```

Could grab this from `insertionFormat` - I'm not sure how fast `editor.getFormat()` is but it would save querying it again when you already know what the answer is. I assume this doesn't cause issues at the end of the document?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts, line 765 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1292#-N-LZg_U-5hF8uvG8Yzr:-N-LZg_U-5hF8uvG8Yzs:b-z9ulvf) ([raw file](https://github.com/sillsdev/web-xforge/blob/80bb3345dea488d68e98851aeb8e9d3daf2fe4c7/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L765)):*
> ```XML
>     if (characterFormat['segment'] != null) {
>       for (const key of Object.keys(characterFormat)) {
>         if (key !== 'text-anchor') {
> ```

Is this just because it is a wrapper around a note?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1975 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1292#-N-La3cK8P6d-Mi4eWIZ:-N-La3cK8P6d-Mi4eWI_:bdxo65g) ([raw file](https://github.com/sillsdev/web-xforge/blob/80bb3345dea488d68e98851aeb8e9d3daf2fe4c7/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1975)):*
> ```XML
>     }));
> 
>     it('remote edits next to note on verse applied correctly', fakeAsync(() => {
> ```

Is this testing text added after a note icon or after the note anchor? I assume the anchor (as you are checking for no underline) but I didn't know that until the final checks as it sounded like it was the icon. 

Do we need to check adding text just before a note as well do you think or have we covered that?


<!-- Sent from Reviewable.io -->

2022-04-11 22:10 UTC, RaymondLuong3 reviewed
Thanks. It is a bit tricky, but it is worth the effort.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1292#-:-N-PfLxcDJcAAJPJYW_S:b-hoq298)* status: all files reviewed, 3 unresolved discussions (waiting on @nigel-wells)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts, line 762 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1292#-N-LY43H5n6CNQIvBIxH:-N-PZy3o5wTfAuqm7isk:b-famkay) ([raw file](https://github.com/sillsdev/web-xforge/blob/80bb3345dea488d68e98851aeb8e9d3daf2fe4c7/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L762)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Could grab this from `insertionFormat` - I'm not sure how fast `editor.getFormat()` is but it would save querying it again when you already know what the answer is. I assume this doesn't cause issues at the end of the document?
</blockquote></details>

There are slight differences between the insertion format and the next character format. The insertion format contains specific information about tells us attributes that it inherits from the previous character (styles) but lacks some information such as quill class attributors (i.e. the note-thread-segment class). We have to get that from the following character. I'll leave a comment since this is nuanced behaviour.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts, line 765 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1292#-N-LZg_U-5hF8uvG8Yzr:-N-Pe7h72yHcjj7V7oLm:b-oa1i0l) ([raw file](https://github.com/sillsdev/web-xforge/blob/80bb3345dea488d68e98851aeb8e9d3daf2fe4c7/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L765)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Is this just because it is a wrapper around a note?
</blockquote></details>

It's a wrapper around a note icon and the note's selected text.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1975 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1292#-N-La3cK8P6d-Mi4eWIZ:-N-Peq1tA4mUe-oZfFQ2:b-2ya74f) ([raw file](https://github.com/sillsdev/web-xforge/blob/80bb3345dea488d68e98851aeb8e9d3daf2fe4c7/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1975)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Is this testing text added after a note icon or after the note anchor? I assume the anchor (as you are checking for no underline) but I didn't know that until the final checks as it sounded like it was the icon. 

Do we need to check adding text just before a note as well do you think or have we covered that?
</blockquote></details>

Good thinking. I double checked, and this issues only affects notes that are at the very beginning of the verse. So we do not need to be concerned about text that comes before, since a user cannot type before a note that comes at the beginning of a verse.


<!-- Sent from Reviewable.io -->

2022-04-11 22:13 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1292)* status: all files reviewed, 3 unresolved discussions (waiting on @nigel-wells)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts, line 762 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1292#-N-LY43H5n6CNQIvBIxH:-N-PfgNtEGteWXJBKLqO:b-wdsh73) ([raw file](https://github.com/sillsdev/web-xforge/blob/80bb3345dea488d68e98851aeb8e9d3daf2fe4c7/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L762)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

There are slight differences between the insertion format and the next character format. The insertion format contains specific information about tells us attributes that it inherits from the previous character (styles) but lacks some information such as quill class attributors (i.e. the note-thread-segment class). We have to get that from the following character. I'll leave a comment since this is nuanced behaviour.
</blockquote></details>

I also checked with the end of the document, and it appears that there is always a newline at the end of the editor content (quill does this on purpose to allow line level formatting). So we will always have a character to pick the formatting from.


<!-- Sent from Reviewable.io -->

2022-04-13 22:03 UTC, nigel-wells requested changes
Just one last question

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1292#-:-N-Zwsez1zBUfDEjhWXr:b-4ajpax)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts, line 762 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1292#-N-LY43H5n6CNQIvBIxH:-N-ZvautBFuzeGeCRm5f:b-etf9xd) ([raw file](https://github.com/sillsdev/web-xforge/blob/80bb3345dea488d68e98851aeb8e9d3daf2fe4c7/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L762)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I also checked with the end of the document, and it appears that there is always a newline at the end of the editor content (quill does this on purpose to allow line level formatting). So we will always have a character to pick the formatting from.
</blockquote></details>

Good to know and thanks for the additional comment explaining this
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts, line 765 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1292#-N-LZg_U-5hF8uvG8Yzr:-N-ZvmgA6DibUPt3ZqiV:b4omj4c) ([raw file](https://github.com/sillsdev/web-xforge/blob/80bb3345dea488d68e98851aeb8e9d3daf2fe4c7/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L765)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

It's a wrapper around a note icon and the note's selected text.
</blockquote></details>

I wonder if we should have an array/map somewhere to describe these kind of elements to ignore? I know we have one which strips out elements before submitting them but I can see this is a slightly different list again. Perhaps the other list could be expanded on with more information as to when it is needed or not needed? Just a thought anyway - no need to do now unless you wanted to :)
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1975 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1292#-N-La3cK8P6d-Mi4eWIZ:-N-ZwOHe5_SMu4wDgw8p:b-g139a7) ([raw file](https://github.com/sillsdev/web-xforge/blob/80bb3345dea488d68e98851aeb8e9d3daf2fe4c7/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1975)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Good thinking. I double checked, and this issues only affects notes that are at the very beginning of the verse. So we do not need to be concerned about text that comes before, since a user cannot type before a note that comes at the beginning of a verse.
</blockquote></details>

What happens in offline mode i.e. someone adds text to the start of a version, comes online, and then syncs to get notes? 


<!-- Sent from Reviewable.io -->

2022-04-20 17:41 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1292)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts, line 765 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1292#-N-LZg_U-5hF8uvG8Yzr:-N070YXPAAhmZrXmbGYr:b4k2n21) ([raw file](https://github.com/sillsdev/web-xforge/blob/80bb3345dea488d68e98851aeb8e9d3daf2fe4c7/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L765)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

I wonder if we should have an array/map somewhere to describe these kind of elements to ignore? I know we have one which strips out elements before submitting them but I can see this is a slightly different list again. Perhaps the other list could be expanded on with more information as to when it is needed or not needed? Just a thought anyway - no need to do now unless you wanted to :)
</blockquote></details>

Hmm, that's a good idea. We will keep that in mind as the list of things to ignore expands.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1975 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1292#-N-La3cK8P6d-Mi4eWIZ:-N072iJnAzxhFeh7Ej8X:bv8egat) ([raw file](https://github.com/sillsdev/web-xforge/blob/80bb3345dea488d68e98851aeb8e9d3daf2fe4c7/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1975)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

What happens in offline mode i.e. someone adds text to the start of a version, comes online, and then syncs to get notes? 
</blockquote></details>

That's a good questions. When a user does a sync, the text anchors of all notes get recalculated and put in the place that Paratext thinks it belongs. So in this case, the note is recalculated, and notes on verses will always be placed at the start of the verse.


<!-- Sent from Reviewable.io -->

2022-04-20 21:52 UTC, nigel-wells approved these changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1292)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts, line 1975 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1292#-N-La3cK8P6d-Mi4eWIZ:-N07xYSiB3ALMjbQoVpP:b7vuge6) ([raw file](https://github.com/sillsdev/web-xforge/blob/80bb3345dea488d68e98851aeb8e9d3daf2fe4c7/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L1975)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

That's a good questions. When a user does a sync, the text anchors of all notes get recalculated and put in the place that Paratext thinks it belongs. So in this case, the note is recalculated, and notes on verses will always be placed at the start of the verse.
</blockquote></details>

Ah, yes, PT always recalcs the positions during sync and SF then uses that. 


<!-- Sent from Reviewable.io -->

2022-04-20 21:52 UTC, nigel-wells approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1292#-:-N07xgin1f_EBWXlq7Y3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2022-04-20 22:38 UTC, merged