SF-1526b notes: fetch type, conflictType, acceptedChangeXml
sillsdev/web-xforge pull request #1306
Opened 2022-04-12 22:11 UTC by marksvc

Adds to Note:
- Type
- ConflictType
- AcceptedChangeXml

Adds types:
- NoteType
- NoteConflictType

This change starts storing ConflictType but does not start directly
using it.

ParatextService.cs: Detect and compose incoming Note changes of Type,
ConflictType, and AcceptedChangeXml.
ParatxtSyncRunner.cs: Writing Notes to the SF DB should include the
new properties.

---

**Stack**:
- #1305
- #1304
- #1303
- #1302

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

2022-04-14 21:13 UTC, RaymondLuong3 requested changes
Nice work and testing. Just a few minor comments.

> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1306#-:-N-dv1Mz5IQlc9XL73J9:b-7gs0lg)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @marksvc)

___
*[src/SIL.XForge.Scripture/Models/Note.cs, line 7 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1306#-N-d_mu58w3JmRolZ3pK:-N-d_mu58w3JmRolZ3pL:bwb3m44) ([raw file](https://github.com/sillsdev/web-xforge/blob/8f400e4c726d547e853cc2be73b42008646a176f/src/SIL.XForge.Scripture/Models/Note.cs#L7)):*
> ```Smalltalk
>     {
>         public string ThreadId { get; set; }
>         /// <summary>Type of note, such as "" for a normal note, or "conflict" for a conflict note. May be always present, in Notes XML file.</summary>
> ```

"May be always present" doesn't make a lot of sense.



_Code quote:_
```Smalltalk
May be always present, in Notes XML file.
```
___
*[src/SIL.XForge.Scripture/Models/Note.cs, line 9 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1306#-N-d_wf50vF-Xo_1C49N:-N-d_wf50vF-Xo_1C49O:b2nreh6) ([raw file](https://github.com/sillsdev/web-xforge/blob/8f400e4c726d547e853cc2be73b42008646a176f/src/SIL.XForge.Scripture/Models/Note.cs#L9)):*
> ```Smalltalk
>         /// <summary>Type of note, such as "" for a normal note, or "conflict" for a conflict note. May be always present, in Notes XML file.</summary>
>         public string Type { get; set; }
>         /// <summary>Type of conflict, if a conflict note. For example, "verseText". If it is not a conflict note, this may read "unknownConflictType".  May be always present, in Notes XML file.</summary>
> ```

Same as above.



_Code quote:_
```Smalltalk
May be always present, in Notes XML file.
```
___
*[test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs, line 2730 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1306#-N-dsrmb2vD6XeaNonAY:-N-dsrmc87LNTB_EoWw1:bps9bog) ([raw file](https://github.com/sillsdev/web-xforge/blob/8f400e4c726d547e853cc2be73b42008646a176f/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L2730)):*
> ```Smalltalk
>             /// <summary>
>             /// Helper method for testing changes detected when comparing incoming Paratext Comments to
>             /// existing SF Notes. `modifyComment` and `modifyNoteThread` allow adjustment to the incoming Paratext
> ```

"and its notes" would be more accurate.



_Code quote:_
```Smalltalk
SF note thread (and its note)
```


<!-- Sent from Reviewable.io -->

2022-04-14 21:14 UTC, marksvc commented
@Nateowami I modified the commit title and body. How's this one?

2022-04-14 21:25 UTC, marksvc reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1306)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/Models/Note.cs, line 7 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1306#-N-d_mu58w3JmRolZ3pK:-N-dvMP-5DQugIxOzKim:b-b36pvl) ([raw file](https://github.com/sillsdev/web-xforge/blob/8f400e4c726d547e853cc2be73b42008646a176f/src/SIL.XForge.Scripture/Models/Note.cs#L7)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

"May be always present" doesn't make a lot of sense.
</blockquote></details>

It's true. For a Notes XML file with probably 35 notes, I found that all of them had a Type element, all of them had a ConflictType element, not all of them had a Contents element, and not all of them had an AcceptedChangeXml element. I wanted to include in the Note model an indication as to whether a property will ever be null/unset, but I didn't have the confidence to say Type and ConflictType will always be present in the Notes XML without more scrutiny  (and therefore we might consider that their values are always at least the empty string). 
I could write , "Seems to always be present, in Notes XML file."  
I'll leave it out.
___
*[src/SIL.XForge.Scripture/Models/Note.cs, line 9 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1306#-N-d_wf50vF-Xo_1C49N:-N-dxbUh2jQfK3cKRJlP:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/8f400e4c726d547e853cc2be73b42008646a176f/src/SIL.XForge.Scripture/Models/Note.cs#L9)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.
___
*[test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs, line 2730 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1306#-N-dsrmb2vD6XeaNonAY:-N-dwydS2H6q3lYg126U:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/8f400e4c726d547e853cc2be73b42008646a176f/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L2730)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

"and its notes" would be more accurate.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-14 21:42 UTC, RaymondLuong3 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1306#-:-N-e0roQ8C7LvllBrJet:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @marksvc)



<!-- Sent from Reviewable.io -->

2022-04-19 23:14 UTC, marksvc commented
Hey @RaymondLuong3 , I had to adjust some code to keep the tests passing.

2022-04-19 23:20 UTC, marksvc commented
Oops, more to do.

2022-04-20 17:19 UTC, RaymondLuong3 approved these changes
Fantastic test coverage :D

> Reviewed 3 of 4 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1306#-:-N06z6og6Jscf1K8LSuY:b-xphyua)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @marksvc)



<!-- Sent from Reviewable.io -->

2022-04-20 17:24 UTC, marksvc commented
Thank you :)

2022-04-20 17:24 UTC, merged