SF-1572 Clear presence when switching books
sillsdev/web-xforge pull request #1387
Opened 2022-06-02 18:56 UTC by marksvc

This PR fixes SF-1572 in the first commit. But the change required some further adjustment to the other tests to keep them running. I am including the followup change as a separate commit to make it easier to review the PR. **But both commit should be squashed together when submitted** with commit messages retained (other than any "commit-id" lines).

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1387)

2022-06-02 19:58 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1387)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @marksvc and @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts` line 244 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1387#-N3_yyn7BsCVu_Rt4j6-:-N3_yyn7BsCVu_Rt4j60:bneepbw) ([raw file](https://github.com/sillsdev/web-xforge/blob/6e5119d1ccc210609b77c903130b39c6294ee2cc/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L244)):*
> ```XML
> 
>   dismissPresences(): void {
>     this.localPresence?.submit(null as unknown as PresenceData);
> ```

I know this predates your change, but `null as unknown as PresenceData` should just be `null` or `undefined`.

The reason for the type error is that higher up in the file we do `LocalPresence<PresenceData>` when it should be `LocalPresence<PresenceData | null>` or `LocalPresence<PresenceData | undefined>`.


<!-- Sent from Reviewable.io -->

2022-06-02 20:55 UTC, marksvc commented
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts` line 244 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1387#-N3_yyn7BsCVu_Rt4j6-:-N3aBsW-3TM13KtCpu13:bpl9hnk) ([raw file](https://github.com/sillsdev/web-xforge/blob/6e5119d1ccc210609b77c903130b39c6294ee2cc/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L244)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I know this predates your change, but `null as unknown as PresenceData` should just be `null` or `undefined`.

The reason for the type error is that higher up in the file we do `LocalPresence<PresenceData>` when it should be `LocalPresence<PresenceData | null>` or `LocalPresence<PresenceData | undefined>`.
</blockquote></details>

Hmm, okay. Well, I'd like to try that in a followup change where I can test it separately.


<!-- Sent from Reviewable.io -->

2022-06-02 21:51 UTC, marksvc commented
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts` line 244 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1387#-N3_yyn7BsCVu_Rt4j6-:-N3aOPsCCjp15oxqSjQY:b-ibtl7w) ([raw file](https://github.com/sillsdev/web-xforge/blob/6e5119d1ccc210609b77c903130b39c6294ee2cc/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L244)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

That's totally fine with me, but what do you mean by "test it separately"? It either builds or it doesn't. Types are erased by the compiler, so it doesn't impact how it runs.
</blockquote></details>

That's a good point. I guess, I already did debugging and used multiple browsers while getting this PR to work and don't want to destabilize it :)


<!-- Sent from Reviewable.io -->

2022-06-06 23:37 UTC, Nateowami requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1387)* status: all files reviewed, 4 unresolved discussions (waiting on @marksvc and @Nateowami)

___
*[`-- commits` line 20 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1387#-N3vNFLGD3nwnaVMS2jk):*
I think this is supposed to say `enablePresenceReceive` (no `d`).



_Code quote:_
```
enablePresenceReceived
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts` line 333 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1387#-N3vLYwcAJoRhBA510P6:-N3vLYwcAJoRhBA510P7:bhxk0i5) ([raw file](https://github.com/sillsdev/web-xforge/blob/c202f3fd6e6257811d5d02461eff22c1c7d7ba2e/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L333)):*
> ```XML
>       );
> 
>       expect(Object.keys((env.component as any).viewModel.presence.remotePresences).length)
> ```

Instead of writing `(env.component as any).viewModel` all over the place, how about writing:
``` ts
get viewModel(): ViewModel {
  return (this.component as any).viewModel;
}
```
And then you can just do `env.viewModel` whenever you want to access it.
You might also consider doing:
``` ts
get presentUserIds(): string[] { // are the actually user ids, or is that an inaccurate description?
  return Object.keys(this.viewModel.presence.remotePresences);
}
```
Then you can just do
```
expect(env.presentUserIds.length).withContext('setup: sharedb presence info should start off empty').toEqual(0);
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts` line 2661 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1387#-N3vMWcU-kmSAhOFYowZ:-N3vMWcU-kmSAhOFYow_:b-tjet1v) ([raw file](https://github.com/sillsdev/web-xforge/blob/c202f3fd6e6257811d5d02461eff22c1c7d7ba2e/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L2661)):*
> ```XML
>     const viewModel: TextViewModel = (this.component as any).viewModel;
>     const presenceData: PresenceData = mock<PresenceData>();
>     const remotePresences: Record<string, PresenceData> | undefined = (viewModel as any).presence.remotePresences;
> ```

Why are you declaring here that `remotePresences` might be undefined, but on the next non-comment line asserting that it is defined? Maybe you meant to do:
``` ts
const remotePresences: Record<string, PresenceData> = (viewModel as any).presence.remotePresences!;
```


<!-- Sent from Reviewable.io -->

2022-06-07 18:16 UTC, marksvc reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1387)* status: all files reviewed, 4 unresolved discussions (waiting on @Nateowami)

___
*[`-- commits` line 20 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1387#-N3vNFLGD3nwnaVMS2jk):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I think this is supposed to say `enablePresenceReceive` (no `d`).
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts` line 244 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1387#-N3_yyn7BsCVu_Rt4j6-:-N3zL5toBA-v1e10IuhT:bm1t9vc) ([raw file](https://github.com/sillsdev/web-xforge/blob/6e5119d1ccc210609b77c903130b39c6294ee2cc/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L244)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

That's a good point. I guess, I already did debugging and used multiple browsers while getting this PR to work and don't want to destabilize it :)
</blockquote></details>

I think probably better is to here do
`this.localPresence?.destroy();`
So  I'll plan to test that in followup.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts` line 333 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1387#-N3vLYwcAJoRhBA510P6:-N3zHVmDBghRolteyuA8:b-9uw5ge) ([raw file](https://github.com/sillsdev/web-xforge/blob/c202f3fd6e6257811d5d02461eff22c1c7d7ba2e/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L333)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Instead of writing `(env.component as any).viewModel` all over the place, how about writing:
``` ts
get viewModel(): ViewModel {
  return (this.component as any).viewModel;
}
```
And then you can just do `env.viewModel` whenever you want to access it.
You might also consider doing:
``` ts
get presentUserIds(): string[] { // are the actually user ids, or is that an inaccurate description?
  return Object.keys(this.viewModel.presence.remotePresences);
}
```
Then you can just do
```
expect(env.presentUserIds.length).withContext('setup: sharedb presence info should start off empty').toEqual(0);
```
</blockquote></details>

Thank you. 
I think they are temporary, random ids. 
I think I'll put the line between convenience and exposing the data, at returning the `Record<string,PresenceData>`, rather than its Keys.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts` line 2661 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1387#-N3vMWcU-kmSAhOFYowZ:-N3zK4MsDmaQfeve2D_0:begwpfb) ([raw file](https://github.com/sillsdev/web-xforge/blob/c202f3fd6e6257811d5d02461eff22c1c7d7ba2e/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L2661)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Why are you declaring here that `remotePresences` might be undefined, but on the next non-comment line asserting that it is defined? Maybe you meant to do:
``` ts
const remotePresences: Record<string, PresenceData> = (viewModel as any).presence.remotePresences!;
```
</blockquote></details>

:)
How about this.


<!-- Sent from Reviewable.io -->

2022-06-07 18:30 UTC, Nateowami approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1387#-:-N3zQeAKAe5zdMqLKkD6:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts` line 244 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1387#-N3_yyn7BsCVu_Rt4j6-:-N3zQP6O3eukbCamGY5x:bdcv6l8) ([raw file](https://github.com/sillsdev/web-xforge/blob/6e5119d1ccc210609b77c903130b39c6294ee2cc/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L244)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I think probably better is to here do
`this.localPresence?.destroy();`
So  I'll plan to test that in followup.

</blockquote></details>

Good point.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts` line 333 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1387#-N3vLYwcAJoRhBA510P6:-N3zPO_U0S2tnxgB9xx_:b-k5dta) ([raw file](https://github.com/sillsdev/web-xforge/blob/c202f3fd6e6257811d5d02461eff22c1c7d7ba2e/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L333)):*
> I think I'll put the line between convenience and exposing the data, at returning the `Record<string,PresenceData>`, rather than its Keys. 

Good call. That's always something that has to be balanced.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts` line 2661 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1387#-N3vMWcU-kmSAhOFYowZ:-N3zP80HAs5_6RNR4LlF:bwdtx1i) ([raw file](https://github.com/sillsdev/web-xforge/blob/c202f3fd6e6257811d5d02461eff22c1c7d7ba2e/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L2661)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

:)
How about this.
</blockquote></details>

Looks good. :+1: 


<!-- Sent from Reviewable.io -->

2022-06-07 20:06 UTC, merged