Add scripts to visualize Paratext auth tokens
sillsdev/web-xforge pull request #1388
Opened 2022-06-04 02:10 UTC by Nateowami

This adds two scripts, one for showing the state of a user's access token in Mongo, and the other to show the access token in Auth0.

The package axios is added for sending HTTP requests. I don't know that much about axios, but it's what Auth0 uses in their examples of how to call their API from Node.js.

2022-06-06 22:21 UTC, RaymondLuong3 requested changes
Nice! This may be useful as we track does problems with paratext tokens expiring.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1388#-:-N3v5ya2-2uU0pmnm5xd:b-114g7o)* status: all files reviewed, 3 unresolved discussions (waiting on @Nateowami)

___
*[`scripts/db_tools/auth0-token-info.ts` line 2 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1388#-N3v4gXkEEdZ9cL2P8qK:-N3v4gXkEEdZ9cL2P8qL:b-vp9gqe) ([raw file](https://github.com/sillsdev/web-xforge/blob/3c330bcc86adfb16399274e24373bac062e16016/scripts/db_tools/auth0-token-info.ts#L2)):*
> ```XML
> #!./node_modules/.bin/ts-node
> ```

This would be a good place to describe what this script is doing and how to run it.
___
*[`scripts/db_tools/db-token-info.ts` line 2 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1388#-N3v4xFADNcfOwpflKYk:-N3v4xFADNcfOwpflKYl:bqg9upi) ([raw file](https://github.com/sillsdev/web-xforge/blob/3c330bcc86adfb16399274e24373bac062e16016/scripts/db_tools/db-token-info.ts#L2)):*
> ```XML
> #!./node_modules/.bin/ts-node
> ```

This would be a good place to add a description of what this file does, and how to run it. Include adding a specific email to the email var.
___
*[`scripts/db_tools/show-jwt.ts` line 5 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1388#-N3v5hWv77Jm4pxvNdrG:-N3v5hWv77Jm4pxvNdrH:b-l0qts3) ([raw file](https://github.com/sillsdev/web-xforge/blob/3c330bcc86adfb16399274e24373bac062e16016/scripts/db_tools/show-jwt.ts#L5)):*
> ```XML
>   const payload = JSON.parse(Buffer.from(payloadSection, 'base64').toString());
>   const expiration = new Date(payload.exp * 1000);
>   const currentTimeInSeconds = new Date().getTime() / 1000;
> ```

I would have expected getTime() to produce the time in miliseconds. Should this not be `new Date().getTime() * 1000?`



_Code quote:_
```XML
  const currentTimeInSeconds = new Date().getTime() / 1000;
```


<!-- Sent from Reviewable.io -->

2022-06-06 22:36 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1388)* status: all files reviewed, 3 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

___
*[`scripts/db_tools/show-jwt.ts` line 5 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1388#-N3v5hWv77Jm4pxvNdrG:-N3v7VMCEHzXYXhqJ4co:bcwsesz) ([raw file](https://github.com/sillsdev/web-xforge/blob/3c330bcc86adfb16399274e24373bac062e16016/scripts/db_tools/show-jwt.ts#L5)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I would have expected getTime() to produce the time in miliseconds. Should this not be `new Date().getTime() * 1000?`
</blockquote></details>

It does [return the time in milliseconds](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTime). To get from seconds to milliseconds, we need to divide by 1000. I think maybe you just got confused looking at this and got it backwards?

A couple lines lower we compare it to `payload.exp` which we get from the JWT. Per the JWT spec, `payload.exp` [is in seconds since the Unix Epoch](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.4).


<!-- Sent from Reviewable.io -->

2022-06-06 23:07 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1388)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

___
*[`scripts/db_tools/auth0-token-info.ts` line 2 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1388#-N3v4gXkEEdZ9cL2P8qK:-N3vFpF16k8FtfQ-RWaj:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/3c330bcc86adfb16399274e24373bac062e16016/scripts/db_tools/auth0-token-info.ts#L2)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This would be a good place to describe what this script is doing and how to run it.
</blockquote></details>

Done.
___
*[`scripts/db_tools/db-token-info.ts` line 2 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1388#-N3v4xFADNcfOwpflKYk:-N3vGNNJCUK2g2HbZQsR:bhy9ot6) ([raw file](https://github.com/sillsdev/web-xforge/blob/3c330bcc86adfb16399274e24373bac062e16016/scripts/db_tools/db-token-info.ts#L2)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This would be a good place to add a description of what this file does, and how to run it. Include adding a specific email to the email var.
</blockquote></details>

Will do.


<!-- Sent from Reviewable.io -->

2022-06-07 22:17 UTC, RaymondLuong3 reviewed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1388)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`scripts/db_tools/show-jwt.ts` line 5 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1388#-N3v5hWv77Jm4pxvNdrG:-N4-EWCg9XbVsr1NZUFb:b-lgbi2q) ([raw file](https://github.com/sillsdev/web-xforge/blob/3c330bcc86adfb16399274e24373bac062e16016/scripts/db_tools/show-jwt.ts#L5)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

It does [return the time in milliseconds](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTime). To get from seconds to milliseconds, we need to divide by 1000. I think maybe you just got confused looking at this and got it backwards?

A couple lines lower we compare it to `payload.exp` which we get from the JWT. Per the JWT spec, `payload.exp` [is in seconds since the Unix Epoch](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.4).
</blockquote></details>

That's right. I was getting mixed up...


<!-- Sent from Reviewable.io -->

2022-06-21 01:00 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1388)* status: 4 of 6 files reviewed, all discussions resolved (waiting on @RaymondLuong3)

___
*[`scripts/db_tools/db-token-info.ts` line 2 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1388#-N3v4xFADNcfOwpflKYk:-N52lU2nEMEeGLk3_UZ_:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/3c330bcc86adfb16399274e24373bac062e16016/scripts/db_tools/db-token-info.ts#L2)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Will do.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-27 19:00 UTC, RaymondLuong3 approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1388)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Nateowami)



<!-- Sent from Reviewable.io -->

2022-06-27 19:23 UTC, merged