SF-1555 Prevent admin pages from scrolling away
sillsdev/web-xforge pull request #1420
Opened 2022-07-02 03:48 UTC by Nateowami

- Only part of the menu is now scrollable.
- Community checking no longer wraps in English when the scrollbar appears.
- Some incorrect behavior regarding when dividers are shown in the menu has been fixed (for example, for resources, previously a divider was shown under the list of books).
- I removed a few pixels of what I think was unnecessary padding at the top of the menu.

Before | After
----------|-------
![](https://user-images.githubusercontent.com/6140710/176985302-8b1e01eb-e527-4a9f-8559-89ec922718c0.png) | ![](https://user-images.githubusercontent.com/6140710/176985301-02259001-824f-46fc-9cf1-a6d6a985f871.png)

2022-07-04 16:49 UTC, RaymondLuong3 requested changes
I'll mention that it looks a little odd to have so much white space in navigation menu when setting mdc-drawer-content { justify-content: space-between; }
![image.png](https://files.reviewableusercontent.io/images/reviewable/17931130/ak6LYHx4kzp9dNG52ADANetS/image.png)

> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1420#-:-N695rgT5FpcWJGv5RMq:b-5hvqhj)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html` line 232 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1420#-N693go27NnjKY_SbYrf:-N693go27NnjKY_SbYrg:bfm71hr) ([raw file](https://github.com/sillsdev/web-xforge/blob/236b0b283dbaa12c9c7c78dea8763456e88309db/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html#L232)):*
> ```HTML
>       <mat-nav-list
>         id="admin-pages-menu-list"
>         *ngIf="(canSync$ | async) || (canSeeSettings$ | async) || (canSeeUsers$ | async)"
> ```

this could all be condensed in the ts file into one property that this template can read. It may be cleaner that way.



_Code quote:_
```HTML
        *ngIf="(canSync$ | async) || (canSeeSettings$ | async) || (canSeeUsers$ | async)"
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss` line 223 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1420#-N696NtcADCG5Km8Z5zc:-N696NtcADCG5Km8Z5zd:b-uy1f5n) ([raw file](https://github.com/sillsdev/web-xforge/blob/236b0b283dbaa12c9c7c78dea8763456e88309db/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss#L223)):*
> ```SCSS
> 
> #tools-menu-list,
> #admin-pages-menu-list {
> ```

It doesn't appear that this line affects anything that I can see.



_Code quote:_
```SCSS
#admin-pages-menu-list {
```


<!-- Sent from Reviewable.io -->

2022-07-05 17:16 UTC, Nateowami reviewed
It does look somewhat odd, but I'm not sure it looks more odd than previously, when it could also have a lot of blank space:
![](https://files.reviewableusercontent.io/images/reviewable/6140710/FmTQ30xlo04vJ6cBkXDPDTs9/sidebar.png)

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1420#-:-N6AZuju3WWSAAKHvwT1:bs1c17y)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html` line 232 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1420#-N693go27NnjKY_SbYrf:-N6ELqumCeCmb3nO0kmQ:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/236b0b283dbaa12c9c7c78dea8763456e88309db/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html#L232)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

this could all be condensed in the ts file into one property that this template can read. It may be cleaner that way.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss` line 223 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1420#-N696NtcADCG5Km8Z5zc:-N6AZ5wY-iDibS49kxJX:biztj4) ([raw file](https://github.com/sillsdev/web-xforge/blob/236b0b283dbaa12c9c7c78dea8763456e88309db/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss#L223)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

It doesn't appear that this line affects anything that I can see.
</blockquote></details>

Without it you get this weird look. Note the gap between the divider and the bottom of the scroll element.
![](https://files.reviewableusercontent.io/images/reviewable/6140710/yuPDsJBvrdFc8VEqsNXZmicA/Screenshot%20from%202022-07-04%2019-33-48.png)


<!-- Sent from Reviewable.io -->

2022-07-05 18:18 UTC, RaymondLuong3 requested changes
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1420)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html` line 232 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1420#-N693go27NnjKY_SbYrf:-N6E_0rE0X0yuz4MXQ43:bmfeaba) ([raw file](https://github.com/sillsdev/web-xforge/blob/236b0b283dbaa12c9c7c78dea8763456e88309db/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html#L232)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I wonder if this should have a async pipe? And I do not believe that the "this" is necessary.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss` line 223 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1420#-N696NtcADCG5Km8Z5zc:-N6EWrGz5Z-0zMm5x0uE:b-a9pqfg) ([raw file](https://github.com/sillsdev/web-xforge/blob/236b0b283dbaa12c9c7c78dea8763456e88309db/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss#L223)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Without it you get this weird look. Note the gap between the divider and the bottom of the scroll element.
![](https://files.reviewableusercontent.io/images/reviewable/6140710/yuPDsJBvrdFc8VEqsNXZmicA/Screenshot%20from%202022-07-04%2019-33-48.png)

</blockquote></details>

Ok, I see it now.


<!-- Sent from Reviewable.io -->

2022-07-05 18:36 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1420)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html` line 232 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1420#-N693go27NnjKY_SbYrf:-N6EaEOz9tZSZyFF4q7a:b-yqzk0g) ([raw file](https://github.com/sillsdev/web-xforge/blob/236b0b283dbaa12c9c7c78dea8763456e88309db/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html#L232)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I wonder if this should have a async pipe? And I do not believe that the "this" is necessary.
</blockquote></details>

Oh, good catch. Presumably this would always be true.

I didn't catch it in my manual testing because another mistake I just noticed was masking the incorrect logic. The `mat-divider` should be a direct descendant of `mat-nav-list`, rather than included with the sync list item. In fact, the *only* reason we need to make the `#admin-pages-menu-list` element conditional is because we don't want it to include the `mat-divider` when there are no items below the divider. It just so happens that in every case where a user can see at least one admin page, the user can see the sync page.


<!-- Sent from Reviewable.io -->

2022-07-05 20:00 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1420)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html` line 232 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1420#-N693go27NnjKY_SbYrf:-N6EvLtx8zjUmWpfR9vk:b-d1hx2p) ([raw file](https://github.com/sillsdev/web-xforge/blob/236b0b283dbaa12c9c7c78dea8763456e88309db/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html#L232)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Hmm, I'm surprised that we did not catch this in a test. I see there is a test in `app.component.spec.ts`. Are you aware of why this test didn't catch that? Maybe the observable does emit a value that the *ngIf can read without the async pipe.
</blockquote></details>

@raymondluong3 That's because the tests are concerned only with which menu items are shown, and they were always properly shown when they should be shown. The only way you would catch this is by noticing that the divider was shown when it shouldn't have been shown. But that wasn't actually happening, since the way the divider was previously made conditional was to show it when the sync menu item is shown.

Put another way:
This conditional is not very important. I added it to fix incorrect behavior regarding when the divider is shown. But it turns out that because I forgot to move the divider, the divider was controlled by the old logic as well. They combined to produce (by accident) the correct behavior, even though this condition was always evaluating to true.


<!-- Sent from Reviewable.io -->

2022-07-05 21:22 UTC, RaymondLuong3 approved these changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1420)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html` line 232 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1420#-N693go27NnjKY_SbYrf:-N6FEY-Y-MHzq8pv1Tc0:b-kkq7z1) ([raw file](https://github.com/sillsdev/web-xforge/blob/236b0b283dbaa12c9c7c78dea8763456e88309db/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html#L232)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

@raymondluong3 That's because the tests are concerned only with which menu items are shown, and they were always properly shown when they should be shown. The only way you would catch this is by noticing that the divider was shown when it shouldn't have been shown. But that wasn't actually happening, since the way the divider was previously made conditional was to show it when the sync menu item is shown.

Put another way:
This conditional is not very important. I added it to fix incorrect behavior regarding when the divider is shown. But it turns out that because I forgot to move the divider, the divider was controlled by the old logic as well. They combined to produce (by accident) the correct behavior, even though this condition was always evaluating to true.
</blockquote></details>

Ok, thanks for digging into that.


<!-- Sent from Reviewable.io -->

2022-07-05 21:33 UTC, merged