SF-1462 Correctly define segments after stanza break
sillsdev/web-xforge pull request #1424
Opened 2022-07-06 17:36 UTC by RaymondLuong3

After a stanza break `\b` marker is introduce, our segment refs are reset and they do not include the verse ref which look like "verse_1_15". For example this would be the output of this usfm before and after this change.

USFM
\c 1
\q \v 1 Some text
\b
\q more in same verse

Before
[{ insert: { chapter } }, { insert: { blank } }, { insert { verse } }, { insert: "Some text" }, { insert: { para: { style: "p" } }, { insert: { para: { style: "b" } }, **{ insert: "more in same verse", attributes: { segment: "q_1" } }**, { insert: { para } }

After
[{ insert: { chapter } }, { insert: { blank } }, { insert { verse } }, { insert: "Some text" }, { insert: { para: { style: "p" } }, { insert: { para: { style: "b" } }, **{ insert: "more in same verse", attributes: { segment: "verse_1_1/q_1" } }**, { insert: { para } }

This assigns the correct verse ref to the text segment so that when we go to insert a note icon, it can correctly.

2022-07-06 18:30 UTC, Nateowami reviewed
Nice work. I hope to review this soon.

Do you think the current (wrong) behavior is causing data corruption? If not, are there other ill effects that we need to consider?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1424#-:-N6Jli7F0wvk_fn_19NB:b3vpo2v)* status: 0 of 5 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-07-06 20:05 UTC, RaymondLuong3 reviewed
So far I have not seen data corruption coming out of the previous behaviour. Since this was round-tripping correctly even though it wasn't technically correct, everything was working. I did not see any ill effects in my testing from before this change, to the current change (other than notes not displaying in the correct location)

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1424#-:-N6K5jw57GuxEaRAWVZE:bhcp12h)* status: 0 of 5 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-07-15 15:02 UTC, marksvc requested changes
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1424)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @marksvc and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts` line 182 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1424#-N71MWoZ9H-aDN5g9Xqy:-N71MWoZ9H-aDN5g9Xqz:bnerjg9) ([raw file](https://github.com/sillsdev/web-xforge/blob/573f4a7d84d64a489cd78ed4d211afa838d427c0/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L182)):*
> ```XML
> 
>     const verseSegments: string[] = env.component.getVerseSegments(VerseRef.parse('LUK 1:1'));
>     expect(verseSegments).toEqual(['verse_1_1', 'verse_1_1/q_1', 'verse_1_1/q_2', 'verse_1_1/q_3']);
> ```

I've been confused about why this is 
```
['verse_1_1', 'verse_1_1/q_1', 'verse_1_1/q_2', 'verse_1_1/q_3']
```
instead of
```
['verse_1_1/q_1', 'verse_1_1/q_2', 'verse_1_1/q_3', 'verse_1_1/q_4'])
```
since the getPoetryVerseTextDoc() inserts with ref "verse_1_1/q_4" but not "verse_1_1". Can you shed light on this?



_Code quote:_
```XML
 expect(verseSegments).toEqual(['verse_1_1', 'verse_1_1/q_1', 'verse_1_1/q_2', 'verse_1_1/q_3']);
```
___
*[`test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs` line 2492 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1424#-N6y2fhy6NqL_lJYtqKi:-N6y2fhy6NqL_lJYtqKj:bovucly) ([raw file](https://github.com/sillsdev/web-xforge/blob/573f4a7d84d64a489cd78ed4d211afa838d427c0/test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs#L2492)):*
> ```Smalltalk
>                 .InsertPara("p")
>                 .InsertPara("b")
>                 .InsertBlank("verse_1_2/p_1")
> ```

Yeah. Interesting that we had (and still have, it looks) some segment refs that aren't very specific, like `p_1` a few lines above.
___
*[`test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs` line 2724 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1424#-N6y3TvL41crjITbu3lS:-N6y3TvL41crjITbu3lT:bre8trb) ([raw file](https://github.com/sillsdev/web-xforge/blob/573f4a7d84d64a489cd78ed4d211afa838d427c0/test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs#L2724)):*
> ```Smalltalk
>                 .InsertText("Poetry third line", "verse_1_1/q_2")
>                 .InsertPara("q")
>                 .InsertText("Poetry fourth line.", "verse_1_1/q_3")
> ```

I'm surprised this is 
- verse_1_1
- verse_1_1/q_1
- verse_1_1/q_2
- verse_1_1/q_3
instead of
- verse_1_1/q_1
- verse_1_1/q_2
- verse_1_1/q_3
- verse_1_1/q_4



_Code quote:_
```Smalltalk
                .InsertText("Poetry first line", "verse_1_1")
                .InsertPara("q")
                .InsertText("Poetry second line", "verse_1_1/q_1")
                .InsertPara("q")
                .InsertPara("b")
                .InsertText("Poetry third line", "verse_1_1/q_2")
                .InsertPara("q")
                .InsertText("Poetry fourth line.", "verse_1_1/q_3")
```


<!-- Sent from Reviewable.io -->

2022-07-15 21:34 UTC, marksvc requested changes
> Reviewed 2 of 5 files at r1, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1424)* status: all files reviewed, 3 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts` line 609 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1424#-N6y4olWBL3jqq5H9s71:-N6y4olXEpRWvqrMHQXZ:b-l9r6uf) ([raw file](https://github.com/sillsdev/web-xforge/blob/81a84456eace930b1be34d86055f8e2946ee5252/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L609)):*
> ```XML
>           if (curSegment != null) {
>             // continue with the current segment at the current index
>             curSegment = new SegmentInfo(curSegment.ref, curIndex);
> ```

I tried commenting out the `curSegment = new SegmentInfo` line and found that the tests still passed. Some extra output shows that it is creating a new SegmentInfo with curIndex of 61 instead of the old SegmentInfo's index of 60.
Is this an important nuance that should be asserted by the tests?



_Code quote:_
```XML
 curSegment = new SegmentInfo(curSegment.ref, curIndex);
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts` line 182 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1424#-N71MWoZ9H-aDN5g9Xqy:-N72g2I1-5Kl5ksBJPTU:blwxtxo) ([raw file](https://github.com/sillsdev/web-xforge/blob/81a84456eace930b1be34d86055f8e2946ee5252/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L182)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Ah, that's because I made a mistake, the getPoetryVerseTextDoc() should have 'verse_1_1' and not 'verse_1_1/q_4'
</blockquote></details>

Oh. Hmm, I was even able to write some junk just now into the test-utils segment names, and the test still passed. That's not very comforting.

Hmm, do you think it's okay that the segment names are being re-interpreted/re-labeled instead of used from the data inserted by test-utils?
___
*[`test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs` line 2724 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1424#-N6y3TvL41crjITbu3lS:-N72gtud5QfKE2GQYOga:b-9755fa) ([raw file](https://github.com/sillsdev/web-xforge/blob/81a84456eace930b1be34d86055f8e2946ee5252/test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs#L2724)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

That is correct, the first segment of any verse is 'verse_x_x', and it is only in subsequent segment that 'verse_x_x/q_1' will come into play. At least from my testing and investigation.
</blockquote></details>

Thank you.
___
*[`test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs` line 2511 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1424#-N72hP2tB9XKydwoXEZV:-N72hP2tB9XKydwoXEZW:b-updtvq) ([raw file](https://github.com/sillsdev/web-xforge/blob/57fd3ff77c142cd560ff7249c7e9b99240f4cad2/test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs#L2511)):*
> ```Smalltalk
>                     "Verse text."),
>                 Para("b",
>                     "Text in line break"),
> ```

Is this something that normally shouldn't happen? Or that is normal? It's not clear from the test if this is a weird corner case or what. 



_Code quote:_
```Smalltalk
                Para("b",
                    "Text in line break"),
```


<!-- Sent from Reviewable.io -->

2022-07-15 22:04 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1424)* status: all files reviewed, 3 unresolved discussions (waiting on @marksvc)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts` line 609 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1424#-N6y4olWBL3jqq5H9s71:-N72rlodBvHxJ5F2l-sz:b-f6svkk) ([raw file](https://github.com/sillsdev/web-xforge/blob/81a84456eace930b1be34d86055f8e2946ee5252/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text-view-model.ts#L609)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I tried commenting out the `curSegment = new SegmentInfo` line and found that the tests still passed. Some extra output shows that it is creating a new SegmentInfo with curIndex of 61 instead of the old SegmentInfo's index of 60.
Is this an important nuance that should be asserted by the tests?
</blockquote></details>

Good catch. I'll add a piece to the test to show this is working.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts` line 182 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1424#-N71MWoZ9H-aDN5g9Xqy:-N72s0ac9ysX5XoShJGw:b3x6m75) ([raw file](https://github.com/sillsdev/web-xforge/blob/81a84456eace930b1be34d86055f8e2946ee5252/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L182)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Oh. Hmm, I was even able to write some junk just now into the test-utils segment names, and the test still passed. That's not very comforting.

Hmm, do you think it's okay that the segment names are being re-interpreted/re-labeled instead of used from the data inserted by test-utils?
</blockquote></details>

I think it would be ideal if we could use what is provided by the delta to create our segments rather than reinterpret them. But that could be in a separate issue altogether.
___
*[`test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs` line 2511 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1424#-N72hP2tB9XKydwoXEZV:-N72t0rODDfPvChgMW7c:b-69173o) ([raw file](https://github.com/sillsdev/web-xforge/blob/57fd3ff77c142cd560ff7249c7e9b99240f4cad2/test/SIL.XForge.Scripture.Tests/Services/DeltaUsxMapperTests.cs#L2511)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Is this something that normally shouldn't happen? Or that is normal? It's not clear from the test if this is a weird corner case or what. 
</blockquote></details>

I added a comment that says this is not encouraged but supported.


<!-- Sent from Reviewable.io -->

2022-07-18 19:11 UTC, RaymondLuong3 reviewed
To testers: This will fix the issue with note icons not appearing on verse segments after the \b marker. The note icon may not appear exactly on the correct letter in the word. That will be fixed in SF-1462b.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1424#-:-N7HhpQyAer5xmfalk4v:bst5q8t)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2022-07-20 18:16 UTC, merged