SF-1596 - Enable passwordless login
sillsdev/web-xforge pull request #1428
Opened 2022-07-07 21:17 UTC by nigel-wells

- Pass additional auth config options to auth0 to enable passwordless login
- Use passwordless login by default when using a shared key

This PR is dependent on strings first being merged into the auth0-configs repo and uploaded to auth0.languagetechnology.org

2022-07-20 21:23 UTC, RaymondLuong3 requested changes
I'll note here that the login page does not say Scripture Forge, and instead says Auth0. The testers saw this and another issue will be opened for it.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1428#-:-N7STeR190Mbh_FLnfPk:b2g56zc)* status: all files reviewed, 3 unresolved discussions (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts` line 189 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1428#-N7SUEej6yncLGkPQcHm:-N7SUEej6yncLGkPQcHn:bl6bnjq) ([raw file](https://github.com/sillsdev/web-xforge/blob/b5676991fb0d5f3e10ab34999d237ec1c84836cb/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts#L189)):*
> ```XML
>   }
> 
>   async logIn({ returnUrl, signUp, locale, promptPasswordlessLogin }: LoginParams = { returnUrl: '' }): Promise<void> {
> ```

When do we call `logIn()` without parameters? Is that still appropriate to not include a return url? I assume that means we are returning to the app start.component



_Code quote:_
```XML
 LoginParams = { returnUrl: '' })
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.spec.ts` line 300 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1428#-N7SS8fVCj8CsAhqx7YR:-N7SS8fVCj8CsAhqx7YS:bwkl4s0) ([raw file](https://github.com/sillsdev/web-xforge/blob/b5676991fb0d5f3e10ab34999d237ec1c84836cb/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.spec.ts#L300)):*
> ```XML
>     expect(authOptions).toBeDefined();
>     if (authOptions != null) {
>       expect(authOptions.enablePasswordless).toEqual(true);
> ```

Nathaniel and I had a conversation about instances in tests where we want to assert that something is not null and not undefined. We concluded that expect().toBeTruthy() is adequate to do this.
If we expect authOptions to be defined and not null, we could do
```
expect(authOptions).toBeTruthy();
expect(authOptions.enablePasswordless!).toEqual(true);
```
What do you think of that.



_Code quote:_
```XML
    if (authOptions != null) {
      expect(authOptions.enablePasswordless).toEqual(true);
      expect(authOptions.promptPasswordlessLogin).toEqual(false);
    }
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.spec.ts` line 316 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1428#-N7STZsO025V_aIBmNvU:-N7STZsO025V_aIBmNvV:b2nreh6) ([raw file](https://github.com/sillsdev/web-xforge/blob/b5676991fb0d5f3e10ab34999d237ec1c84836cb/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.spec.ts#L316)):*
> ```XML
>     ).last()[0];
>     expect(authOptions).toBeDefined();
>     if (authOptions != null) {
> ```

Same as above.



_Code quote:_
```XML
 if (authOptions != null) {
```


<!-- Sent from Reviewable.io -->

2022-07-25 02:17 UTC, nigel-wells reviewed
Thanks - this is fixed now.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1428#-:-N7n5oKD6GjAoN-ufXcJ:bwfn43h)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts` line 189 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1428#-N7SUEej6yncLGkPQcHm:-N7n4GZTEjXHhJTKObT8:beq8uds) ([raw file](https://github.com/sillsdev/web-xforge/blob/b5676991fb0d5f3e10ab34999d237ec1c84836cb/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts#L189)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

When do we call `logIn()` without parameters? Is that still appropriate to not include a return url? I assume that means we are returning to the app start.component
</blockquote></details>

It's more so we can create some kind of state to pass along to auth0. We also expect something to be available to check on the callback from auth0. I see one of interfaces said this could be `undefined` so I've removed that to ensure it is always defined. FYI there is a validation check in the callback that will send users to `/projects` if it fails for whatever reason.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.spec.ts` line 300 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1428#-N7SS8fVCj8CsAhqx7YR:-N7n5AWK7pKWNf1qj3bX:bv2w07h) ([raw file](https://github.com/sillsdev/web-xforge/blob/b5676991fb0d5f3e10ab34999d237ec1c84836cb/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.spec.ts#L300)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Nathaniel and I had a conversation about instances in tests where we want to assert that something is not null and not undefined. We concluded that expect().toBeTruthy() is adequate to do this.
If we expect authOptions to be defined and not null, we could do
```
expect(authOptions).toBeTruthy();
expect(authOptions.enablePasswordless!).toEqual(true);
```
What do you think of that.
</blockquote></details>

Yes, makes sense. I suspect these were written this way in the past (I copied and pasted the format for consistency across all tests) to make the IDE happy. If you remove the specific `null` check then the IDE complains about the proceeding statements saying that `authOptions` may actually be `null`. We could add in some `!` to make it happy. What are your thoughts? 
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.spec.ts` line 316 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1428#-N7STZsO025V_aIBmNvU:-N7n5lfjD7Z9fAF6bDk8:bqi7dbg) ([raw file](https://github.com/sillsdev/web-xforge/blob/b5676991fb0d5f3e10ab34999d237ec1c84836cb/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.spec.ts#L316)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

As per previous comment.


<!-- Sent from Reviewable.io -->

2022-07-25 17:58 UTC, RaymondLuong3 approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1428)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts` line 189 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1428#-N7SUEej6yncLGkPQcHm:-N7qURty-qUuiR80Fh2F:b-tiwng7) ([raw file](https://github.com/sillsdev/web-xforge/blob/b5676991fb0d5f3e10ab34999d237ec1c84836cb/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts#L189)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

It's more so we can create some kind of state to pass along to auth0. We also expect something to be available to check on the callback from auth0. I see one of interfaces said this could be `undefined` so I've removed that to ensure it is always defined. FYI there is a validation check in the callback that will send users to `/projects` if it fails for whatever reason.
</blockquote></details>

Ok, that's good to know.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.spec.ts` line 300 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1428#-N7SS8fVCj8CsAhqx7YR:-N7qUrDS7cb8kvRa2NXZ:b-enni0s) ([raw file](https://github.com/sillsdev/web-xforge/blob/b5676991fb0d5f3e10ab34999d237ec1c84836cb/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.spec.ts#L300)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Yes, makes sense. I suspect these were written this way in the past (I copied and pasted the format for consistency across all tests) to make the IDE happy. If you remove the specific `null` check then the IDE complains about the proceeding statements saying that `authOptions` may actually be `null`. We could add in some `!` to make it happy. What are your thoughts? 
</blockquote></details>

Hmm, that's a good thought that this keeps it consistent with the other tests in the spec. I think I am happy to keep it consistent since the benefit is so minor.


<!-- Sent from Reviewable.io -->

2022-08-05 02:41 UTC, Nateowami commented
We'll wait until Twilio is ready before merging this, since once it's on master it's in the queue to go to qa and live.

2022-08-18 19:21 UTC, marksvc commented
This is working great in local testing on master. 
I think we should change the text "sign in" to "log in".

2022-08-30 18:08 UTC, merged