SF-1609 Improve Resource Sync Efficiency
sillsdev/web-xforge pull request #1430
Opened 2022-07-08 23:45 UTC by pmachapman

This pull request contains the following changes:
 * Standardizes resource checking in `ParatextService` and `ParatextSyncRunner`
 * Added a `ResourceConfig` child class of `SFProject` to track resource checksums and revision number
 * `ResourceConfig` data is compared to the data from the Paratext feed to ensure that resource text data is only updated if the resource has changed
 * Added unit tests for new resource manifest and revision checking

2022-07-11 18:09 UTC, RaymondLuong3 requested changes
Nice work! This will streamline our sync with projects that are based on resource! I have some minor suggestions.

> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1430#-:-N6iRnP-375kl4jvT3cj:b-jte6zo)* status: all files reviewed, 9 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 330 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1430#-N6iDqmK9mmHTlzJTxnu:-N6iDqmL87q-wsUz6a4q:bezlt1v) ([raw file](https://github.com/sillsdev/web-xforge/blob/9372597a33b03ee83e46eb43b8be398453950b38/src/SIL.XForge.Scripture/Services/ParatextService.cs#L330)):*
> ```Smalltalk
>         /// Determines whether a the <see cref="TextData"/> for a resource project requires updating.
>         /// </summary>
>         /// <param name="project">The resource project.</param>
> ```

this doesn't sound accurate. It should be the scripture forge project.



_Code quote:_
```Smalltalk
        /// <param name="project">The resource project.</param>
```
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 1138 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1430#-N6iFf-44DMyCcq339Q8:-N6iFf-44DMyCcq339Q9:b-38mig9) ([raw file](https://github.com/sillsdev/web-xforge/blob/9372597a33b03ee83e46eb43b8be398453950b38/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1138)):*
> ```Smalltalk
>         {
>             // We do not back up resources
>             if (paratextId == null || this.IsResource(paratextId))
> ```

Our convention is to not use the "this" keyword in our backend c# code. Here and below.



_Code quote:_
```Smalltalk
        if (paratextId == null || this.IsResource(paratextId))
```
___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 312 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1430#-N6iLiv9DLyiNeGUGFqY:-N6iLiv9DLyiNeGUGFqZ:b76h81i) ([raw file](https://github.com/sillsdev/web-xforge/blob/9372597a33b03ee83e46eb43b8be398453950b38/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L312)):*
> ```Smalltalk
>                 }
> 
>                 bool resourceNeedsUpdating = paratextProject is ParatextResource paratextResource &&
> ```

What do you think about making this even more generic. ParatextService.ResourceDocsNeedUpdating could simply be DocNeedsUpdating, then we can pass in the SFProject and the ParatextProject. And in DocNeedsUpdating, we do the logic that determines if it is resource and if its contents have changed. This way, ParatextSyncRunner does not need to be aware of ParatextResource, well almost... other than when we update the project.resourceConfig.



_Code quote:_
```Smalltalk
                bool resourceNeedsUpdating = paratextProject is ParatextResource paratextResource &&
                                             _paratextService.ResourceDocsNeedUpdating(_projectDoc.Data, paratextResource);
```
___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 313 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1430#-N6iIxbz43J7WCleiKjk:-N6iIxbz43J7WCleiKjl:bne1rgv) ([raw file](https://github.com/sillsdev/web-xforge/blob/9372597a33b03ee83e46eb43b8be398453950b38/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L313)):*
> ```Smalltalk
> 
>                 bool resourceNeedsUpdating = paratextProject is ParatextResource paratextResource &&
>                                              _paratextService.ResourceDocsNeedUpdating(_projectDoc.Data, paratextResource);
> ```

Nit: The indentation on this line does not need to be so far indented.



_Code quote:_
```Smalltalk
                                             _paratextService.ResourceDocsNeedUpdating(_projectDoc.Data, paratextResource);
```
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs` line 2254 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1430#-N6iOzVI8gB-lDLlI-dw:-N6iOzVI8gB-lDLlI-dx:b-sv2pb5) ([raw file](https://github.com/sillsdev/web-xforge/blob/9372597a33b03ee83e46eb43b8be398453950b38/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L2254)):*
> ```Smalltalk
>             var project = new SFProject
>             {
>                 ParatextId = "not_a_resource",
> ```

You could comment that this is not valid because the length is not 16.



_Code quote:_
```Smalltalk
                ParatextId = "not_a_resource",
```
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs` line 2270 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1430#-N6iOYQ-9j_Mczdxzvjm:-N6iOYQ-9j_Mczdxzvjn:b7ju7zf) ([raw file](https://github.com/sillsdev/web-xforge/blob/9372597a33b03ee83e46eb43b8be398453950b38/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L2270)):*
> ```Smalltalk
>             var project = new SFProject
>             {
>                 ParatextId = "a_valid_resource",
> ```

It would be good to leave a comment that this is valid since it is 16 characters long. Even better, Assert.That(env.Service.IsResource(project.ParatextId), Is.True);



_Code quote:_
```Smalltalk
                ParatextId = "a_valid_resource",
```
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs` line 1514 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1430#-N6iPxvlEUTw20SdgDuQ:-N6iPxvlEUTw20SdgDuR:bb7phvt) ([raw file](https://github.com/sillsdev/web-xforge/blob/9372597a33b03ee83e46eb43b8be398453950b38/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L1514)):*
> ```Smalltalk
>             env.SetupPTData(new Book("MAT", 3), new Book("MRK", 1));
> 
>             // Setup the environment so the Paratext service will return the the resource has changed
> ```

typo



_Code quote:_
```Smalltalk
urn the the resource has changed
```
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs` line 1534 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1430#-N6iQ_hF6r9aJPPTfl1h:-N6iQ_hF6r9aJPPTfl1i:b-faxqj0) ([raw file](https://github.com/sillsdev/web-xforge/blob/9372597a33b03ee83e46eb43b8be398453950b38/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L1534)):*
> ```Smalltalk
> 
>         [Test]
>         public async Task SyncAsync_ResourceNotChanged()
> ```

Maybe a better name is SyncAsync_ResourceNeedsUpdate since the resource has changed for the sake of this test, but we are choosing to not update it.



_Code quote:_
```Smalltalk
     public async Task SyncAsync_ResourceNotChanged()
```
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs` line 1539 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1430#-N6iQqn1CaMh3shAhR0I:-N6iQqn1CaMh3shAhR0J:b-nysmer) ([raw file](https://github.com/sillsdev/web-xforge/blob/9372597a33b03ee83e46eb43b8be398453950b38/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L1539)):*
> ```Smalltalk
>             var env = new TestEnvironment();
>             env.SetupSFData(true, true, false, false,
>                 new Book("MAT", 2), new Book("MRK", 2));
> ```

Funny that in order to show that our resource did not get doc updates, we introduce text changes and see if our texts do not get updated.



_Code quote:_
```Smalltalk
            env.SetupSFData(true, true, false, false,
                new Book("MAT", 2), new Book("MRK", 2));
            env.SetupPTData(new Book("MAT", 3), new Book("MRK", 1));
```


<!-- Sent from Reviewable.io -->

2022-07-12 06:23 UTC, pmachapman reviewed
Thanks for your code review and feedback! Please let me know if I have incorrectly understood or implemented any of your changes.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1430#-:-N6kqWXF-19CvAlMCEYX:b-b1sg4p)* status: all files reviewed, 9 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 330 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1430#-N6iDqmK9mmHTlzJTxnu:-N6kk3Jx0YwAk3dV4TWQ:b-ifv4j9) ([raw file](https://github.com/sillsdev/web-xforge/blob/9372597a33b03ee83e46eb43b8be398453950b38/src/SIL.XForge.Scripture/Services/ParatextService.cs#L330)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

this doesn't sound accurate. It should be the scripture forge project.
</blockquote></details>

Yes, it is unclear. I have updated it - please let me know if I have made it clearer or muddier!



_Code quote:_
```Smalltalk
Determines whether a the <see cref="Te
```
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 1138 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1430#-N6iFf-44DMyCcq339Q8:-N6kkHQ18c9fX2WcqyTk:bp3yn6b) ([raw file](https://github.com/sillsdev/web-xforge/blob/9372597a33b03ee83e46eb43b8be398453950b38/src/SIL.XForge.Scripture/Services/ParatextService.cs#L1138)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Our convention is to not use the "this" keyword in our backend c# code. Here and below.
</blockquote></details>

Apologies, old habits die hard. Removed here and below.
___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 312 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1430#-N6iLiv9DLyiNeGUGFqY:-N6kyaIr6l6UZbYBpht_:b-83gnvg) ([raw file](https://github.com/sillsdev/web-xforge/blob/9372597a33b03ee83e46eb43b8be398453950b38/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L312)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

What do you think about making this even more generic. ParatextService.ResourceDocsNeedUpdating could simply be DocNeedsUpdating, then we can pass in the SFProject and the ParatextProject. And in DocNeedsUpdating, we do the logic that determines if it is resource and if its contents have changed. This way, ParatextSyncRunner does not need to be aware of ParatextResource, well almost... other than when we update the project.resourceConfig.
</blockquote></details>

I didn't make this generic, as I wanted it to map to the ParatextData function described in the comments, so that if it has to be updated in future, the update will be straightforward. I also wanted to ensure that the function was not misused by requiring the ParatextResource object to be passed to it - if it is named generically, it might be misused or perhaps morph in future.

That said, if there is a comparable check for Paratext projects that they have been updated, it would be worthwhile to make this function generic. Are you aware of any similar metadata we could track for Paratext projects to see if they have bene updated?
___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 313 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1430#-N6iIxbz43J7WCleiKjk:-N6klTVH8fZrr0rvnXww:b6e4k1i) ([raw file](https://github.com/sillsdev/web-xforge/blob/9372597a33b03ee83e46eb43b8be398453950b38/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L313)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Nit: The indentation on this line does not need to be so far indented.
</blockquote></details>

Yes, it is a bit extreme - I have made it just a tab width. For some reason either VS or Resharper made it this large.
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs` line 2254 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1430#-N6iOzVI8gB-lDLlI-dw:-N6kmgN16EcEzmVXZ3K2:b82o7f) ([raw file](https://github.com/sillsdev/web-xforge/blob/9372597a33b03ee83e46eb43b8be398453950b38/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L2254)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

You could comment that this is not valid because the length is not 16.
</blockquote></details>

Good idea - done. Also added an Assert IsFalse
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs` line 2270 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1430#-N6iOYQ-9j_Mczdxzvjm:-N6kmeY1AqlRtuFiBEeq:b5h40xt) ([raw file](https://github.com/sillsdev/web-xforge/blob/9372597a33b03ee83e46eb43b8be398453950b38/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L2270)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

It would be good to leave a comment that this is valid since it is 16 characters long. Even better, Assert.That(env.Service.IsResource(project.ParatextId), Is.True);
</blockquote></details>

Great idea. Done (and for all the others).
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs` line 1514 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1430#-N6iPxvlEUTw20SdgDuQ:-N6knMUJ4KCf84nHl2DA:bbuyr22) ([raw file](https://github.com/sillsdev/web-xforge/blob/9372597a33b03ee83e46eb43b8be398453950b38/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L1514)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

typo
</blockquote></details>

Good spotting. Fixed.
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs` line 1534 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1430#-N6iQ_hF6r9aJPPTfl1h:-N6kv013BdQ-aTPQaFDp:b-l7cs4c) ([raw file](https://github.com/sillsdev/web-xforge/blob/9372597a33b03ee83e46eb43b8be398453950b38/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L1534)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Maybe a better name is SyncAsync_ResourceNeedsUpdate since the resource has changed for the sake of this test, but we are choosing to not update it.
</blockquote></details>

I have rewritten the test - see below.
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs` line 1539 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1430#-N6iQqn1CaMh3shAhR0I:-N6koMQq4_ZLzvRMbRRL:bk914ll) ([raw file](https://github.com/sillsdev/web-xforge/blob/9372597a33b03ee83e46eb43b8be398453950b38/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L1539)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Funny that in order to show that our resource did not get doc updates, we introduce text changes and see if our texts do not get updated.
</blockquote></details>

I have rewritten the test to be a bit more logical - the PT data is now the same as the SF data, and the test now checks to see if the text is retrieved from Paratext, as this only happens when the SF project is being updated. I have also updated SyncAsync_ResourceChanged() to use the opposite check.


<!-- Sent from Reviewable.io -->

2022-07-12 21:21 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1430)* status: all files reviewed, 2 unresolved discussions (waiting on @pmachapman)

___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs` line 1562 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1430#-N6oHTWj0fzr09xuFQbx:-N6oHTWj0fzr09xuFQby:bb7phvt) ([raw file](https://github.com/sillsdev/web-xforge/blob/d7c1906dcf3a6ad9d5347513a7a69cc88f8ae604/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L1562)):*
> ```Smalltalk
>                 Regex.IsMatch(logEvent.Message, "Starting"), 1);
> 
>             // The book text not is retrieved from Paratext as the resource did not change
> ```

typo



_Code quote:_
```Smalltalk
 text not is retrieved
```


<!-- Sent from Reviewable.io -->

2022-07-13 06:20 UTC, pmachapman reviewed
No problem - done.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1430#-:-N6q8e2F0igeZDoQIxYX:bb1e4ou)* status: all files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs` line 2270 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1430#-N6iOYQ-9j_Mczdxzvjm:-N6q954m5WxeM9jyUUE6:b-qz2kx) ([raw file](https://github.com/sillsdev/web-xforge/blob/9372597a33b03ee83e46eb43b8be398453950b38/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L2270)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Hey, I see now that this is used in many tests. Could we assign this to a readonly field in TestEnvironment.ValidResourceId and then set ParatextId = env.ValidResourceId. I think this is cleaner.
</blockquote></details>

Yes, that is a great idea. I think I was too stuck in the test-trenches to see the resource ids already in the TestEnvironment. I have changed them to env.Resource1Id instead.
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs` line 1562 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1430#-N6oHTWj0fzr09xuFQbx:-N6q8xDX3WpvTs7gIuIl:b-9xd0ar) ([raw file](https://github.com/sillsdev/web-xforge/blob/d7c1906dcf3a6ad9d5347513a7a69cc88f8ae604/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L1562)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

typo
</blockquote></details>

Thank you - how embarrassing :-)


<!-- Sent from Reviewable.io -->

2022-07-13 17:04 UTC, RaymondLuong3 approved these changes
Good work! I approve. The testers will test this and then we can merge it.

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1430#-:-N6sW3Mf4LefgELugwS8:bgssmau)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs` line 2270 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1430#-N6iOYQ-9j_Mczdxzvjm:-N6sVwe1CuixEwJPa_BF:b-2wy9mc) ([raw file](https://github.com/sillsdev/web-xforge/blob/9372597a33b03ee83e46eb43b8be398453950b38/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L2270)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Yes, that is a great idea. I think I was too stuck in the test-trenches to see the resource ids already in the TestEnvironment. I have changed them to env.Resource1Id instead.
</blockquote></details>

Nice. I like this a lot better.


<!-- Sent from Reviewable.io -->

2022-07-15 16:15 UTC, Nateowami commented
I rebased this without conflicts, but the tests are now failing because it doesn't compile. I think I could easily get it to compile, but I don't have confidence the rebase worked things out correctly, so I'm just going to leave it.

2022-07-15 19:42 UTC, pmachapman reviewed
No problem - I have fixed the method call that required updated, and retested locally, and the rebase works great.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1430#-:-N72Lq8ID2B7thjU4TVk:b-tjjga4)* status: 8 of 9 files reviewed, all discussions resolved (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2022-07-15 20:08 UTC, Nateowami approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1430)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)



<!-- Sent from Reviewable.io -->

2022-07-18 14:42 UTC, merged