SF-1653 Update text anchor when multiple edits in a delta
sillsdev/web-xforge pull request #1442
Opened 2022-07-20 19:46 UTC by RaymondLuong3

This change enables the ability to update a text anchor when multiple edit positions exist in a delta. Currently, this only happens when a user edits text via a drag and drop, and then undoes the drag and drop. Previously, this would cause the text anchor to be updated incorrectly because we only handled the first edit (insert or delete) that we saw in the delta.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/1442)

2022-07-25 22:57 UTC, marksvc requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1442)* status: all files reviewed, 11 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts` line 1001 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1442#-N7rZ3Nf1DPpkWzpSr8x:-N7rZ3Nf1DPpkWzpSr8y:b-q5cnxo) ([raw file](https://github.com/sillsdev/web-xforge/blob/357c14fabbf33e2abd799ea41641c2d4193257dd/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L1001)):*
> ```XML
>     delta?: DeltaStatic,
>     segmentsBeforeDelta?: IterableIterator<[string, RangeStatic]>,
>     embedsBeforeDelta?: Readonly<Map<string, number>>
> ```

To avoid any misunderstanding from the ambiguity of "before" meaning in time or position, let's use something like
```
segmentsTemporallyBeforeDelta
embedsTemporallyBeforeDelta
```
I'm not very happy with those suggested names, but I'm not sure what's best to use. 



_Code quote:_
```XML
    segmentsBeforeDelta?: IterableIterator<[string, RangeStatic]>,
    embedsBeforeDelta?: Readonly<Map<string, number>>
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts` line 1017 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1442#-N7rOh8c2TEVzANgHjGS:-N7rOh8c2TEVzANgHjGT:bmzyxu5) ([raw file](https://github.com/sillsdev/web-xforge/blob/357c14fabbf33e2abd799ea41641c2d4193257dd/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L1017)):*
> ```XML
>         // set the current verse and range on the first pass
>         currentVerse = baseVerse;
>         currentVerseRange = range;
> ```

Oh no, won't this be storing the range of a `segment` and so conceivably not of the whole verse? 

Same for a dozen lines later, with `currentVerseRange = range;`



_Code quote:_
```XML
 currentVerseRange = range;
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts` line 1029 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1442#-N7rO9gp0PKVKFDznOxj:-N7rO9gp0PKVKFDznOxk:bh32fn0) ([raw file](https://github.com/sillsdev/web-xforge/blob/357c14fabbf33e2abd799ea41641c2d4193257dd/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L1029)):*
> ```XML
>         verseIsEdited = false;
>       } else {
>         currentVerseRange.length += range.length;
> ```

Oh, didn't we maybe not want to do this on the first iteration of the loop, since a dozen lines above, we do `currentVerseRange = range;`? Maybe if we omit the `currentVerseRange = range;` above, then we can safely do this line here without incrementing currentVerseRange.length more than desired?



_Code quote:_
```XML
      } else {
        currentVerseRange.length += range.length;
      }
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts` line 1034 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1442#-N7rPO0n9NZzAZ_d0As_:-N7rPO0n9NZzAZ_d0Asa:baebauz) ([raw file](https://github.com/sillsdev/web-xforge/blob/357c14fabbf33e2abd799ea41641c2d4193257dd/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L1034)):*
> ```XML
>       const editedPositionsWithinRange: number[] = editPositions.filter(
>         pos => pos >= range.index && pos <= range.index + range.length
>       );
> ```

I know that we have handling sometimes for when an edit occurs at the end of a range, where we include it in that range, and so we  would use `<=` in `pos <= range.index + range.length` rather than the `<` operator. But it occurs to me that by doing this, we potentially will find a position "in" two different segments, if the segments are adjacent. I don't know yet if there will be a problem about it, but it's something I was just thinking.



_Code quote:_
```XML
      const editedPositionsWithinRange: number[] = editPositions.filter(
        pos => pos >= range.index && pos <= range.index + range.length
      );
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts` line 1055 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1442#-N7rTjm_0HTFhsXKLgeB:-N7rTjm_0HTFhsXKLgeC:b7vc0o8) ([raw file](https://github.com/sillsdev/web-xforge/blob/357c14fabbf33e2abd799ea41641c2d4193257dd/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L1055)):*
> ```XML
>   private getEditPositionInDelta(delta: DeltaStatic): number[] {
>     let curIndex = 0;
>     const editPositions: number[] = [];
> ```

How about `s` in `getEditPositionsInDelta`?



_Code quote:_
```XML
getEditPositionInDelta
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts` line 1076 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1442#-N7rUkME3t4HsnHwwEcn:-N7rUkMF0C0YkvNhYExc:b-m14ge1) ([raw file](https://github.com/sillsdev/web-xforge/blob/357c14fabbf33e2abd799ea41641c2d4193257dd/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L1076)):*
> ```XML
>   private getBaseVerse(segmentRef: string): string {
>     const matchArray: RegExpExecArray | null = VERSE_REGEX.exec(segmentRef);
>     return matchArray == null ? segmentRef : matchArray[0];
> ```

What's the thinking  behind returning `segmentRef` if there was no match? 



_Code quote:_
```XML
null ? segmentRef
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 1157 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1442#-N7qomI62-fapDBnT_fc:-N7qomI62-fapDBnT_fd:bmln88f) ([raw file](https://github.com/sillsdev/web-xforge/blob/357c14fabbf33e2abd799ea41641c2d4193257dd/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1157)):*
> ```XML
>     const textDeleteOps: DeltaOperation[] = delta.filter(ops => ops.delete != null);
>     const hasTextEditOp: boolean = textInsertOps.length > 0 || textDeleteOps.length > 0;
>     for (const affected of affectedEmbeds) {
> ```

So there is now an outer loop that runs the inner loop over multiple sets of embeds, that may correspond to different verse ranges. And the `editPosition` will be one within the given range, unlike perhaps `editOpIndex` above.

Are we limiting to within specific ranges for performance, or because it would be incorrect behaviour to process outside of those ranges? It looks like from `getAnchorChanges()` that the verse range is being used to only  consider and apply some insert and delete information when we are in the range. I'm unsure so far if we would be getting to getAnchorChanges() and working when we are _out_ of the range, tho. 



_Code quote:_
```XML
for (const affected of affectedEmbeds) {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 1176 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1442#-N7qnes4EwTs0xudaQMf:-N7qnes4EwTs0xudaQMg:brfxozr) ([raw file](https://github.com/sillsdev/web-xforge/blob/357c14fabbf33e2abd799ea41641c2d4193257dd/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1176)):*
> ```XML
>         );
>         const noteAnchorEndIndex: number = notePos + noteThreadDoc.data.position.length + noteCountInTextAnchor;
>         const isUndoOperation: boolean = reinsertedNoteEmbeds.length > 0;
> ```

Introducing this variable is helpful for communicating the meaning.

Haha, actually, while debugging and doing an undo, I found that `isUndoOperation` was false. I wonder if there is another variable name we could use that communicates but is not at times incorrect. Maybe `isUndoingDeleteNoteEmbed`?



_Code quote:_
```XML
const isUndoOperation: boolean =
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 1191 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1442#-N7r3D0s52J3FcgprdZV:-N7r3D0t1ckT4k3VU7Qg:b-xr9t1y) ([raw file](https://github.com/sillsdev/web-xforge/blob/357c14fabbf33e2abd799ea41641c2d4193257 [...]

2022-07-29 21:06 UTC, marksvc commented
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts` line 1001 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1442#-N7rZ3Nf1DPpkWzpSr8x:-N8AluVsC-fS_qc_WlKo:bdk55ka) ([raw file](https://github.com/sillsdev/web-xforge/blob/357c14fabbf33e2abd799ea41641c2d4193257dd/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L1001)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

To avoid any misunderstanding from the ambiguity of "before" meaning in time or position, let's use something like
```
segmentsTemporallyBeforeDelta
embedsTemporallyBeforeDelta
```
I'm not very happy with those suggested names, but I'm not sure what's best to use. 
</blockquote></details>

Some colleagues liked `preDeltaSegmentCache`.


<!-- Sent from Reviewable.io -->

2022-08-03 20:03 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1442)* status: all files reviewed, 11 unresolved discussions (waiting on @marksvc)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts` line 1001 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1442#-N7rZ3Nf1DPpkWzpSr8x:-N8Z_kEG37XizoWglmtL:bg9dsy) ([raw file](https://github.com/sillsdev/web-xforge/blob/357c14fabbf33e2abd799ea41641c2d4193257dd/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L1001)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Some colleagues liked `preDeltaSegmentCache`.
</blockquote></details>

Good suggestion. I renamed it hear and in other places.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts` line 1017 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1442#-N7rOh8c2TEVzANgHjGS:-N8Zb61DBdczq9BQrMdH:b-xkk72p) ([raw file](https://github.com/sillsdev/web-xforge/blob/357c14fabbf33e2abd799ea41641c2d4193257dd/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L1017)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Oh no, won't this be storing the range of a `segment` and so conceivably not of the whole verse? 

Same for a dozen lines later, with `currentVerseRange = range;`
</blockquote></details>

This will set `currentVerseRange = range` when `currentVerseRange == null` on the very first pass. Then on subsequent passes, the `currentVerseRange` length gets updated. So we only reset `currentVerseRange` when the total verse range has calculated and added to the `embedByEditedVerse` list.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts` line 1029 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1442#-N7rO9gp0PKVKFDznOxj:-N8ZeyiV6MLMcrd6lKX_:b-osm7rp) ([raw file](https://github.com/sillsdev/web-xforge/blob/357c14fabbf33e2abd799ea41641c2d4193257dd/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L1029)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Oh, didn't we maybe not want to do this on the first iteration of the loop, since a dozen lines above, we do `currentVerseRange = range;`? Maybe if we omit the `currentVerseRange = range;` above, then we can safely do this line here without incrementing currentVerseRange.length more than desired?
</blockquote></details>

Good thinking. I've adjusted the logic so that even if this is the first iteration, the length is correct.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts` line 1034 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1442#-N7rPO0n9NZzAZ_d0As_:-N8ZfZDm1YIug8TktIB3:b-fp02rj) ([raw file](https://github.com/sillsdev/web-xforge/blob/357c14fabbf33e2abd799ea41641c2d4193257dd/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L1034)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I know that we have handling sometimes for when an edit occurs at the end of a range, where we include it in that range, and so we  would use `<=` in `pos <= range.index + range.length` rather than the `<` operator. But it occurs to me that by doing this, we potentially will find a position "in" two different segments, if the segments are adjacent. I don't know yet if there will be a problem about it, but it's something I was just thinking.
</blockquote></details>

We are actually ok, since there will always be a length of 1 between segments. So if the edit occurred at position 10 at the end of a segment. The start of the next segment could not be at position 10. Typically, segments are separated by a verse embed or a newline character which have a length of 1.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts` line 1055 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1442#-N7rTjm_0HTFhsXKLgeB:-N8ZgNsFDjnpIDBneoi5:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/357c14fabbf33e2abd799ea41641c2d4193257dd/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L1055)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

How about `s` in `getEditPositionsInDelta`?
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts` line 1076 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1442#-N7rUkME3t4HsnHwwEcn:-N8Zg_0s7dDsIRjpAdj3:be3tdeq) ([raw file](https://github.com/sillsdev/web-xforge/blob/357c14fabbf33e2abd799ea41641c2d4193257dd/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L1076)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

What's the thinking  behind returning `segmentRef` if there was no match? 
</blockquote></details>

Thanks for asking. Originally I did not expect the match to fail. But after working on other issues, I've discovered that paragraph breaks such as section headings do not have an associated verse segment. Paratext allows you to create notes on paragraph headings, and considers the notes on those segments as part of the previous verse. I've adjusted the logic and added a test.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 1157 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1442#-N7qomI62-fapDBnT_fc:-N8ZjRHy-gHVEftDhr24:b-gyd9d6) ([raw file](https://github.com/sillsdev/web-xforge/blob/357c14fabbf33e2abd799ea41641c2d4193257dd/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1157)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

So there is now an outer loop that runs the inner loop over multiple sets of embeds, that may correspond to different verse ranges. And the `editPosition` will be one within the given range, unlike perhaps `editOpIndex` above.

Are we limiting to within specific ranges for performance, or because it would be incorrect behaviour to process outside of those ranges? It looks like from `getAnchorChanges()` that the verse range is being used to only  consider and apply some insert and delete information when we are in the range. I'm unsure so far if we would be getting to getAnchorChanges() and working when we are _out_ of the range, tho. 



</blockquote></details>

We need to know what edits happened in a verse range to decide how to update the text anchor, since the text anchor is relative to the verse. So if edits occurred outside of the verse range, they can be ignored
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 1176 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1442#-N7qnes4EwTs0xudaQMf:-N8Zkeh07qwAeaAwKH5R:boj1qgt) ([raw file](https://github.com/sillsdev/web-xforge/blob/357c14fabbf33e2abd799ea41641c2d4193257dd/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1176)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Introducing this variable is helpful for communicating the meaning.

Haha, actually, while debugging and doing an undo, I found that `isUndoOperation` was false. I wonder if there is another variable name we could use that communicates but is not at times incorrect. Maybe `isUndoingDeleteNoteEmbed`?
</blockquote></details>

Good catch. Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 1292 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1442#-N7r-cbY3BXS3ZjbY8mo:-N8Zkx0ZDeFG5NMOpznT:b-i21bbo) ([raw file](https://github.com/sillsdev/web-xforge/blob/357c14fabbf33e2abd799ea41641c2d4193257dd/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1292)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

This might be better named `editIsInVerseRange` or `isEditInVerseRange`.
</blockq [...]

2022-08-22 20:35 UTC, marksvc approved these changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1442)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts` line 1034 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1442#-N7rPO0n9NZzAZ_d0As_:-NA5Q05z-gVqkpPi4Grp:b-cz7bae) ([raw file](https://github.com/sillsdev/web-xforge/blob/357c14fabbf33e2abd799ea41641c2d4193257dd/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L1034)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

We are actually ok, since there will always be a length of 1 between segments. So if the edit occurred at position 10 at the end of a segment. The start of the next segment could not be at position 10. Typically, segments are separated by a verse embed or a newline character which have a length of 1.
</blockquote></details>

Ok, thank you.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 1295 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1442#-N7r4thZ9davJTSKe9Lg:-NA5iKRFCwMOdVIMT9b2:b-20xq2k) ([raw file](https://github.com/sillsdev/web-xforge/blob/357c14fabbf33e2abd799ea41641c2d4193257dd/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1295)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I'm not sure what you mean by query for the information we want. We need to know the verse range to know which edits in the delta occur in the verse, then we can update note text anchors accordingly. other method arguments do not provide info about verse ranges.
</blockquote></details>

Yeah I don't think I was thinking about this the right way. 


<!-- Sent from Reviewable.io -->

2022-08-24 15:22 UTC, merged