SF-1656 Do not build machine project when target has no source docs
sillsdev/web-xforge pull request #1450
Opened 2022-07-25 20:53 UTC by RaymondLuong3

* detect and create suggestion engine only if conditions met on front end
* notify user when source project does not contain target books
* do not create translation engine if source books not available on back end
* TODO: analyze the editor component

The recent update to Machine 2.5.11 has revealed some existing problems with how we handle building our translation engine using Machine. This corrects how we were using Machine by detecting whether we have texts to generate a translation suggestion engine with. In the event that no source texts are available for any book in our project, we skip over the step of creating a translation suggestion engine.

2022-08-04 20:05 UTC, Nateowami requested changes
> Reviewed 8 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1450)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html` line 3 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1450#-N8eQ72jD4F61IIe4uLc:-N8eQ72jD4F61IIe4uLd:bbvz194) ([raw file](https://github.com/sillsdev/web-xforge/blob/426c365cc86e9bcfb89d366816a736ee4135052b/src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html#L3)):*
> ```HTML
> <ng-container *transloco="let t; read: 'translate_overview'">
>   <div class="title mat-display-1">{{ t("translate_overview") }}</div>
>   <div *ngIf="showCannotTrainEngineMessage" class="translation-suggestions-info">
> ```

Maybe hide the suggestion engine card too, in this case?

Or maybe the suggestion engine card should be shown, but this should be part of the card itself, rather than a separate disjointed message?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts` line 96 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1450#-N8eQVhdEulXFwSlPKpt:-N8eQVhdEulXFwSlPKpu:bme3ami) ([raw file](https://github.com/sillsdev/web-xforge/blob/426c365cc86e9bcfb89d366816a736ee4135052b/src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts#L96)):*
> ```XML
>   get showCannotTrainEngineMessage(): boolean {
>     if (this.projectDoc?.data == null) {
>       return true;
> ```

Won't this result in it being shown wrongly while the page is still loading? It seems like it would be better to not show the message when we don't yet know that this is a problem.


<!-- Sent from Reviewable.io -->

2022-08-04 22:01 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1450)* status: 8 of 10 files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html` line 3 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1450#-N8eQ72jD4F61IIe4uLc:-N8eriz99_Y-uH4zBuSF:b8przi5) ([raw file](https://github.com/sillsdev/web-xforge/blob/426c365cc86e9bcfb89d366816a736ee4135052b/src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.html#L3)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Maybe hide the suggestion engine card too, in this case?

Or maybe the suggestion engine card should be shown, but this should be part of the card itself, rather than a separate disjointed message?
</blockquote></details>

Good thinking. I'll add that onto the engine card.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts` line 96 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1450#-N8eQVhdEulXFwSlPKpt:-N8es4T01mpWBaTamACE:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/426c365cc86e9bcfb89d366816a736ee4135052b/src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.ts#L96)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Won't this result in it being shown wrongly while the page is still loading? It seems like it would be better to not show the message when we don't yet know that this is a problem.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-04 22:42 UTC, Nateowami reviewed
@raymondluong3 I can't get the message to show, and it looks like there's still a front-end test failing.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1450#-:-N8f0Qbe2saswGLz0Xei:beeycmq)* status: 2 of 10 files reviewed, 2 unresolved discussions (waiting on @Nateowami)



<!-- Sent from Reviewable.io -->

2022-08-05 16:32 UTC, RaymondLuong3 reviewed
Whoops, I had left a bang on the template that let me see the message. It should be good now.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1450#-:-N8iqSlK6iKJs3DtnMbZ:b-gtqbw6)* status: 2 of 10 files reviewed, 2 unresolved discussions (waiting on @Nateowami)



<!-- Sent from Reviewable.io -->

2022-08-06 00:18 UTC, Nateowami approved these changes
> Reviewed 2 of 10 files at r1, 5 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1450)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2022-08-10 16:46 UTC, merged