SF-1668 Store the current project id and navigate on login
sillsdev/web-xforge pull request #1468
Opened 2022-08-12 20:04 UTC by RaymondLuong3

* add currentProjectId property on the Site class
* store the project id on the user's site in the data
* use the stored id when no project id exists in local storage
* modify user service currentProjectId to accept a user parameter
* add user service test

2022-08-23 18:22 UTC, Nateowami requested changes
> Reviewed 12 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1468)* status: 12 of 14 files reviewed, 1 unresolved discussion (waiting on @Nateowami and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user.service.ts` line 51 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1468#-NAAvZNYC9gUiXot4vO9:-NAAvZNYC9gUiXot4vOA:b-8qo4fd) ([raw file](https://github.com/sillsdev/web-xforge/blob/0eb8bc515370c60b814fcc3ec4b07a3f8a73f7a9/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user.service.ts#L51)):*
> ```XML
>   async setCurrentProjectId(user?: UserDoc, value?: string): Promise<void> {
>     this.localSettings.set(CURRENT_PROJECT_ID_SETTING, value);
>     await user?.submitJson0Op(update => {
> ```

`user` needs to be non-optional, otherwise this is a no-op when it should clear the setting.


<!-- Sent from Reviewable.io -->

2022-08-23 21:18 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1468)* status: 8 of 14 files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user.service.ts` line 51 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1468#-NAAvZNYC9gUiXot4vO9:-NABZN3X69K03-IxoT0Q:b-ilwfnd) ([raw file](https://github.com/sillsdev/web-xforge/blob/0eb8bc515370c60b814fcc3ec4b07a3f8a73f7a9/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user.service.ts#L51)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

`user` needs to be non-optional, otherwise this is a no-op when it should clear the setting.
</blockquote></details>

Thanks. I've made both non-optional.


<!-- Sent from Reviewable.io -->

2022-08-24 01:58 UTC, Nateowami reviewed
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1468)* status: all files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 418 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1468#-NACSzwQ0Cb7aFWPqbeL:-NACSzwR1a9EdGJ0_bi7:b-12myw) ([raw file](https://github.com/sillsdev/web-xforge/blob/dca5c50a672620d4067d8c210375eff9dffb2fb4/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L418)):*
> ```XML
>         }
>         if (this.currentUserDoc != null) {
>           await this.userService.setCurrentProjectId(this.currentUserDoc, this.selectedProjectDoc.id);
> ```

Is there any reason to think `this.currentUserDoc` might be undefined? If not, then I think it makes more sense to assert that it's not null. While it's generally preferable to avoid non-null assertions, the advantage of an assertion is that if it turns out that you're wrong, you'll eventually run into an error and find out that you were wrong and can address it. In a case like this, if we're wrong it will just silently not behave correctly.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user.service.spec.ts` line 50 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1468#-NACZ8IMCSPYmDlyDiaR:-NACZ8INBlRJty7guCvx:bwwnkc8) ([raw file](https://github.com/sillsdev/web-xforge/blob/dca5c50a672620d4067d8c210375eff9dffb2fb4/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/user.service.spec.ts#L50)):*
> ```XML
>     expect(user.data!.sites['sf'].currentProjectId).toEqual('project01');
>     env.service.setCurrentProjectId(user, 'project02');
>     expect(user.data!.sites['sf'].currentProjectId).toEqual('project02');
> ```

It looks like there's no test to make sure it saves locally as well?


<!-- Sent from Reviewable.io -->

2022-08-24 16:18 UTC, Nateowami reviewed
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1468)* status: all files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2022-08-24 17:05 UTC, Nateowami approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1468#-:-NAFo9O5CsIyg4a8UYB9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2022-08-25 17:51 UTC, merged