Multi-cursor fixes to presence logic
sillsdev/web-xforge pull request #1484
Opened 2022-09-01 04:14 UTC by nigel-wells

- Update presence when text ID changes
- Don't remove presence on blur
- Refactored presence logic from `text-view-model.ts` to `text.component.ts`
- Subscribe to a presence channel and a presence doc
- Display name while actively editing a document
- Added community checking test to ensure presence is disabled

This PR aims to resolve SF-1587, SF-1580, and SF-1611.

The core issue was the app trying to use document presence to also work for a general "viewing the book and chapter" presence as well. ShareDB offers two separate ways to handle this. This PR now subscribes to the TextDoc specific presence as well as a generic channel for who is viewing the same TextDoc.

New features introduced were:
- Showing a users name while they are actively updating the document
- Showing any viewer looking at the TextDoc regardless of their permission or ability to edit the text

2022-09-01 18:58 UTC, Nateowami commented
@nigel-wells Can you confirm that you've read through the acceptance tests for SF-1552 and made sure there isn't a feature you overlooked and may have inadvertently removed? Ira listed about 10 items. Some of them likely are no longer correct after this change. I just want to make sure we're not failing to consider things that Ira may have considered when originally implementing it.

2022-09-01 22:15 UTC, RaymondLuong3 requested changes
> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1484)* status: all files reviewed, 7 unresolved discussions (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-doc.ts` line 34 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1484#-NAuzGsiB9Ydjs3O0sY1:-NAuzGsiB9Ydjs3O0sY2:bzbe37d) ([raw file](https://github.com/sillsdev/web-xforge/blob/d99dd38a02a1ac83cdde5c634e4a46c119fd2a1f/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-doc.ts#L34)):*
> ```XML
>  * and chapter.
>  */
> export class TextDoc extends RealtimeDoc<TextData, TextData, RangeStatic> {
> ```

What is this for?



_Code quote:_
```XML
 RangeStatic>
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts` line 42 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1484#-NAuzicu3OG2VDNvv384:-NAuzicu3OG2VDNvv385:bazjpe9) ([raw file](https://github.com/sillsdev/web-xforge/blob/d99dd38a02a1ac83cdde5c634e4a46c119fd2a1f/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L42)):*
> ```XML
> 
> const EDITORS = new Set<Quill>();
> // When a user is active in the editor a timer starts to mark them as inactive for remote presences
> ```

Was this meant to say inactive?



_Code quote:_
```XML
When a user is active
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts` line 847 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1484#-NAv3zOv0JcMyW6opvs8:-NAv3zOv0JcMyW6opvs9:bjywem2) ([raw file](https://github.com/sillsdev/web-xforge/blob/d99dd38a02a1ac83cdde5c634e4a46c119fd2a1f/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L847)):*
> ```XML
>       if (error) throw error;
>     });
>     this.presenceChannel?.off('receive', this.onPresenceChannelReceive);
> ```

What is the reasoning for the second arg in this call? I would think that this would simply turn off the presence channel listener, but then it takes a second arg?



_Code quote:_
```XML
    this.presenceChannel?.off('receive', this.onPresenceChannelReceive);
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts` line 975 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1484#-NAv3J_l0u-yAvj1ajG5:-NAv3J_l0u-yAvj1ajG6:bjib8ck) ([raw file](https://github.com/sillsdev/web-xforge/blob/d99dd38a02a1ac83cdde5c634e4a46c119fd2a1f/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L975)):*
> ```XML
>       if (active) {
>         if (this.activePresenceSubscription != null) {
>           this.activePresenceSubscription.unsubscribe();
> ```

I like how this is done to set mark a user inactive after a certain time.



_Code quote:_
```XML
      if (active) {
        if (this.activePresenceSubscription != null) {
          this.activePresenceSubscription.unsubscribe();
        }
        this.activePresenceSubscription = timer(PRESENCE_EDITOR_ACTIVE_TIMEOUT)
          .pipe(takeUntil(this.presenceActiveEditor$))
          .subscribe(() => {
            this.submitLocalPresenceChannel(false);
          });
      }
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts` line 401 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1484#-NAv4yWU4MjRymeF-LnY:-NAv4yWU4MjRymeF-LnZ:b-3lm12j) ([raw file](https://github.com/sillsdev/web-xforge/blob/d99dd38a02a1ac83cdde5c634e4a46c119fd2a1f/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L401)):*
> ```XML
>       // After a text update the channel will emit that the user is active
>       let presenceData: PresenceData = presenceChannelSubmit.calls.mostRecent().args[0] as PresenceData;
>       expect(presenceData).toBeDefined();
> ```

This may lead to a silent failure. What if we do `expect(presenceData!.viewer.activeInEditor).toBe(true)`?



_Code quote:_
```XML
      expect(presenceData).toBeDefined();
      if (presenceData != null) {
        expect(presenceData.viewer.activeInEditor).toBe(true);
      }
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts` line 409 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1484#-NAv5IOE-B82gUE5n-Eq:-NAv5IOE-B82gUE5n-Er:b2nreh6) ([raw file](https://github.com/sillsdev/web-xforge/blob/d99dd38a02a1ac83cdde5c634e4a46c119fd2a1f/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L409)):*
> ```XML
>       TestEnvironment.waitForPresenceTimer();
>       presenceData = presenceChannelSubmit.calls.mostRecent().args[0] as PresenceData;
>       expect(presenceData).toBeDefined();
> ```

Same as above.



_Code quote:_
```XML
      expect(presenceData).toBeDefined();
      if (presenceData != null) {
        expect(presenceData.viewer.activeInEditor).toBe(false);
      }
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 638 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1484#-NAv6UdF3U5ieQqnAkNI:-NAv6UdF3U5ieQqnAkNJ:b-cvq5i0) ([raw file](https://github.com/sillsdev/web-xforge/blob/d99dd38a02a1ac83cdde5c634e4a46c119fd2a1f/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L638)):*
> ```XML
>   onPresenceChange(remotePresences?: RemotePresences): void {
>     if (remotePresences != null) {
>       // Both source and target docs can emit a presence so only include one unique user
> ```

This this true? I see that the source doc does not have presence enabled, so I assume source text presence would not be emitted



_Code quote:_
```XML
 Both source and target docs can emit a presence so only include one unique user
```


<!-- Sent from Reviewable.io -->

2022-09-02 03:07 UTC, nigel-wells commented
@Nateowami Thanks for raising. I've read over those acceptance tests and they mostly relate to the multi-viewer in the toolbar which I didn't touch other than adding a comment. If we make those tests known to the testers they can go over them again to make sure I haven't accidently broken them but I don't anticipate there being an issue. There probably should be some more tests around those as it is very minimal at the moment.

2022-09-02 03:29 UTC, nigel-wells reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1484)* status: all files reviewed, 7 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-doc.ts` line 34 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1484#-NAuzGsiB9Ydjs3O0sY1:-NAw9uGN92NfLSBjjz3k:b-seza6j) ([raw file](https://github.com/sillsdev/web-xforge/blob/d99dd38a02a1ac83cdde5c634e4a46c119fd2a1f/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/text-doc.ts#L34)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

What is this for?
</blockquote></details>

Previously this was `PresenceData` but ShareDB only uses `RangeStatic` when sharing presence data when subscribed to the doc presence instead of the channel presence. The data type is actually defined by operation type we use with ShareDB
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts` line 42 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1484#-NAuzicu3OG2VDNvv384:-NAwBXDm5xIpYGc_8ws9:b-ke8aku) ([raw file](https://github.com/sillsdev/web-xforge/blob/d99dd38a02a1ac83cdde5c634e4a46c119fd2a1f/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L42)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Was this meant to say inactive?
</blockquote></details>

In my mind what I wrote is correct but I'm never that great at writing sentences lol If you think it is confusing and you understand it then can you suggest an alternative way of saying the same thing.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts` line 847 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1484#-NAv3zOv0JcMyW6opvs8:-NAwCe9I5lKlAIprF9e2:boblbiy) ([raw file](https://github.com/sillsdev/web-xforge/blob/d99dd38a02a1ac83cdde5c634e4a46c119fd2a1f/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L847)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

What is the reasoning for the second arg in this call? I would think that this would simply turn off the presence channel listener, but then it takes a second arg?
</blockquote></details>

Ira had this setup previously. What will happen is it will emit that the user is no longer on the channel in order to update the users in the toolbar
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts` line 975 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1484#-NAv3J_l0u-yAvj1ajG5:-NAwCxk-8shK4vXMbrCK:b-zcjvte) ([raw file](https://github.com/sillsdev/web-xforge/blob/d99dd38a02a1ac83cdde5c634e4a46c119fd2a1f/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L975)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I like how this is done to set mark a user inactive after a certain time.
</blockquote></details>

Thanks
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts` line 401 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1484#-NAv4yWU4MjRymeF-LnY:-NAwE-Ye7w7X71_9JTxK:b-47oxt3) ([raw file](https://github.com/sillsdev/web-xforge/blob/d99dd38a02a1ac83cdde5c634e4a46c119fd2a1f/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L401)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This may lead to a silent failure. What if we do `expect(presenceData!.viewer.activeInEditor).toBe(true)`?
</blockquote></details>

Thanks for raising - that was leftover from my previous attempt when using `capture` instead of `spyOn`. I've removed it now as it isn't needed.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts` line 409 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1484#-NAv5IOE-B82gUE5n-Eq:-NAwE8C6AEvoI2mb6qqb:b-ido17d) ([raw file](https://github.com/sillsdev/web-xforge/blob/d99dd38a02a1ac83cdde5c634e4a46c119fd2a1f/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.spec.ts#L409)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

As per my other comment
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 638 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1484#-NAv6UdF3U5ieQqnAkNI:-NAwD2oK1XIXJtULraNk:b8lnmr9) ([raw file](https://github.com/sillsdev/web-xforge/blob/d99dd38a02a1ac83cdde5c634e4a46c119fd2a1f/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L638)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This this true? I see that the source doc does not have presence enabled, so I assume source text presence would not be emitted
</blockquote></details>

It isn't enabled but it does generate a presence ID. The source doc is readonly but we need readonly to still have presence for other observer roles. I just added the note here as it confused me for a while as to why there were multiple presence IDs being generated.

...


Actually, this was before I created an input to enable presence which isn't set on the source which means this is no longer an issue! I'll remove the comment.


<!-- Sent from Reviewable.io -->

2022-09-06 18:01 UTC, RaymondLuong3 reviewed
I looked at the three Scenarios that this fixes, and it looks to work for each. Good job.
I found some issues while using this. One is that the avatar does not appear even though I can see the other user's cursor. The second issue I found is that sometimes I can navigate away using my translator user, and my admin still see that the translator is on the same chapter. I am user PT users to test this. 

![image.png](https://files.reviewableusercontent.io/images/reviewable/17931130/3rbW0dZ0vbgvCI2FasZopR-I/image.png)

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1484#-:-NBIx0HP74elMBGidcAF:b8fhqa2)* status: all files reviewed, 4 unresolved discussions (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2022-09-06 18:02 UTC, RaymondLuong3 reviewed
![image.png](https://files.reviewableusercontent.io/images/reviewable/17931130/ZeEw6S5NHPLjulSzmPEcsjA8/image.png)

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1484#-:-NBIxrzpA5hL0TZIn6BD:bqz8nfv)* status: all files reviewed, 4 unresolved discussions (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2022-09-07 10:18 UTC, nigel-wells reviewed
Thanks for testing. Can you confirm if you can only replicate that with PT users? I can't see how it would be unique to them though. Was there any other steps you were doing as it was pretty consistent in my initial tests. I just need some repeatable steps to try and replicate at my end.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1484#-:-NBMS8Ik8y6tN_whgdmC:b1rlzfm)* status: all files reviewed, 4 unresolved discussions (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2022-09-07 17:23 UTC, RaymondLuong3 approved these changes
Hmm, I can't seem to reproduce it. I was trying three users, one was a email/password user. It seems to be working just fine today. Something to keep in mind, but otherwise I approve.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1484#-:-NBNxd7W5jKSQYnSPkja:b-lw41eu)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts` line 42 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1484#-NAuzicu3OG2VDNvv384:-NBNyFHo-FOsJxlo_ylg:b-e4nzd7) ([raw file](https://github.com/sillsdev/web-xforge/blob/d99dd38a02a1ac83cdde5c634e4a46c119fd2a1f/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L42)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

In my mind what I wrote is correct but I'm never that great at writing sentences lol If you think it is confusing and you understand it then can you suggest an alternative way of saying the same thing.
</blockquote></details>

Yes, I get it now. I was just having trouble understanding what was happening until I read through the code.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts` line 847 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1484#-NAv3zOv0JcMyW6opvs8:-NBNySyt4gcVLTzFJaLb:bmomcx8) ([raw file](https://github.com/sillsdev/web-xforge/blob/d99dd38a02a1ac83cdde5c634e4a46c119fd2a1f/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/text.component.ts#L847)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Ira had this setup previously. What will happen is it will emit that the user is no longer on the channel in order to update the users in the toolbar
</blockquote></details>

Ok, it is good to know that it was this way before.


<!-- Sent from Reviewable.io -->

2022-09-12 17:57 UTC, merged