SF-1614 Save the results of each sync to the database
sillsdev/web-xforge pull request #1485
Opened 2022-09-02 20:09 UTC by pmachapman

This pull request saves the results of each sync to Mongo in a new collection, `sync_metrics`. A new document is created in this collection for every sync.

The metrics recorded include:

 * Project that is being synced
 * User doing the sync
 * Time sync was queued
 * Time sync started
 * Time sync finished
 * Status of sync (queued, running, successful, failed, cancelled)
 * On failure, the error message
 * Whether this sync had to wait on another sync
 * Whether a backup is created and/or restored
 * Books in SF added/deleted/updated
 * Books in PT updated
 * Notes in SF added/deleted/updated
 * Notes in PT added/deleted/updated
 * Questions in SF deleted
 * TextDocs in SF added/deleted/updated
 * Resource User access in SF added or removed
 * User access in SF removed from the project
 * A log including:
   * The log messages from `ParatextSyncRunner`
   * The time various stages of the sync occur

**Notes**

 * There is no interface for viewing these metrics in the frontend.
 * The realtime server is not used for storing the metrics, as they are not sent to the frontend.
 * The log does not log messages from `ParatextService`, as this would have convoluted the implementation of `ParatextService` due to its singleton scope.
 * Existing unit tests have been updated to utilize the sync metrics

2022-09-07 19:19 UTC, RaymondLuong3 requested changes
Nice work. This will give us a 

> Reviewed 14 of 15 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1485#-:-NBON9fv1NJCDSgNv5SE:bbmsh9b)* status: all files reviewed, 14 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/Models/SyncMetricInfo.cs` line 22 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1485#-NBO1vJKB9pHw9waN5-Q:-NBO1vJKB9pHw9waN5-R:b-ysmofh) ([raw file](https://github.com/sillsdev/web-xforge/blob/d3d9ca90d9d7014238754b5b21c4188ae7de0478/src/SIL.XForge.Scripture/Models/SyncMetricInfo.cs#L22)):*
> ```Smalltalk
>         public int Updated { get; set; }
> 
>         public static SyncMetricInfo operator +(SyncMetricInfo a, SyncMetricInfo b)
> ```

Neat. I had to look up what this does.



_Code quote:_
```Smalltalk
        public static SyncMetricInfo operator +(SyncMetricInfo a, SyncMetricInfo b)
```
___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 219 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1485#-NBO3V8419uksLVvIVdr:-NBO3V8419uksLVvIVds:b-kacsby) ([raw file](https://github.com/sillsdev/web-xforge/blob/d3d9ca90d9d7014238754b5b21c4188ae7de0478/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L219)):*
> ```Smalltalk
>                     if (isDataInSync && !_paratextService.IsResource(targetParatextId))
>                     {
>                         LogMetric("Updating paratext book");
> ```

This could say Updating paratext notes to be more specific.



_Code quote:_
```Smalltalk
       LogMetric("Updating paratext book");
```
___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 424 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1485#-NBO4E8w4LNInz2rxudQ:-NBO4E8w4LNInz2rxudR:b-nr5vns) ([raw file](https://github.com/sillsdev/web-xforge/blob/d3d9ca90d9d7014238754b5b21c4188ae7de0478/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L424)):*
> ```Smalltalk
>                     string message =
>                         $"Error occurred while executing Paratext sync for project with SF id '{projectSFId}'. {(additionalInformation.Length == 0 ? string.Empty : $"Additional information: {additionalInformation}")}";
>                     _syncMetrics.ErrorDetails = $"{e}{Environment.NewLine}{message}";
> ```

If you log e this way, wouldn't you get the string representation of e which I think would be the hashcode by default?



_Code quote:_
```Smalltalk
           _syncMetrics.ErrorDetails = $"{e}{Environment.NewLine}{message}";
```
___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 501 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1485#-NBO4nr93Aanrh2Qmhjp:-NBO4nr93Aanrh2Qmhjq:b-gphi6h) ([raw file](https://github.com/sillsdev/web-xforge/blob/d3d9ca90d9d7014238754b5b21c4188ae7de0478/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L501)):*
> ```Smalltalk
>             foreach (int bookNum in targetBooks)
>             {
>                 LogMetric($"Updating book {bookNum}");
> ```

It would be more specific to say `updating text info for book {bookNum}`.



_Code quote:_
```Smalltalk
 LogMetric($"Updating book {bookNum}");
```
___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 1212 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1485#-NBO61k62cMlEsk5uzDL:-NBO61k62cMlEsk5uzDM:b-jnw5a) ([raw file](https://github.com/sillsdev/web-xforge/blob/d3d9ca90d9d7014238754b5b21c4188ae7de0478/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L1212)):*
> ```Smalltalk
>                 updateRoles = false;
>             }
>             else if (token.IsCancellationRequested)
> ```

This else if can be merged into the previous one.



_Code quote:_
```Smalltalk
        else if (token.IsCancellationRequested)
```
___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 1403 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1485#-NBO6qXf1tMSLRnjceR5:-NBO6qXf1tMSLRnjceR6:b-y7ryuc) ([raw file](https://github.com/sillsdev/web-xforge/blob/d3d9ca90d9d7014238754b5b21c4188ae7de0478/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L1403)):*
> ```Smalltalk
>             }
> 
>             // If we have an id in the job ids collection, remove the first one
> ```

This comment may need to be updated.



_Code quote:_
```Smalltalk
   // If we have an id in the job ids collection, remove the first one
```
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs` line 52 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1485#-NBOB9QxAFZJhs6Hwuys:-NBOB9Qy5tEOtbutBQ6y:bwmoemn) ([raw file](https://github.com/sillsdev/web-xforge/blob/d3d9ca90d9d7014238754b5b21c4188ae7de0478/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L52)):*
> ```Smalltalk
> 
>             // Check that the failure was logged in the sync metrics
>             var syncMetrics = env.GetSyncMetrics("project01");
> ```

We typically do not use `var` unless the type is explicit in the assignment. Use `SyncMetricsInfo` Here and below.



_Code quote:_
```Smalltalk
      var syncMetrics = env.GetSyncMetrics("project01");
```
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs` line 1143 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1485#-NBONZ2I43KeT0OKAY3k:-NBONZ2I43KeT0OKAY3l:bo3lkdp) ([raw file](https://github.com/sillsdev/web-xforge/blob/d3d9ca90d9d7014238754b5b21c4188ae7de0478/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L1143)):*
> ```Smalltalk
>                         )
>                 )
>                 .Do(_ => throw new ArgumentException());
> ```

Are there any other details that should be logged with an exception is thrown? I know we will log the error details, and I imagine that since the transaction is aborted, only the error details will be saved to the sync metrics. But just wondering if there is anything else that would be helpful to saved like the log messages.



_Code quote:_
```Smalltalk

                .Do(_ => throw new ArgumentException());
```
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs` line 1854 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1485#-NBOH8pU9H8y3OTqgh7o:-NBOH8pU9H8y3OTqgh7p:bogoisz) ([raw file](https://github.com/sillsdev/web-xforge/blob/d3d9ca90d9d7014238754b5b21c4188ae7de0478/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L1854)):*
> ```Smalltalk
>             Assert.That(thread01.Notes.Select(n => n.DataId), Is.EquivalentTo(new[] { "n01", "n03" }));
>             SFProject project = env.GetProject();
>             Assert.That(project.Sync.LastSyncSuccessful, Is.True);
> ```

You could verify the sync metrics here too. A note gets removed from the thread, and a note gets added.



_Code quote:_
```Smalltalk
Assert.That(project.Sync.LastSyncSuccessful, Is.True);
```
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs` line 1868 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1485#-NBOHaRzCpWPOkqsBgmh:-NBOHaRzCpWPOkqsBgmi:bl7cvds) ([raw file](https://github.com/sillsdev/web-xforge/blob/d3d9ca90d9d7014238754b5b21c4188ae7de0478/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L1868)):*
> ```Smalltalk
>             var syncMetrics = env.GetSyncMetrics("project01");
>             Assert.That(syncMetrics.Status, Is.EqualTo(SyncStatus.Successful));
>             Assert.That(syncMetrics.NoteThreads, Is.EqualTo(new SyncMetricInfo(added: 0, deleted: 0, updated: 2)));
> ```

I'm surprised two note threads get updated here? Do you know what is going on? It should be that One note thread is deleted.



_Code quote:_
```Smalltalk
            Assert.That(syncMetrics.NoteThreads, Is.EqualTo(new SyncMetricInfo(added: 0, deleted: 0, updated: 2)));
```
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs` line 1944 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/14 [...]

2022-09-07 19:21 UTC, RaymondLuong3 reviewed
I mean to say that this will help us diagnose things better. I wonder how important it is to save the changes to our texts, notes and users. I imagine that the best thing to do is save the info that led to a failed sync. So this adds lots of info to the syncMetrics collection which may never be looked at when syncs are successful.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1485#-:-NBOO6WACuGmn9uQPN9E:b-ykgz62)* status: all files reviewed, 14 unresolved discussions (waiting on @pmachapman)



<!-- Sent from Reviewable.io -->

2022-09-07 20:07 UTC, Nateowami reviewed
@raymondluong3 We may also want to investigate sync speed. Knowing how much actually changed might help us determine whether a sync was slow because of lots of changes, or for other reasons.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1485#-:-NBOZ0qK4Gmm74cFrSjS:b-4j6r02)* status: all files reviewed, 14 unresolved discussions (waiting on @pmachapman)



<!-- Sent from Reviewable.io -->

2022-09-09 20:12 UTC, pmachapman reviewed
The log saves timestamps to the second, which will help highlight cumulative or large speed issues, when combined with the statistics saved in the metrics

 I am not sure what raw data we would store in the sync_metrics which wouldn't be recorded in ShareDB?
Calculating the number of ShareDB changes between the start and end of a sync could help diagnose issues where for example, too much is being written to the database because of a bug.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1485#-:-NBVmnHb4LhvCP1SUmdz:bhm54rt)* status: 11 of 17 files reviewed, 14 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 219 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1485#-NBO3V8419uksLVvIVdr:-NBVojF9DZ9n9Mdfg1wn:bt2vr0y) ([raw file](https://github.com/sillsdev/web-xforge/blob/d3d9ca90d9d7014238754b5b21c4188ae7de0478/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L219)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This could say Updating paratext notes to be more specific.
</blockquote></details>

Fixed!
___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 424 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1485#-NBO4E8w4LNInz2rxudQ:-NBVpHlCBb31Fo1iHZKw:b-n4a431) ([raw file](https://github.com/sillsdev/web-xforge/blob/d3d9ca90d9d7014238754b5b21c4188ae7de0478/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L424)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

If you log e this way, wouldn't you get the string representation of e which I think would be the hashcode by default?
</blockquote></details>

The string interpolation will call Exception.ToString(), which displays the error details - see https://docs.microsoft.com/en-us/dotnet/api/system.exception.tostring
___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 501 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1485#-NBO4nr93Aanrh2Qmhjp:-NBVpvcn0Bli795iEivA:b5xkbkk) ([raw file](https://github.com/sillsdev/web-xforge/blob/d3d9ca90d9d7014238754b5b21c4188ae7de0478/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L501)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

It would be more specific to say `updating text info for book {bookNum}`.
</blockquote></details>

Changed - thanks!
___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 1212 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1485#-NBO61k62cMlEsk5uzDL:-NBVqhk_7d8wD8glDKto:bffaq7i) ([raw file](https://github.com/sillsdev/web-xforge/blob/d3d9ca90d9d7014238754b5b21c4188ae7de0478/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L1212)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This else if can be merged into the previous one.
</blockquote></details>

Thank you - tidied up!
___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 1403 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1485#-NBO6qXf1tMSLRnjceR5:-NBVrrrDAuCZAqGbfQLp:b-k5ym20) ([raw file](https://github.com/sillsdev/web-xforge/blob/d3d9ca90d9d7014238754b5b21c4188ae7de0478/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L1403)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This comment may need to be updated.
</blockquote></details>

Good spotting - updated.
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs` line 52 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1485#-NBOB9QxAFZJhs6Hwuys:-NBVrwjJ5FD3hOJMWfVi:b-c3fc2g) ([raw file](https://github.com/sillsdev/web-xforge/blob/d3d9ca90d9d7014238754b5b21c4188ae7de0478/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L52)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

We typically do not use `var` unless the type is explicit in the assignment. Use `SyncMetricsInfo` Here and below.
</blockquote></details>

No problem - fixed.
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs` line 1143 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1485#-NBONZ2I43KeT0OKAY3k:-NBYe7lBCVLM1wsRSme5:b-usbf53) ([raw file](https://github.com/sillsdev/web-xforge/blob/d3d9ca90d9d7014238754b5b21c4188ae7de0478/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L1143)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Are there any other details that should be logged with an exception is thrown? I know we will log the error details, and I imagine that since the transaction is aborted, only the error details will be saved to the sync metrics. But just wondering if there is anything else that would be helpful to saved like the log messages.
</blockquote></details>

Not that I am aware of. If there are particular data points that you want to know, we can add them to the sync_metrics log. This has all log messages from `ParatextSyncRunner`, but am not able to capture any from `ParatextService`, unfortunately because `ParatextService` runs in a singleton scope.

Usually in scenarios like this, I will use log as much relevant information as possible, and then when an exception occurs, refer to the log for the background.
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs` line 1854 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1485#-NBOH8pU9H8y3OTqgh7o:-NBVuNOY20FDsqehwWte:bb1e4oh) ([raw file](https://github.com/sillsdev/web-xforge/blob/d3d9ca90d9d7014238754b5b21c4188ae7de0478/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L1854)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

You could verify the sync metrics here too. A note gets removed from the thread, and a note gets added.
</blockquote></details>

No problem - done!
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs` line 1868 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1485#-NBOHaRzCpWPOkqsBgmh:-NBVwmpR4q6thjOAmVlW:b1l6yxw) ([raw file](https://github.com/sillsdev/web-xforge/blob/d3d9ca90d9d7014238754b5b21c4188ae7de0478/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L1868)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I'm surprised two note threads get updated here? Do you know what is going on? It should be that One note thread is deleted.
</blockquote></details>

I misunderstood what was going on (I thought deletion only took place in another place in code). I have corrected the calculations for thread updates/deletions, and added note metrics.
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs` line 1944 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1485#-NBOIJ6G6K2upjMqLHo6:-NBW2bJj98_UBSbxGiX5:bkqejd4) ([raw file](https://github.com/sillsdev/web-xforge/blob/d3d9ca90d9d7014238754b5b21c4188ae7de0478/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L1944)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I'm surprised there is an update, I would have expected no changes to the thread. Did a date get updated?
</blockquote></details>

No, it was my misunderstanding of the note thread code. Fixed.



_Code quote:_
```Smalltalk
SyncAsync_NoteChange_None()
```
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs` line 2089 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1485#-NBOIhx13Q5D-lQpH5-B:-NBWF0Cs7WA4ABx7bBM6:b-v2lhl) ([raw file](https://github.com/sillsdev/web-xforge/blob/d3d9ca90d9d7014238754b5b21c4188ae7de0478/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs# [...]

2022-09-13 18:34 UTC, RaymondLuong3 requested changes
I see that we do not roll back the metrics when we abort a transaction either because the sync had an error, or that a user cancels the sync. That may be the key to help us diagnose what went wrong. We should be able to find the sync ID in the logs, and then refer to the corresponding sync metric document in the collection. Is it quite visible in the logs what id is used for each sync?

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1485#-:-NBs4S204sdHnrCx6iEi:b68rt9u)* status: all files reviewed, 2 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 424 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1485#-NBO4E8w4LNInz2rxudQ:-NBs-AxI0PEzO-WTW7o8:bb7dv6p) ([raw file](https://github.com/sillsdev/web-xforge/blob/d3d9ca90d9d7014238754b5b21c4188ae7de0478/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L424)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

The string interpolation will call Exception.ToString(), which displays the error details - see https://docs.microsoft.com/en-us/dotnet/api/system.exception.tostring
</blockquote></details>

Nice, I'm glad that is the case.
___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 942 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1485#-NBs4HpH3FvGvrfsRgJ0:-NBs4HpH3FvGvrfsRgJ1:bqdf6ji) ([raw file](https://github.com/sillsdev/web-xforge/blob/f49e69cb5665114cec4d5a8e269cd13ef768596f/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L942)):*
> ```Smalltalk
> 
>                     _syncMetrics.Notes += new NoteSyncMetricInfo(
>                         added: change.NotesAdded.Count,
> ```

I didn't realize the += operator works on lists. Nice.



_Code quote:_
```Smalltalk
                    _syncMetrics.Notes += new NoteSyncMetricInfo(
                        added: change.NotesAdded.Count,
                        deleted: change.NotesDeleted.Count,
                        updated: change.NotesUpdated.Count,
                        removed: change.NoteIdsRemoved.Count
```
___
*[`src/SIL.XForge.Scripture/Services/SyncService.cs` line 85 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1485#-NBs6sQ_7t9ZlSR2Fcr-:-NBs6sQ_7t9ZlSR2Fcr0:b-honvlf) ([raw file](https://github.com/sillsdev/web-xforge/blob/f49e69cb5665114cec4d5a8e269cd13ef768596f/src/SIL.XForge.Scripture/Services/SyncService.cs#L85)):*
> ```Smalltalk
>                         {
>                             DateQueued = DateTime.UtcNow,
>                             Id = ObjectId.GenerateNewId().ToString(),
> ```

Is this recorded anywhere in the server logs? It should be visible so we can find the corresponding Sync Metric document.



_Code quote:_
```Smalltalk
                            Id = ObjectId.GenerateNewId().ToString(),
```
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs` line 1143 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1485#-NBONZ2I43KeT0OKAY3k:-NBs0UAa2pcVKcgxHXPt:btpupwb) ([raw file](https://github.com/sillsdev/web-xforge/blob/d3d9ca90d9d7014238754b5b21c4188ae7de0478/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L1143)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Not that I am aware of. If there are particular data points that you want to know, we can add them to the sync_metrics log. This has all log messages from `ParatextSyncRunner`, but am not able to capture any from `ParatextService`, unfortunately because `ParatextService` runs in a singleton scope.

Usually in scenarios like this, I will use log as much relevant information as possible, and then when an exception occurs, refer to the log for the background.
</blockquote></details>

Ok, I'm glad that you took the time to think this through.
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs` line 1868 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1485#-NBOHaRzCpWPOkqsBgmh:-NBs3ePJBUjV_tOItdo8:b-va2fpk) ([raw file](https://github.com/sillsdev/web-xforge/blob/d3d9ca90d9d7014238754b5b21c4188ae7de0478/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L1868)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

I misunderstood what was going on (I thought deletion only took place in another place in code). I have corrected the calculations for thread updates/deletions, and added note metrics.
</blockquote></details>

Ok, yes I see there is a difference between a note being marked 'deleted', and one that is removed altogether.


<!-- Sent from Reviewable.io -->

2022-09-13 19:34 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1485)* status: all files reviewed, 2 unresolved discussions (waiting on @pmachapman and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 942 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1485#-NBs4HpH3FvGvrfsRgJ0:-NBsKFh_4LqLWrNYmrFz:b-b0rm6t) ([raw file](https://github.com/sillsdev/web-xforge/blob/f49e69cb5665114cec4d5a8e269cd13ef768596f/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L942)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I didn't realize the += operator works on lists. Nice.
</blockquote></details>

It's not actually a list. `_syncMetrics.Notes` is a `NoteSyncMetricInfo`, which implements the `+` operator (see the line ` public static NoteSyncMetricInfo operator +(NoteSyncMetricInfo a, NoteSyncMetricInfo b)` line in the `NoteSyncMetricInfo` class).


<!-- Sent from Reviewable.io -->

2022-09-21 00:05 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1485)* status: all files reviewed, 2 unresolved discussions (waiting on @Nateowami and @pmachapman)

___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 942 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1485#-NBs4HpH3FvGvrfsRgJ0:-NCSMDN72LuTM1BmkpL1:bw2rvon) ([raw file](https://github.com/sillsdev/web-xforge/blob/f49e69cb5665114cec4d5a8e269cd13ef768596f/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L942)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

It's not actually a list. `_syncMetrics.Notes` is a `NoteSyncMetricInfo`, which implements the `+` operator (see the line ` public static NoteSyncMetricInfo operator +(NoteSyncMetricInfo a, NoteSyncMetricInfo b)` line in the `NoteSyncMetricInfo` class).
</blockquote></details>

Ah yes, I see, I was mistaken.


<!-- Sent from Reviewable.io -->

2022-09-23 06:51 UTC, pmachapman reviewed
I have added logging of the sync ID to the log when the job is queued, cancelled, or started. I considered adding it to every log message, but it would have been restricted to just ParatextSyncRunner, and would have added a lot of noise to the log.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1485#-:-NCcx5iz9Br_N1ffkUtH:b182web)* status: 15 of 17 files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/Services/SyncService.cs` line 85 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1485#-NBs6sQ_7t9ZlSR2Fcr-:-NCd-SGnDn_GmPnfEfRz:blpn1vw) ([raw file](https://github.com/sillsdev/web-xforge/blob/f49e69cb5665114cec4d5a8e269cd13ef768596f/src/SIL.XForge.Scripture/Services/SyncService.cs#L85)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Is this recorded anywhere in the server logs? It should be visible so we can find the corresponding Sync Metric document.
</blockquote></details>

That is a great idea - I have added information log messages when the sync metrics are created (i.e. when the job is queued), and when the job is started, and when the job is cancelled.


<!-- Sent from Reviewable.io -->

2022-09-26 20:06 UTC, RaymondLuong3 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1485#-:-NCvP9FN8EMk4bJYLdN8:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/Services/SyncService.cs` line 85 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1485#-NBs6sQ_7t9ZlSR2Fcr-:-NCvOue70jUZXFl9ko5f:bhcqwro) ([raw file](https://github.com/sillsdev/web-xforge/blob/f49e69cb5665114cec4d5a8e269cd13ef768596f/src/SIL.XForge.Scripture/Services/SyncService.cs#L85)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

That is a great idea - I have added information log messages when the sync metrics are created (i.e. when the job is queued), and when the job is started, and when the job is cancelled.
</blockquote></details>

I'm glad we both agree!


<!-- Sent from Reviewable.io -->

2022-09-30 21:09 UTC, Nateowami reviewed
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1485)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)



<!-- Sent from Reviewable.io -->

2022-09-30 21:10 UTC, merged