SF-1696 - Fix connecting issue with Auth0 when loading PWA while offline
sillsdev/web-xforge pull request #1491
Opened 2022-09-13 03:27 UTC by nigel-wells

- Implemented a new browser online status which doesn't rely on having an active connection to node
- Don't check for an access token when offline
- Pass getAccessToken() to sharedb for requesting the latest access token

2022-09-26 19:59 UTC, RaymondLuong3 requested changes
I'm glad that this will allow authenticating with Auth0 when we have an internet connection, but it will not if we don't.

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1491#-:-NCvNOYa2DTicW0-vv5g:b738rvi)* status: all files reviewed, 2 unresolved discussions (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts` line 766 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1491#-NCvLZZV0HnTy0KvdrEt:-NCvLZZW0DUAF6Wb6m9v:buga2qi) ([raw file](https://github.com/sillsdev/web-xforge/blob/fa8303f4ec45580d086e6e87410a8667955b64d1/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts#L766)):*
> ```XML
> 
>   setBrowserOffline() {
>     this.browserOnline$.next(false);
> ```

You could create a method called `setBrowserOnlineStatus` and pass in a boolean to set the value if you think that is clear. Here and below.



_Code quote:_
```XML
  setBrowserOffline() {
    this.browserOnline$.next(false);
  }

  setBrowserOnline() {
    this.browserOnline$.next(true);
  }
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/pwa.service.ts` line 42 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1491#-NCvMa-P6RS3HVsYxRSY:-NCvMa-P6RS3HVsYxRSZ:bjzofls) ([raw file](https://github.com/sillsdev/web-xforge/blob/fa8303f4ec45580d086e6e87410a8667955b64d1/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/pwa.service.ts#L42)):*
> ```XML
>       //    the web socket hasn't yet had a chance to connect i.e. (null) when the app first loads
>       this.appOnlineStatus.next(this.windowOnLineStatus.getValue() && this.webSocketStatus.getValue() !== false);
>       // this.appOnlineStatus.next(this.windowOnLineStatus.getValue());
> ```

Looks like this line should be removed.



_Code quote:_
```XML
      // this.appOnlineStatus.next(this.windowOnLineStatus.getValue());
```


<!-- Sent from Reviewable.io -->

2022-09-27 01:26 UTC, nigel-wells reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1491)* status: 5 of 8 files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts` line 766 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1491#-NCvLZZV0HnTy0KvdrEt:-NCwY8VMEzmzZF_tq-co:bbce6gb) ([raw file](https://github.com/sillsdev/web-xforge/blob/fa8303f4ec45580d086e6e87410a8667955b64d1/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts#L766)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

You could create a method called `setBrowserOnlineStatus` and pass in a boolean to set the value if you think that is clear. Here and below.
</blockquote></details>

Thanks - I was in two minds about which way to go for what would be easier to read when writing/reviewing tests. I've changed to your suggestion.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/pwa.service.ts` line 42 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1491#-NCvMa-P6RS3HVsYxRSY:-NCwX4qX18DtKkORK87o:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/fa8303f4ec45580d086e6e87410a8667955b64d1/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/pwa.service.ts#L42)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Looks like this line should be removed.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-27 16:12 UTC, RaymondLuong3 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1491#-:-NCzgFngATUZbZUm_VgX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nigel-wells)



<!-- Sent from Reviewable.io -->

2022-09-28 21:26 UTC, Nateowami approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1491)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nigel-wells)



<!-- Sent from Reviewable.io -->

2022-09-28 21:27 UTC, merged