SF-1577 - Opening nav drawer doesn't close keyboard on mobile
sillsdev/web-xforge pull request #1539
Opened 2022-10-14 01:55 UTC by nigel-wells

- Introduce new package to help calculator on-screen keyboard
- If keyboard has been open then don't try to re-focus the target editor

The package used in this solution has some limitations where the detection event is ~1 second before being emitted - they acknowledge this in their readme and code with reasons behind it. Still, it is better than what we currently experience on mobile devices.

My testing finds that it works well as long as you you don't have your tester hat on where you immediately try to close the keyboard in <1s which of course will trigger it to open again. If you tap it a second time I find that it stays away.

I've tested on a real Android phone but not a iOS phone and BrowserStack is having issues logging in with localhost.

2022-10-19 17:26 UTC, RaymondLuong3 reviewed
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1539)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 1010 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1539#-NElGYwx6FGklBWwIlM6:-NElGYwx6FGklBWwIlM7:b-vws0ml) ([raw file](https://github.com/sillsdev/web-xforge/blob/fa257c091de83865001baadafbaf536c52e08d52/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1010)):*
> ```XML
>         // reset focus, which causes Quill to scroll to the selection
>         this.target!.blur();
>         if (!this.isKeyboardVisible) {
> ```

What is the logic behind how this fixes the problem? Is it because we call `setTextHeight()` anytime a user clicks outside of the editor?



_Code quote:_
```XML
        if (!this.isKeyboardVisible) {
          this.target!.focus();
        }
```


<!-- Sent from Reviewable.io -->

2022-10-25 00:16 UTC, nigel-wells reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1539)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 1010 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1539#-NElGYwx6FGklBWwIlM6:-NFBUN_p-0vzwOvYwZfs:b1nh7gp) ([raw file](https://github.com/sillsdev/web-xforge/blob/fa257c091de83865001baadafbaf536c52e08d52/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1010)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

What is the logic behind how this fixes the problem? Is it because we call `setTextHeight()` anytime a user clicks outside of the editor?
</blockquote></details>

The underlaying scenario is we recalculate the height of the quill editor on the resize event. The resize event occurs when the keyboard starts disappearing and because the focus was initially set we then ensure the cursor is still set after the resize event. This simply checks to see if the keyboard was there (which is only triggered for the mobile keyboards) then don't set the focus again after the resize event.


<!-- Sent from Reviewable.io -->

2022-10-25 16:20 UTC, RaymondLuong3 requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1539)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 1010 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1539#-NElGYwx6FGklBWwIlM6:-NFEwOkc3Sh2Pp3DQXuM:bcd6kbc) ([raw file](https://github.com/sillsdev/web-xforge/blob/fa257c091de83865001baadafbaf536c52e08d52/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1010)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

The underlaying scenario is we recalculate the height of the quill editor on the resize event. The resize event occurs when the keyboard starts disappearing and because the focus was initially set we then ensure the cursor is still set after the resize event. This simply checks to see if the keyboard was there (which is only triggered for the mobile keyboards) then don't set the focus again after the resize event.
</blockquote></details>

Ok, let's add a comment, since it isn't obvious from reading the code.


<!-- Sent from Reviewable.io -->

2022-10-26 00:20 UTC, nigel-wells reviewed
I'm putting this on hold for now as this change might not be needed any more of the change I made for SF-1733 passes testing then that also resolves this issue without the need for an additional package.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1539#-:-NFGe0T_C92LHTikp460:b9ijvv8)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)



<!-- Sent from Reviewable.io -->

2022-11-09 02:31 UTC, nigel-wells commented
Closing this PR as I found a different way to improve what we already have seeming it is our code causing the issue.

2022-11-09 02:31 UTC, closed without merging