tool: import-project: make it more plain if connecting
sillsdev/web-xforge pull request #1581
Opened 2022-11-07 23:51 UTC by marksvc

2022-11-08 00:08 UTC, Nateowami requested changes

2022-11-08 00:08 UTC, Nateowami commented on scripts/db_tools/import-project.ts
> +      console.log(`Origin realtime server connection: ${(originConn as any).state}`);
Can you update the type definition in `src/RealtimeServer/typings/sharedb/lib/client.d.ts` instead of adding a type assertion here?

2022-11-09 22:55 UTC, marksvc reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1581)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`scripts/db_tools/import-project.ts` line 126 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1581#-NGJVPD_F1k--kvbrjGL-r1-126:-NGTaq787xkss0_aLLjY:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/e9ebe27a90f7d554f63e24d6e5e148d304810462/scripts/db_tools/import-project.ts#L126)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Can you update the type definition in `src/RealtimeServer/typings/sharedb/lib/client.d.ts` instead of adding a type assertion here?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-16 19:35 UTC, Nateowami approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1581#-:-NH0w130-MI845lW8ZDr:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @marksvc)

___
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1581#-NH0w4Mu2lGOTFBac8F5):*
I'm pretty sure this comment is no longer correct, so when merging we'll want to make sure to edit it out.


<!-- Sent from Reviewable.io -->

2022-11-16 20:48 UTC, merged

2022-11-16 21:35 UTC, marksvc commented
*[`-- commits` line 4 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1581#-NH0w4Mu2lGOTFBac8F5):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I'm pretty sure this comment is no longer correct, so when merging we'll want to make sure to edit it out.
</blockquote></details>

In client.d.ts, I defined `Connection.state`  as the union of a few strings. I decided on those specific strings based on examining node_modules/sharedb/lib/client/connection.js. But it's ok if that fell out.


<!-- Sent from Reviewable.io -->

2022-11-17 03:06 UTC, Nateowami commented
@marksvc OK. I misread that as meaning that was how you determined that the `as any` type assertion was actually correct. Sorry about that.