Separate SF and PT note thread rights
sillsdev/web-xforge pull request #1635
Opened 2022-12-07 19:33 UTC by RaymondLuong3

This change separates the rights for PT and SF note threads. Note threads continue to use the same service in the realtime server, but permission to view note threads is based on the rights of the user to view pt notes and sf notes.
If desired, another step would be to further separate SF and PT notes into their own collections in mongo, but I do not see the need or benefit of that.

2022-12-07 23:11 UTC, Nateowami requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1635)* status: all files reviewed, 3 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/RealtimeServer/scriptureforge/realtime-server.ts` line 38 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1635#-NIikGlt4vA-UaPZVBLZ:-NIikGlt4vA-UaPZVBL_:b-uh6jtr) ([raw file](https://github.com/sillsdev/web-xforge/blob/180956bfae9e131345f461c31f1652fbf508d85c/src/RealtimeServer/scriptureforge/realtime-server.ts#L38)):*
> ```XML
>         }
>         this.getProject(context.query.projectRef).then(p => {
>           if (
> ```

I think this would be easier to read as:
``` ts
const userId = context.agent.connectSession.userId;
if (p != null && !SF_PROJECT_RIGHTS.hasRight(p, userId, SFProjectDomain.PTNoteThreads, Operation.View)) {
  context.query = { ...context.query, ...{ dataId: { $regex: SF_NOTE_THREAD_PREFIX } } };
}
```
With the user ID defined in a variable, the condition doesn't wrap, and the indention gets less wild.
___
*[`src/RealtimeServer/scriptureforge/models/sf-project-rights.ts` line 78 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1635#-NIihClx4VK8kAcCThpS:-NIihClx4VK8kAcCThpT:b-i1a5qu) ([raw file](https://github.com/sillsdev/web-xforge/blob/180956bfae9e131345f461c31f1652fbf508d85c/src/RealtimeServer/scriptureforge/models/sf-project-rights.ts#L78)):*
> ```XML
> 
>       { projectDomain: SFProjectDomain.PTNoteThreads, operation: Operation.Create },
>       { projectDomain: SFProjectDomain.PTNoteThreads, operation: Operation.Edit },
> ```

I think a PTReviewer can only view text and notes, and create, edit, and delete own notes. I'm not certain, but I think we should find out. Here's a screenshot from PT that leads me to think this:
![](https://files.reviewableusercontent.io/images/reviewable/6140710/-BW4Af03kPns2i2A5YbmYWk1/Screenshot%20from%202022-12-07%2017-32-28.png)

(I could be wrong, so please don't just take my opinion and assume it's correct).
___
*[`src/RealtimeServer/scriptureforge/services/note-thread-service.ts` line 77 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1635#-NIipsmGAhot9X0kOh16:-NIipsmGAhot9X0kOh17:b-ms1lzi) ([raw file](https://github.com/sillsdev/web-xforge/blob/180956bfae9e131345f461c31f1652fbf508d85c/src/RealtimeServer/scriptureforge/services/note-thread-service.ts#L77)):*
> ```XML
>     const project: Project | undefined = await this.server.getProject(doc.projectRef);
>     if (project?.userRoles[session.userId] == null) return false;
>     if (
> ```

I think this conditional could be made a lot more readable:
``` ts
const userId = session.userId; // shorter variable name prevents wrapping on later lines
const canReadPTNotes = RIGHTS.hasRight(project, userId, SFProjectDomain.PTNoteThreads, Operation.View);
const canReadSFNotes = RIGHTS.hasRight(project, userId, SFProjectDomain.SFNoteThreads, Operation.View);
const isSFNote = doc.dataId.startsWith(SF_NOTE_THREAD_PREFIX);
// conditional is much easier to read because the variables tell you what each value represents
return canReadPTNotes || (canReadSFNotes && isSFNote);
```


<!-- Sent from Reviewable.io -->

2022-12-07 23:52 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1635)* status: 2 of 10 files reviewed, 3 unresolved discussions (waiting on @Nateowami)

___
*[`src/RealtimeServer/scriptureforge/realtime-server.ts` line 38 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1635#-NIikGlt4vA-UaPZVBLZ:-NIizTEQ6SNcqinZ7Xez:b2mh6na) ([raw file](https://github.com/sillsdev/web-xforge/blob/180956bfae9e131345f461c31f1652fbf508d85c/src/RealtimeServer/scriptureforge/realtime-server.ts#L38)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I think this would be easier to read as:
``` ts
const userId = context.agent.connectSession.userId;
if (p != null && !SF_PROJECT_RIGHTS.hasRight(p, userId, SFProjectDomain.PTNoteThreads, Operation.View)) {
  context.query = { ...context.query, ...{ dataId: { $regex: SF_NOTE_THREAD_PREFIX } } };
}
```
With the user ID defined in a variable, the condition doesn't wrap, and the indention gets less wild.
</blockquote></details>

Good thinking. I've made some changes to the formatting.
___
*[`src/RealtimeServer/scriptureforge/models/sf-project-rights.ts` line 78 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1635#-NIihClx4VK8kAcCThpS:-NIizaLF19yiPR8IzTMb:b46aslp) ([raw file](https://github.com/sillsdev/web-xforge/blob/180956bfae9e131345f461c31f1652fbf508d85c/src/RealtimeServer/scriptureforge/models/sf-project-rights.ts#L78)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I think a PTReviewer can only view text and notes, and create, edit, and delete own notes. I'm not certain, but I think we should find out. Here's a screenshot from PT that leads me to think this:
![](https://files.reviewableusercontent.io/images/reviewable/6140710/-BW4Af03kPns2i2A5YbmYWk1/Screenshot%20from%202022-12-07%2017-32-28.png)

(I could be wrong, so please don't just take my opinion and assume it's correct).
</blockquote></details>

These rights are on the note thread, so a reviewer should be able to create and edit note thread, even if the thread was not created by the reviewer. I did remove the delete right, I'm not sure we will delete note threads when they get resolved, instead we will likely just mark them as resolved. So the delete right may not be important for admins either. But I left it in for them.
___
*[`src/RealtimeServer/scriptureforge/services/note-thread-service.ts` line 77 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1635#-NIipsmGAhot9X0kOh16:-NIj-FHm3TVs_2Rg2GMZ:beej048) ([raw file](https://github.com/sillsdev/web-xforge/blob/180956bfae9e131345f461c31f1652fbf508d85c/src/RealtimeServer/scriptureforge/services/note-thread-service.ts#L77)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I think this conditional could be made a lot more readable:
``` ts
const userId = session.userId; // shorter variable name prevents wrapping on later lines
const canReadPTNotes = RIGHTS.hasRight(project, userId, SFProjectDomain.PTNoteThreads, Operation.View);
const canReadSFNotes = RIGHTS.hasRight(project, userId, SFProjectDomain.SFNoteThreads, Operation.View);
const isSFNote = doc.dataId.startsWith(SF_NOTE_THREAD_PREFIX);
// conditional is much easier to read because the variables tell you what each value represents
return canReadPTNotes || (canReadSFNotes && isSFNote);
```
</blockquote></details>

Nice suggestion. done.


<!-- Sent from Reviewable.io -->

2022-12-08 05:43 UTC, Nateowami requested changes
Nice work. Just a couple comments.

> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1635#-:-NIkFgT54x2u6MpqP52F:b-2m5sxg)* status: all files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/RealtimeServer/scriptureforge/realtime-server.ts` line 44 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1635#-NIkED7KCwDhzbcvJSb6:-NIkED7KCwDhzbcvJSb7:b-9drsmw) ([raw file](https://github.com/sillsdev/web-xforge/blob/b92e22ddc4513d0a3eb107977a21c376718345ec/src/RealtimeServer/scriptureforge/realtime-server.ts#L44)):*
> ```XML
>             SF_PROJECT_RIGHTS.hasRight(p, userId, SFProjectDomain.SFNoteThreads, Operation.View)
>           ) {
>             context.query = { ...context.query, ...{ publishedToSF: true } };
> ```

I think this can be simplified to:
``` ts
context.query = { ...context.query, publishedToSF: true }
```
___
*[`src/RealtimeServer/scriptureforge/models/sf-project-rights.ts` line 78 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1635#-NIihClx4VK8kAcCThpS:-NIkEbAp-kyt_QMehnS6:baq367d) ([raw file](https://github.com/sillsdev/web-xforge/blob/180956bfae9e131345f461c31f1652fbf508d85c/src/RealtimeServer/scriptureforge/models/sf-project-rights.ts#L78)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

These rights are on the note thread, so a reviewer should be able to create and edit note thread, even if the thread was not created by the reviewer. I did remove the delete right, I'm not sure we will delete note threads when they get resolved, instead we will likely just mark them as resolved. So the delete right may not be important for admins either. But I left it in for them.
</blockquote></details>

I think the issue here is that the domains aren't fully set up. If you look at the permissions for the questions, you'll see that only admins have the `questions.edit` permission, despite the fact that community checkers can add answers (which edits a question).


<!-- Sent from Reviewable.io -->

2022-12-08 05:48 UTC, Nateowami requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1635)* status: all files reviewed, 2 unresolved discussions (waiting on @nigel-wells and @RaymondLuong3)

___
*[`src/RealtimeServer/scriptureforge/models/sf-project-rights.ts` line 78 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1635#-NIihClx4VK8kAcCThpS:-NIkG5_U7Cnyi2b0Bnrp:b-ew6vnd) ([raw file](https://github.com/sillsdev/web-xforge/blob/180956bfae9e131345f461c31f1652fbf508d85c/src/RealtimeServer/scriptureforge/models/sf-project-rights.ts#L78)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I think the issue here is that the domains aren't fully set up. If you look at the permissions for the questions, you'll see that only admins have the `questions.edit` permission, despite the fact that community checkers can add answers (which edits a question).
</blockquote></details>

Just to elaborate on what I was saying a bit:
When a reviewer adds a note to a note thread, the note thread object is being edited. So if you just look at it from the perspective of "which models can the user modify", then yes, the user is editing the note thread. But our permissions system is more granular than the model level and specifies which parts of an object can be edited by a given user. I'm not very familiar with how it works, but @nigel-wells has done some work related to this recently and may be able to provide insight.


<!-- Sent from Reviewable.io -->

2022-12-11 22:12 UTC, nigel-wells reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1635)* status: all files reviewed, 2 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

___
*[`src/RealtimeServer/scriptureforge/models/sf-project-rights.ts` line 78 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1635#-NIihClx4VK8kAcCThpS:-NJ25Gwm0H4a5aWGncue:bdp3fcd) ([raw file](https://github.com/sillsdev/web-xforge/blob/180956bfae9e131345f461c31f1652fbf508d85c/src/RealtimeServer/scriptureforge/models/sf-project-rights.ts#L78)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Just to elaborate on what I was saying a bit:
When a reviewer adds a note to a note thread, the note thread object is being edited. So if you just look at it from the perspective of "which models can the user modify", then yes, the user is editing the note thread. But our permissions system is more granular than the model level and specifies which parts of an object can be edited by a given user. I'm not very familiar with how it works, but @nigel-wells has done some work related to this recently and may be able to provide insight.
</blockquote></details>

Each collection can have a corresponding service which is used to define an array of object path templates to help the permissions system understand the different parts of the collection. The project domain is setup here to define which permissions are relevant to the collection. A request is then made to read, update, delete, etc. and the rights are checked against what has been defined in the object path templates.

All of this can be overwritten (and are in some cases) per collection as these are just protected methods.

Looking at `setupDomains()` in `note-thread-services.ts` it looks like a permission is needed for `PTNoteThreads` to create the actual note thread and then anyone with access to `Notes` can do actions on the `note_threads.notes` part of the object. This means the `SFNoteThreads` are redundant in the sense of enforcing permissions in the realtime server but can obviously be checked from the frontend. If you created an additional `SFProjectDomain.SFNotes` then you could use that to enforce the permissions in the realtime server. The existing `SFProjectDomain.Notes` can be used for PT permissions. This is essentially giving two sets of permissions to do exactly the same thing. You can overwrite the `allowRead` (which it looks like you've done) to check the user wanting to access/change the object has the business logic permission to that specific object which I think you did by changing the ID of the note thread? The middleware you wrote the other day can be updated to return the relevant note threads based on permission as well.


<!-- Sent from Reviewable.io -->

2023-01-04 18:20 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1635)* status: 7 of 12 files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[`src/RealtimeServer/scriptureforge/realtime-server.ts` line 44 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1635#-NIkED7KCwDhzbcvJSb6:-NKy-iNuDKXbeIe2iMaJ:bo5nztk) ([raw file](https://github.com/sillsdev/web-xforge/blob/b92e22ddc4513d0a3eb107977a21c376718345ec/src/RealtimeServer/scriptureforge/realtime-server.ts#L44)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I think this can be simplified to:
``` ts
context.query = { ...context.query, publishedToSF: true }
```
</blockquote></details>

Nice. Done.
___
*[`src/RealtimeServer/scriptureforge/models/sf-project-rights.ts` line 78 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1635#-NIihClx4VK8kAcCThpS:-NKxylCe55KaRDGfGz3I:bsntdih) ([raw file](https://github.com/sillsdev/web-xforge/blob/180956bfae9e131345f461c31f1652fbf508d85c/src/RealtimeServer/scriptureforge/models/sf-project-rights.ts#L78)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Each collection can have a corresponding service which is used to define an array of object path templates to help the permissions system understand the different parts of the collection. The project domain is setup here to define which permissions are relevant to the collection. A request is then made to read, update, delete, etc. and the rights are checked against what has been defined in the object path templates.

All of this can be overwritten (and are in some cases) per collection as these are just protected methods.

Looking at `setupDomains()` in `note-thread-services.ts` it looks like a permission is needed for `PTNoteThreads` to create the actual note thread and then anyone with access to `Notes` can do actions on the `note_threads.notes` part of the object. This means the `SFNoteThreads` are redundant in the sense of enforcing permissions in the realtime server but can obviously be checked from the frontend. If you created an additional `SFProjectDomain.SFNotes` then you could use that to enforce the permissions in the realtime server. The existing `SFProjectDomain.Notes` can be used for PT permissions. This is essentially giving two sets of permissions to do exactly the same thing. You can overwrite the `allowRead` (which it looks like you've done) to check the user wanting to access/change the object has the business logic permission to that specific object which I think you did by changing the ID of the note thread? The middleware you wrote the other day can be updated to return the relevant note threads based on permission as well.
</blockquote></details>

Thanks for the insight! I was happily surprised to learn that we, in fact, do not need to be concerned about SFNotes and PTNotes. When we specify that a note thread is a PT note thread, a reviewer will not be able to read or insert notes to that note thread because ShareDBAccess requires that the user has read permission on the PT note thread. That's a nice trick :)

I have added some logic to find the applicable domains for a NoteThreadDoc. For SF note threads, the `SFProjectDomain.PTNoteThread` will be removed from the applicable domains and `SFProjectDomain.SFNoteThread` will be used as the domain for the thread. This has the advantage of not needing to overwrite any of the access methods like `allowRead`.  This should be tested since it does affect other services that implement the ProjectDataService class.

Let me know what you think.


<!-- Sent from Reviewable.io -->

2023-01-10 00:54 UTC, nigel-wells requested changes
Looking pretty good now - feels like we're landing in the right spot with all of this which is great. Just a few comments below for clarification.

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1635#-:-NLO9lx8-RIAzrYHEHR_:b5w1ho4)* status: all files reviewed, 6 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

___
*[`src/RealtimeServer/scriptureforge/models/note-thread.ts` line 66 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1635#-NLO93IqAktq29xmIxoU:-NLO93IqAktq29xmIxoV:b-6zflx4) ([raw file](https://github.com/sillsdev/web-xforge/blob/ba78f556afc60138cb3455eeac95e65e3e006392/src/RealtimeServer/scriptureforge/models/note-thread.ts#L66)):*
> ```XML
>   status: NoteStatus;
>   tagIcon: string;
>   publishedToSF?: boolean;
> ```

I agree that it will make it easier to run checks against a specific property. I'm not 100% on calling it "published". I would have thought "create" but I see you had then and changed your mind? Published to me says this note thread has been published on SF and others (PT) aren't which seems confusing. "Created On" seems right - what made you change it?
___
*[`src/RealtimeServer/scriptureforge/models/sf-project-rights.ts` line 78 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1635#-NIihClx4VK8kAcCThpS:-NLO9bISEg6tTbgJO0G3:b-1lmv8t) ([raw file](https://github.com/sillsdev/web-xforge/blob/180956bfae9e131345f461c31f1652fbf508d85c/src/RealtimeServer/scriptureforge/models/sf-project-rights.ts#L78)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Thanks for the insight! I was happily surprised to learn that we, in fact, do not need to be concerned about SFNotes and PTNotes. When we specify that a note thread is a PT note thread, a reviewer will not be able to read or insert notes to that note thread because ShareDBAccess requires that the user has read permission on the PT note thread. That's a nice trick :)

I have added some logic to find the applicable domains for a NoteThreadDoc. For SF note threads, the `SFProjectDomain.PTNoteThread` will be removed from the applicable domains and `SFProjectDomain.SFNoteThread` will be used as the domain for the thread. This has the advantage of not needing to overwrite any of the access methods like `allowRead`.  This should be tested since it does affect other services that implement the ProjectDataService class.

Let me know what you think.
</blockquote></details>

That's a nice way to do it, make the entity data available so you can check it and make a decision off that - I like it.
___
*[`src/RealtimeServer/scriptureforge/services/note-thread-service.spec.ts` line 135 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1635#-NLO5bMP7CrZZIrPRIzZ:-NLO5bMP7CrZZIrPRIz_:bygxixo) ([raw file](https://github.com/sillsdev/web-xforge/blob/ba78f556afc60138cb3455eeac95e65e3e006392/src/RealtimeServer/scriptureforge/services/note-thread-service.spec.ts#L135)):*
> ```XML
>     const env = new TestEnvironment();
>     await env.createData();
>     const conn: Connection = clientConnect(env.server, 'reviewer');
> ```

I was confused initially around "reviewer". When I first started reviewing I thought this was related to the reviewer role and I wasn't sure which role it was. After reviewing I see "reviewer", in this instance, is just the user ID. If roles aren't relevant here then perhaps we should call this a different name? I can understand why you'd want to call it a reviewer as it links back to how we happen to have implemented that in the project rights.



_Code quote:_
```XML
  it('allows a reviewer to create a note thread', async () => {
    const env = new TestEnvironment();
    await env.createData();
    const conn: Connection = clientConnect(env.server, 'reviewer');
```
___
*[`src/RealtimeServer/scriptureforge/services/note-thread-service.spec.ts` line 181 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1635#-NLO58ql1bgZ_6Eswi39:-NLO58ql1bgZ_6Eswi3A:bcqdqqz) ([raw file](https://github.com/sillsdev/web-xforge/blob/ba78f556afc60138cb3455eeac95e65e3e006392/src/RealtimeServer/scriptureforge/services/note-thread-service.spec.ts#L181)):*
> ```XML
>   });
> 
>   it('allows reviewer to update own note', async () => {
> ```

state `update and delete` own note
___
*[`src/RealtimeServer/scriptureforge/services/note-thread-service.spec.ts` line 533 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1635#-NLO32h3B9JfeYep681O:-NLO32h46Wba26ednSNC:bn25das) ([raw file](https://github.com/sillsdev/web-xforge/blob/ba78f556afc60138cb3455eeac95e65e3e006392/src/RealtimeServer/scriptureforge/services/note-thread-service.spec.ts#L533)):*
> ```XML
>       dateModified: '',
>       ownerRef,
>       content: 'this note should not be inserted',
> ```

As this is a generic method I think `content` should be more generic as well otherwise it may confuse future tests if it is used when the content should be inserted.


<!-- Sent from Reviewable.io -->

2023-01-10 23:14 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1635)* status: all files reviewed, 6 unresolved discussions (waiting on @Nateowami and @nigel-wells)

___
*[`src/RealtimeServer/scriptureforge/models/note-thread.ts` line 66 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1635#-NLO93IqAktq29xmIxoU:-NLSr40gCik6N9HmdVRl:b-caj048) ([raw file](https://github.com/sillsdev/web-xforge/blob/ba78f556afc60138cb3455eeac95e65e3e006392/src/RealtimeServer/scriptureforge/models/note-thread.ts#L66)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

I agree that it will make it easier to run checks against a specific property. I'm not 100% on calling it "published". I would have thought "create" but I see you had then and changed your mind? Published to me says this note thread has been published on SF and others (PT) aren't which seems confusing. "Created On" seems right - what made you change it?
</blockquote></details>

This was something that Nathaniel and I had talked about. You are right that currently this describes notes that are created in SF, but we thought in the future there may be a reason to publish translator notes created in PT so they are visible to reviewer users. That's why we named it this way.
___
*[`src/RealtimeServer/scriptureforge/models/sf-project-rights.ts` line 78 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1635#-NIihClx4VK8kAcCThpS:-NLSrTMS81RWtFiKsYg7:b-qczc61) ([raw file](https://github.com/sillsdev/web-xforge/blob/180956bfae9e131345f461c31f1652fbf508d85c/src/RealtimeServer/scriptureforge/models/sf-project-rights.ts#L78)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

That's a nice way to do it, make the entity data available so you can check it and make a decision off that - I like it.
</blockquote></details>

Thanks. It saves us a lot of code when we do not have to overwrite the allowRead and the other permission checks.
___
*[`src/RealtimeServer/scriptureforge/services/note-thread-service.spec.ts` line 135 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1635#-NLO5bMP7CrZZIrPRIzZ:-NLSu-ms-3LOhpQHdTd_:b-qobao9) ([raw file](https://github.com/sillsdev/web-xforge/blob/ba78f556afc60138cb3455eeac95e65e3e006392/src/RealtimeServer/scriptureforge/services/note-thread-service.spec.ts#L135)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

I was confused initially around "reviewer". When I first started reviewing I thought this was related to the reviewer role and I wasn't sure which role it was. After reviewing I see "reviewer", in this instance, is just the user ID. If roles aren't relevant here then perhaps we should call this a different name? I can understand why you'd want to call it a reviewer as it links back to how we happen to have implemented that in the project rights.
</blockquote></details>

I was thinking the same way that you were, that the `reviewer` describes the userId only. But the project is defined with 3 users with the IDs `[projectAdmin, checker, reviewer]` and that does come into play. I'll leave a comment so that it is clear. I'll also replace the instances of the userIds with a variable.
___
*[`src/RealtimeServer/scriptureforge/services/note-thread-service.spec.ts` line 181 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1635#-NLO58ql1bgZ_6Eswi39:-NLSsyO0Cdq9fNtHH8Gk:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/ba78f556afc60138cb3455eeac95e65e3e006392/src/RealtimeServer/scriptureforge/services/note-thread-service.spec.ts#L181)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

state `update and delete` own note
</blockquote></details>

Done.
___
*[`src/RealtimeServer/scriptureforge/services/note-thread-service.spec.ts` line 533 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1635#-NLO32h3B9JfeYep681O:-NLSsPud8_DMwC_WvC5r:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/ba78f556afc60138cb3455eeac95e65e3e006392/src/RealtimeServer/scriptureforge/services/note-thread-service.spec.ts#L533)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

As this is a generic method I think `content` should be more generic as well otherwise it may confuse future tests if it is used when the content should be inserted.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-11 00:19 UTC, nigel-wells approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1635#-:-NLTB_J01wte-6HXEol9:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

___
*[`src/RealtimeServer/scriptureforge/models/note-thread.ts` line 66 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1635#-NLO93IqAktq29xmIxoU:-NLTBS9v6VSILwoazK6u:b-blwvn1) ([raw file](https://github.com/sillsdev/web-xforge/blob/ba78f556afc60138cb3455eeac95e65e3e006392/src/RealtimeServer/scriptureforge/models/note-thread.ts#L66)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This was something that Nathaniel and I had talked about. You are right that currently this describes notes that are created in SF, but we thought in the future there may be a reason to publish translator notes created in PT so they are visible to reviewer users. That's why we named it this way.
</blockquote></details>

Right ok - good to know.
___
*[`src/RealtimeServer/scriptureforge/services/note-thread-service.spec.ts` line 135 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1635#-NLO5bMP7CrZZIrPRIzZ:-NLT9v8tBZob88QTe82p:b-zcjvte) ([raw file](https://github.com/sillsdev/web-xforge/blob/ba78f556afc60138cb3455eeac95e65e3e006392/src/RealtimeServer/scriptureforge/services/note-thread-service.spec.ts#L135)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I was thinking the same way that you were, that the `reviewer` describes the userId only. But the project is defined with 3 users with the IDs `[projectAdmin, checker, reviewer]` and that does come into play. I'll leave a comment so that it is clear. I'll also replace the instances of the userIds with a variable.
</blockquote></details>

Thanks


<!-- Sent from Reviewable.io -->

2023-01-11 17:21 UTC, merged