SF-1808 Add default tag icon for SF notes
sillsdev/web-xforge pull request #1666
Opened 2023-01-16 22:24 UTC by RaymondLuong3

* define sf note tag name and icon
* update defaultCommentTag property when creating a note
* show note tag icon on settings page
* add method to update paratext comment tags
* update comment tag in paratext when a tag icon exists on the project
* remove tagIcon property from SFProject model
* TODO: update tagIcon property on note thread model
* TODO: Add community checking specific tag icon

2023-01-27 01:04 UTC, nigel-wells requested changes
Thanks for your work on this - looks like a pretty big task to reach this point.
I did have some issues when a opened the branch up that I'm yet to resolve. Existing projects gave me all sorts of errors trying to view settings. If I connected a new project the settings page worked but trying to add a note (as administrator) showed me a permission denied error on `sf_projects_profile`. I've done a `dotnet clean` and that didn't resolve anything. I'll try a little more otherwise I'll touch base with you when you're next in.

> Reviewed 20 of 40 files at r1, 28 of 28 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-:-NMkji_NCGAUbcDQ5MVT:bf4osg2)* status: all files reviewed, 28 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/RealtimeServer/scriptureforge/models/note-tag.ts` line 4 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-NMkA9PM1Zp0d1b1hj2s:-NMkA9PN5qmpQUkTjE91:bwwdmfi) ([raw file](https://github.com/sillsdev/web-xforge/blob/ddcf4240bd92407c10c52ce5af593b82c8e7da1d/src/RealtimeServer/scriptureforge/models/note-tag.ts#L4)):*
> ```XML
> export const SF_TAG_ICON = '06star2';
> export const SF_TAG_NAME = 'Scripture Forge Note';
> export const NOT_SET_ID = 0;
> ```

What's the purpose for this? Could it not be left undefined? Or have you done this so that the default icon doesn't show if it is undefined?
___
*[`src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts` line 149 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-NMjx9uhA8ZDuonCljeY:-NMjx9uhA8ZDuonCljeZ:bp7cexu) ([raw file](https://github.com/sillsdev/web-xforge/blob/ddcf4240bd92407c10c52ce5af593b82c8e7da1d/src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts#L149)):*
> ```XML
> 
> class SFProjectMigration7 implements Migration {
>   static readonly VERSION = 7;
> ```

The race is on! I have a migration script for the share dialog that is version 7 as well - which will be merged first! lol
___
*[`src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts` line 156 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-NMjx2wL-3uhmTjfde7d:-NMjx2wL-3uhmTjfde7e:b4gfmzu) ([raw file](https://github.com/sillsdev/web-xforge/blob/ddcf4240bd92407c10c52ce5af593b82c8e7da1d/src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts#L156)):*
> ```XML
>       ops.push({ p: ['tagIcon'], od: true });
>     }
>     await submitMigrationOp(SFProjectMigration6.VERSION, doc, ops);
> ```

I assume this is supposed to reference 7 not 6?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts` line 17 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-NMjyJmO2R3CRe4Gt0CZ:-NMjyJmO2R3CRe4Gt0C_:b-b4oxzw) ([raw file](https://github.com/sillsdev/web-xforge/blob/ddcf4240bd92407c10c52ce5af593b82c8e7da1d/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts#L17)):*
> ```XML
> export function defaultNoteThreadIcon(tagIcon: string | undefined): NoteThreadIcon {
>   if (tagIcon == null) {
>     tagIcon = SF_TAG_ICON;
> ```

Why is this no longer the `DEFAULT_TAG_ICON`? Are you saying `SF_TAG_ICON` is also a default icon? Why not just have the `SF_TAG_ICON` as the default in the first place?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts` line 102 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-NMjztAs1nYV3NwAHG_X:-NMjztAs1nYV3NwAHG_Y:b-djxqvk) ([raw file](https://github.com/sillsdev/web-xforge/blob/ddcf4240bd92407c10c52ce5af593b82c8e7da1d/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts#L102)):*
> ```XML
>       iconDefinedNotes.length === 0 ? undefined : iconDefinedNotes[iconDefinedNotes.length - 1].tagId;
>     if (tagId == null) {
>       return '';
> ```

Why would you not return the default icon here?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts` line 104 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-NMjy5zm0if_RI7HjHEH:-NMjy5zm0if_RI7HjHEI:b-exvic6) ([raw file](https://github.com/sillsdev/web-xforge/blob/ddcf4240bd92407c10c52ce5af593b82c8e7da1d/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts#L104)):*
> ```XML
>       return '';
>     }
>     return noteTags.find(t => t.id === tagId)?.icon ?? DEFAULT_TAG_ICON;
> ```

Similar to my question above - should this be `SF_TAG_ICON`?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.spec.ts` line 215 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-NMk1LZH3f1O-M7p7-rP:-NMk1LZH3f1O-M7p7-rQ:bwsfy95) ([raw file](https://github.com/sillsdev/web-xforge/blob/ddcf4240bd92407c10c52ce5af593b82c8e7da1d/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.spec.ts#L215)):*
> ```XML
>       ownerRef: 'user01',
>       projectRef: 'project01',
>       tagId: tagId,
> ```

Could simplify to just `tagId`
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.spec.ts` line 232 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-NMk1UVu8fgUEtz20P7z:-NMk1UVu8fgUEtz20P8-:bwsfy95) ([raw file](https://github.com/sillsdev/web-xforge/blob/ddcf4240bd92407c10c52ce5af593b82c8e7da1d/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.spec.ts#L232)):*
> ```XML
>         type: NoteType.Normal,
>         conflictType: NoteConflictType.DefaultValue,
>         tagId: tagId,
> ```

Could simplify to just `tagId`
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 1320 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-NMk331VEeH9Hlv29cfa:-NMk331VEeH9Hlv29cfb:b-3zm2id) ([raw file](https://github.com/sillsdev/web-xforge/blob/ddcf4240bd92407c10c52ce5af593b82c8e7da1d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1320)):*
> ```XML
>     const icon: NoteThreadIcon =
>       threadDoc.getIcon(this.noteTags).url.length === 0
>         ? defaultNoteThreadIcon(SF_TAG_ICON)
> ```

Same as other questions - I'm confused as to which icon should be the default?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts` line 3664 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-NMk5-6ADrSMCEhHxO27:-NMk5-6ADrSMCEhHxO28:b-eo02kc) ([raw file](https://github.com/sillsdev/web-xforge/blob/ddcf4240bd92407c10c52ce5af593b82c8e7da1d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L3664)):*
> ```XML
>       u => u.sfUserId === assignedSFUserRef
>     );
>     const noteTagId: number | undefined = undefinedTagId ? undefined : 1;
> ```

I found the naming and use of `undefinedTagId` confusing. If `undefinedTagId` is `true` then set it to `undefined`. I would have thought it would be more straight forward to simply check if it is undefined rather and set it to `false` from your test. This why your checking a field labeled `undefined` if it is indeed `undefined` - if that made sense.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts` line 712 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-NMkAm1G0JR-htUwpeb3:-NMkAm1G0JR-htUwpeb4:bwp0u57) ([raw file](https://github.com/sillsdev/web-xforge/blob/ddcf4240bd92407c10c52ce5af593b82c8e7da1d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts#L712)):*
> ```XML
>     const type: NoteType = NoteType.Normal;
>     const conflictType: NoteConflictType = NoteConflictType.DefaultValue;
>     const tagId: number | undefined = undefinedTagId ? undefined : 1;
> ```

Similar as other comment
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 242 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-NMkjO6VDfEGJkqZ-iO3:-NMkjO6VDfEGJkqZ-iO4:b-61n974) ([raw file](https://github.com/sillsdev/web-xforge/blob/ [...]

2023-01-27 02:02 UTC, nigel-wells reviewed
FYI the permission denied error may be something else as I'm seeing it on all branches now. I don't believe it was there prior to checking out this branch

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-:-NMkxALJEdmS-OKVRR1h:bp8icx0)* status: all files reviewed, 28 unresolved discussions (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2023-01-31 23:49 UTC, RaymondLuong3 reviewed
Hmm, let's look at this together.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-:-NN8DwMOBTNGzGrQBSo0:bh2wdny)* status: 29 of 50 files reviewed, 28 unresolved discussions (waiting on @github-code-scanning[bot] and @nigel-wells)

___
*[`src/RealtimeServer/scriptureforge/models/note-tag.ts` line 4 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-NMkA9PM1Zp0d1b1hj2s:-NN8FZ6U-qqepSxVCygO:bf25oyw) ([raw file](https://github.com/sillsdev/web-xforge/blob/ddcf4240bd92407c10c52ce5af593b82c8e7da1d/src/RealtimeServer/scriptureforge/models/note-tag.ts#L4)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

What's the purpose for this? Could it not be left undefined? Or have you done this so that the default icon doesn't show if it is undefined?
</blockquote></details>

Actually, I can remove this now that I have added a step to migrate note threads so they do not have the tagId property.
___
*[`src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts` line 149 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-NMjx9uhA8ZDuonCljeY:-NN8G_zjEioniXARsxE5:bw76kyc) ([raw file](https://github.com/sillsdev/web-xforge/blob/ddcf4240bd92407c10c52ce5af593b82c8e7da1d/src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts#L149)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

The race is on! I have a migration script for the share dialog that is version 7 as well - which will be merged first! lol
</blockquote></details>

Haha, it is on indeed.
___
*[`src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts` line 156 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-NMjx2wL-3uhmTjfde7d:-NN8HeeA3BVUpb12X5js:boyvzmv) ([raw file](https://github.com/sillsdev/web-xforge/blob/ddcf4240bd92407c10c52ce5af593b82c8e7da1d/src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts#L156)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

I assume this is supposed to reference 7 not 6?
</blockquote></details>

You're right! I'm not sure how the test didn't end up catching that.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts` line 17 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-NMjyJmO2R3CRe4Gt0CZ:-NN8p1QD432pRuBktlfM:bp8poqj) ([raw file](https://github.com/sillsdev/web-xforge/blob/ddcf4240bd92407c10c52ce5af593b82c8e7da1d/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts#L17)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Why is this no longer the `DEFAULT_TAG_ICON`? Are you saying `SF_TAG_ICON` is also a default icon? Why not just have the `SF_TAG_ICON` as the default in the first place?
</blockquote></details>

Thanks for pointing this out. I think I was starting to get confused about how to use this function. I've added a comment to help me remember.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts` line 102 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-NMjztAs1nYV3NwAHG_X:-NN8qlcIDNm6ktXXCT0y:b-nc647p) ([raw file](https://github.com/sillsdev/web-xforge/blob/ddcf4240bd92407c10c52ce5af593b82c8e7da1d/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts#L102)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Why would you not return the default icon here?
</blockquote></details>

If we return the empty string for threads that do not have any `tagIds` set on its notes (which happens when users first start creating notes) then we can provide the default SF note tag in the component. So there is a distinction between a default for an ID we do not know, and when there is no tag Id at all.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts` line 104 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-NMjy5zm0if_RI7HjHEH:-NN8qomv2VfI-3YUg0Bw:b-1l06dn) ([raw file](https://github.com/sillsdev/web-xforge/blob/ddcf4240bd92407c10c52ce5af593b82c8e7da1d/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts#L104)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Similar to my question above - should this be `SF_TAG_ICON`?
</blockquote></details>

The distinction between the `DEFAULT_TAG_ICON` and the `SF_TAG_ICON` is that the first will be used whenever we cannot determine the icon from the ID, and the second will be used when we know that the user is creating an SF note, then the default is `SF_TAG_ICON` until they set otherwise. In this case, the `DEFAULT_TAG_ICON` is right.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.spec.ts` line 215 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-NMk1LZH3f1O-M7p7-rP:-NN8rpys-F3HH8UeqNpG:b-7wso34) ([raw file](https://github.com/sillsdev/web-xforge/blob/ddcf4240bd92407c10c52ce5af593b82c8e7da1d/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.spec.ts#L215)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Could simplify to just `tagId`
</blockquote></details>

Not relevant anymore
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.spec.ts` line 232 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-NMk1UVu8fgUEtz20P7z:-NN8rv2KCLEX7yLqhOcg:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/ddcf4240bd92407c10c52ce5af593b82c8e7da1d/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.spec.ts#L232)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Could simplify to just `tagId`
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 1320 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-NMk331VEeH9Hlv29cfa:-NN8ryLx1A1SycBEtEts:b-4ztj2h) ([raw file](https://github.com/sillsdev/web-xforge/blob/ddcf4240bd92407c10c52ce5af593b82c8e7da1d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1320)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Same as other questions - I'm confused as to which icon should be the default?
</blockquote></details>

This is addressed above.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts` line 3664 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-NMk5-6ADrSMCEhHxO27:-NN8wQbL1W8W_vrRX3wI:b-txsgs8) ([raw file](https://github.com/sillsdev/web-xforge/blob/ddcf4240bd92407c10c52ce5af593b82c8e7da1d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L3664)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

I found the naming and use of `undefinedTagId` confusing. If `undefinedTagId` is `true` then set it to `undefined`. I would have thought it would be more straight forward to simply check if it is undefined rather and set it to `false` from your test. This why your checking a field labeled `undefined` if it is indeed `undefined` - if that made sense.
</blockquote></details>

I've renamed the variable. I wanted an easy way to create a note thread with undefined as the tag Id without needing to explicitly require that parameter in `addParatextNoteThread`. Is this any better?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/note-dialog/note-dialog.component.spec.ts` line 712 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-NMkAm1G0JR-htUwpeb3:-NN8xFxP68SxRtCyqHm3:b-34vmyd) ([raw file](https://github.com/sillsdev/web-xforge/blob/ddcf4240bd92407c10c52ce5af593b82c8e7da1d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/ [...]

2023-02-01 20:01 UTC, RaymondLuong3 reviewed
I wasn't seeing any of the permission denied errors you were seeing, but it is possible it was related to changes with the permissions system which should be fixed now.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-:-NNDZO-Q0gOmQzdGLgNx:b4arp8u)* status: 25 of 50 files reviewed, 30 unresolved discussions (waiting on @github-code-scanning[bot] and @nigel-wells)

___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs` line 3844 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-NLwfrkZCZh10a8Kq0Gd-r3-3844:-NNDZKSA4egTLGQ4wNlQ:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/c4d9e6a3c358b50ff9e7060e4b5772d8eeb2c0a2/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L3844)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Useless assignment to local variable

This assignment to [threadTagId](1) is useless, since its value is never read.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/464)
</blockquote></details>

Done.
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs` line 3850 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-NLwfrkZCZh10a8Kq0Gd-r3-3850:-NNDZKj_BJXURNAodr4W:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/c4d9e6a3c358b50ff9e7060e4b5772d8eeb2c0a2/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L3850)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Useless assignment to local variable

This assignment to [threadTagId](1) is useless, since its value is never read.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/465)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-01 21:51 UTC, nigel-wells requested changes
I've just got a couple of clarifying questions below. I'll re-run some tests to see if that permission error has gone away and let you know.

> Reviewed 8 of 21 files at r3, 17 of 17 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-:-NNDxMXH5y4ZiSWwGgFZ:b-469wuo)* status: all files reviewed, 12 unresolved discussions (waiting on @github-code-scanning[bot] and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts` line 102 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-NMjztAs1nYV3NwAHG_X:-NNDqk5f9Yl-e7uBVSwq:b-aj47y0) ([raw file](https://github.com/sillsdev/web-xforge/blob/ddcf4240bd92407c10c52ce5af593b82c8e7da1d/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts#L102)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

If we return the empty string for threads that do not have any `tagIds` set on its notes (which happens when users first start creating notes) then we can provide the default SF note tag in the component. So there is a distinction between a default for an ID we do not know, and when there is no tag Id at all.
</blockquote></details>

Thanks for this. What does "1" represent in this new line of `t.tagId === 1`? Is this a specific icon you're trying to target or is there something else special about that ID that we want to use it?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts` line 104 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-NMjy5zm0if_RI7HjHEH:-NNDqg1GBjrRn04xYRSD:b-eckuzd) ([raw file](https://github.com/sillsdev/web-xforge/blob/ddcf4240bd92407c10c52ce5af593b82c8e7da1d/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts#L104)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

The distinction between the `DEFAULT_TAG_ICON` and the `SF_TAG_ICON` is that the first will be used whenever we cannot determine the icon from the ID, and the second will be used when we know that the user is creating an SF note, then the default is `SF_TAG_ICON` until they set otherwise. In this case, the `DEFAULT_TAG_ICON` is right.
</blockquote></details>

Right, ok.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts` line 3664 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-NMk5-6ADrSMCEhHxO27:-NNDtgteAptX9FECU6Qp:bbrjw2s) ([raw file](https://github.com/sillsdev/web-xforge/blob/ddcf4240bd92407c10c52ce5af593b82c8e7da1d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L3664)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I've renamed the variable. I wanted an easy way to create a note thread with undefined as the tag Id without needing to explicitly require that parameter in `addParatextNoteThread`. Is this any better?
</blockquote></details>

Ah, ok. Yes, renaming that makes more sense thanks.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 242 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-NMkjO6VDfEGJkqZ-iO3:-NNDwp321S-gSAKkEsd1:b4oq9kj) ([raw file](https://github.com/sillsdev/web-xforge/blob/ddcf4240bd92407c10c52ce5af593b82c8e7da1d/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L242)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Does this work better? It explains how it will be created, so the user can just assume it will happen automatically.
</blockquote></details>

That is better thanks. To clarify, the tag icon can not be changed until after a user creates some notes and then a PT user does a sync? This means the initial notes added are stuck on whatever that note was until the sync takes place? Is this because flag data isn't available until after notes exist in the project?
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs` line 754 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-NMkfRgh8ZT4-UvCUcex:-NNDw2iYETJGGrNVP_Mq:b1zumaj) ([raw file](https://github.com/sillsdev/web-xforge/blob/ddcf4240bd92407c10c52ce5af593b82c8e7da1d/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L754)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

No need because we can already tell that the 3rd `NoteTag` was deleted because it is not in `project.NoteTags`.
</blockquote></details>

Of course - its amazing how looking at code with fresh eyes makes it clearer :)


<!-- Sent from Reviewable.io -->

2023-02-01 23:46 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1666)* status: all files reviewed, 12 unresolved discussions (waiting on @github-code-scanning[bot] and @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts` line 102 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-NMjztAs1nYV3NwAHG_X:-NNELATB04Ml9mO1jVdz:b-f2z0gl) ([raw file](https://github.com/sillsdev/web-xforge/blob/ddcf4240bd92407c10c52ce5af593b82c8e7da1d/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts#L102)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Thanks for this. What does "1" represent in this new line of `t.tagId === 1`? Is this a specific icon you're trying to target or is there something else special about that ID that we want to use it?
</blockquote></details>

The tag with the ID "1" is guaranteed to exist, it is the `toDoTagId` in Paratext. I've created a const variable for it.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 242 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-NMkjO6VDfEGJkqZ-iO3:-NNEM-t0C99cCsfUSVm8:b17epz) ([raw file](https://github.com/sillsdev/web-xforge/blob/ddcf4240bd92407c10c52ce5af593b82c8e7da1d/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L242)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

That is better thanks. To clarify, the tag icon can not be changed until after a user creates some notes and then a PT user does a sync? This means the initial notes added are stuck on whatever that note was until the sync takes place? Is this because flag data isn't available until after notes exist in the project?
</blockquote></details>

That's right, when a user first starts adding note, the default star icon will be used. I initially wanted to allow an admin to select the icon for SF notes in the settings page, but Nathaniel pointed out it is better not to replicate settings that can be controlled in Paratext. In any case, we are not allowing users to update note tags in SF (yet) so the star icon will be used for SF notes until a paratext user updates the tag in PT and we synchronize.
Flag data will be available right away once this change is merged, and a PT user does sync.


<!-- Sent from Reviewable.io -->

2023-02-02 21:22 UTC, nigel-wells requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-:-NNJ-SsA76Jx7GyzBh9r:bg7igkv)* status: all files reviewed, 9 unresolved discussions (waiting on @github-code-scanning[bot] and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts` line 102 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-NMjztAs1nYV3NwAHG_X:-NNIzzas9IZTQnmmWC9w:b-ucfkn4) ([raw file](https://github.com/sillsdev/web-xforge/blob/ddcf4240bd92407c10c52ce5af593b82c8e7da1d/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts#L102)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

The tag with the ID "1" is guaranteed to exist, it is the `toDoTagId` in Paratext. I've created a const variable for it.
</blockquote></details>

Thanks.


<!-- Sent from Reviewable.io -->

2023-02-02 21:22 UTC, nigel-wells approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-:-NNJ-_r18FZ3VxreN3Mk:bnfp4nl)* status: all files reviewed, 9 unresolved discussions (waiting on @github-code-scanning[bot] and @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2023-02-03 03:56 UTC, Nateowami requested changes
Good work. I do see a couple of issues:
1. I'm not really sure the information about adding notes really belongs on the settings page. I think that belongs in documentation (though I do think we need to more closely integrate our help with various pages in the app itself).
2. It definitely should not be shown when the "allow adding notes" feature flag is off. Right now it's showing up.
3. Making changes to the note tags in Paratext doesn't appear to sync back to the project document in Scripture Forge. Maybe this just hasn't been implemented yet?
4. I can't remember if this is supposed to work yet, but right now if I create a note it doesn't actually sync, and disappears after doing a sync. I think this is not a regression and is just the current state of master?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-:-NNKE6Fu2lbcm-aTzJLi:bbok1yk)* status: all files reviewed, 9 unresolved discussions (waiting on @github-code-scanning[bot] and @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2023-02-06 20:07 UTC, RaymondLuong3 reviewed
Thanks for double checking.
1. I agree, it would be best to have that info in a help document that we can link to. When it comes time to add the helps, I'll bring this up. But we can update the settings page at that time.
2. Thanks, I had forgotten to hide it behind the feature flag.
3. This is fixed now. Apparently there is a cached comment tag file that we needed to updated.
4. The sync works only when we uncomment the code. It just hasn't been tested thoroughly so it is not yet production ready.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-:-NNcJ01EDL6bEXFunYsS:b-ozx0br)* status: 44 of 51 files reviewed, 9 unresolved discussions (waiting on @github-code-scanning[bot] and @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts` line 102 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-NMjztAs1nYV3NwAHG_X:-NNcKqQtAQAMmJKEYgp9:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/ddcf4240bd92407c10c52ce5af593b82c8e7da1d/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/note-thread-doc.ts#L102)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Thanks.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-06 21:21 UTC, nigel-wells approved these changes
> Reviewed 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1666)* status: all files reviewed, 8 unresolved discussions (waiting on @github-code-scanning[bot])



<!-- Sent from Reviewable.io -->

2023-02-08 20:19 UTC, Nateowami reviewed
Just re-reviewed this, and it looks like the main issues are now fixed. I do think the notice on the settings page should be removed before merging for a couple of reasons:
1. It really belongs in help documentation
2. Once we add the same feature for community checking answers, if we put it on the settings page, there will then be two of these notices, which seems kind of redundant
3. I think it would be more helpful to show a warning message if and only if there is a collision between what icons are used by SF and other note tags (I'm envisioning a future "warnings" section where we surface relevant warnings like "Your project's font is set to a font we can't serve for licensing reasons; please consider changing it").
4. Once this gets merged, the strings will be in Crowdin. So even if we make changes between now and when the notes feature goes live, the translators will still get asked to translate these strings.
5. The settings page is already in need of some cleanup/streamlining/clarification (especially around sharing settings, which will probably be pulled out into their own section). Once that's cleaned up this message is likely to be even more out of place.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-:-NNmbrDyCidrxRtq5to2:b-p437bg)* status: all files reviewed (commit messages unreviewed), 8 unresolved discussions (waiting on @github-code-scanning[bot])



<!-- Sent from Reviewable.io -->

2023-02-08 20:58 UTC, RaymondLuong3 reviewed
Hmm, I wasn't sure if you were suggesting that we remove just a part or the entire adding notes section on the settings page. Since it is not a setting that can be controlled in SF anyways, I've removed the entire section. A user may just be happily surprised to see it all working without any configuration or thought on their part. Then the help pages can explain how a use could update the icon if they choose to. What do you think?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-:-NNmnzLUEUTqT5GuRPjY:b96dv31)* status: 46 of 51 files reviewed, 8 unresolved discussions (waiting on @github-code-scanning[bot] and @nigel-wells)



<!-- Sent from Reviewable.io -->

2023-02-09 02:56 UTC, Nateowami reviewed
Agree. Looks good.

> Reviewed 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1666#-:-NNo5Zr-B4DXC_D8jAG6:b1dbbd8)* status: all files reviewed, 8 unresolved discussions (waiting on @github-code-scanning[bot])



<!-- Sent from Reviewable.io -->

2023-02-09 02:57 UTC, Nateowami approved these changes

2023-02-09 03:11 UTC, merged