SF-1911 Schema Validation in MongoDB
sillsdev/web-xforge pull request #1746
Opened 2023-03-14 22:38 UTC by pmachapman

This PR adds schema validation in MongoDB, which logs warnings when does not match the validation schema.

To Do:
 * Tools to verify and correct schema validation errors

2023-08-16 18:48 UTC, RaymondLuong3 requested changes
Excellent! Even though this does not fully stop bad data from getting into our mongo data, we will at least know that what we have in mongo will match the schema, which is a good step forward. I have a few suggestions.

I also noticed when I tried to get it to fail, I get an unusual error. It looks like it was done on purpose. It's not the error I was expecting to see. I changed the answer status to one that is not defined and I got an error that I was expecting.
![image.png](https://files.reviewableusercontent.io/images/reviewable/17931130/lIY9LTnZiq5pN8t0c6xFtsd5/image.png)

But also after I refreshed the page I see this.
![image copy 1.png](https://files.reviewableusercontent.io/images/reviewable/17931130/XN-q8MNPYwl13eJ6lvmkFk7w/image.png)

And the answer does get pushed to mongo (I don't think I was expecting that).

> Reviewed 2 of 27 files at r1, 36 of 36 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-:-NbzZtiX3mJWFLr8XEkN:b-ix3y32)* status: all files reviewed, 19 unresolved discussions (waiting on @pmachapman)

___
*[`scripts/db_tools/validate-data.ts` line 5 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-Nbz8APU7ZqSwnWU4Xkg:-Nbz8APU7ZqSwnWU4Xkh:bb752ax) ([raw file](https://github.com/sillsdev/web-xforge/blob/d894ff58ca293c508ac291700ebe51de1ba2f682/scripts/db_tools/validate-data.ts#L5)):*
> ```XML
> //
> // Validate Data
> //
> ```

Typo
___
*[`scripts/db_tools/validate-data.ts` line 8 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-NbzZ_nZ3_s1O4dlAGgr:-NbzZ_nZ3_s1O4dlAGgs:bdw3ucc) ([raw file](https://github.com/sillsdev/web-xforge/blob/d894ff58ca293c508ac291700ebe51de1ba2f682/scripts/db_tools/validate-data.ts#L8)):*
> ```XML
> // Validates the dta in MongoDB based on the validation schemas installed
> //
> // This script needs ts-node and must be run from the containing directory. Setup: npm ci
> ```

Nice tool! I was able to run it and see any documents with data that does not match the schema. You might want to include that the real-time server should be running to use the tool. Otherwise it looks like the tools starts but does nothing.



_Code quote:_
```XML
// This script needs ts-node and must be run from the containing directory. Setup: npm ci
```
___
*[`scripts/db_tools/validate-data.ts` line 89 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-NbzAMG-EksgPHelvWbh:-NbzAMG-EksgPHelvWbi:b-op9pyg) ([raw file](https://github.com/sillsdev/web-xforge/blob/d894ff58ca293c508ac291700ebe51de1ba2f682/scripts/db_tools/validate-data.ts#L89)):*
> ```XML
> 
>           // Retrieve all invalid documents from the collection
>           const documents = await db
> ```

Can you add types to these? Here and elsewhere in the file.



_Code quote:_
```XML
  const documents = await db
```
___
*[`src/RealtimeServer/common/realtime-server.ts` line 177 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-NbzCCo7A9OaYKXb6eLB:-NbzCCo7A9OaYKXb6eLC:b-o5ntcq) ([raw file](https://github.com/sillsdev/web-xforge/blob/d894ff58ca293c508ac291700ebe51de1ba2f682/src/RealtimeServer/common/realtime-server.ts#L177)):*
> ```XML
>     // Setup Ajv
>     const ajv = new Ajv({ strict: false, allErrors: true, logger: false });
>     ajvBsonType(ajv);
> ```

That is neat that Mongo provides a bson validator for ajv. 



_Code quote:_
```XML
   ajvBsonType(ajv);
```
___
*[`src/RealtimeServer/common/realtime-server.ts` line 204 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-NbzD9Tc62blnSgvgOuw:-NbzD9Tc62blnSgvgOux:b-mxkhx0) ([raw file](https://github.com/sillsdev/web-xforge/blob/d894ff58ca293c508ac291700ebe51de1ba2f682/src/RealtimeServer/common/realtime-server.ts#L204)):*
> ```XML
>         for (const op of ops) {
>           // Skip blank operations
>           if (op.p == null) {
> ```

Is this really a blank operation? Or just one without a path so there is no way to apply it.



_Code quote:_
```XML
   if (op.p == null) {
```
___
*[`src/RealtimeServer/common/realtime-server.ts` line 207 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-NbzDIjN68geM4ygrf1h:-NbzDIjN68geM4ygrf1i:b-rh63k7) ([raw file](https://github.com/sillsdev/web-xforge/blob/d894ff58ca293c508ac291700ebe51de1ba2f682/src/RealtimeServer/common/realtime-server.ts#L207)):*
> ```XML
>             continue;
>           }
>           let properties = validationSchema.properties;
> ```

Add types where possible.



_Code quote:_
```XML
     let properties = validationSchema.properties;
```
___
*[`src/RealtimeServer/common/realtime-server.ts` line 310 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-NbzGRIFEqpTFBsOtrKC:-NbzGRIFEqpTFBsOtrKD:bdfj8gb) ([raw file](https://github.com/sillsdev/web-xforge/blob/d894ff58ca293c508ac291700ebe51de1ba2f682/src/RealtimeServer/common/realtime-server.ts#L310)):*
> ```XML
>                     break;
>                   case 'null':
>                     validData = newValue == null;
> ```

I don't know if I knew there was such a thing as a null type.



_Code quote:_
```XML
                  case 'null':
                    validData = newValue == null;
```
___
*[`src/RealtimeServer/common/realtime-server.ts` line 325 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-NbzH7Su7BB1krK3b3oY:-NbzH7Su7BB1krK3b3oZ:b-z1n864) ([raw file](https://github.com/sillsdev/web-xforge/blob/d894ff58ca293c508ac291700ebe51de1ba2f682/src/RealtimeServer/common/realtime-server.ts#L325)):*
> ```XML
>                   case 'object': {
>                     const validate = ajv.compile(propertySchema);
>                     validData = validate(newValue);
> ```

What does validate do to check that the new value is valid?



_Code quote:_
```XML
                    const validate = ajv.compile(propertySchema);
                    validData = validate(newValue);
```
___
*[`src/RealtimeServer/common/models/validation-schema.ts` line 2 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-NbzLXmPC5AKdnMlRA0J:-NbzLXmPC5AKdnMlRA0K:bhj7eg4) ([raw file](https://github.com/sillsdev/web-xforge/blob/d894ff58ca293c508ac291700ebe51de1ba2f682/src/RealtimeServer/common/models/validation-schema.ts#L2)):*
> ```XML
> export interface ValidationSchema {
>   additionalProperties?: boolean;
> ```

This one checks that additional properties are allowed on the object, is that correct? Could you add documentation for that?



_Code quote:_
```XML
  additionalProperties?: boolean;
```
___
*[`src/RealtimeServer/common/services/project-service.ts` line 52 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-NbzMZr88-3aP6wIm67p:-NbzMZr88-3aP6wIm67q:b-cvq7h8) ([raw file](https://github.com/sillsdev/web-xforge/blob/d894ff58ca293c508ac291700ebe51de1ba2f682/src/RealtimeServer/common/services/project-service.ts#L52)):*
> ```XML
>       _type: {
>         bsonType: ['null', 'string']
>       },
> ```

I think there would only be two types for our docs, Json0 and richtext. When would a type be null? Or maybe I'm not understanding this correctly. Ah, yes I see now that it is saved as a url to sharejs.org. Hmm, that is probably good enough for me.



_Code quote:_
```XML
      _type: {
        bsonType: ['null', 'string']
      },
```
___
*[`src/RealtimeServer/common/services/user-service.ts` line 49 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-NbzN9oMEJWTRrVTxn_Q:-NbzN9oMEJWTRrVTxn_R:b-sj624e) ([raw file](https://github.com/sillsdev/web-xforge/blob/d894ff58ca293c508ac291700ebe51de1ba2f682/src/RealtimeServer/common/services/user-service.ts#L49)):*
> ```XML
>       email: {
>         bsonType: 'string'
>       },
> ```

We could specify a length for the paratextId, but I am ok with this as is too.
___
*[`src/RealtimeServer/common/services/user-service.ts` line 74 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-NbzN_2GDWCeUUh_Wt2r:-NbzN_2GDWCeUUh_Wt2s:bf535l2) ([raw file](https://github.com/sillsdev/web-xforge/blob/d894ff58ca293c50 [...]

2023-08-16 18:52 UTC, RaymondLuong3 reviewed
Actually, it does look like the answer was blocked from being submitted. So that is working as I expected.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-:-NbzgC8R4fc3cyeKZHht:b-e2ehmt)* status: all files reviewed, 19 unresolved discussions (waiting on @pmachapman)



<!-- Sent from Reviewable.io -->

2023-08-20 22:44 UTC, pmachapman reviewed
Thanks - I have fixed the points raised (apologies if I missed any, I split this over two days), and have added the schema for text_audio.

I am not sure about the error you describe - if you let me know your method, I can try to recreate it.

Perhaps some of the problem is that the error only occurs when the op is pushed to the Realtime Server? (which is in another thread, I believe)

> Dismissed @github-code-scanning[bot] from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-:-NcJdJbe1mup3gpEYJrp:b4devx4)* status: all files reviewed, 16 unresolved discussions (waiting on @RaymondLuong3)

___
*[`scripts/db_tools/validate-data.ts` line 5 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-Nbz8APU7ZqSwnWU4Xkg:-Nc0FLVeEZPuUcqwC-Mb:b-a6taqh) ([raw file](https://github.com/sillsdev/web-xforge/blob/d894ff58ca293c508ac291700ebe51de1ba2f682/scripts/db_tools/validate-data.ts#L5)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Typo
</blockquote></details>

Thanks! Fixed.
___
*[`scripts/db_tools/validate-data.ts` line 8 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-NbzZ_nZ3_s1O4dlAGgr:-Nc0GPgR6n03U5jNKFHW:b-f54bg) ([raw file](https://github.com/sillsdev/web-xforge/blob/d894ff58ca293c508ac291700ebe51de1ba2f682/scripts/db_tools/validate-data.ts#L8)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Nice tool! I was able to run it and see any documents with data that does not match the schema. You might want to include that the real-time server should be running to use the tool. Otherwise it looks like the tools starts but does nothing.
</blockquote></details>

The realtime server doesn't need to be running for the tool to work, but it must be run just once to have the schemas created in MongoDB.
___
*[`scripts/db_tools/validate-data.ts` line 89 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-NbzAMG-EksgPHelvWbh:-Nc0IBOo9uCnIzZhc8-V:byed8lo) ([raw file](https://github.com/sillsdev/web-xforge/blob/d894ff58ca293c508ac291700ebe51de1ba2f682/scripts/db_tools/validate-data.ts#L89)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Can you add types to these? Here and elsewhere in the file.
</blockquote></details>

Done - thanks!
___
*[`src/RealtimeServer/common/realtime-server.ts` line 204 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-NbzD9Tc62blnSgvgOuw:-NcJRpdq5ZfjHDim6IIj:bif1dxq) ([raw file](https://github.com/sillsdev/web-xforge/blob/d894ff58ca293c508ac291700ebe51de1ba2f682/src/RealtimeServer/common/realtime-server.ts#L204)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Is this really a blank operation? Or just one without a path so there is no way to apply it.
</blockquote></details>

Just one without a path. Have clarified the comment.
___
*[`src/RealtimeServer/common/realtime-server.ts` line 207 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-NbzDIjN68geM4ygrf1h:-Nc0Oprz8CC0zo6WoWkv:bkk50zm) ([raw file](https://github.com/sillsdev/web-xforge/blob/d894ff58ca293c508ac291700ebe51de1ba2f682/src/RealtimeServer/common/realtime-server.ts#L207)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Add types where possible.
</blockquote></details>

Done - please let me know if I have forgotten any.
___
*[`src/RealtimeServer/common/realtime-server.ts` line 325 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-NbzH7Su7BB1krK3b3oY:-Nc0PDnh2ihKa7Eh9VSA:bj2i27i) ([raw file](https://github.com/sillsdev/web-xforge/blob/d894ff58ca293c508ac291700ebe51de1ba2f682/src/RealtimeServer/common/realtime-server.ts#L325)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

What does validate do to check that the new value is valid?
</blockquote></details>

ajv compiles schemas into functions (see https://ajv.js.org/guide/getting-started.html). We then use the function that was generated to check that the property's value matches the property's schema.
___
*[`src/RealtimeServer/common/models/validation-schema.ts` line 2 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-NbzLXmPC5AKdnMlRA0J:-Nc0RHdI3S-GFkzc0kd1:bcvjgzp) ([raw file](https://github.com/sillsdev/web-xforge/blob/d894ff58ca293c508ac291700ebe51de1ba2f682/src/RealtimeServer/common/models/validation-schema.ts#L2)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This one checks that additional properties are allowed on the object, is that correct? Could you add documentation for that?
</blockquote></details>

Good idea. Done.
___
*[`src/RealtimeServer/common/services/project-service.ts` line 52 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-NbzMZr88-3aP6wIm67p:-Nc0Iy277RN0EbM4MKcu:b-p7wte7) ([raw file](https://github.com/sillsdev/web-xforge/blob/d894ff58ca293c508ac291700ebe51de1ba2f682/src/RealtimeServer/common/services/project-service.ts#L52)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I think there would only be two types for our docs, Json0 and richtext. When would a type be null? Or maybe I'm not understanding this correctly. Ah, yes I see now that it is saved as a url to sharejs.org. Hmm, that is probably good enough for me.
</blockquote></details>

If I remember correctly, it can be null in some cases if the object is deleted.

And yes, the string is a url describing the type of the doc.
___
*[`src/RealtimeServer/common/services/user-service.ts` line 49 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-NbzN9oMEJWTRrVTxn_Q:-NcJa52s88NCs2SMUnrl:bms06gf) ([raw file](https://github.com/sillsdev/web-xforge/blob/d894ff58ca293c508ac291700ebe51de1ba2f682/src/RealtimeServer/common/services/user-service.ts#L49)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

We could specify a length for the paratextId, but I am ok with this as is too.
</blockquote></details>

I didn't specify a length or character regex, as it is not a user updatable value (this part of the schema will just be used for document validation in Mongo).
___
*[`src/RealtimeServer/common/services/user-service.ts` line 74 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-NbzN_2GDWCeUUh_Wt2r:-NcJTHoiEJzch3X99a-u:b-owfe6r) ([raw file](https://github.com/sillsdev/web-xforge/blob/d894ff58ca293c508ac291700ebe51de1ba2f682/src/RealtimeServer/common/services/user-service.ts#L74)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This could be null in the case that the user is not currently on the project. Does this handle that case?
</blockquote></details>

This case is handled as `UserService.setCurrentProjectId()` unsets this property if a null value is specified. We only need to have `['null', 'string']` if a property is explicitly set to null.
___
*[`src/RealtimeServer/common/services/user-service.ts` line 112 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-NbzNu9fBJUzGXKSgBaT:-NcJlAb5EU7YrJXxwmbF:b-468plj) ([raw file](https://github.com/sillsdev/web-xforge/blob/d894ff58ca293c508ac291700ebe51de1ba2f682/src/RealtimeServer/common/services/user-service.ts#L112)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

What do you think about creating a base validation schema, like MongoDocumentSchema that ValidationSchema can inherit from. And these you could put the `_id, _type, _v, etc.` into the MongoDocumentSchema.
</blockquote></details>

Good idea. I have added static validation schemas to `DocService` and `ProjectDataService`, and modified the services that inherit from these reuse the validation schema properties.

JSON Schemas don't support inher [...]

2023-08-21 22:13 UTC, RaymondLuong3 requested changes
Nice. It's getting closer. I am still able to see an error when I change something in the model but do not propagate that change into the schema. I added a num enum value for AnswerStatus and built the realtime server models. Then I added the new enum in `checking.component.ts` and when I tried to create an answer and save it, the error appears. If I refresh the page, the error dialog appears again.

![image.png](https://files.reviewableusercontent.io/images/reviewable/17931130/GimZBl8hyhXFnomkQhPBPAwU/image.png)

> Reviewed 14 of 14 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-:-NcP8Xk38QDWyLTubEpC:bkjklsd)* status: all files reviewed, 3 unresolved discussions (waiting on @pmachapman)

___
*[`scripts/db_tools/validate-data.ts` line 8 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-NbzZ_nZ3_s1O4dlAGgr:-NcP4lPg1IgTT1cMSWez:b-hk637u) ([raw file](https://github.com/sillsdev/web-xforge/blob/d894ff58ca293c508ac291700ebe51de1ba2f682/scripts/db_tools/validate-data.ts#L8)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

The realtime server doesn't need to be running for the tool to work, but it must be run just once to have the schemas created in MongoDB.
</blockquote></details>

Oh, I see now why I thought I needed to have the realtime server running. That's good to know the server has to be run once before this script will work.
___
*[`scripts/db_tools/validate-data.ts` line 108 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-NcP5D4l40CZ0qmC7OJa:-NcP5D4l40CZ0qmC7OJb:b3a6dlq) ([raw file](https://github.com/sillsdev/web-xforge/blob/2a425e4ce405a26d70940d7b6d39a043546e23d4/scripts/db_tools/validate-data.ts#L108)):*
> ```XML
>             console.log(`${colored(colors.red, `${collection.name} document failed validation:`)} ${document._id}`);
>             if (this.showValidationErrors) {
>               const isValid: Boolean = validate(document);
> ```

boolean should actually be lowercase for the primitive type.



_Code quote:_
```XML
 const isValid: Boolean = validate(document);
```
___
*[`src/RealtimeServer/common/services/project-data-service.spec.ts` line 337 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-NcP6XZZ3z1ePtVR7Srw:-NcP6XZZ3z1ePtVR7Srx:brxfiwf) ([raw file](https://github.com/sillsdev/web-xforge/blob/2a425e4ce405a26d70940d7b6d39a043546e23d4/src/RealtimeServer/common/services/project-data-service.spec.ts#L337)):*
> ```XML
>       num: {
>         bsonType: 'int'
>       },
> ```

I'm not quite sure what this num property refers to. I think of project data as being questions and note threads, so where does this num property appear?



_Code quote:_
```XML
      num: {
        bsonType: 'int'
      },
```
___
*[`src/RealtimeServer/common/services/user-service.ts` line 74 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-NbzN_2GDWCeUUh_Wt2r:-NcP72zI6Y2vigzqn-qX:b-8ix24r) ([raw file](https://github.com/sillsdev/web-xforge/blob/d894ff58ca293c508ac291700ebe51de1ba2f682/src/RealtimeServer/common/services/user-service.ts#L74)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

This case is handled as `UserService.setCurrentProjectId()` unsets this property if a null value is specified. We only need to have `['null', 'string']` if a property is explicitly set to null.
</blockquote></details>

Ok, that's right, we never actually set the value to null.
___
*[`src/RealtimeServer/common/services/user-service.ts` line 112 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-NbzNu9fBJUzGXKSgBaT:-NcP7E4pD9dPa59shHMm:bjp21xa) ([raw file](https://github.com/sillsdev/web-xforge/blob/d894ff58ca293c508ac291700ebe51de1ba2f682/src/RealtimeServer/common/services/user-service.ts#L112)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Good idea. I have added static validation schemas to `DocService` and `ProjectDataService`, and modified the services that inherit from these reuse the validation schema properties.

JSON Schemas don't support inheritance, but this approach should suffice?
</blockquote></details>

Oh, yes I see that if there is no inheritance why you did it the way you did. But your solution looks good, and I think it will be easier to follow with fewer properties explicitly listed.
___
*[`src/RealtimeServer/scriptureforge/services/note-thread-service.ts` line 97 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-NbzQQRPB-QlVdAvmsIw:-NcP7ZFy-2YYQCY64sSk:bwm68mx) ([raw file](https://github.com/sillsdev/web-xforge/blob/d894ff58ca293c508ac291700ebe51de1ba2f682/src/RealtimeServer/scriptureforge/services/note-thread-service.ts#L97)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

No problem - removed (it was included because note inherits from comment, which has this property).
</blockquote></details>

Oh, yes I see now. Thanks for looking into that.
___
*[`src/RealtimeServer/scriptureforge/services/question-service.ts` line 25 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-NbzRcMQDFAvyEgw-X7h:-NcP7iKH4wk7L6fMhrOS:b-jzx7lg) ([raw file](https://github.com/sillsdev/web-xforge/blob/d894ff58ca293c508ac291700ebe51de1ba2f682/src/RealtimeServer/scriptureforge/services/question-service.ts#L25)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Yes, that is correct - deleted objects just have these properties. Most (maybe all?) collections will have deleted objects like this, because of objects being deleted on sync, etc.
</blockquote></details>

Ok, good to know.
___
*[`src/RealtimeServer/scriptureforge/services/sf-project-service.ts` line 56 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-NbzSzZJ0BUlg_phGUhy:-NcP7u_G47k4FWe1e2xC:b-dijf9t) ([raw file](https://github.com/sillsdev/web-xforge/blob/d894ff58ca293c508ac291700ebe51de1ba2f682/src/RealtimeServer/scriptureforge/services/sf-project-service.ts#L56)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

It took a while for me to figure out the best place for the schema. I originally wanted it as meta data to the model, but that was not practical. Having it as a separate property to the model also made the model a bit complex, where currently these are quite streamlined. Also, the inheritance in the models could make it a bit more complex to maintain?

I decided on putting them in the service, as we have other metadata (i.e. immutable properties, projections, and permissions) defined here.
</blockquote></details>

I'm glad for it to be in the service, you are right that we also keep other metadata in those files, so that is good.


<!-- Sent from Reviewable.io -->

2023-08-21 22:56 UTC, pmachapman reviewed
Thank you for the recreation steps.

The first error is from the Realtime Server, blocking the op:
![image.png](https://files.reviewableusercontent.io/images/reviewable/8665431/Xtru6E3nMdbItEuGZDij1_hP/image.png)
It is a bit technical as it is really designed for us to figure out what has gone wrong.

The error reappears on refresh because it is still a pending op, and ShareDB is trying to send it again:
![image copy 1.png](https://files.reviewableusercontent.io/images/reviewable/8665431/gELaG9JZCJUVVysyRDGzjMVf/image.png)

I am not sure what we can do to stop this, as it appears to be ShareDB working by design?

Logging out then in again would fix this error.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-:-NcPHJ0iE3K7dB60N9oq:b-8gp5gq)* status: all files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[`scripts/db_tools/validate-data.ts` line 108 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-NcP5D4l40CZ0qmC7OJa:-NcPFLG9Bc8qPolPGGos:bfc3hct) ([raw file](https://github.com/sillsdev/web-xforge/blob/2a425e4ce405a26d70940d7b6d39a043546e23d4/scripts/db_tools/validate-data.ts#L108)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

boolean should actually be lowercase for the primitive type.
</blockquote></details>

Thank you! Fixed.
___
*[`src/RealtimeServer/common/services/project-data-service.spec.ts` line 337 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-NcP6XZZ3z1ePtVR7Srw:-NcPF_924NmC7MHiHhU9:b473qz0) ([raw file](https://github.com/sillsdev/web-xforge/blob/2a425e4ce405a26d70940d7b6d39a043546e23d4/src/RealtimeServer/common/services/project-data-service.spec.ts#L337)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I'm not quite sure what this num property refers to. I think of project data as being questions and note threads, so where does this num property appear?
</blockquote></details>

`num` is in the `TestData`, `TestSubData`, and `TestSubSubData` classes used in this spec file (and so why I have only declared this schema in this file).


<!-- Sent from Reviewable.io -->

2023-08-22 15:51 UTC, RaymondLuong3 reviewed
This is probably OK since we are dealing with an edge case and we do not expect users to run into this issue with any consistency. I am happy to merge this, but I would open another issue to gracefully handle the situation when a user does try to submit an op that is invalid. At a minimum, we can tell the user what happened and instruct them to log out.

To deploy this code, are you thinking of pushing this to QA and running the tool to validate the DB? Then we have it active on QA for a time to test? I think you are right that it is probably best to disable it on live for a time, but how will we know if users are creating invalid ops if they aren't validated and reported?

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-:-NcSuUJE7A86Zldutc2m:b-r2chsa)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

___
*[`src/RealtimeServer/common/services/project-data-service.spec.ts` line 337 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-NcP6XZZ3z1ePtVR7Srw:-NcSuRd2ErEHcWMiRMpl:b12p8mj) ([raw file](https://github.com/sillsdev/web-xforge/blob/2a425e4ce405a26d70940d7b6d39a043546e23d4/src/RealtimeServer/common/services/project-data-service.spec.ts#L337)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

`num` is in the `TestData`, `TestSubData`, and `TestSubSubData` classes used in this spec file (and so why I have only declared this schema in this file).
</blockquote></details>

Nice, good to know.


<!-- Sent from Reviewable.io -->

2023-08-22 19:44 UTC, pmachapman reviewed
> To deploy this code, are you thinking of pushing this to QA and running the tool to validate the DB?

Yes. I do not have access to QA to run it myself, so will need help to do this.

>Then we have it active on QA for a time to test?

Yes - monitoring errors in bugsnag during this period.

> but how will we know if users are creating invalid ops if they aren't validated and reported?

I don't imaging this period of time will be for too long - perhaps a month or two. We will monitor by validating the database at semi-regular intervals (maybe once every two weeks or month).

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-:-NcTl-PaC0MuR7XW15tE:b-a98fmg)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)



<!-- Sent from Reviewable.io -->

2023-08-22 21:10 UTC, RaymondLuong3 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> Let's get it to the testers. Can you add acceptance tests for the Jira card.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1746#-:-NcU4CGbBzSRgD-Qqqvt:bllovh1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)



<!-- Sent from Reviewable.io -->

2023-08-27 23:56 UTC, merged