SF-1932 - Store updated avatar URL in Auth0 user metadata
sillsdev/web-xforge pull request #1772
Opened 2023-03-28 23:09 UTC by nigel-wells

- Save any update to the Avatar URL (picture) in the user metadata in Auth0
- On receiving the user profile from Auth0, use the picture value from metadata if available
- Update presence information when the user doc changes
- Added return types
- Added a user doc to various tests that use the text component

2023-03-30 02:28 UTC, pmachapman requested changes
Looks good. Thank you for cleaning up the TypeScript warnings and removing deadwood as you were updating. Just one comment on a bit I found confusing.

2023-03-30 02:28 UTC, pmachapman commented on src/SIL.XForge/Services/UserService.cs
> +                string picture =
I found this block a little confusing on first glance (I had to double take to figure out what it was doing). One way you could make this more readable is to simplify this line as follows:
```csharp
string picture = (string)userProfile["user_metadata"]?["picture"];
```

2023-04-02 23:03 UTC, nigel-wells reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1772)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`src/SIL.XForge/Services/UserService.cs` line 72 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1772#-NReTw0JdiGwA23GEj-D-r1-72:-NS3C3H2A1Ylf0Yy8YBw:b69u4km) ([raw file](https://github.com/sillsdev/web-xforge/blob/d64a6981f95dc4083ddb64a7d232c3bf1e9f2828/src/SIL.XForge/Services/UserService.cs#L72)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

I found this block a little confusing on first glance (I had to double take to figure out what it was doing). One way you could make this more readable is to simplify this line as follows:
```csharp
string picture = (string)userProfile["user_metadata"]?["picture"];
```
</blockquote></details>

Ah neat, didn't realise we could do null checks like that. Does this same approach work for anything in C#? I assume it would work with more dimensions i.e. `(string)userProfile["user_metadata"]?["picture"]?["url"];` ?


<!-- Sent from Reviewable.io -->

2023-04-02 23:11 UTC, pmachapman approved these changes
> Reviewed 8 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1772)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/SIL.XForge/Services/UserService.cs` line 72 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1772#-NReTw0JdiGwA23GEj-D-r1-72:-NS3CjJG3ISfisz42vgE:b-p4x4wl) ([raw file](https://github.com/sillsdev/web-xforge/blob/d64a6981f95dc4083ddb64a7d232c3bf1e9f2828/src/SIL.XForge/Services/UserService.cs#L72)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Ah neat, didn't realise we could do null checks like that. Does this same approach work for anything in C#? I assume it would work with more dimensions i.e. `(string)userProfile["user_metadata"]?["picture"]?["url"];` ?
</blockquote></details>

It works for anything that is nullable in C# (strings, objects, etc...). And yes, it works multiple levels deep.


<!-- Sent from Reviewable.io -->

2023-04-05 02:28 UTC, merged