SF-1917 Add reviewer name to note thread in PT
sillsdev/web-xforge pull request #1791
Opened 2023-04-19 19:37 UTC by RaymondLuong3

* get usernames from user ids from the user service
* add the SF user label to comments when pushing to PT
* interpret comment and note changes accounting for the note label

This change introduces the reviewer label to comments created in SF by users who do not have a paratext role on the project. Each time an admin or translator does a sync, the content of the SF note will be compared to the equivalent comment content in PT. This is a string comparison that interprets the strings with or without SF reviewer labels when needed.

2023-05-02 03:06 UTC, pmachapman requested changes
Looks good - just some minor points of feedback.

> Reviewed 1 of 7 files at r1, 1 of 1 files at r2, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1791#-:-NUPQAmr-h_iJbwN53pc:bvrs2ut)* status: all files reviewed, 12 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 78 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1791#-NUPMJDn53YYSzJym35Y:-NUPMJDn53YYSzJym35Z:b-7qhx2j) ([raw file](https://github.com/sillsdev/web-xforge/blob/1d0b850d9539b23ff915801de21188e7afbd75b6/src/SIL.XForge.Scripture/Services/ParatextService.cs#L78)):*
I ran this Regex against my Paratext projects, and it threw up a couple of false positives in note contents, such as:

> [it should not say "invisible spiritual body" - as Christ's body was certainly visible after the resurrection]

We could tighten up the regular expression by making it more like the COMMENTER_LABEL_REGEX regular expression in SF-1917, and anchor it to the start and end of the string (as it looks like you are using the regular expression against the inner text of the p tag):

`^\[[^\]]+\s-\s[^\]]+\]$`

You should also change the declaration to be a `private const string`, which makes the compiler more efficient at using this value.
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 2409 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1791#-NUPOcki1obaNLuGWkyY:-NUPOcki1obaNLuGWkyZ:b15f0v5) ([raw file](https://github.com/sillsdev/web-xforge/blob/1d0b850d9539b23ff915801de21188e7afbd75b6/src/SIL.XForge.Scripture/Services/ParatextService.cs#L2409)):*
> ```Smalltalk
>             XNode node = elem.FirstNode;
>             // check if the text matches the note label format
>             if (node is XText text && Regex.IsMatch(text.Value, SF_USER_LABEL_REGEX))
> ```

You could speed up the execution of this Regex by making it a compiled regex:
```csharp
Regex.IsMatch(text.Value, SF_USER_LABEL_REGEX, RegexOptions.Compiled)
```
This will speed up execution every time this is run, at the cost of a very slight cost when SF first runs.
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs` line 921 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1791#-NUPPhLtB4g-kiEGqkWE:-NUPPhLtB4g-kiEGqkWF:buqmoxr) ([raw file](https://github.com/sillsdev/web-xforge/blob/1d0b850d9539b23ff915801de21188e7afbd75b6/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L921)):*
> ```Smalltalk
>             ptProjectUsers
>         );
>         // Assert.That(changes.Count, Is.EqualTo(8));
> ```

Should we delete this line instead of commenting it out?
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs` line 1616 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1791#-NUPPwW_-SVqGQgSmgh3:-NUPPwWaBU_KtyF6VRYP:b62ce0s) ([raw file](https://github.com/sillsdev/web-xforge/blob/1d0b850d9539b23ff915801de21188e7afbd75b6/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L1616)):*
> ```Smalltalk
>         );
> 
>         // TODO: Give thread 06 to user05
> ```

Is this a TODO you still want to do?


<!-- Sent from Reviewable.io -->

2023-05-02 15:51 UTC, RaymondLuong3 commented on src/SIL.XForge.Scripture/Services/ParatextService.cs
> +                        comment.Contents.InnerXml = xml;
Dismissing alert as a false alert.

2023-05-02 17:40 UTC, RaymondLuong3 reviewed
Ok, I think it should be up to date now. Thanks for your suggestions.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1791#-:-NUSY6BX55NUoFjkuWJv:b-gte6ip)* status: all files reviewed, 12 unresolved discussions (waiting on @github-code-scanning[bot], @Nateowami, and @pmachapman)

___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 2220 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1791#gh-1171786431:-NUSX-JZ6-04uAw8wmWe:bjsexub) ([raw file](https://github.com/sillsdev/web-xforge/blob/4e00f7fd2d87015d8c55fbe516c7299a4c4da3bc/src/SIL.XForge.Scripture/Services/ParatextService.cs#L2220)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Dereferenced variable may be null

Variable [comment.Contents](1) may be null at this access as suggested by [this](2) null check.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/502)
</blockquote></details>

False positive.
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 2399 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1791#gh-1171786427:-NUSXtMt9JY0fLr8EM4r:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/4e00f7fd2d87015d8c55fbe516c7299a4c4da3bc/src/SIL.XForge.Scripture/Services/ParatextService.cs#L2399)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Nested 'if' statements can be combined

These 'if' statements can be combined.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/501)
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 2406 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1791#gh-1171786420:-NUSXtwFDGAENzonWpEm:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/4e00f7fd2d87015d8c55fbe516c7299a4c4da3bc/src/SIL.XForge.Scripture/Services/ParatextService.cs#L2406)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Redundant ToString() call

Redundant call to 'ToString' on a String object.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/499)
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 2226 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1791#gh-1179421019:-NUSX449BqAoGhXy7WYH:bjsexub) ([raw file](https://github.com/sillsdev/web-xforge/blob/cab7fda6ef9835024d3e229ca8f3c1b488316bd0/src/SIL.XForge.Scripture/Services/ParatextService.cs#L2226)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Dereferenced variable may be null

Variable [comment.Contents](1) may be null at this access as suggested by [this](2) null check.
Variable [comment.Contents](1) may be null at this access as suggested by [this](3) null check.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/504)
</blockquote></details>

False positive.
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 78 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1791#-NUPMJDn53YYSzJym35Y:-NUSBULTCfZxtpdzhOug:brxmqbl) ([raw file](https://github.com/sillsdev/web-xforge/blob/1d0b850d9539b23ff915801de21188e7afbd75b6/src/SIL.XForge.Scripture/Services/ParatextService.cs#L78)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

I ran this Regex against my Paratext projects, and it threw up a couple of false positives in note contents, such as:

> [it should not say "invisible spiritual body" - as Christ's body was certainly visible after the resurrection]

We could tighten up the regular expression by making it more like the COMMENTER_LABEL_REGEX regular expression in SF-1917, and anchor it to the start and end of the string (as it looks like you are using the regular expression against the inner text of the p tag):

`^\[[^\]]+\s-\s[^\]]+\]$`

You should also change the declaration to be a `private const string`, which makes the compiler more efficient at using this value.
</blockquote></details>

Good thinking to check that. I think anchoring the text to the start and end will be useful and hopefully eliminate matching the majority of false positive cases.
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 2382 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1791#gh-1180806899:-NUSXeDAELXYB6iErHR5:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/1d0b850d9539b23ff915801de21188e7afbd75b6/src/SIL.XForge.Scripture/Services/ParatextService.cs#L2382)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Redundant ToString() call

Redundant call to 'ToString' on a String object.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/506)
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 2409 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1791#-NUPOcki1obaNLuGWkyY:-NUSXejw3FasARPGAO87:b-hq3azl) ([raw file](https://github.com/sillsdev/web-xforge/blob/1d0b850d9539b23ff915801de21188e7afbd75b6/src/SIL.XForge.Scripture/Services/ParatextService.cs#L2409)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

You could speed up the execution of this Regex by making it a compiled regex:
```csharp
Regex.IsMatch(text.Value, SF_USER_LABEL_REGEX, RegexOptions.Compiled)
```
This will speed up execution every time this is run, at the cost of a very slight cost when SF first runs.
</blockquote></details>

Good thinking. I didn't realize that was an option.
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 2417 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1791#gh-1180806902:-NUSXuI-3QbqF2gwlzHP:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/1d0b850d9539b23ff915801de21188e7afbd75b6/src/SIL.XForge.Scripture/Services/ParatextService.cs#L2417)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Redundant ToString() call

Redundant call to 'ToString' on a String object.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/507)
</blockquote></details>

Done.
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs` line 3626 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1791#gh-1171786424:-NUSY4ckERQs1sJgWFyw:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/4e00f7fd2d87015d8c55fbe516c7299a4c4da3bc/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L3626)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Missed 'readonly' opportunity

Field 'usernames' can be 'readonly'.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/500)
</blockquote></details>

Done.
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs` line 921 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1791#-NUPPhLtB4g-kiEGqkWE:-NUSXxiN1_9PDV9Xf_z3:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/1d0b850d9539b23ff915801de21188e7afbd75b6/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L921)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Should we delete this line instead of commenting it out?
</blockquote></details>

Done.
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs` line 1616 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1791#-NUPPwW_-SVqGQgSmgh3:-NUSXzbZ0YXRW2EvbyGQ:bw1l15s) ([raw file](https://github.com/sillsdev/web-xforge/blob/1d0b850d9539b23ff915801de21188e7afbd75b6/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L1616)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></ [...]

2023-05-02 17:57 UTC, pmachapman approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1791#-:-NUSaa848MUxHoF6bYQQ:bnfp4nl)* status: all files reviewed, 8 unresolved discussions (waiting on @github-code-scanning[bot] and @Nateowami)



<!-- Sent from Reviewable.io -->

2023-05-02 22:11 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1791)* status: all files reviewed, 8 unresolved discussions (waiting on @github-code-scanning[bot])

___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 78 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1791#-NUPMJDn53YYSzJym35Y:-NUTV6zn9Tn9keQveRuH:bn6jf77) ([raw file](https://github.com/sillsdev/web-xforge/blob/1d0b850d9539b23ff915801de21188e7afbd75b6/src/SIL.XForge.Scripture/Services/ParatextService.cs#L78)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Good thinking to check that. I think anchoring the text to the start and end will be useful and hopefully eliminate matching the majority of false positive cases.
</blockquote></details>

Can we not do something like:
``` csharp
var labelElement = new XElement("p", label);
labelElement.SetAttributeValue("class", "sf-user-label");
contentElem.Add(labelElement);
```
So we don't need to use regexs to identify which element has the label?


<!-- Sent from Reviewable.io -->

2023-05-03 23:45 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1791)* status: 5 of 7 files reviewed, 8 unresolved discussions (waiting on @github-code-scanning[bot] and @pmachapman)

___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 78 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1791#-NUPMJDn53YYSzJym35Y:-NUZ--HT8_QrdtmRv6Ww:b-rzgx3b) ([raw file](https://github.com/sillsdev/web-xforge/blob/1d0b850d9539b23ff915801de21188e7afbd75b6/src/SIL.XForge.Scripture/Services/ParatextService.cs#L78)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Excellent idea! I knew there had to be a more robust way. Thanks for the suggestion.
</blockquote></details>

@pmachapman Is adding a class the XML way of doing this? Or should it be a boolean property or something? It probably doesn't make that much of a deal, but there's a decent chance whatever we start doing here we'll start doing elsewhere.


<!-- Sent from Reviewable.io -->

2023-05-08 20:27 UTC, pmachapman commented
> > _[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1791)_ status: 5 of 7 files reviewed, 8 unresolved discussions (waiting on @github-code-scanning[bot] and @pmachapman)
> 
> _[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 78 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1791#-NUPMJDn53YYSzJym35Y:-NUZ--HT8_QrdtmRv6Ww:b-rzgx3b) ([raw file](https://github.com/sillsdev/web-xforge/blob/1d0b850d9539b23ff915801de21188e7afbd75b6/src/SIL.XForge.Scripture/Services/ParatextService.cs#L78)):_
> 
> Previously, RaymondLuong3 (Raymond Luong) wrote…
> @pmachapman Is adding a class the XML way of doing this? Or should it be a boolean property or something? It probably doesn't make that much of a deal, but there's a decent chance whatever we start doing here we'll start doing elsewhere.

Reviewable isn't working for me today, so I will answer here.

If this is not specifically formatting information, a better way would probably be to use an HTML data attribute, like `<p data-sf-user-label="true">[SF User - xforge]</p>`. [HTML data attributes](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes) are useful particularly if you will be adding other types of information (i.e. it gets confusing to parse something like `<p class="sf-user-label sf-hidden sf-exported">` in an XDocument - `<p data-sf-user-label="true" data-sf-exported="true" data-sf-hidden="true"></p>` is easier to parse in C#).

If the class is to be used for formatting, it will be perfectly fine to stay as a class of course.

My general rule of thumb is it if it used to formatting/presentation, use regular HTML attributes. If it is for my own custom parsing, use data attributes.

2023-05-08 20:59 UTC, RaymondLuong3 commented
Thanks for that insight on when we should use custom data attributes. That makes sense to me. I have made the chances according to what you have suggested.

2023-05-08 22:30 UTC, merged