log: record ParatextData errors during SendReceive
sillsdev/web-xforge pull request #1807
Opened 2023-04-27 19:51 UTC by marksvc

- ParatextData outputs messages using Trace and Alert. Capture these
to SyncMetrics.
- Bump up alert logging to Error level so errors also make their way
thru to the console output.
- May help investigate SF-1968 sync problem.

commit-id:8cda5d8e

2023-04-27 19:56 UTC, marksvc commented
Steps to test:
- Synchronize a project.
- It should not crash or anything like that :)
- If you look in the MongoDB sync_metrics collection, and search for projectRef docs with your sfproject id, the last one's log should now include some lines beginning with "Trace:".

2023-04-27 20:54 UTC, marksvc commented
There is some trouble with messages getting to the right place. Converting to draft.

2023-04-27 23:22 UTC, marksvc commented
If ParatextService.cs looks like a big diff, try ignoring whitespace at the beginning of lines.

2023-04-28 22:47 UTC, RaymondLuong3 requested changes
Is this trying to get sync metrics data logged when errors occur in Paratext Data? I like that this will get those messages logged in a useable way.

> Reviewed 4 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1807#-:-NU91LBj0wjz_jw26Lyx:b-1dcy8b)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @github-code-scanning[bot] and @marksvc)

___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 152 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1807#-NU9-FWa2DnO3HxBrGfI:-NU9-FWa2DnO3HxBrGfJ:b-ab92i2) ([raw file](https://github.com/sillsdev/web-xforge/blob/b6a8139bcd9b3f8d163ccfe4e4bce157a02adab2/src/SIL.XForge.Scripture/Services/ParatextService.cs#L152)):*
> ```Smalltalk
>     public void Init()
>     {
>         System.Diagnostics.Trace.AutoFlush = true;
> ```

Did you mean to uncomment this?



_Code quote:_
```Smalltalk
  System.Diagnostics.Trace.AutoFlush = true;
```
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 196 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1807#-NU911yt8G5-4zneiP6F:-NU911yt8G5-4zneiP6G:box8kmz) ([raw file](https://github.com/sillsdev/web-xforge/blob/b6a8139bcd9b3f8d163ccfe4e4bce157a02adab2/src/SIL.XForge.Scripture/Services/ParatextService.cs#L196)):*
> ```Smalltalk
> 
>         LambdaTraceListener listener = new LambdaTraceListener(traceListener);
>         try
> ```

Nit: You could move the try below the null checks here.



_Code quote:_
```Smalltalk
        try
        {
```
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 204 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1807#-NU9211P4pEXyzngHk1K:-NU9211P4pEXyzngHk1L:b-l2jj9l) ([raw file](https://github.com/sillsdev/web-xforge/blob/b6a8139bcd9b3f8d163ccfe4e4bce157a02adab2/src/SIL.XForge.Scripture/Services/ParatextService.cs#L204)):*
> ```Smalltalk
> 
>             // Messages from ParatextData Hg.cs and SharingLogic HandleErrors() go to Trace and Alert. Record them into
>             // each sync's SyncMetrics log. This will also unfortunately capture trace and alert messages from other
> ```

Does this mean that sync of different projects might get recorded? Is it because ParatextService is a singleton?



_Code quote:_
```Smalltalk
            // each sync's SyncMetrics log. This will also unfortunately capture trace and alert messages from other
            // irrelevant syncs or areas at the same time, along with the desired information. These internal messages,
```


<!-- Sent from Reviewable.io -->

2023-05-02 15:14 UTC, marksvc reviewed
Yes! 

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1807#-:-NUS0t_f2rAqlSzYWCOD:b-7xt2v3)* status: 4 of 7 files reviewed, 3 unresolved discussions (waiting on @github-code-scanning[bot] and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 75 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1807#gh-1179796173:-NURz6s7DB5WKCnlcP1T:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/b6a8139bcd9b3f8d163ccfe4e4bce157a02adab2/src/SIL.XForge.Scripture/Services/ParatextService.cs#L75)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Missed 'readonly' opportunity

Field '_alertSystem' can be 'readonly'.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/505)
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 152 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1807#-NU9-FWa2DnO3HxBrGfI:-NURzKLOD2oZjVn_nkCf:b9wa0ho) ([raw file](https://github.com/sillsdev/web-xforge/blob/b6a8139bcd9b3f8d163ccfe4e4bce157a02adab2/src/SIL.XForge.Scripture/Services/ParatextService.cs#L152)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Did you mean to uncomment this?
</blockquote></details>

Thank you. Yes, it seemed like it might help the error messages be promptly written to our logs. I did not test what buffering, delay, or out-of-order situations might happen without it.
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 196 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1807#-NU911yt8G5-4zneiP6F:-NURzu2m0BlFiyYzOMgj:b-d1vxpx) ([raw file](https://github.com/sillsdev/web-xforge/blob/b6a8139bcd9b3f8d163ccfe4e4bce157a02adab2/src/SIL.XForge.Scripture/Services/ParatextService.cs#L196)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Nit: You could move the try below the null checks here.
</blockquote></details>

Right. I have moved the null checking to the beginning of the method.
___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 204 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1807#-NU9211P4pEXyzngHk1K:-NUS-FKoDy2FHcsVxPzz:booe25z) ([raw file](https://github.com/sillsdev/web-xforge/blob/b6a8139bcd9b3f8d163ccfe4e4bce157a02adab2/src/SIL.XForge.Scripture/Services/ParatextService.cs#L204)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Does this mean that sync of different projects might get recorded? Is it because ParatextService is a singleton?
</blockquote></details>

Yes, unrelated project messages or errors will end up in the syncmetrics. I don't think it's because our services are singletons, but rather since (1) we can use ParatextData for multiple activities at the same time, and (2) ParatextData reports errors and diagnostics via a global logging mechanism that is not tied to a particular activity. So when ParatextData calls Alert.Show or writes to Trace, we don't know if it is from a particular activity that we are interested in or another one (or at least I haven't seen how to do that yet). And so unrelated project sync info from ParatextData would get recorded.

This does have an upside: Because our ParatextData does do different things at the same time, which could conceivably interfere with one another if our multi-user modifications aren't perfect, it may actually be useful to see some of these other project messages in SyncMetrics. (Tho I would rather them be separated out if it were easy.)

Peter and I noted that running separate ParatextData processes for each sync would allow us to isolate messages to a given sync. 


<!-- Sent from Reviewable.io -->

2023-05-02 15:44 UTC, RaymondLuong3 requested changes
I can see the Trace messages from within the send/receive process in Paratext Data

> Reviewed 2 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1807#-:-NUS6SOsEympW3s1ZOxd:b-w1e9t4)* status: all files reviewed, 2 unresolved discussions (waiting on @github-code-scanning[bot] and @marksvc)

___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 204 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1807#-NU9211P4pEXyzngHk1K:-NUS6fMAD6N6rYaTWI1S:b-bid4qx) ([raw file](https://github.com/sillsdev/web-xforge/blob/b6a8139bcd9b3f8d163ccfe4e4bce157a02adab2/src/SIL.XForge.Scripture/Services/ParatextService.cs#L204)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Yes, unrelated project messages or errors will end up in the syncmetrics. I don't think it's because our services are singletons, but rather since (1) we can use ParatextData for multiple activities at the same time, and (2) ParatextData reports errors and diagnostics via a global logging mechanism that is not tied to a particular activity. So when ParatextData calls Alert.Show or writes to Trace, we don't know if it is from a particular activity that we are interested in or another one (or at least I haven't seen how to do that yet). And so unrelated project sync info from ParatextData would get recorded.

This does have an upside: Because our ParatextData does do different things at the same time, which could conceivably interfere with one another if our multi-user modifications aren't perfect, it may actually be useful to see some of these other project messages in SyncMetrics. (Tho I would rather them be separated out if it were easy.)

Peter and I noted that running separate ParatextData processes for each sync would allow us to isolate messages to a given sync. 
</blockquote></details>

Hmm, that is kind of unfortunate, but we will see if that becomes confusing. And I imagine there is no way to indicate which project a log message belongs to. Actually, it looks like you can add some text to indicate the project that is being synced when you set up the LamdaTraceListener. What do you think about that?


<!-- Sent from Reviewable.io -->

2023-05-02 16:26 UTC, marksvc reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1807)* status: all files reviewed, 2 unresolved discussions (waiting on @github-code-scanning[bot] and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 204 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1807#-NU9211P4pEXyzngHk1K:-NUSH9t7AeXdgn2PdZoS:b-rbhtho) ([raw file](https://github.com/sillsdev/web-xforge/blob/b6a8139bcd9b3f8d163ccfe4e4bce157a02adab2/src/SIL.XForge.Scripture/Services/ParatextService.cs#L204)):*
So, the thing about that is that during each sync, each sync's TraceListener, and alert listener, will listen to all Trace and Alert messages. So we could have each listener include the sf project id, like

> 2023-05-02: When syncing sfproject 6123456789000, this Trace message came: ....

But it wouldn't mean that the message is actually related to the project. And in fact, all trace listeners would record the same message, but with their own sfproject id pre-pended, to their own syncmetrics :). So if we have two syncs at the same time, and ParatextData gives an alert saying "File locking error", we will have one syncmetrics that says

> 2023-05-02: When syncing sfproject 4444444444, this Trace message came: File locking error.

and another syncmetrics that says

> 2023-05-02: When syncing sfproject 5555555555, this Trace message came: File locking error.

And neither of them would actually be telling us which project the message was associated with :)


<!-- Sent from Reviewable.io -->

2023-05-02 17:21 UTC, RaymondLuong3 approved these changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1807)* status: all files reviewed, 1 unresolved discussion (waiting on @github-code-scanning[bot])

___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 204 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1807#-NU9211P4pEXyzngHk1K:-NUSTwIC5iIley_Q4n39:b-yktn7g) ([raw file](https://github.com/sillsdev/web-xforge/blob/b6a8139bcd9b3f8d163ccfe4e4bce157a02adab2/src/SIL.XForge.Scripture/Services/ParatextService.cs#L204)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

So, the thing about that is that during each sync, each sync's TraceListener, and alert listener, will listen to all Trace and Alert messages. So we could have each listener include the sf project id, like

> 2023-05-02: When syncing sfproject 6123456789000, this Trace message came: ....

But it wouldn't mean that the message is actually related to the project. And in fact, all trace listeners would record the same message, but with their own sfproject id pre-pended, to their own syncmetrics :). So if we have two syncs at the same time, and ParatextData gives an alert saying "File locking error", we will have one syncmetrics that says

> 2023-05-02: When syncing sfproject 4444444444, this Trace message came: File locking error.

and another syncmetrics that says

> 2023-05-02: When syncing sfproject 5555555555, this Trace message came: File locking error.

And neither of them would actually be telling us which project the message was associated with :)

</blockquote></details>

Ok, that makes sense. Thanks.


<!-- Sent from Reviewable.io -->

2023-05-02 17:22 UTC, merged