Create simplified navigation sidebar
sillsdev/web-xforge pull request #1825
Opened 2023-05-05 04:29 UTC by Nateowami

2023-09-11 01:46 UTC, nigel-wells requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1825)* status: 0 of 26 files reviewed, 1 unresolved discussion (waiting on @Nateowami)

*[a discussion](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Ne0tmTxErqI6ZEi-0Pw:-Ne0tmTxErqI6ZEi-0Px:bhuabf3) (no related file):*
To be clear, this PR is only focused on the nav bar and not addressing any issues that are created from the new nav bar i.e. community checking app, if you only have questions in Matthew, and then you add a question to John, you can't access that new question until you leave community checking and then come back in so that you see ALL the questions. 

It would be fine if they were different cards but then it raises questions around when this branch should get merged in if we know it is going to cause issues with other parts? Perhaps we should put it behind a feature flag which should be easy with you refactoring into a dedicated component now.

___


<!-- Sent from Reviewable.io -->

2023-09-11 03:28 UTC, nigel-wells requested changes
> Reviewed 4 of 24 files at r1, 20 of 22 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1825)* status: 24 of 26 files reviewed, 21 unresolved discussions (waiting on @Nateowami)

*[a discussion](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Ne1Dk6HBcjYtiErD2nF:-Ne1Dk6HBcjYtiErD2nG:b-ljhbz4) (no related file):*
I'm in two minds about having no Karma tests written and only having stories. For a large number of them, stories work fine. There are some which could probably be stories but I'm not sold on it? Perhaps it just needs more steps to be added? One example is "add spin class to sync icon when in progress" which has two expectations - the first is that the spinner turns on when a sync starts and then the spinner turns off when the sync finishes. The story at the moment just shows a spinner and no context as to how that gets set. Are we losing coverage by just writing stories?

___
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 234 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Ne15SCECBbL_G0vVxYw:-Ne15SCECBbL_G0vVxYx:b-ljv4aa) ([raw file](https://github.com/sillsdev/web-xforge/blob/fb7d717b27a1f1cb61d880aaeb323083d4f39324/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L234)):*
> ```XML
>   }
> 
>   get hasSingleAppEnabled(): boolean {
> ```

This is no longer used
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 268 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Ne15_Dl9XgWsweLPU45:-Ne15_Dl9XgWsweLPU46:b-ljv4aa) ([raw file](https://github.com/sillsdev/web-xforge/blob/fb7d717b27a1f1cb61d880aaeb323083d4f39324/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L268)):*
> ```XML
>   }
> 
>   get showAllQuestions(): boolean {
> ```

This is no longer used
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 281 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Ne15k5I716u12iJKDKN:-Ne15k5I716u12iJKDKO:b-ljv4aa) ([raw file](https://github.com/sillsdev/web-xforge/blob/fb7d717b27a1f1cb61d880aaeb323083d4f39324/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L281)):*
> ```XML
>   }
> 
>   get defaultFocusState(): DefaultFocusState {
> ```

This is no longer used
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 503 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Ne15q-73fZpF8xG7mbS:-Ne15q-73fZpF8xG7mbT:b-ljv4aa) ([raw file](https://github.com/sillsdev/web-xforge/blob/fb7d717b27a1f1cb61d880aaeb323083d4f39324/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L503)):*
> ```XML
>   }
> 
>   getBookName(text: TextInfo): string {
> ```

This is no longer used
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 507 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Ne15t5bD_iVkQ12iJvZ:-Ne15t5bD_iVkQ12iJv_:b-ljv4aa) ([raw file](https://github.com/sillsdev/web-xforge/blob/fb7d717b27a1f1cb61d880aaeb323083d4f39324/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L507)):*
> ```XML
>   }
> 
>   getBookId(text: TextInfo): string {
> ```

This is no longer used
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 523 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Ne15xT0DNKfXXZy4JCh:-Ne15xT0DNKfXXZy4JCi:b-ljv4aa) ([raw file](https://github.com/sillsdev/web-xforge/blob/fb7d717b27a1f1cb61d880aaeb323083d4f39324/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L523)):*
> ```XML
>   }
> 
>   get lastSyncFailed(): boolean {
> ```

This is no longer used
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.html` line 2 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Ne12Co14TVUXVtnN7sH:-Ne12Co14TVUXVtnN7sI:bsh55if) ([raw file](https://github.com/sillsdev/web-xforge/blob/fb7d717b27a1f1cb61d880aaeb323083d4f39324/src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.html#L2)):*
> ```HTML
> <ng-container *transloco="let t; read: 'app'">
>   <mat-nav-list id="tools-menu-list" (click)="clickWithinNavList($event)">
> ```

What do you think about the idea of having a menu render array rather than constructing each unique item in the template? This would help future proof it for new apps or functionality we add in the future without having to re-think how to setup the menu correctly i.e. adding in dividers
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.html` line 6 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Ne118mr3mgxoZ6xcgAy:-Ne118mr3mgxoZ6xcgAz:bjzp89b) ([raw file](https://github.com/sillsdev/web-xforge/blob/fb7d717b27a1f1cb61d880aaeb323083d4f39324/src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.html#L6)):*
> ```HTML
>       {{ t("translate") }}
>     </mat-list-item>
>     <div *ngIf="isTranslateEnabled">
> ```

Is there value in this still being in a div container? It was collapsible before but now it is always visible.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.html` line 17 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Ne1-2Io11DKL2HiknjD:-Ne1-2Io11DKL2HiknjE:bks7kn) ([raw file](https://github.com/sillsdev/web-xforge/blob/fb7d717b27a1f1cb61d880aaeb323083d4f39324/src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.html#L17)):*
> ```HTML
>       <a *ngIf="canGenerateDraft" mat-list-item [appRouterLink]="draftGenerationLink">
>         <mat-icon mat-list-icon>edit_note</mat-icon>
>         Generate draft <span class="nav-label">beta</span>
> ```

Provide translated string
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.html` line 24 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Ne11QxG9qI9tsIQeSQ9:-Ne11QxG9qI9tsIQeSQA:b-5leohb) ([raw file](https://github.com/sillsdev/web-xforge/blob/fb7d717b27a1f1cb61d880aaeb323083d4f39324/src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.html#L24)):*
> ```HTML
>       {{ t("community_checking") }}
>     </mat-list-item>
>     <div *ngIf="isCheckingEnabled">
> ```

Same as translate comment above
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.html` line 46 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Ne12jMEDEDRVmpqFQj9:-Ne12jMEDEDRVmpqFQjA:b-2549a9) ([raw file](https://github.com/sillsdev/web-xforge/blob/fb7d717b27a1f1cb61d880aaeb323083d4f39324/src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.html#L46)):*
> ```HTML
>   >
>     <mat-divider></mat-divider>
>     <div *ngIf="canSync$ | async">
> ```

Can this go directly on the `<a...>` below? Same with other admin tasks
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.html` line 52 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Ne13TZR7tOEOtcs7ARe:-Ne13TZR7tOEOtcs7ARf:b-1oo606) ([raw file](https://github.com/sillsdev/web-xforge/blob/fb7d717b27a1f1cb61d880aaeb323083d4f39324/src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.html#L52)):*
> ```HTML
>           matBadge="error"
>           [matBadgeHidden]="!lastSyncFailed || syncInProgress"
>           [class.sync-in-progress]="syncInProgress"
> ```

This is not respecting the stillness feature flag any more?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.scss` line 35 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Ne19PpN6xbLqStrEO-D:-Ne19PpN6xbLqStrEO-E:b1l9mqf) ([raw file](https://github.com/sillsdev/web-xforge/blob/fb7d717b27a1f1cb61d880aaeb323083d4f39324/src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.scss#L35)):*
> ```SCSS
>     background-color: #e7e8e7;
>   }
> }
> ```

Can these be nested in the above rules?



_Code quote:_
```SCSS
.mat-list-item {
  &.activated-nav-item,
  &.ac [...]

2023-09-12 00:12 UTC, Nateowami reviewed
> Reviewed 5 of 24 files at r1, 1 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1825)* status: 18 of 26 files reviewed, 21 unresolved discussions (waiting on @nigel-wells)

*[a discussion](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Ne0tmTxErqI6ZEi-0Pw:-Ne5ZxdfAzXch1Hj6dB6:bnnhe6j) (no related file):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

To be clear, this PR is only focused on the nav bar and not addressing any issues that are created from the new nav bar i.e. community checking app, if you only have questions in Matthew, and then you add a question to John, you can't access that new question until you leave community checking and then come back in so that you see ALL the questions. 

It would be fine if they were different cards but then it raises questions around when this branch should get merged in if we know it is going to cause issues with other parts? Perhaps we should put it behind a feature flag which should be easy with you refactoring into a dedicated component now.
</blockquote></details>

Yes, there are issues elsewhere that are brought up by the new navigation. It's unfortunate how many things have to change at once to make the whole thing work coherently. I'm hoping to merge this about the same time as #2033 and make them work at least OK with each other. 

___
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 234 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Ne15SCECBbL_G0vVxYw:-Ne5BsVa3AEXe5tPs7cm:btx5lkc) ([raw file](https://github.com/sillsdev/web-xforge/blob/fb7d717b27a1f1cb61d880aaeb323083d4f39324/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L234)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

This is no longer used
</blockquote></details>

Thanks for catching all these unused items.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 268 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Ne15_Dl9XgWsweLPU45:-Ne5Byeg7HN2Dpwja2nJ:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/fb7d717b27a1f1cb61d880aaeb323083d4f39324/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L268)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

This is no longer used
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 281 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Ne15k5I716u12iJKDKN:-Ne5C0SwD200frR4flPN:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/fb7d717b27a1f1cb61d880aaeb323083d4f39324/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L281)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

This is no longer used
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 503 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Ne15q-73fZpF8xG7mbS:-Ne5C3_kDcGm0Z3PXT3V:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/fb7d717b27a1f1cb61d880aaeb323083d4f39324/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L503)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

This is no longer used
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 507 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Ne15t5bD_iVkQ12iJvZ:-Ne5C6Xe-ZzjIDk8nOHR:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/fb7d717b27a1f1cb61d880aaeb323083d4f39324/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L507)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

This is no longer used
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 523 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Ne15xT0DNKfXXZy4JCh:-Ne5C9ty1jOA50tBSVXO:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/fb7d717b27a1f1cb61d880aaeb323083d4f39324/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L523)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

This is no longer used
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.html` line 2 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Ne12Co14TVUXVtnN7sH:-Ne5KKz65Yhd7Jdzn-T4:b-e616gy) ([raw file](https://github.com/sillsdev/web-xforge/blob/fb7d717b27a1f1cb61d880aaeb323083d4f39324/src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.html#L2)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

What do you think about the idea of having a menu render array rather than constructing each unique item in the template? This would help future proof it for new apps or functionality we add in the future without having to re-think how to setup the menu correctly i.e. adding in dividers
</blockquote></details>

I did consider that, but I don't think it would actually be that simple. There are a lot of variables. Each page has its own logic for whether it should be shown, it's own icon, translation string, classes, logic for whether it should be highlighted as being active, etc. I think it's easier to reason about written all out in the template.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.html` line 6 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Ne118mr3mgxoZ6xcgAy:-Ne5HLx9EIlo1rfkf1lo:b-przen4) ([raw file](https://github.com/sillsdev/web-xforge/blob/fb7d717b27a1f1cb61d880aaeb323083d4f39324/src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.html#L6)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Is there value in this still being in a div container? It was collapsible before but now it is always visible.
</blockquote></details>

Good point. Not sure why I missed that. I moved them all to the same level, and used an ng-container for the conditional.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.html` line 17 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Ne1-2Io11DKL2HiknjD:-Ne5HzfxCBc8OIle_18L:b7w8pj5) ([raw file](https://github.com/sillsdev/web-xforge/blob/fb7d717b27a1f1cb61d880aaeb323083d4f39324/src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.html#L17)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Provide translated string
</blockquote></details>

The entire draft generation feature has yet to be internationalized. It's also still behind a feature flag. So I think the whole thing can be done at once.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.html` line 24 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Ne11QxG9qI9tsIQeSQ9:-Ne5Hsa70w_Vz0Lozi7m:byhm06n) ([raw file](https://github.com/sillsdev/web-xforge/blob/fb7d717b27a1f1cb61d880aaeb323083d4f39324/src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.html#L24)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Same as translate comment above
</blockquote></details>

Thanks. Moved it to an ng-container as well.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.html` line 46 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Ne12jMEDEDRVmpqFQj9:-Ne5Hf0l0jm5gapD6xnx:b-axzg3o) ([raw file](https://github.com/sillsdev/web-xforge/blob/fb7d717b27a1f1cb61d880aaeb323083d4f39324/src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigati [...]

2023-09-20 04:50 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1825)* status: 17 of 26 files reviewed, 3 unresolved discussions (waiting on @nigel-wells)

*[a discussion](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Ne1Dk6HBcjYtiErD2nF:-NektUEh6UiXARrbrJ7G:bwvtbec) (no related file):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Did you have any thoughts around the tests? I've not reviewed them yet in case you change them based on this discussion.
</blockquote></details>

I keep not responding to this because it would take me a while to write out my thoughts about the tests, but it basically boils down to:

1. What tests are useful generally depends on the unit under test
2. This component has almost no complicated state changes; the project is just updated (by the parent setting a different project), and then everything flows via change detection to the template.

Because of that I've just tried to create tests for as many scenarios as possible, and not tested state changes (since that's not likely to have much value).

Probably the most missing tests are testing what clicking an element would do. It might make sense to assert the href on the links. Then again, that might not be as likely to break.

With regards to your example of the sync icon spinning, and not having a test to show that it gets added and then removed, the code we'd be testing is this:
``` ts
  get syncInProgress(): boolean {
    return this.selectedProjectDoc?.data != null && this.selectedProjectDoc.data.sync.queuedCount > 0;
  }
```
Which has no external state or side effects. I personally think we'd be testing Angular more so than the component. Of course, you could test that the selectedProjectDoc is getting updated when it should, but it's set by the parent component, which wouldn't be in the tests, so it would essentially be testing our tests.

___
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.scss` line 80 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Ne1Auek7eNU8YS4F03N:-NeBSHG30uK-gmKcQ2H4:b-sw6e1d) ([raw file](https://github.com/sillsdev/web-xforge/blob/fb7d717b27a1f1cb61d880aaeb323083d4f39324/src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.scss#L80)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Fair points. I've chatted this over with Jeanna and she suggested we could consider doing something similar to this.
* Left align
* Incorporate the divider line in the heading
* Add more space above headings
![image.png](https://files.reviewableusercontent.io/images/reviewable/17464863/-U8OJnI7ZP3OAJD0EmnoxAw5/image.png)
</blockquote></details>

I like that a lot better. I think that doesn't need to hold up this change though. It's not fundamental.


<!-- Sent from Reviewable.io -->

2023-09-21 03:15 UTC, nigel-wells requested changes
> Reviewed 7 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1825)* status: 24 of 26 files reviewed, 1 unresolved discussion (waiting on @Nateowami)

*[a discussion](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Ne1Dk6HBcjYtiErD2nF:-NepiGZS8x-bW6i1VOGN:b7ogj9b) (no related file):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I keep not responding to this because it would take me a while to write out my thoughts about the tests, but it basically boils down to:

1. What tests are useful generally depends on the unit under test
2. This component has almost no complicated state changes; the project is just updated (by the parent setting a different project), and then everything flows via change detection to the template.

Because of that I've just tried to create tests for as many scenarios as possible, and not tested state changes (since that's not likely to have much value).

Probably the most missing tests are testing what clicking an element would do. It might make sense to assert the href on the links. Then again, that might not be as likely to break.

With regards to your example of the sync icon spinning, and not having a test to show that it gets added and then removed, the code we'd be testing is this:
``` ts
  get syncInProgress(): boolean {
    return this.selectedProjectDoc?.data != null && this.selectedProjectDoc.data.sync.queuedCount > 0;
  }
```
Which has no external state or side effects. I personally think we'd be testing Angular more so than the component. Of course, you could test that the selectedProjectDoc is getting updated when it should, but it's set by the parent component, which wouldn't be in the tests, so it would essentially be testing our tests.
</blockquote></details>

I agree that we need to pick the most appropriate tool for testing depending on what it is. The tests you've written seem fine and it is a very "simple" component in terms of what it does. What I'm not sure about is what will happen to our code coverage if we start removing existing (or avoiding writing) tests in order to write stories. I assume our coverage will slowly start to decrease overtime. I see Storybook can also do coverage reports - it would be great if it could combine with our existing ones?

I don't think this needs to hold up the PR as removing a couple of tests here won't make that big of an impact but it is something we probably need to decide and be clear on with the team.

I'll take a look at reviewing the other files now.

___
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.scss` line 80 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Ne1Auek7eNU8YS4F03N:-NephT_e3LnMkKRU7Ft3:b-tncxur) ([raw file](https://github.com/sillsdev/web-xforge/blob/fb7d717b27a1f1cb61d880aaeb323083d4f39324/src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.scss#L80)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I like that a lot better. I think that doesn't need to hold up this change though. It's not fundamental.
</blockquote></details>

Where should we put comments/thoughts like these so they aren't forgotten? 


<!-- Sent from Reviewable.io -->

2023-09-21 03:27 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1825)* status: 24 of 26 files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

*[a discussion](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Ne1Dk6HBcjYtiErD2nF:-NepldmkD6g5C3EEDeFZ:bbzfske) (no related file):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

I agree that we need to pick the most appropriate tool for testing depending on what it is. The tests you've written seem fine and it is a very "simple" component in terms of what it does. What I'm not sure about is what will happen to our code coverage if we start removing existing (or avoiding writing) tests in order to write stories. I assume our coverage will slowly start to decrease overtime. I see Storybook can also do coverage reports - it would be great if it could combine with our existing ones?

I don't think this needs to hold up the PR as removing a couple of tests here won't make that big of an impact but it is something we probably need to decide and be clear on with the team.

I'll take a look at reviewing the other files now.
</blockquote></details>

Yeah, if we could get it in our code coverage reports that would be great.

___
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.scss` line 80 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Ne1Auek7eNU8YS4F03N:-NepliEYA__2_Coydbm_:bg1nrbf) ([raw file](https://github.com/sillsdev/web-xforge/blob/fb7d717b27a1f1cb61d880aaeb323083d4f39324/src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.scss#L80)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Where should we put comments/thoughts like these so they aren't forgotten?
</blockquote></details>

Probably new issue, or if you want you can try your hand at making the change in this PR itself.


<!-- Sent from Reviewable.io -->

2023-09-28 00:59 UTC, nigel-wells requested changes
> Reviewed 1 of 8 files at r4, 1 of 8 files at r6, 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1825)* status: all files reviewed, 10 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts` line 14 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NfOFNJA69gfTdEjyFI-:-NfOFNJA69gfTdEjyFI0:b-qoli25) ([raw file](https://github.com/sillsdev/web-xforge/blob/907a76fa01ffc5c47431a9cb8967eb81acb80750/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts#L14)):*
> ```XML
> import { createTestUser } from 'realtime-server/lib/esm/common/models/user-test-data';
> import { obj } from 'realtime-server/lib/esm/common/utils/obj-path';
> import { Question, getQuestionDocId } from 'realtime-server/lib/esm/scriptureforge/models/question';
> ```

Unused `getQuestionDocID` once the below methods are removed.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts` line 126 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NfOEBYR498hN8cC2u71:-NfOEBYR498hN8cC2u72:b-vc6zbv) ([raw file](https://github.com/sillsdev/web-xforge/blob/907a76fa01ffc5c47431a9cb8967eb81acb80750/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts#L126)):*
> ```XML
>     expect(env.isDrawerVisible).toEqual(true);
>     expect(env.selectedProjectId).toEqual('project01');
>     // Translate | Overview | Draft & review | Community Checking | My progress | Questions & answers | Synchronize |
> ```

Nit  `My Progress` should be `Manage questions`? Same applies to below comments if this needs correcting. It doesn't effect the test expectations but confused me as to why I wasn't seeing it as an admin :)
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts` line 622 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NfOEt95BMO2lSdwfVik:-NfOEt95BMO2lSdwfVil:b-yrumkl) ([raw file](https://github.com/sillsdev/web-xforge/blob/907a76fa01ffc5c47431a9cb8967eb81acb80750/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts#L622)):*
> ```XML
>   }
> 
>   get syncInProgressClassIsPresent(): boolean {
> ```

Unused
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts` line 627 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NfOEyvtDAPKGaY_qExi:-NfOEyvtDAPKGaY_qExj:b-yrumkl) ([raw file](https://github.com/sillsdev/web-xforge/blob/907a76fa01ffc5c47431a9cb8967eb81acb80750/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts#L627)):*
> ```XML
>   }
> 
>   get lastSyncFailedBadgeIsPresent(): boolean {
> ```

Unused
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts` line 632 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NfOF-T21JSiFoqtJYZR:-NfOF-T21JSiFoqtJYZS:b-yrumkl) ([raw file](https://github.com/sillsdev/web-xforge/blob/907a76fa01ffc5c47431a9cb8967eb81acb80750/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts#L632)):*
> ```XML
>   }
> 
>   getMenuItemText(index: number): string {
> ```

Unused
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts` line 649 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NfOFAGO2JRtlRsmUQ8F:-NfOFAGO2JRtlRsmUQ8G:b-yrumkl) ([raw file](https://github.com/sillsdev/web-xforge/blob/907a76fa01ffc5c47431a9cb8967eb81acb80750/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts#L649)):*
> ```XML
>   }
> 
>   remoteAddQuestion(newQuestion: Question): void {
> ```

Unused
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts` line 664 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NfOFBZ_6obbMtC0_Dmf:-NfOFBZ_6obbMtC0_Dmg:b-yrumkl) ([raw file](https://github.com/sillsdev/web-xforge/blob/907a76fa01ffc5c47431a9cb8967eb81acb80750/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts#L664)):*
> ```XML
>   }
> 
>   localAddQuestion(newQuestion: Question): void {
> ```

Unused
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts` line 670 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NfOFFL9D4nLsq0ROnrM:-NfOFFL9D4nLsq0ROnrN:b-yrumkl) ([raw file](https://github.com/sillsdev/web-xforge/blob/907a76fa01ffc5c47431a9cb8967eb81acb80750/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts#L670)):*
> ```XML
>   }
> 
>   localSetIsArchived(question: Question, isArchived: boolean): void {
> ```

Unused
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.stories.ts` line 110 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NfOHoUf63Y9tIXuyb11:-NfOHoUf63Y9tIXuyb12:bez2828) ([raw file](https://github.com/sillsdev/web-xforge/blob/907a76fa01ffc5c47431a9cb8967eb81acb80750/src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.stories.ts#L110)):*
> ```XML
> export default meta;
> 
> type Story = StoryFn;
> ```

Need to use the new CSF 3 format`StoryObj` and all below stories
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 2139 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NfOCNX45IqCa_aoSwDw:-NfOCNX53RQUv0tbBf7c:b-feeq3w) ([raw file](https://github.com/sillsdev/web-xforge/blob/907a76fa01ffc5c47431a9cb8967eb81acb80750/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L2139)):*
> ```XML
> 
>   private keepInsertNoteFabInView(): void {
>     if (this.insertNoteFab == null || this.target == null || this.target.editor == null || this.targetContainer == null)
> ```

Can be `this.target?.editor == null`


<!-- Sent from Reviewable.io -->

2023-09-28 01:26 UTC, Nateowami commented
@nigel-wells Wow, I'm really bad at cleaning things up aren't I? Thanks for catching all of these. Working on fixing them.

2023-09-28 10:05 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1825)* status: 23 of 26 files reviewed, 9 unresolved discussions (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts` line 14 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NfOFNJA69gfTdEjyFI-:-NfO_pJ2BcPBtyKmsxlV:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/907a76fa01ffc5c47431a9cb8967eb81acb80750/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts#L14)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Unused `getQuestionDocID` once the below methods are removed.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts` line 126 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NfOEBYR498hN8cC2u71:-NfQBvem3V6KEHpIkUrW:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/907a76fa01ffc5c47431a9cb8967eb81acb80750/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts#L126)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Nit  `My Progress` should be `Manage questions`? Same applies to below comments if this needs correcting. It doesn't effect the test expectations but confused me as to why I wasn't seeing it as an admin :)
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts` line 622 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NfOEt95BMO2lSdwfVik:-NfQBoVtC6X3PBQtFV4H:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/907a76fa01ffc5c47431a9cb8967eb81acb80750/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts#L622)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Unused
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts` line 627 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NfOEyvtDAPKGaY_qExi:-NfQBp3W5t1JkeBhmxVX:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/907a76fa01ffc5c47431a9cb8967eb81acb80750/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts#L627)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Unused
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts` line 632 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NfOF-T21JSiFoqtJYZR:-NfQBph74x8_SW4Rzk2d:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/907a76fa01ffc5c47431a9cb8967eb81acb80750/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts#L632)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Unused
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts` line 649 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NfOFAGO2JRtlRsmUQ8F:-NfQBqQrC_gtjAzZHXY0:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/907a76fa01ffc5c47431a9cb8967eb81acb80750/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts#L649)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Unused
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts` line 664 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NfOFBZ_6obbMtC0_Dmf:-NfQBrVQAnrMOAShtPAT:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/907a76fa01ffc5c47431a9cb8967eb81acb80750/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts#L664)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Unused
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts` line 670 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NfOFFL9D4nLsq0ROnrM:-NfQBrwGBYvTHgL2rmOA:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/907a76fa01ffc5c47431a9cb8967eb81acb80750/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts#L670)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Unused
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.stories.ts` line 110 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NfOHoUf63Y9tIXuyb11:-NfQEvvvBnPBthBv8jKv:b8640gp) ([raw file](https://github.com/sillsdev/web-xforge/blob/907a76fa01ffc5c47431a9cb8967eb81acb80750/src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.stories.ts#L110)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Need to use the new CSF 3 format`StoryObj` and all below stories
</blockquote></details>

Will do, but I think I'm done for the day.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 2139 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NfOCNX45IqCa_aoSwDw:-NfOZ7nGEGhiglMqsvRt:b-eo1iqo) ([raw file](https://github.com/sillsdev/web-xforge/blob/907a76fa01ffc5c47431a9cb8967eb81acb80750/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L2139)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Can be `this.target?.editor == null`
</blockquote></details>

Maybe? This was not touched in this PR. I think you're seeing the diff do to a a rebase.


<!-- Sent from Reviewable.io -->

2023-09-29 00:23 UTC, nigel-wells reviewed
All good :) Can we get a our lint checker to throw an error if there are unused ones?

> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-:-NfTJEQE7nROQMGTeVxb:b-19yayc)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 2139 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NfOCNX45IqCa_aoSwDw:-NfTJ2Xu0jYyG9TgdMBP:bf7b8wz) ([raw file](https://github.com/sillsdev/web-xforge/blob/907a76fa01ffc5c47431a9cb8967eb81acb80750/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L2139)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Maybe? This was not touched in this PR. I think you're seeing the diff do to a a rebase.
</blockquote></details>

Yeah, odd. I only saw it because it was highlighted as a change. Up to you if you want to fix as part of this.


<!-- Sent from Reviewable.io -->

2023-10-11 21:25 UTC, siltomato requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1825)* status: 17 of 28 files reviewed, 3 unresolved discussions (waiting on @Nateowami and @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/resume-checking.service.ts` line 35 at r10](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NgVT7hdBV3_BCt_KeqO:-NgVT7hdBV3_BCt_KeqP:b449vp5) ([raw file](https://github.com/sillsdev/web-xforge/blob/529800d9d23cb5133c62e014fa10f1db7431978c/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/resume-checking.service.ts#L35)):*
> ```XML
>    * already)
>    */
>   getQuestion(): QuestionDoc | undefined {
> ```

Can I suggest to rewrite this service in a more 'reactive' way so that consumers are notified instead of needing to poll to get updated results?  Here is an idea for a possible solution:
```ts
import { Injectable } from '@angular/core';
import { Canon } from '@sillsdev/scripture';
import { BehaviorSubject, merge, Observable, Subscription } from 'rxjs';
import { distinct, filter, map, throttleTime } from 'rxjs/operators';
import { QuestionDoc } from 'src/app/core/models/question-doc';
import { ActivatedProjectService } from 'xforge-common/activated-project.service';
import { SubscriptionDisposable } from 'xforge-common/subscription-disposable';
import { UserService } from 'xforge-common/user.service';
import { CheckingQuestionsService } from './checking-questions.service';

/**
 * Provides information about what location the user should be sent to in order to resume community checking (or start
 * for the first time).
 *
 * At present, this means sending the user to the first question that is unanswered, and limiting the scope of questions
 * to the chapter level.
 */
@Injectable({ providedIn: 'root' })
export class ResumeCheckingService extends SubscriptionDisposable {
  private resumeQuestion$ = new BehaviorSubject<QuestionDoc | undefined>(undefined);
  private querySub?: Subscription;

  constructor(
    private readonly userService: UserService,
    private readonly activatedProjectService: ActivatedProjectService,
    private readonly questionService: CheckingQuestionsService
  ) {
    super();
    this.subscribe(this.activatedProjectService.projectId$, projectId => this.refreshQuestionQuery(projectId));
  }

  /**
   * @returns The question for the user to resume community checking on, or undefined, if no project is selected, the
   * question has not yet been loaded, or no question matches the criteria (e.g. user has answered all questions'
   * already)
   */
  getQuestion(): Observable<QuestionDoc | undefined> {
    return this.resumeQuestion$.pipe(distinct(q => q?.id));
  }

  /**
   * @returns An path to navigate to the community checking component and resume checking. In general this will lead
   * the user to first unanswered question.
   */
  getLink(): Observable<string[]> {
    return this.getQuestion().pipe(map(q => this.getLinkTokens(q)));
  }

  private getLinkTokens(questionDoc: QuestionDoc | undefined): string[] {
    const verseRef = questionDoc?.data?.verseRef;
    const projectId = this.activatedProjectService.projectId;

    if (verseRef != null && projectId != null) {
      const book = Canon.bookNumberToId(verseRef.bookNum);
      return ['projects', projectId, 'checking', book, String(verseRef.chapterNum)];
    } else {
      // TODO FIXME handle case where no questions, or all questions already answered
      return [''];
    }
  }

  private async refreshQuestionQuery(projectId: string | undefined): Promise<void> {
    if (projectId == null) {
      return;
    }

    const query = await this.questionService.queryFirstUnansweredQuestion(projectId, this.userService.currentUserId);

    // Ensure the project has not changed while awaiting the query
    if (this.activatedProjectService.projectId === projectId) {
      this.querySub?.unsubscribe();
      this.querySub = this.subscribe(
        merge(
          query.ready$.pipe(filter(isReady => isReady)),
          query.remoteChanges$,
          query.localChanges$,
          query.remoteDocChanges$
        ).pipe(throttleTime(1000)),
        () => {
          this.resumeQuestion$.next(query?.docs[0]);
        }
      );
    }
  }
}
```


<!-- Sent from Reviewable.io -->

2023-10-11 22:22 UTC, siltomato reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1825)* status: 17 of 28 files reviewed, 3 unresolved discussions (waiting on @Nateowami and @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.ts` line 154 at r10](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NgVl07QAQU07iBb_Gjh:-NgVl07QAQU07iBb_Gji:blrl76h) ([raw file](https://github.com/sillsdev/web-xforge/blob/529800d9d23cb5133c62e014fa10f1db7431978c/src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.ts#L154)):*
> ```XML
>   }
> 
>   get draftGenerationLink(): string[] {
> ```

Ok, this is interesting... I put a console.log at the start of this function and reloaded the page.  Checkout how many times it was called.
![image copy 1.png](https://files.reviewableusercontent.io/images/reviewable/133386342/d-RkMwqsaeGpP_V4f2fqmQ4W/image.png)
I think anytime we call a function from the template, this number is going to be high due to change detection having no way of knowing if the result changed, but this seems unusually high.


One way to overcome this is by creating a pipe that change detection can consider 'pure'.  Something like:
```ts
import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'projectLink'
})
export class ProjectLinkPipe implements PipeTransform {
  transform(
    projectId: string | undefined,
    page: 'translate' | 'draft-generation' | 'checking' | 'sync' | 'users' | 'settings',
    subPages: string[] = []
  ): string[] {
    return this.getProjectLink(projectId, page, subPages);
  }

  private getProjectLink(
    projectId: string | undefined,
    page: 'translate' | 'draft-generation' | 'checking' | 'sync' | 'users' | 'settings',
    subPages: string[] = []
  ): string[] {
    if (page === 'draft-generation') {
      console.log('ProjectLinkPipe - draftGenerationLink');
    }

    if (projectId == null) {
      return [];
    }
    return ['/projects', projectId, page, ...subPages];
  }
}

```

...and calling it something like:
```html
<a *ngIf="canGenerateDraft" mat-list-item [appRouterLink]="this.selectedProjectId | projectLink : 'draft-generation'">
```

The result was a single call:
![image.png](https://files.reviewableusercontent.io/images/reviewable/133386342/XoVOxxH6-c-oPPEreuz-ItjS/image.png)

I don't know if the performance gains are worth the increase in complexity, but it may be worth considering in some cases.  Simpler than pipes would be using properties with calculated values as opposed to function calls (or getters) where not too cumbersome.

I wish there was some way to tag 'pure' functions via a decorator or something that angular change detection would recognize.


<!-- Sent from Reviewable.io -->

2023-11-10 02:29 UTC, Nateowami reviewed
> Dismissed @github-advanced-security[bot] from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1825)* status: 11 of 29 files reviewed, 2 unresolved discussions (waiting on @nigel-wells and @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/resume-checking.service.ts` line 35 at r10](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NgVT7hdBV3_BCt_KeqO:-Nir1h2Z5QzlqXdab0d-:b-etuwtx) ([raw file](https://github.com/sillsdev/web-xforge/blob/529800d9d23cb5133c62e014fa10f1db7431978c/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/resume-checking.service.ts#L35)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Can I suggest to rewrite this service in a more 'reactive' way so that consumers are notified instead of needing to poll to get updated results?  Here is an idea for a possible solution:
```ts
import { Injectable } from '@angular/core';
import { Canon } from '@sillsdev/scripture';
import { BehaviorSubject, merge, Observable, Subscription } from 'rxjs';
import { distinct, filter, map, throttleTime } from 'rxjs/operators';
import { QuestionDoc } from 'src/app/core/models/question-doc';
import { ActivatedProjectService } from 'xforge-common/activated-project.service';
import { SubscriptionDisposable } from 'xforge-common/subscription-disposable';
import { UserService } from 'xforge-common/user.service';
import { CheckingQuestionsService } from './checking-questions.service';

/**
 * Provides information about what location the user should be sent to in order to resume community checking (or start
 * for the first time).
 *
 * At present, this means sending the user to the first question that is unanswered, and limiting the scope of questions
 * to the chapter level.
 */
@Injectable({ providedIn: 'root' })
export class ResumeCheckingService extends SubscriptionDisposable {
  private resumeQuestion$ = new BehaviorSubject<QuestionDoc | undefined>(undefined);
  private querySub?: Subscription;

  constructor(
    private readonly userService: UserService,
    private readonly activatedProjectService: ActivatedProjectService,
    private readonly questionService: CheckingQuestionsService
  ) {
    super();
    this.subscribe(this.activatedProjectService.projectId$, projectId => this.refreshQuestionQuery(projectId));
  }

  /**
   * @returns The question for the user to resume community checking on, or undefined, if no project is selected, the
   * question has not yet been loaded, or no question matches the criteria (e.g. user has answered all questions'
   * already)
   */
  getQuestion(): Observable<QuestionDoc | undefined> {
    return this.resumeQuestion$.pipe(distinct(q => q?.id));
  }

  /**
   * @returns An path to navigate to the community checking component and resume checking. In general this will lead
   * the user to first unanswered question.
   */
  getLink(): Observable<string[]> {
    return this.getQuestion().pipe(map(q => this.getLinkTokens(q)));
  }

  private getLinkTokens(questionDoc: QuestionDoc | undefined): string[] {
    const verseRef = questionDoc?.data?.verseRef;
    const projectId = this.activatedProjectService.projectId;

    if (verseRef != null && projectId != null) {
      const book = Canon.bookNumberToId(verseRef.bookNum);
      return ['projects', projectId, 'checking', book, String(verseRef.chapterNum)];
    } else {
      // TODO FIXME handle case where no questions, or all questions already answered
      return [''];
    }
  }

  private async refreshQuestionQuery(projectId: string | undefined): Promise<void> {
    if (projectId == null) {
      return;
    }

    const query = await this.questionService.queryFirstUnansweredQuestion(projectId, this.userService.currentUserId);

    // Ensure the project has not changed while awaiting the query
    if (this.activatedProjectService.projectId === projectId) {
      this.querySub?.unsubscribe();
      this.querySub = this.subscribe(
        merge(
          query.ready$.pipe(filter(isReady => isReady)),
          query.remoteChanges$,
          query.localChanges$,
          query.remoteDocChanges$
        ).pipe(throttleTime(1000)),
        () => {
          this.resumeQuestion$.next(query?.docs[0]);
        }
      );
    }
  }
}
```
</blockquote></details>

I think it's a good idea, but this PR has morphed and broken so many times over the last six months I think it would be better to merge it first.

Of course, there's the hazard that then we never get to it, since it's no longer a high priority, but I'm finding keeping this PR up to date quite challenging as-is.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.ts` line 154 at r10](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NgVl07QAQU07iBb_Gjh:-Nir23Ce5DXCqq2kzQHE:b-3b3s8n) ([raw file](https://github.com/sillsdev/web-xforge/blob/529800d9d23cb5133c62e014fa10f1db7431978c/src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.ts#L154)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Ok, this is interesting... I put a console.log at the start of this function and reloaded the page.  Checkout how many times it was called.
![image copy 1.png](https://files.reviewableusercontent.io/images/reviewable/133386342/d-RkMwqsaeGpP_V4f2fqmQ4W/image.png)
I think anytime we call a function from the template, this number is going to be high due to change detection having no way of knowing if the result changed, but this seems unusually high.


One way to overcome this is by creating a pipe that change detection can consider 'pure'.  Something like:
```ts
import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'projectLink'
})
export class ProjectLinkPipe implements PipeTransform {
  transform(
    projectId: string | undefined,
    page: 'translate' | 'draft-generation' | 'checking' | 'sync' | 'users' | 'settings',
    subPages: string[] = []
  ): string[] {
    return this.getProjectLink(projectId, page, subPages);
  }

  private getProjectLink(
    projectId: string | undefined,
    page: 'translate' | 'draft-generation' | 'checking' | 'sync' | 'users' | 'settings',
    subPages: string[] = []
  ): string[] {
    if (page === 'draft-generation') {
      console.log('ProjectLinkPipe - draftGenerationLink');
    }

    if (projectId == null) {
      return [];
    }
    return ['/projects', projectId, page, ...subPages];
  }
}

```

...and calling it something like:
```html
<a *ngIf="canGenerateDraft" mat-list-item [appRouterLink]="this.selectedProjectId | projectLink : 'draft-generation'">
```

The result was a single call:
![image.png](https://files.reviewableusercontent.io/images/reviewable/133386342/XoVOxxH6-c-oPPEreuz-ItjS/image.png)

I don't know if the performance gains are worth the increase in complexity, but it may be worth considering in some cases.  Simpler than pipes would be using properties with calculated values as opposed to function calls (or getters) where not too cumbersome.

I wish there was some way to tag 'pure' functions via a decorator or something that angular change detection would recognize.
</blockquote></details>

Same as above, I think this is a good idea, but not worth holding this PR up more. Signals are coming in Angular and may make this easier.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.stories.ts` line 110 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NfOHoUf63Y9tIXuyb11:-Nir2Ebd5k78LXdAVwkm:bi8le3v) ([raw file](https://github.com/sillsdev/web-xforge/blob/907a76fa01ffc5c47431a9cb8967eb81acb80750/src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.stories.ts#L110)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Will do, but I think I'm done for the day.
</blockquote></details>

Actually, I think it's probably better to move forward as-is (there's nothing really wrong with t [...]

2023-11-13 03:36 UTC, nigel-wells requested changes
Only a few comments from me - I'll let @siltomato respond to the other files he's been providing feedback on.

> Reviewed 2 of 11 files at r9, 2 of 11 files at r11, 14 of 14 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-:-Nj5jtnzBByH5ew_dPHW:b-mk1efz)* status: all files reviewed, 5 unresolved discussions (waiting on @Nateowami and @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.html` line 16 at r12](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Nj5Uvf-3UrUHmIcE16R:-Nj5Uvf-3UrUHmIcE16S:b-yoiazt) ([raw file](https://github.com/sillsdev/web-xforge/blob/270b127e8f355ee763c172c66a298897b6ac1646/src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.html#L16)):*
> ```HTML
>       </a>
>       <a *ngIf="canGenerateDraft" mat-list-item [appRouterLink]="draftGenerationLink">
>         <mat-icon mat-list-icon>edit_note</mat-icon>
> ```

Do you think this one should also mirror?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.stories.ts` line 110 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NfOHoUf63Y9tIXuyb11:-Nj5co6rDw56XWnvdGol:b-5fxsh6) ([raw file](https://github.com/sillsdev/web-xforge/blob/907a76fa01ffc5c47431a9cb8967eb81acb80750/src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.stories.ts#L110)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Actually, I think it's probably better to move forward as-is (there's nothing really wrong with the function format, it's just not the latest). Keeping this PR up to date with master has been a major challenge.
</blockquote></details>

I get that this in itself should hold up merging the rest of the PR. It seems odd that we would introduce new code that we know is in a format we don't want - kind of like building another component in MDC. Most of the stories are the same so maybe it wouldn't take too long to update? I won't push hard on this so let me know.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 846 at r8](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Nj5Zp4041_btk4RExXI:-Nj5Zp4041_btk4RExXJ:bo9zme9) ([raw file](https://github.com/sillsdev/web-xforge/blob/58cf4587ea00108ed891ce2afa9f8126fcd487cd/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L846)):*
> ```XML
>           this.subscribeScroll(this.target.editor);
> 
>           if (this.featureFlags.showNmtDrafting.enabled) {
> ```

Was it intentional to remove the feature flag?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/activated-project.service.ts` line 111 at r12](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Nj5gbVcAW_wJJHaQlko:-Nj5gbVd3RRR-u-pa7TQ:bk6dyed) ([raw file](https://github.com/sillsdev/web-xforge/blob/270b127e8f355ee763c172c66a298897b6ac1646/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/activated-project.service.ts#L111)):*
> ```XML
> }
> 
> export class TestActiveProjectIdService implements IActiveProjectIdService {
> ```

Are these needed here if they only relate to the stories?


<!-- Sent from Reviewable.io -->

2023-11-20 15:14 UTC, siltomato requested changes
Just a minor import nit.  Also, perhaps it would be worth adding some TODO comments with an eye toward angular signals? 

> Reviewed 2 of 11 files at r9, 1 of 14 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-:-NjhHArqDzsV3noOhQ4K:bktmv6c)* status: all files reviewed, 7 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions.service.ts` line 14 at r12](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Niu69ih7nQnzIBh9ja_:-Niu69ih7nQnzIBh9jaa:b-3hs49f) ([raw file](https://github.com/sillsdev/web-xforge/blob/270b127e8f355ee763c172c66a298897b6ac1646/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions.service.ts#L14)):*
> ```XML
> import { RealtimeService } from '../../../xforge-common/realtime.service';
> import { QuestionDoc } from '../../core/models/question-doc';
> ```

This was probably my fault, but should the 'xforge-common' imports be referenced from 'xforge-common' as the root instead of a relative path since there is a tsconfig rule for it?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/resume-checking.service.ts` line 35 at r10](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NgVT7hdBV3_BCt_KeqO:-NjhG-yMEKq4JupiR97y:b-lc5b4o) ([raw file](https://github.com/sillsdev/web-xforge/blob/529800d9d23cb5133c62e014fa10f1db7431978c/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/resume-checking.service.ts#L35)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I think it's a good idea, but this PR has morphed and broken so many times over the last six months I think it would be better to merge it first.

Of course, there's the hazard that then we never get to it, since it's no longer a high priority, but I'm finding keeping this PR up to date quite challenging as-is.
</blockquote></details>

Ok, sounds good.  Would it be worth putting a 'TODO' on it?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.ts` line 154 at r10](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NgVl07QAQU07iBb_Gjh:-NjhGET26bc1tGhk9vW6:b-7wboay) ([raw file](https://github.com/sillsdev/web-xforge/blob/529800d9d23cb5133c62e014fa10f1db7431978c/src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.ts#L154)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Same as above, I think this is a good idea, but not worth holding this PR up more. Signals are coming in Angular and may make this easier.
</blockquote></details>

Yes, I'm curious how signals will change how we approach these things.  Maybe a 'TODO' is warranted?


<!-- Sent from Reviewable.io -->

2023-11-21 04:47 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1825)* status: 21 of 29 files reviewed, 6 unresolved discussions (waiting on @nigel-wells and @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions.service.ts` line 14 at r12](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Niu69ih7nQnzIBh9ja_:-Njj9_Y_6SsmV47_SpI8:b-m5so5s) ([raw file](https://github.com/sillsdev/web-xforge/blob/270b127e8f355ee763c172c66a298897b6ac1646/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions.service.ts#L14)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

This was probably my fault, but should the 'xforge-common' imports be referenced from 'xforge-common' as the root instead of a relative path since there is a tsconfig rule for it?
</blockquote></details>

Do you mean ESLint rule, not tsconfig? We have a similar rule for `src`, but it's kind of arbitrary.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/resume-checking.service.ts` line 35 at r10](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NgVT7hdBV3_BCt_KeqO:-NjjZUyr4ltmzuJUmVSE:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/529800d9d23cb5133c62e014fa10f1db7431978c/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/resume-checking.service.ts#L35)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Ok, sounds good.  Would it be worth putting a 'TODO' on it?
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.html` line 16 at r12](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Nj5Uvf-3UrUHmIcE16R:-NjE27Or2KVuBJbQCGcv:b-lhkmuo) ([raw file](https://github.com/sillsdev/web-xforge/blob/270b127e8f355ee763c172c66a298897b6ac1646/src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.html#L16)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Do you think this one should also mirror?
</blockquote></details>

No. See our document "Scripture Forge RTL Design Guidelines." In general a pencil should not be flipped. Maybe it would make sense to move it to the other side, but we can't do that easily. And I'd rather err on the side of not flipping.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.ts` line 154 at r10](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NgVl07QAQU07iBb_Gjh:-NjkBsmA98tcqhQ9Th77:bhr01aq) ([raw file](https://github.com/sillsdev/web-xforge/blob/529800d9d23cb5133c62e014fa10f1db7431978c/src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.component.ts#L154)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Yes, I'm curious how signals will change how we approach these things.  Maybe a 'TODO' is warranted?
</blockquote></details>

I don't really see this as something important to optimize, though if it is a bottleneck it wouldn't be that difficult to do so.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.stories.ts` line 110 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NfOHoUf63Y9tIXuyb11:-NjkBTpI3jUvtngZCTpU:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/907a76fa01ffc5c47431a9cb8967eb81acb80750/src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.stories.ts#L110)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

I get that this in itself should hold up merging the rest of the PR. It seems odd that we would introduce new code that we know is in a format we don't want - kind of like building another component in MDC. Most of the stories are the same so maybe it wouldn't take too long to update? I won't push hard on this so let me know.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 846 at r8](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Nj5Zp4041_btk4RExXI:-NjE2T2D5LW59Jw5wx5l:b6y6kbj) ([raw file](https://github.com/sillsdev/web-xforge/blob/58cf4587ea00108ed891ce2afa9f8126fcd487cd/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L846)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Was it intentional to remove the feature flag?
</blockquote></details>

I did not make any change here. I think you're seeing a diff caused by a rebase. Maybe it was the notes feature flag? It got removed when the flag was turned on (I don't think this was the right approach, but I didn't see it until after it happened).
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/activated-project.service.ts` line 111 at r12](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Nj5gbVcAW_wJJHaQlko:-NjkBZea8vxixdQMydAS:b-a46byk) ([raw file](https://github.com/sillsdev/web-xforge/blob/270b127e8f355ee763c172c66a298897b6ac1646/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/activated-project.service.ts#L111)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Are these needed here if they only relate to the stories?
</blockquote></details>

They wouldn't have to be here, but I look at the whole thing as a package. The whole reason the ActiveProjectService takes an ActiveProjectIdService is so this testing infrastructure works. I did consider doing it the other way though.


<!-- Sent from Reviewable.io -->

2023-11-21 17:21 UTC, siltomato requested changes
> Reviewed 1 of 7 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1825)* status: 22 of 29 files reviewed, 6 unresolved discussions (waiting on @Nateowami and @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions.service.ts` line 14 at r12](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Niu69ih7nQnzIBh9ja_:-NjmmCsqB8Gg-8cLyLd9:bym6tlv) ([raw file](https://github.com/sillsdev/web-xforge/blob/270b127e8f355ee763c172c66a298897b6ac1646/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions.service.ts#L14)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Do you mean ESLint rule, not tsconfig? We have a similar rule for `src`, but it's kind of arbitrary.
</blockquote></details>

I was referring to the tsconfig `compilerOptions.paths`.  I guess 'rule' is the wrong word =).
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/resume-checking.service.ts` line 35 at r10](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NgVT7hdBV3_BCt_KeqO:-Njmo_Ba3vSL9RlWSjCB:bu2t8n9) ([raw file](https://github.com/sillsdev/web-xforge/blob/529800d9d23cb5133c62e014fa10f1db7431978c/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/resume-checking.service.ts#L35)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Ah, ok, that is a useful comment, but I was referring to a TODO in regard to the idea of making the service more 'reactive'.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/activated-project.service.ts` line 16 at r15](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NjmspSuCLT7rYK5W-YB:-NjmspSuCLT7rYK5W-YC:b-n2gjru) ([raw file](https://github.com/sillsdev/web-xforge/blob/cb9587e506144d97f7fd9b7002c813e9d56ed728/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/activated-project.service.ts#L16)):*
> ```XML
> 
> @Injectable({ providedIn: 'root' })
> export class ActiveProjectIdService implements ActiveProjectIdService {
> ```

Would it be better to put these services one per file?  If we need to group them, we could organize them under the same directory.


<!-- Sent from Reviewable.io -->

2023-11-21 18:00 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1825)* status: 22 of 29 files reviewed, 6 unresolved discussions (waiting on @nigel-wells and @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions.service.ts` line 14 at r12](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Niu69ih7nQnzIBh9ja_:-Njmx2YDC3pR_PqjfteF:b-x88sn9) ([raw file](https://github.com/sillsdev/web-xforge/blob/270b127e8f355ee763c172c66a298897b6ac1646/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions.service.ts#L14)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

I was referring to the tsconfig `compilerOptions.paths`.  I guess 'rule' is the wrong word =).
</blockquote></details>

I don't understand; what does the import format have to do with the tsconfig compiler options?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/resume-checking.service.ts` line 35 at r10](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NgVT7hdBV3_BCt_KeqO:-Njmy0h82ZB5SFXXmAAh:bd2hnfd) ([raw file](https://github.com/sillsdev/web-xforge/blob/529800d9d23cb5133c62e014fa10f1db7431978c/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/resume-checking.service.ts#L35)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Ah, ok, that is a useful comment, but I was referring to a TODO in regard to the idea of making the service more 'reactive'.
</blockquote></details>

I must have accidentally removed the comment. Re-adding.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/activated-project.service.ts` line 16 at r15](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NjmspSuCLT7rYK5W-YB:-NjmyBCu1iAKWtpAVd9g:b-ilv3nd) ([raw file](https://github.com/sillsdev/web-xforge/blob/cb9587e506144d97f7fd9b7002c813e9d56ed728/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/activated-project.service.ts#L16)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Would it be better to put these services one per file?  If we need to group them, we could organize them under the same directory.
</blockquote></details>

Maybe? In general I think it makes sense to split things up if files are getting too long, or code isn't closely related. But in this case all these services exist to work with the ActiveProjectService. The only reason the ActiveProjectService takes an IActiveProjectIdService is so the testing class can work. So they seem more closely related to me that just ordinarily depending on each other.


<!-- Sent from Reviewable.io -->

2023-11-21 22:57 UTC, siltomato requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1825)* status: 22 of 29 files reviewed, 6 unresolved discussions (waiting on @Nateowami and @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions.service.ts` line 14 at r12](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Niu69ih7nQnzIBh9ja_:-Njo3Q409CvrMafXB9bE:bryn5ay) ([raw file](https://github.com/sillsdev/web-xforge/blob/270b127e8f355ee763c172c66a298897b6ac1646/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions.service.ts#L14)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I don't understand; what does the import format have to do with the tsconfig compiler options?
</blockquote></details>

You could import from `'xforge-common/realtime.service'` instead of `'../../../xforge-common/realtime.service'` due to the path compiler option in tsconfig.  My mentioning the compiler option was confusing, sorry about that.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/activated-project.service.ts` line 16 at r15](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NjmspSuCLT7rYK5W-YB:-Njo4lPtDLkHpw0Pq5Ou:b-qya1dl) ([raw file](https://github.com/sillsdev/web-xforge/blob/cb9587e506144d97f7fd9b7002c813e9d56ed728/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/activated-project.service.ts#L16)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Maybe? In general I think it makes sense to split things up if files are getting too long, or code isn't closely related. But in this case all these services exist to work with the ActiveProjectService. The only reason the ActiveProjectService takes an IActiveProjectIdService is so the testing class can work. So they seem more closely related to me that just ordinarily depending on each other.
</blockquote></details>

Ok, makes sense.  On another note, I just noticed that the service is implementing itself instead of the interface.


<!-- Sent from Reviewable.io -->

2023-11-22 16:45 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1825)* status: 20 of 29 files reviewed, 5 unresolved discussions (waiting on @nigel-wells and @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions.service.ts` line 14 at r12](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Niu69ih7nQnzIBh9ja_:-Njrucwm3lZP0ZC4C9oG:b-bo20t4) ([raw file](https://github.com/sillsdev/web-xforge/blob/270b127e8f355ee763c172c66a298897b6ac1646/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-questions.service.ts#L14)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

You could import from `'xforge-common/realtime.service'` instead of `'../../../xforge-common/realtime.service'` due to the path compiler option in tsconfig.  My mentioning the compiler option was confusing, sorry about that.
</blockquote></details>

Done. We have a few other files with the same, for what it's worth.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/activated-project.service.ts` line 16 at r15](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NjmspSuCLT7rYK5W-YB:-NjruaOEAgLq3GLz14hi:b-ouxslc) ([raw file](https://github.com/sillsdev/web-xforge/blob/cb9587e506144d97f7fd9b7002c813e9d56ed728/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/activated-project.service.ts#L16)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Ok, makes sense.  On another note, I just noticed that the service is implementing itself instead of the interface.
</blockquote></details>

Good catch. Fixed. At first I was surprised it compiled at all, but it will compile even if this class doesn't implement anything, because it satisfies the interface.


<!-- Sent from Reviewable.io -->

2023-11-22 16:55 UTC, siltomato approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-:-Njrx3ywA7H5HmoHKE2j:bnfp4nl)* status: 20 of 29 files reviewed, 4 unresolved discussions (waiting on @nigel-wells)



<!-- Sent from Reviewable.io -->

2023-11-22 21:51 UTC, nigel-wells requested changes
Just one comment around stories.

> Reviewed 3 of 7 files at r13, 1 of 1 files at r15, 1 of 1 files at r16, 5 of 5 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-:-Njt-y8eCF_hniXAXDSw:b-gzzdy4)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.stories.ts` line 110 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NfOHoUf63Y9tIXuyb11:-Njt-sed8geLt0WgMJ_g:b-668q2r) ([raw file](https://github.com/sillsdev/web-xforge/blob/907a76fa01ffc5c47431a9cb8967eb81acb80750/src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.stories.ts#L110)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks for working through this.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.stories.ts` line 181 at r17](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Njt-XFq3wednyXDywb6:-Njt-XFq3wednyXDywb7:bos5yvk) ([raw file](https://github.com/sillsdev/web-xforge/blob/d2d816e5565a7e443f23566584c968af8e5401c4/src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.stories.ts#L181)):*
> ```XML
> 
> export const Administrator: Story = {
>   args: { ...Default.args, role: SFProjectRole.ParatextAdministrator },
> ```

This can just be changed to `...Default`. `args` then only get added if you want to overwrite something from `Default`. Same with all the below. See `join.stories.ts` as an example.


<!-- Sent from Reviewable.io -->

2023-11-22 22:29 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1825)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.stories.ts` line 181 at r17](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Njt-XFq3wednyXDywb6:-Njt8J7j8rp_2dPBRN37:b-rl0key) ([raw file](https://github.com/sillsdev/web-xforge/blob/d2d816e5565a7e443f23566584c968af8e5401c4/src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.stories.ts#L181)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

This can just be changed to `...Default`. `args` then only get added if you want to overwrite something from `Default`. Same with all the below. See `join.stories.ts` as an example.
</blockquote></details>

This one can be changed to `args: Default.args,`, but I don't understand what you mean about the ones below.


<!-- Sent from Reviewable.io -->

2023-11-22 22:37 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1825)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.stories.ts` line 181 at r17](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Njt-XFq3wednyXDywb6:-Njt9u1x3T_AOL5YpNeI:bbv3q2m) ([raw file](https://github.com/sillsdev/web-xforge/blob/d2d816e5565a7e443f23566584c968af8e5401c4/src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.stories.ts#L181)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This one can be changed to `args: Default.args,`, but I don't understand what you mean about the ones below.
</blockquote></details>

To some extent I like the fact that the role is always specified. Yes, it is a bit redundant, but the main reason the "Default" exists, is to allow us to quickly create specialized stories. And we have one that is basically the default, but adjusted for each role. We could not specify the role in this case, but then a) it's not consistent with the other role-related stories, and b) you can't tell just from the story that it's doing what it says (you have to look at default to see what the role is set to if not specified). So the story is no longer self-documenting.


<!-- Sent from Reviewable.io -->

2023-11-22 22:39 UTC, nigel-wells requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1825)* status: all files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.stories.ts` line 181 at r17](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-Njt-XFq3wednyXDywb6:-NjtAkNL7l47UcUoGvoQ:by2iuam) ([raw file](https://github.com/sillsdev/web-xforge/blob/d2d816e5565a7e443f23566584c968af8e5401c4/src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.stories.ts#L181)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

To some extent I like the fact that the role is always specified. Yes, it is a bit redundant, but the main reason the "Default" exists, is to allow us to quickly create specialized stories. And we have one that is basically the default, but adjusted for each role. We could not specify the role in this case, but then a) it's not consistent with the other role-related stories, and b) you can't tell just from the story that it's doing what it says (you have to look at default to see what the role is set to if not specified). So the story is no longer self-documenting.
</blockquote></details>

Yes, there is value in that. See below adjustment to other tests which still shows the role. It was more around taking the spread out of args and then overwriting what you need in the args.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.stories.ts` line 208 at r17](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NjtASnA6HXRNJT1Y51m:-NjtASnA6HXRNJT1Y51n:b-y3wi33) ([raw file](https://github.com/sillsdev/web-xforge/blob/d2d816e5565a7e443f23566584c968af8e5401c4/src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.stories.ts#L208)):*
> ```XML
>     ]);
>   }
> };
> ```

This would become:

```
export const Translator: Story = {
  ...Default.args,
  args: { role: SFProjectRole.ParatextTranslator },
  play: async ({ canvasElement }) => {
    expect(menuItems(canvasElement)).toEqual([
      'Overview',
      'Draft & review',
      'Generate draft',
      'My progress',
      'Questions & answers',
      'Synchronize'
    ]);
  }
};
```



_Code quote:_
```XML
export const Translator: Story = {
  args: { ...Default.args, role: SFProjectRole.ParatextTranslator },
  play: async ({ canvasElement }) => {
    expect(menuItems(canvasElement)).toEqual([
      'Overview',
      'Draft & review',
      'Generate draft',
      'My progress',
      'Questions & answers',
      'Synchronize'
    ]);
  }
};
```


<!-- Sent from Reviewable.io -->

2023-11-22 22:43 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1825)* status: all files reviewed, 2 unresolved discussions (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.stories.ts` line 208 at r17](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NjtASnA6HXRNJT1Y51m:-NjtBNRS4-ATEXD9aGbQ:b-8r6ybk) ([raw file](https://github.com/sillsdev/web-xforge/blob/d2d816e5565a7e443f23566584c968af8e5401c4/src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.stories.ts#L208)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

This would become:

```
export const Translator: Story = {
  ...Default.args,
  args: { role: SFProjectRole.ParatextTranslator },
  play: async ({ canvasElement }) => {
    expect(menuItems(canvasElement)).toEqual([
      'Overview',
      'Draft & review',
      'Generate draft',
      'My progress',
      'Questions & answers',
      'Synchronize'
    ]);
  }
};
```
</blockquote></details>

That doesn't work. You're spreading the args into the story itself. Also it's more verbose, and makes it less obvious that the default args are being included (and again, they aren't).


<!-- Sent from Reviewable.io -->

2023-11-22 22:49 UTC, Nateowami commented
In addition to code review, someone should approve the changes in Storybook

2023-11-22 22:51 UTC, nigel-wells requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1825)* status: all files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.stories.ts` line 208 at r17](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-NjtASnA6HXRNJT1Y51m:-NjtDZjH5Y5EXdRgSUcF:bmlym1s) ([raw file](https://github.com/sillsdev/web-xforge/blob/d2d816e5565a7e443f23566584c968af8e5401c4/src/SIL.XForge.Scripture/ClientApp/src/app/navigation/navigation.stories.ts#L208)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

That doesn't work. You're spreading the args into the story itself. Also it's more verbose, and makes it less obvious that the default args are being included (and again, they aren't).
</blockquote></details>

Yes, I thought that was best practice for creating stories. Your Default would be your default with all the common properties needed across tests. As it is, your Default is just args which is what you were already bringing into every story. It isn't a requirement as it depends on the story you're writing.


<!-- Sent from Reviewable.io -->

2023-11-27 16:47 UTC, Nateowami commented
@nigel-wells Were you still wanting changes to this PR before it goes for testing?

2023-11-27 22:04 UTC, nigel-wells approved these changes
Just needed to review the chromatic visuals - nothing to compare them with yet so happy for them to become the baseline for future work.

> Reviewed 3 of 3 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1825#-:-NkHnnCf1WIEwzV98AaF:bys6fxd)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Nateowami)



<!-- Sent from Reviewable.io -->

2023-12-01 13:38 UTC, merged