SF-2002 Does not create an SF user label for Paratext users with edited display names
sillsdev/web-xforge pull request #1835
Opened 2023-05-09 22:49 UTC by RaymondLuong3

Using the paratext username to determine if a user is a paratext user on the project is no longer acceptable because Paratext users can update their display name. This change detects if a user is a Paratext user on the project using the SF user id, and if so, then it does not add the SF user label to the note content.
In addition, update the currentPtUsers property in ParatextSyncRunner at the start of the sync so that it is up to date at the start of the sync.

2023-05-10 04:05 UTC, Nateowami commented
@RaymondLuong3 I think the title should say "Do not" "Does not"? Also, it says "for Paratext users with edited display names". Why would we do it for any Paratext users, regardless of whether the display name is edited?

2023-05-15 20:10 UTC, pmachapman requested changes
Looks good so far - just a few questions on possible optimizations of the code, and one CodeQL warning to fix or suppress.

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1835#-:-NVW13Tc0YXYdT8EIchs:bori61w)* status: all files reviewed, 5 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 1523 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1835#-NVVzfKu9h-yt6XyI7NU:-NVVzfKu9h-yt6XyI7NV:b-55gqj8) ([raw file](https://github.com/sillsdev/web-xforge/blob/59794a20a49e79c16011ead0384700d49bfc584b/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L1523)):*
> ```Smalltalk
>                     else if (
>                         existingUser.SFUserId == null
>                         && ptUsernamesToSFUserIds.TryGetValue(existingUser.Username, out string userId)
> ```

Is this `TryGetValue` still relevant? From what I understand, _currentPtSyncUsers and ptUsernamesToSFUserIds will have the same usernames and user ids. Previously it was different, as _currentPtSyncUsers  was loaded from the project doc,
___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 1664 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1835#-NVVxCMNE60znxK-jPHN:-NVVxCMNE60znxK-jPHO:biv6f2) ([raw file](https://github.com/sillsdev/web-xforge/blob/59794a20a49e79c16011ead0384700d49bfc584b/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L1664)):*
> ```Smalltalk
>     }
> 
>     private async Task<Dictionary<string, ParatextUserProfile>> GetCurrentProjectPTUsers(CancellationToken token)
> ```

Is it practical to combine this with `GetPTUsernameToSFUserIdsAsync` above?
___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 1667 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1835#-NVW04696qac-Glxu6XV:-NVW04696qac-Glxu6XW:b-jg2io9) ([raw file](https://github.com/sillsdev/web-xforge/blob/59794a20a49e79c16011ead0384700d49bfc584b/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L1667)):*
> ```Smalltalk
>     {
>         IReadOnlyDictionary<string, string> sfUserIdsToUsernames =
>             await _paratextService.GetParatextUsernameMappingAsync(_userSecret, _projectDoc.Data, token);
> ```

With this change, `GetParatextUsernameMappingAsync`, which calls the registry, is called three times during a sync. Theoretically it should be at most called twice, the output could change when the sync to Paratext takes place (when the project is not registered, i.e. is a back translation). Is it possible to reduce the number of calls of this method per sync to 2?
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs` line 1445 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1835#-NVVx3ysB51nTz506ZVh:-NVVx3ysB51nTz506ZVi:b-rvb8aq) ([raw file](https://github.com/sillsdev/web-xforge/blob/59794a20a49e79c16011ead0384700d49bfc584b/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L1445)):*
> ```Smalltalk
>         // env.ParatextService
>         //     .GetParatextUsernameMappingAsync(Arg.Any<UserSecret>(), Arg.Any<SFProject>(), Arg.Any<CancellationToken>())
>         //     .ThrowsForAnyArgs(new OperationCanceledException());
> ```

I think it is OK to remove this block, as the sequence of execution has changed enough in ParatextSyncRunner to make it redundant.


<!-- Sent from Reviewable.io -->

2023-05-17 22:23 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1835)* status: all files reviewed, 5 unresolved discussions (waiting on @github-code-scanning[bot] and @pmachapman)

___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 1523 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1835#-NVVzfKu9h-yt6XyI7NU:-NVfcIl72en6SC75UE_5:b44qm8o) ([raw file](https://github.com/sillsdev/web-xforge/blob/59794a20a49e79c16011ead0384700d49bfc584b/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L1523)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Is this `TryGetValue` still relevant? From what I understand, _currentPtSyncUsers and ptUsernamesToSFUserIds will have the same usernames and user ids. Previously it was different, as _currentPtSyncUsers  was loaded from the project doc,
</blockquote></details>

I thought about the scenarios, and if a Paratext user gets removed from the project, they won't in the dictionary of userIds, so I think we need to keep it the way it is.
___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 1664 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1835#-NVVxCMNE60znxK-jPHN:-NVfh8Gp3BgD5mS3jK8t:b-eq6501) ([raw file](https://github.com/sillsdev/web-xforge/blob/59794a20a49e79c16011ead0384700d49bfc584b/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L1664)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Is it practical to combine this with `GetPTUsernameToSFUserIdsAsync` above?
</blockquote></details>

Yes, we can do that. Thanks for the suggestion.
___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 1667 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1835#-NVW04696qac-Glxu6XV:-NVfhvy4Aw7ddn0EUTQf:b-gy84yu) ([raw file](https://github.com/sillsdev/web-xforge/blob/59794a20a49e79c16011ead0384700d49bfc584b/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L1667)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

With this change, `GetParatextUsernameMappingAsync`, which calls the registry, is called three times during a sync. Theoretically it should be at most called twice, the output could change when the sync to Paratext takes place (when the project is not registered, i.e. is a back translation). Is it possible to reduce the number of calls of this method per sync to 2?
</blockquote></details>

Thanks for noticing this. I've updated it to only need to call `_paratextService.GetParatextUsernameMappingAsync` once
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs` line 2324 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1835#gh-1189204053:-NVfiZQ64N5Fxe7fcQUv:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/d55131e693d44be48b0c367854313dc1eac0f2da/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L2324)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Missed 'readonly' opportunity

Field '_guidStartNum' can be 'readonly'.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/516)
</blockquote></details>

Done.
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs` line 1445 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1835#-NVVx3ysB51nTz506ZVh:-NVfiQ9H3kEdq8NdkrWN:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/59794a20a49e79c16011ead0384700d49bfc584b/test/SIL.XForge.Scripture.Tests/Services/ParatextSyncRunnerTests.cs#L1445)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

I think it is OK to remove this block, as the sequence of execution has changed enough in ParatextSyncRunner to make it redundant.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-05-18 01:19 UTC, pmachapman approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r3, all commit messages.
> Dismissed @github-code-scanning[bot] from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1835#-:-NVgR7nq-pNHmV-_KOnS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2023-05-18 16:05 UTC, merged