SF-1506 Maintain consistent font size for va markers
sillsdev/web-xforge pull request #1867
Opened 2023-05-25 17:39 UTC by RaymondLuong3

Before
![image](https://github.com/sillsdev/web-xforge/assets/17931130/2622dd2c-b458-47e5-b53c-b4d146b8023e)

After
![Alternate verse markers](https://github.com/sillsdev/web-xforge/assets/17931130/74be029a-8e76-4b0a-9027-3f3b83ec49dc)

2023-05-25 17:47 UTC, Nateowami commented
I don't understand. And the screenshots are not showing a before and after of the same chapter. Can you show a before and after of the same chapter?

2023-05-28 20:57 UTC, pmachapman requested changes
The font sizing looks a more consistent with your CSS change, but the baselines are still a bit off between alternate verse numbers in paragraphs and alternate verse numbers in verse markers:

![va](https://github.com/sillsdev/web-xforge/assets/8665431/15901854-2883-4567-814d-09622ec60f21)

Should be the 5 in the screenshot have the same baseline as the 3, or the 4?

Also, a couple of things I noticed, not directly related to your PR, but related to the issue:
 1. When a `\va \va*` is mid-verse, it is editable (and does updated PT correctly on sync). Is this a bug?
 2. I wonder if readability could be improved by enclosing the alternate verse numbers in brackets (like in the example screenshot given in https://ubsicap.github.io/usfm/chapters_verses/index.html#va-va):
  
![va_brackets](https://github.com/sillsdev/web-xforge/assets/8665431/622dc34a-f0b3-412d-97b2-a0a08aba3883)

 This CSS did it for me:
```css
span[data-style='va']:before {
  content: '(';
}
span[data-style='va']:after {
  content: ')';
}
usx-char[data-style~='va']:before {
  content: '(';
}
usx-char[data-style~='va']:after {
  content: ')';
}
```

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1867#-:-NWZ8aDR7wR6DtL4jnMg:b6dhydp)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2023-05-30 16:35 UTC, RaymondLuong3 reviewed
I see what you mean, you can edit the marker if it is mid-verse. I've checked and synchronizing changes appears to work for those mid-verse markers. Maybe we can leave it as-is. I have also added the brackets to make the va markers stand out more.

As for the comments about the positioning of the VA markers, I don't think they need to be compared to the existing verse embed. I was just going for if they look acceptable on its own. I could adjust it if there is a reason to.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1867#-:-NWhUtni3dvyn6-7NcK0:bf1i1oi)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @pmachapman)



<!-- Sent from Reviewable.io -->

2023-05-30 20:02 UTC, pmachapman approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> - all good - thank you! I think the brackets will help to make the vertical alignments less jarring when close together, like in my screenshot.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1867#-:-NWiDoTb4lkjlaDObFai:bqnwo4n)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2023-05-30 20:43 UTC, merged