SF-2047 mdc to mat checking answers
sillsdev/web-xforge pull request #1873
Opened 2023-05-30 05:49 UTC by josephmyers

2023-05-30 15:05 UTC, Nateowami requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1873)* status: 0 of 12 files reviewed, 5 unresolved discussions (waiting on @github-code-scanning[bot] and @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html` line 50 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1873#-NWhAGQd5AatToAyPJc8:-NWhAGQd5AatToAyPJc9:b-s4asx9) ([raw file](https://github.com/sillsdev/web-xforge/blob/7ad2648e5632c7ba1e16810275cbf3d98733925d/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html#L50)):*
> ```HTML
>                   <mat-form-field appearance="outline">
>                     <mat-label>{{ t("your_answer") }}</mat-label>
>                     <textarea appAutofocus matInput type="text" formControlName="answerText"></textarea>
> ```

The documentation for textarea doesn't list type as a valid attribute: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss` line 272 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1873#-NWh-wI61joeEH7tv_Ux:-NWh-wI61joeEH7tv_Uy:b1x9gyh) ([raw file](https://github.com/sillsdev/web-xforge/blob/7ad2648e5632c7ba1e16810275cbf3d98733925d/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss#L272)):*
> ```SCSS
> :host ::ng-deep .mat-form-field.mat-form-field-invalid .mat-form-field-label,
> :host ::ng-deep .mat-form-field-required-marker {
>   color: var(--mdc-theme-error) !important;
> ```

I highly doubt this is the correct way to set the color when the form field is invalid. You could take a look at some other forms to see how they're themed. In general, `::ng-deep` should be avoided as it creates a tight coupling between the components. Sometimes it's unavoidable, and that's when it should be used.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-answered-dialog/question-answered-dialog.component.html` line 1 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1873#-NWh-8Ly5xQ9_BBTqaBQ:-NWh-8Ly5xQ9_BBTqaBR:b-sfnc05) ([raw file](https://github.com/sillsdev/web-xforge/blob/7ad2648e5632c7ba1e16810275cbf3d98733925d/src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-answered-dialog/question-answered-dialog.component.html#L1)):*
> ```HTML
> <ng-container *transloco="let t; read: 'question_answered_dialog'">
> ```

This component should be deleted, not converted to Material. It can be replaced with something like:
``` ts
DialogService.confirm('question_answered_dialog.some_message', 'question_answered_dialog.edit_anyway');
```

There's at least one other dialog component like this.


<!-- Sent from Reviewable.io -->

2023-06-01 06:16 UTC, josephmyers commented
I only merged with master after I epic failed the rebase. Pro tip: don't mix GH rebase with Git rebase. Also pro tip: just use Git rebase

2023-06-01 07:57 UTC, josephmyers reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1873)* status: 0 of 15 files reviewed, 5 unresolved discussions (waiting on @github-code-scanning[bot] and @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts` line 4 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1873#gh-1209922449:-NWpb16D-bCEBuPaW7xu:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/5539f2fa35bd1049004e056f47ff853d4a2f23fc/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts#L4)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Unused variable, import, function or class

Unused import MatDialog.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/530)
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html` line 50 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1873#-NWhAGQd5AatToAyPJc8:-NWpbEzO81Xe0CD_BLdu:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/7ad2648e5632c7ba1e16810275cbf3d98733925d/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html#L50)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

The documentation for textarea doesn't list type as a valid attribute: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss` line 272 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1873#-NWh-wI61joeEH7tv_Ux:-NWpxTC73lpbfFNal1fd:b-lbcctm) ([raw file](https://github.com/sillsdev/web-xforge/blob/7ad2648e5632c7ba1e16810275cbf3d98733925d/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss#L272)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I highly doubt this is the correct way to set the color when the form field is invalid. You could take a look at some other forms to see how they're themed. In general, `::ng-deep` should be avoided as it creates a tight coupling between the components. Sometimes it's unavoidable, and that's when it should be used.
</blockquote></details>

Done. I was just trying to maintain the same color from before. It should match the others now
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-answered-dialog/question-answered-dialog.component.html` line 1 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1873#-NWh-8Ly5xQ9_BBTqaBQ:-NWpcvZ-8x-jpdwjd1AI:b-p0l6mn) ([raw file](https://github.com/sillsdev/web-xforge/blob/7ad2648e5632c7ba1e16810275cbf3d98733925d/src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-answered-dialog/question-answered-dialog.component.html#L1)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This component should be deleted, not converted to Material. It can be replaced with something like:
``` ts
DialogService.confirm('question_answered_dialog.some_message', 'question_answered_dialog.edit_anyway');
```

There's at least one other dialog component like this.
</blockquote></details>

Done. Genius!
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts` line 32 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1873#gh-1209736116:-NWpd6FH54HjVVNFKFt6:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/5265ad22d837b5e8d7410428eda6ff8d9bed11e2/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/ui-common.module.ts#L32)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Useless assignment to local variable

The value assigned to MatTabsModule here is unused.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/529)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-06 17:48 UTC, Nateowami requested changes
There's way too much spacing between the answer field and the buttons below it. This spacing is caused by two things:
1. Padding under the form field
2. A hidden error message telling the user they need to add an answer.

When the keyboard is open on mobile, the amount of screen space is dramatically reduced, and screen space is very limited.

I think the reason the error message is hidden with `visibility: hidden` instead of `display: none` is so that there isn't a layout shift when it shows up. That's a nice goal, and makes sense in some contexts (e.g. on a large form on desktop), but it's not worth the cost in this case, so I think it would be better to make it not take up space when it's not shown.

As for the padding under the form field, I don't think this is easily configurable, so it might just need to be removed using `::ng-deep`.

![](https://files.reviewableusercontent.io/images/reviewable/6140710/ZchiQWvBtl94aIYKcndKLLHM/checking_answers_too_tall.png)

> Reviewed 1 of 10 files at r2, 1 of 1 files at r4, 8 of 9 files at r5, 2 of 2 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1873#-:-NXGJ9XNCtq087i8cSuD:bshmx5l)* status: all files reviewed, 10 unresolved discussions (waiting on @github-code-scanning[bot] and @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss` line 100 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1873#-NXGjtIcETXSySq6QOCs:-NXGjtIcETXSySq6QOCt:bep1f3k) ([raw file](https://github.com/sillsdev/web-xforge/blob/2c006e7213449e64c89af8d98260aca8c9240595/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss#L100)):*
> ```SCSS
>     justify-content: flex-end;
>     .mat-button:not(:first-child) {
>       margin-left: $button-spacing;
> ```

This rule is not working as intended, because the save button doesn't have the mat-button class, so this rule doesn't select it. Also, using left margin is not an ideal way of adding spacing. This rule could probably be changed to just `column-gap: $button-spacing;`
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss` line 104 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1873#-NXGeR9ICYGrnlghgDHC:-NXGeR9ICYGrnlghgDHD:b-4wg5ne) ([raw file](https://github.com/sillsdev/web-xforge/blob/2c006e7213449e64c89af8d98260aca8c9240595/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss#L104)):*
> ```SCSS
>   }
>   ::ng-deep .mat-tab-label-content {
>     flex: 1;
> ```

This is not doing anything so far as I can tell.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss` line 105 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1873#-NXGeesaELowygDYFVKP:-NXGeesaELowygDYFVKQ:b-bca895) ([raw file](https://github.com/sillsdev/web-xforge/blob/2c006e7213449e64c89af8d98260aca8c9240595/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss#L105)):*
> ```SCSS
>   ::ng-deep .mat-tab-label-content {
>     flex: 1;
>     column-gap: 8px;
> ```

This is trying to add spacing between two elements that are part of this component, not part of a Material component, so we should be able to style them without using `::ng-deep` and tightly coupling to the current Material implementation (which we know has major changes coming in the next version).

Option 1 would be to add a wrapper around the elements and then style the wrapper:
``` html
<ng-template matTabLabel>
  <span class="tab-label">
    <mat-icon>library_music</mat-icon>
    {{ media.isActive("xs") ? t("record") : t("record_upload") }}
  </span>
</ng-template>
```
``` scss
.tab-label {
  display: flex;
  align-items: center;
  column-gap: 8px;
}
```
Option 2 would be to add a class to the icon and add margin after it:
``` html
<ng-template matTabLabel>
  <mat-icon class="tab-icon">library_music</mat-icon>
  {{ media.isActive("xs") ? t("record") : t("record_upload") }}
</ng-template>
```
``` scss
.tab-icon {
  margin-inline-end: 8px;
}
```
Actually, after experimenting, I see that option 2 does not work in RTL mode, because there's a rule that sets `direction: 'ltr';` for the `material-icons` class. I'm not sure why it's needed, but it means `margin-inline-end` set on an icon will always set the margin on the right side.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss` line 108 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1873#-NXGc1Tm4ARVmYcyeDnV:-NXGc1Tm4ARVmYcyeDnW:b-e5lyl9) ([raw file](https://github.com/sillsdev/web-xforge/blob/2c006e7213449e64c89af8d98260aca8c9240595/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss#L108)):*
> ```SCSS
>   }
>   ::ng-deep .mat-ink-bar {
>     background-color: var(--mdc-theme-primary);
> ```

`::ng-deep` should be avoided any time there is a good alternative, because it creates a close coupling with other components. In this case, Material has a well-supported way of theming components. For the sake of simplicity, we don't need to deal with that in this PR. You can just remove this and we'll deal with theming later.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss` line 266 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1873#-NXGhz8q9ODgo8mYguah:-NXGhz8q9ODgo8mYguai:b8zygxr) ([raw file](https://github.com/sillsdev/web-xforge/blob/2c006e7213449e64c89af8d98260aca8c9240595/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss#L266)):*
> ```SCSS
> .mat-button {
>   line-height: unset;
>   padding: 0 8px;
> ```

This rule works about as intended, but it seems like it's almost a happy accident that it does (an accident that is likely to not last).

It seems like it's way too broad, and it would be better to add a class on just the buttons you need this style applied to.

Here's a screenshot showing what's impacted by this rule (in red):
![](https://files.reviewableusercontent.io/images/reviewable/6140710/tO-iFbwwRjI77DkHr7PR0-Y4/Screenshot%20from%202023-06-06%2013-18-26.png)

- The cancel button is having its padding reduced, which isn't that noticeable, but is an unintended effect of this overly-broad rule
- The cancel button *would* be short as well, except that it just so happens to be inside a flex container that is stretching it to the height of the tallest other element (the save answer button)
- The save answer button, remarkably, is not affected, because it just so happens that a primary button doesn't have the mat-button class. If we were to add the mat-button class to that button, we'd end up with this:
![](https://files.reviewableusercontent.io/images/reviewable/6140710/9r6dap4CmfOFdEAslRJMbzHu/Screenshot%20from%202023-06-06%2013-24-59.png)
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts` line 351 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1873#-NXGlBpO1kvql2nnOOdt:-NXGlBpO1kvql2nnOOdu:bcdg1od) ([raw file](https://github.com/sillsdev/web-xforge/blob/2c006e7213449e64c89af8d98260aca8c9240595/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts#L351)):*
> ```XML
>     const projectId = this._questionDoc.data.projectRef;
>     if (this._questionDoc.getAnswers().length > 0) {
>       const answeredDialogRef = this.dialogService.confirm(
> ```

See my comment on the checking overview component. The same issue brought up there applies here.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-com [...]

2023-06-07 06:27 UTC, josephmyers reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1873)* status: 9 of 15 files reviewed, 10 unresolved discussions (waiting on @github-code-scanning[bot] and @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss` line 100 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1873#-NXGjtIcETXSySq6QOCs:-NXJDPGR-8Sl67WkEPX9:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/2c006e7213449e64c89af8d98260aca8c9240595/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss#L100)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This rule is not working as intended, because the save button doesn't have the mat-button class, so this rule doesn't select it. Also, using left margin is not an ideal way of adding spacing. This rule could probably be changed to just `column-gap: $button-spacing;`
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss` line 104 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1873#-NXGeR9ICYGrnlghgDHC:-NXJIbXJCIrKUsMVL0Sf:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/2c006e7213449e64c89af8d98260aca8c9240595/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss#L104)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This is not doing anything so far as I can tell.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss` line 105 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1873#-NXGeesaELowygDYFVKP:-NXJLSOs3k05eQ74si0_:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/2c006e7213449e64c89af8d98260aca8c9240595/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss#L105)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This is trying to add spacing between two elements that are part of this component, not part of a Material component, so we should be able to style them without using `::ng-deep` and tightly coupling to the current Material implementation (which we know has major changes coming in the next version).

Option 1 would be to add a wrapper around the elements and then style the wrapper:
``` html
<ng-template matTabLabel>
  <span class="tab-label">
    <mat-icon>library_music</mat-icon>
    {{ media.isActive("xs") ? t("record") : t("record_upload") }}
  </span>
</ng-template>
```
``` scss
.tab-label {
  display: flex;
  align-items: center;
  column-gap: 8px;
}
```
Option 2 would be to add a class to the icon and add margin after it:
``` html
<ng-template matTabLabel>
  <mat-icon class="tab-icon">library_music</mat-icon>
  {{ media.isActive("xs") ? t("record") : t("record_upload") }}
</ng-template>
```
``` scss
.tab-icon {
  margin-inline-end: 8px;
}
```
Actually, after experimenting, I see that option 2 does not work in RTL mode, because there's a rule that sets `direction: 'ltr';` for the `material-icons` class. I'm not sure why it's needed, but it means `margin-inline-end` set on an icon will always set the margin on the right side.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss` line 108 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1873#-NXGc1Tm4ARVmYcyeDnV:-NXJLfInAt9ypPJqXVRf:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/2c006e7213449e64c89af8d98260aca8c9240595/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss#L108)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

`::ng-deep` should be avoided any time there is a good alternative, because it creates a close coupling with other components. In this case, Material has a well-supported way of theming components. For the sake of simplicity, we don't need to deal with that in this PR. You can just remove this and we'll deal with theming later.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss` line 266 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1873#-NXGhz8q9ODgo8mYguah:-NXJR_Hc-UUQMY6u5hm2:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/2c006e7213449e64c89af8d98260aca8c9240595/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss#L266)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This rule works about as intended, but it seems like it's almost a happy accident that it does (an accident that is likely to not last).

It seems like it's way too broad, and it would be better to add a class on just the buttons you need this style applied to.

Here's a screenshot showing what's impacted by this rule (in red):
![](https://files.reviewableusercontent.io/images/reviewable/6140710/tO-iFbwwRjI77DkHr7PR0-Y4/Screenshot%20from%202023-06-06%2013-18-26.png)

- The cancel button is having its padding reduced, which isn't that noticeable, but is an unintended effect of this overly-broad rule
- The cancel button *would* be short as well, except that it just so happens to be inside a flex container that is stretching it to the height of the tallest other element (the save answer button)
- The save answer button, remarkably, is not affected, because it just so happens that a primary button doesn't have the mat-button class. If we were to add the mat-button class to that button, we'd end up with this:
![](https://files.reviewableusercontent.io/images/reviewable/6140710/9r6dap4CmfOFdEAslRJMbzHu/Screenshot%20from%202023-06-06%2013-24-59.png)

</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts` line 351 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1873#-NXGlBpO1kvql2nnOOdt:-NXJXK0tE7Drjw8U4Fpr:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/2c006e7213449e64c89af8d98260aca8c9240595/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts#L351)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

See my comment on the checking overview component. The same issue brought up there applies here.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.stories.ts` line 83 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1873#-NXGoL5a-rF7TZmiLbVe:-NXJUkJG-TtiQ9ymP8Yn:bd8m1n) ([raw file](https://github.com/sillsdev/web-xforge/blob/2c006e7213449e64c89af8d98260aca8c9240595/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.stories.ts#L83)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

The decorators should be moved up to the story meta. Then you won't need to reference Template on every story. The default args can be moved as well.

See the join component stories for some ways to clean up this file. You could also look at the PR that introduced it, where we had some discussion over the improvements that were made.
</blockquote></details>

Done. It can be hard to figure out which example to use when there are multiple!
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts` line 380 at r7](https://revi [...]

2023-06-07 07:24 UTC, josephmyers reviewed
> Dismissed @github-code-scanning[bot] from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1873)* status: 8 of 15 files reviewed, 8 unresolved discussions (waiting on @Nateowami)



<!-- Sent from Reviewable.io -->

2023-06-07 07:28 UTC, josephmyers reviewed
> Reviewed 4 of 9 files at r5, 1 of 2 files at r6, 3 of 3 files at r7, 5 of 6 files at r9, 1 of 1 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1873)* status: all files reviewed, 8 unresolved discussions (waiting on @Nateowami)



<!-- Sent from Reviewable.io -->

2023-06-08 03:10 UTC, josephmyers reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1873)* status: 14 of 15 files reviewed, 4 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.stories.ts` line 106 at r12](https://reviewable.io/reviews/sillsdev/web-xforge/1873#-NXLk4MH9laqK11JtId7:-NXNwOTu2M6YK7jfSM-p:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/d3b9c4611d3b07fba1a9461929a322a06d01b74f/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.stories.ts#L106)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Instead of creating an empty object and that adding properties to it, just create it in one step:
``` ts
export const OwnComments: Story = {
  args: {
    answer: {
      ...defaultArgs.answer,
      comments: [
        createComment('comment 1', 'user01'),
        createComment('comment 2', 'user01'),
        createComment('comment 3', 'user01')
      ]
    }
  },
  play: async ({ canvasElement }) => {
    const root = within(canvasElement);
  
    const editButtons = root.getAllByRole('button', { name: /Edit/i });
    expect(editButtons.length).toBe(3);
  
    const deleteButtons = root.getAllByRole('button', { name: /Delete/i });
    expect(deleteButtons.length).toBe(3);
  }
}
```
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.stories.ts` line 108 at r12](https://reviewable.io/reviews/sillsdev/web-xforge/1873#-NXLh-ESAuU_v3pMkEnJ:-NXNwUgCEFFMOsbw8DKN:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/d3b9c4611d3b07fba1a9461929a322a06d01b74f/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.stories.ts#L108)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

You don't need to pull in defaultArgs here. It's already set in Meta.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.stories.ts` line 112 at r12](https://reviewable.io/reviews/sillsdev/web-xforge/1873#-NXLhKG6680O08K39_NE:-NXNxn0H-jWZbUw1svUc:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/d3b9c4611d3b07fba1a9461929a322a06d01b74f/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.stories.ts#L112)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

How about `createComments(['user01', 'user01', 'user01'])` here and elsewhere?

Something like:
``` ts
function createComments(userIds: string[]): Comment[] {
  return userIds.map((id, index) => createComment(`comment ${index + 1}`, id))
}
```
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.stories.ts` line 158 at r12](https://reviewable.io/reviews/sillsdev/web-xforge/1873#-NXLO5BP60f0xjNJ20Yx:-NXNxoupCn20rO7ZGMSG:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/d3b9c4611d3b07fba1a9461929a322a06d01b74f/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.stories.ts#L158)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Here we have `user3` and `user01`. In this case the inconsistency doesn't really matter, because there isn't any mocking that relies on user 3 being `user03`, but it leaves something to break in the future.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-08 03:10 UTC, josephmyers reviewed
> Reviewed 2 of 2 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1873)* status: all files reviewed, 4 unresolved discussions (waiting on @Nateowami)



<!-- Sent from Reviewable.io -->

2023-06-08 04:04 UTC, Nateowami approved these changes
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1873)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @josephmyers)



<!-- Sent from Reviewable.io -->

2023-06-08 04:16 UTC, Nateowami approved these changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1873)* status: all files reviewed, 1 unresolved discussion (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.stories.ts` line 84 at r14](https://reviewable.io/reviews/sillsdev/web-xforge/1873#-NXOBuP65KERX6yjD3hn:-NXOBuP65KERX6yjD3ho:b-hopvke) ([raw file](https://github.com/sillsdev/web-xforge/blob/06f4538b515260cd283c882a85f82226e26c643f/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.stories.ts#L84)):*
> ```XML
>         { provide: UserService, useValue: instance(mockedUserService) }
>       ],
>       declarations: [OwnerComponent]
> ```

Consider adding `CheckingCommentFormComponent` here. That would make the stories much more complete, because there would be an actual form.

(I thought you could remove the declarations and just add `CheckingModule` to the imports, but that has not been successful in my testing).


<!-- Sent from Reviewable.io -->

2023-06-08 04:42 UTC, josephmyers commented
> > _[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1873)_ status: all files reviewed, 1 unresolved discussion (waiting on @josephmyers)
> 
> _[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.stories.ts` line 84 at r14](https://reviewable.io/reviews/sillsdev/web-xforge/1873#-NXOBuP65KERX6yjD3hn:-NXOBuP65KERX6yjD3ho:b-hopvke) ([raw file](https://github.com/sillsdev/web-xforge/blob/06f4538b515260cd283c882a85f82226e26c643f/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.stories.ts#L84)):_
> 
> > ```
> >         { provide: UserService, useValue: instance(mockedUserService) }
> >       ],
> >       declarations: [OwnerComponent]
> > ```
> 
> Consider adding `CheckingCommentFormComponent` here. That would make the stories much more complete, because there would be an actual form.
> 
> (I thought you could remove the declarations and just add `CheckingModule` to the imports, but that has not been successful in my testing).

Is this something behind the scenes? I'm not seeing any visible impact to the stories

2023-06-08 14:40 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1873)* status: all files reviewed, 1 unresolved discussion (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.stories.ts` line 84 at r14](https://reviewable.io/reviews/sillsdev/web-xforge/1873#-NXOBuP65KERX6yjD3hn:-NXQRs5uBa-pVRKUCuav:bve5tkg) ([raw file](https://github.com/sillsdev/web-xforge/blob/06f4538b515260cd283c882a85f82226e26c643f/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.stories.ts#L84)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Is this something behind the scenes? I'm not seeing any visible impact to the stories
</blockquote></details>

If you click the add comment button in the stories, it doesn't load the comment form unless this is added.


<!-- Sent from Reviewable.io -->

2023-06-12 02:56 UTC, josephmyers commented
> > _[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1873)_ status: all files reviewed, 1 unresolved discussion (waiting on @josephmyers)
> 
> _[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.stories.ts` line 84 at r14](https://reviewable.io/reviews/sillsdev/web-xforge/1873#-NXOBuP65KERX6yjD3hn:-NXQRs5uBa-pVRKUCuav:bve5tkg) ([raw file](https://github.com/sillsdev/web-xforge/blob/06f4538b515260cd283c882a85f82226e26c643f/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-comments/checking-comments.stories.ts#L84)):_
> 
> Previously, josephmyers wrote…
> If you click the add comment button in the stories, it doesn't load the comment form unless this is added.

Oh snap. Awesome, thanks

2023-06-13 15:28 UTC, Nateowami approved these changes
> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1873)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @josephmyers)



<!-- Sent from Reviewable.io -->

2023-06-13 15:28 UTC, merged