SF-2088 Add model for Scripture Audio
sillsdev/web-xforge pull request #1913
Opened 2023-06-19 21:08 UTC by pmachapman

This Pull Request:
* Adds support for a new `text_audio` to ShareDB to store audio timings and references to the MP3 files
* Adds a `hasAudio` flag to the chapter object (`sf_projects.texts[].chapters[].hasAudio`)
* Adds a migrator to set this flag to `false` for every chapter of every project

2023-06-21 05:10 UTC, josephmyers approved these changes
Changes look good and appear to match the design doc. Looking forward to seeing these as we start to hook things up

> Reviewed 27 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1913#-:-NYRLsbWAuEzK2YC1vDg:bqizdqa)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)



<!-- Sent from Reviewable.io -->

2023-06-22 04:01 UTC, Nateowami requested changes
> Reviewed 27 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1913)* status: all files reviewed, 5 unresolved discussions (waiting on @pmachapman)

___
*[`src/RealtimeServer/scriptureforge/models/audio-timing.ts` line 2 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1913#-NYTwOZH3KA2g6ATqQNl:-NYTwOZH3KA2g6ATqQNm:b-rgs3b5) ([raw file](https://github.com/sillsdev/web-xforge/blob/8e30894304353b583f73b30f7dd9d6cfdc9dd114/src/RealtimeServer/scriptureforge/models/audio-timing.ts#L2)):*
> ```XML
> export interface AudioTiming {
>   verse: string;
> ```

I wonder if "verse" is the right name here? Sometimes it will be a heading or something else. Or it will be a portion of a verse.
___
*[`src/RealtimeServer/scriptureforge/models/sf-project-rights.ts` line 86 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1913#-NYTxdeG0PDAr0aEoSqS:-NYTxdeG0PDAr0aEoSqT:bq214u9) ([raw file](https://github.com/sillsdev/web-xforge/blob/8e30894304353b583f73b30f7dd9d6cfdc9dd114/src/RealtimeServer/scriptureforge/models/sf-project-rights.ts#L86)):*
> ```XML
>     sf_note_threads: ['view', 'create', 'edit', 'delete_own'],
>     notes: ['view', 'create', 'edit_own', 'delete_own'],
>     text_audio: ['view', 'edit', 'create']
> ```

Translators by default don't have permission to create or edit questions, so it doesn't make a ton of sense to give them permission to create/edit audio recordings.
___
*[`src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts` line 213 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1913#-NYWFdHR-a2NctyTHtc1:-NYWFdHR-a2NctyTHtc2:b5hgeda) ([raw file](https://github.com/sillsdev/web-xforge/blob/8e30894304353b583f73b30f7dd9d6cfdc9dd114/src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts#L213)):*
> ```XML
>  * This migration adds support for adding the hasAudio flag to chapters.
>  */
> class SFProjectMigration10 implements Migration {
> ```

I lean towards thinking the property should be optional and we don't need to migrate, but I don't have a firm reason for saying so.
___
*[`src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts` line 225 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1913#-NYTyE-E5QeWS8GxHYAF:-NYTyE-FB-8e76LsXRAs:b-5lkr39) ([raw file](https://github.com/sillsdev/web-xforge/blob/8e30894304353b583f73b30f7dd9d6cfdc9dd114/src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts#L225)):*
> ```XML
>       }
>     }
>     if (ops.length > 0) {
> ```

This check is redundant, since submitMigrationOp has the exact same check.
___
*[`src/SIL.XForge.Scripture/Models/TextAudio.cs` line 9 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1913#-NYWCiI27mqUAJvSggc1:-NYWCiI27mqUAJvSggc2:bt6t78h) ([raw file](https://github.com/sillsdev/web-xforge/blob/8e30894304353b583f73b30f7dd9d6cfdc9dd114/src/SIL.XForge.Scripture/Models/TextAudio.cs#L9)):*
> ```Smalltalk
> {
>     public string DataId { get; set; }
>     public List<AudioTiming> Timings { get; set; } = new List<AudioTiming>();
> ```

Isn't this missing `mimeType` and `audioUrl`?


<!-- Sent from Reviewable.io -->

2023-06-25 23:17 UTC, pmachapman reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1913)* status: all files reviewed, 5 unresolved discussions (waiting on @Nateowami)

___
*[`src/RealtimeServer/scriptureforge/models/audio-timing.ts` line 2 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1913#-NYTwOZH3KA2g6ATqQNl:-NYom7G44qoL5AN6SjUI:b-sxfqcw) ([raw file](https://github.com/sillsdev/web-xforge/blob/8e30894304353b583f73b30f7dd9d6cfdc9dd114/src/RealtimeServer/scriptureforge/models/audio-timing.ts#L2)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I wonder if "verse" is the right name here? Sometimes it will be a heading or something else. Or it will be a portion of a verse.
</blockquote></details>

I agree - I have renamed it to `textRef`. If you can think of a better name, I am not opposed to renaming it again.
___
*[`src/RealtimeServer/scriptureforge/models/sf-project-rights.ts` line 86 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1913#-NYTxdeG0PDAr0aEoSqS:-NYopqcE3ZPb4DaqQvgW:b-1isnj4) ([raw file](https://github.com/sillsdev/web-xforge/blob/8e30894304353b583f73b30f7dd9d6cfdc9dd114/src/RealtimeServer/scriptureforge/models/sf-project-rights.ts#L86)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Translators by default don't have permission to create or edit questions, so it doesn't make a ton of sense to give them permission to create/edit audio recordings.
</blockquote></details>

I thought that translators would be uploading audio recordings? See the workflow step "Admins upload files"
___
*[`src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts` line 213 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1913#-NYWFdHR-a2NctyTHtc1:-NYol8qk0GO6DqcOg49O:b-a715q6) ([raw file](https://github.com/sillsdev/web-xforge/blob/8e30894304353b583f73b30f7dd9d6cfdc9dd114/src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts#L213)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I lean towards thinking the property should be optional and we don't need to migrate, but I don't have a firm reason for saying so.
</blockquote></details>

After thinking on it over the weekend, I think making it optional is acceptable given that this is not a feature that is used across all projects.

In addition, coalescing `null` to `false`  is acceptable from my perspective - if our default was `true` (for some reason), I would not be making it optional.
___
*[`src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts` line 225 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1913#-NYTyE-E5QeWS8GxHYAF:-NYol_YvDXfBem_B-Fh3:b-9pahed) ([raw file](https://github.com/sillsdev/web-xforge/blob/8e30894304353b583f73b30f7dd9d6cfdc9dd114/src/RealtimeServer/scriptureforge/services/sf-project-migrations.ts#L225)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This check is redundant, since submitMigrationOp has the exact same check.
</blockquote></details>

I have removed the migration.
___
*[`src/SIL.XForge.Scripture/Models/TextAudio.cs` line 9 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1913#-NYWCiI27mqUAJvSggc1:-NYolxOCEFm6RxJ-F_q5:b-jb11fo) ([raw file](https://github.com/sillsdev/web-xforge/blob/8e30894304353b583f73b30f7dd9d6cfdc9dd114/src/SIL.XForge.Scripture/Models/TextAudio.cs#L9)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Isn't this missing `mimeType` and `audioUrl`?
</blockquote></details>

Good spotting - fixed. Such is the problem of not having an automatic synchronization of our models...


<!-- Sent from Reviewable.io -->

2023-06-26 15:40 UTC, Nateowami approved these changes
> Reviewed 21 of 21 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1913)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

___
*[`src/RealtimeServer/scriptureforge/models/audio-timing.ts` line 2 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1913#-NYTwOZH3KA2g6ATqQNl:-NYsIYlcDvppQCl5FwoL:b-ba7jcz) ([raw file](https://github.com/sillsdev/web-xforge/blob/8e30894304353b583f73b30f7dd9d6cfdc9dd114/src/RealtimeServer/scriptureforge/models/audio-timing.ts#L2)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

I agree - I have renamed it to `textRef`. If you can think of a better name, I am not opposed to renaming it again.
</blockquote></details>

Sounds good to me.
___
*[`src/RealtimeServer/scriptureforge/models/sf-project-rights.ts` line 86 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1913#-NYTxdeG0PDAr0aEoSqS:-NYsJHwHCpcasEb7nl99:b9ryrxm) ([raw file](https://github.com/sillsdev/web-xforge/blob/8e30894304353b583f73b30f7dd9d6cfdc9dd114/src/RealtimeServer/scriptureforge/models/sf-project-rights.ts#L86)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

I thought that translators would be uploading audio recordings? See the workflow step "Admins upload files"
</blockquote></details>

I don't quite understand. The section you're mentioning in the document specifically says "admins."


<!-- Sent from Reviewable.io -->

2023-06-26 20:20 UTC, pmachapman reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1913)* status: 23 of 27 files reviewed, all discussions resolved (waiting on @josephmyers and @Nateowami)

___
*[`src/RealtimeServer/scriptureforge/models/sf-project-rights.ts` line 86 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1913#-NYTxdeG0PDAr0aEoSqS:-NYtLu335U5TtyxGKjIy:ba1ds2) ([raw file](https://github.com/sillsdev/web-xforge/blob/8e30894304353b583f73b30f7dd9d6cfdc9dd114/src/RealtimeServer/scriptureforge/models/sf-project-rights.ts#L86)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I don't quite understand. The section you're mentioning in the document specifically says "admins."
</blockquote></details>

So I had a rather broad interpretation of "admins"...I have restricted the add/edit to Paratext Administrators.


<!-- Sent from Reviewable.io -->

2023-06-26 20:51 UTC, Nateowami approved these changes
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1913)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)



<!-- Sent from Reviewable.io -->

2023-06-26 20:51 UTC, merged