SF-2098 Suggestions Settings to Material
sillsdev/web-xforge pull request #1915
Opened 2023-06-21 10:01 UTC by josephmyers

2023-06-22 20:27 UTC, Nateowami requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1915)* status: all files reviewed, 2 unresolved discussions (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.html` line 5 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1915#-NYZjnUTABnDTUuMns9r:-NYZjnUTABnDTUuMns9s:bhszalk) ([raw file](https://github.com/sillsdev/web-xforge/blob/f3ff2187e113a7e3293d64c56ca91c6f3e757e87/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.html#L5)):*
> ```HTML
>   <mat-dialog-content>
>     <div class="offline-text" *ngIf="!pwaService.isOnline">{{ t("settings_not_available_offline") }}</div>
>     <mat-slide-toggle #suggestionsToggle id="suggestions-enabled-switch">{{
> ```

This is minor, but it would read better if you the curly braces were separated from the caret, on their own line:
``` html
<mat-slide-toggle #suggestionsToggle id="suggestions-enabled-switch">
  {{ t("translation_suggestions") }}
</mat-slide-toggle>
```
Prettier won't do this automatically because there's not a space between them, and in HTML the presence or lack of white space can make a difference. If you add a single space between them though and then save, Prettier will reformat it to its own line.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.ts` line 50 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1915#-NYZlDXR379JuMC1rKsN:-NYZlDXR379JuMC1rKsO:b-wyeucp) ([raw file](https://github.com/sillsdev/web-xforge/blob/f3ff2187e113a7e3293d64c56ca91c6f3e757e87/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.ts#L50)):*
> ```XML
>           );
>         });
>         this.subscribe(this.pwaService.onlineStatus$, isOnline => {
> ```

Normally it would make more sense to set this via the HTML template, something like:
``` html
<slider [disabled]="pwaService.isOnline"></slider>
```
The reason that wasn't done is because the MDC slider wouldn't let us programatically change the value when it was disabled, so this was introduced as a workaround: https://github.com/sillsdev/web-xforge/pull/682

It's also the reason why we had to subscribe to the value of the toggle, rather than just bind it to the template. Did you check whether we can do away with these subscriptions after switching to Material?


<!-- Sent from Reviewable.io -->

2023-06-26 03:13 UTC, josephmyers reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1915)* status: all files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.ts` line 50 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1915#-NYZlDXR379JuMC1rKsN:-NYpfkZ-1m00seZa0Typ:b-cligrr) ([raw file](https://github.com/sillsdev/web-xforge/blob/f3ff2187e113a7e3293d64c56ca91c6f3e757e87/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.ts#L50)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Normally it would make more sense to set this via the HTML template, something like:
``` html
<slider [disabled]="pwaService.isOnline"></slider>
```
The reason that wasn't done is because the MDC slider wouldn't let us programatically change the value when it was disabled, so this was introduced as a workaround: https://github.com/sillsdev/web-xforge/pull/682

It's also the reason why we had to subscribe to the value of the toggle, rather than just bind it to the template. Did you check whether we can do away with these subscriptions after switching to Material?
</blockquote></details>

I experimented briefly with rewriting this section (mentioned above) but opted against it ultimately. But I have no problem giving it a full look


<!-- Sent from Reviewable.io -->

2023-06-26 04:56 UTC, josephmyers reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1915)* status: 4 of 6 files reviewed, all discussions resolved (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.ts` line 50 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/1915#-NYZlDXR379JuMC1rKsN:-NYq2jWwBPzcUmNos8ZV:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/f3ff2187e113a7e3293d64c56ca91c6f3e757e87/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.ts#L50)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

I experimented briefly with rewriting this section (mentioned above) but opted against it ultimately. But I have no problem giving it a full look
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-27 05:25 UTC, Nateowami submitted a review, later dismissed
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1915)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.html` line 10 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1915#-NYsr7gNAgRuji5njPPu:-NYsr7gNAgRuji5njPPv:b-a1m7yt) ([raw file](https://github.com/sillsdev/web-xforge/blob/1bde1e538b439a61e625efa18d5e34bce565d234/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.html#L10)):*
I've run out of time to write anything longer, but this message gets logged as a warning:

> It looks like you're using the disabled attribute with a reactive form directive. If you set disabled to true
when you set up this control in your component class, the disabled attribute will actually be set in the DOM for
you. We recommend using this approach to avoid 'changed after checked' errors.
Example:
>
> // Specify the `disabled` property at control creation time:
form = new FormGroup({
  first: new FormControl({value: 'Nancy', disabled: true}, Validators.required),
  last: new FormControl('Drew', Validators.required)
});
>
> // Controls can also be enabled/disabled after creation:
form.get('first')?.enable();
form.get('last')?.disable();.

So we should probably avoid this.


<!-- Sent from Reviewable.io -->

2023-06-27 06:28 UTC, josephmyers reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1915)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.html` line 10 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1915#-NYsr7gNAgRuji5njPPu:-NYvWPpl64ivLFWtJm4m:b-rpw0kt) ([raw file](https://github.com/sillsdev/web-xforge/blob/1bde1e538b439a61e625efa18d5e34bce565d234/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.html#L10)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I've run out of time to write anything longer, but this message gets logged as a warning:

> It looks like you're using the disabled attribute with a reactive form directive. If you set disabled to true
when you set up this control in your component class, the disabled attribute will actually be set in the DOM for
you. We recommend using this approach to avoid 'changed after checked' errors.
Example:
>
> // Specify the `disabled` property at control creation time:
form = new FormGroup({
  first: new FormControl({value: 'Nancy', disabled: true}, Validators.required),
  last: new FormControl('Drew', Validators.required)
});
>
> // Controls can also be enabled/disabled after creation:
form.get('first')?.enable();
form.get('last')?.disable();.

So we should probably avoid this.
</blockquote></details>

I'm sure you can correct where I've gone wrong. There didn't appear to be any 'changed after checked' errors. They make it sound like their fix has no downsides, but I had to add a manual subscription to onlineStatus. Messed up my pretty code!


<!-- Sent from Reviewable.io -->

2023-07-04 19:52 UTC, RaymondLuong3 requested changes
Nice. Just couple minor comments.

> Reviewed 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1915#-:-NZXSc63049lKEmMDl9_:b-ql0zg1)* status: all files reviewed, 3 unresolved discussions (waiting on @josephmyers and @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.html` line 20 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1915#-NZXSJrmEEUOPD3QysyP:-NZXSJrmEEUOPD3QysyQ:b76khlw) ([raw file](https://github.com/sillsdev/web-xforge/blob/92fdf04a6478d10b63df0b342ce353fdb403230e/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.html#L20)):*
> ```HTML
>         [disabled]="settingsDisabled"
>         [(ngModel)]="numSuggestions"
>         disableOptionCentering
> ```

What does disableOptionCentering do? I'm not seeing a noticeable difference with it removed.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.spec.ts` line 150 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1915#-NZXOkT0BDy-FCPMkeRu:-NZXOkT0BDy-FCPMkeRv:b-3iv9jw) ([raw file](https://github.com/sillsdev/web-xforge/blob/92fdf04a6478d10b63df0b342ce353fdb403230e/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.spec.ts#L150)):*
> ```XML
>   }
> 
>   get matSuggestionsEnabledSwitch(): HTMLElement {
> ```

You probably can go without the mat prefix.


<!-- Sent from Reviewable.io -->

2023-07-05 02:50 UTC, josephmyers reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1915)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.html` line 20 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1915#-NZXSJrmEEUOPD3QysyP:-NZYu5SxCQ5KO8FJLeYD:b-ao1a1x) ([raw file](https://github.com/sillsdev/web-xforge/blob/92fdf04a6478d10b63df0b342ce353fdb403230e/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.html#L20)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

What does disableOptionCentering do? I'm not seeing a noticeable difference with it removed.
</blockquote></details>

Supposedly it makes the dropdown actually drop down, instead of centering itself over the field, which I had to do on the Connect Project page. But yeah, no effect here. Good catch!
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.spec.ts` line 150 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1915#-NZXOkT0BDy-FCPMkeRu:-NZYw9y-CgXwl_9FMaIn:b690wqm) ([raw file](https://github.com/sillsdev/web-xforge/blob/92fdf04a6478d10b63df0b342ce353fdb403230e/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.spec.ts#L150)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

You probably can go without the mat prefix.
</blockquote></details>

Sure. Without the prefix is already used though. I shifted things around a little.


<!-- Sent from Reviewable.io -->

2023-07-05 22:26 UTC, RaymondLuong3 approved these changes
Nice work :)

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1915#-:-NZc9YM337UU81gfO6kc:b90cghs)* status: all files reviewed, 2 unresolved discussions (waiting on @josephmyers and @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.spec.ts` line 154 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1915#-NZc9Cv580TntLWH-DBB:-NZc9Cv580TntLWH-DBC:b-qmw9k6) ([raw file](https://github.com/sillsdev/web-xforge/blob/2504595e0e8d70a8e18594ca4606d913618543b7/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions-settings-dialog.component.spec.ts#L154)):*
> ```XML
>   }
> 
>   get suggestionsEnabledCheckbox(): HTMLInputElement {
> ```

I can see why you changed this to checkbox, since that is essentially what the switch is. Just kind of strange to look for a checkbox on the dialog, but we are really trying to get the switch. No reason to hold this up for that.


<!-- Sent from Reviewable.io -->

2023-07-07 16:09 UTC, merged