Refactor audio playing to AudioPlayer
sillsdev/web-xforge pull request #1934
Opened 2023-06-28 06:06 UTC by josephmyers

2023-06-29 07:42 UTC, josephmyers commented on src/SIL.XForge.Scripture/ClientApp/src/app/shared/checking-audio-recorder.stories.ts
The slider is broken in Storybook. If someone knows how to get it working, please advise!

2023-06-29 07:51 UTC, josephmyers commented on src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-player.ts
> +    this.audio.addEventListener('timeupdate', () => {});
This is required to cause consuming components to update seek/currentTime values at the expected interval. Before, they were only updating once every few seconds. It seems less than ideal, yet better than forcing all components to listen to some new event and trigger their own UI updates.

2023-07-03 09:39 UTC, josephmyers commented on src/SIL.XForge.Scripture/ClientApp/src/app/shared/checking-audio-recorder.stories.ts
This started working after I split off the basic audio functionality to the base component. I verified it was still broken before.

2023-07-04 08:30 UTC, josephmyers commented on src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player-new/checking-audio-player-new.component.ts
> +      setTimeout(() => (this._isAudioAvailable = this.audioPlayer!.enabled));
Necessary to update asynchronously in order to avoid changing during a Change Detection cycle.

2023-07-04 20:47 UTC, RaymondLuong3 requested changes
Ok, I see that this introduces a new audioComponent and a checkingAudioPlayerNewComponent. My understanding is that we will switch out the original checkingAudioPlayerComponent at some point, but we will keep it and then when we have ample time to test, we can swap in the new one. I think this is a good approach, but it just delays the work which we could just do now. But I'm not leaning to heavily to do that.
What is the next step after this? Maybe it would be a good time to create an issue to say to swap out the original checkingAudioPlayerComponent with this one.

> Reviewed 4 of 12 files at r4, 7 of 12 files at r6, 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1934#-:-NZXdBD53jKScFmMWWq8:bnplcte)* status: all files reviewed, 6 unresolved discussions (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player-new/checking-audio-player-new.component.ts` line 22 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1934#-NZXVz196MRToFGl_QFn:-NZXVz196MRToFGl_QFo:b-fjcjt9) ([raw file](https://github.com/sillsdev/web-xforge/blob/558e87ffc4a726aa17a9e3e857dd81a729ea170d/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player-new/checking-audio-player-new.component.ts#L22)):*
> ```XML
>   ngAfterViewInit(): void {
>     this.subscribe(this.audioPlayer!.isAudioAvailableChanged, () => {
>       setTimeout(() => (this._isAudioAvailable = this.audioPlayer!.enabled));
> ```

Maybe this is an issue where we should be listening to an observable from the audio player. Perhaps a property called isEnabled$ could be added, then when it emits, we can subscribe to it an set the `_isAudioAvailable` member. I like to avoid setTimeout if there is a better way to handle it.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.component.ts` line 13 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1934#-NZXcb521SVSLjcLbgJz:-NZXcb521SVSLjcLbgK-:buh8mgm) ([raw file](https://github.com/sillsdev/web-xforge/blob/558e87ffc4a726aa17a9e3e857dd81a729ea170d/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.component.ts#L13)):*
> ```XML
>   styleUrls: ['./audio-player.component.scss']
> })
> export class AudioPlayerComponent extends SubscriptionDisposable implements OnDestroy {
> ```

This doesn't actually have an ngOnDestroy method so you can remove the implements part of this.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.component.ts` line 74 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1934#-NZXaMIu1qMYvPG-P8Yc:-NZXaMIu1qMYvPG-P8Yd:b-cgtm0t) ([raw file](https://github.com/sillsdev/web-xforge/blob/558e87ffc4a726aa17a9e3e857dd81a729ea170d/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.component.ts#L74)):*
> ```XML
> @Pipe({ name: 'audioTime' })
> export class AudioTimePipe implements PipeTransform {
>   transform(seconds: number, ..._args: any[]): string {
> ```

Add the type for minutes and seconds.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/checking-audio-recorder.stories.ts` line 0 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1934#gh-1246244940:-NZXc4yQ-xac12T7Gyse:b-9z9rvy) ([raw file](https://github.com/sillsdev/web-xforge/blob/cf62725eb640b8e24ef001d41060fd37da857886/src/SIL.XForge.Scripture/ClientApp/src/app/shared/checking-audio-recorder.stories.ts#L0)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

This started working after I split off the basic audio functionality to the base component. I verified it was still broken before.
</blockquote></details>

I think you meant for this story to exist in the `checking` folder


<!-- Sent from Reviewable.io -->

2023-07-05 04:09 UTC, josephmyers reviewed
Yeah, it'd be good to track that on the board. I can do that. The next step, based on my understanding of Nathaniel's guidance, would be to start using it in the new scripture audio components. Identify issues as we develop, and once the larger feature is ready to be integrated, we swap out the old/previous components for the new.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1934#-:-NZYz8fbDzUhG42o0ysz:blrql22)* status: 12 of 17 files reviewed, 5 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player-new/checking-audio-player-new.component.ts` line 22 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1934#-NZXVz196MRToFGl_QFn:-NZZ5YO39GXm82Pf1uc6:bula85v) ([raw file](https://github.com/sillsdev/web-xforge/blob/558e87ffc4a726aa17a9e3e857dd81a729ea170d/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player-new/checking-audio-player-new.component.ts#L22)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Maybe this is an issue where we should be listening to an observable from the audio player. Perhaps a property called isEnabled$ could be added, then when it emits, we can subscribe to it an set the `_isAudioAvailable` member. I like to avoid setTimeout if there is a better way to handle it.
</blockquote></details>

Yeah, I do, too. And I do like how your proposition cleans up the code some. However, I am seeing BehaviorSubject (assuming that was your intent) suffer from the issue I spent fixing all of yesterday. Maybe I'm misunderstanding your comment, in which case I may need a little more specific direction. The issue is that the audio's delayed loading causes the property to be updated at an uncontrolled time. So it's coming back between the two CD's, throwing NG100. See my recent checkin comment where I fixed this issue, if you haven't already. I am seeing the observable behave the same way as my manual EventEmitter. So I've checked what I have, but I haven't been able to get the observable to work without the setTimeout.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.component.ts` line 13 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1934#-NZXcb521SVSLjcLbgJz:-NZZ4mLEAL5B0rW8121Q:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/558e87ffc4a726aa17a9e3e857dd81a729ea170d/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.component.ts#L13)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This doesn't actually have an ngOnDestroy method so you can remove the implements part of this.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.component.ts` line 74 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1934#-NZXaMIu1qMYvPG-P8Yc:-NZZ4wV2623WEQuLnT8O:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/558e87ffc4a726aa17a9e3e857dd81a729ea170d/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.component.ts#L74)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Add the type for minutes and seconds.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-05 09:15 UTC, josephmyers commented
Because of an error in GH (see githubstatus.com), a couple important changes I made are not reflected in the PR. Take a look at the branch itself for the as of now two commits that didn't trigger new builds.

2023-07-05 22:50 UTC, RaymondLuong3 requested changes
Hmm, that's good to know. I'll take a look to see if I can spot the difference between this PR and the branch.

> Reviewed 4 of 5 files at r8, 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1934#-:-NZcEL3z533kskkTi2kl:b-3cnhd0)* status: all files reviewed, 7 unresolved discussions (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player-new/checking-audio-player-new.component.ts` line 22 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1934#-NZXVz196MRToFGl_QFn:-NZcAUR0CjA_ZI0DRrph:b4owasv) ([raw file](https://github.com/sillsdev/web-xforge/blob/558e87ffc4a726aa17a9e3e857dd81a729ea170d/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player-new/checking-audio-player-new.component.ts#L22)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Yeah, I do, too. And I do like how your proposition cleans up the code some. However, I am seeing BehaviorSubject (assuming that was your intent) suffer from the issue I spent fixing all of yesterday. Maybe I'm misunderstanding your comment, in which case I may need a little more specific direction. The issue is that the audio's delayed loading causes the property to be updated at an uncontrolled time. So it's coming back between the two CD's, throwing NG100. See my recent checkin comment where I fixed this issue, if you haven't already. I am seeing the observable behave the same way as my manual EventEmitter. So I've checked what I have, but I haven't been able to get the observable to work without the setTimeout.
</blockquote></details>

Ok, that is too bad we can't figure out a reliable way to definitively get isAudioAvailable at this stage in the component life cycle. I think what you are describing is what I wanted to see. I was expecting that subscribing to an observable would remove the error for value changed after component checked. Thanks for giving that a try.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.ts` line 5 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/1934#-NZcBrR200x6mAxI3gF1:-NZcBrR200x6mAxI3gF2:bhtisgy) ([raw file](https://github.com/sillsdev/web-xforge/blob/08bbab70e2202a111511f5b7cad0883749d43715/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.ts#L5)):*
> ```XML
> import { VerseRef } from 'realtime-server/lib/esm/scriptureforge/scripture-utils/verse-ref';
> import { TextDocId } from 'src/app/core/models/text-doc';
> import { AudioPlayerComponent } from 'src/app/shared/audio/audio-player.component';
> ```

Use relative paths here too.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.spec.ts` line 6 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/1934#-NZcCyyk1CTg18kpahol:-NZcCyyk1CTg18kpahom:bvhknw6) ([raw file](https://github.com/sillsdev/web-xforge/blob/08bbab70e2202a111511f5b7cad0883749d43715/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.spec.ts#L6)):*
> ```XML
> import { AudioTiming } from 'realtime-server/lib/esm/scriptureforge/models/audio-timing';
> import { of } from 'rxjs';
> import { AudioPlayerComponent } from 'src/app/shared/audio/audio-player.component';
> ```

Use relative paths.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.component.html` line 3 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/1934#-NZcDJGtDw7HiDABgYlu:-NZcDJGtDw7HiDABgYlv:b-wp7tl3) ([raw file](https://github.com/sillsdev/web-xforge/blob/08bbab70e2202a111511f5b7cad0883749d43715/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.component.html#L3)):*
> ```HTML
> <ng-container *transloco="let t; read: 'checking_audio_player'">
>   <div>
>     <div *ngIf="audio !== undefined && isAudioAvailable$.value" class="content" dir="ltr">
> ```

Instead of taking the value of the isAudioAvailable$ property, I see we typically use the async pipe. So it would look like `<div *ngIf="audio !== undefined && (isAudioAvailable$ | async)" class=..>`
This way if the isAudioAvailable$ emits, the conditional is updated. Give it a try.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.component.html` line 8 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/1934#-NZcDuyq7iaInc8mrsgy:-NZcDuyq7iaInc8mrsgz:byczwrt) ([raw file](https://github.com/sillsdev/web-xforge/blob/08bbab70e2202a111511f5b7cad0883749d43715/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.component.html#L8)):*
> ```HTML
>       <div class="duration">{{ duration | audioTime }}</div>
>     </div>
>     <div *ngIf="!isAudioAvailable$.value" class="audio-not-available">
> ```

Try the async pipe here.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player-new/checking-audio-player-new.stories.ts` line 5 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/1934#-NZcBXi7EwpY8--CntnB:-NZcBXi7EwpY8--CntnC:b-iuacle) ([raw file](https://github.com/sillsdev/web-xforge/blob/08bbab70e2202a111511f5b7cad0883749d43715/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player-new/checking-audio-player-new.stories.ts#L5)):*
> ```XML
> import { userEvent, within } from '@storybook/testing-library';
> import { of } from 'rxjs';
> import { AudioPlayerComponent, AudioTimePipe } from 'src/app/shared/audio/audio-player.component';
> ```

You'll want to use relative paths here. My editor does this to me too.


<!-- Sent from Reviewable.io -->

2023-07-06 03:25 UTC, josephmyers reviewed
It fixed itself. I didn't see the changes when I stopped work yesterday, but I see them now.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1934#-:-NZd2dwf9IcO3JRiceUP:b3escub)* status: 14 of 18 files reviewed, 7 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.ts` line 5 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/1934#-NZcBrR200x6mAxI3gF1:-NZd5Yzq2OsAq_Z5evNj:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/08bbab70e2202a111511f5b7cad0883749d43715/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.ts#L5)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Use relative paths here too.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.spec.ts` line 6 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/1934#-NZcCyyk1CTg18kpahol:-NZd5ibCEAyrbaDypxQR:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/08bbab70e2202a111511f5b7cad0883749d43715/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.spec.ts#L6)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Use relative paths.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.component.html` line 3 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/1934#-NZcDJGtDw7HiDABgYlu:-NZd65tw0lmrmGxIKz6v:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/08bbab70e2202a111511f5b7cad0883749d43715/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.component.html#L3)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Instead of taking the value of the isAudioAvailable$ property, I see we typically use the async pipe. So it would look like `<div *ngIf="audio !== undefined && (isAudioAvailable$ | async)" class=..>`
This way if the isAudioAvailable$ emits, the conditional is updated. Give it a try.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.component.html` line 8 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/1934#-NZcDuyq7iaInc8mrsgy:-NZdB7i2DmH0dc-8uBSG:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/08bbab70e2202a111511f5b7cad0883749d43715/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.component.html#L8)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Try the async pipe here.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player-new/checking-audio-player-new.stories.ts` line 5 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/1934#-NZcBXi7EwpY8--CntnB:-NZd5I2h650dpfvKgKRY:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/08bbab70e2202a111511f5b7cad0883749d43715/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player-new/checking-audio-player-new.stories.ts#L5)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

You'll want to use relative paths here. My editor does this to me too.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-06 18:18 UTC, RaymondLuong3 requested changes
Thanks for your work. Two more paths to fix. Has an issue been created to swap out the old audio component with the new one? Thanks for your work! 

> Reviewed 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1934#-:-NZgPIhU9u8XLlDERr4_:b-hrzp7s)* status: all files reviewed, 3 unresolved discussions (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.ts` line 5 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/1934#-NZcBrR200x6mAxI3gF1:-NZgPoG4353sgJWFt5zP:bfikjkz) ([raw file](https://github.com/sillsdev/web-xforge/blob/08bbab70e2202a111511f5b7cad0883749d43715/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.ts#L5)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Oops, not resolve yet.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.spec.ts` line 6 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/1934#-NZcCyyk1CTg18kpahol:-NZgPiAvDgHdbQgFOAHn:bemdlk5) ([raw file](https://github.com/sillsdev/web-xforge/blob/08bbab70e2202a111511f5b7cad0883749d43715/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.spec.ts#L6)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Oops, not resolved yet.


<!-- Sent from Reviewable.io -->

2023-07-10 08:12 UTC, josephmyers reviewed
Yep. SF-2140!

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1934#-:-NZype6v0qbbVgjs_rcH:b-tfq5er)* status: 16 of 18 files reviewed, 3 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.spec.ts` line 6 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/1934#-NZcCyyk1CTg18kpahol:-NZyqivlEGh9ZwG16OoX:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/08bbab70e2202a111511f5b7cad0883749d43715/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.spec.ts#L6)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Oops, not resolved yet.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-10 16:29 UTC, RaymondLuong3 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1934#-:-N_-ck-_8-Rdet3JJSKo:bg7igkv)* status: all files reviewed, 2 unresolved discussions



<!-- Sent from Reviewable.io -->

2023-07-10 17:17 UTC, merged

2023-07-10 17:23 UTC, Nateowami commented
@RaymondLuong3 @josephmyers Was there not an associated Jira issue?

2023-07-10 17:54 UTC, RaymondLuong3 commented
I didn't see one.