SF-2045 Back translation draft UI
sillsdev/web-xforge pull request #1961
Opened 2023-07-12 16:02 UTC by siltomato

This is the UI for the back translation draft.  It is hidden behind feature flag 'Show NMT drafting'.  Once enabled, there will be a 'Generate draft' menu item that will take user to the draft generation page.

**Draft generation page _(new)_**
- Shows instructions and requirements
- If requirements are met, user can start a pre-translation build
- User can return to this page any time to see progress or cancel build
- Once build is complete, displays options to preview draft or generate a new draft

**Draft preview page _(new)_**
- Displays draft text in blue interleaved with user's existing translation for the displayed chapter
- User can navigate chapters and 'Apply to project' an entire chapter at a time
  - Currently, users cannot selectively apply verse-by-verse
- User can click the 'Edit' button anytime to navigate to the editor for the current chapter

**Editor page additions**
- If there are any unapplied pre-translations for the current chapter _(pre-translations available and user hasn't translated all chapter verses)_, there will be a 'Preview draft' button that will navigate user to draft preview page.
- In this way, user can work and is 'notified' by the presence of the 'Preview draft' button when draft is available.
  - Maybe an additional notification can be added in the future?

**Notes**
- To experiment with a mock service, add these providers to `TranslateModule`:
```ts
@NgModule({
  ...
  providers: [
    // These providers are for testing back translation with mock service
    { provide: HttpClient, useClass: MockPreTranslationHttpClient },
    { provide: DRAFT_GENERATION_SERVICE_OPTIONS, useValue: { pollRate: 1000 } }
  ]
})
export class TranslateModule {}
```
- You can add test data to `mock-pretranslation-machine-api.ts`.  Currently, there is test data only for the first two chapters of Genesis and Exodus.
- Added `ng-circle-progress` npm package
- The circle progress animation (`ng-circle-progress`) while build is active on the draft generation page looks glitchy when using the mock service.  I think this won't be an issue for the actual service as progress updates will be much less frequent.

**TODO**

- Add i18n translations

2023-07-12 20:26 UTC, pmachapman commented on src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts
> +        this.draftJob = job;
I notice you use `draftJob` to determine whether or not a draft has been generated (and so ready for the next step).

When a build has finished, `getBuildProgress` will return a 404 - as there is not build running.

Is there another way we could calculate the "build completed" state? If there are API changes you want me to make, I can do them.

Also, I have noticed an error in my API - MachineApService.cs line 816 should be:
```cs
            case ServalApiException { StatusCode: StatusCodes.Status204NoContent }:
                return;
```

The machine-api should be telling you a 204 if there is no build running.

2023-07-12 20:29 UTC, pmachapman reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961)* status: 0 of 40 files reviewed, 1 unresolved discussion (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 70 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N_AmYx68PSh2xBnpEQO:-N_AmYx68PSh2xBnpEQP:bzbonsf) ([raw file](https://github.com/sillsdev/web-xforge/blob/e58eefbea9185514e796e66c0c961433ec770970/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L70)):*
> ```XML
>         ),
>       job => {
>         this.draftJob = job;
> ```

Not a proper review - just a comment as I was running your code.

I notice you use `draftJob` to determine whether or not a draft has been generated (and so ready for the next step).

When a build has finished, `getBuildProgress` should return a 204 - as there is no build running.

Is there another way we could calculate the "build completed" state? If there are API changes you want me to make, I can do them.

<!-- Sent from Reviewable.io -->

2023-07-17 20:56 UTC, RaymondLuong3 requested changes
Wow, there was so much work involved in this PR. It is nice to see how it looks like with most of the components and services in place, but I recommend that in the future, you just take on a smaller chunk at a time. Especially with this behind a feature flag, it would be nice to focus on a smaller piece.
I made some suggestions for you to look at. Nothing major, as I know there is still work that can come at a later time.

> Reviewed 30 of 40 files at r1, 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-:-N__cJfi2Fr1YCeflk_4:b-94an9r)* status: all files reviewed, 24 unresolved discussions (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html` line 154 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N__5MPt6EljyU0bEAXF:-N__5MPu0EEB1rUiIUlC:b-91lyao) ([raw file](https://github.com/sillsdev/web-xforge/blob/cd8040b7b81c3bb40538d0398c5b0a3b8ccbd15f/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html#L154)):*
> ```HTML
>             [appRouterLink]="getRouterLink('draft-generation')"
>           >
>             <mat-icon mat-list-icon>draw</mat-icon>
> ```

I'm not sure this is the right icon. I do like the pencil aspect, but if I looked at it without the Generate draft label, I would have no clue what the icon is for.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts` line 69 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N__5pWGBGVTRN7OeM5D:-N__5pWGBGVTRN7OeM5E:b-eurkta) ([raw file](https://github.com/sillsdev/web-xforge/blob/cd8040b7b81c3bb40538d0398c5b0a3b8ccbd15f/src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts#L69)):*
> ```XML
>     CheckingModule,
>     UsersModule,
>     UICommonModule.forRoot(),
> ```

What does this do?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/nllb-language.service.ts` line 22 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N__6I-K-fsMORa9_1IY:-N__6I-K-fsMORa9_1IZ:bi6m63d) ([raw file](https://github.com/sillsdev/web-xforge/blob/cd8040b7b81c3bb40538d0398c5b0a3b8ccbd15f/src/SIL.XForge.Scripture/ClientApp/src/app/translate/nllb-language.service.ts#L22)):*
> ```XML
>    */
>   isNllbLanguage(languageCode: string | null | undefined): boolean {
>     if (!languageCode) {
> ```

Nit: We typically spell out `languageCode == null`
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/nllb-language.service.ts` line 26 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N__6S3cB9_beQPqg14t:-N__6S3cB9_beQPqg14u:bbip1z7) ([raw file](https://github.com/sillsdev/web-xforge/blob/cd8040b7b81c3bb40538d0398c5b0a3b8ccbd15f/src/SIL.XForge.Scripture/ClientApp/src/app/translate/nllb-language.service.ts#L26)):*
> ```XML
>     }
> 
>     const code = languageCode.split('-')[0].toLowerCase();
> ```

Nit: Add types wherever you can.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/nllb-language.service.spec.ts` line 28 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N__6iijBYmkR0zlWm5y:-N__6iijBYmkR0zlWm5z:b-1qn7z6) ([raw file](https://github.com/sillsdev/web-xforge/blob/cd8040b7b81c3bb40538d0398c5b0a3b8ccbd15f/src/SIL.XForge.Scripture/ClientApp/src/app/translate/nllb-language.service.spec.ts#L28)):*
> ```XML
> 
>   it('should be created', () => {
>     expect(service).toBeTruthy();
> ```

This can be removed.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/nllb-language.service.spec.ts` line 60 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N__6wCW1tcgpBh7B3mQ:-N__6wCW1tcgpBh7B3mR:bo89fks) ([raw file](https://github.com/sillsdev/web-xforge/blob/cd8040b7b81c3bb40538d0398c5b0a3b8ccbd15f/src/SIL.XForge.Scripture/ClientApp/src/app/translate/nllb-language.service.spec.ts#L60)):*
> ```XML
> 
>     it('should return true for valid two-letter NLLB language code with culture', () => {
>       expect(service.isNllbLanguage('en-Latn-GB')).toBe(true);
> ```

Good testing.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/nllb-languages.ts` line 3 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N__7udk06PknHjGWp5D:-N__7udk06PknHjGWp5E:bi3s5qn) ([raw file](https://github.com/sillsdev/web-xforge/blob/cd8040b7b81c3bb40538d0398c5b0a3b8ccbd15f/src/SIL.XForge.Scripture/ClientApp/src/app/translate/nllb-languages.ts#L3)):*
> ```XML
> import { InjectionToken } from '@angular/core';
> 
> export interface NllbLanguage {
> ```

What do you think about adding a comment about nllb to explain where this set comes from. You can also add a url for where to access the authoritative info, and maybe instructions for how to update this file as more languages get added.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 2 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N__IoAmB8eOpxeoWUGf:-N__IoAmB8eOpxeoWUGg:b-bugqrp) ([raw file](https://github.com/sillsdev/web-xforge/blob/cd8040b7b81c3bb40538d0398c5b0a3b8ccbd15f/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L2)):*
> ```HTML
> <mat-card>
>   <h1 mat-card-title>Generate back translation drafts</h1>
> ```

You will want to internationalize this by wrapping the entire html in a ng-container and moving the strings to our non-checking.json assets file. But that can be done as a follow-up if you want.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 27 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N__Hsvw6ePujQsmQQkX:-N__Hsvw6ePujQsmQQkY:b-wq0e9a) ([raw file](https://github.com/sillsdev/web-xforge/blob/cd8040b7b81c3bb40538d0398c5b0a3b8ccbd15f/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L27)):*
> ```HTML
>       <li>
>         <mat-icon *ngIf="isTargetLanguageNllb" class="criteria-met">check</mat-icon>
>         <mat-icon *ngIf="!isTargetLanguageNllb" class="criteria-not-met">clear</mat-icon>
> ```

You might like the interpolation way to specify the icon.
`<mat-icon>{{ isTargetLanguageNllb ? "check" : "clear" }}</mat-icon>`



_Code quote:_
```HTML
        <mat-icon *ngIf="isTargetLanguageNllb" class="criteria-met">check</mat-icon>
        <mat-icon *ngIf="!isTargetLanguageNllb" class="criteria-not-met">clear</mat-icon>
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 78 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N__Kx8X202JdvA7WYIq:-N__Kx8X202JdvA7WYIr:b45xxp2) ([raw file](https://github.com/sillsdev/web-xforge/blob/cd8040b7b81c3bb40538d0398c5b0a3b8ccbd15f/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L78)):*
> ```HTML
> 
>     <ng-container *ngIf="isGenerationSupported()">
>       <section *ngIf="!draftJob; else jobExists">
> ```

Nit: Use draftJob == null



_Code quote:_
```HTML
      <section *ngIf="!draftJob; else jobExists">
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 89 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N__K9XQ8BhvWALldlPV:-N__K9XQ8BhvWALldlPW:b-pthru4) ([raw file](https://github.com/sillsdev/web-xforge/blob/cd8040b7b81c3bb40538d0398c5b0a3b8ccbd15f/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L89)):*
> ```HTML
> 
>       <ng-template #jobExists>
>         <section *ngIf="isDraftComplete(draftJob) || !isDraftInProgress(draftJob)" class="view-or-create-options">
> ```

Instead of a function that takes a draftJob parameter, you could just create a getter called `isDraftComplete` and in the ts specify the logic there. There's nothing wrong with the current approach either.



_Code quote:_
```HTML
 <section *ngIf="isDraftComplete(draftJob) || !isDraftInProgress(draftJob)" c [...]

2023-07-19 04:45 UTC, siltomato reviewed
Yes, point taken regarding smaller chunks.  =)

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-:-N_e7YHt1j0vAsn7nNXy:b-m8x41g)* status: 30 of 40 files reviewed, 9 unresolved discussions (waiting on @pmachapman and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html` line 154 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N__5MPt6EljyU0bEAXF:-N__uZ1w8p6KOmHicwpt:b7ri8qa) ([raw file](https://github.com/sillsdev/web-xforge/blob/cd8040b7b81c3bb40538d0398c5b0a3b8ccbd15f/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html#L154)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I'm not sure this is the right icon. I do like the pencil aspect, but if I looked at it without the Generate draft label, I would have no clue what the icon is for.
</blockquote></details>

Yep, good point.  Any suggestions?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts` line 69 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N__5pWGBGVTRN7OeM5D:-N__utsS-hZgkxVRg3EE:b8n59nn) ([raw file](https://github.com/sillsdev/web-xforge/blob/cd8040b7b81c3bb40538d0398c5b0a3b8ccbd15f/src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts#L69)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

What does this do?
</blockquote></details>

`NgCircleProgressModule` is declared in `UICommonModule`, and its defaults are specified using `forRoot`.  My understanding is that the `forRoot()` pattern is for registering providers at the application root, so calling it directly in `UICommonModule` `imports` array would not be right.  Calling it via `UICommonModule.forRoot()` in the app root, gets the `ModuleWithProviders` to be registered at the app root level.

Here's where `forRoot` actuallly gets called on `NgCircleProgressModule`:
```ts
export class UICommonModule {
  static forRoot(): ModuleWithProviders<UICommonModule> {
    return {
      ngModule: UICommonModule,
      providers: [
        ...(NgCircleProgressModule.forRoot({
          // Defaults
          radius: 100,
          outerStrokeWidth: 8,
          innerStrokeWidth: 4,
          outerStrokeColor: '#298ed1',
          innerStrokeColor: '#95c4e6',
          animationDuration: 1000,
          titleFontSize: '48',
          unitsFontSize: '20',
          showSubtitle: false,
          responsive: true
        }).providers ?? [])
      ]
    };
  }
}
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/nllb-language.service.ts` line 22 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N__6I-K-fsMORa9_1IY:-N_a0ooAAEiWIFadhRCi:bvqyo4o) ([raw file](https://github.com/sillsdev/web-xforge/blob/cd8040b7b81c3bb40538d0398c5b0a3b8ccbd15f/src/SIL.XForge.Scripture/ClientApp/src/app/translate/nllb-language.service.ts#L22)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Nit: We typically spell out `languageCode == null`
</blockquote></details>

Ok, I'll try to adapt to that style.  That reminds me, I should probably add some quick short-circuit checks for length.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/nllb-language.service.ts` line 26 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N__6S3cB9_beQPqg14t:-N_a1fi09i-v8Z3SVmUb:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/cd8040b7b81c3bb40538d0398c5b0a3b8ccbd15f/src/SIL.XForge.Scripture/ClientApp/src/app/translate/nllb-language.service.ts#L26)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Nit: Add types wherever you can.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/nllb-language.service.spec.ts` line 28 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N__6iijBYmkR0zlWm5y:-N_a1rtX9f9ReqddFldh:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/cd8040b7b81c3bb40538d0398c5b0a3b8ccbd15f/src/SIL.XForge.Scripture/ClientApp/src/app/translate/nllb-language.service.spec.ts#L28)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This can be removed.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/nllb-languages.ts` line 3 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N__7udk06PknHjGWp5D:-N_a2H6_7CZU4v03V-VZ:b26zpau) ([raw file](https://github.com/sillsdev/web-xforge/blob/cd8040b7b81c3bb40538d0398c5b0a3b8ccbd15f/src/SIL.XForge.Scripture/ClientApp/src/app/translate/nllb-languages.ts#L3)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

What do you think about adding a comment about nllb to explain where this set comes from. You can also add a url for where to access the authoritative info, and maybe instructions for how to update this file as more languages get added.
</blockquote></details>

Great point.  Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 2 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N__IoAmB8eOpxeoWUGf:-N_a2SUa68mOgquEbzno:b-nojzzj) ([raw file](https://github.com/sillsdev/web-xforge/blob/cd8040b7b81c3bb40538d0398c5b0a3b8ccbd15f/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L2)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

You will want to internationalize this by wrapping the entire html in a ng-container and moving the strings to our non-checking.json assets file. But that can be done as a follow-up if you want.
</blockquote></details>

Yes, I was thinking about tackling i18n in a separate issue/PR.  Created jira issue SF-2153.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 27 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N__Hsvw6ePujQsmQQkX:-N_a2pnH617sLozJMxnT:bmiskcq) ([raw file](https://github.com/sillsdev/web-xforge/blob/cd8040b7b81c3bb40538d0398c5b0a3b8ccbd15f/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L27)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

You might like the interpolation way to specify the icon.
`<mat-icon>{{ isTargetLanguageNllb ? "check" : "clear" }}</mat-icon>`
</blockquote></details>

Yes, good idea.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 78 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N__Kx8X202JdvA7WYIq:-N_a4S4iEpovHzb8cM1D:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/cd8040b7b81c3bb40538d0398c5b0a3b8ccbd15f/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L78)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Nit: Use draftJob == null
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 70 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N_AmYx68PSh2xBnpEQO:-N_dcDTW0lgctowE7pyV:b-moopxn) ([raw file](https://github.com/sillsdev/web-xforge/blob/e58eefbea9185514e796e66c0c961433ec770970/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L70)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Not a proper review - just a comment as I was running your code.

I notice you use `draftJob` to determine whether or not a draft has been generated (and so ready for the next step).

When a build has finished, `getBuildProgress` should return a 204 - as there is no bui [...]

2023-07-19 17:44 UTC, RaymondLuong3 requested changes
> Reviewed 10 of 10 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961)* status: 37 of 40 files reviewed, 6 unresolved discussions (waiting on @pmachapman and @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html` line 154 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N__5MPt6EljyU0bEAXF:-N_jElnr5h1HxAHxu7rA:b-h77kw1) ([raw file](https://github.com/sillsdev/web-xforge/blob/cd8040b7b81c3bb40538d0398c5b0a3b8ccbd15f/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html#L154)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Yep, good point.  Any suggestions?
</blockquote></details>

I did a quick search and found these. What do you think about `edit note`, `edit_document` or `contract edit`. I'm happy with either of those.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts` line 69 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N__5pWGBGVTRN7OeM5D:-N_jDESo3SJKn_LDSYmi:b-qqkl3l) ([raw file](https://github.com/sillsdev/web-xforge/blob/cd8040b7b81c3bb40538d0398c5b0a3b8ccbd15f/src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts#L69)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

`NgCircleProgressModule` is declared in `UICommonModule`, and its defaults are specified using `forRoot`.  My understanding is that the `forRoot()` pattern is for registering providers at the application root, so calling it directly in `UICommonModule` `imports` array would not be right.  Calling it via `UICommonModule.forRoot()` in the app root, gets the `ModuleWithProviders` to be registered at the app root level.

Here's where `forRoot` actuallly gets called on `NgCircleProgressModule`:
```ts
export class UICommonModule {
  static forRoot(): ModuleWithProviders<UICommonModule> {
    return {
      ngModule: UICommonModule,
      providers: [
        ...(NgCircleProgressModule.forRoot({
          // Defaults
          radius: 100,
          outerStrokeWidth: 8,
          innerStrokeWidth: 4,
          outerStrokeColor: '#298ed1',
          innerStrokeColor: '#95c4e6',
          animationDuration: 1000,
          titleFontSize: '48',
          unitsFontSize: '20',
          showSubtitle: false,
          responsive: true
        }).providers ?? [])
      ]
    };
  }
}
```

</blockquote></details>

Ok, that is good to know.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/mock-pretranslation-machine-api.ts` line 33 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N_jBPKXBN0qPLDjxtrg:-N_jBPKXBN0qPLDjxtrh:b-voot7s) ([raw file](https://github.com/sillsdev/web-xforge/blob/7116d4e69ee8f44b4e4507ad336e9c7e1ced4516/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/mock-pretranslation-machine-api.ts#L33)):*
> ```XML
>   get<T extends BuildDto | PreTranslationData | undefined>(url: string): Observable<HttpResponse<T>> {
>     const GET_DRAFT_URL_REGEX: RegExp = /^translation\/engines\/project:[^\/]+\/actions\/pretranslate\/(\d+)_(\d+)$/i;
>     const GET_BUILD_PROGRESS_URL_REGEX: RegExp = /^translation\/builds\/id:[^\/?]+\?(?-i)pretranslate=true$/i;
> ```

I think this was causing us build errors.



_Code quote:_
```XML
(?-i)
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 146 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N_jCcmN8VozRcjRL_-D:-N_jCcmN8VozRcjRL_-E:b-d7uwyq) ([raw file](https://github.com/sillsdev/web-xforge/blob/7116d4e69ee8f44b4e4507ad336e9c7e1ced4516/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L146)):*
> ```XML
> 
>   applyDraft(): void {
>     if (!this.preDraftTargetDelta?.ops) {
> ```

Nit: Use this.preDraftTargetDelta?.ops == null
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 184 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N_jEIiB56tPsqe76f29:-N_jEIiB56tPsqe76f2A:bbv5no8) ([raw file](https://github.com/sillsdev/web-xforge/blob/7116d4e69ee8f44b4e4507ad336e9c7e1ced4516/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L184)):*
> ```XML
>   navigateBookChapter(book: number, chapter: number): void {
>     this.router.navigateByUrl(
>       `/projects/${this.targetProjectId}/draft-preview/${Canon.bookNumberToId(book)}/${chapter}`
> ```

As I mentioned, this doesn't seem to navigate to the right chapter. If you choose to fix this on a follow-up, add a TODO here.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.spec.ts` line 53 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N__Wmoo7a90FZzWwXMl:-N_jDRAY8TNzLFeaHTux:bq4qng3) ([raw file](https://github.com/sillsdev/web-xforge/blob/cd8040b7b81c3bb40538d0398c5b0a3b8ccbd15f/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.spec.ts#L53)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Testing is definitely an area that I am lacking experience in.  I'll take a look at `configureTestingModule`.  Is this something that you think I should implement in the current test files, or just for future reference?
</blockquote></details>

You should be able to swap out this instance of `configureTestingModule` with the one from xforge-common/test-utils and I think we should because of the issues we had in the past with `compileComponents()` but you can choose to do that in a followup.


<!-- Sent from Reviewable.io -->

2023-07-21 06:34 UTC, siltomato reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961)* status: 26 of 40 files reviewed, 3 unresolved discussions (waiting on @pmachapman and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html` line 154 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N__5MPt6EljyU0bEAXF:-N_oCwZG5ru6ak6vVjYq:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/cd8040b7b81c3bb40538d0398c5b0a3b8ccbd15f/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html#L154)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

![image.png](https://files.reviewableusercontent.io/images/reviewable/17931130/Vo230uHAeaJkGttzYXTyHIjP/image.png)
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/mock-pretranslation-machine-api.ts` line 33 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N_jBPKXBN0qPLDjxtrg:-N_oDFNN7osMk-TZUirk:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/7116d4e69ee8f44b4e4507ad336e9c7e1ced4516/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/mock-pretranslation-machine-api.ts#L33)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I think this was causing us build errors.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 146 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N_jCcmN8VozRcjRL_-D:-N_oFIQP5CikpfB8tCfN:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/7116d4e69ee8f44b4e4507ad336e9c7e1ced4516/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L146)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Nit: Use this.preDraftTargetDelta?.ops == null
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 184 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N_jEIiB56tPsqe76f29:-N_oGWUJEC2IVpELE7sr:bql6urd) ([raw file](https://github.com/sillsdev/web-xforge/blob/7116d4e69ee8f44b4e4507ad336e9c7e1ced4516/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L184)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

As I mentioned, this doesn't seem to navigate to the right chapter. If you choose to fix this on a follow-up, add a TODO here.
</blockquote></details>

Should be fixed now.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.spec.ts` line 53 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N__Wmoo7a90FZzWwXMl:-N_r8x3w-fvz0s7G0EqQ:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/cd8040b7b81c3bb40538d0398c5b0a3b8ccbd15f/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.spec.ts#L53)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

You should be able to swap out this instance of `configureTestingModule` with the one from xforge-common/test-utils and I think we should because of the issues we had in the past with `compileComponents()` but you can choose to do that in a followup.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-21 14:51 UTC, siltomato reviewed
I added support for detecting whether any completed draft build exists for this project.  If a build has ever 'completed', there should be pre-translations available.  So, a 'preview draft' button is shown on the draft-generation page now if the latest retrieved build is not in progress or have a 'completed' state, such as if a user cancels a build.

If you run a build with the real service to completion, then start another one and cancel it, that should trigger the new UI option.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-:-N_suPdJ-Ge-5_UxOnCV:b-eci6td)* status: 26 of 40 files reviewed, 3 unresolved discussions (waiting on @pmachapman and @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2023-07-21 15:28 UTC, RaymondLuong3 requested changes
Nice, I think that is an improvement that users will have a good experience with. I have a few minor changes proposed. Thanks for swapping over to the `configureTestingModule` function, I'm glad it just worked for you.

> Reviewed 1 of 3 files at r5, 13 of 13 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-:-N_t2wGeCZ3VINMvfXvH:bc32yhh)* status: all files reviewed, 7 unresolved discussions (waiting on @pmachapman and @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts` line 91 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N_t06Cj-Xg94kERACd1:-N_t06Cj-Xg94kERACd2:b8jug5n) ([raw file](https://github.com/sillsdev/web-xforge/blob/9b79608a62d659d86d915576bcd5c3a9a262b77f/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts#L91)):*
> ```XML
> 
>   describe('ngOnInit', () => {
>     fit('should subscribe to build progress', () => {
> ```

You will want to remove the fit.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.spec.ts` line 13 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N_t0p8s2quwuV0Z8ssj:-N_t0p8s2quwuV0Z8ssk:b-n4ww3x) ([raw file](https://github.com/sillsdev/web-xforge/blob/9b79608a62d659d86d915576bcd5c3a9a262b77f/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.spec.ts#L13)):*
> ```XML
> import { of } from 'rxjs';
> import { SFProjectProfileDoc } from 'src/app/core/models/sf-project-profile-doc';
> import { SF_TYPE_REGISTRY } from 'src/app/core/models/sf-type-registry';
> ```

Use relative paths here. Looks like there are 6 imports that need cleaned up.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.spec.ts` line 41 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N_t15wP1EhhmzngvfR6:-N_t15wP1EhhmzngvfR7:b74jx3x) ([raw file](https://github.com/sillsdev/web-xforge/blob/9b79608a62d659d86d915576bcd5c3a9a262b77f/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.spec.ts#L41)):*
> ```XML
> 
>   class TestEnvironment {
>     fixture!: ComponentFixture<DraftViewerComponent>;
> ```

I don't think you need the bang since these are guaranteed to be set in the constructor.



_Code quote:_
```XML
    fixture!: ComponentFixture<DraftViewerComponent>;
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.spec.ts` line 151 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N_t1kAj6lKGs8neKH3i:-N_t1kAj6lKGs8neKH3j:b-91bm5b) ([raw file](https://github.com/sillsdev/web-xforge/blob/9b79608a62d659d86d915576bcd5c3a9a262b77f/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.spec.ts#L151)):*
> ```XML
>     tick();
> 
>     verify(mockDraftGenerationService.getGeneratedDraft('targetProjectId', 1, 2)).called();
> ```

Let's test that it just gets called once. There is a nice `.once()` I use. Here and on the other tests.



_Code quote:_
```XML
    verify(mockDraftGenerationService.getGeneratedDraft('targetProjectId', 1, 2)).called();
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 24 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N_t2bJWB2acu0ZQnQWm:-N_t2bJWB2acu0ZQnQWn:b-6cu1i5) ([raw file](https://github.com/sillsdev/web-xforge/blob/9b79608a62d659d86d915576bcd5c3a9a262b77f/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L24)):*
> ```XML
>   TranslationSuggester
> } from '@sillsdev/machine';
> import { isEmpty, isEqual, isString } from 'lodash-es';
> ```

Good to know there is an isString function. I'll use it in the future.



_Code quote:_
```XML
import { isEmpty, isEqual, isString } from 'lodash-es';
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 2015 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N_t2Xci7ulBDDcl2869:-N_t2Xci7ulBDDcl286A:b-xs1gv0) ([raw file](https://github.com/sillsdev/web-xforge/blob/9b79608a62d659d86d915576bcd5c3a9a262b77f/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L2015)):*
> ```XML
>   private checkForPreTranslations(): void {
>     const targetOps = this.target?.editor?.getContents().ops!;
>     const isChapterComplete = targetOps.every(op => {
> ```

Add types wherever possible.



_Code quote:_
```XML
    const targetOps = this.target?.editor?.getContents().ops!;
    const isChapterComplete = targetOps.every(op => {
```


<!-- Sent from Reviewable.io -->

2023-07-21 15:30 UTC, RaymondLuong3 reviewed
Can you also add steps for an acceptance test? If it requires that you use some mock data, you can create a new branch with those changes in place, and let the testers know to do testing on that branch.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-:-N_t3NW19lSbHBCG1NV-:bjmmi8g)* status: all files reviewed, 7 unresolved discussions (waiting on @pmachapman and @siltomato)



<!-- Sent from Reviewable.io -->

2023-07-21 22:26 UTC, siltomato reviewed
If they don't mind waiting for real data, using the real service would be the best.  I can make a branch for quick tests using the mock service as well.  After the PR is approved and merged, I'll fork the branch and add the mock service provider.  I'll leave a note in the jira about it for the testers.

In the latest update, I improved the mock service to add support for 'last completed build' and to handle refreshes (by storing some state in browser session storage).

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-:-N_tTrm58sHu67QDLuFS:b-glwn7l)* status: 34 of 40 files reviewed, 5 unresolved discussions (waiting on @pmachapman and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts` line 91 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N_t06Cj-Xg94kERACd1:-N_tSB4M3M3zhsGjdch2:b-sx0b7w) ([raw file](https://github.com/sillsdev/web-xforge/blob/9b79608a62d659d86d915576bcd5c3a9a262b77f/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts#L91)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

You will want to remove the fit.
</blockquote></details>

Thanks, good catch.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.spec.ts` line 13 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N_t0p8s2quwuV0Z8ssj:-N_tT8nBEJ7W7kGYK8fN:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/9b79608a62d659d86d915576bcd5c3a9a262b77f/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.spec.ts#L13)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Use relative paths here. Looks like there are 6 imports that need cleaned up.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.spec.ts` line 41 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N_t15wP1EhhmzngvfR6:-N_tOmj6DlKgKcvsQ9ec:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/9b79608a62d659d86d915576bcd5c3a9a262b77f/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.spec.ts#L41)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I don't think you need the bang since these are guaranteed to be set in the constructor.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 2015 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N_t2Xci7ulBDDcl2869:-N_tOWcz8FTjRYCSjF3R:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/9b79608a62d659d86d915576bcd5c3a9a262b77f/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L2015)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Add types wherever possible.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-24 22:14 UTC, RaymondLuong3 requested changes
Do I understand correctly that you will fork this branch and add some tests that the testers can use to confirm that this is working up to this point? If that isn't too difficult, I would prefer that we allow testing on this earlier. It makes me a little nervous when we add big chunks of code into the codebase without some knowledge it is doing what we want without unexpected side effects.

> Reviewed 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-:-Na8wq4U6CnsOTVy7KTK:bu8acpx)* status: all files reviewed, 2 unresolved discussions (waiting on @pmachapman and @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/mock-pretranslation-machine-api.ts` line 133 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-Na8wD8w5P57nhl261LO:-Na8wD8w5P57nhl261LP:bv53txf) ([raw file](https://github.com/sillsdev/web-xforge/blob/e23ff3f1730dd9e8f1176341f773667f64a3ac5e/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/mock-pretranslation-machine-api.ts#L133)):*
> ```XML
>   private startGeneration(isContinue: boolean = false): void {
>     const interval: number = 200;
>     const duration: number = 12000;
> ```

Could you leave a comment with how you got these numbers?



_Code quote:_
```XML
    const interval: number = 200;
    const duration: number = 12000;
```


<!-- Sent from Reviewable.io -->

2023-07-24 22:20 UTC, siltomato reviewed
Ya, sorry I realized I misspoke.  I made the branch `feature/SF-2045-back-translation-draft-ui_MOCK_SERVICE` for quick testing of UI functionality.  I referenced the mock service branch in the SF-2045 jira for the testers.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-:-Na8y6lw8FkRYrPGb-7M:b-1h7kyv)* status: all files reviewed, 2 unresolved discussions (waiting on @pmachapman)



<!-- Sent from Reviewable.io -->

2023-07-25 02:02 UTC, siltomato reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961)* status: 39 of 40 files reviewed, 2 unresolved discussions (waiting on @pmachapman and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/mock-pretranslation-machine-api.ts` line 133 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-Na8wD8w5P57nhl261LO:-Na9m2m8BB8Yq1zGvJ4K:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/e23ff3f1730dd9e8f1176341f773667f64a3ac5e/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/mock-pretranslation-machine-api.ts#L133)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Could you leave a comment with how you got these numbers?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-25 15:46 UTC, RaymondLuong3 approved these changes
@Nateowami I've looked through these files somewhat thoroughly and I am happy for this to get in behind a feature flag for testers to have a go at it.

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-:-NaCiWe-5jrJ01WeW7Zw:b18ix62)* status: all files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/mock-pretranslation-machine-api.ts` line 133 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-Na8wD8w5P57nhl261LO:-NaCiNAZB-zZPQMBtor6:b-yxz4bt) ([raw file](https://github.com/sillsdev/web-xforge/blob/e23ff3f1730dd9e8f1176341f773667f64a3ac5e/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/mock-pretranslation-machine-api.ts#L133)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks! It saves me trying to calculate what those numbers might mean.


<!-- Sent from Reviewable.io -->

2023-07-27 04:30 UTC, siltomato reviewed
I noticed an issue with the 'has draft' detection when in the editor.  The 'Preview draft' button displayed when there was a `note-thread-embed` object for the op insert for a verse.  This update fixes that and adds corresponding tests.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-:-NaKaYAW4K9GZl99SeQ8:b-5baycm)* status: 33 of 40 files reviewed, 1 unresolved discussion (waiting on @pmachapman and @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2023-07-27 15:43 UTC, RaymondLuong3 reviewed
Good thought. I have some style suggestions, but otherwise the changes look good.

> Reviewed 7 of 7 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-:-NaN00wZAZ0eG5tGALYL:bxusc8z)* status: all files reviewed, 5 unresolved discussions (waiting on @pmachapman and @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts` line 23 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NaMvCxg0ocCTRp7CcsA:-NaMvCxg0ocCTRp7CcsB:bwcahp5) ([raw file](https://github.com/sillsdev/web-xforge/blob/f986de5fbb64063b01312514c2eb3e3fbf3a9147/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts#L23)):*
> ```XML
>       const draftSegmentText: string = draft[op.attributes?.segment];
> 
>       if (!draftSegmentText) {
> ```

Nit: Use draftSegmentText == null
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts` line 34 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NaMyVS-BlA_roKuDS8-:-NaMyVS-BlA_roKuDS80:b-3yumpo) ([raw file](https://github.com/sillsdev/web-xforge/blob/f986de5fbb64063b01312514c2eb3e3fbf3a9147/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts#L34)):*
> ```XML
>       // Can populate draft if insert is object that has 'blank: true' property.
>       // Other objects are not draftable (e.g. 'note-thread-embed').
>       return op.insert?.blank;
> ```

Nit: op.insert?.blank != null
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts` line 53 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NaMyiew7HQS2AN53lW2:-NaMyiew7HQS2AN53lW3:b-b5aeos) ([raw file](https://github.com/sillsdev/web-xforge/blob/f986de5fbb64063b01312514c2eb3e3fbf3a9147/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts#L53)):*
> ```XML
> 
>       // No draft for this segment; use any existing translation
>       if (!draftSegmentText) {
> ```

Nit: draftSegmentText == null. Here and below.



_Code quote:_
```XML
      if (!draftSegmentText) {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 2026 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NaN-qmA0zhmpafICAvi:-NaN-qmA0zhmpafICAvj:b-j6f0bk) ([raw file](https://github.com/sillsdev/web-xforge/blob/f986de5fbb64063b01312514c2eb3e3fbf3a9147/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L2026)):*
> ```XML
> 
>         // Check if insert is object that doesn't have 'blank: true' property (e.g. 'note-thread-embed')
>         return !op.insert?.blank;
> ```

Nit: op.insert?.blank == null



_Code quote:_
```XML
  return !op.insert?.blank;
```


<!-- Sent from Reviewable.io -->

2023-07-27 20:48 UTC, siltomato reviewed
Thanks, I really appreciate the 'nits'.  I need to more explicit sometimes.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-:-NaO4-uJ6y7rndC5E_o6:bpkkqe4)* status: 39 of 40 files reviewed, 1 unresolved discussion (waiting on @pmachapman and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts` line 23 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NaMvCxg0ocCTRp7CcsA:-NaNweyg4asynv8Xq4q8:b-t4vjvy) ([raw file](https://github.com/sillsdev/web-xforge/blob/f986de5fbb64063b01312514c2eb3e3fbf3a9147/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts#L23)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Nit: Use draftSegmentText == null
</blockquote></details>

For this one, I want to check empty string as well (not sure if it is necessary, but can't hurt).  What do you think about lodash `isEmpty()`?
```ts
if (isEmpty(draftSegmentText?.trim())) {
    return false;
}
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts` line 34 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NaMyVS-BlA_roKuDS8-:-NaNxI62-IWnL86edHdc:bg7mw7j) ([raw file](https://github.com/sillsdev/web-xforge/blob/f986de5fbb64063b01312514c2eb3e3fbf3a9147/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts#L34)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Nit: op.insert?.blank != null
</blockquote></details>

In this case, the `blank` property is a boolean when it exists, and when `blank == false`, I want to return false.  
I could be more explicit with:
```ts
return op.insert?.blank === true;
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts` line 53 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NaMyiew7HQS2AN53lW2:-NaO3n68-CckxBqbIC1b:b5hwl3x) ([raw file](https://github.com/sillsdev/web-xforge/blob/f986de5fbb64063b01312514c2eb3e3fbf3a9147/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts#L53)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Nit: draftSegmentText == null. Here and below.
</blockquote></details>

Solution as above.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 2026 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NaN-qmA0zhmpafICAvi:-NaO3x0c3ezUAXbOL7HP:b5hwl3x) ([raw file](https://github.com/sillsdev/web-xforge/blob/f986de5fbb64063b01312514c2eb3e3fbf3a9147/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L2026)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Nit: op.insert?.blank == null
</blockquote></details>

Solution as above.


<!-- Sent from Reviewable.io -->

2023-07-28 16:16 UTC, RaymondLuong3 approved these changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961)* status: all files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts` line 23 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NaMvCxg0ocCTRp7CcsA:-NaSFoQn2RUrk4Hg8yba:b-muqr83) ([raw file](https://github.com/sillsdev/web-xforge/blob/f986de5fbb64063b01312514c2eb3e3fbf3a9147/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts#L23)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

For this one, I want to check empty string as well (not sure if it is necessary, but can't hurt).  What do you think about lodash `isEmpty()`?
```ts
if (isEmpty(draftSegmentText?.trim())) {
    return false;
}
```
</blockquote></details>

Ah yes, you have a point about the empty string. I looked at isEmpty, and I think this is an appropriate use. Strings are array-like, so for a 0 length string, isEmpty would be true. Similar with null objects (and undefined I assume)


<!-- Sent from Reviewable.io -->

2023-07-28 17:49 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961)* status: all files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts` line 23 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NaMvCxg0ocCTRp7CcsA:-NaSQzXQE9w7eJZGb-Fp:bg7qapn) ([raw file](https://github.com/sillsdev/web-xforge/blob/f986de5fbb64063b01312514c2eb3e3fbf3a9147/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts#L23)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Ah yes, you have a point about the empty string. I looked at isEmpty, and I think this is an appropriate use. Strings are array-like, so for a 0 length string, isEmpty would be true. Similar with null objects (and undefined I assume)
</blockquote></details>

I really don't think replacing the logical NOT operator (`!`) with `_.isEmpty()` improves readability at all.

The reason we've typically avoided coercing types to boolean values is because it usually makes it less clear what we are checking for. If you see:
``` ts
if (someValue) {
  // ...
}
```
... and `someValue` is not boolean, then it's not clear what we are guarding against (nullish values? Empty strings? 0? NaN?).

Writing `if (someValue)` or `if (!someValue)` is less clear in what we are checking for, but I can still look at it and reason about what values it guards against.

The problem with `_.isEmpty()` is that I can't reason about it without looking up the documentation, and it's not obvious from the name that it's also doing a null check. Reading the documentation, it shows that it considers null empty, but it doesn't say anything about `undefined` (I would assume it's treated the same, but we're still not told. The docs say `Checks if value is an empty object, collection, map, or set.` null is considered an object, so based on this description it might make sense to think it's considered an empty object, but undefined would not).

While falsy values can be tricky, they're part of the language, so I expect developers to have a pretty good idea how they work. A third-party function that may change in the future is a different story.

One option would be to just be verbose and check for nullish and empty values separately. Or you could just write a helper function and deal with the whitespace check at the same time:

``` ts
function isStringWithNonWhiteSpaceChars(value: unknown): boolean {
  return typeof value === 'string' && /\S/.test(value);
}
```

Just to be clear, I don't have a problem with using third-party functions when they make sense, but the discussion here was about making it extremely clear what we are and are not checking for.


<!-- Sent from Reviewable.io -->

2023-07-28 19:28 UTC, siltomato reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961)* status: all files reviewed, 2 unresolved discussions (waiting on @Nateowami, @pmachapman, and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts` line 23 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NaMvCxg0ocCTRp7CcsA:-NaSjTPE8V-NsgN7qNS8:b-umeysb) ([raw file](https://github.com/sillsdev/web-xforge/blob/f986de5fbb64063b01312514c2eb3e3fbf3a9147/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts#L23)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I really don't think replacing the logical NOT operator (`!`) with `_.isEmpty()` improves readability at all.

The reason we've typically avoided coercing types to boolean values is because it usually makes it less clear what we are checking for. If you see:
``` ts
if (someValue) {
  // ...
}
```
... and `someValue` is not boolean, then it's not clear what we are guarding against (nullish values? Empty strings? 0? NaN?).

Writing `if (someValue)` or `if (!someValue)` is less clear in what we are checking for, but I can still look at it and reason about what values it guards against.

The problem with `_.isEmpty()` is that I can't reason about it without looking up the documentation, and it's not obvious from the name that it's also doing a null check. Reading the documentation, it shows that it considers null empty, but it doesn't say anything about `undefined` (I would assume it's treated the same, but we're still not told. The docs say `Checks if value is an empty object, collection, map, or set.` null is considered an object, so based on this description it might make sense to think it's considered an empty object, but undefined would not).

While falsy values can be tricky, they're part of the language, so I expect developers to have a pretty good idea how they work. A third-party function that may change in the future is a different story.

One option would be to just be verbose and check for nullish and empty values separately. Or you could just write a helper function and deal with the whitespace check at the same time:

``` ts
function isStringWithNonWhiteSpaceChars(value: unknown): boolean {
  return typeof value === 'string' && /\S/.test(value);
}
```

Just to be clear, I don't have a problem with using third-party functions when they make sense, but the discussion here was about making it extremely clear what we are and are not checking for.
</blockquote></details>

I see what you are saying.  Maybe `isEmpty` should be reserved for checking empty objects.  As far as 3rd party utility functions go, though, lodash seems to have the trust factor if you know what i mean.  I feel like performance and edge cases have been already considered.

Ok, here's an example... I know that the function you gave above is just a quick, untested suggestion, so no knock on you at all, but it fits my case here.  If a string object instead of a string primitive were passed to that function, such as `new String('howdy')`, it would return false.

I like the function idea, though.  Maybe lodash `isString` would be appropriate here?
```ts
function isStringWithNonWhitespaceChars(value: unknown): boolean {
    return isString(value) && /\\S/.test(value);
}

// Or
function isStringWithNonWhitespaceChars(value: unknown): boolean {
    return isString(value) && value.trim();
}

// And then
if (!isStringWithNonWhitespaceChars(draftSegmentText)) {
    return false;
}
```

Alternately, since the type of `draftSegmentText` should be `string | undefined`, one of these might work?
```ts
if (!draftSegmentText?.trim()) {
    return false;
}

// Or
if (!draftSegmentText?.trim().length) {
    return false;
}
```

Is there one of these ways that looks best to you guys?


<!-- Sent from Reviewable.io -->

2023-07-28 20:24 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961)* status: all files reviewed, 2 unresolved discussions (waiting on @pmachapman, @RaymondLuong3, and @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts` line 23 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NaMvCxg0ocCTRp7CcsA:-NaT4K2e7Iv_yk62C7so:bdpy1gn) ([raw file](https://github.com/sillsdev/web-xforge/blob/f986de5fbb64063b01312514c2eb3e3fbf3a9147/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts#L23)):*
Oh wow, I was unaware that `new String()` created string-like objects. I've only used `String()`, which creates strings:
```
> String('a') === 'a'
true
> new String('a') === 'a'
false
> typeof String('a')
'string'
> typeof new String('a')
'object'
```
The same pattern holds for numbers and booleans. With very few exceptions, when we check what type something is, we always use `typeof`, so I don't think we've been mixing in non-primitives. In fact TypeScript won't let you mix them up:

``` ts
    let x = 'a';
    x = new String('b');
//  ^ Type 'String' is not assignable to type 'string'.  
//  'string' is a primitive, but 'String' is a wrapper object. Prefer using 'string' when possible.ts(2322)
    let x: string
```

On the line preceding this you've already declared the type to be `string | undefined`, so it doesn't really make sense to then check if it's a string-like object.

I would be OK with `draftSegmentText?.trim()`, as I think it's pretty clear that it contemplates both nullish values, and having only white space.

Part of the reason I went with a regex is because I think it would avoid creating new strings to be garbage collected, but most likely that's a very trivial thing (I haven't looked at the context to see how many times this would be run).


<!-- Sent from Reviewable.io -->

2023-07-28 21:02 UTC, siltomato reviewed
Removed lodash `isEmpty` use on strings.  Added draft generation requirement that project have a source project selected.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-:-NaTHmd5BpdBkIEXWV1y:b-6s2a5j)* status: 36 of 40 files reviewed, 1 unresolved discussion (waiting on @pmachapman and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts` line 23 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NaMvCxg0ocCTRp7CcsA:-NaTAZga0JHDXkJUj-LW:btzzsv3) ([raw file](https://github.com/sillsdev/web-xforge/blob/f986de5fbb64063b01312514c2eb3e3fbf3a9147/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts#L23)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Oh wow, I was unaware that `new String()` created string-like objects. I've only used `String()`, which creates strings:
```
> String('a') === 'a'
true
> new String('a') === 'a'
false
> typeof String('a')
'string'
> typeof new String('a')
'object'
```
The same pattern holds for numbers and booleans. With very few exceptions, when we check what type something is, we always use `typeof`, so I don't think we've been mixing in non-primitives. In fact TypeScript won't let you mix them up:

``` ts
    let x = 'a';
    x = new String('b');
//  ^ Type 'String' is not assignable to type 'string'.  
//  'string' is a primitive, but 'String' is a wrapper object. Prefer using 'string' when possible.ts(2322)
    let x: string
```

On the line preceding this you've already declared the type to be `string | undefined`, so it doesn't really make sense to then check if it's a string-like object.

I would be OK with `draftSegmentText?.trim()`, as I think it's pretty clear that it contemplates both nullish values, and having only white space.

Part of the reason I went with a regex is because I think it would avoid creating new strings to be garbage collected, but most likely that's a very trivial thing (I haven't looked at the context to see how many times this would be run).
</blockquote></details>

Yep, good point about the `string` type constraint not allowing string objects.

If you guys are on board, I'll go with `draftSegmentText?.trim()`


<!-- Sent from Reviewable.io -->

2023-07-31 05:35 UTC, siltomato reviewed
Peter noticed a bug where if you view Revelation 3, then change to Jude, the chapter selector is blank, but should be reset to the highest chapter in the new book (i.e. 1).  Added fix to navigate to highest chapter of book if chapter from route is above chapter range for book. Added test case.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-:-NaeNPILBs66nZT1BGzh:b-8scrz8)* status: 34 of 40 files reviewed, 2 unresolved discussions (waiting on @github-code-scanning[bot], @Nateowami, @pmachapman, and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.spec.ts` line 7 at r12](https://reviewable.io/reviews/sillsdev/web-xforge/1961#gh-1278803216:-NaeRHsS2m0XC-wChtJo:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/1a5b790febac7cef1f60028baeca5496d80083ab/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.spec.ts#L7)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Unused variable, import, function or class

Unused import DeltaStatic.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/619)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-31 16:31 UTC, RaymondLuong3 approved these changes
> Reviewed 4 of 4 files at r11, 1 of 2 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961)* status: all files reviewed, 4 unresolved discussions (waiting on @github-code-scanning[bot], @Nateowami, @pmachapman, and @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 175 at r13](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-Nagj-mZ4rhap1SppEcd:-Nagj-mZ4rhap1SppEce:b1dyd8u) ([raw file](https://github.com/sillsdev/web-xforge/blob/abc1cfdde8ad309c7acd0288ab2ea159b74128cb/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L175)):*
> ```XML
>   }
> 
>   isGenerationSupported(): boolean {
> ```

Nit: Looks like this could actually be a getter.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 105 at r13](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-Nagk8hh0YYLtrORG9Jd:-Nagk8hh0YYLtrORG9Je:b6xt8d8) ([raw file](https://github.com/sillsdev/web-xforge/blob/abc1cfdde8ad309c7acd0288ab2ea159b74128cb/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L105)):*
> ```XML
>     // Navigate to highest chapter of book if chapter from route is above chapter range for book
>     if (chapter != null && chapter > this.chapters.length) {
>       this.navigateBookChapter(book, this.chapters.length);
> ```

I would actually prefer if the navigation went to the first chapter of the new book, but I can see the rationale for this too.



_Code quote:_
```XML
      this.navigateBookChapter(book, this.chapters.length);
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts` line 23 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NaMvCxg0ocCTRp7CcsA:-NaglEI3AsFq0AWLZmTh:b-r1mbgh) ([raw file](https://github.com/sillsdev/web-xforge/blob/f986de5fbb64063b01312514c2eb3e3fbf3a9147/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts#L23)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Yep, good point about the `string` type constraint not allowing string objects.

If you guys are on board, I'll go with `draftSegmentText?.trim()`
</blockquote></details>

I can be OK with the trim approach. We know that the insert is a string, and if it is not empty, we can use it as a draft. We could compare the `op.insert.trim().length > 0` to make it more explicit, but I'm fine with how it is now because that won't work if the insert is undefined.


<!-- Sent from Reviewable.io -->

2023-07-31 17:16 UTC, RaymondLuong3 approved these changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961)* status: all files reviewed, 4 unresolved discussions (waiting on @github-code-scanning[bot], @Nateowami, @pmachapman, and @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 105 at r13](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-Nagk8hh0YYLtrORG9Jd:-NagwlMW9u9giG-VCQwJ:brvogqf) ([raw file](https://github.com/sillsdev/web-xforge/blob/abc1cfdde8ad309c7acd0288ab2ea159b74128cb/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L105)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Good point.  It makes me wonder if changing the book should always reset the chapter to 1, even if the chapter is not out of range.  Is there any reason to keep the chapter the same if the book changes?
</blockquote></details>

No, not from my perspective.


<!-- Sent from Reviewable.io -->

2023-07-31 23:03 UTC, siltomato reviewed
Changed to navigate to first included chapter of selected book on user book change OR if specified chapter from route is not a chapter for the book.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-:-Nai97j3-fuKKoYPftIN:b-pbpal9)* status: 36 of 40 files reviewed, 2 unresolved discussions (waiting on @github-code-scanning[bot], @Nateowami, @pmachapman, and @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2023-08-02 02:03 UTC, Nateowami reviewed
I've only partially reviewed the changes, but it's the end of the day so I'm going to leave my comments so far.

Nothing I've seen is critical to change, and I wouldn't hold up merging because of them. They're just suggested improvements. 

> Reviewed 11 of 40 files at r1, 1 of 10 files at r3, 3 of 10 files at r4, 2 of 13 files at r6, 3 of 7 files at r9, 1 of 5 files at r14.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-:-NanyhRg5I4ENARSHP9J:bio0ja8)* status: 36 of 40 files reviewed, 5 unresolved discussions (waiting on @github-code-scanning[bot], @pmachapman, @RaymondLuong3, and @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss` line 290 at r13](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-Nai0xl7CMiezzeu9mER:-Nai0xl7CMiezzeu9mES:b-xn0lns) ([raw file](https://github.com/sillsdev/web-xforge/blob/abc1cfdde8ad309c7acd0288ab2ea159b74128cb/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss#L290)):*
> ```SCSS
>   font-size: small;
>   background: #4678d6;
>   margin-left: auto;
> ```

Doesn't work in RTL mode. I suggest replacing both margin settings with `margin-inline-start: 0;`.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/working-animated-indicator/working-animated-indicator.component.spec.ts` line 20 at r13](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-Nai1dDP9XUjrWgZoYVv:-Nai1dDP9XUjrWgZoYVw:brkkiqs) ([raw file](https://github.com/sillsdev/web-xforge/blob/abc1cfdde8ad309c7acd0288ab2ea159b74128cb/src/SIL.XForge.Scripture/ClientApp/src/app/shared/working-animated-indicator/working-animated-indicator.component.spec.ts#L20)):*
> ```XML
> 
>   it('should create', () => {
>     expect(component).toBeTruthy();
> ```

This really doesn't test much of anything, other than that the component is constructed without error. The component is entirely visual; it seems like the ideal component to put in Storybook.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/nllb-language.service.ts` line 33 at r14](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NanwpH97NtN6suFZNV7:-NanwpH97NtN6suFZNV8:bgc8jou) ([raw file](https://github.com/sillsdev/web-xforge/blob/dc53d0d69d1cac738e2c85ec9f75428307760063/src/SIL.XForge.Scripture/ClientApp/src/app/translate/nllb-language.service.ts#L33)):*
> ```XML
>     }
> 
>     return !!findKey(this.nllbLanguages, (lang: NllbLanguage) => lang.iso639_1 === code);
> ```

How about:
``` ts
return Object.keys(nllb).includes(code) || Object.values(nllb).some(locale => locale.iso639_1 === code);
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-routing.module.ts` line 11 at r14](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NanxqP21GmhbjIkdekc:-NanxqP21GmhbjIkdekd:b-e7yw7k) ([raw file](https://github.com/sillsdev/web-xforge/blob/dc53d0d69d1cac738e2c85ec9f75428307760063/src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-routing.module.ts#L11)):*
> ```XML
> const routes: Routes = [
>   {
>     path: 'projects/:projectId/translate/:bookId/:chapter',
> ```

Nice. I have wanted to have this capability added for a long time.


<!-- Sent from Reviewable.io -->

2023-08-02 19:53 UTC, Nateowami reviewed
> Reviewed 1 of 40 files at r1, 1 of 4 files at r11, 1 of 5 files at r14, 3 of 5 files at r15.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961)* status: 36 of 41 files reviewed, 14 unresolved discussions (waiting on @github-code-scanning[bot], @pmachapman, @RaymondLuong3, and @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.ts` line 38 at r14](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NarBatvAKXsHwUQFinJ:-NarBatvAKXsHwUQFinK:b-fn2ve5) ([raw file](https://github.com/sillsdev/web-xforge/blob/dc53d0d69d1cac738e2c85ec9f75428307760063/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.ts#L38)):*
> ```XML
>  * is in one of these states.
>  */
> export const ACTIVE_BUILD_STATES = new InjectionToken<BuildStates[]>('ACTIVE_BUILD_STATES', {
> ```

I'm curious why some of these settings are injected, rather than just declaring a constant. I could see this potentially changing at some point in the future, but that wouldn't really explain the need to inject. Are the states that would be considered active be different in e.g. a testing scenario?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 27 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N__Hsvw6ePujQsmQQkX:-NarGTzx98qrcfsOKTft:b-s1s3p9) ([raw file](https://github.com/sillsdev/web-xforge/blob/cd8040b7b81c3bb40538d0398c5b0a3b8ccbd15f/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L27)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Yes, good idea.
</blockquote></details>

So, as I was reviewing this file, I did not see this conversation, because it was already resolved. And I came up with ( ... drumroll ... ) this:

``` html
        <mat-icon *ngIf="isTargetLanguageNllb" class="criteria-met">check</mat-icon>
        <mat-icon *ngIf="!isTargetLanguageNllb" class="criteria-not-met">clear</mat-icon>
```
Which is verbatim what you had before.

What I like about the `*ngIf` version is that:
- It's shorter
- It's pretty easy to see there are two mutually exclusive options (the `*ngIf` lines up vertically, and it's easy to spot that one has the `!` and the other does not)
- There's only one condition on each.

In contrast, to it took me a bit to figure out that all three conditions were based on the value of `isTargetLanguageNllb`, and so there were really only two possible outcomes from all the conditions.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 34 at r14](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NarMpbwAbGZnT5nWkKw:-NarMpbwAbGZnT5nWkKx:b-brveg0) ([raw file](https://github.com/sillsdev/web-xforge/blob/dc53d0d69d1cac738e2c85ec9f75428307760063/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L34)):*
> ```HTML
>             of <em>"{{ targetLanguageDisplayName }}"</em>
>           </ng-container>
>           is <span *ngIf="!isTargetLanguageNllb">not</span> in the
> ```

I don't think conditional words like "not" are going to work well when localizing. It's going to be a lot easier to just have two separate strings. I'm guessing you've already worked this out in your I18n PR.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 36 at r14](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NarKUNX0fa5MVqLNyQy:-NarKUNX0fa5MVqLNyQz:b-o0v341) ([raw file](https://github.com/sillsdev/web-xforge/blob/dc53d0d69d1cac738e2c85ec9f75428307760063/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L36)):*
> ```HTML
>           is <span *ngIf="!isTargetLanguageNllb">not</span> in the
>           <a
>             href="https://ai.facebook.com/research/no-language-left-behind/#200-languages-accordion"
> ```

This doesn't actually link directly to the list of languages. I'm guessing there's somewhere more helpful we could point the user to.

Possibly even just showing a table of languages directly within the app, since we have all the data available.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 60 at r14](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NarN2MV3-t8crO2BTXT:-NarN2MV3-t8crO2BTXU:byrjt34) ([raw file](https://github.com/sillsdev/web-xforge/blob/dc53d0d69d1cac738e2c85ec9f75428307760063/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L60)):*
> ```HTML
>   </section>
> 
>   <ng-container *ngIf="isReady">
> ```

Could we have a better variable name than `isReady`? Ready for what? I'm guessing it means all conditions for clicking the "generate draft" button are met (based on the context of what came before it in this component), but I can't tell for certain. 

OK, I went and checked, and it appears it means the draft is completely ready (i.e. a build has finished).
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 87 at r14](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NarL-uB5XHArc06I96k:-NarL-uB5XHArc06I96l:bdymcv8) ([raw file](https://github.com/sillsdev/web-xforge/blob/dc53d0d69d1cac738e2c85ec9f75428307760063/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L87)):*
> ```HTML
> 
>     <section *ngIf="isBackTranslation && isTargetLanguageNllb && !isSourceProjectSet">
>       <h3><mat-icon>info</mat-icon>Source text not selected</h3>
> ```

We've avoided using the info icon where possible since, I don't think it conveys the message very well in a non-English context. Admittedly, it is used in a couple other places.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 141 at r15](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NarkTnF3rDJDkJB6_ks:-NarkTnF3rDJDkJB6_kt:b-puri1) ([raw file](https://github.com/sillsdev/web-xforge/blob/b8703d9525234b72bb408055f39909ff15f215bc/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L141)):*
> ```HTML
>             </p>
> 
>             <p>A suggested workflow is to regenerate a draft after every completion of a few books.</p>
> ```

I'm not sure how accurate this is. Books vary in size by more than two orders of magnitude. Also the wording isn't the most clear, which might lead to less than accurate localization of this string.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.scss` line 54 at r14](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NarJMcIDpoSR8S9L_KW:-NarJMcIDpoSR8S9L_KX:bwuh7v) ([raw file](https://github.com/sillsdev/web-xforge/blob/dc53d0d69d1cac738e2c85ec9f75428307760063/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.scss#L54)):*
> ```SCSS
>     }
>     &.criteria-not-met {
>       color: #cc0000;
> ```

Rather than picking a new error color, we should use an existing color. For example, `var(--mdc-theme-error)` (yes, we're trying to get rid of MDC, but this is already used a number of places, and swapping it out will be easy).
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.scss` line 1 at r15](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-Narl0cZ3xW0cTgKxm6U:-Narl0cZ3xW0cTgKxm6V:bi10u8g) ([raw file](https://github.com/sillsdev/web-xforge/blob/b8703d9525234b72bb408055f39909ff15f215bc/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.scss#L1)):*
> ```SCSS
> @import 'src/variables';
> ```

Let's `@use` rather than `@import`. I [...]

2023-08-02 23:26 UTC, Nateowami reviewed
> Reviewed 1 of 40 files at r1, 1 of 13 files at r6, 1 of 6 files at r7, 2 of 5 files at r15, 1 of 4 files at r16.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961)* status: 35 of 41 files reviewed, 18 unresolved discussions (waiting on @github-code-scanning[bot], @pmachapman, @RaymondLuong3, and @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 68 at r16](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NasZ1x2-nrvgPsoqLge:-NasZ1x2-nrvgPsoqLgf:b-1l1xzg) ([raw file](https://github.com/sillsdev/web-xforge/blob/e0ea7a382bccf90ef133ec0e183f6aa83b7873fc/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L68)):*
> ```HTML
>     </section>
> 
>     <section *ngIf="infoAlert === InfoAlert.NotNllb">
> ```

How about "InfoAlert.LanguageNotSupported"? There's no guarantee that the NLLB is what we'll be using at some point in the future. Or that we'll be able to support languages that weren't part of the NLLB 200.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 86 at r16](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NasZL4zB84KcnS8X8un:-NasZL4zB84KcnS8X8uo:b-9q4fdu) ([raw file](https://github.com/sillsdev/web-xforge/blob/e0ea7a382bccf90ef133ec0e183f6aa83b7873fc/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L86)):*
> ```HTML
>     </section>
> 
>     <section *ngIf="infoAlert === InfoAlert.NotSourceProjectSet">
> ```

I thin you mean NoSourceProjectSet (not "Not")?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 94 at r16](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NasZURc-XFZQUd9VXIL:-NasZURc-XFZQUd9VXIM:b4wtkh6) ([raw file](https://github.com/sillsdev/web-xforge/blob/e0ea7a382bccf90ef133ec0e183f6aa83b7873fc/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L94)):*
> ```HTML
>     </section>
> 
>     <section *ngIf="infoAlert === InfoAlert.NotSourceAndTargetLanguageDifferent">
> ```

I do not understand what "NotSourceAndTargetLanguageDifferent". The negative makes it sound like they do differ. Maybe `InfoAlert.SourceAndTargetLanguagesIdentical`?


<!-- Sent from Reviewable.io -->

2023-08-03 00:10 UTC, Nateowami requested changes
> Reviewed 1 of 40 files at r1, 1 of 4 files at r16.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961)* status: 36 of 41 files reviewed, 20 unresolved discussions (waiting on @github-code-scanning[bot], @pmachapman, @RaymondLuong3, and @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss` line 22 at r16](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-Nas_7eQ43K1pxogbfC1:-Nas_7eQ43K1pxogbfC2:bvn9n63) ([raw file](https://github.com/sillsdev/web-xforge/blob/e0ea7a382bccf90ef133ec0e183f6aa83b7873fc/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.scss#L22)):*
> ```SCSS
> 
> .language-label {
>   height: 36px; // To match label containing button
> ```

I know this only increases the height by 7 pixels, but vertical space is quite limited, and I've actually seriously considered moving these project labels because they're already taking up too much height. A lot of users are on lower resolution devices. For an extreme example, see SF-1669. In that case it wasn't fully our fault (we didn't cause the on-screen keyboard), but even if the keyboard hadn't been there height would have been limited.

I think the best place for the "show draft" button is in the toolbar above the editor.

Also, keep in mind this page is likely where we're going to keep adding more and more functionality, so this problem is likely to get worse.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 296 at r16](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NasgDGLBCiEMI1xlK2K:-NasgDGLBCiEMI1xlK2L:b-c1y3yz) ([raw file](https://github.com/sillsdev/web-xforge/blob/e0ea7a382bccf90ef133ec0e183f6aa83b7873fc/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L296)):*
> ```XML
> 
>       // Update url to reflect current chapter
>       this.router.navigateByUrl(
> ```

Does this trigger anything, or just change the URL? I kind of expect `navigateByUrl` to trigger ActivatedRoute, which should make everything before this in the setter irrelevant. Or is that not how it works?


<!-- Sent from Reviewable.io -->

2023-08-03 23:33 UTC, siltomato reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961)* status: 25 of 41 files reviewed, 6 unresolved discussions (waiting on @github-code-scanning[bot], @Nateowami, @pmachapman, and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.ts` line 38 at r14](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NarBatvAKXsHwUQFinJ:-Nav9QqSBiQ_12b1xagF:bj8hk8r) ([raw file](https://github.com/sillsdev/web-xforge/blob/dc53d0d69d1cac738e2c85ec9f75428307760063/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.ts#L38)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I'm curious why some of these settings are injected, rather than just declaring a constant. I could see this potentially changing at some point in the future, but that wouldn't really explain the need to inject. Are the states that would be considered active be different in e.g. a testing scenario?
</blockquote></details>

Yes, I was on the fence about this one.  When thinking about how to classify it, I decided to err on the side of flexibility.  This one does seem more like constant rather than configuration, though.  I'll change it.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 27 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-N__Hsvw6ePujQsmQQkX:-NavHE3u0j3ru21s3koG:b-jpm0jz) ([raw file](https://github.com/sillsdev/web-xforge/blob/cd8040b7b81c3bb40538d0398c5b0a3b8ccbd15f/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L27)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

So, as I was reviewing this file, I did not see this conversation, because it was already resolved. And I came up with ( ... drumroll ... ) this:

``` html
        <mat-icon *ngIf="isTargetLanguageNllb" class="criteria-met">check</mat-icon>
        <mat-icon *ngIf="!isTargetLanguageNllb" class="criteria-not-met">clear</mat-icon>
```
Which is verbatim what you had before.

What I like about the `*ngIf` version is that:
- It's shorter
- It's pretty easy to see there are two mutually exclusive options (the `*ngIf` lines up vertically, and it's easy to spot that one has the `!` and the other does not)
- There's only one condition on each.

In contrast, to it took me a bit to figure out that all three conditions were based on the value of `isTargetLanguageNllb`, and so there were really only two possible outcomes from all the conditions.
</blockquote></details>

Yep, you make a good point.  I'll change it.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 34 at r14](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NarMpbwAbGZnT5nWkKw:-NavIKpG31C-aCR7B2yD:b7yypxn) ([raw file](https://github.com/sillsdev/web-xforge/blob/dc53d0d69d1cac738e2c85ec9f75428307760063/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L34)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I don't think conditional words like "not" are going to work well when localizing. It's going to be a lot easier to just have two separate strings. I'm guessing you've already worked this out in your I18n PR.
</blockquote></details>

Yes, I ran into this issue when working on the i18n.  It is handled in that PR.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 36 at r14](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NarKUNX0fa5MVqLNyQy:-NavM2VV6jX6ymgVvZDw:bsxe5z3) ([raw file](https://github.com/sillsdev/web-xforge/blob/dc53d0d69d1cac738e2c85ec9f75428307760063/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L36)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This doesn't actually link directly to the list of languages. I'm guessing there's somewhere more helpful we could point the user to.

Possibly even just showing a table of languages directly within the app, since we have all the data available.
</blockquote></details>

Yes, the link target seems broken in chromium browsers.  The link with hash is scrolling down the page properly in firefox.  I like the idea of linking to a page with context where the user can learn more rather than just an in-app table if possible.  Alternately, we could display the table of languages and show a link to "learn more".

I added a TODO.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 60 at r14](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NarN2MV3-t8crO2BTXT:-NavPdAH5aegYEzcnf36:b-ijppf4) ([raw file](https://github.com/sillsdev/web-xforge/blob/dc53d0d69d1cac738e2c85ec9f75428307760063/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L60)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Could we have a better variable name than `isReady`? Ready for what? I'm guessing it means all conditions for clicking the "generate draft" button are met (based on the context of what came before it in this component), but I can't tell for certain. 

OK, I went and checked, and it appears it means the draft is completely ready (i.e. a build has finished).
</blockquote></details>

Yes, it needs a better name.  Changed to `isDraftJobFetched` and added comment.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 87 at r14](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NarL-uB5XHArc06I96k:-NavUjo_753dzC0_FzBL:b-gsysh5) ([raw file](https://github.com/sillsdev/web-xforge/blob/dc53d0d69d1cac738e2c85ec9f75428307760063/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L87)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

We've avoided using the info icon where possible since, I don't think it conveys the message very well in a non-English context. Admittedly, it is used in a couple other places.
</blockquote></details>

What is a good alternative?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 141 at r15](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NarkTnF3rDJDkJB6_ks:-NavVtb_AW6IehDBSmz6:bic371j) ([raw file](https://github.com/sillsdev/web-xforge/blob/b8703d9525234b72bb408055f39909ff15f215bc/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L141)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I'm not sure how accurate this is. Books vary in size by more than two orders of magnitude. Also the wording isn't the most clear, which might lead to less than accurate localization of this string.
</blockquote></details>

What would be better user guidance?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 68 at r16](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NasZ1x2-nrvgPsoqLge:-NavU64-EKr93Qq54pKU:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/e0ea7a382bccf90ef133ec0e183f6aa83b7873fc/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L68)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

How about "InfoAlert.LanguageNotSupported"? There's no guarantee that the NLLB is what we'll be using at some point in the future. Or that we'll be able to support langua [...]

2023-08-04 20:16 UTC, siltomato reviewed
Reverted editor component changes to master.  These will be put in a later PR.  Also, fixed a change detection bug in the draft viewer.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-:-Nb1ArAKA-3txDQmwjhn:bjfngx3)* status: 25 of 41 files reviewed, 6 unresolved discussions (waiting on @github-code-scanning[bot], @Nateowami, @pmachapman, and @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2023-08-07 23:31 UTC, Nateowami requested changes
> Reviewed 4 of 13 files at r17, 1 of 2 files at r18, 4 of 5 files at r19.
> Dismissed @github-code-scanning[bot] from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961)* status: 34 of 41 files reviewed, 12 unresolved discussions (waiting on @github-code-scanning[bot], @pmachapman, @RaymondLuong3, and @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 87 at r14](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NarL-uB5XHArc06I96k:-Nb1-49oDeeOhg_uvS_H:bs7fexq) ([raw file](https://github.com/sillsdev/web-xforge/blob/dc53d0d69d1cac738e2c85ec9f75428307760063/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L87)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

What is a good alternative?
</blockquote></details>

The top two options I see would be a warning icon, or no icon at all.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 141 at r15](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NarkTnF3rDJDkJB6_ks:-Nb1-8b2-TCl1HK9wH4M:b7ma4au) ([raw file](https://github.com/sillsdev/web-xforge/blob/b8703d9525234b72bb408055f39909ff15f215bc/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L141)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

What would be better user guidance?
</blockquote></details>

I'm not really sure. Probably a question for the NLP team.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 86 at r19](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NbGdz3w8rZ5RyJFoe7D:-NbGdz3w8rZ5RyJFoe7E:b-aka43t) ([raw file](https://github.com/sillsdev/web-xforge/blob/db4b89316d737debac656b91331e65a3ca875548/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L86)):*
> ```XML
>   ngOnInit(): void {
>     this.subscribe(
>       combineLatest([this.activatedProject.projectId$, this.activatedProject.projectDoc$, this.i18n.locale$]),
> ```

Why are we doing a `combineLatest` of `projectId$` and `projectDoc$`? Won't this make the handler fire twice every time the project is selected?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 88 at r19](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NbGeSwP0xCQxiuzmw9s:-NbGeSwP0xCQxiuzmw9t:bgulsgl) ([raw file](https://github.com/sillsdev/web-xforge/blob/db4b89316d737debac656b91331e65a3ca875548/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L88)):*
> ```XML
>       combineLatest([this.activatedProject.projectId$, this.activatedProject.projectDoc$, this.i18n.locale$]),
>       ([projectId, projectDoc, locale]) => {
>         const translateConfig = projectDoc?.data?.translateConfig;
> ```

If the project hasn't loaded, should we really be doing anything at all in this method? Maybe just return? That would make the rest of the method much simpler because it won't need null checks.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 105 at r19](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NbGgvnF9kaMZxk8ZaOw:-NbGgvnF9kaMZxk8ZaOx:b-1lj8g0) ([raw file](https://github.com/sillsdev/web-xforge/blob/db4b89316d737debac656b91331e65a3ca875548/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L105)):*
> ```XML
> 
>     this.hasAnyCompletedBuild$ = this.draftGenerationService
>       .getLastCompletedBuild(this.activatedProject.projectId!)
> ```

It looks to me like this is not going to adapt to switching projects; it just assumes the project ID has already been set, and then subscribes to builds for that project. (This objection applies to some of the later subscriptions as well; I'm not going to comment on them separately).

Not sure the RxJS operator that would be needed; maybe `switchMap`?

Also, if this were designed to subscribe to the project ID, then it could be defined before `onInit` is called, which solves some type safety issues (right now you've asserted that it always exists, even though it doesn't).
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 127 at r19](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NbGn3A87uMkbNCi1vxr:-NbGn3A87uMkbNCi1vxs:bukg852) ([raw file](https://github.com/sillsdev/web-xforge/blob/db4b89316d737debac656b91331e65a3ca875548/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L127)):*
> ```XML
>   /**
>    * Gets the language name for the specified code rendered in the specified locale.
>    * TODO: This seems like it could be factored out as a utility function
> ```

The I18nService, not a utility function, would be the ideal place to put this. But totally fine to leave it as a TODO.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 141 at r19](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NbGoX8X-KQ7qXByFzuO:-NbGoX8X-KQ7qXByFzuP:bwdufgo) ([raw file](https://github.com/sillsdev/web-xforge/blob/db4b89316d737debac656b91331e65a3ca875548/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L141)):*
> ```XML
>   }
> 
>   async generateDraft(shouldConfirm = false): Promise<void> {
> ```

This method is named `generateDraft`, but it doesn't always do that. Also, when you read something like `generateDraft(true)`, there's no hint as to what the boolean value means. I think it would be better to write:

``` ts
async generateNewDraftClicked() {
  if (await promptUser()) {
    await this.generateDraft();
  }
}

async generateDraft() {
  // ...
}
```
I don't really like the name `generateNewDraftClicked`, but I think it's a lot more clear what it might do. And the method `generateDraft()` actually does what it says.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 143 at r19](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NbGq9IECRfJcLIsXg4M:-NbGq9IECRfJcLIsXg4N:b-r6w4wo) ([raw file](https://github.com/sillsdev/web-xforge/blob/db4b89316d737debac656b91331e65a3ca875548/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L143)):*
> ```XML
>   async generateDraft(shouldConfirm = false): Promise<void> {
>     if (shouldConfirm) {
>       const isConfirmed: boolean | undefined = await this.dialogService.openGenericDialog({
> ```

How about simplifying to:
```ts
      const isConfirmed: boolean = await this.dialogService.confirm(
        of('This will re-create any unapplied draft text! Are you sure you want to generate a new draft?'),
        of('Yes, start generation'),
        of('No')
      );
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 163 at r19](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NbHFT71AKvSneD2bEDR:-NbHFT71AKvSneD2bEDS:b-scns57) ([raw file](https://github.com/sillsdev/web-xforge/blob/db4b89316d737debac656b91331e65a3ca875548/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L163)):*
> ```XML
>           // Handle automatic closing of dialog if job finishes while cancel dialog is open
>           if (!this.canCancel(job)) {
>             this.matDialog.closeAll();
> ```

This would also close any other dialog, such as an error dialog, an edit name dialog, etc. To me that seems worse than not automatically closing the dialog at all.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-gen [...]

2023-08-08 00:18 UTC, Nateowami requested changes
> Reviewed 1 of 13 files at r17, 1 of 2 files at r18.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961)* status: 36 of 41 files reviewed, 21 unresolved discussions (waiting on @github-code-scanning[bot], @pmachapman, @RaymondLuong3, and @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts` line 39 at r19](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NbHM56r3eyqSkmiIA5j:-NbHM56r3eyqSkmiIA5k:b-3i6478) ([raw file](https://github.com/sillsdev/web-xforge/blob/db4b89316d737debac656b91331e65a3ca875548/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts#L39)):*
> ```XML
>       takeWhile(job => activeBuildStates.includes(job?.state as BuildStates), true),
>       distinct(job => `${job?.state}${job?.percentCompleted}`),
>       shareReplay({ bufferSize: 1, refCount: true })
> ```

Nice. I learned something new.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts` line 55 at r19](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NbHN23k-sBKFTqsVPjt:-NbHN23k-sBKFTqsVPju:b-vllbor) ([raw file](https://github.com/sillsdev/web-xforge/blob/db4b89316d737debac656b91331e65a3ca875548/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts#L55)):*
> ```XML
>         // Conform 'state' to BuildStates enum
>         if (res.data) {
>           res.data.state = res.data.state.toUpperCase();
> ```

If the capitalization of the state sent by the server differs from the enum, then either the server or the enum is wrong, right? And shouldn't it be fixed there, so we don't forever have to remember to map between them?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts` line 58 at r19](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NbHNKtACiPrymNCWLAs:-NbHNKtACiPrymNCWLAt:bpgp041) ([raw file](https://github.com/sillsdev/web-xforge/blob/db4b89316d737debac656b91331e65a3ca875548/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts#L58)):*
> ```XML
>         }
> 
>         if (res.data?.state === BuildStates.Faulted) {
> ```

This is now our second check for whether `res.data` exists. If it doesn't, shouldn't that throw an exception, and then from then on we don't have to have null checks in the method?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts` line 93 at r19](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NbHO07K1cDMYmqxc0Zt:-NbHO07K1cDMYmqxc0Zu:b7sgjgt) ([raw file](https://github.com/sillsdev/web-xforge/blob/db4b89316d737debac656b91331e65a3ca875548/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts#L93)):*
> ```XML
>         }),
>         catchError(err => {
>           // If project doesn't exist on ML server, return undefined
> ```

What does this mean in this context? Machine learning? I haven't seen Serval referenced this way before.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts` line 107 at r19](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NbHOr0A3f5xaEEtQDZv:-NbHOr0A3f5xaEEtQDZw:bpnf7ff) ([raw file](https://github.com/sillsdev/web-xforge/blob/db4b89316d737debac656b91331e65a3ca875548/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts#L107)):*
> ```XML
>    * @returns An observable BuildDto describing the state and progress of a currently running or just started build job.
>    */
>   startBuild(projectId: string): Observable<BuildDto | undefined> {
> ```

It seems to me that this method would be more accurately named `startBuildOrGetExisting()`, and then it would be possible to create a private method called `startBuild()` that is called by this method. That would clean this method up a bit, as the ternary operator is currently used in such a way that it's a bit difficult to read.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts` line 127 at r19](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NbHPOuu8TZWt4wBknm8:-NbHPOuu8TZWt4wBknm9:bh0n0l6) ([raw file](https://github.com/sillsdev/web-xforge/blob/db4b89316d737debac656b91331e65a3ca875548/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts#L127)):*
> ```XML
>   cancelBuild(projectId: string): Observable<void> {
>     return this.httpClient.post<void>(`translation/pretranslations/cancel`, JSON.stringify(projectId)).pipe(
>       map(res => res.data),
> ```

Why isn't there a `res.data.state = res.data.state.toUpperCase()` here as in other places?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts` line 143 at r19](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NbHQ7Do836nothnLO2S:-NbHQ7Do836nothnLO2T:b9gd6c7) ([raw file](https://github.com/sillsdev/web-xforge/blob/db4b89316d737debac656b91331e65a3ca875548/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts#L143)):*
This descritpion:
> dictionary of segmentRef -> verse

is a bit imprecise. Sometimes "verse" is used to mean "verse reference". From context I can guess that's not the case here. Also, not every segmentRef is for a verse. There are headings and other things, and verses are split/combined. So maybe `segmentRef -> segment text`?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts` line 166 at r19](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NbHRZhL-lU5YMjrfw7p:-NbHRZhL-lU5YMjrfw7q:b-1m9yip) ([raw file](https://github.com/sillsdev/web-xforge/blob/db4b89316d737debac656b91331e65a3ca875548/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts#L166)):*
> ```XML
>    */
>   private toDraftSegmentMap(preTranslations: PreTranslation[]): DraftSegmentMap {
>     return reduce(
> ```

This use of reduce is a lot harder to read and understand than a loop would be. I've used reduce before so I was able to guess what is going on and looked at the last argument to verify that `{}` was being passed as the starting value, as I expected. Even then, it took me longer to verify it was doing what I thought, and I'm guessing some developers, especially newer developers, would struggle with it even more.

Also, I'm left wondering why `preTranslations.reduce(...)` wouldn't have worked.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts` line 169 at r19](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NbHRTs8Cr1eqZ2Asu4W:-NbHRTs8Cr1eqZ2Asu4X:b-26yx0r) ([raw file](https://github.com/sillsdev/web-xforge/blob/db4b89316d737debac656b91331e65a3ca875548/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts#L169)):*
> ```XML
>       preTranslations,
>       (result: DraftSegmentMap, curr: PreTranslation) => {
>         let { success, verseRef } = VerseRef.tryParse(curr.reference);
> ```

Not all segments are for verses. Are we assuming we're not getting anything in the response other than verses?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts` line 173 at r19](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NbHUePz5oOqR3SQgVSi:-NbHUePz5oOqR3SQgVSj:b5th251) ([raw file](https://github.com/sillsdev/web-xforge/blob/db4b89316d737debac656b91331e65a3ca875548/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts#L173)):*
> Ensure single space at end

I can clearly see that this is what it does, but I have no idea why. Wouldn't segments typically not end with a space?


<!-- Sent from Reviewable.i [...]

2023-08-10 03:59 UTC, siltomato reviewed
Wow, thanks for going through this so thoroughly.  I've made changes in most places and TODOS in a few.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-:-NbRQNTe6OFDFfVlVZTI:b-r3b4mh)* status: 24 of 46 files reviewed, 13 unresolved discussions (waiting on @github-code-scanning[bot], @Nateowami, @pmachapman, and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 87 at r14](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NarL-uB5XHArc06I96k:-NbKhN8oDpdBefFVgVtt:b-tohhbk) ([raw file](https://github.com/sillsdev/web-xforge/blob/dc53d0d69d1cac738e2c85ec9f75428307760063/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L87)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

The top two options I see would be a warning icon, or no icon at all.
</blockquote></details>

Removed icon.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 141 at r15](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NarkTnF3rDJDkJB6_ks:-NbPoFJj4NiIWA2lXnNY:b-xif9f0) ([raw file](https://github.com/sillsdev/web-xforge/blob/b8703d9525234b72bb408055f39909ff15f215bc/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L141)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I'm not really sure. Probably a question for the NLP team.
</blockquote></details>

I talked to John Lambert, and he mentioned that one chapter would be a good amount to do retraining.  

He also mentioned that there doesn't currently need to be any limit on build requests per day/week, but eventually a limit something like once a week if a chapter is completed, or 5 chapters completed would allow a retrain that day.

Changed text and added TODO to add logic to not offer regeneration until some determined unit of work is complete.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 86 at r19](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NbGdz3w8rZ5RyJFoe7D:-NbHWKkh3rv-br77O2b7:b-1g1q9d) ([raw file](https://github.com/sillsdev/web-xforge/blob/db4b89316d737debac656b91331e65a3ca875548/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L86)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Why are we doing a `combineLatest` of `projectId$` and `projectDoc$`? Won't this make the handler fire twice every time the project is selected?
</blockquote></details>

`combineLatest` won't fire until all observables have emitted at least once.  I combined them this way in case the locale changes, figuring the project won't change on this component (if it does, the app routes away from this component).

But, you make a good point... I shouldn't rely on this.  Maybe a more correct way would be to zip the `projectId$` and `projectDoc$` and `combineLatest` that with` locale$`.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 88 at r19](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NbGeSwP0xCQxiuzmw9s:-NbL7PsdCsH8LF3aeuAS:bqqi41w) ([raw file](https://github.com/sillsdev/web-xforge/blob/db4b89316d737debac656b91331e65a3ca875548/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L88)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

If the project hasn't loaded, should we really be doing anything at all in this method? Maybe just return? That would make the rest of the method much simpler because it won't need null checks.
</blockquote></details>

Added `filter` to the observables to filter out undefined.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 105 at r19](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NbGgvnF9kaMZxk8ZaOw:-NbLB8Xa1CrhMB7EmM8-:b8mdmry) ([raw file](https://github.com/sillsdev/web-xforge/blob/db4b89316d737debac656b91331e65a3ca875548/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L105)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

It looks to me like this is not going to adapt to switching projects; it just assumes the project ID has already been set, and then subscribes to builds for that project. (This objection applies to some of the later subscriptions as well; I'm not going to comment on them separately).

Not sure the RxJS operator that would be needed; maybe `switchMap`?

Also, if this were designed to subscribe to the project ID, then it could be defined before `onInit` is called, which solves some type safety issues (right now you've asserted that it always exists, even though it doesn't).
</blockquote></details>

I was making some assumptions due to how `ActivateProjectService` gets the project id.  Currently project id is always available from the route before `ngOnInit()` is called, but it would be more robust if I just subscribed to `projectId$`.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 127 at r19](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NbGn3A87uMkbNCi1vxr:-NbQe_8W7J-XABFZ4Dnf:b-xgajqg) ([raw file](https://github.com/sillsdev/web-xforge/blob/db4b89316d737debac656b91331e65a3ca875548/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L127)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

The I18nService, not a utility function, would be the ideal place to put this. But totally fine to leave it as a TODO.
</blockquote></details>

Moved to `I18nService`.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 141 at r19](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NbGoX8X-KQ7qXByFzuO:-NbQUWa70V3OMMFlUmPf:b-ax934z) ([raw file](https://github.com/sillsdev/web-xforge/blob/db4b89316d737debac656b91331e65a3ca875548/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L141)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This method is named `generateDraft`, but it doesn't always do that. Also, when you read something like `generateDraft(true)`, there's no hint as to what the boolean value means. I think it would be better to write:

``` ts
async generateNewDraftClicked() {
  if (await promptUser()) {
    await this.generateDraft();
  }
}

async generateDraft() {
  // ...
}
```
I don't really like the name `generateNewDraftClicked`, but I think it's a lot more clear what it might do. And the method `generateDraft()` actually does what it says.
</blockquote></details>

What do you think about:
```ts
async generateDraft({ withConfirm = false } = {}): Promise<void> {
    if (withConfirm) {
        // ...
```
Then the option name would need to be specified
```html
<button (click)="generateDraft({ withConfirm: true })">
    Generate draft
</button>

<-- Or could be called without option if no confirmation needed -->
<button (click)="generateDraft()">
    Generate draft
</button>
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 143 at r19](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NbGq9IECRfJcLIsXg4M:-NbQbqdm88XRJzONaSgZ:bt9ijnv) ([raw file](https://github.com/sillsdev/web-xforge/blob/db4b89316d737debac656b91331e65a3ca875548/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generat [...]

2023-08-14 14:21 UTC, siltomato reviewed
Peter added upper casing to the 'QUEUED' and 'FAULTED' build states in SF-2053b, so I removed that code from `DraftGenerationService`.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-:-NboPbNqCHm9cbCud8Sc:bfcv01v)* status: 24 of 46 files reviewed, 14 unresolved discussions (waiting on @github-code-scanning[bot], @Nateowami, @pmachapman, and @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2023-08-14 16:41 UTC, Nateowami requested changes
> Reviewed 1 of 5 files at r14, 8 of 18 files at r20.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961)* status: 32 of 46 files reviewed, 9 unresolved discussions (waiting on @github-code-scanning[bot], @pmachapman, @RaymondLuong3, and @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 86 at r19](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NbGdz3w8rZ5RyJFoe7D:-Nboj09SBnsQgN4t0XwY:b-nqjvkq) ([raw file](https://github.com/sillsdev/web-xforge/blob/db4b89316d737debac656b91331e65a3ca875548/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L86)):*
> figuring the project won't change on this component

Most components *do* have to handle the project changing, which is a major motivation for creating the ActivatedProjectService to begin with. It's always been a tricky edge case to handle.

I kind of wish Angular had a way of saying "if this input changes, destroy and recreate the entire component." That way we could handle certain edge cases (like switching to a different project) that don't happen often without having to carefully work them into the component logic.

If you're going to assume the project never changes, it would be very easy to just get the project ID, await the fetching of the project, and then continue initializing the component. There wouldn't be a need to subscribe to an observable.

In the interests of speed and simplicity, perhaps we should not worry about this case for now. But it at least should have a comment explaining this.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 88 at r19](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NbGeSwP0xCQxiuzmw9s:-NbomD7h5l21WcpFKP7b:bq3hxx3) ([raw file](https://github.com/sillsdev/web-xforge/blob/db4b89316d737debac656b91331e65a3ca875548/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L88)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Added `filter` to the observables to filter out undefined.
</blockquote></details>

I don't see why we're subscribing to the projectId and the projectDoc. The projectDoc has the projectId. The only reason both observables exist is because the projectId can be determined earlier (it's pulled from the URL), while the projectDoc cannot fire until the project data has loaded (it comes over the network). If we don't want to init until the projectDoc loads, then we should just subscribe to that and get the projectId from it.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 141 at r19](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NbGoX8X-KQ7qXByFzuO:-NbUwz9c3qwVw7QDcBty:bqksgw) ([raw file](https://github.com/sillsdev/web-xforge/blob/db4b89316d737debac656b91331e65a3ca875548/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L141)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

What do you think about:
```ts
async generateDraft({ withConfirm = false } = {}): Promise<void> {
    if (withConfirm) {
        // ...
```
Then the option name would need to be specified
```html
<button (click)="generateDraft({ withConfirm: true })">
    Generate draft
</button>

<-- Or could be called without option if no confirmation needed -->
<button (click)="generateDraft()">
    Generate draft
</button>
```
</blockquote></details>

That's good. Thanks for updating it.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 163 at r19](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NbHFT71AKvSneD2bEDR:-NbUz4Ib6WXd-5PUXz7V:bbutwdi) ([raw file](https://github.com/sillsdev/web-xforge/blob/db4b89316d737debac656b91331e65a3ca875548/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L163)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Good point.  I modified `openGenericDialog` to return a `MatDialogRef` in addition to the result.  That way I can be specific about what dialog to close.
</blockquote></details>

Good change. What happens if `cancelDialogRef.close()` is called after it's already closed? It looks like that could happen?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 174 at r19](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NbHGi7O-6dCN_Y-qAk_:-NbogbeE9IOZlDp93hw0:b-ayrgup) ([raw file](https://github.com/sillsdev/web-xforge/blob/db4b89316d737debac656b91331e65a3ca875548/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L174)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

So I looked up a few UX suggestions for confirmation dialogs, and [this one](https://uxdesign.cc/are-you-sure-you-want-to-do-this-microcopy-for-confirmation-dialogues-1d94a0f73ac6) describes the very thing I am guilty of!

![confirm-dialog-ux-example.png](https://files.reviewableusercontent.io/images/reviewable/133386342/ZwDkxKUVV0JzCLsCxUtNyAWO/confirm-dialog-ux-example.png)

Since there is some relevant description of the consequences of the action, what do you think about framing it similar to the 'Do' suggestion?
</blockquote></details>

I think this is better framing. However, one thing to note is that translators won't necessarily be able to tell the context of the strings when translating. So breaking the message into multiple strings potentially makes for less clear localization than just putting the entire message into one string.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts` line 58 at r19](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NbHNKtACiPrymNCWLAs:-NbUxg6b6eqIKihPTA3c:bfsrria) ([raw file](https://github.com/sillsdev/web-xforge/blob/db4b89316d737debac656b91331e65a3ca875548/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts#L58)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

`undefined` is an acceptable state for `res.data` if no build has ever run.
</blockquote></details>

From reading the code, I expected that when no build has ever run, the status will be 404, and we'll jump straight to the error handler. Is that not correct?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts` line 107 at r19](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NbHOr0A3f5xaEEtQDZv:-NbV-8wF4ZVjHT0ntF7r:b-4y46d) ([raw file](https://github.com/sillsdev/web-xforge/blob/db4b89316d737debac656b91331e65a3ca875548/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts#L107)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Good idea, I like that much better.
</blockquote></details>

Good name choice. Thanks.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts` line 127 at r19](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NbHPOuu8TZWt4wBknm8:-NbV-JpJ-Yt5ae2YJ7U4:bk0ezuj) ([raw file](https://github.com/sillsdev/web-xforge/blob/db4b89316d737debac656b91331e65a3ca875548/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts#L127)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Cancel doesn't return content.
</blockquote></details>

Ah, makes sense.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts` line 173 at r19](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NbHUePz5oOqR3SQgVSi:-NbonoBH35Qk [...]

2023-08-16 20:07 UTC, siltomato reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961)* status: 26 of 46 files reviewed, 9 unresolved discussions (waiting on @github-code-scanning[bot], @Nateowami, @pmachapman, and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 86 at r19](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NbGdz3w8rZ5RyJFoe7D:-NbzhDEpDXww4YRpdygG:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/db4b89316d737debac656b91331e65a3ca875548/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L86)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

> figuring the project won't change on this component

Most components *do* have to handle the project changing, which is a major motivation for creating the ActivatedProjectService to begin with. It's always been a tricky edge case to handle.

I kind of wish Angular had a way of saying "if this input changes, destroy and recreate the entire component." That way we could handle certain edge cases (like switching to a different project) that don't happen often without having to carefully work them into the component logic.

If you're going to assume the project never changes, it would be very easy to just get the project ID, await the fetching of the project, and then continue initializing the component. There wouldn't be a need to subscribe to an observable.

In the interests of speed and simplicity, perhaps we should not worry about this case for now. But it at least should have a comment explaining this.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 88 at r19](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NbGeSwP0xCQxiuzmw9s:-NbzCWVW3uQwtsbIo57c:bb6un1j) ([raw file](https://github.com/sillsdev/web-xforge/blob/db4b89316d737debac656b91331e65a3ca875548/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L88)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I don't see why we're subscribing to the projectId and the projectDoc. The projectDoc has the projectId. The only reason both observables exist is because the projectId can be determined earlier (it's pulled from the URL), while the projectDoc cannot fire until the project data has loaded (it comes over the network). If we don't want to init until the projectDoc loads, then we should just subscribe to that and get the projectId from it.
</blockquote></details>

Done
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 163 at r19](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NbHFT71AKvSneD2bEDR:-NbzFXuT-R6-TU8EZ073:b-fpouly) ([raw file](https://github.com/sillsdev/web-xforge/blob/db4b89316d737debac656b91331e65a3ca875548/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L163)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Good change. What happens if `cancelDialogRef.close()` is called after it's already closed? It looks like that could happen?
</blockquote></details>

Calling closed on an already closed dialog should have no effect, but I added`getState()` check for good measure.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 174 at r19](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NbHGi7O-6dCN_Y-qAk_:-NbzQtSR-f6cWN6hXe_F:b6ipja5) ([raw file](https://github.com/sillsdev/web-xforge/blob/db4b89316d737debac656b91331e65a3ca875548/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L174)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I think this is better framing. However, one thing to note is that translators won't necessarily be able to tell the context of the strings when translating. So breaking the message into multiple strings potentially makes for less clear localization than just putting the entire message into one string.
</blockquote></details>

Yeah, that makes sense.  Could this be mitigated with descriptive translation keys?
```json
{
    "dialog_confirm_draft_cancellation_message": "Canceling will reset progress for this draft request. You will still be able to use the last completed draft.",
    "dialog_confirm_draft_cancellation_title": "Cancel draft generation?",
}
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts` line 58 at r19](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NbHNKtACiPrymNCWLAs:-NbzUh0_AAEAQhMMTyp-:b-zkmpa) ([raw file](https://github.com/sillsdev/web-xforge/blob/db4b89316d737debac656b91331e65a3ca875548/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts#L58)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

From reading the code, I expected that when no build has ever run, the status will be 404, and we'll jump straight to the error handler. Is that not correct?
</blockquote></details>

Yes, that is correct, sorry!  Now that the build state casing has been fixed, this is no longer an issue.  Also, in SF-2175, an error is no longer thrown for 'faulted' state.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts` line 173 at r19](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NbHUePz5oOqR3SQgVSi:-NbzZGHaBbo-faRdFR6x:bq89yjx) ([raw file](https://github.com/sillsdev/web-xforge/blob/db4b89316d737debac656b91331e65a3ca875548/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.service.ts#L173)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

OK, looking at some existing projects, I see that is often but not always the case. I'm not sure why that is; one possibility is that people put them in because they think their needed. Another might be that our DeltaUsx mapper is inserting them when it shouldn't. 

Looking at the USFM/USX documentation, I don't see any indication that spaces are needed at the end of a verse: https://docs.usfm.bible/usfm-usx-docs/latest/cv/v.html (well, obviously a space is needed before the next verse marker, but I don't think that space is counted as part of the verse).

I looked at one of my test projects, and here's the USFM stored in the project:
```
\v 1 Paul, an apostle of Jesus Christ by the will of God, to the saints which are at Ephesus, and to the faithful in Christ Jesus:
\v 2 grace \add be\add* to you, and peace, from God our Father, and \add from\add* the Lord Jesus Christ.
\s2 The Gospel of Your Salvation
\p
\v 3 Blessed \add be\add* the God and Father of our Lord Jesus Christ, who hath blessed us with all spiritual blessings in heavenly \add places\add* in Christ:
\v 4 according as he hath chosen us in him before the foundation of the world, that we should be holy and without blame before him in love:
```
None of those lines have trailing white space, so the only white space between verses is the new lines.
In SF:
- There is a space at the end of verse 1
- There is no space at the end of verse 2
- There is a space at the end of verse 3

I think the pattern is that we're inserting spaces when one verse flows to the next, but not when a verse is followed by a heading or other formatting. This may have to do with how our XML parser handles white space. I think it's something to investigate as a potential issue, not something to copy.
</blockquote></details>

Ok, I modified the TODO comment to reflect that adding a space when a verse flows to the next needs in [...]

2023-08-18 17:59 UTC, Nateowami requested changes
> Reviewed 6 of 18 files at r20, 2 of 2 files at r21, 8 of 10 files at r22, 1 of 1 files at r23.
> Dismissed @pmachapman from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961)* status: 40 of 46 files reviewed, 12 unresolved discussions (waiting on @github-code-scanning[bot], @RaymondLuong3, and @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 174 at r19](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NbHGi7O-6dCN_Y-qAk_:-Nc8Zbxj6NlnkEpWV6aX:b-vu4dhk) ([raw file](https://github.com/sillsdev/web-xforge/blob/db4b89316d737debac656b91331e65a3ca875548/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L174)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Yeah, that makes sense.  Could this be mitigated with descriptive translation keys?
```json
{
    "dialog_confirm_draft_cancellation_message": "Canceling will reset progress for this draft request. You will still be able to use the last completed draft.",
    "dialog_confirm_draft_cancellation_title": "Cancel draft generation?",
}
```
</blockquote></details>

That slightly mitigates it, but I doubt it will make that much of a difference. The keys are not that prominent in Crowdin.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 95 at r23](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-Nc8f7eE6grf3ElyioXm:-Nc8f7eE6grf3ElyioXn:b7u2qr4) ([raw file](https://github.com/sillsdev/web-xforge/blob/3ce6776c582650630eae749fd1e875cabc5e51d8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L95)):*
> ```XML
>         this.isSourceProjectSet = translateConfig?.source?.projectRef !== undefined;
>         this.targetLanguage = projectDoc.data?.writingSystem.tag;
>         this.targetLanguageDisplayName = this.i18n.getLanguageDisplayName(this.targetLanguage);
> ```

As far as I can tell, this entire initilization is idempotent, so it probably doesn't matter if it gets run more often than necessary. However, initializing components tends to often be a tricky thing, especially as a component is maintained over time.

I can read through this init function and conclude after thinking about it that it's probably OK that it runs every time the language changes, even though for a lot of components that wouldn't be OK, or would at least not be ideal, since they might do something like query for any existing builds (in this component, that's handled separately). But it's not immediately obvious, which makes it a little harder to read and maintain.

I guess the advantage is that the `targetLanguageDisplayName` is precomputed, but that seems like a very minor optimization. If that were moved to a getter, than this entire function could be run exactly once each time a project is selected, and there's less of a chance for edge case issues when the locale changes.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.scss` line 23 at r23](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-Nc8_XQl2TPIHHjBzXUf:-Nc8_XQl2TPIHHjBzXUg:b7taypa) ([raw file](https://github.com/sillsdev/web-xforge/blob/3ce6776c582650630eae749fd1e875cabc5e51d8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.scss#L23)):*
> ```SCSS
> }
> 
> [mat-button],
> ```

We almost always select Material elements using classes. Sometimes we use tag names. I think all three of these always work:
``` scss
[mat-button] {}
.mat-button {}
mat-button {}
```
It seems like it would be nice to be consistent. 

Oh wait. I think I figured it out. You're specifically selecting buttons other than icon buttons. I think that could be done with classes though. Is there an advantage to using the attributes?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.scss` line 27 at r23](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-Nc8bKr85btTlIW5pdLo:-Nc8bKr85btTlIW5pdLp:b-7ax7ek) ([raw file](https://github.com/sillsdev/web-xforge/blob/3ce6776c582650630eae749fd1e875cabc5e51d8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.scss#L27)):*
> ```SCSS
>   mat-icon {
>     // Smaller icons on button when accompanied by text
>     font-size: 22px;
> ```

In general I like this change.

However:
1. This is a local solution to fix a global problem (The problem with fixing global problems locally, is that by the time you get around to fixing it globally, it will probably have been solved several different ways in several different places, which must then be identified, removed, and then verified to not be causing a regression. Which may be a lot more work than if no one had tried to solve it at all.)
2. I've noticed that icons in buttons with text make the button 1.297px taller, which is not ideal (and this doesn't fix that).
3. It makes the icons blurry. You can barely tell with the edit icon, but if you change the icon to `post_add` it becomes *very* obvious. So, I don't think this change, applied globally would be a good solution.

What does seem to solve the height problem is:
``` scss
.mat-button-wrapper {
  display: flex;
  align-items: center;
  column-gap: 4px;
}
```

It seems like there are a range of issues that could be better solved by creating our own icon button component, with an option to have it automatically switch to `mat-icon-button` on small screens.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.scss` line 35 at r23](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-Nc8iyRW331dgdAHNquM:-Nc8iyRW331dgdAHNquN:b-8xyskv) ([raw file](https://github.com/sillsdev/web-xforge/blob/3ce6776c582650630eae749fd1e875cabc5e51d8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.scss#L35)):*
> ```SCSS
>   display: flex;
>   margin-inline-start: 8px;
>   border-inline-start: 1px solid $border-color;
> ```

Have you seen the `.toolbar-separator` class from `editor.component.html`? It implements the same thing in a way that doesn't look wrong. The fact that the button is in contact with the separator has been bugging me since the first time I checked out this component.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.scss` line 103 at r23](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-Nc8jHrM4jwB2wIOd5e8:-Nc8jHrM4jwB2wIOd5e9:bvyxpfl) ([raw file](https://github.com/sillsdev/web-xforge/blob/3ce6776c582650630eae749fd1e875cabc5e51d8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.scss#L103)):*
> ```SCSS
>   color: #bbb;
>   font-style: italic;
>   font-family: monospace;
> ```

This stylistic choice is unlikely to localize very well. Take for example Arabic:

Monospace:
![](https://files.reviewableusercontent.io/images/reviewable/6140710/MW3qS4ULYEdVUZacdDQcObhE/arabic_monospace.png)
Default:
![](https://files.reviewableusercontent.io/images/reviewable/6140710/9mb_4y9acsAmnAlNvirxme5l/arabic_non_monospace.png)

I don't know how bad that looks, but I'm guessing it's significantly worse.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.scss` line 104 at r23](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-Nc8kJ9o7OShGFjEiU_O:-Nc8kJ9o7OShGFjEiU_P:bvay6us) ([raw file](https://github.com/sillsdev/web-xforge/blob/3ce6776c582650630eae749fd1e875cabc5e51d8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.scss#L104)):*
> ```SCSS
>   font-style: italic;
>   font-family: mon [...]

2023-08-21 07:55 UTC, siltomato reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961)* status: 34 of 46 files reviewed, 6 unresolved discussions (waiting on @github-code-scanning[bot], @Nateowami, and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 95 at r23](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-Nc8f7eE6grf3ElyioXm:-NcLSCh31BO_3Y0_aXwO:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/3ce6776c582650630eae749fd1e875cabc5e51d8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L95)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

As far as I can tell, this entire initilization is idempotent, so it probably doesn't matter if it gets run more often than necessary. However, initializing components tends to often be a tricky thing, especially as a component is maintained over time.

I can read through this init function and conclude after thinking about it that it's probably OK that it runs every time the language changes, even though for a lot of components that wouldn't be OK, or would at least not be ideal, since they might do something like query for any existing builds (in this component, that's handled separately). But it's not immediately obvious, which makes it a little harder to read and maintain.

I guess the advantage is that the `targetLanguageDisplayName` is precomputed, but that seems like a very minor optimization. If that were moved to a getter, than this entire function could be run exactly once each time a project is selected, and there's less of a chance for edge case issues when the locale changes.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.scss` line 23 at r23](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-Nc8_XQl2TPIHHjBzXUf:-NcLL2Ef4IJPo2ZAoBf6:b-q03c55) ([raw file](https://github.com/sillsdev/web-xforge/blob/3ce6776c582650630eae749fd1e875cabc5e51d8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.scss#L23)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

We almost always select Material elements using classes. Sometimes we use tag names. I think all three of these always work:
``` scss
[mat-button] {}
.mat-button {}
mat-button {}
```
It seems like it would be nice to be consistent. 

Oh wait. I think I figured it out. You're specifically selecting buttons other than icon buttons. I think that could be done with classes though. Is there an advantage to using the attributes?
</blockquote></details>

This is one of those times when a comment would have been useful for myself =).  I can't remember why I used attribute selector here.  Looks like no good reason, though.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.scss` line 27 at r23](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-Nc8bKr85btTlIW5pdLo:-NcLzeJA75cpT60Q1ztH:b-811h45) ([raw file](https://github.com/sillsdev/web-xforge/blob/3ce6776c582650630eae749fd1e875cabc5e51d8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.scss#L27)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

In general I like this change.

However:
1. This is a local solution to fix a global problem (The problem with fixing global problems locally, is that by the time you get around to fixing it globally, it will probably have been solved several different ways in several different places, which must then be identified, removed, and then verified to not be causing a regression. Which may be a lot more work than if no one had tried to solve it at all.)
2. I've noticed that icons in buttons with text make the button 1.297px taller, which is not ideal (and this doesn't fix that).
3. It makes the icons blurry. You can barely tell with the edit icon, but if you change the icon to `post_add` it becomes *very* obvious. So, I don't think this change, applied globally would be a good solution.

What does seem to solve the height problem is:
``` scss
.mat-button-wrapper {
  display: flex;
  align-items: center;
  column-gap: 4px;
}
```

It seems like there are a range of issues that could be better solved by creating our own icon button component, with an option to have it automatically switch to `mat-icon-button` on small screens.
</blockquote></details>

Yes, a custom icon button component sounds interesting.  Removed `font-size`.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.scss` line 35 at r23](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-Nc8iyRW331dgdAHNquM:-NcLFWnJ2KCYyPpx69_i:bb4ars0) ([raw file](https://github.com/sillsdev/web-xforge/blob/3ce6776c582650630eae749fd1e875cabc5e51d8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.scss#L35)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Have you seen the `.toolbar-separator` class from `editor.component.html`? It implements the same thing in a way that doesn't look wrong. The fact that the button is in contact with the separator has been bugging me since the first time I checked out this component.
</blockquote></details>

I understand how that can be.  Added space.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.scss` line 103 at r23](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-Nc8jHrM4jwB2wIOd5e8:-NcLDOET3DgvX5rL4Hxa:b3px6ho) ([raw file](https://github.com/sillsdev/web-xforge/blob/3ce6776c582650630eae749fd1e875cabc5e51d8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.scss#L103)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This stylistic choice is unlikely to localize very well. Take for example Arabic:

Monospace:
![](https://files.reviewableusercontent.io/images/reviewable/6140710/MW3qS4ULYEdVUZacdDQcObhE/arabic_monospace.png)
Default:
![](https://files.reviewableusercontent.io/images/reviewable/6140710/9mb_4y9acsAmnAlNvirxme5l/arabic_non_monospace.png)

I don't know how bad that looks, but I'm guessing it's significantly worse.
</blockquote></details>

Thanks, changed.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.scss` line 104 at r23](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-Nc8kJ9o7OShGFjEiU_O:-NcLDGpQ9Z3T-9n2c1D2:b-m8jjnl) ([raw file](https://github.com/sillsdev/web-xforge/blob/3ce6776c582650630eae749fd1e875cabc5e51d8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.scss#L104)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

In English this is perfectly acceptable, but I'm not sure it will look correct in every language we support, and every future language we may support.
</blockquote></details>

Thanks, I'll try to keep that in mind.  
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 29 at r21](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-Nbue73U03m6SO8bQ9g-:-NcA0AZh5l5wyW6nhLGE:b-nnrexs) ([raw file](https://github.com/sillsdev/web-xforge/blob/3e4e1cf8e426c14cc47204ece9ed17af4d0e88f9/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L29)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Oh, this is interesting. Why is it  [...]

2023-08-22 21:14 UTC, Nateowami requested changes
> Reviewed 7 of 10 files at r24, 1 of 1 files at r26.
> Dismissed @github-code-scanning[bot] from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961)* status: 41 of 46 files reviewed, 9 unresolved discussions (waiting on @RaymondLuong3 and @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts` line 18 at r26](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NcTxFHc6FL16Vg6QNit:-NcTxFHc6FL16Vg6QNiu:b84zymt) ([raw file](https://github.com/sillsdev/web-xforge/blob/edeb743bf6202b03838ea012413b9f1d398b4892/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts#L18)):*
> ```XML
> 
> describe('DraftGenerationComponent', () => {
>   let mockDialogService: jasmine.SpyObj<DialogService>;
> ```

Is there a reason we're using Jasmine spies rather than mocking with ts-mockito? This isn't how we've been writing any of our tests (there are a few instances of spying). It's not wrong (at least I don't think it is), it's just a different way of doing things which requires a developer to understand more things in order to be able to read and maintain tests. It also seems like it doesn't have the same type safety as ts-mockito, as I'm seeing things like:
``` ts
     mockDraftGenerationService = jasmine.createSpyObj('DraftGenerationService', [
        'startBuildOrGetActiveBuild',
        'cancelBuild',
        'getBuildProgress',
        'pollBuildProgress',
        'getLastCompletedBuild'
      ]);
 ```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 56 at r25](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NcSl0qlCPBHKDxaqtn-:-NcSl0qlCPBHKDxaqtn0:b-tqtvlh) ([raw file](https://github.com/sillsdev/web-xforge/blob/9621a7fa060f548e8c8859817a5814b22446c2ce/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L56)):*
> ```XML
>     private readonly activatedRoute: ActivatedRoute,
>     private readonly router: Router,
>     private readonly changeDetectorRef: ChangeDetectorRef
> ```

This is not used.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 126 at r25](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NcPxQdu2gRcBXCEKLzM:-NcPxQdu2gRcBXCEKLzN:bifekuk) ([raw file](https://github.com/sillsdev/web-xforge/blob/9621a7fa060f548e8c8859817a5814b22446c2ce/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L126)):*
> ```XML
> 
>   populateDraftText(): void {
>     if (!this.currentBook || !this.currentChapter) {
> ```

Here's another case of assuming there's never a chapter 0, which I'm not sure is correct (it might be, but I'm not sure. Maybe it's sometimes used for front matter to a book?). Book numbers are all 1-based (not 0-based), so they'll always be truthy if they're defined, but I think it would be better to always check if it's nullish rather than if it's truthy.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 155 at r25](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NcSiRj-0DctcByRE1hx:-NcSiRj-0DctcByRE1hy:b-obpwvs) ([raw file](https://github.com/sillsdev/web-xforge/blob/9621a7fa060f548e8c8859817a5814b22446c2ce/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L155)):*
> ```XML
>     }
> 
>     const cleanedOps: DeltaOperation[] = this.cleanDraftOps(this.targetEditor.editor?.getContents().ops!);
> ```

This entire method keeps having to handled the possibility that `this.targetEditor.editor` might be undefined. I think it would be more helpful to have a single check at the beginning of the method. 
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 162 at r25](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NcSjPEUAcRDitO9l2x5:-NcSjPEUAcRDitO9l2x6:b-okgqng) ([raw file](https://github.com/sillsdev/web-xforge/blob/9621a7fa060f548e8c8859817a5814b22446c2ce/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L162)):*
> ```XML
> 
>     // Call updateContents() with diff instead of setContents() with entire contents because
>     // setContents() is causing a 'delete' op to be appended because of the final '\n'.
> ```

This is really important but I don't understand exactly what this is saying. We had a lot of trouble with delete ops getting snuck into documents, when they should only be in deltas. I think we did manage to get rid of the issues that caused it. But one of our remediations was to reduce the damage by detecting data corruption and then locking the editor once it was corrupted, so the user wouldn't keep editing (making it harder to restore to a good state without losing user data). Also, by locking the editor and informing the user of the problem, we thought it would increase the probability that we would get an error report that would actually tell us what steps led to the problem.

Do you know how a final new line causes this to happen? Getting a better understanding of this issue could be very valuable.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 91 at r26](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NcSm3Zl1_MaUcq6weZS:-NcSm3Zl1_MaUcq6weZT:blexydt) ([raw file](https://github.com/sillsdev/web-xforge/blob/edeb743bf6202b03838ea012413b9f1d398b4892/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L91)):*
> ```XML
>       // so that editor `loaded` events are not missed.  This causes an ExpressionChangedAfterItHasBeenCheckedError.
>       // Setting the properties in a timeout is a workaround for this.
>       setTimeout(() => {
> ```

Maybe I'm misunderstanding the problem, but could this whole issue not be solved by doing something like:
``` ts
    const editorsChanged$ = this.targetEditorQueryList.changes.pipe(
      switchMap(() => zip(this.sourceEditor?.loaded ?? of(null), this.targetEditor.loaded))
    );

    const routedBookChapter = this.activatedRoute.paramMap.pipe(map((params: ParamMap) => [params.get('bookId'), params.get('chapter')]));

    // Wait for editors to load and route to change before setting book/chapter
    zip(editorsChanged$, routedBookChapter).subscribe((editor, bookChapter) => {
      
    });
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts` line 29 at r23](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-Nc8zx8c2QajvpNSSzx9:-Nc8zx8c2QajvpNSSzxA:b1ez5c4) ([raw file](https://github.com/sillsdev/web-xforge/blob/3ce6776c582650630eae749fd1e875cabc5e51d8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts#L29)):*
> ```XML
> 
>       // Can populate draft if insert is a blank string
>       if (isString(op.insert)) {
> ```

Why not just `typeof op.insert === 'string'`?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts` line 35 at r23](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-Nc9-G4ICVlzs6ypPShY:-Nc9-G4ICVlzs6ypPShZ:bheo099) ([raw file](https://github.com/sillsdev/web-xforge/blob/3ce6776c582650630eae749fd1e875cabc5e51d8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts#L35)):*
> ```XML
>       // Can populate draft if insert is object that has 'blank: true' property.
>       // Other objects are not draftable (e.g. 'note-thread-embed').
>       return op.insert?.blank === true;
> ```

This entire function is hard to follow, w [...]

2023-08-23 21:37 UTC, siltomato reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961)* status: 41 of 46 files reviewed, 6 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts` line 18 at r26](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NcTxFHc6FL16Vg6QNit:-NcU9wBqEx6ZfRVOQ1BU:bqoz7c0) ([raw file](https://github.com/sillsdev/web-xforge/blob/edeb743bf6202b03838ea012413b9f1d398b4892/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts#L18)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Is there a reason we're using Jasmine spies rather than mocking with ts-mockito? This isn't how we've been writing any of our tests (there are a few instances of spying). It's not wrong (at least I don't think it is), it's just a different way of doing things which requires a developer to understand more things in order to be able to read and maintain tests. It also seems like it doesn't have the same type safety as ts-mockito, as I'm seeing things like:
``` ts
     mockDraftGenerationService = jasmine.createSpyObj('DraftGenerationService', [
        'startBuildOrGetActiveBuild',
        'cancelBuild',
        'getBuildProgress',
        'pollBuildProgress',
        'getLastCompletedBuild'
      ]);
 ```
</blockquote></details>

Yes, sorry, I was not familiar with ts-mockito.  I've started to use ts-mockito in new specs.  Good point about the type safety.  I should have used the generic method, then the method names would need to be `keyof DraftGenerationService`.  Do you want me to re-write the tests using ts-mockito?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 29 at r21](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-Nbue73U03m6SO8bQ9g-:-NcYyc9W8fniWL5wzsdQ:b-9h5gc1) ([raw file](https://github.com/sillsdev/web-xforge/blob/3e4e1cf8e426c14cc47204ece9ed17af4d0e88f9/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L29)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Since `targetEditorQueryList` is `@ViewChildren`, it is only defined after `ngAfterViewInit`, but I need to subscribe to it before the text doc ids are set due to chapter change triggered from url so that 'sourceEditor' and 'targetEditor' `loaded` events aren't missed.  But, subscribing to the route and setting properties in `ngAfterViewInit` causes an `ExpressionChangedAfterItHasBeenCheckedError`.

Using `OnPush` got around this problem, but maybe it would be better to use the `setTimeout` workaround to set the offending properties?  It's a hack, and probably there is a way to rework the events so that this isn't needed.  If you've got an idea, I'm open to it!
</blockquote></details>

`setTimeout` no longer needed due to fix described below.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 56 at r25](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NcSl0qlCPBHKDxaqtn-:-NcXy_6l23AOy12AN29W:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/9621a7fa060f548e8c8859817a5814b22446c2ce/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L56)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This is not used.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 126 at r25](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NcPxQdu2gRcBXCEKLzM:-NcY3_HI7UHXBGG-jw1R:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/9621a7fa060f548e8c8859817a5814b22446c2ce/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L126)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Here's another case of assuming there's never a chapter 0, which I'm not sure is correct (it might be, but I'm not sure. Maybe it's sometimes used for front matter to a book?). Book numbers are all 1-based (not 0-based), so they'll always be truthy if they're defined, but I think it would be better to always check if it's nullish rather than if it's truthy.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 155 at r25](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NcSiRj-0DctcByRE1hx:-NcY4RitBF2Rya8vQwn6:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/9621a7fa060f548e8c8859817a5814b22446c2ce/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L155)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This entire method keeps having to handled the possibility that `this.targetEditor.editor` might be undefined. I think it would be more helpful to have a single check at the beginning of the method.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 162 at r25](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NcSjPEUAcRDitO9l2x5:-NcZ4ylNBSzKNpcdV4XH:ba7qj98) ([raw file](https://github.com/sillsdev/web-xforge/blob/9621a7fa060f548e8c8859817a5814b22446c2ce/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L162)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This is really important but I don't understand exactly what this is saying. We had a lot of trouble with delete ops getting snuck into documents, when they should only be in deltas. I think we did manage to get rid of the issues that caused it. But one of our remediations was to reduce the damage by detecting data corruption and then locking the editor once it was corrupted, so the user wouldn't keep editing (making it harder to restore to a good state without losing user data). Also, by locking the editor and informing the user of the problem, we thought it would increase the probability that we would get an error report that would actually tell us what steps led to the problem.

Do you know how a final new line causes this to happen? Getting a better understanding of this issue could be very valuable.
</blockquote></details>

Yes, it seems to be a issue with `setContents` in Quill.  [Here's a link to the `setContents` method on github](https://github.com/quilljs/quill/blob/0148738cb22d52808f35873adb620ca56b1ae061/core/quill.js#L302) (copied to code snippet below).

If the last op ends with `\n`, a delete op is appended.  This seems to be only a problem when the source is 'user', as that will trigger a document update.



_Code snippet:_
```XML
setContents(delta, source = Emitter.sources.API) {
  return modify.call(this, () => {
    delta = new Delta(delta);
    let length = this.getLength();
    let deleted = this.editor.deleteText(0, length);
    let applied = this.editor.applyDelta(delta);
    let lastOp = applied.ops[applied.ops.length - 1];
    if (lastOp != null && typeof(lastOp.insert) === 'string' && lastOp.insert[lastOp.insert.length-1] === '\n') {
      this.editor.deleteText(this.getLength() - 1, 1);
      applied.delete(1);
    }
    let ret = deleted.compose(applied);
    return ret;
  }, source);
}
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 91 at r26](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NcSm3Zl1_MaUcq6weZS:-NcYG9Qb1KKG6anRvoBq:b-7nv9bc)  [...]

2023-08-29 15:15 UTC, Nateowami reviewed
Almost done reviewing. Four files to go, and they're all test related.

> Reviewed 4 of 5 files at r27, 2 of 2 files at r28.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-:-Nd0rJOmDkeWmOLAnp18:b-whvs26)* status: 42 of 46 files reviewed, all discussions resolved (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts` line 18 at r26](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NcTxFHc6FL16Vg6QNit:-Nd0qVWEB_Y_qHnkWQ4b:bsssj6g) ([raw file](https://github.com/sillsdev/web-xforge/blob/edeb743bf6202b03838ea012413b9f1d398b4892/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts#L18)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Yes, sorry, I was not familiar with ts-mockito.  I've started to use ts-mockito in new specs.  Good point about the type safety.  I should have used the generic method, then the method names would need to be `keyof DraftGenerationService`.  Do you want me to re-write the tests using ts-mockito?
</blockquote></details>

No, you don't need to rewrite them. I think it would probably be better to use ts-mockito in the future though, just because most of our tests are already written that way (less for devs to learn), and I think it has better type checking.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 29 at r21](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-Nbue73U03m6SO8bQ9g-:-NcZREvsEerSAE9Cg0DY:b-1vahzj) ([raw file](https://github.com/sillsdev/web-xforge/blob/3e4e1cf8e426c14cc47204ece9ed17af4d0e88f9/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L29)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

`setTimeout` no longer needed due to fix described below.
</blockquote></details>

Wonderful.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 162 at r25](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NcSjPEUAcRDitO9l2x5:-Nd0pkzfEX3qwKEX0SnG:b5njlcv) ([raw file](https://github.com/sillsdev/web-xforge/blob/9621a7fa060f548e8c8859817a5814b22446c2ce/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L162)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Yes, it seems to be a issue with `setContents` in Quill.  [Here's a link to the `setContents` method on github](https://github.com/quilljs/quill/blob/0148738cb22d52808f35873adb620ca56b1ae061/core/quill.js#L302) (copied to code snippet below).

If the last op ends with `\n`, a delete op is appended.  This seems to be only a problem when the source is 'user', as that will trigger a document update.
</blockquote></details>

Thanks for the explanation. It looks like the intent is to prevent trailing new lines from being added by accident. I'm not sure how that ends up with the data being corrupted though. We may want to try to figure that out to see if we're accidentally causing it in some cases.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts` line 29 at r23](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-Nc8zx8c2QajvpNSSzx9:-NcZUH4yC6F6vKPWPpxm:b-jzgwoe) ([raw file](https://github.com/sillsdev/web-xforge/blob/3ce6776c582650630eae749fd1e875cabc5e51d8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts#L29)):*
(Wrote this several days ago and didn't post it until now)

I agree `isString` reads better. I don't really feel like it's a good replacement though. Here's the implementation:
``` js
function isString(value) {
  const type = typeof value
  return type === 'string' || (type === 'object' && value != null && !Array.isArray(value) && getTag(value) == '[object String]')
}
```
I'm not sure why it needs `!Array.isArray(value)`. And here's the type definition:
``` ts
        /**
         * Checks if value is classified as a String primitive or object.
         *
         * @param value The value to check.
         * @return Returns true if value is correctly classified, else false.
         */
        isString(value?: any): value is string;
```
Notice the type definition disagrees with the documentation. The type definition should be `string | String`. `String` has weird behavior, like `new String('abc') != new String('abc')` The TypeScript documentation says:

> The type names `String`, `Number`, and `Boolean` (starting with capital letters) are legal, but refer to some special built-in types that will very rarely appear in your code. _Always_ use `string`, `number`, or `boolean` for types.

I would be in favor of adding an `isString` method to `src/SIL.XForge.Scripture/ClientApp/src/type-utils.ts` that just checks if `typeof value === 'string'`.

(Not within this PR, just thinking it's a good solution).
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts` line 35 at r23](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-Nc9-G4ICVlzs6ypPShY:-NcZTmHD4InrPO1LONp6:bjk7pvk) ([raw file](https://github.com/sillsdev/web-xforge/blob/3ce6776c582650630eae749fd1e875cabc5e51d8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts#L35)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Cool, I had to look up "cyclomatic complexity".  Changed!

Also, `draftSegmentText != null` removal should cause the compiler to complain now.  I updated `DraftSegmentMap` interface.
</blockquote></details>

Yeah, I almost didn't use the term "cyclomatic complexity" because it seems wrong to use complicated technical terms to criticize complexity. I only know the term because JSHint would tell you what a function's cyclomatic complexity was. Ultimately I don't care what score it gets for complexity, just how readable it is. But it did take me longer to figure out what it was doing due to the number of different paths.


<!-- Sent from Reviewable.io -->

2023-08-29 17:25 UTC, siltomato reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961)* status: 42 of 46 files reviewed, all discussions resolved (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts` line 18 at r26](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NcTxFHc6FL16Vg6QNit:-Nd149S391yzdGUHeODM:bigpj1m) ([raw file](https://github.com/sillsdev/web-xforge/blob/edeb743bf6202b03838ea012413b9f1d398b4892/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts#L18)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

No, you don't need to rewrite them. I think it would probably be better to use ts-mockito in the future though, just because most of our tests are already written that way (less for devs to learn), and I think it has better type checking.
</blockquote></details>

Ok, sounds good.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 162 at r25](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NcSjPEUAcRDitO9l2x5:-Nd1BCkn-mn7rlVunMy_:bnwh8bm) ([raw file](https://github.com/sillsdev/web-xforge/blob/9621a7fa060f548e8c8859817a5814b22446c2ce/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L162)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Thanks for the explanation. It looks like the intent is to prevent trailing new lines from being added by accident. I'm not sure how that ends up with the data being corrupted though. We may want to try to figure that out to see if we're accidentally causing it in some cases.
</blockquote></details>

The `isBadDelta()` function to check if ops are corrupted determines that the delta is bad if any op does not have an `insert` property, which makes the appended `delete` op the offender.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts` line 29 at r23](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-Nc8zx8c2QajvpNSSzx9:-Nd1IHy9-1Zy9ow9zrBS:b-akij6p) ([raw file](https://github.com/sillsdev/web-xforge/blob/3ce6776c582650630eae749fd1e875cabc5e51d8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts#L29)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

(Wrote this several days ago and didn't post it until now)

I agree `isString` reads better. I don't really feel like it's a good replacement though. Here's the implementation:
``` js
function isString(value) {
  const type = typeof value
  return type === 'string' || (type === 'object' && value != null && !Array.isArray(value) && getTag(value) == '[object String]')
}
```
I'm not sure why it needs `!Array.isArray(value)`. And here's the type definition:
``` ts
        /**
         * Checks if value is classified as a String primitive or object.
         *
         * @param value The value to check.
         * @return Returns true if value is correctly classified, else false.
         */
        isString(value?: any): value is string;
```
Notice the type definition disagrees with the documentation. The type definition should be `string | String`. `String` has weird behavior, like `new String('abc') != new String('abc')` The TypeScript documentation says:

> The type names `String`, `Number`, and `Boolean` (starting with capital letters) are legal, but refer to some special built-in types that will very rarely appear in your code. _Always_ use `string`, `number`, or `boolean` for types.

I would be in favor of adding an `isString` method to `src/SIL.XForge.Scripture/ClientApp/src/type-utils.ts` that just checks if `typeof value === 'string'`.

(Not within this PR, just thinking it's a good solution).
</blockquote></details>

Yes, that array check is curious.  Good point about the type definition, too.  Thanks for pointing out `type-utils.ts`.


<!-- Sent from Reviewable.io -->

2023-08-29 17:52 UTC, Nateowami reviewed
Three test files to go.

> Reviewed 1 of 7 files at r9, 1 of 18 files at r20.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-:-Nd1QDrECiCn-9JKgAgS:b-tbayof)* status: 43 of 46 files reviewed, all discussions resolved (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 162 at r25](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NcSjPEUAcRDitO9l2x5:-Nd1P-Lv4JKou0iZGRIe:bqo7wzh) ([raw file](https://github.com/sillsdev/web-xforge/blob/9621a7fa060f548e8c8859817a5814b22446c2ce/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L162)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

The `isBadDelta()` function to check if ops are corrupted determines that the delta is bad if any op does not have an `insert` property, which makes the appended `delete` op the offender.
</blockquote></details>

Yes, I understand that part. There are two types of deltas: those that describe a document, and those that describe a change to a document. Deletions are only valid for describing a change to a document. If they show up in a document, the document is corrupted and it's no longer possible to apply transformations to it, because it's in a nonsensical state. What I'm trying to understand is why Quill ends up adding a delete op at the end of the document, rather than actually deleting the last character.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts` line 29 at r23](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-Nc8zx8c2QajvpNSSzx9:-Nd1Pkql5ZkmqWoiWmPr:b-5lra3t) ([raw file](https://github.com/sillsdev/web-xforge/blob/3ce6776c582650630eae749fd1e875cabc5e51d8/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts#L29)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Yes, that array check is curious.  Good point about the type definition, too.  Thanks for pointing out `type-utils.ts`.
</blockquote></details>

I'm sure they have a reason for it. I just don't know what it is, and for thinks like type checks, I want them to be provably correct so they're performing proper [type narrowing](https://www.typescriptlang.org/docs/handbook/2/narrowing.html).


<!-- Sent from Reviewable.io -->

2023-08-29 21:42 UTC, siltomato reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961)* status: 43 of 46 files reviewed, all discussions resolved (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 162 at r25](https://reviewable.io/reviews/sillsdev/web-xforge/1961#-NcSjPEUAcRDitO9l2x5:-Nd278ha2i7mBFwD3kON:b-j8jibq) ([raw file](https://github.com/sillsdev/web-xforge/blob/9621a7fa060f548e8c8859817a5814b22446c2ce/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L162)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Yes, I understand that part. There are two types of deltas: those that describe a document, and those that describe a change to a document. Deletions are only valid for describing a change to a document. If they show up in a document, the document is corrupted and it's no longer possible to apply transformations to it, because it's in a nonsensical state. What I'm trying to understand is why Quill ends up adding a delete op at the end of the document, rather than actually deleting the last character.
</blockquote></details>

Yeah, it does seem like a bug.


<!-- Sent from Reviewable.io -->

2023-08-30 03:35 UTC, Nateowami reviewed
> Reviewed 1 of 5 files at r27.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961)* status: 44 of 46 files reviewed, all discussions resolved (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2023-08-31 13:49 UTC, Nateowami approved these changes
> Reviewed 1 of 5 files at r14, 1 of 10 files at r24, 2 of 2 files at r29, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1961)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @siltomato)



<!-- Sent from Reviewable.io -->

2023-08-31 19:25 UTC, merged