Question plays audio and relevant scripture audio.
sillsdev/web-xforge pull request #1964
Opened 2023-07-13 03:38 UTC by josephmyers

There's still a lot of work to be done, particularly with UX. This completes the happy path (with stubbed data) and serves as the groundwork for the rest of the effort.

The single button audio player now renders custom content, which will aid in reuse. It still needs error state work. It now inherits from the new base class AudioPlayerBaseComponent, which I introduced as a common layer for any audio-loading component. The main feature of the single button player is its ability to dynamically use either AudioPlayer or AudioSegmentPlayer, based on given optional Inputs. If it receives start and end values, it will create and use the latter.

AudioSegmentPlayer is a subclass of AudioPlayer. I debated over various design patterns, rather than traditional inheritance, but extending the original seemed the best fit. The subclass is small, and it changes the behavior of its parent, rather than adding behavior. The child class accepts a full audio file, like its parent, but plays only the given range from it. All its properties, e.g. seek and currentTime, are based off the range and not the full audio file.

Much work left to be done in error cases, UX, and testing.

2023-07-13 03:40 UTC, josephmyers commented on src/SIL.XForge.Scripture/ClientApp/src/app/checking-question/checking-question.component.ts
> +  get scriptureAudioStart(): number | undefined {
This was a hack to work with my stubbed test data. We'll need a more sophisticated way to read the verse numbers from the timing data.

2023-07-13 06:57 UTC, josephmyers commented on src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.scss
> +  outline: none;
The outline (use Tab) is cut off, and I haven't been able to figure out how to style it such that it a) isn't cut off, and b) doesn't conflict with the radial progress.

2023-07-20 14:05 UTC, josephmyers commented
Not sure how I broke a test by adding a test file. Will look at this more tomorrow.

2023-07-20 18:56 UTC, RaymondLuong3 requested changes
Nice work! I gave it a test and it seems to be doing the right thing. It took me a while to discover that I can choose between playing the audio for the scripture text and the question, but after I discovered that, I really liked it. We can revisit discoverability later. The only thing I found not working was that I couldn't get the audio player to stop where my timing data said the timing was. I didn't look into it too deeply. Other than that, I like how this is turning out!

> Reviewed 6 of 18 files at r1, 10 of 13 files at r2, 16 of 16 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1964#-:-N_odmA56xygjTcKuPTG:b-3j0ci3)* status: all files reviewed, 21 unresolved discussions (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts` line 37 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1964#-N_oJypSEVN8H9O3OUbO:-N_oJypSEVN8H9O3OUbP:bljs7km) ([raw file](https://github.com/sillsdev/web-xforge/blob/5c9ac0668072fa5845dc4bfd9192456f586c8947/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts#L37)):*
> ```XML
> import { BehaviorSubject, of, Subject } from 'rxjs';
> import { first } from 'rxjs/operators';
> import { AudioTimePipe } from 'src/app/shared/audio/audio-time-pipe';
> ```

Use relative paths here.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player-new/checking-audio-player-new.component.spec.ts` line 11 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1964#-N_oKVdV2KCQ_99QxO91:-N_oKVdV2KCQ_99QxO92:bxgw1m8) ([raw file](https://github.com/sillsdev/web-xforge/blob/5c9ac0668072fa5845dc4bfd9192456f586c8947/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player-new/checking-audio-player-new.component.spec.ts#L11)):*
> ```XML
> import { TestTranslocoModule } from 'xforge-common/test-utils';
> import { UICommonModule } from 'xforge-common/ui-common.module';
> import { AudioPlayerComponent } from '../../../shared/audio/audio-player.component/audio-player.component';
> ```

Let's rename these folders so that there isn't a dot in the folder name. `audio-player` and `audio-player-base` should be sufficient.



_Code quote:_
```XML
import { AudioPlayerComponent } from '../../../shared/audio/audio-player.component/audio-player.component';
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.html` line 2 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1964#-N_oLEVi7TO_HXu1UPdX:-N_oLEVi7TO_HXu1UPdY:bm4abj2) ([raw file](https://github.com/sillsdev/web-xforge/blob/5c9ac0668072fa5845dc4bfd9192456f586c8947/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.html#L2)):*
> ```HTML
> <button type="button" [style.--audio-progress]="progressInDegrees" *transloco="let t; read: 'checking_audio_player'">
>   <ng-content *ngIf="isAudioAvailable$.value"></ng-content>
> ```

You can use the async pipe here. It would look like *ngIf="isAudioAvailable | async"
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.ts` line 5 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1964#-N_oLdIm5tVfTUNNz2af:-N_oLdIm5tVfTUNNz2ag:bljs7km) ([raw file](https://github.com/sillsdev/web-xforge/blob/5c9ac0668072fa5845dc4bfd9192456f586c8947/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.ts#L5)):*
> ```XML
> import { AudioPlayer, AudioStatus } from 'src/app/shared/audio/audio-player';
> import { AudioPlayerBaseComponent } from 'src/app/shared/audio/audio-player-base.component/audio-player-base.component';
> import { AudioSegmentPlayer } from 'src/app/shared/audio/audio-segment-player';
> ```

Use relative paths here.



_Code quote:_
```XML
import { AudioPlayer, AudioStatus } from 'src/app/shared/audio/audio-player';
import { AudioPlayerBaseComponent } from 'src/app/shared/audio/audio-player-base.component/audio-player-base.component';
import { AudioSegmentPlayer } from 'src/app/shared/audio/audio-segment-player';
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.ts` line 24 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1964#-N_oMoGr8KKsdmvQL5eU:-N_oMoGr8KKsdmvQL5eV:b-x2xcpi) ([raw file](https://github.com/sillsdev/web-xforge/blob/5c9ac0668072fa5845dc4bfd9192456f586c8947/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.ts#L24)):*
> ```XML
>   }
> 
>   constructor(pwaService: PwaService) {
> ```

You can make pwaService `private readonly`
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.ts` line 33 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1964#-N_oNDKn0Em0IRqeWuF0:-N_oNDKn0Em0IRqeWuF1:brtbrmg) ([raw file](https://github.com/sillsdev/web-xforge/blob/5c9ac0668072fa5845dc4bfd9192456f586c8947/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.ts#L33)):*
> ```XML
> 
>   get playing(): boolean {
>     return this._audio?.isPlaying ?? false;
> ```

What do you think about using `this.audio` instead? When I see `this._audio`, I think I am expecting a private member, but in this case, it is actually in the base class.



_Code quote:_
```XML
    return this._audio?.isPlaying ?? false;
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.spec.ts` line 7 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1964#-N_oOEDBDIjc_rqzE5fo:-N_oOEDBDIjc_rqzE5fp:bljs7km) ([raw file](https://github.com/sillsdev/web-xforge/blob/5c9ac0668072fa5845dc4bfd9192456f586c8947/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.spec.ts#L7)):*
> ```XML
> import { of } from 'rxjs';
> import { AudioPlayer } from 'src/app/shared/audio/audio-player';
> import { AudioSegmentPlayer } from 'src/app/shared/audio/audio-segment-player';
> ```

Use relative paths here.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.spec.ts` line 40 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1964#-N_oORyd05_8hQ7P8y7H:-N_oORyd05_8hQ7P8y7I:b-aycbl3) ([raw file](https://github.com/sillsdev/web-xforge/blob/5c9ac0668072fa5845dc4bfd9192456f586c8947/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.spec.ts#L40)):*
> ```XML
>   it('shows content when audio is available', async () => {
>     const env = new TestEnvironment();
>     await env.wait();
> ```

That is strange this needs to be called twice. Would it work to just go env.wait(600) in the places where it is called twice, or is there a reason to need to call env.fixture.detectChanges twice?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.spec.ts` line 108 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1964#-N_oPCR_719kBrbDRVZ9:-N_oPCR_719kBrbDRVZA:b-bfln1k) ([raw file](https://github.com/sillsdev/web-xforge/blob/5c9ac0668072fa5845dc4bfd9192456f586c8947/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.spec.ts#L108)):*
> ```XML
>     });
> 
>     env.component.player.audio?.setSeek(98);
> ```

What does the value 98 mean? Could you set it as a variable to explain?



_Code quote:_
```XML
   env.component.player.audio?.se [...]

2023-07-24 04:01 UTC, josephmyers reviewed
Cool, thanks for the review. The only place I'm diverging from the design doc is in allowing the user to select between the two audio's before having listened to the scripture. Maybe it's not a big deal to branch from that document, but I stuck to it as much as possible. It would be a bigger divergence from the design doc, but I super cool with that if that's the general understanding of the team. I just didn't want to go crazy for my first time.

I'm interested to know what your timing data looked like. Mine was working. Obviously the timing feature isn't in yet, so my integration with that is not intended to be final (I was fudging the data to verify it would only play the given range). Are you seeing timing data being passed to the audio player?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1964#-:-Na4QPefA1cvr3eQzyec:btvegwj)* status: 13 of 35 files reviewed, 21 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts` line 37 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1964#-N_oJypSEVN8H9O3OUbO:-Na4cSjJ4x4DfqPKD9Zj:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/5c9ac0668072fa5845dc4bfd9192456f586c8947/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts#L37)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Use relative paths here.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player-new/checking-audio-player-new.component.spec.ts` line 11 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1964#-N_oKVdV2KCQ_99QxO91:-Na4dZZO4LEnvhnORctU:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/5c9ac0668072fa5845dc4bfd9192456f586c8947/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player-new/checking-audio-player-new.component.spec.ts#L11)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Let's rename these folders so that there isn't a dot in the folder name. `audio-player` and `audio-player-base` should be sufficient.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.html` line 2 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1964#-N_oLEVi7TO_HXu1UPdX:-Na4eArWEwRasHy_HumA:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/5c9ac0668072fa5845dc4bfd9192456f586c8947/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.html#L2)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

You can use the async pipe here. It would look like *ngIf="isAudioAvailable | async"
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.ts` line 5 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1964#-N_oLdIm5tVfTUNNz2af:-Na4etWzC_y7oTZ472Xa:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/5c9ac0668072fa5845dc4bfd9192456f586c8947/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.ts#L5)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Use relative paths here.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.ts` line 24 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1964#-N_oMoGr8KKsdmvQL5eU:-Na4f0tu2usQxrSPhUkL:b8oaaob) ([raw file](https://github.com/sillsdev/web-xforge/blob/5c9ac0668072fa5845dc4bfd9192456f586c8947/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.ts#L24)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

You can make pwaService `private readonly`
</blockquote></details>

We're just passing this to the base class, so we don't need to save it here. Is that what you're wanting? I was thinking what I have now is just a pass-through -- is that wrong?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.ts` line 33 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1964#-N_oNDKn0Em0IRqeWuF0:-Na4hogC09L2qF0jFqg6:b-8k97s2) ([raw file](https://github.com/sillsdev/web-xforge/blob/5c9ac0668072fa5845dc4bfd9192456f586c8947/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.ts#L33)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

What do you think about using `this.audio` instead? When I see `this._audio`, I think I am expecting a private member, but in this case, it is actually in the base class.
</blockquote></details>

Sure. I made it private and added a protected set
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.spec.ts` line 7 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1964#-N_oOEDBDIjc_rqzE5fo:-Na4kIdD0uXqZPRWOLdT:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/5c9ac0668072fa5845dc4bfd9192456f586c8947/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.spec.ts#L7)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Use relative paths here.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.spec.ts` line 40 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1964#-N_oORyd05_8hQ7P8y7H:-Na4kL3_ASfcxubBqdUu:btx4aui) ([raw file](https://github.com/sillsdev/web-xforge/blob/5c9ac0668072fa5845dc4bfd9192456f586c8947/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.spec.ts#L40)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

That is strange this needs to be called twice. Would it work to just go env.wait(600) in the places where it is called twice, or is there a reason to need to call env.fixture.detectChanges twice?
</blockquote></details>

I agree that it's strange, but waiting longer didn't help. I had to use two wait's, and no less than 300ms was consistent for me
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.spec.ts` line 108 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1964#-N_oPCR_719kBrbDRVZ9:-Na4l60Q8f1nRU4E1cDX:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/5c9ac0668072fa5845dc4bfd9192456f586c8947/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.spec.ts#L108)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

What does the value 98 mean? Could you set it as a variable to explain?
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.spec.ts` line 125 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1964#-N_oPRJNBiTFF_z3qSwV:-Na4lQlL-0wuQHQC3xfA:b-8ni64d) ([raw file](https://github.com/sillsdev/web-xforge/blob/5c9ac0668072fa5845dc4bfd9192456f586c8947/src/SIL.XForge.Scripture/ClientApp/src/app/chec [...]

2023-07-24 16:35 UTC, RaymondLuong3 requested changes
Just a few more comments, mostly styling. Thanks for pointing me to the design doc. Sticking to the doc will be best as we implement this feature. When it comes time to test, we can then see how everything works together and then make some UI/UX changes to the design down if necessary. Nice work!

> Reviewed 24 of 24 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1964#-:-Na7jyvz1e8frzsCpk9c:b-5ndvs2)* status: all files reviewed, 6 unresolved discussions (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.ts` line 117 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1964#-Na7g80V1sDHsjC8cFRH:-Na7g80V1sDHsjC8cFRI:b2vg43c) ([raw file](https://github.com/sillsdev/web-xforge/blob/ccc410b0bd6fb833449e9f72b243edd92a9d49b3/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.ts#L117)):*
> ```XML
>       this.projectService.queryAudioText(projectId).then(audioQuery => {
>         this._scriptureTextAudioData = audioQuery?.docs?.find(t => t.id === audioId)?.data;
>         if (!this._scriptureTextAudioData || !this.scriptureAudioUrl) {
> ```

Style: We typically write `this._scriptureTextAudioData == null`
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player-new/checking-audio-player-new.component.spec.ts` line 5 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1964#-Na7geS0C9K4rQU-a6BK:-Na7geS0C9K4rQU-a6BL:bvhknw6) ([raw file](https://github.com/sillsdev/web-xforge/blob/ccc410b0bd6fb833449e9f72b243edd92a9d49b3/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player-new/checking-audio-player-new.component.spec.ts#L5)):*
> ```XML
> import { By } from '@angular/platform-browser';
> import { of } from 'rxjs';
> import { AudioStatus } from 'src/app/shared/audio/audio-player';
> ```

Use relative paths.



_Code quote:_
```XML
import { AudioStatus } from 'src/app/shared/audio/audio-player';
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.ts` line 24 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1964#-N_oMoGr8KKsdmvQL5eU:-Na7h-cbCdGu7Rt7eFAU:b2ppn35) ([raw file](https://github.com/sillsdev/web-xforge/blob/5c9ac0668072fa5845dc4bfd9192456f586c8947/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.ts#L24)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

We're just passing this to the base class, so we don't need to save it here. Is that what you're wanting? I was thinking what I have now is just a pass-through -- is that wrong?
</blockquote></details>

Oh yes you are right. I missed the part that this was just getting pasted through to the base class.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.spec.ts` line 125 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1964#-N_oPRJNBiTFF_z3qSwV:-Na7hrYG2vcURz_bAWh_:bplxh03) ([raw file](https://github.com/sillsdev/web-xforge/blob/5c9ac0668072fa5845dc4bfd9192456f586c8947/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.spec.ts#L125)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

I'm not following you. We subscribe to the event and increment the counter if the value is false. Or are you saying that you want the description to match the name exactly?
</blockquote></details>

Ok, I think I understand it now. The reason the count incremented is because `hasFishinedPlayingOnce$` fires, and you confirm that it does be checking the count incremented. Could you leave a comment that the count incremented because `hasFinishedPlayingOnce$` fired false.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking-question/checking-question.component.ts` line 49 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1964#-N_oZjuu5eGHlXXdyhiI:-Na7iPLO53sigeFtnSkp:b-mix806) ([raw file](https://github.com/sillsdev/web-xforge/blob/5c9ac0668072fa5845dc4bfd9192456f586c8947/src/SIL.XForge.Scripture/ClientApp/src/app/checking-question/checking-question.component.ts#L49)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Done. Is there a way we can customize our Prettier or ESLint to force this? I see https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/typedef.md
</blockquote></details>

Good thinking. Feel free to open another PR for that. I can't remember if we have discussed this or not, but it sounds like what we want.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.ts` line 37 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1964#-N_oci4TCZPy76eFrve2:-Na7js3n9ElCXunTg5XS:b-fmdcr1) ([raw file](https://github.com/sillsdev/web-xforge/blob/5c9ac0668072fa5845dc4bfd9192456f586c8947/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio/audio-player.ts#L37)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

It should be working. Is your timing data being read in properly?
</blockquote></details>

I'll do some more testing, but I won't let that hold up this PR. Just bringing it to your attention.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json` line 250 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1964#-Na7j1fb-liy2okVwpmR:-Na7j1fb-liy2okVwpmS:b-ohicqa) ([raw file](https://github.com/sillsdev/web-xforge/blob/ccc410b0bd6fb833449e9f72b243edd92a9d49b3/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json#L250)):*
> ```JSON
>   "checking_questions": {
>     "no_questions_found": "No questions found to match your filter",
>     "no_question_text": "Listen to the question for ",
> ```

The key string doesn't really match what the text says. Maybe `listen_to_question` would be a better key.



_Code quote:_
```JSON
    "no_question_text": "Listen to the question for ",
```
___
*[`src/SIL.XForge.Scripture/Services/SFProjectService.cs` line 831 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1964#-N_odSvXDmACFT9cB4O-:-Na7jKA1BPnGKMWYiybL:bzh8g5i) ([raw file](https://github.com/sillsdev/web-xforge/blob/5c9ac0668072fa5845dc4bfd9192456f586c8947/src/SIL.XForge.Scripture/Services/SFProjectService.cs#L831)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

I'm following the sample data given to us at https://drive.google.com/drive/folders/1bZTUElNADuXAYvhGvWSZdea7vteafZ7Z

We shouldn't really even merge this in. I just included it to make it possible for others to see things in action
</blockquote></details>

Yea, it's not really a big deal, but I'm happy to merge it until we get audio uploading working.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking-question/checking-question.component.html` line 26 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1964#-N_oaXPw5Bzg-qEctdbM:-Na7fgAp8fJPTbWSKgwL:b2glcta) ([raw file](https://github.com/sillsdev/web-xforge/blob/5c9ac0668072fa5845dc4bfd9192456f586c8947/src/SIL.XForge.Scripture/ClientApp/src/app/checking-question/checking-question.component.html#L26)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

This doesn't match the design doc, which says "Clicking the little audio button takes the state back to listen to the verses." If they mention it specifically, I feel like I would need a good reason to not do that. Do you want me to diverge from this?

I'm also a little biased. I experimented with text clickability, but I didn't like it. It didn't look right. If we want the text to be clickable, it'll take some other GUI changes/co [...]

2023-07-25 01:42 UTC, josephmyers reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1964)* status: 32 of 36 files reviewed, 5 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.ts` line 117 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1964#-Na7g80V1sDHsjC8cFRH:-Na9bCpc3E7HPN6-7Rhd:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/ccc410b0bd6fb833449e9f72b243edd92a9d49b3/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.ts#L117)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Style: We typically write `this._scriptureTextAudioData == null`
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player-new/checking-audio-player-new.component.spec.ts` line 5 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1964#-Na7geS0C9K4rQU-a6BK:-Na9ePcV2klPwaf35ruW:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/ccc410b0bd6fb833449e9f72b243edd92a9d49b3/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player-new/checking-audio-player-new.component.spec.ts#L5)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Use relative paths.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.spec.ts` line 125 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1964#-N_oPRJNBiTFF_z3qSwV:-Na9fM0P7VYAu3NPELyU:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/5c9ac0668072fa5845dc4bfd9192456f586c8947/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/single-button-audio-player/single-button-audio-player.component.spec.ts#L125)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Ok, I think I understand it now. The reason the count incremented is because `hasFishinedPlayingOnce$` fires, and you confirm that it does be checking the count incremented. Could you leave a comment that the count incremented because `hasFinishedPlayingOnce$` fired false.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json` line 250 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/1964#-Na7j1fb-liy2okVwpmR:-Na9fmK58NyoWx1lMpyM:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/ccc410b0bd6fb833449e9f72b243edd92a9d49b3/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json#L250)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

The key string doesn't really match what the text says. Maybe `listen_to_question` would be a better key.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/Services/SFProjectService.cs` line 831 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1964#-N_odSvXDmACFT9cB4O-:-Na9fqOU3879-jZmzPTK:b1tkop) ([raw file](https://github.com/sillsdev/web-xforge/blob/5c9ac0668072fa5845dc4bfd9192456f586c8947/src/SIL.XForge.Scripture/Services/SFProjectService.cs#L831)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Yea, it's not really a big deal, but I'm happy to merge it until we get audio uploading working.
</blockquote></details>

Okay, sounds good. It at least gets something working.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking-question/checking-question.component.html` line 26 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/1964#-N_oaXPw5Bzg-qEctdbM:-Na9aazr0DzjafSelSAi:b-u9mxss) ([raw file](https://github.com/sillsdev/web-xforge/blob/5c9ac0668072fa5845dc4bfd9192456f586c8947/src/SIL.XForge.Scripture/ClientApp/src/app/checking-question/checking-question.component.html#L26)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Ok, that is good to know that this was part of the spec. I didn't pay close attention to that. I think that we should stick to the spec as we get this feature out, and then make adjustments to it if we find it doesn't serve us best at that point.
</blockquote></details>

Yeah, I agree. Thanks


<!-- Sent from Reviewable.io -->

2023-07-25 04:14 UTC, josephmyers commented
@Nateowami was able to see an issue with uploading question audio when the question has no corresponding scripture audio. The audio player showed an error icon, but clicking on it played the audio as normal. I have not been able to reproduce this bug, but we should keep an eye out for it

2023-07-25 15:51 UTC, RaymondLuong3 approved these changes
Did you have a chance to look at the funny behaviour where the single button audio player appears broken after recording a new question audio? Fixing that can come in a follow up. Just create a card for that so we don't forget it is there.

> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1964#-:-NaCjT398wBjhL0hWvt_:by0res5)* status: all files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2023-07-25 18:36 UTC, merged

2023-07-26 02:37 UTC, josephmyers commented
@RaymondLuong3 That's what I was pinging Nathaniel about above. On his machine, it seemed linked to not having scripture audio. I spent some time on it yesterday but wasn't able to reproduce it. If I ever see it though, I'll make a bug for it