SF-2026 Chapter Audio UI
sillsdev/web-xforge pull request #1985
Opened 2023-08-01 09:22 UTC by josephmyers

2023-08-03 21:31 UTC, Nateowami commented
> Papa Parse has trouble parsing rows of the other format.

What is "the other format"?

2023-08-05 08:00 UTC, josephmyers commented
> > Papa Parse has trouble parsing rows of the other format.
> 
> What is "the other format"?

The other .txt in the test files folder, e.g. Mark_003.txt and Mark_004.txt. It appears to be due to each line being surrounded by quotes.

2023-08-09 06:45 UTC, nigel-wells requested changes
This is working well for a MVP. 

Def some work we can do for the UI but the sooner we can merge this the more others can make use of it for other areas. I'll just note some thoughts here:
- Error messages are different from our normal red under the element
- Upload timing file could button could work similar to audio where it changes to a delete button after you've uploaded something
- Not a fan of centering everything
- Could try and make the elements work/look like normal material inputs - somehow. where it is all inlined. This would help for a future idea where you could setup multiple chapters all from the one screen
- Tooltip (or link to help?) to explain how timing data should be formatted i.e. the columns, or even what software we recommend/support.

The other files have come from Adobe Audition. The quotes surrounding it, however, I'm not sure how the user got them added - perhaps they tried opening it in Excel and saved it again or something strange but they are not there as a result of an Adobe Audition export.

> Reviewed 10 of 17 files at r1, 10 of 14 files at r4, 1 of 14 files at r5, 13 of 13 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1985#-:-NbHS24F2n9b4P6xriU5:bt95lvv)* status: all files reviewed, 30 unresolved discussions (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 46 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1985#-NbNlxdj9GS0W4JCjHqk:-NbNlxdj9GS0W4JCjHql:b-v5zqav) ([raw file](https://github.com/sillsdev/web-xforge/blob/d9e6ed76296b924575654d5ce53b310d88dc87d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L46)):*
> ```XML
>   private _hasTimingBeenUploaded: boolean = false;
>   private _audioLength: number = 0;
>   private _errorText: string = '';
> ```

This needs to be a translatable string. Also, it isn't clear that this text only relates to a timing data error.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 64 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1985#-NbNkqOW6AX0JcnbafoI:-NbNkqOW6AX0JcnbafoJ:b-2g3riz) ([raw file](https://github.com/sillsdev/web-xforge/blob/d9e6ed76296b924575654d5ce53b310d88dc87d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L64)):*
> ```XML
>     for (const question of publishedQuestions) {
>       const bookNum = question.data?.verseRef.bookNum!;
>       const chapterNum = question.data?.verseRef.chapterNum;
> ```

This could be `undefined`. Perhaps let both `bookNum` and `chapterNum` be set without a `!` and if either is `undefined` then `continue`.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 66 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1985#-NbNlK8p5Z38kOuT101k:-NbNlK8p5Z38kOuT101l:by7at71) ([raw file](https://github.com/sillsdev/web-xforge/blob/d9e6ed76296b924575654d5ce53b310d88dc87d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L66)):*
> ```XML
>       const chapterNum = question.data?.verseRef.chapterNum;
> 
>       const text = this.data.textsByBookId[Canon.bookNumberToId(bookNum)];
> ```

nit  add type
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 68 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1985#-NbNkeT_4B_RU3ohRmiD:-NbNkeT_4B_RU3ohRmiE:bcdnwfy) ([raw file](https://github.com/sillsdev/web-xforge/blob/d9e6ed76296b924575654d5ce53b310d88dc87d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L68)):*
> ```XML
>       const text = this.data.textsByBookId[Canon.bookNumberToId(bookNum)];
>       const textChapter = text?.chapters.find(c => c.number === chapterNum);
>       if (!textChapter?.hasAudio) {
> ```

Need a check on `textChapter` as it could be undefined
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 81 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1985#-NbNlG3NDfC-dkN84KyV:-NbNlG3NDfC-dkN84KyW:b-ljxt83) ([raw file](https://github.com/sillsdev/web-xforge/blob/d9e6ed76296b924575654d5ce53b310d88dc87d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L81)):*
> ```XML
> 
>   private checkForPreexistingAudio(): void {
>     const text = this.data.textsByBookId[Canon.bookNumberToId(this.book)];
> ```

nit  Add type and for `textChapter`
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 135 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1985#-NbNmIPtEHab9aIkQv4J:-NbNmIPtEHab9aIkQv4K:bvmn99v) ([raw file](https://github.com/sillsdev/web-xforge/blob/d9e6ed76296b924575654d5ce53b310d88dc87d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L135)):*
> ```XML
> 
>   async audioUpdate(audio: AudioAttachment): Promise<void> {
>     this.audio = audio;
> ```

Should we only set this after the `url` check?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 167 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1985#-NbNnX9N3Yo1Wf1_4B5I:-NbNnX9N3Yo1Wf1_4B5J:bxakbup) ([raw file](https://github.com/sillsdev/web-xforge/blob/d9e6ed76296b924575654d5ce53b310d88dc87d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L167)):*
> ```XML
>   }
> 
>   private async validateTimingEntries(timing: AudioTiming[], audioLength: number): Promise<void> {
> ```

Does this need to be `async` ?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 207 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1985#-NbNoOPaDLEgng9g4QQk:-NbNoOPaDLEgng9g4QQl:bei1lg1) ([raw file](https://github.com/sillsdev/web-xforge/blob/d9e6ed76296b924575654d5ce53b310d88dc87d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L207)):*
> ```XML
>     );
>     this._loadingAudio = false;
>     if (audioUrl === null || audioUrl === undefined) {
> ```

Can be changed to `audioUrl == null` which covers both instances
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 220 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1985#-NbNnNs84YP6h6k2JPl3:-NbNnNs84YP6h6k2JPl4:bxakbup) ([raw file](https://github.com/sillsdev/web-xforge/blob/d9e6ed76296b924575654d5ce53b310d88dc87d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L220)):*
> ```XML
>   }
> 
>   private async populateToField(index: number, rows: AudioTiming[]): Promise<number> {
> ```

Does this need to be `async` ?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 223 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1985#-NbNnwz79EyChXoJu1xN:-NbNnwz79EyChXoJu1xO:b-1tqsht) ([raw file](https://github.com/sillsdev/web-xforge/blob/d9e6ed76296b924575654d5ce53b310d88dc87d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L223)):*
> ```XML
>     const row: AudioTiming = rows[index];
>     const to: number = row.to;
>     if (to > 0) return to;
> ```

Could you simply check `row.to > 0` rather than creating the `to` variable?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 228 at  [...]

2023-08-09 08:42 UTC, josephmyers reviewed
Thanks for the review. I also am not crazy about the UI, but I do like centering things as they currently are better than left-aligning them. The real problem is how wide the audio player is when loaded. Couple that with its Upload label at small width's, and you have to have something like titles to differentiate between the two inputs. Definitely feel free to give it a facelift!

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1985#-:-NbOF0tpAO4tmbEQcKY6:bs7i1fo)* status: all files reviewed, 21 unresolved discussions (waiting on @github-code-scanning[bot] and @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 160 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1985#gh-1280349585:-NbOJXIu18nzDg5kCre5:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/e69e2c60891ed785a7b638ee590d9f4d288bec6f/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L160)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Comparison with NaN

Useless comparison with NaN.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/620)
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 160 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/1985#gh-1280349589:-NbOJXwK4GcLEjeU5yJC:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/e69e2c60891ed785a7b638ee590d9f4d288bec6f/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L160)):*
<details><summary><i>Previously, github-code-scanning[bot] wrote…</i></summary><blockquote>

## Comparison with NaN

Useless comparison with NaN.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/621)
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 46 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1985#-NbNlxdj9GS0W4JCjHqk:-NbOHsHWC14T-47IgXbs:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/d9e6ed76296b924575654d5ce53b310d88dc87d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L46)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

This needs to be a translatable string. Also, it isn't clear that this text only relates to a timing data error.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 64 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1985#-NbNkqOW6AX0JcnbafoI:-NbOIAzH3m7di2VujegG:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/d9e6ed76296b924575654d5ce53b310d88dc87d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L64)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

This could be `undefined`. Perhaps let both `bookNum` and `chapterNum` be set without a `!` and if either is `undefined` then `continue`.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 66 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1985#-NbNlK8p5Z38kOuT101k:-NbOIQar63-6kC0iAdZm:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/d9e6ed76296b924575654d5ce53b310d88dc87d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L66)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

nit  add type
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 68 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1985#-NbNkeT_4B_RU3ohRmiD:-NbOIk274EOz8i31BY10:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/d9e6ed76296b924575654d5ce53b310d88dc87d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L68)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Need a check on `textChapter` as it could be undefined
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 135 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1985#-NbNmIPtEHab9aIkQv4J:-NbOJ4ji9a_hkHCnRQbi:bsi3or1) ([raw file](https://github.com/sillsdev/web-xforge/blob/d9e6ed76296b924575654d5ce53b310d88dc87d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L135)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Should we only set this after the `url` check?
</blockquote></details>

My only thought is that it would not allow the audio to be cleared. Thoughts?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 167 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1985#-NbNnX9N3Yo1Wf1_4B5I:-NbOJq6mAC9CreiuVsym:b-1nju6h) ([raw file](https://github.com/sillsdev/web-xforge/blob/d9e6ed76296b924575654d5ce53b310d88dc87d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L167)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Does this need to be `async` ?
</blockquote></details>

Not anymore! Thanks
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 207 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1985#-NbNoOPaDLEgng9g4QQk:-NbOJyChE7plc-LBfSzr:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/d9e6ed76296b924575654d5ce53b310d88dc87d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L207)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Can be changed to `audioUrl == null` which covers both instances
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 220 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1985#-NbNnNs84YP6h6k2JPl3:-NbOK0sc9WfJezpE1g2B:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/d9e6ed76296b924575654d5ce53b310d88dc87d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L220)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Does this need to be `async` ?
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 223 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1985#-NbNnwz79EyChXoJu1xN:-NbOK8hm-F1Onl0GoK8z:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/d9e6ed76296b924575654d5ce53b310d88dc87d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L223)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Could you simply check `row.to > 0` rather than creating the `to` variable?
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 228 at r6](https://reviewable.io/review [...]

2023-08-10 02:10 UTC, nigel-wells requested changes
Couple of other UI bugs/tweaks on the community checking app I noticed that we can address later:
- If you play the chapter audio, and then change questions, the player stays visible even if the next question is in a different chapter
- Clicking the play chapter icon should immediately start playing audio rather than just making the component visible and requiring you to click a second play button
- If audio is not available then the play and seek buttons should be disabled
- Adding should default the book and chapter to whatever is currently in view

> Reviewed 14 of 14 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1985#-:-NbSB4FFC-_ciT4WCyWz:b-9tcrb4)* status: all files reviewed, 5 unresolved discussions (waiting on @github-code-scanning[bot] and @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 46 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1985#-NbNlxdj9GS0W4JCjHqk:-NbS9Clg5ozM-meY8pf4:bgrgoko) ([raw file](https://github.com/sillsdev/web-xforge/blob/d9e6ed76296b924575654d5ce53b310d88dc87d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L46)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can you change the type to `I18nKey` as this will ensure the keys you use further down match up with real keys defined in our translation files.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 135 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1985#-NbNmIPtEHab9aIkQv4J:-NbS4igw7ZrydNJ8tLJX:b-5p0ggb) ([raw file](https://github.com/sillsdev/web-xforge/blob/d9e6ed76296b924575654d5ce53b310d88dc87d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L135)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

My only thought is that it would not allow the audio to be cleared. Thoughts?
</blockquote></details>

Good point. I see `CheckingAudioCombinedComponent` can emit a `reset` which would be worth handling. Perhaps we should unset it completely if it isn't valid? The only thing using it at the moment is the `save()` method and that is handling it fine so I'm not overly fussed at this point. I won't block this and leave it up to you if you feel you want to do something further.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.spec.ts` line 172 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1985#-NbO-r-x2dqqh6DazKV8:-NbS8e4B17VnKQ6_tLSr:bcztgws) ([raw file](https://github.com/sillsdev/web-xforge/blob/d9e6ed76296b924575654d5ce53b310d88dc87d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.spec.ts#L172)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Nope! I did get confused when I was writing these, though. Please double check
</blockquote></details>

Ah, I see why I got confused. The test talks about one thing but only deals with the opposite. I get it now :)
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.html` line 11 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1985#-NbSAnuEAvSwcngNqR6w:-NbSAnuEAvSwcngNqR6x:b-uu0awl) ([raw file](https://github.com/sillsdev/web-xforge/blob/20b853540442e3e179f0bf4acbb5a768bb0ce557/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.html#L11)):*
> ```HTML
>     <button mat-icon-button class="next-ref-button" (click)="nextRef()"><mat-icon>skip_next</mat-icon></button>
>   </div>
>   <button *ngIf="canDelete" mat-icon-button class="close-button" (click)="deleteAudioTimingData()">
> ```

This works as a quick replacement of what we had before (add and delete). I suspect we'd probably end up with an edit option to manage the timing data or audio rather than completely deleting it and having to start again. Doesn't need to hold things up.


<!-- Sent from Reviewable.io -->

2023-08-10 03:24 UTC, josephmyers reviewed
These are good comments. I didn't mess with the chapter audio, other than to move the delete button there. But I agree they should be addressed.

I fixed your last note, as it's something I missed for the dialog. It was working at one point...

> Dismissed @github-code-scanning[bot] from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1985#-:-NbSI4J9DrPj8cPRVPP6:bf2w46p)* status: 28 of 32 files reviewed, 4 unresolved discussions (waiting on @github-code-scanning[bot] and @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 46 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1985#-NbNlxdj9GS0W4JCjHqk:-NbSQUIn8k5nZP5NxDaI:bb6un1j) ([raw file](https://github.com/sillsdev/web-xforge/blob/d9e6ed76296b924575654d5ce53b310d88dc87d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L46)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Can you change the type to `I18nKey` as this will ensure the keys you use further down match up with real keys defined in our translation files.
</blockquote></details>

Done
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 135 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/1985#-NbNmIPtEHab9aIkQv4J:-NbSR2PT4NnrpqQaJjg9:bm70p7i) ([raw file](https://github.com/sillsdev/web-xforge/blob/d9e6ed76296b924575654d5ce53b310d88dc87d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L135)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Good point. I see `CheckingAudioCombinedComponent` can emit a `reset` which would be worth handling. Perhaps we should unset it completely if it isn't valid? The only thing using it at the moment is the `save()` method and that is handling it fine so I'm not overly fussed at this point. I won't block this and leave it up to you if you feel you want to do something further.
</blockquote></details>

Yeah, I think it's fine. If audio were public, it could be misinterpreted, but it's okay while it's private.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.html` line 11 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1985#-NbSAnuEAvSwcngNqR6w:-NbSRf_eAB35ZB1K4REz:b-csc9gb) ([raw file](https://github.com/sillsdev/web-xforge/blob/20b853540442e3e179f0bf4acbb5a768bb0ce557/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.html#L11)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

This works as a quick replacement of what we had before (add and delete). I suspect we'd probably end up with an edit option to manage the timing data or audio rather than completely deleting it and having to start again. Doesn't need to hold things up.
</blockquote></details>

Yeah. Your PR will make this is a much lower use case. But the functionality was on the question page before, and I didn't feel strongly enough about it to remove it completely. If we want to, I am totally cool with that.


<!-- Sent from Reviewable.io -->

2023-08-10 04:05 UTC, nigel-wells requested changes
> Reviewed 23 of 23 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1985)* status: all files reviewed, 8 unresolved discussions (waiting on @github-code-scanning[bot] and @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 24 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/1985#-NbSattqClFtA-fEooPg:-NbSattqClFtA-fEooPh:b-okrkxu) ([raw file](https://github.com/sillsdev/web-xforge/blob/ee959f0b250b0f9431e439e1ad5715c24b4742df/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L24)):*
> ```XML
>   textsByBookId: TextsByBookId;
>   questionsSorted: readonly QuestionDoc[];
>   currentBook: number | undefined;
> ```

Use `currentBook?: number` - same as below. This will save you having to make sure it is set to something in your tests.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 137 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/1985#-NbSbV_GAaqZylDT8giR:-NbSbV_GAaqZylDT8giS:b-kihaox) ([raw file](https://github.com/sillsdev/web-xforge/blob/ee959f0b250b0f9431e439e1ad5715c24b4742df/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L137)):*
> ```XML
> 
>   get errorMessage(): string {
>     return this._timingErrorText ?? '';
> ```

I'm surprised this worked. If you set the errors to their keys and then return the key to the template the template can then pass it through `t(error)`. What you might find otherwise is if there is an error, and you change the language, the string probably won't update until it is triggered again.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.spec.ts` line 257 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/1985#-NbSbBiXDucThHjxQ-XH:-NbSbBiXDucThHjxQ-XI:bag4xeq) ([raw file](https://github.com/sillsdev/web-xforge/blob/ee959f0b250b0f9431e439e1ad5715c24b4742df/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.spec.ts#L257)):*
> ```XML
>           textsByBookId: TestEnvironment.textsByBookId,
>           questionsSorted: this.questions,
>           currentBook: undefined,
> ```

You'll be able to remove `currentBook` and `currentChapter` after the interface is updated to make them optional.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.html` line 11 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/1985#-NbSAnuEAvSwcngNqR6w:-NbSa6tg7mMI4wuFJqc3:btzmqbb) ([raw file](https://github.com/sillsdev/web-xforge/blob/20b853540442e3e179f0bf4acbb5a768bb0ce557/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-scripture-audio-player/checking-scripture-audio-player.component.html#L11)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Yeah. Your PR will make this is a much lower use case. But the functionality was on the question page before, and I didn't feel strongly enough about it to remove it completely. If we want to, I am totally cool with that.
</blockquote></details>

I'm happy for the button to be there for now to allow for existing test scenarios. We can review once all the other PRs are merged in.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts` line 317 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/1985#-NbSbJhp9sMfZjan9aXh:-NbSbJhp9sMfZjan9aXi:b-egyfpi) ([raw file](https://github.com/sillsdev/web-xforge/blob/ee959f0b250b0f9431e439e1ad5715c24b4742df/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts#L317)):*
> ```XML
>       textsByBookId: this.textsByBookId,
>       questionsSorted: this.allPublishedQuestions,
>       currentBook: undefined,
> ```

Can be removed here as well.


<!-- Sent from Reviewable.io -->

2023-08-14 02:02 UTC, josephmyers reviewed
> Dismissed @github-code-scanning[bot] from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1985)* status: all files reviewed, 5 unresolved discussions (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 24 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/1985#-NbSattqClFtA-fEooPg:-Nbla1Gw3a9MRIh5c77P:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/ee959f0b250b0f9431e439e1ad5715c24b4742df/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L24)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Use `currentBook?: number` - same as below. This will save you having to make sure it is set to something in your tests.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 137 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/1985#-NbSbV_GAaqZylDT8giR:-NblgkDMDAtradsyfq_D:bjd8jke) ([raw file](https://github.com/sillsdev/web-xforge/blob/ee959f0b250b0f9431e439e1ad5715c24b4742df/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L137)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

I'm surprised this worked. If you set the errors to their keys and then return the key to the template the template can then pass it through `t(error)`. What you might find otherwise is if there is an error, and you change the language, the string probably won't update until it is triggered again.
</blockquote></details>

Ok, if I'm understanding you, you want the translation to happen at the template level. Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.spec.ts` line 257 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/1985#-NbSbBiXDucThHjxQ-XH:-NblktHEEIZTMgRuc6Td:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/ee959f0b250b0f9431e439e1ad5715c24b4742df/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.spec.ts#L257)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

You'll be able to remove `currentBook` and `currentChapter` after the interface is updated to make them optional.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts` line 317 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/1985#-NbSbJhp9sMfZjan9aXh:-Nbll0VG996swlT04PNw:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/ee959f0b250b0f9431e439e1ad5715c24b4742df/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts#L317)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Can be removed here as well.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-14 21:22 UTC, nigel-wells approved these changes
> Reviewed 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1985)* status: all files reviewed, 1 unresolved discussion (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html` line 1 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/1985#-Nbpv8OsCYg04T0L4Ee_:-Nbpv8OsCYg04T0L4Eea:bbu3wai) ([raw file](https://github.com/sillsdev/web-xforge/blob/ee959f0b250b0f9431e439e1ad5715c24b4742df/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html#L1)):*
> ```HTML
> <ng-container *transloco="let t; read: 'checking_audio_dialog'">
> ```

Why did this need to change - did the `t(errorMessage)` cause issues? This is non blocking so I'm just asking the question. Ideally we wouldn't have to prefix every translate message but if it is what it is.


<!-- Sent from Reviewable.io -->

2023-08-15 01:08 UTC, josephmyers reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/1985)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html` line 1 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/1985#-Nbpv8OsCYg04T0L4Ee_:-NbqiR0W4YmRHD2krtek:b-dkqubj) ([raw file](https://github.com/sillsdev/web-xforge/blob/ee959f0b250b0f9431e439e1ad5715c24b4742df/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html#L1)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Why did this need to change - did the `t(errorMessage)` cause issues? This is non blocking so I'm just asking the question. Ideally we wouldn't have to prefix every translate message but if it is what it is.
</blockquote></details>

Yeah, it was an unfortunate side effect of storing the string as an I18nKey. The keys had to be stored as the fully qualified name, and the t() was also prepending the section, which broke those lookups.


<!-- Sent from Reviewable.io -->

2023-08-15 02:14 UTC, merged