SF-2193 Add bubble splash effect that can be added to various buttons
sillsdev/web-xforge pull request #2013
Opened 2023-08-22 02:41 UTC by siltomato

This is part of the gamification initiative to add visual rewards for app actions.  The bubble splash effect is implemented as a directive that can be added to angular material buttons.
```html
<button mat-flat-button sfBubbleButton color="primary">Mat flat button</button>
```
Sample buttons can be seen in storybook under 'Misc/Bubble Button'.

2023-08-22 20:16 UTC, Nateowami reviewed
Overall looks good. A couple comments.

Curious if you considered using a third-party library to simplify the creation of this? See e.g. the feature/confetti branch from a few months ago.

Was it intentional that the size of bubbles seems to be scaled relative to button size? I found that a bit odd. I thought if it was necessary to scale the size of the buttons, that would make sense as a parameter.

**I am not taking responsibility for reviewing this, just swinging by to add a few comments.**

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2013#-:-NcTntUT4JrhJpuQJYsc:b-ewqtls)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/bubble-button/bubble-button.directive.ts` line 11 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2013#-NcTpduu0DFIWAg6Fa8W:-NcTpduu0DFIWAg6Fa8X:bv9scym) ([raw file](https://github.com/sillsdev/web-xforge/blob/76b45087f81d28b91b1cfcaad0a84ed4eb606d00/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/bubble-button/bubble-button.directive.ts#L11)):*
> ```XML
> @Directive({
>   selector: '[sfBubbleButton]'
> })
> ```

Does Angular not allow specifying CSS for a directive?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/bubble-button/bubble-button.stories.ts` line 26 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2013#-NcToE2u0GF0qlXI05bb:-NcToE2u0GF0qlXI05bc:bcpj61w) ([raw file](https://github.com/sillsdev/web-xforge/blob/76b45087f81d28b91b1cfcaad0a84ed4eb606d00/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/bubble-button/bubble-button.stories.ts#L26)):*
> ```XML
> type Story = StoryObj;
> 
> export const MatRaisedButton: Story = {
> ```

There are a lot of stories here that all do the same thing in just about the same way (so far as I can tell). Chromatic bills us per screenshot. We're not going to go broke due to having six more screenshots than necessary, but if we consistently create several times as many as really necessary, we're likely to put ourselves in a position where we're forced to upgrade to a plan with more screenshots.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/bubble-button/bubble-button.stories.ts` line 28 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2013#-NcTpLdoAMzfMVHVPBmQ:-NcTpLdoAMzfMVHVPBmR:b-xhwjg2) ([raw file](https://github.com/sillsdev/web-xforge/blob/76b45087f81d28b91b1cfcaad0a84ed4eb606d00/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/bubble-button/bubble-button.stories.ts#L28)):*
> ```XML
> export const MatRaisedButton: Story = {
>   render: () => ({
>     template: `<button mat-raised-button sfBubbleButton color="primary">Mat raised button</button>`
> ```

This is a lot more verbose than necessary on all these stories. Instead of specifying a render function on all of them, it seems like it would make more sense to use [args](https://storybook.js.org/docs/angular/writing-stories/args). Maybe that wouldn't work as well as I think in this situation.


<!-- Sent from Reviewable.io -->

2023-08-29 23:01 UTC, marksvc requested changes
I like it. I noticed that the short buttons only have a little bit of celebration. I think we should decide on the amount of celebration (for example, the size of the bubbles, and how far out they fly), and make it consistent for large and small buttons.

I think it does make sense to use a 3rd party library. It seems like something that someone else would have already provided. I also haven't looked into it. I also like the bubbles. :)

I think I'm learning here rather than in a position to provide a scrutinous review. But I considered the files and made comments.

Thanks for your work!

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2013#-:-Nd2JWCY8-1SQ_XN8CEM:b9tcb7n)* status: all files reviewed, 9 unresolved discussions (waiting on @Nateowami and @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/bubble-button/bubble-button.scss` line 6 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2013#-Nd2Q0fq9EHKP1BR_gzB:-Nd2Q0fq9EHKP1BR_gzC:b-36nxwo) ([raw file](https://github.com/sillsdev/web-xforge/blob/76b45087f81d28b91b1cfcaad0a84ed4eb606d00/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/bubble-button/bubble-button.scss#L6)):*
> ```SCSS
> 
> /// Gets the min/max css function to constrain the size within a min and max size in px.
> /// @param {number} $sizePercentage - The size of the bubble as a percentage of the button size.
> ```

Yeah, maybe this could be based on something other than the size of the button, so it's uniform across buttons of varying lengths. Maybe it could be based on
- height of the button,
- height or width of the web page's viewport, or
- a constant px or em value, if that looks good on different viewports
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/bubble-button/bubble-button.scss` line 111 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2013#-Nd2T-U07tGx0Ur1aG2L:-Nd2T-U07tGx0Ur1aG2M:b-msjj2j) ([raw file](https://github.com/sillsdev/web-xforge/blob/76b45087f81d28b91b1cfcaad0a84ed4eb606d00/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/bubble-button/bubble-button.scss#L111)):*
> ```SCSS
>       right: -20%;
> 
>       // Needed to make the padding increase the height as the width increases.
> ```

I wonder if it will result in UI elements getting pushed around, if the button is in the midst of other UI elements when this happens?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/bubble-button/bubble-button.scss` line 114 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2013#-Nd2TE_LC8XHP_-fNOOP:-Nd2TE_LC8XHP_-fNOOQ:b-nhuhzl) ([raw file](https://github.com/sillsdev/web-xforge/blob/76b45087f81d28b91b1cfcaad0a84ed4eb606d00/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/bubble-button/bubble-button.scss#L114)):*
> ```SCSS
>       // Long buttons need more height for the animation so the circles don't get cut off.
>       box-sizing: content-box;
>       padding-top: 30%; // Percentage of width of containing element
> ```

Do you mean "height" instead of "width"?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/bubble-button/bubble-button.scss` line 114 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2013#-Nd2TIcJ7J0OKDf-vzQj:-Nd2TIcJ7J0OKDf-vzQk:b-9e0eao) ([raw file](https://github.com/sillsdev/web-xforge/blob/76b45087f81d28b91b1cfcaad0a84ed4eb606d00/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/bubble-button/bubble-button.scss#L114)):*
> ```SCSS
>       // Long buttons need more height for the animation so the circles don't get cut off.
>       box-sizing: content-box;
>       padding-top: 30%; // Percentage of width of containing element
> ```

Because the bubbles fly out at known range of pixels, wouldn't you want to set padding-top to close to the value of the maximum px distance that a bubble might fly out? Or what is the purpose of using a percentage of the size of the containing element?

Also, would you not also need a padding-bottom?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/bubble-button/bubble-button.scss` line 121 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2013#-Nd2TrXO5AjO7fo-wRzW:-Nd2TrXO5AjO7fo-wRzX:b9po9r8) ([raw file](https://github.com/sillsdev/web-xforge/blob/76b45087f81d28b91b1cfcaad0a84ed4eb606d00/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/bubble-button/bubble-button.scss#L121)):*
> ```SCSS
> 
>     &:before {
>       display: none;
> ```

Why is `display` configured both here and above in the following? Is that a mistake, or is there a particular behaviour that causes?
```css
    &:before,
    &:after {
      position: absolute;
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/bubble-button/bubble-button.scss` line 129 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2013#-Nd2VVT20jQT0sQWgMR1:-Nd2VVT20jQT0sQWgMR2:b-fiyntz) ([raw file](https://github.com/sillsdev/web-xforge/blob/76b45087f81d28b91b1cfcaad0a84ed4eb606d00/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/bubble-button/bubble-button.scss#L129)):*
> ```SCSS
>     &:after {
>       display: none;
>       top: 65%;
> ```

(And this is not at odds with the following? )

```css
&:before,
&:after {
  ...
  height: 100%;
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/bubble-button/bubble-button.stories.ts` line 26 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2013#-NcToE2u0GF0qlXI05bb:-Nd2K2sy2J-ubIeuNJeh:balruyl) ([raw file](https://github.com/sillsdev/web-xforge/blob/76b45087f81d28b91b1cfcaad0a84ed4eb606d00/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/bubble-button/bubble-button.stories.ts#L26)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

There are a lot of stories here that all do the same thing in just about the same way (so far as I can tell). Chromatic bills us per screenshot. We're not going to go broke due to having six more screenshots than necessary, but if we consistently create several times as many as really necessary, we're likely to put ourselves in a position where we're forced to upgrade to a plan with more screenshots.
</blockquote></details>

@Nateowami, :-/ Can we disconnect some of our storybook tests from Chromatic?
I found it helpful to click thru the different UI cases and see the behaviour for them. It will be too bad if using Chromatic resulted in needing to restrict ourselves.


<!-- Sent from Reviewable.io -->

2023-08-30 00:14 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2013)* status: all files reviewed, 9 unresolved discussions (waiting on @marksvc and @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/bubble-button/bubble-button.stories.ts` line 26 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2013#-NcToE2u0GF0qlXI05bb:-Nd2mJK--yr5vr65_ZFU:b-hx3upc) ([raw file](https://github.com/sillsdev/web-xforge/blob/76b45087f81d28b91b1cfcaad0a84ed4eb606d00/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/bubble-button/bubble-button.stories.ts#L26)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

@Nateowami, :-/ Can we disconnect some of our storybook tests from Chromatic?
I found it helpful to click thru the different UI cases and see the behaviour for them. It will be too bad if using Chromatic resulted in needing to restrict ourselves.
</blockquote></details>

Yes, that can be done. Though I thought args would make more sense, and allow even more flexibility with experimenting with possible variations.


<!-- Sent from Reviewable.io -->

2023-09-08 17:54 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2013)* status: all files reviewed, 9 unresolved discussions (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/bubble-button/bubble-button.stories.ts` line 26 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2013#-NcToE2u0GF0qlXI05bb:-NdpvIaMDhkMPitdI1s3:bsg18yh) ([raw file](https://github.com/sillsdev/web-xforge/blob/76b45087f81d28b91b1cfcaad0a84ed4eb606d00/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/bubble-button/bubble-button.stories.ts#L26)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Yes, that can be done. Though I thought args would make more sense, and allow even more flexibility with experimenting with possible variations.
</blockquote></details>

Actually, come to think of it, Chromatic isn't going to be able to do a good job screenshotting an animation anyway, so my point was kind of moot. @siltomato Can you just disable Chromatic for this entire file? https://www.chromatic.com/docs/ignoring-elements


<!-- Sent from Reviewable.io -->

2025-03-24 04:26 UTC, josephmyers commented
@Nateowami, do we want to leave this open, as well?

2025-08-05 23:28 UTC, merged