SF-2022 Improve chapter audio dialog UI
sillsdev/web-xforge pull request #2051
Opened 2023-09-08 04:48 UTC by nigel-wells

* Moved existing audio warning into book selector
* Added  icon for book selector
* Change colours for invalid errors
* Trigger invalid errors when saving
* Set long filenames to overflow ellipse
* Added missing translation strings
* Removed redundant test async

2023-09-08 22:21 UTC, RaymondLuong3 requested changes
Nice work. I did some testing and found it to be working quite nicely. If I happen to select 2 timings or audio files, it drops one and takes the second one. I wonder if we need to handle this case by throwing and error to the user.
I see we are requiring a user to upload timing files in order to upload audio. I think a small number of users may not like that, but I imagine that most would be recording in HearThis or Audacity, in which case the timing data is easy to get. But I'm also not certain where most audio data will be coming from.
Several minor comments, but I like this a lot!

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2051#-:-Ndqs-LV3CoN3U_npKgh:bhvtkhd)* status: all files reviewed, 15 unresolved discussions (waiting on @josephmyers and @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog-service.ts` line 14 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2051#-NdqXQc57GzvoAd8fmn3:-NdqXQc6BByqqWw0S5pH:b-kslh9b) ([raw file](https://github.com/sillsdev/web-xforge/blob/1af4f91266f5fa74aab1eb0e6ef56972e44ad9fa/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog-service.ts#L14)):*
> ```XML
>   providedIn: 'root'
> })
> export class ChapterAudioDialogService {
> ```

Let's rename this file to `chapter-audio-dialog.service.ts` to be consistent with our other service classes.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html` line 30 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2051#-NdqjPzW3K73WfdfAMp8:-NdqjPzW3K73WfdfAMp9:bpkvnnr) ([raw file](https://github.com/sillsdev/web-xforge/blob/1af4f91266f5fa74aab1eb0e6ef56972e44ad9fa/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html#L30)):*
> ```HTML
>       </div>
>       <div class="wrapper wrapper-audio" [ngClass]="{ valid: hasAudioBeenUploaded, invalid: audioErrorMessage !== '' }">
>         <ng-container *ngIf="hasAudioBeenUploaded">
> ```

Do we need an ng-container here?



_Code quote:_
```HTML
        <ng-container *ngIf="hasAudioBeenUploaded">
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html` line 49 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2051#-Ndqa_-J4PK1g1wtel3L:-Ndqa_-J4PK1g1wtel3M:b-8rr2zh) ([raw file](https://github.com/sillsdev/web-xforge/blob/1af4f91266f5fa74aab1eb0e6ef56972e44ad9fa/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html#L49)):*
> ```HTML
>           <span *ngIf="!hasAudioBeenUploaded && audioErrorMessage !== ''">{{
>             t("checking_audio_dialog.no_audio_file_uploaded")
>           }}</span>
> ```

This doesn't look right, there are two spans with the same content.



_Code quote:_
```HTML
          <span *ngIf="!hasAudioBeenUploaded && audioErrorMessage !== ''">{{
            t("checking_audio_dialog.no_audio_file_uploaded")
          }}</span>
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html` line 54 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2051#-NdqahDS0sUG_qPyK-dX:-NdqahDS0sUG_qPyK-dY:b131v96) ([raw file](https://github.com/sillsdev/web-xforge/blob/1af4f91266f5fa74aab1eb0e6ef56972e44ad9fa/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html#L54)):*
> ```HTML
>       <div
>         class="wrapper wrapper-timing"
>         [ngClass]="{ valid: hasTimingBeenUploaded, invalid: timingErrorMessage !== '' }"
> ```

Are we forcing users to upload a timing file as well as a audio?



_Code quote:_
```HTML
        [ngClass]="{ valid: hasTimingBeenUploaded, invalid: timingErrorMessage !== '' }"
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.scss` line 3 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2051#-Ndqkxr8-yDhKQYSAtWF:-Ndqkxr8-yDhKQYSAtWG:b2ntlss) ([raw file](https://github.com/sillsdev/web-xforge/blob/1af4f91266f5fa74aab1eb0e6ef56972e44ad9fa/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.scss#L3)):*
> ```SCSS
> @use 'src/variables';
> 
> @mixin wrapperState($borderColor, $textColor) {
> ```

Nice mixin. I'll need to try and make one of these one day.



_Code quote:_
```SCSS
@mixin wrapperState($borderColor, $textColor) {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 69 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2051#-NdqlCkF6qtX4WoG9COc:-NdqlCkF6qtX4WoG9COd:bn0hz2j) ([raw file](https://github.com/sillsdev/web-xforge/blob/1af4f91266f5fa74aab1eb0e6ef56972e44ad9fa/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L69)):*
> ```XML
> 
>   get audioFilename(): string {
>     return this.audio?.fileName || '';
> ```

This could be `return this.audio?.fileName ?? ''` since the right-hand option should only be taken if the fileName is null or underfined.



_Code quote:_
```XML
    return this.audio?.fileName || '';
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 262 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2051#-Ndqn9W-1YBqR79kOzsV:-Ndqn9W-1YBqR79kOzsW:br9ur79) ([raw file](https://github.com/sillsdev/web-xforge/blob/1af4f91266f5fa74aab1eb0e6ef56972e44ad9fa/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L262)):*
> ```XML
> 
>   private getStartingLocation(): void {
>     if (this.data.currentBook !== undefined && this.data.currentChapter !== undefined) {
> ```

Nit: We typically use != null, and in this case we probably don't want to set the book and chapter to null if that was the value we had.



_Code quote:_
```XML
    if (this.data.currentBook !== undefined && this.data.currentChapter !== undefined) {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 268 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2051#-NdqmynI5ftC9ndYhM_x:-NdqmynI5ftC9ndYhM_y:b-4o65cd) ([raw file](https://github.com/sillsdev/web-xforge/blob/1af4f91266f5fa74aab1eb0e6ef56972e44ad9fa/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L268)):*
> ```XML
>     }
> 
>     const publishedQuestions = this.data.questionsSorted.filter(q => !q.data?.isArchived);
> ```

Add a type here and below.



_Code quote:_
```XML
const publishedQuestions = 
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 273 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2051#-NdqnSJLDcD2WRXOjmhT:-NdqnSJLDcD2WRXOjmhU:b-1dpvpq) ([raw file](https://github.com/sillsdev/web-xforge/blob/1af4f91266f5fa74aab1eb0e6ef56972e44ad9fa/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L273)):*
> ```XML
>       const chapterNum = question.data?.verseRef.chapterNum;
> 
>       if (bookNum === undefined || chapterNum === undefined) continue;
> ```

Nit: Use == null here.



_Code quote:_
```XML
      if (bookNum === undefined || chapterNum === undefined) continue;
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 301 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2051#-NdqpvyjDWmveWRyWmxb:-NdqpvyjDWmveWRyWmxc:b-zhj01p) ([raw file](https://github.com/sillsdev/web-xforge/blob/1af4f91266f5fa74aab1eb0e6ef56972e44ad9fa/src/SIL.XForge.Scripture/ClientApp/src/app/check [...]

2023-09-13 03:44 UTC, nigel-wells reviewed
I had considered forcing one upload at a time but figured it would be nicer for the user if they could do 2 (or more in the future). I don't think an error would be nice - perhaps a disclaimer below the browse button that only one will be used? It will be pretty obvious to the user that only one is used and the other ignored.

It would be relatively simple later on to remove the requirement for timing data. If we don't have any timing data then we'll likely need to change that assumption in a number of other places as well.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2051#-:-NeBQ3Az5VSbMd7c5mJx:b-vddigi)* status: 2 of 8 files reviewed, 12 unresolved discussions (waiting on @josephmyers and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html` line 30 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2051#-NdqjPzW3K73WfdfAMp8:-NeBSiCX09RNrjdYYBqA:bs6z13l) ([raw file](https://github.com/sillsdev/web-xforge/blob/1af4f91266f5fa74aab1eb0e6ef56972e44ad9fa/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html#L30)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Do we need an ng-container here?
</blockquote></details>

Something needs to wrap all the elements otherwise the if statement needs to be added to every element which would be a bit repetitive. No div is output from this so he DOM is still clean.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html` line 49 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2051#-Ndqa_-J4PK1g1wtel3L:-NeBKDIx4VTlowJGSrZ9:brnac3n) ([raw file](https://github.com/sillsdev/web-xforge/blob/1af4f91266f5fa74aab1eb0e6ef56972e44ad9fa/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html#L49)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This doesn't look right, there are two spans with the same content.
</blockquote></details>

Gosh - that made total sense at the time.... I've removed now.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html` line 54 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2051#-NdqahDS0sUG_qPyK-dX:-NeBLHLr06WE5yQ7kDci:bwaw3tp) ([raw file](https://github.com/sillsdev/web-xforge/blob/1af4f91266f5fa74aab1eb0e6ef56972e44ad9fa/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html#L54)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Are we forcing users to upload a timing file as well as a audio?
</blockquote></details>

That was how it was working before. The chapter audio won't work that well without any timing data. We can create a separate Jira card if this needs to change.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 69 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2051#-NdqlCkF6qtX4WoG9COc:-NeBLmP35bf5pK4e3-lH:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/1af4f91266f5fa74aab1eb0e6ef56972e44ad9fa/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L69)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This could be `return this.audio?.fileName ?? ''` since the right-hand option should only be taken if the fileName is null or underfined.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 268 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2051#-NdqmynI5ftC9ndYhM_x:-NeBMOm73rU2tLDXdAnh:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/1af4f91266f5fa74aab1eb0e6ef56972e44ad9fa/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L268)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Add a type here and below.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 301 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2051#-NdqpvyjDWmveWRyWmxb:-NeBaL-_1aD-BhJ5ZGnQ:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/1af4f91266f5fa74aab1eb0e6ef56972e44ad9fa/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L301)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Can you leave a method comment here to describe why we need to populate the to field
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 319 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2051#-NdqoMejCmbX7fL1bXxk:-NeBantn8pPYlz0KnyYc:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/1af4f91266f5fa74aab1eb0e6ef56972e44ad9fa/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L319)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This regex might be a good one to move to the top of the file.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 347 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2051#-Ndqofdb5WtnvfnXWIV0:-NeBMilp2RL44bf8SAmm:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/1af4f91266f5fa74aab1eb0e6ef56972e44ad9fa/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L347)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Add the type here and below.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 352 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2051#-NdqoveM9GD5eazzD7f8:-NeBP9AO6Y9qXTWfQvx8:bjg422p) ([raw file](https://github.com/sillsdev/web-xforge/blob/1af4f91266f5fa74aab1eb0e6ef56972e44ad9fa/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L352)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Could you leave a comment here to describe what validated means?
</blockquote></details>

I've added in the current translations that Joseph proposed for these blocks
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json` line 205 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2051#-Ndqr4ZJ1GpZklNTViP0:-NeBQ-GFDC68tmFrqbBg:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/1af4f91266f5fa74aab1eb0e6ef56972e44ad9fa/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json#L205)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This should probably be chapter_audio_dialog since that is the name of the component that uses these keys.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json` line 212 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2051#-NdqZDyi64kh34UUJ1IA:-NeBMo6t2I7uFpQ5n3a3:by5s4ia) ([raw file](https://github.com/sillsdev/web-xforge/blob/1af4f91266f5fa74aab1eb0e6ef56972e44ad9fa/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json#L212)):*
<details><summary><i>Previously, [...]

2023-09-13 17:09 UTC, RaymondLuong3 approved these changes
It was a minor observation. I imagine that users will likely only try to upload one audio and timing file. But if we find that users deviate from that workflow, we can always come back to make it more restrictive (that is probably the uncommon case).

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2051#-:-NeEUw125d2UQuOhHOjX:b-a1ftjy)* status: all files reviewed, 1 unresolved discussion (waiting on @josephmyers and @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html` line 30 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2051#-NdqjPzW3K73WfdfAMp8:-NeESYwcEntDFr7sIRV0:bdqxln9) ([raw file](https://github.com/sillsdev/web-xforge/blob/1af4f91266f5fa74aab1eb0e6ef56972e44ad9fa/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html#L30)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Something needs to wrap all the elements otherwise the if statement needs to be added to every element which would be a bit repetitive. No div is output from this so he DOM is still clean.
</blockquote></details>

Oh yes, I see that now. I'm not sure what I was thinking.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html` line 54 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2051#-NdqahDS0sUG_qPyK-dX:-NeEVW76DXZDlW4CcPlk:bgr44z9) ([raw file](https://github.com/sillsdev/web-xforge/blob/1af4f91266f5fa74aab1eb0e6ef56972e44ad9fa/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html#L54)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

That was how it was working before. The chapter audio won't work that well without any timing data. We can create a separate Jira card if this needs to change.
</blockquote></details>

Let's keep this as-is, I think the experience with chapter audio is so much better with timing files. If we find that users don't have timing files, we can change it then.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json` line 212 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2051#-NdqZDyi64kh34UUJ1IA:-NeETJhE7GL2N_E-8Suz:b-ab4o2f) ([raw file](https://github.com/sillsdev/web-xforge/blob/1af4f91266f5fa74aab1eb0e6ef56972e44ad9fa/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json#L212)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

I considered that but I wasn't sure that would be enough context to the translators?
</blockquote></details>

These keys are available for the Translators to see, but I'm not sure how often they are used to help translators. But if the extra context helps, let's keep it.


<!-- Sent from Reviewable.io -->

2023-09-18 16:41 UTC, RaymondLuong3 requested changes
Looks like the testers did some good testing. A few suggestions, then we can merge this.

> Reviewed 1 of 2 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2051#-:-Ned9bcBB6XPFxbJGYWd:b-hfgusc)* status: all files reviewed, 5 unresolved discussions (waiting on @josephmyers and @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 162 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2051#-Ned78v1-uKM_yjgaqO-:-Ned78v1-uKM_yjgaqO0:b-9nimi2) ([raw file](https://github.com/sillsdev/web-xforge/blob/4c56cc97cb7f924226c68985a20d68c00a69c557/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L162)):*
> ```XML
>   deleteAudioData(): void {
>     this.audio = undefined;
>     this.fileDropzone!.nativeElement.value = '';
> ```

This must be because after the previously uploaded file is deleted, it still exists as part of the uploaded files. If that is the case, there was some good testing done!



_Code quote:_
```XML
    this.fileDropzone!.nativeElement.value = '';
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts` line 232 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2051#-Ned9ZEJ5Bpq8708U2yR:-Ned9ZEJ5Bpq8708U2yS:b-2o9ok4) ([raw file](https://github.com/sillsdev/web-xforge/blob/4c56cc97cb7f924226c68985a20d68c00a69c557/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts#L232)):*
> ```XML
>     }
>     const project = this.projectDoc?.data;
>     const userId = this.userService.currentUserId;
> ```

Nit: define types here.



_Code quote:_
```XML
    const project = this.projectDoc?.data;
    const userId = this.userService.currentUserId;
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts` line 163 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2051#-Ned8Suk4FC-vCEM8WwA:-Ned8Suk4FC-vCEM8WwB:b-qjnekz) ([raw file](https://github.com/sillsdev/web-xforge/blob/4c56cc97cb7f924226c68985a20d68c00a69c557/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts#L163)):*
> ```XML
>     if (!this.featureFlags.scriptureAudio.enabled) {
>       return false;
>     }
> ```

We should add a test for when a user does not have permission to create audio.



_Code quote:_
```XML
  get canCreateScriptureAudio(): boolean {
    if (!this.featureFlags.scriptureAudio.enabled) {
      return false;
    }
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts` line 165 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2051#-Ned9NxSANODZTNYXORs:-Ned9NxSANODZTNYXORt:bfm5kav) ([raw file](https://github.com/sillsdev/web-xforge/blob/4c56cc97cb7f924226c68985a20d68c00a69c557/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts#L165)):*
> ```XML
>     }
>     const project = this.projectDoc?.data;
>     const userId = this.userService.currentUserId;
> ```

Nit: A few of these getters could have types defined in their bodies.



_Code quote:_
```XML
    const project = this.projectDoc?.data;
    const userId = this.userService.currentUserId;
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts` line 170 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2051#-Ned9C0xB74OEHmcMLgx:-Ned9C0xB74OEHmcMLgy:bp5k2xi) ([raw file](https://github.com/sillsdev/web-xforge/blob/4c56cc97cb7f924226c68985a20d68c00a69c557/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts#L170)):*
> ```XML
> 
>   get canDeleteScriptureAudio(): boolean {
>     if (!this.featureFlags.scriptureAudio.enabled) {
> ```

We should add a test for when a user should not be able to delete the chapter audio.



_Code quote:_
```XML
  get canDeleteScriptureAudio(): boolean {
    if (!this.featureFlags.scriptureAudio.enabled) {
```


<!-- Sent from Reviewable.io -->

2023-09-19 03:24 UTC, nigel-wells reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2051)* status: all files reviewed, 3 unresolved discussions (waiting on @josephmyers and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts` line 162 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2051#-Ned78v1-uKM_yjgaqO-:-NefQnevDYwqNtTWUuJE:br36njo) ([raw file](https://github.com/sillsdev/web-xforge/blob/4c56cc97cb7f924226c68985a20d68c00a69c557/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.ts#L162)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This must be because after the previously uploaded file is deleted, it still exists as part of the uploaded files. If that is the case, there was some good testing done!
</blockquote></details>

Exactly - and it leaves a tooltip state what the selected file was. Settings the value to an empty string removes that tooltip which is something the testers raised.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts` line 232 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2051#-Ned9ZEJ5Bpq8708U2yR:-NefRO_L9L9qrt_Bsw82:bb6un1j) ([raw file](https://github.com/sillsdev/web-xforge/blob/4c56cc97cb7f924226c68985a20d68c00a69c557/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts#L232)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Nit: define types here.
</blockquote></details>

Done
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts` line 163 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2051#-Ned8Suk4FC-vCEM8WwA:-NefRRPCCJ3NDcHQAz33:bwxoao0) ([raw file](https://github.com/sillsdev/web-xforge/blob/4c56cc97cb7f924226c68985a20d68c00a69c557/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts#L163)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

We should add a test for when a user does not have permission to create audio.
</blockquote></details>

As mentioned in Slack, Joseph will be creating relevant tests.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts` line 165 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2051#-Ned9NxSANODZTNYXORs:-NefRz3z8LNAkooehhzj:bb6un1j) ([raw file](https://github.com/sillsdev/web-xforge/blob/4c56cc97cb7f924226c68985a20d68c00a69c557/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts#L165)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Nit: A few of these getters could have types defined in their bodies.
</blockquote></details>

Done
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts` line 170 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2051#-Ned9C0xB74OEHmcMLgx:-NefRVSc2IH5XN-z6BHg:bwxoao0) ([raw file](https://github.com/sillsdev/web-xforge/blob/4c56cc97cb7f924226c68985a20d68c00a69c557/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking-overview/checking-overview.component.ts#L170)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

We should add a test for when a user should not be able to delete the chapter audio.
</blockquote></details>

As mentioned in Slack, Joseph will be creating relevant tests.


<!-- Sent from Reviewable.io -->

2023-09-19 14:48 UTC, RaymondLuong3 approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2051)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @josephmyers)



<!-- Sent from Reviewable.io -->

2023-09-19 15:42 UTC, merged