SF-2255 Show biblical terms in default locale when blank
sillsdev/web-xforge pull request #2084
Opened 2023-09-25 03:22 UTC by pmachapman

When changing to a language that does not have a gloss translated for a Biblical Term (i.e. ἅγιος-1 in Romans 1:2 in Spanish), a blank definition is shown. Instead, it should show the definition in the default language (English).

This PR provides fallbacks for blank Biblical Term translations for glosses, categories, and notes where they are blank in the translation file. This occurs most often for Spanish, as the Spanish XML file only has some translations where French is more complete.

2023-09-25 06:41 UTC, josephmyers requested changes
I am seeing Gloss work and Notes work, but Category is still showing up blank for me. I made the following change, and I'm wondering if this is the use case we're going for:
![image.png](https://files.reviewableusercontent.io/images/reviewable/43733878/c9QMQZFMhZp0UeYBn9w3GPVw/image.png)

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2084#-:-NfA2NWr95bdyswqE5Gq:bk4nwg)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)



<!-- Sent from Reviewable.io -->

2023-09-25 18:49 UTC, pmachapman reviewed
@josephmyers This isn't the sort of use case this PR is designed to address - you have modified the master XML list (which should always have the term), not the localization.

This PR is for when the localization file (i.e. `BiblicalTermsEs.xml`) has only a partial localization for a Biblical Term. Some (but not all) of the terms include:

 * Español: ἅγιος-1 (Romans 1:2)
 * Español: δόξα-3 (Romans 1:23)
 * Español: 1-חַיָּה (Genesis 1:24)
 * Français: πατήρ (2 Corinthians 1:2)

*Note: These are common words and will occur elsewhere - I just chose places they occur in my test translation.*

You should be able to find more by checking out master, navigating from chapter to chapter, and looking for Biblical Terms that have gaps under the gloss column:

![image.png](https://files.reviewableusercontent.io/images/reviewable/8665431/U4BmlsoIevyTMfAny2Vltlju/image.png)

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2084#-:-NfC_tN-716BKqZ4emJ5:b-p2snmg)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)



<!-- Sent from Reviewable.io -->

2023-09-26 01:54 UTC, josephmyers commented
Ok, that makes sense. So you added code for blank categories, and I'm wondering how to test that!

2023-09-26 02:53 UTC, pmachapman reviewed
It is a pretty obscure occurrence to have a blank category - I added it for completeness more than anything.

To test a missing category localization:

1. Open: `src\SIL.XForge.Scripture\Terms\Lists\BiblicalTermsEs.xml`
2. Change the line: `<Localization Id\="FA" Gloss\="Animales" />`
3. To: `<Localization Id\="FA" Gloss\="" />`
4. Rebuild the .NET application
5. Synchronize your project
6. Change the language to Español
7. Look at a Fauna term, like "רֶמֶשׂ" in Genesis 1:24

This is not a likely scenario...possible but not really likely to happen.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2084#-:-NfEKeN--I0mFJbIfsgE:b-2jbj99)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)



<!-- Sent from Reviewable.io -->

2023-09-27 17:10 UTC, merged