Add Forward Translation Drafting feature flag
sillsdev/web-xforge pull request #2087
Opened 2023-09-25 23:18 UTC by pmachapman

This PR adds a feature flag that overrides the checks in back translation drafting for:

 * Whether the translation is a back translation
 * Whether the language is in the NLLB

This means that when this feature flag is enabled, testing of forward translation drafting can be done using Serval.

2023-09-26 06:56 UTC, Nateowami reviewed
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2087)* status: all files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 98 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2087#-NfFEr8T2I60F9N_r9PI:-NfFEr8T2I60F9N_r9PJ:bjqhnun) ([raw file](https://github.com/sillsdev/web-xforge/blob/5d6390823d4ecf869b8ddf3a8f43b619dfc11bf7/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L98)):*
> ```XML
>       this.isTargetLanguageSupported = this.nllbService.isNllbLanguage(this.targetLanguage);
>       this.isSourceAndTargetDifferent = translateConfig?.source?.writingSystem.tag !== this.targetLanguage;
>       this.isForwardTranslationEnabled = this.featureFlags.allowForwardTranslationNmtDrafting.enabled;
> ```

Setting this at the time the component is initialized means it won't dynamically update when the feature flag is turned on.

This might seem like an edge case, but the most likely workflow is that someone is going to come to this component, see they're blocked, and then turn the flag on.

If this is made a getter instead of a regular property, we can easily make it dynamic.

Otherwise we're just kind of throwing away all the advantages we get from Angular change detection.

(I'm away, and this is intentionally non-blocking. I can't necessarily follow up on this review)


<!-- Sent from Reviewable.io -->

2023-09-26 07:06 UTC, Nateowami commented
I should add that besides the one item mentioned, this looks very good, and I've tested and see that it works great.

2023-09-26 20:11 UTC, pmachapman reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2087)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 98 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2087#-NfFEr8T2I60F9N_r9PI:-NfI6K5SAy_c2eh1tT9l:b-7jy9rl) ([raw file](https://github.com/sillsdev/web-xforge/blob/5d6390823d4ecf869b8ddf3a8f43b619dfc11bf7/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L98)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Setting this at the time the component is initialized means it won't dynamically update when the feature flag is turned on.

This might seem like an edge case, but the most likely workflow is that someone is going to come to this component, see they're blocked, and then turn the flag on.

If this is made a getter instead of a regular property, we can easily make it dynamic.

Otherwise we're just kind of throwing away all the advantages we get from Angular change detection.

(I'm away, and this is intentionally non-blocking. I can't necessarily follow up on this review)
</blockquote></details>

Done - good idea it bugged me too when I tried to turn the feature flag on while viewing the drafting page.


<!-- Sent from Reviewable.io -->

2023-09-26 21:02 UTC, RaymondLuong3 requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2087)* status: all files reviewed, 2 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 29 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2087#-NfIH-SmE4k1ySkCDhqT:-NfIH-SmE4k1ySkCDhqU:b-8ki2df) ([raw file](https://github.com/sillsdev/web-xforge/blob/eb5c21a3af823b819598f35be5367731f43ac55e/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L29)):*
> ```HTML
>         <mat-icon *ngIf="isBackTranslation" class="criteria-met">check</mat-icon>
>         <mat-icon *ngIf="!isBackTranslation" class="criteria-not-met">clear</mat-icon>
>         <p>Your project type is <span *ngIf="!isBackTranslation">not</span> a back translation project.</p>
> ```

You could probably hide this check if the forward translation feature flag is enabled. Or hide it in the case when the project is not a back translation project. It is confusing to see an X on the requirement, but you can still proceed.



_Code quote:_
```HTML
        <mat-icon *ngIf="isBackTranslation" class="criteria-met">check</mat-icon>
        <mat-icon *ngIf="!isBackTranslation" class="criteria-not-met">clear</mat-icon>
        <p>Your project type is <span *ngIf="!isBackTranslation">not</span> a back translation project.</p>
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 33 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2087#-NfIHfB56zcMirQN4WkQ:-NfIHfB56zcMirQN4WkR:bmg19fp) ([raw file](https://github.com/sillsdev/web-xforge/blob/eb5c21a3af823b819598f35be5367731f43ac55e/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L33)):*
> ```HTML
>       <li>
>         <mat-icon *ngIf="isTargetLanguageSupported" class="criteria-met">check</mat-icon>
>         <mat-icon *ngIf="!isTargetLanguageSupported" class="criteria-not-met">clear</mat-icon>
> ```

Does it matter if the language is part of the NLLB for forward translations? We might show an X here if it is a forward translation, and still be able to proceed. So it would be best to hide this check if the forward translation drafting is enabled.



_Code quote:_
```HTML
        <mat-icon *ngIf="isTargetLanguageSupported" class="criteria-met">check</mat-icon>
        <mat-icon *ngIf="!isTargetLanguageSupported" class="criteria-not-met">clear</mat-icon>
```


<!-- Sent from Reviewable.io -->

2023-09-27 01:30 UTC, pmachapman reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2087)* status: all files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 29 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2087#-NfIH-SmE4k1ySkCDhqT:-NfJCj6RD4BAr7kDZ6Mj:b-kvf2g3) ([raw file](https://github.com/sillsdev/web-xforge/blob/eb5c21a3af823b819598f35be5367731f43ac55e/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L29)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

You could probably hide this check if the forward translation feature flag is enabled. Or hide it in the case when the project is not a back translation project. It is confusing to see an X on the requirement, but you can still proceed.
</blockquote></details>

I think hiding it when it is not a back translation project when forward translation drafting is enabled is the best option. If a project is a back translation and forward translation drafting is enabled, it will still show as ticked.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 33 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2087#-NfIHfB56zcMirQN4WkQ:-NfJCZgj4d1StyJ8jb8Q:bl6dvf3) ([raw file](https://github.com/sillsdev/web-xforge/blob/eb5c21a3af823b819598f35be5367731f43ac55e/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L33)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Does it matter if the language is part of the NLLB for forward translations? We might show an X here if it is a forward translation, and still be able to proceed. So it would be best to hide this check if the forward translation drafting is enabled.
</blockquote></details>

It is not supposed to matter for forward translations. Quality will be better if the translation is in the NLLB set though.

I have changed it to act like the back translation check mark (above): If forward translation is enabled it is hidden if not in the NLLB, shows if it is in the NLLB.


<!-- Sent from Reviewable.io -->

2023-09-27 14:47 UTC, RaymondLuong3 approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2087)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)



<!-- Sent from Reviewable.io -->

2023-09-27 15:04 UTC, merged