SF-2258 Fix uploading of Biblical Terms to Serval
sillsdev/web-xforge pull request #2091
Opened 2023-09-27 01:37 UTC by pmachapman

This Pull Request fixes the upload of Biblical Terms to Serval based on feedback from the Serval team. In particular it:

 * Cleans renderings to not contain Paratext specific syntax
 * Loads Biblical Terms from MongoDB with fallback to the XML file if the terms are not yet populated in the database

2023-09-28 21:08 UTC, RaymondLuong3 requested changes
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2091)* status: all files reviewed, 5 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/Services/SFBiblicalTermsText.cs` line 14 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2091#-NfSY_MDDfFOKt9dBexq:-NfSY_MDDfFOKt9dBexr:b-79zbe1) ([raw file](https://github.com/sillsdev/web-xforge/blob/976632fe4ab46193a8d6e44b7e2be13c2892d0bf/src/SIL.XForge.Scripture/Services/SFBiblicalTermsText.cs#L14)):*
> ```Smalltalk
> public class SFBiblicalTermsText : IText
> {
>     private static readonly Regex BracketedTextRegex = new Regex(@"\([^)]*\)", RegexOptions.Compiled);
> ```

In the situation where there is text like "(first) and (second)" I assume that we want to keep " and ". Does this ensure that the match is not greedy? Actually, I see now it will work since it can only match what is inside the bracket. Nice.



_Code quote:_
```Smalltalk
    private static readonly Regex BracketedTextRegex = new Regex(@"\([^)]*\)", RegexOptions.Compiled);
```
___
*[`src/SIL.XForge.Scripture/Services/SFBiblicalTermsText.cs` line 46 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2091#-NfSbhQL1DYh41Sih_Ld:-NfSbhQMCClD9zK6c2vM:b-zhk4ri) ([raw file](https://github.com/sillsdev/web-xforge/blob/976632fe4ab46193a8d6e44b7e2be13c2892d0bf/src/SIL.XForge.Scripture/Services/SFBiblicalTermsText.cs#L46)):*
> ```Smalltalk
>     public IEnumerable<TextSegment> GetSegments(bool includeText = true, IText? basedOn = null) => _segments;
> 
>     private static string RemoveParatextSyntaxFromRendering(string rendering)
> ```

This could use a method comment for its use.



_Code quote:_
```Smalltalk
    private static string RemoveParatextSyntaxFromRendering(string rendering)
```
___
*[`src/SIL.XForge.Scripture/Services/SFBiblicalTermsText.cs` line 67 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2091#-NfSZbrT3-tmm3TQ8bYG:-NfSZbrU9qOG4uyTOcfj:bl5wvgp) ([raw file](https://github.com/sillsdev/web-xforge/blob/976632fe4ab46193a8d6e44b7e2be13c2892d0bf/src/SIL.XForge.Scripture/Services/SFBiblicalTermsText.cs#L67)):*
> ```Smalltalk
>         foreach (BiblicalTerm biblicalTerm in biblicalTerms.OrderBy(t => t.TermId))
>         {
>             foreach (string rendering in biblicalTerm.Renderings.Select(RemoveParatextSyntaxFromRendering))
> ```

I did not know you could .Select() and pass in a function. That is neat.



_Code quote:_
```Smalltalk
  foreach (string rendering in biblicalTerm.Renderings.Select(RemoveParatextSyntaxFromRendering))
```
___
*[`test/SIL.XForge.Scripture.Tests/Services/SFBiblicalTermsTextTests.cs` line 105 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2091#-NfS_WOjDcy3JcZv_V6W:-NfS_WOjDcy3JcZv_V6X:bs8iuso) ([raw file](https://github.com/sillsdev/web-xforge/blob/976632fe4ab46193a8d6e44b7e2be13c2892d0bf/test/SIL.XForge.Scripture.Tests/Services/SFBiblicalTermsTextTests.cs#L105)):*
> ```Smalltalk
>         TextSegment[] segments = text.GetSegments().ToArray();
>         Assert.That(segments.Length, Is.EqualTo(3));
>         Assert.That(string.Join(" ", segments[0].Segment), Is.EqualTo("Term1"));
> ```

I'm confused why you need to call string.join() but the result is a string with no whitespace? Is it because the segment is tokenized? Maybe add a comment if there is a reason for this.



_Code quote:_
```Smalltalk
        Assert.That(string.Join(" ", segments[0].Segment), Is.EqualTo("Term1"));
```


<!-- Sent from Reviewable.io -->

2023-10-01 17:19 UTC, pmachapman reviewed
> Dismissed @github-code-scanning[bot] from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2091)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/Services/SFBiblicalTermsText.cs` line 46 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2091#-NfSbhQL1DYh41Sih_Ld:-Nfg9TcK0lsqMVsB6BM3:b-ydonir) ([raw file](https://github.com/sillsdev/web-xforge/blob/976632fe4ab46193a8d6e44b7e2be13c2892d0bf/src/SIL.XForge.Scripture/Services/SFBiblicalTermsText.cs#L46)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This could use a method comment for its use.
</blockquote></details>

Done. Good idea.
___
*[`test/SIL.XForge.Scripture.Tests/Services/SFBiblicalTermsTextTests.cs` line 105 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2091#-NfS_WOjDcy3JcZv_V6W:-NfgBGWoCyVUyY0jk99J:bcbb6sk) ([raw file](https://github.com/sillsdev/web-xforge/blob/976632fe4ab46193a8d6e44b7e2be13c2892d0bf/test/SIL.XForge.Scripture.Tests/Services/SFBiblicalTermsTextTests.cs#L105)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I'm confused why you need to call string.join() but the result is a string with no whitespace? Is it because the segment is tokenized? Maybe add a comment if there is a reason for this.
</blockquote></details>

It was copy pasta from previous unit tests. I have rewritten these to check the array dimensions as I think that will be clearer.


<!-- Sent from Reviewable.io -->

2023-10-02 17:45 UTC, RaymondLuong3 requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2091)* status: all files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`test/SIL.XForge.Scripture.Tests/Services/SFBiblicalTermsTextTests.cs` line 169 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2091#-NflU_zk1Doa_jRmFk2N:-NflU_zk1Doa_jRmFk2O:b-39vih8) ([raw file](https://github.com/sillsdev/web-xforge/blob/e99170deb8cd3c73c7677e87066b68aeee8dbfcb/test/SIL.XForge.Scripture.Tests/Services/SFBiblicalTermsTextTests.cs#L169)):*
> ```Smalltalk
>             Assert.That(segments[i].SegmentRef.ToString(), Is.EqualTo("Term" + (i + 1).ToString("D2")));
>             Assert.That(segments[i].Segment.Count, Is.EqualTo(renderings[i].expectedCount));
>             Assert.That(string.Join(" ", segments[i].Segment), Is.EqualTo(renderings[i].expected));
> ```

Looks like you missed one.



_Code quote:_
```Smalltalk
         Assert.That(string.Join(" ", segments[i].Segment), Is.EqualTo(renderings[i].expected));
```


<!-- Sent from Reviewable.io -->

2023-10-02 18:31 UTC, pmachapman reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2091)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`test/SIL.XForge.Scripture.Tests/Services/SFBiblicalTermsTextTests.cs` line 169 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2091#-NflU_zk1Doa_jRmFk2N:-Nfle1mz0z1HPA-2DP2b:b-qqkzo0) ([raw file](https://github.com/sillsdev/web-xforge/blob/e99170deb8cd3c73c7677e87066b68aeee8dbfcb/test/SIL.XForge.Scripture.Tests/Services/SFBiblicalTermsTextTests.cs#L169)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Looks like you missed one.
</blockquote></details>

Done. I have updated the test to use an array for the expected data.


<!-- Sent from Reviewable.io -->

2023-10-02 19:22 UTC, RaymondLuong3 approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2091)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)



<!-- Sent from Reviewable.io -->

2023-10-09 18:51 UTC, merged