SF-2230 Display draft preview button while build running
sillsdev/web-xforge pull request #2112
Opened 2023-10-08 23:08 UTC by siltomato

Show button to preview draft while a build job is running if a previous draft exists.  Now UI should conform to flow chart:
![Pre-Translation Drafting UI States](https://github.com/sillsdev/web-xforge/assets/133386342/cd3bc7bf-ddf3-402b-b273-5d082f492789)

2023-10-09 23:59 UTC, pmachapman requested changes
Just some minor comments RE: the UX and a nit

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2112#-:-NgLixZ32Dhz-v_5Wsl8:b2o4000)* status: all files reviewed, 3 unresolved discussions (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 118 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2112#-NgLmP2LDRzdOj1yfoRg:-NgLmP2LDRzdOj1yfoRh:binij7r) ([raw file](https://github.com/sillsdev/web-xforge/blob/ca09d6567553468b807ade23f33f0c8842af1b29/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L118)):*
> ```HTML
> 
>         <button mat-flat-button color="primary" (click)="generateDraft()">
>           <mat-icon class="material-icons-outlined">padding</mat-icon>
> ```

I am not sure what this icon is trying to portray? Perhaps something that shows more the processing/generating/working metaphor? Something like `model_training`?

I realize your struggle to find a good icon, however!



_Code quote:_
```HTML
<mat-icon class="material-icons-outlined">padding</mat-icon>
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 201 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2112#-NgLrH6_9ShshV4xzJRT:-NgLrH6_9ShshV4xzJRU:bi4slwx) ([raw file](https://github.com/sillsdev/web-xforge/blob/ca09d6567553468b807ade23f33f0c8842af1b29/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L201)):*
> ```HTML
>               Preview last draft
>             </a>
>           </div>
> ```

These buttons feel too close together for me.

Does it work if we put them on the same line as the moving cogs? Having preview below the cogs makes it feel like the preview action is associated with the "processing" of the cogs, when it is not. i.e.

![image.png](https://files.reviewableusercontent.io/images/reviewable/8665431/lebSxgzVO9CMSEqSVbMRxHt3/image.png)

I am not much of a UX expert however, so if you think I am wrong, no problems! :-)



_Code quote:_
```HTML
          <div class="button-strip">
            <button *ngIf="canCancel(draftJob)" mat-flat-button color="primary" (click)="cancel()">
              <mat-icon>highlight_off</mat-icon>
              Cancel generation
            </button>
            <a *ngIf="hasAnyCompletedBuild" mat-flat-button color="primary" [routerLink]="draftViewerUrl">
              <mat-icon>manage_search</mat-icon>
              Preview last draft
            </a>
          </div>
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 64 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2112#-NgLl8Jl3ZnSC69zgSU5:-NgLl8Jl3ZnSC69zgSU6:bpx25jh) ([raw file](https://github.com/sillsdev/web-xforge/blob/ca09d6567553468b807ade23f33f0c8842af1b29/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L64)):*
> ```XML
>    * from that build can still be retrieved.
>    */
>   hasAnyCompletedBuild!: boolean;
> ```

Nit: Would it be better to just assign an initial value to this? i.e. `hasAnyCompletedBuild = false;`



_Code quote:_
```XML
hasAnyCompletedBuild!: boolean;
```


<!-- Sent from Reviewable.io -->

2023-10-10 17:21 UTC, siltomato reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2112)* status: all files reviewed, 2 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 118 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2112#-NgLmP2LDRzdOj1yfoRg:-NgPOZDq9vCavdlhZelE:bbeptth) ([raw file](https://github.com/sillsdev/web-xforge/blob/ca09d6567553468b807ade23f33f0c8842af1b29/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L118)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

I am not sure what this icon is trying to portray? Perhaps something that shows more the processing/generating/working metaphor? Something like `model_training`?

I realize your struggle to find a good icon, however!
</blockquote></details>

Ooh, yeah.  I like that one.  Good find!

Also, I noticed that I used different icons for the preview button here and in the editor component.  In the editor, I used `edit_note`, whereas here I used `manage_search`.  Which one do you think is better?
![image.png](https://files.reviewableusercontent.io/images/reviewable/133386342/8dgCYdJdqPFbI0MRczTETM16/image.png)
![image copy 1.png](https://files.reviewableusercontent.io/images/reviewable/133386342/Avk2mJokoUH-enpsC2WlYW4a/image.png)
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 201 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2112#-NgLrH6_9ShshV4xzJRT:-NgPZCPn2PRToj9wwYgf:bu63fm3) ([raw file](https://github.com/sillsdev/web-xforge/blob/ca09d6567553468b807ade23f33f0c8842af1b29/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L201)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

These buttons feel too close together for me.

Does it work if we put them on the same line as the moving cogs? Having preview below the cogs makes it feel like the preview action is associated with the "processing" of the cogs, when it is not. i.e.

![image.png](https://files.reviewableusercontent.io/images/reviewable/8665431/lebSxgzVO9CMSEqSVbMRxHt3/image.png)

I am not much of a UX expert however, so if you think I am wrong, no problems! :-)
</blockquote></details>

I'm not a UX expert either, but I've come to understand that when something feels wrong to fresh eyes, it usually is.

I made some tweaks to space the buttons more, reduce the space between the indicator and the buttons, and try to center the cogs over the cancel button.  How does this look to you?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 64 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2112#-NgLl8Jl3ZnSC69zgSU5:-NgPP7taBvHc-2oXwZOj:bd69lc2) ([raw file](https://github.com/sillsdev/web-xforge/blob/ca09d6567553468b807ade23f33f0c8842af1b29/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L64)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Nit: Would it be better to just assign an initial value to this? i.e. `hasAnyCompletedBuild = false;`
</blockquote></details>

Much better, thanks.

Also, this brings up a question for me.  When is it okay to skip explicitly setting a type?  When assigning to a primitive, I tend to prefer the terser syntax of skipping the type assignment.  Is there a guideline we are following on this?


<!-- Sent from Reviewable.io -->

2023-10-10 19:46 UTC, pmachapman requested changes
Looks good - only need to unify the preview draft icons and we are done!

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2112#-:-NgQ6ZgW9Ou-DxOdQmry:bryxoyl)* status: all files reviewed, 2 unresolved discussions (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 118 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2112#-NgLmP2LDRzdOj1yfoRg:-NgQ4nTl6XG1K5oNsDMr:b-z0f8dn) ([raw file](https://github.com/sillsdev/web-xforge/blob/ca09d6567553468b807ade23f33f0c8842af1b29/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L118)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Ooh, yeah.  I like that one.  Good find!

Also, I noticed that I used different icons for the preview button here and in the editor component.  In the editor, I used `edit_note`, whereas here I used `manage_search`.  Which one do you think is better?
![image.png](https://files.reviewableusercontent.io/images/reviewable/133386342/8dgCYdJdqPFbI0MRczTETM16/image.png)
![image copy 1.png](https://files.reviewableusercontent.io/images/reviewable/133386342/Avk2mJokoUH-enpsC2WlYW4a/image.png)
</blockquote></details>

I think `edit_note` is a lot clearer, especially since you do more than view on the preview draft page.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 201 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2112#-NgLrH6_9ShshV4xzJRT:-NgQ57Jo-u6dj-AurUN4:b-us4fcj) ([raw file](https://github.com/sillsdev/web-xforge/blob/ca09d6567553468b807ade23f33f0c8842af1b29/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L201)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

I'm not a UX expert either, but I've come to understand that when something feels wrong to fresh eyes, it usually is.

I made some tweaks to space the buttons more, reduce the space between the indicator and the buttons, and try to center the cogs over the cancel button.  How does this look to you?
</blockquote></details>

Yes, that is way better!
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts` line 64 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2112#-NgLl8Jl3ZnSC69zgSU5:-NgQ5EFm4vgBEtK8bQWe:b-dasjes) ([raw file](https://github.com/sillsdev/web-xforge/blob/ca09d6567553468b807ade23f33f0c8842af1b29/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.ts#L64)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Much better, thanks.

Also, this brings up a question for me.  When is it okay to skip explicitly setting a type?  When assigning to a primitive, I tend to prefer the terser syntax of skipping the type assignment.  Is there a guideline we are following on this?
</blockquote></details>

I think when the type is really clear in the declaration, you don't need to define it. I have been corrected in code reviews in the past for being overly definitive, i.e. `let isReady: boolean = true`.

I checked our [style guides](https://github.com/sillsdev/web-xforge/wiki/Style-guides) and couldn't find any specific rules on this, however.


<!-- Sent from Reviewable.io -->

2023-10-11 02:00 UTC, siltomato reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2112)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 118 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2112#-NgLmP2LDRzdOj1yfoRg:-NgRSdG55CKj9Ve52L_J:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/ca09d6567553468b807ade23f33f0c8842af1b29/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L118)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

I think `edit_note` is a lot clearer, especially since you do more than view on the preview draft page.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html` line 201 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2112#-NgLrH6_9ShshV4xzJRT:-NgRQu078l5oLlPxY0Lt:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/ca09d6567553468b807ade23f33f0c8842af1b29/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.html#L201)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Yes, that is way better!
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-11 04:08 UTC, pmachapman approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2112#-:-NgRux7e-xOI_6FEwBU6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @siltomato)



<!-- Sent from Reviewable.io -->

2023-10-12 13:24 UTC, merged