SF-2254 Hide Pre-Translation Draft UI When Offline
sillsdev/web-xforge pull request #2114
Opened 2023-10-09 01:21 UTC by pmachapman

When the user's Internet connection goes offline, the functionality to preview the pre-translation draft and apply the draft to the project remains visible.

This PR hides that functionality when the connection goes offline, as the pre-translation drafting functionality requires a live connection to Serval via SF's Machine API.

2023-10-09 13:36 UTC, siltomato requested changes
Looks good.  Just noted a possible scenario when the user comes online after loading the component (both draft-viewer and editor).

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2114#-:-NgJVMrk5gMlP2EaC6X4:bs3y2a)* status: all files reviewed, 3 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 73 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2114#-NgJahJ58wOE4bDfy0n8:-NgJahJ58wOE4bDfy0n9:b-hh6r9e) ([raw file](https://github.com/sillsdev/web-xforge/blob/01e0306bb6a29a16048c4901e1bfbb2c924d0e0b/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L73)):*
> ```XML
> 
>     // Wait to populate draft until both editors are loaded with current chapter
>     zip(this.sourceEditor?.loaded ?? of(null), this.targetEditor.loaded).subscribe(() => {
> ```

If the user is offline and then comes online after the editor loads, do we need to check for a draft in reaction to user coming online (if we haven't already checked)?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 78 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2114#-NgJZS3K9IHWJceUk342:-NgJZS3K9IHWJceUk343:b4t1ayc) ([raw file](https://github.com/sillsdev/web-xforge/blob/01e0306bb6a29a16048c4901e1bfbb2c924d0e0b/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L78)):*
> ```XML
>       this.isDraftApplied = false;
>       this.preDraftTargetDelta = this.targetEditor.editor?.getContents();
>       this.populateDraftText();
> ```

I noticed that if user is offline, it still makes a network request for the draft, causing the "network request failed" snackbar notice. Do you think we should prevent the draft request and display a notice something like, "Draft preview is not available while offline"?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 844 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2114#-NgJb_wgCurG2RdZuVgw:-NgJb_wgCurG2RdZuVgx:b-32jgf7) ([raw file](https://github.com/sillsdev/web-xforge/blob/01e0306bb6a29a16048c4901e1bfbb2c924d0e0b/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L844)):*
> ```XML
> 
>           if (this.featureFlags.showNmtDrafting.enabled) {
>             this.checkForPreTranslations();
> ```

Like in the draft viewer component, if the user is offline and then comes online after the editor loads, do we need to check for a draft in reaction to user coming online (if we haven't already checked)?

Also, should we prevent the draft check if the user is offline to avoid snackbar error notice?


<!-- Sent from Reviewable.io -->

2023-10-09 22:33 UTC, pmachapman reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2114)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 73 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2114#-NgJahJ58wOE4bDfy0n8:-NgLRwUiEFWnW_2gpdn8:b-mdzfxk) ([raw file](https://github.com/sillsdev/web-xforge/blob/01e0306bb6a29a16048c4901e1bfbb2c924d0e0b/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L73)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

If the user is offline and then comes online after the editor loads, do we need to check for a draft in reaction to user coming online (if we haven't already checked)?
</blockquote></details>

I have added a `draftPopulated` variable that should help the code behind know if they need to get the chapter when coming online.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 78 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2114#-NgJZS3K9IHWJceUk342:-NgLRUQk2uZPs_1X7wra:b-r0vbnr) ([raw file](https://github.com/sillsdev/web-xforge/blob/01e0306bb6a29a16048c4901e1bfbb2c924d0e0b/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L78)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

I noticed that if user is offline, it still makes a network request for the draft, causing the "network request failed" snackbar notice. Do you think we should prevent the draft request and display a notice something like, "Draft preview is not available while offline"?
</blockquote></details>

I re-read the JIRA ticket, and changed it so the draft preview UI is hidden completely and a message is shown - I think if users changed chapters when offline, they would wonder why they could not apply the draft, and possible get confused.

Is this too stark a change?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 844 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2114#-NgJb_wgCurG2RdZuVgw:-NgLYl437uZT0cCS3BfU:bvhxslg) ([raw file](https://github.com/sillsdev/web-xforge/blob/01e0306bb6a29a16048c4901e1bfbb2c924d0e0b/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L844)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Like in the draft viewer component, if the user is offline and then comes online after the editor loads, do we need to check for a draft in reaction to user coming online (if we haven't already checked)?

Also, should we prevent the draft check if the user is offline to avoid snackbar error notice?
</blockquote></details>

Good idea. I have refactored the code a bit to achieve that.


<!-- Sent from Reviewable.io -->

2023-10-10 16:15 UTC, siltomato requested changes
I like your idea of hiding everything if not online for the draft viewer.  I made some suggestions for massaging rxjs a bit to get the desired effects.

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2114#-:-NgPMP6ZD796GBsLH1hY:b-oh9x2l)* status: all files reviewed, 14 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.html` line 3 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2114#-NgP6lYv8-OVMN6ExSSF:-NgP6lYwCM86ObDWombw:bhmjjg8) ([raw file](https://github.com/sillsdev/web-xforge/blob/42ab32f9cad53af3de8d76cb9f9030d4599656df/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.html#L3)):*
> ```HTML
> <h1>Draft preview and apply</h1>
> 
> <ng-container *ngIf="!isOnline">
> ```

This `<ng-container>` could be removed and the `*ngIf` put directly on the `<section>`.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.html` line 10 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2114#-NgP6ey83NxMeP6rjKtN:-NgP6ey83NxMeP6rjKtO:bun8eaw) ([raw file](https://github.com/sillsdev/web-xforge/blob/42ab32f9cad53af3de8d76cb9f9030d4599656df/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.html#L10)):*
> ```HTML
> </ng-container>
> 
> <ng-container *ngIf="isOnline">
> ```

One possible issue with the `*ngIf` on the editors is that if the draft loads and sets the `draftPopulated` flag, then the user goes offline and comes back again, the draft will be gone from the editor and won't load again.

One idea is to wrap a div that renders but hides if offline.  Something like:
```html
<div [class.offline]="!isOnline">
```
and then setting the `offline` class to `display: none` in the stylesheet.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.html` line 61 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2114#-NgPGPCs63OcUl-_f2i0:-NgPGPCt0fDr9u652jZG:b-fbmnr9) ([raw file](https://github.com/sillsdev/web-xforge/blob/42ab32f9cad53af3de8d76cb9f9030d4599656df/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.html#L61)):*
> ```HTML
>         {{ targetProject?.shortName }}
>         <!-- TODO: Update i18n -->
>         <span *ngIf="showDraft" class="draft-indicator" [ngClass]="{ applied: isDraftApplied }">
> ```

Since everything is hidden now when offline, this could be changed back to `hasDraft` and the `showDraft` getter could be removed (noted below).
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.html` line 65 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2114#-NgPGXUy2weYHQmkVWpU:-NgPGXUy2weYHQmkVWpV:baqdhic) ([raw file](https://github.com/sillsdev/web-xforge/blob/42ab32f9cad53af3de8d76cb9f9030d4599656df/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.html#L65)):*
> ```HTML
>           <mat-icon *ngIf="isDraftApplied" class="check-icon">check</mat-icon>
>         </span>
>         <div *ngIf="!isDraftApplied && showDraft" class="apply-draft-button-container">
> ```

Could be changed back to `hasDraft`.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 78 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2114#-NgJZS3K9IHWJceUk342:-NgN32Y8DC3dDjMs7w1W:b-a7ljwd) ([raw file](https://github.com/sillsdev/web-xforge/blob/01e0306bb6a29a16048c4901e1bfbb2c924d0e0b/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L78)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

I re-read the JIRA ticket, and changed it so the draft preview UI is hidden completely and a message is shown - I think if users changed chapters when offline, they would wonder why they could not apply the draft, and possible get confused.

Is this too stark a change?
</blockquote></details>

Makes sense to me.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 23 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2114#-NgPH-I1C22v59zTDVJO:-NgPH-I1C22v59zTDVJP:b94g08p) ([raw file](https://github.com/sillsdev/web-xforge/blob/42ab32f9cad53af3de8d76cb9f9030d4599656df/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L23)):*
> ```XML
> })
> export class DraftViewerComponent implements OnInit {
>   @ViewChild('sourceText') sourceEditor?: TextComponent; // Vernacular (source might not be set in project settings)
> ```

I realized that we don't really need to wait for the source editor to load below, so we could remove this line entirely.



_Code quote:_
```XML
@ViewChild('sourceText') sourceEditor?: TextComponent; // Vernacular (source might not be set in project settings)
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 60 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2114#-NgPHFOkEYFuzwWpQ0u-:-NgPHFOkEYFuzwWpQ0u0:b-y0egxc) ([raw file](https://github.com/sillsdev/web-xforge/blob/42ab32f9cad53af3de8d76cb9f9030d4599656df/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L60)):*
> ```XML
>   get showDraft(): boolean {
>     return this.onlineStatusService.isOnline && this.hasDraft;
>   }
> ```

This getter could be removed since everything is hidden when offline.



_Code quote:_
```XML
  get showDraft(): boolean {
    return this.onlineStatusService.isOnline && this.hasDraft;
  }
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 62 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2114#-NgMvd-GD0R0ES4qLys7:-NgMvd-GD0R0ES4qLys8:b-1f4cfo) ([raw file](https://github.com/sillsdev/web-xforge/blob/42ab32f9cad53af3de8d76cb9f9030d4599656df/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L62)):*
> ```XML
>   }
> 
>   get isOnline(): boolean {
> ```

Since we're subscribing to `onlineStatus$` below, what do you think about removing the `isOnline` getter, declaring `isOnline` as a class property, initializing it to `this.onlineStatusService.isOnline`,  and then setting it inside the subscription below?  The benefit would be the efficiency of property access instead of the unnecessary function call.

I've put an example of an idea for that below.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 84 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2114#-NgPHrb33GhtaX5m4OcC:-NgPHrb33GhtaX5m4OcD:bv9dk8r) ([raw file](https://github.com/sillsdev/web-xforge/blob/42ab32f9cad53af3de8d76cb9f9030d4599656df/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L84)):*
> ```XML
>         this.populateDraftText();
>       }
>     });
> ```

Here's an idea to rewrite this to respond to online status changes once the editor loads.  Also, I realized that we don't really need to wait for source editor to load.
```ts
// Wait to populate draft until target editor is loaded with current chapter
this.targetEditor.loaded
  .pipe(
    tap(() => {
      this.draftPopulated = false;
    }),
    // Listen for online status changes once the editor loads
    switchMap(() => this.onlineStatusService.onlineStatus$)
  )
  .subscribe(online => {
    this.isOnline = online;

    // Populate just once per edit [...]

2023-10-10 22:56 UTC, pmachapman reviewed
Thank you for your suggestions and the time it took to figure them out! Please let me know if I have misunderstood or mis-implemented any of them.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2114#-:-NgQmkFy9JlJE6xh_AL7:b-blt8oi)* status: 1 of 6 files reviewed, 14 unresolved discussions (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.html` line 3 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2114#-NgP6lYv8-OVMN6ExSSF:-NgQWWR26l2eeWVl8AQm:b-ydonir) ([raw file](https://github.com/sillsdev/web-xforge/blob/42ab32f9cad53af3de8d76cb9f9030d4599656df/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.html#L3)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

This `<ng-container>` could be removed and the `*ngIf` put directly on the `<section>`.
</blockquote></details>

Done. Good idea.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.html` line 10 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2114#-NgP6ey83NxMeP6rjKtN:-NgQ_c6P5lDlNRTS0DSh:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/42ab32f9cad53af3de8d76cb9f9030d4599656df/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.html#L10)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

One possible issue with the `*ngIf` on the editors is that if the draft loads and sets the `draftPopulated` flag, then the user goes offline and comes back again, the draft will be gone from the editor and won't load again.

One idea is to wrap a div that renders but hides if offline.  Something like:
```html
<div [class.offline]="!isOnline">
```
and then setting the `offline` class to `display: none` in the stylesheet.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.html` line 61 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2114#-NgPGPCs63OcUl-_f2i0:-NgQbl3aC5lISvPBmP4E:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/42ab32f9cad53af3de8d76cb9f9030d4599656df/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.html#L61)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Since everything is hidden now when offline, this could be changed back to `hasDraft` and the `showDraft` getter could be removed (noted below).
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.html` line 65 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2114#-NgPGXUy2weYHQmkVWpU:-NgQbm7I61ffGnReKlVj:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/42ab32f9cad53af3de8d76cb9f9030d4599656df/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.html#L65)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Could be changed back to `hasDraft`.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 78 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2114#-NgJZS3K9IHWJceUk342:-NgQc68M7QLMvQLk_8Fj:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/01e0306bb6a29a16048c4901e1bfbb2c924d0e0b/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L78)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Makes sense to me.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 23 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2114#-NgPH-I1C22v59zTDVJO:-NgQc2B-6wpp5Il3AF_E:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/42ab32f9cad53af3de8d76cb9f9030d4599656df/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L23)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

I realized that we don't really need to wait for the source editor to load below, so we could remove this line entirely.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 60 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2114#-NgPHFOkEYFuzwWpQ0u-:-NgQc3pRBoWq-Hk7nFtL:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/42ab32f9cad53af3de8d76cb9f9030d4599656df/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L60)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

This getter could be removed since everything is hidden when offline.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 62 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2114#-NgMvd-GD0R0ES4qLys7:-NgQcYU77dBCab3_dQCN:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/42ab32f9cad53af3de8d76cb9f9030d4599656df/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L62)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Since we're subscribing to `onlineStatus$` below, what do you think about removing the `isOnline` getter, declaring `isOnline` as a class property, initializing it to `this.onlineStatusService.isOnline`,  and then setting it inside the subscription below?  The benefit would be the efficiency of property access instead of the unnecessary function call.

I've put an example of an idea for that below.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 84 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2114#-NgPHrb33GhtaX5m4OcC:-NgQfIOD33Yd2z4ZzbtE:b78xpl8) ([raw file](https://github.com/sillsdev/web-xforge/blob/42ab32f9cad53af3de8d76cb9f9030d4599656df/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L84)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Here's an idea to rewrite this to respond to online status changes once the editor loads.  Also, I realized that we don't really need to wait for source editor to load.
```ts
// Wait to populate draft until target editor is loaded with current chapter
this.targetEditor.loaded
  .pipe(
    tap(() => {
      this.draftPopulated = false;
    }),
    // Listen for online status changes once the editor loads
    switchMap(() => this.onlineStatusService.onlineStatus$)
  )
  .subscribe(online => {
    this.isOnline = online;

    // Populate just once per editor load
    if (online && !this.draftPopulated) {
      this.populateDraftText();
    }
  });
```

Also, we'll need to unsubscribe from this one.  Sorry I missed doing that, myself.
</blockquote></details>

Done. No problem - I have updated the component to use a `SubscriptionDisposable`.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 91 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2114#-NgPBgWuAWun6uYcMEK4:-NgQfTUE7FJIX8z6-mxr:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/42ab32f9cad53af3de8d76cb9f9030d4599656df/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L91)):*
<details><summa [...]

2023-10-11 02:30 UTC, siltomato requested changes
Awesome!  Just one small change, and we're done.

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2114#-:-NgRZ8sy0UP0K6UNktXY:b1dkeh3)* status: all files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 43 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2114#-NgRUcEb9tHPOAh34c9v:-NgRUcEb9tHPOAh34c9w:b-26apcn) ([raw file](https://github.com/sillsdev/web-xforge/blob/7c1e6dc0160cfe7d30cff2dbfd735253b0300173/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L43)):*
> ```XML
>   hasDraft = false;
>   draftPopulated = false;
>   isOnline = false;
> ```

`isOnline` may need to be initialized to `this.onlineStatusService.isOnline` to prevent a flash of the offline view while the editor loads.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 137 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2114#-NgRW_A12UvJAC2JYVnI:-NgRW_A12UvJAC2JYVnJ:b5bmimz) ([raw file](https://github.com/sillsdev/web-xforge/blob/7c1e6dc0160cfe7d30cff2dbfd735253b0300173/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L137)):*
> ```XML
>     }
> 
>     this.subscribe(
> ```

Interestingly, we don't actually need to unsubscribe from this one, as is it is an http request which completes.  I actually had initially included a note to unsubscribe from this as I went through before I remembered that.

It won't hurt anything to leave it as-is, of course, so I'll leave it up to you.


<!-- Sent from Reviewable.io -->

2023-10-11 04:22 UTC, pmachapman reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2114)* status: all files reviewed, 1 unresolved discussion (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 43 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2114#-NgRUcEb9tHPOAh34c9v:-NgRwhwT9t3wbeaETp0b:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/7c1e6dc0160cfe7d30cff2dbfd735253b0300173/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L43)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

`isOnline` may need to be initialized to `this.onlineStatusService.isOnline` to prevent a flash of the offline view while the editor loads.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts` line 137 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2114#-NgRW_A12UvJAC2JYVnI:-NgRxt4n0b5W0fHx-wCq:bswk5ke) ([raw file](https://github.com/sillsdev/web-xforge/blob/7c1e6dc0160cfe7d30cff2dbfd735253b0300173/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.component.ts#L137)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Interestingly, we don't actually need to unsubscribe from this one, as is it is an http request which completes.  I actually had initially included a note to unsubscribe from this as I went through before I remembered that.

It won't hurt anything to leave it as-is, of course, so I'll leave it up to you.
</blockquote></details>

Done. I have reverted it.


<!-- Sent from Reviewable.io -->

2023-10-11 04:51 UTC, siltomato approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2114#-:-NgS3o2m9PVA3OJqyQFV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @pmachapman)



<!-- Sent from Reviewable.io -->

2023-10-11 18:19 UTC, merged