SF-2249 Handle invalid url book in draft preview and editor pages
sillsdev/web-xforge pull request #2147
Opened 2023-10-26 23:32 UTC by siltomato

When the URL of either the Translate or Preview Draft screen is manually changed to a book that is not in the target project, the components should now route to the first valid book/chapter of the project.

2023-10-27 22:25 UTC, RaymondLuong3 requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2147)* status: all files reviewed, 2 unresolved discussions (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 630 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2147#-NhnBCXb-ff3DGuz1yRU:-NhnBCXb-ff3DGuz1yRV:bqg2mkg) ([raw file](https://github.com/sillsdev/web-xforge/blob/896a21305350e82a3090ba1069bd7b0110d66633/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L630)):*
> ```XML
> 
>         // If book is not in project, navigate to first book of project
>         if (this.text == null) {
> ```

It might also make sense to navigate to the last book that a user was on. I think if possible, we navigate to the book that is stored in `SFProjectUserConfig` but just sending them to the projects route. That is more in line with how we handle when a user logs in.



_Code quote (i):_
```XML
        if (this.text == null) {
```



_Code snippet (ii):_
```XML
this.router.navigateByUrl('projects', { replaceUrl: true })
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 633 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2147#-NhnBoFHAfV2SmH7y6qd:-NhnBoFHAfV2SmH7y6qe:bfsq5j2) ([raw file](https://github.com/sillsdev/web-xforge/blob/896a21305350e82a3090ba1069bd7b0110d66633/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L633)):*
> ```XML
>           const firstText = this.projectDoc.data.texts[0];
>           const newBookId = Canon.bookNumberToId(firstText.bookNum);
>           const chapter = firstText.chapters[0].number;
> ```

Nit: Add types here.



_Code quote:_
```XML
          const firstText = this.projectDoc.data.texts[0];
          const newBookId = Canon.bookNumberToId(firstText.bookNum);
          const chapter = firstText.chapters[0].number;
```


<!-- Sent from Reviewable.io -->

2023-10-29 03:00 UTC, siltomato reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2147)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 630 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2147#-NhnBCXb-ff3DGuz1yRU:-NhtHPXMCu55llJDuTql:bax1ksf) ([raw file](https://github.com/sillsdev/web-xforge/blob/896a21305350e82a3090ba1069bd7b0110d66633/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L630)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

It might also make sense to navigate to the last book that a user was on. I think if possible, we navigate to the book that is stored in `SFProjectUserConfig` but just sending them to the projects route. That is more in line with how we handle when a user logs in.
</blockquote></details>

Ok, neat.  Changed to navigate to 'projects' route.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 633 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2147#-NhnBoFHAfV2SmH7y6qd:-NhnFI7O67OF0dn-755q:b75kj0y) ([raw file](https://github.com/sillsdev/web-xforge/blob/896a21305350e82a3090ba1069bd7b0110d66633/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L633)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Nit: Add types here.
</blockquote></details>

Removed this code as suggested in previous comment.


<!-- Sent from Reviewable.io -->

2023-10-30 17:37 UTC, RaymondLuong3 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2147#-:-Ni0eKSu4ym77CT_dF_H:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @siltomato)



<!-- Sent from Reviewable.io -->

2023-10-30 17:40 UTC, RaymondLuong3 commented
Looks like you have a failing test to fix.

2023-10-30 20:32 UTC, RaymondLuong3 approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2147)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @siltomato)



<!-- Sent from Reviewable.io -->

2023-11-02 18:25 UTC, RaymondLuong3 approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2147)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @siltomato)



<!-- Sent from Reviewable.io -->

2023-11-02 18:26 UTC, merged