SF-2314 Role and Permissions dialog openable when offline
sillsdev/web-xforge pull request #2182
Opened 2023-11-22 17:09 UTC by josephmyers

The dialog can be opened while offline, but the fields are still not editable. I added some text to indicate this in the dialog.

2023-11-22 22:33 UTC, nigel-wells requested changes
Nice to look at this new component - amazing job!

Just a couple of thoughts on the notice.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2182#-:-Njt9fJD8_OIF9zux2Xu:b-o7mkg4)* status: all files reviewed, 1 unresolved discussion (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/users/roles-and-permissions/roles-and-permissions-dialog.component.html` line 19 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2182#-Njt9Lgz7mPB0NcU883k:-Njt9Lgz7mPB0NcU883l:b609qi9) ([raw file](https://github.com/sillsdev/web-xforge/blob/73331a3faaef1aa3accfbd48cc72766f6e6e01e8/src/SIL.XForge.Scripture/ClientApp/src/app/users/roles-and-permissions/roles-and-permissions-dialog.component.html#L19)):*
> ```HTML
>       </div>
>     </app-notice>
>     <span class="offline-text" *ngIf="form.disabled">{{ t("offline") }}</span>
> ```

Could we use the notice component instead - it would need margin above as it is right next to the other notice.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 335 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2182#-Njt9XMq4myLvDw11LWY:-Njt9XMq4myLvDw11LWZ:bfeuorj) ([raw file](https://github.com/sillsdev/web-xforge/blob/73331a3faaef1aa3accfbd48cc72766f6e6e01e8/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L335)):*
> ```JSON
>     "learn_more": "Learn More",
>     "none": "None",
>     "offline": "Editing is unavailable while offline.",
> ```

What about, "Changing roles & permissions is unavailable while offline" ?


<!-- Sent from Reviewable.io -->

2023-11-23 01:19 UTC, Nateowami commented
How do I get to this dialog without having two separate Paratext accounts? Or is that the answer?

2023-11-27 02:50 UTC, josephmyers commented
> How do I get to this dialog without having two separate Paratext accounts? Or is that the answer?

Nope, admin's can open it for any SF user, as well. But if you specifically want to see that the checkboxes for the permissions settings are disabled, you will need a second PT user on the project.

2023-11-27 03:04 UTC, josephmyers reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2182)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/users/roles-and-permissions/roles-and-permissions-dialog.component.html` line 19 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2182#-Njt9Lgz7mPB0NcU883k:-NkDgzP91bZTYz1Hb3Pi:b9ej6dw) ([raw file](https://github.com/sillsdev/web-xforge/blob/73331a3faaef1aa3accfbd48cc72766f6e6e01e8/src/SIL.XForge.Scripture/ClientApp/src/app/users/roles-and-permissions/roles-and-permissions-dialog.component.html#L19)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Could we use the notice component instead - it would need margin above as it is right next to the other notice.
</blockquote></details>

I have no problem doing this, but the current implementation is consistent with how the Users page above is working. Do you want me to change that one, as well? I do see that I missed the top margin, which makes it look bad for PT users. I'll fix this, for sure.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 335 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2182#-Njt9XMq4myLvDw11LWY:-NkDiy6E3niIvA1E30Ye:bb6un1j) ([raw file](https://github.com/sillsdev/web-xforge/blob/73331a3faaef1aa3accfbd48cc72766f6e6e01e8/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L335)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

What about, "Changing roles & permissions is unavailable while offline" ?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-11-27 03:50 UTC, nigel-wells requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2182)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/users/roles-and-permissions/roles-and-permissions-dialog.component.html` line 19 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2182#-Njt9Lgz7mPB0NcU883k:-NkDtXqX5ptMlIvnwlRX:b-rai4ay) ([raw file](https://github.com/sillsdev/web-xforge/blob/73331a3faaef1aa3accfbd48cc72766f6e6e01e8/src/SIL.XForge.Scripture/ClientApp/src/app/users/roles-and-permissions/roles-and-permissions-dialog.component.html#L19)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

I have no problem doing this, but the current implementation is consistent with how the Users page above is working. Do you want me to change that one, as well? I do see that I missed the top margin, which makes it look bad for PT users. I'll fix this, for sure.
</blockquote></details>

Let's go ahead and update the users page as well to keep it consistent.


<!-- Sent from Reviewable.io -->

2023-11-27 07:41 UTC, josephmyers reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2182)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/users/roles-and-permissions/roles-and-permissions-dialog.component.html` line 19 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2182#-Njt9Lgz7mPB0NcU883k:-NkEhGo_0MSKWvWKv6Oz:b-gxlde6) ([raw file](https://github.com/sillsdev/web-xforge/blob/73331a3faaef1aa3accfbd48cc72766f6e6e01e8/src/SIL.XForge.Scripture/ClientApp/src/app/users/roles-and-permissions/roles-and-permissions-dialog.component.html#L19)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Let's go ahead and update the users page as well to keep it consistent.
</blockquote></details>

Actually, we appear to be at the very antithesis of inconsistency. I see four places using app-notice, and nine places using the "offline-text" class. How about we split this off to its own effort for bringing everything up to the app-notice style?


<!-- Sent from Reviewable.io -->

2023-11-27 20:39 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2182)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/users/roles-and-permissions/roles-and-permissions-dialog.component.html` line 19 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2182#-Njt9Lgz7mPB0NcU883k:-NkGR1S27VIPjBew0e3G:b-3oazxo) ([raw file](https://github.com/sillsdev/web-xforge/blob/73331a3faaef1aa3accfbd48cc72766f6e6e01e8/src/SIL.XForge.Scripture/ClientApp/src/app/users/roles-and-permissions/roles-and-permissions-dialog.component.html#L19)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Actually, we appear to be at the very antithesis of inconsistency. I see four places using app-notice, and nine places using the "offline-text" class. How about we split this off to its own effort for bringing everything up to the app-notice style?
</blockquote></details>

I'm not sure we want to bring everything to the app-notice style. It's very bold/prominent. In some contexts that's good (e.g. an entire page being unavailable offline), but I'm not sure it makes sense everywhere (e.g. where a small thing is unavailable, but most of the page is usable).


<!-- Sent from Reviewable.io -->

2023-11-27 21:59 UTC, nigel-wells approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2182)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/users/roles-and-permissions/roles-and-permissions-dialog.component.html` line 19 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2182#-Njt9Lgz7mPB0NcU883k:-NkHl_ri8yp5z4kN4GbA:bkg3bli) ([raw file](https://github.com/sillsdev/web-xforge/blob/73331a3faaef1aa3accfbd48cc72766f6e6e01e8/src/SIL.XForge.Scripture/ClientApp/src/app/users/roles-and-permissions/roles-and-permissions-dialog.component.html#L19)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I'm not sure we want to bring everything to the app-notice style. It's very bold/prominent. In some contexts that's good (e.g. an entire page being unavailable offline), but I'm not sure it makes sense everywhere (e.g. where a small thing is unavailable, but most of the page is usable).
</blockquote></details>

Yes, let's address this in a separate task.
@Nateowami I agree the notice component can look in your face if there are a heap of notices. What it does do is ensure consistent paddings around messages which currently, without it, look very cramped next to other elements on the page. If the outline isn't subtle enough then we could easily add another style for softer messages or even tone down the current ones to something similar to :
![image.png](https://files.reviewableusercontent.io/images/reviewable/17464863/minWEJsxbZ2Ik1bUpWNKjdPT/image.png)


<!-- Sent from Reviewable.io -->

2023-11-28 03:04 UTC, Nateowami commented
@josephmyers Can we get a proper title for this PR? It should start with a verb (e.g. "Allow opening roles & permissions dialog offline") and generally use [passive voice](https://en.wikipedia.org/wiki/Imperative_mood) for consistency (though if doing so makes for a less useful title, clarity should be preferred).

The current title seems to imply that the dialog is openable when offline and shouldn't be, or isn't openable and should. It is not possible to infer from the title what it actually does.

2023-11-30 14:20 UTC, merged