SF-2381 Support phrase level audio scripture playback on questions
sillsdev/web-xforge pull request #2199
Opened 2023-11-30 21:57 UTC by RaymondLuong3

Timing files can be broken down into phrase level (and even word level) components. The Single button audio player accepts the timing for the section of the audio for the verse that a question pertains to. Previously, the component that extracted the data for the timing range did not account for the phrase level timings, meaning that for a single verse, there may be multiple timings.
This change ensures that all the timings for a timing range is considered so that single button audio player is given the correct timing information for the verse.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sillsdev/web-xforge/2199)

2023-12-01 17:44 UTC, Nateowami reviewed
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2199)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.ts` line 95 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2199#-NkaSmHa124zJFHmr63x:-NkaSmHa124zJFHmr63y:bi4mxsm) ([raw file](https://github.com/sillsdev/web-xforge/blob/dce33dbeb7e2bf3e52b030a6fd8c42d4f4b0af80/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.ts#L95)):*
> ```XML
>     );
>     if (verseTimings == null || verseTimings.length === 0) return;
>     return verseTimings.sort((a, b) => b.to - a.to)[0].to;
> ```

Are we expecting the timings to be out of order? I think that would be invalid timing data. Why can't we just take the last timing for the verse? For example:
``` ts
return verseTimings[verseTimings.length - 1].to;
```
Tests continue to pass after this change.


<!-- Sent from Reviewable.io -->

2023-12-04 04:22 UTC, josephmyers requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2199)* status: all files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.spec.ts` line 166 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2199#-Nkn0ziv9qH6cQT1QmdN:-Nkn0ziv9qH6cQT1QmdO:bc38suo) ([raw file](https://github.com/sillsdev/web-xforge/blob/dce33dbeb7e2bf3e52b030a6fd8c42d4f4b0af80/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.spec.ts#L166)):*
> ```XML
>   });
> 
>   it('plays the entire verse when timing files are phrase level', async () => {
> ```

This is basically an integration test. It's not this class's responsibility to verify the entire verse plays, just that it passes the correct start and end to the audio player. We don't have to delete it, but it's a little out of place, and it has a costly 1.2s wait time.

I recommend writing a unit test to verify that scriptureAudioStart and scriptureAudioEnd are correct with phrase-style timing data.


<!-- Sent from Reviewable.io -->

2023-12-04 20:26 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2199)* status: all files reviewed, 2 unresolved discussions (waiting on @josephmyers and @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.ts` line 95 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2199#-NkaSmHa124zJFHmr63x:-NkqVEolAl1GZOm_Zyu8:b-yky4od) ([raw file](https://github.com/sillsdev/web-xforge/blob/dce33dbeb7e2bf3e52b030a6fd8c42d4f4b0af80/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.ts#L95)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Are we expecting the timings to be out of order? I think that would be invalid timing data. Why can't we just take the last timing for the verse? For example:
``` ts
return verseTimings[verseTimings.length - 1].to;
```
Tests continue to pass after this change.
</blockquote></details>

Some timing formats have all the headings grouped in one section of the file, and the verse timings grouped in another. So we should not make the assumption that timings are in order.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.spec.ts` line 166 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2199#-Nkn0ziv9qH6cQT1QmdN:-NkqU04s8ZhOEZd2e3Hj:bza8odk) ([raw file](https://github.com/sillsdev/web-xforge/blob/dce33dbeb7e2bf3e52b030a6fd8c42d4f4b0af80/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.spec.ts#L166)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

This is basically an integration test. It's not this class's responsibility to verify the entire verse plays, just that it passes the correct start and end to the audio player. We don't have to delete it, but it's a little out of place, and it has a costly 1.2s wait time.

I recommend writing a unit test to verify that scriptureAudioStart and scriptureAudioEnd are correct with phrase-style timing data.
</blockquote></details>

That is basically what this does. `env.component.question.scriptureAudioStart` is the propert on the `CheckingQuestionComponent` that is provided to the `SingleButtonAudioPlayerComponent`. If the 1.2s wait seems too costly, it is there to check that the audio is more than 1s long.


<!-- Sent from Reviewable.io -->

2023-12-05 02:33 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2199)* status: all files reviewed, 2 unresolved discussions (waiting on @josephmyers and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.ts` line 95 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2199#-NkaSmHa124zJFHmr63x:-NkrDpC039dRnK_L2dol:b-9gp9hh) ([raw file](https://github.com/sillsdev/web-xforge/blob/dce33dbeb7e2bf3e52b030a6fd8c42d4f4b0af80/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.ts#L95)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Some timing formats have all the headings grouped in one section of the file, and the verse timings grouped in another. So we should not make the assumption that timings are in order.
</blockquote></details>

That is extremely surprising to me. Good to know. I would have assumed timing data formats would require that the timing data be chronological. Is this documented anywhere in a comment? I think it may belong here.

In `get scriptureAudioStart()`, there is a built-in assumption that the first matching timing will be the first chronologically, I think?

Also, what do you think about changing this last line to `Math.max(...verseTimings.map(t => t.to))`? We can be fairly certain that the list will always be short enough that sorting and taking the first item will be extremely fast, but it seems odd to do so when there's a more direct solution that doesn't require sorting.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.spec.ts` line 166 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2199#-Nkn0ziv9qH6cQT1QmdN:-NkrmxQA8dmACDewMFpt:b47a7dp) ([raw file](https://github.com/sillsdev/web-xforge/blob/dce33dbeb7e2bf3e52b030a6fd8c42d4f4b0af80/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.spec.ts#L166)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

That is basically what this does. `env.component.question.scriptureAudioStart` is the propert on the `CheckingQuestionComponent` that is provided to the `SingleButtonAudioPlayerComponent`. If the 1.2s wait seems too costly, it is there to check that the audio is more than 1s long.
</blockquote></details>

I don't think we actually have to play to audio to test that the component correctly figures out when the audio should start and stop. As long as it's figuring it out correctly and sending that information to the child component, we should be fine.

Joseph's comment about 1.2 seconds being costly may seem extreme, but if each of our 1197 Jasmine tests took 1.2 seconds, the entire suite would take 24 minutes. On my machine the tests take about 70 seconds to run, and that's about 58 ms each on average. Being able to get near instant feedback is critical to being able to use the tests as part of the development process.


<!-- Sent from Reviewable.io -->

2023-12-05 05:51 UTC, josephmyers requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2199)* status: all files reviewed, 2 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.spec.ts` line 166 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2199#-Nkn0ziv9qH6cQT1QmdN:-NksWFcE9PNkhcsBrmCw:begqjr5) ([raw file](https://github.com/sillsdev/web-xforge/blob/dce33dbeb7e2bf3e52b030a6fd8c42d4f4b0af80/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.spec.ts#L166)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I don't think we actually have to play to audio to test that the component correctly figures out when the audio should start and stop. As long as it's figuring it out correctly and sending that information to the child component, we should be fine.

Joseph's comment about 1.2 seconds being costly may seem extreme, but if each of our 1197 Jasmine tests took 1.2 seconds, the entire suite would take 24 minutes. On my machine the tests take about 70 seconds to run, and that's about 58 ms each on average. Being able to get near instant feedback is critical to being able to use the tests as part of the development process.
</blockquote></details>

Thanks, Nathaniel, you said it better. Maybe it's as simple as removing the playScripture() and wait(1200). They don't have an impact on the start and end properties, and we have coverage for the focusedText label enough that we can likely get by without it in this test.


<!-- Sent from Reviewable.io -->

2023-12-05 19:06 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2199)* status: all files reviewed, 2 unresolved discussions (waiting on @josephmyers and @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.ts` line 95 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2199#-NkaSmHa124zJFHmr63x:-NkvM3O9E-B1MJJX1sE3:b-huxwo0) ([raw file](https://github.com/sillsdev/web-xforge/blob/dce33dbeb7e2bf3e52b030a6fd8c42d4f4b0af80/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.ts#L95)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

That is extremely surprising to me. Good to know. I would have assumed timing data formats would require that the timing data be chronological. Is this documented anywhere in a comment? I think it may belong here.

In `get scriptureAudioStart()`, there is a built-in assumption that the first matching timing will be the first chronologically, I think?

Also, what do you think about changing this last line to `Math.max(...verseTimings.map(t => t.to))`? We can be fairly certain that the list will always be short enough that sorting and taking the first item will be extremely fast, but it seems odd to do so when there's a more direct solution that doesn't require sorting.
</blockquote></details>

Thanks for spotting that. I've added a comment and updated both getters to return the start and end time using the Math function. Why didn't I think of that?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.spec.ts` line 166 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2199#-Nkn0ziv9qH6cQT1QmdN:-NkvL1G5-VxOBEBxytYj:b6slcya) ([raw file](https://github.com/sillsdev/web-xforge/blob/dce33dbeb7e2bf3e52b030a6fd8c42d4f4b0af80/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.spec.ts#L166)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Thanks, Nathaniel, you said it better. Maybe it's as simple as removing the playScripture() and wait(1200). They don't have an impact on the start and end properties, and we have coverage for the focusedText label enough that we can likely get by without it in this test.
</blockquote></details>

Yes, it does not do a whole lot other than it shows that at 1.2 seconds in, the audio is still playing and the scripture focus text is still active. But the test coverage already in the document is sufficient.


<!-- Sent from Reviewable.io -->

2023-12-12 14:38 UTC, merged