SF-2409 Remove tokienization of data sent to Serval
sillsdev/web-xforge pull request #2239
Opened 2023-12-13 19:54 UTC by pmachapman

Because Serval performs its own, more accurate tokenization, we should not do that before sending the data to Serval. However, until the In-Process machine is removed from SF, that logic will need to remain.

This is achieved by:

* Creating data structures that override and are parallel to the SIL.Machine data structures that includes the entire Segment text.
* Only sending verse segment data to Serval Nmt for Pre-Translation.
* Refactoring SFScriptureTextTests for clarity.

In addition, this PR alters the data sent to Serval to Pre-Translation to only include verse data. This will improve the quality of data generated. A later PR (SF-2410) will re-enable this support via a project setting.

2023-12-14 19:40 UTC, RaymondLuong3 requested changes
Thanks. Just some minor clean-up and then it is good to go.

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2239#-:-Nldpr8UDePzHjowk2MD:bbt5ecn)* status: all files reviewed, 8 unresolved discussions (waiting on @pmachapman)

___
*[`test/SIL.XForge.Scripture.Tests/Services/SFScriptureTextTests.cs` line 24 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2239#-NldorAd0XDtUGrIwc3h:-NldorAd0XDtUGrIwc3i:b4g0r75) ([raw file](https://github.com/sillsdev/web-xforge/blob/c50797a23e4f9ecfdf846039f1e8e6d8631a1158/test/SIL.XForge.Scripture.Tests/Services/SFScriptureTextTests.cs#L24)):*
> ```Smalltalk
>             {
>                 "ops",
>                 new BsonArray { ChapterMarker, VerseMarker, VerseSegment }
> ```

Great clean up to simplify reusing the bson objects in the Bson array.
___
*[`test/SIL.XForge.Scripture.Tests/Services/SFScriptureTextTests.cs` line 190 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2239#-NldnTZE9XjnwTV-NsZ4:-NldnTZE9XjnwTV-NsZ5:b-5qqvzw) ([raw file](https://github.com/sillsdev/web-xforge/blob/c50797a23e4f9ecfdf846039f1e8e6d8631a1158/test/SIL.XForge.Scripture.Tests/Services/SFScriptureTextTests.cs#L190)):*
> ```Smalltalk
>         };
>         const int numberOps = 3;
>         const int numberSegments = 0;
> ```

expectedNumberSegments would be a better name
___
*[`test/SIL.XForge.Scripture.Tests/Services/SFScriptureTextTests.cs` line 224 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2239#-Nldnbmr-v5CjeS5sghO:-Nldnbmr-v5CjeS5sghP:b2nreh6) ([raw file](https://github.com/sillsdev/web-xforge/blob/c50797a23e4f9ecfdf846039f1e8e6d8631a1158/test/SIL.XForge.Scripture.Tests/Services/SFScriptureTextTests.cs#L224)):*
> ```Smalltalk
>         };
>         const int numberOps = 3;
>         const int numberSegments = 1;
> ```

Same as above.



_Code quote:_
```Smalltalk
        const int numberSegments = 1;
```
___
*[`test/SIL.XForge.Scripture.Tests/Services/SFScriptureTextTests.cs` line 247 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2239#-Nldnz7J-yfEkVPUew3n:-Nldnz7J-yfEkVPUew3o:b-hp3no1) ([raw file](https://github.com/sillsdev/web-xforge/blob/c50797a23e4f9ecfdf846039f1e8e6d8631a1158/test/SIL.XForge.Scripture.Tests/Services/SFScriptureTextTests.cs#L247)):*
> ```Smalltalk
> 
>     [Test]
>     public void Create_ExcludeNonScriptureSegmentsIfPreTranslateFalse()
> ```

This should say "IncludeNonScriptureSegments..."
___
*[`test/SIL.XForge.Scripture.Tests/Services/SFScriptureTextTests.cs` line 258 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2239#-NldnxTI4d1ku4uQGdAu:-NldnxTI4d1ku4uQGdAv:b2nreh6) ([raw file](https://github.com/sillsdev/web-xforge/blob/c50797a23e4f9ecfdf846039f1e8e6d8631a1158/test/SIL.XForge.Scripture.Tests/Services/SFScriptureTextTests.cs#L258)):*
> ```Smalltalk
>         };
>         const int numberOps = 4;
>         const int numberSegments = 2; // The heading and the verse text
> ```

Same as above.
___
*[`test/SIL.XForge.Scripture.Tests/Services/SFScriptureTextTests.cs` line 292 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2239#-Nldo6Xc4I40Ka3KYOdg:-Nldo6Xc4I40Ka3KYOdh:b2nreh6) ([raw file](https://github.com/sillsdev/web-xforge/blob/c50797a23e4f9ecfdf846039f1e8e6d8631a1158/test/SIL.XForge.Scripture.Tests/Services/SFScriptureTextTests.cs#L292)):*
> ```Smalltalk
>         };
>         const int numberOps = 4;
>         const int numberSegments = 1; // Just the verse text
> ```

Same as above.
___
*[`test/SIL.XForge.Scripture.Tests/Services/SFScriptureTextTests.cs` line 326 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2239#-NldoAAnAfLB-qxfqSTB:-NldoAAnAfLB-qxfqSTC:b2nreh6) ([raw file](https://github.com/sillsdev/web-xforge/blob/c50797a23e4f9ecfdf846039f1e8e6d8631a1158/test/SIL.XForge.Scripture.Tests/Services/SFScriptureTextTests.cs#L326)):*
> ```Smalltalk
>         };
>         const int numberOps = 4;
>         const int numberSegments = 2; // The verse text and the paragraph in the verse
> ```

Same as above.
___
*[`test/SIL.XForge.Scripture.Tests/Services/SFScriptureTextTests.cs` line 395 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2239#-NldoisfD8ofr80Bv3ru:-NldoisfD8ofr80Bv3rv:b2nreh6) ([raw file](https://github.com/sillsdev/web-xforge/blob/c50797a23e4f9ecfdf846039f1e8e6d8631a1158/test/SIL.XForge.Scripture.Tests/Services/SFScriptureTextTests.cs#L395)):*
> ```Smalltalk
>         };
>         const int numberOps = 4;
>         const int numberSegments = 1; // Just the verse text
> ```

Same as above.


<!-- Sent from Reviewable.io -->

2023-12-14 20:13 UTC, RaymondLuong3 reviewed
Any idea why I would get this 503 error? It is preventing me from testing this issue.
![image.png](https://files.reviewableusercontent.io/images/reviewable/17931130/fd_yjVLm0yLM5xsfD1rlgbjd/image.png)

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2239#-:-NldxXYs6Drz0LXCDAbZ:b-4jedew)* status: all files reviewed, 8 unresolved discussions (waiting on @pmachapman)



<!-- Sent from Reviewable.io -->

2023-12-14 20:17 UTC, ddaspit reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2239#-:-NldyUpxCqlo3FKqoGDE:bnfp4nl)* status: all files reviewed, 8 unresolved discussions (waiting on @pmachapman)



<!-- Sent from Reviewable.io -->

2023-12-14 20:18 UTC, RaymondLuong3 reviewed
Ok, looks like I was on the wrong branch. It is working now.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2239#-:-NldyjNC7Ka7k-9LSRjq:b-5omggn)* status: all files reviewed, 8 unresolved discussions (waiting on @pmachapman)



<!-- Sent from Reviewable.io -->

2023-12-17 18:36 UTC, pmachapman reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2239)* status: 7 of 11 files reviewed, 7 unresolved discussions (waiting on @ddaspit and @RaymondLuong3)

___
*[`test/SIL.XForge.Scripture.Tests/Services/SFScriptureTextTests.cs` line 190 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2239#-NldnTZE9XjnwTV-NsZ4:-NlszI7o6ZNSD96uiGov:b-jsrqj9) ([raw file](https://github.com/sillsdev/web-xforge/blob/c50797a23e4f9ecfdf846039f1e8e6d8631a1158/test/SIL.XForge.Scripture.Tests/Services/SFScriptureTextTests.cs#L190)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

expectedNumberSegments would be a better name
</blockquote></details>

Done. Great idea.
___
*[`test/SIL.XForge.Scripture.Tests/Services/SFScriptureTextTests.cs` line 224 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2239#-Nldnbmr-v5CjeS5sghO:-NlszeO18lWlNZvxQXa0:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/c50797a23e4f9ecfdf846039f1e8e6d8631a1158/test/SIL.XForge.Scripture.Tests/Services/SFScriptureTextTests.cs#L224)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.
___
*[`test/SIL.XForge.Scripture.Tests/Services/SFScriptureTextTests.cs` line 247 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2239#-Nldnz7J-yfEkVPUew3n:-NlszeoDDwLozWjyVruC:b-vu792e) ([raw file](https://github.com/sillsdev/web-xforge/blob/c50797a23e4f9ecfdf846039f1e8e6d8631a1158/test/SIL.XForge.Scripture.Tests/Services/SFScriptureTextTests.cs#L247)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This should say "IncludeNonScriptureSegments..."
</blockquote></details>

Done. Good catch - thank you!
___
*[`test/SIL.XForge.Scripture.Tests/Services/SFScriptureTextTests.cs` line 258 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2239#-NldnxTI4d1ku4uQGdAu:-Nlszpgy9trAHdCIrVcB:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/c50797a23e4f9ecfdf846039f1e8e6d8631a1158/test/SIL.XForge.Scripture.Tests/Services/SFScriptureTextTests.cs#L258)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.
___
*[`test/SIL.XForge.Scripture.Tests/Services/SFScriptureTextTests.cs` line 292 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2239#-Nldo6Xc4I40Ka3KYOdg:-Nlszr5W9Njscax8ad0D:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/c50797a23e4f9ecfdf846039f1e8e6d8631a1158/test/SIL.XForge.Scripture.Tests/Services/SFScriptureTextTests.cs#L292)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.
___
*[`test/SIL.XForge.Scripture.Tests/Services/SFScriptureTextTests.cs` line 326 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2239#-NldoAAnAfLB-qxfqSTB:-NlszrmG1TXeh0n96O8t:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/c50797a23e4f9ecfdf846039f1e8e6d8631a1158/test/SIL.XForge.Scripture.Tests/Services/SFScriptureTextTests.cs#L326)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.
___
*[`test/SIL.XForge.Scripture.Tests/Services/SFScriptureTextTests.cs` line 395 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2239#-NldoisfD8ofr80Bv3ru:-NlszsJM6XVu_1GKX_Rx:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/c50797a23e4f9ecfdf846039f1e8e6d8631a1158/test/SIL.XForge.Scripture.Tests/Services/SFScriptureTextTests.cs#L395)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-18 17:28 UTC, RaymondLuong3 approved these changes
> Reviewed 2 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2239)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)



<!-- Sent from Reviewable.io -->

2023-12-18 17:57 UTC, merged