SF-2414 Refactored CC answer tabs into a single view
sillsdev/web-xforge pull request #2287
Opened 2024-01-09 08:58 UTC by josephmyers

Really trying to maximize efficiency of space, with a focus on mobile devices.

Introduced a compact flag on the audio recorder, which the CC answer view uses. The combined control uses the standard version. Both versions have had some modifications made to save space.

2024-01-09 14:22 UTC, Nateowami commented
I realize this is still a draft PR, but I want to point out that this messed up the layout in other places where the record component is used:

![](https://github.com/sillsdev/web-xforge/assets/6140710/7ef73e4c-f60f-4934-9d31-6944522f3b43)

2024-01-15 07:21 UTC, josephmyers commented
Thanks for keeping me accountable. I was already aware that this would impact other places, and I think I've made improvements to both. I'm struggling to see where in your screenshot I've messed up the layout. Here's the old layout:
![image](https://github.com/sillsdev/web-xforge/assets/43733878/79051cbf-8674-4971-bbff-d1e0ccfd61ff)
The layout here is all messed up. Spatially, we've set the start and end verse references together, but then grouped the verse display closely with the question text. Then, we set the Record/Upload piece way down off on its own. It's pretty confusing.

What I've done is group things according to their ideas, namely, verse reference and question. (I did add the word "audio" back to the buttons.) This is even more important on mobile, which looks worse than desktop. My branch fixes that, too, and the side-to-side runoff.
![image](https://github.com/sillsdev/web-xforge/assets/43733878/86f61e65-61e5-4530-aaaf-e5652e2e4697)

Old->New (Mobile)
![image](https://github.com/sillsdev/web-xforge/assets/43733878/ae7fc72a-c2e1-4de6-a4b1-c6aa19ece94d)

2024-01-16 06:37 UTC, Nateowami commented
Having the recording buttons center aligned feels wrong to me. They seem like they should be left aligned.

2024-01-16 06:48 UTC, josephmyers commented
The whole form, other than the header and footer, is centered, except for those controls. If we had any other fields that were left-aligned, it might make more sense. But as it is, it's jarring being the only thing stuck to the left. I can undo it, but it doesn't match with the visual flow. Really, it doesn't lead the users' eyes to the natural end of the form at the bottom right like it could.

2024-01-17 03:19 UTC, nigel-wells commented
Could you do the same approach you did for answering the question with the record button to the right of the question and an attach button under it?

2024-01-17 03:30 UTC, josephmyers commented
I like that idea. The Attach button would be different slightly, of course

2024-01-24 18:33 UTC, Nateowami commented
When I hover over the button and then move my mouse down, the tooltip gets in the way. This also happens when adding an answer, so I have trouble clicking "Save."

![](https://github.com/sillsdev/web-xforge/assets/6140710/186385ec-95e2-498b-b583-07d46c3ba5ca)

One option would be to change the position: https://v16.material.angular.io/components/tooltip/overview

2024-01-30 22:21 UTC, Nateowami commented
@josephmyers I see you've updated this PR in the last 12 hours, but there are a large number of conflicts. Is this actually ready to review again?

2024-01-31 06:20 UTC, josephmyers commented
No, but I'm about to do the master rebase. I typically re-request review when I finish the comments

2024-02-28 02:49 UTC, nigel-wells requested changes
I like where this is heading. I've only reviewed around half of it as I have some queries which may or may not impact the parts I've not reviewed - mostly UI related.

> Reviewed 16 of 26 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-:-NrhbJQF74R-ZQ6kXZ1U:bluzuik)* status: 16 of 26 files reviewed, 13 unresolved discussions (waiting on @josephmyers and @Nateowami)

___
*[`src/RealtimeServer/scriptureforge/models/dynamic-value.ts` line 7 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrcJ5jA3_1fDlQj2BZq:-NrcJ5jA3_1fDlQj2BZr:b-h8wc4v) ([raw file](https://github.com/sillsdev/web-xforge/blob/d8b02cf9d6f9bb8570700a15b317d95d1b9babb5/src/RealtimeServer/scriptureforge/models/dynamic-value.ts#L7)):*
> ```XML
>   audio, or both.
> */
> export interface DynamicValue extends Value {
> ```

I don't get yet why you've done this rather than leaving them as optional properties on the Question model. I'll review this comment later in my review in case it comes clearer then :)
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html` line 75 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrcOV7oEohwow1epbXT:-NrcOV7oEohwow1epbXU:bwa8rod) ([raw file](https://github.com/sillsdev/web-xforge/blob/d8b02cf9d6f9bb8570700a15b317d95d1b9babb5/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html#L75)):*
> ```HTML
>       </div>
>       <div class="answers-container" *ngIf="shouldShowAnswers">
>         <ng-container>
> ```

Do we still need the container?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.html` line 24 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrcTnHn1xdk6tnSNwBD:-NrcTnHn1xdk6tnSNwBE:b-mfwlo4) ([raw file](https://github.com/sillsdev/web-xforge/blob/d8b02cf9d6f9bb8570700a15b317d95d1b9babb5/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.html#L24)):*
> ```HTML
>     </button>
>   </div>
>   <div *ngIf="hasAudioAttachment" class="has-attachment">
> ```

This works but visually I find it odd going from a big record button to a big stop button, to a small play button with an X just above it - I get why it turned out that way though. It isn't too bad on mobile but it is very big on desktop.

I did like one of the wireframe ideas where the play/record was also down where attach is.

Looking a the add/edit question dialog and it isn't so bad because of the uploader. What if the "Upload" icon turned into a rubbish bin button - this may help with things moving around after audio is uploaded/attached?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.ts` line 35 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrhaMNYC80NYVT7kdYP:-NrhaMNYC80NYVT7kdYQ:b-pvml83) ([raw file](https://github.com/sillsdev/web-xforge/blob/d8b02cf9d6f9bb8570700a15b317d95d1b9babb5/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.ts#L35)):*
> ```XML
>   ]
> })
> /* eslint-disable brace-style */
> ```

Should we update our lint rules if prettier is breaking them?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.ts` line 65 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrhaoNW5hNUdilIhvPV:-NrhaoNW5hNUdilIhvPW:b-975il9) ([raw file](https://github.com/sillsdev/web-xforge/blob/d8b02cf9d6f9bb8570700a15b317d95d1b9babb5/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.ts#L65)):*
> ```XML
>   }
> 
>   writeValue(obj: any): void {
> ```

For this, and below, can we not declare the expected type?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.scss` line 6 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrhUwvx2k3_6V0ZB0iD:-NrhUwvx2k3_6V0ZB0iE:b-eiydfz) ([raw file](https://github.com/sillsdev/web-xforge/blob/3fbc4040e4d3ef749c21d0cfb5c0cc40ecd11add/src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.scss#L6)):*
> ```SCSS
> 
> mat-form-field {
>   margin-bottom: 1em;
> ```

This is still needed or at least needed for small devices when it is stacked.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.scss` line 6 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrhVYNG2Z3ox3bT7Kkn:-NrhVYNG2Z3ox3bT7Kko:b-q0tsf1) ([raw file](https://github.com/sillsdev/web-xforge/blob/d8b02cf9d6f9bb8570700a15b317d95d1b9babb5/src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.scss#L6)):*
> ```SCSS
> 
> mat-form-field {
>   .scripture-helper-text .scripture-reference {
> ```

Is this around the right way? It looks like `.scripture-help-text` is nested inside of `.scripture-reference`
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.scss` line 12 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrhTvn71PUvBGHVhZh9:-NrhTvn86t3nNsNo0_GJ:bqi7lh5) ([raw file](https://github.com/sillsdev/web-xforge/blob/d8b02cf9d6f9bb8570700a15b317d95d1b9babb5/src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.scss#L12)):*
> ```SCSS
>     }
>   }
>   &.question-container {
> ```

This class doesn't exist any more.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.scss` line 24 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrhW91t7neBisoRC0N3:-NrhW91t7neBisoRC0N4:b-pzma1y) ([raw file](https://github.com/sillsdev/web-xforge/blob/d8b02cf9d6f9bb8570700a15b317d95d1b9babb5/src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.scss#L24)):*
> ```SCSS
> .text-container {
>   height: 10em;
>   margin-bottom: 3em;
> ```

I'm in two minds about this. I like the extra breathing space but it feels like something is missing - perhaps we're all too often trying to reduce space that it makes me uneasy about deliberately creating space lol
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts` line 186 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrhZljM8VjwEA5KX_S2:-NrhZljM8VjwEA5KX_S3:b-i5mxzs) ([raw file](https://github.com/sillsdev/web-xforge/blob/d8b02cf9d6f9bb8570700a15b317d95d1b9babb5/src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts#L186)):*
> ```XML
>     this.dialogRef.close({
>       verseRef: this._selection,
>       text: this.textAndAudio?.text.value,
> ```

We'd want to be sure at this point that `textAndAudio` is defined. It is proved above, can we do that here as well? Otherwise, use a `!` to really state that it is defined.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts` line 103 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrhWz0QCv6WvTjdRyK2:-NrhWz0QCv6WvTjdRyK3:b-dt51xh) ([raw file](https://github.com/sillsdev/web-xforge/blob/3fbc4040e4d3ef749c21d0cfb5c0cc40ecd11add/src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts#L103)):*
> ```XML
>     flush();
>     expect(env.afterCloseCallback).not.toHaveBeenCalled();
>     expect(env.scriptureStartValidationMsg.textContent).toContain('Required');
> ```

Do you think we could move the test - I get they aren't really related to what it says this test is testing.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.compon [...]

2024-02-28 05:13 UTC, josephmyers reviewed
Thanks for your review. Nobody else wanted it, I guess! I had a little trouble understanding one or two of your comments, probably because it's been a while since I wrote all this. Let me know if a Google Meet would be better in helping me understand

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-:-Nri5x3o4s9oI0Y_GzGz:b-xncmhx)* status: 11 of 26 files reviewed, 13 unresolved discussions (waiting on @Nateowami and @nigel-wells)

___
*[`src/RealtimeServer/scriptureforge/models/dynamic-value.ts` line 7 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrcJ5jA3_1fDlQj2BZq:-NrhkrTZ6sJjFj-oXcUT:bfv62l9) ([raw file](https://github.com/sillsdev/web-xforge/blob/08327f4804419aee01a40ce5ec60d2d7505a946f/src/RealtimeServer/scriptureforge/models/dynamic-value.ts#L7)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

I don't get yet why you've done this rather than leaving them as optional properties on the Question model. I'll review this comment later in my review in case it comes clearer then :)
</blockquote></details>

We can't leave them on Question, because it has to work for Answer, as well. The granularization of these interfaces is required to be able to accept either Question or Answer as a value. Questions and Answers are similar in that they both require text or audio.

This was required for me to implement your comment about the Edit Question dialog, unless we want to duplicate TextAndAudioComponent for it.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html` line 75 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrcOV7oEohwow1epbXT:-NrhoB1a2W_Bi_a15I15:bl4mpi6) ([raw file](https://github.com/sillsdev/web-xforge/blob/08327f4804419aee01a40ce5ec60d2d7505a946f/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html#L75)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Do we still need the container?
</blockquote></details>

Doesn't look like it! Thanks
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.html` line 24 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrcTnHn1xdk6tnSNwBD:-NrhobMN0yhtREzU7fiH:b-p37xzr) ([raw file](https://github.com/sillsdev/web-xforge/blob/08327f4804419aee01a40ce5ec60d2d7505a946f/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.html#L24)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

This works but visually I find it odd going from a big record button to a big stop button, to a small play button with an X just above it - I get why it turned out that way though. It isn't too bad on mobile but it is very big on desktop.

I did like one of the wireframe ideas where the play/record was also down where attach is.

Looking a the add/edit question dialog and it isn't so bad because of the uploader. What if the "Upload" icon turned into a rubbish bin button - this may help with things moving around after audio is uploaded/attached?
</blockquote></details>

Okay, you mention a lot in one comment! I'll try to tackle everything:

I am certainly open to other ideas. I, too, liked the original design, which had the mic down in the bottom left. However, that design was created when we were thinking we might remove Select Text, so it doesn't account for it at all. I spent a long time trying to get Select Text to fit into that design in a clear and compact way, but it didn't work. You'll notice even as it currently is in the branch, it's quite reduced. This I think is a good thing, but it was hard to justify reducing it more.

The only other design I had, though it had its own problems, was to combine all three auxiliary tools (Record, Upload, and Select Text) into Attach and make it a menu. Though it sounds nice, you still run into multiple issues with two "attachments." I came to the conclusion that Select Text was the limiting factor, the only sensible place to put it being where it is now, and record/upload had to fit in after.

Keep in mind the focus for this is mobile. Nathaniel has iterated to me multiple times, "Design for mobile, ensure desktop works." On an actual mobile device, the button isn't overbearing to me. It's big, but it emphasizes equality with text. We already know that some projects are using only audio. Are you suggesting any tweak in particular? I could drop the border (and shrink the button), and maybe that would be enough?

I wasn't aware the switch from two buttons to one on upload was jarring. I can certainly change this, but how should it work for the Answers pane, which doesn't have Upload?

We can certainly talk about these over a call, if that'd be helpful.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.ts` line 35 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrhaMNYC80NYVT7kdYP:-Nrhxd2C20l6NtYzNmDS:b-osgfon) ([raw file](https://github.com/sillsdev/web-xforge/blob/08327f4804419aee01a40ce5ec60d2d7505a946f/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.ts#L35)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Should we update our lint rules if prettier is breaking them?
</blockquote></details>

I posted this to Slack a long time ago. I think both rules are still desired, but in this rare case they conflicted.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.ts` line 65 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrhaoNW5hNUdilIhvPV:-NrhyZDG3Dob0puFmY-r:b-l5wxi0) ([raw file](https://github.com/sillsdev/web-xforge/blob/08327f4804419aee01a40ce5ec60d2d7505a946f/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.ts#L65)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

For this, and below, can we not declare the expected type?
</blockquote></details>

I read this about ten times. Can you be a little clearer on what I should do? These come from ControlValueAccessor.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.scss` line 6 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrhVYNG2Z3ox3bT7Kkn:-Nri0odC1bHsGYrVAtRT:b1o5n88) ([raw file](https://github.com/sillsdev/web-xforge/blob/08327f4804419aee01a40ce5ec60d2d7505a946f/src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.scss#L6)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Is this around the right way? It looks like `.scripture-help-text` is nested inside of `.scripture-reference`
</blockquote></details>

Done. I honestly don't even remember what this was doing. I removed it altogether
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.scss` line 6 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrhUwvx2k3_6V0ZB0iD:-Nri0rFj2FPjNRCdnWo9:b-3j5ti3) ([raw file](https://github.com/sillsdev/web-xforge/blob/1db30373e93e802af449d558dcd971f699579986/src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.scss#L6)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

This is still needed or at least needed for small devices when it is stacked.
</blockquote></details>

I wasn't able to see this having an effect. It looks fine to me without it, and I couldn't ever get the helper text larger than  [...]

2024-02-29 03:09 UTC, nigel-wells requested changes
Thanks. This was one I thought Nathaniel was looking at due to the feedback but since clarified that was more of a quick review and feedback of the feature rather than in-depth.

A chat would be great as I'm still unsure about the dynamic value property that you're introducing and why we need to break it out.

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-:-NrmpAbb8EBQdtIRcIrE:b-8jqh47)* status: 16 of 26 files reviewed, 6 unresolved discussions (waiting on @josephmyers and @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.html` line 24 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrcTnHn1xdk6tnSNwBD:-NrmodsK2cXT2MMNT8Ml:b-7shjc2) ([raw file](https://github.com/sillsdev/web-xforge/blob/08327f4804419aee01a40ce5ec60d2d7505a946f/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.html#L24)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Okay, you mention a lot in one comment! I'll try to tackle everything:

I am certainly open to other ideas. I, too, liked the original design, which had the mic down in the bottom left. However, that design was created when we were thinking we might remove Select Text, so it doesn't account for it at all. I spent a long time trying to get Select Text to fit into that design in a clear and compact way, but it didn't work. You'll notice even as it currently is in the branch, it's quite reduced. This I think is a good thing, but it was hard to justify reducing it more.

The only other design I had, though it had its own problems, was to combine all three auxiliary tools (Record, Upload, and Select Text) into Attach and make it a menu. Though it sounds nice, you still run into multiple issues with two "attachments." I came to the conclusion that Select Text was the limiting factor, the only sensible place to put it being where it is now, and record/upload had to fit in after.

Keep in mind the focus for this is mobile. Nathaniel has iterated to me multiple times, "Design for mobile, ensure desktop works." On an actual mobile device, the button isn't overbearing to me. It's big, but it emphasizes equality with text. We already know that some projects are using only audio. Are you suggesting any tweak in particular? I could drop the border (and shrink the button), and maybe that would be enough?

I wasn't aware the switch from two buttons to one on upload was jarring. I can certainly change this, but how should it work for the Answers pane, which doesn't have Upload?

We can certainly talk about these over a call, if that'd be helpful.
</blockquote></details>

Good reminder that mobile is king for community checking. What if we took a similar approach to sending a message on your phone where the send button is just an icon and is inside the textbox itself? The answer starts off as a one liner and grows the more you type. This would then free up the space under it (with Attach verses) to let you move the audio controls down there?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.ts` line 65 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrhaoNW5hNUdilIhvPV:-NrmceHLExRJHvX5tx24:bgrvsh5) ([raw file](https://github.com/sillsdev/web-xforge/blob/08327f4804419aee01a40ce5ec60d2d7505a946f/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.ts#L65)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

I read this about ten times. Can you be a little clearer on what I should do? These come from ControlValueAccessor.
</blockquote></details>

Use `AudioAttachment` instead of `any`

`writeValue(obj: AudioAttachment)`
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.scss` line 6 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrhUwvx2k3_6V0ZB0iD:-Nrm_-VM-Mq9Gyd6R0PY:b-kvw2i5) ([raw file](https://github.com/sillsdev/web-xforge/blob/1db30373e93e802af449d558dcd971f699579986/src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.scss#L6)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

I wasn't able to see this having an effect. It looks fine to me without it, and I couldn't ever get the helper text larger than ~200px. Does the change you recommend below address this? Here's a screenshot without the style (maybe the error text could use a couple pixels):
![image.png](https://files.reviewableusercontent.io/images/reviewable/43733878/jjjcRmRsBRz6sTC8KmwBi_c5/image.png)
</blockquote></details>

I should have provided more context. The end reference needs a value
![image.png](https://files.reviewableusercontent.io/images/reviewable/17464863/-Ujm04ueXJn7MtGf91eV4ZBx/image.png)
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.scss` line 24 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrhW91t7neBisoRC0N3:-NrmmqCjCR_H5MPeoZw3:b-xjdu34) ([raw file](https://github.com/sillsdev/web-xforge/blob/08327f4804419aee01a40ce5ec60d2d7505a946f/src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.scss#L24)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

See my response to Nathaniel from Jan 15. But it sounds like neither of you guys really likes the change? I can make further tweaks, if you want.
</blockquote></details>

I'm ok with - I prefer the space more than no space. To be honest, what bugs me the most is the scripture start/end boxes not lining up nicely with the text container :)
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts` line 186 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrhZljM8VjwEA5KX_S2:-Nrm_UXg68yptKpecoSD:bmvr8m0) ([raw file](https://github.com/sillsdev/web-xforge/blob/08327f4804419aee01a40ce5ec60d2d7505a946f/src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts#L186)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

I agree, thanks. I've been told before to avoid `!` in general.
</blockquote></details>

It has its place. Actually, do you even get a warning without it? I've tried just now and there is no warning about it being possibly undefined.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts` line 103 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrhWz0QCv6WvTjdRyK2:-NrmapwJ3jZUAOmdsiBE:bed2vng) ([raw file](https://github.com/sillsdev/web-xforge/blob/1db30373e93e802af449d558dcd971f699579986/src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts#L103)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Help me understand here. Where should I move the test? To me, it's testing that clicking Save when required fields are missing isn't allowed. This is related to the question dialog, right?
</blockquote></details>

I should have quoted the parts I was referring to.

```
expect(env.scriptureStartValidationMsg.textContent).toContain('Required');
expect(env.scriptureStartValidationMsg.textContent).not.toContain('e.g.');
expect(env.scriptureStartValidationMsg.textContent).not.toContain('range');
```
These lines seem useful to assert in a separate test.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json` line 191 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrcP6CO0RnYqu9ryw40:-Nrmblyi5PPJ-486EpQB:b9a0lfa) ([raw file](https://github.com/sillsdev/web-xforge/blob/08327 [...]

2024-02-29 07:02 UTC, josephmyers reviewed
Threw you an invite for next week!

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-:-NrnFU3P95sGyb2O8MSI:bjwy8a9)* status: 12 of 26 files reviewed, 6 unresolved discussions (waiting on @Nateowami and @nigel-wells)

___
*[`src/RealtimeServer/scriptureforge/models/dynamic-value.ts` line 7 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrcJ5jA3_1fDlQj2BZq:-NrnI_qeDdMMJmrJDMWj:b-5gybnf) ([raw file](https://github.com/sillsdev/web-xforge/blob/08327f4804419aee01a40ce5ec60d2d7505a946f/src/RealtimeServer/scriptureforge/models/dynamic-value.ts#L7)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

We can't leave them on Question, because it has to work for Answer, as well. The granularization of these interfaces is required to be able to accept either Question or Answer as a value. Questions and Answers are similar in that they both require text or audio.

This was required for me to implement your comment about the Edit Question dialog, unless we want to duplicate TextAndAudioComponent for it.
</blockquote></details>

Sorry that I'm not explaining well enough. We for sure can talk about it more next week, but here's me trying to do some more clarification:

TextAndAudioComponent can receive either Question or Answer. The only properties it needs from these are text and audioUrl, as seen in that file. Maybe there's some other way that TS/JS allows you to make those two concretes interchangeable, but the way most apparent to me was to extract the duplicated properties into a shared interface. This allows both to be compatible, which is what makes interfaces so useful. More info [here](https://www.baeldung.com/java-interface-segregation)
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.html` line 24 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrcTnHn1xdk6tnSNwBD:-NrnF-HS-XX5uGCudmRN:b9l7rjf) ([raw file](https://github.com/sillsdev/web-xforge/blob/08327f4804419aee01a40ce5ec60d2d7505a946f/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.html#L24)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Good reminder that mobile is king for community checking. What if we took a similar approach to sending a message on your phone where the send button is just an icon and is inside the textbox itself? The answer starts off as a one liner and grows the more you type. This would then free up the space under it (with Attach verses) to let you move the audio controls down there?
</blockquote></details>

I'll try to put this design on Balsamiq, and we can flesh it out there.
https://balsamiq.cloud/sghq53/pejrlz8/rC402
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.ts` line 65 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrhaoNW5hNUdilIhvPV:-NrnH0-U5S8af8yijwXy:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/08327f4804419aee01a40ce5ec60d2d7505a946f/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.ts#L65)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Use `AudioAttachment` instead of `any`

`writeValue(obj: AudioAttachment)`
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.scss` line 6 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrhUwvx2k3_6V0ZB0iD:-NrnPu6R2ajrFo3JtFg3:b-j57e5m) ([raw file](https://github.com/sillsdev/web-xforge/blob/1db30373e93e802af449d558dcd971f699579986/src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.scss#L6)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

I should have provided more context. The end reference needs a value
![image.png](https://files.reviewableusercontent.io/images/reviewable/17464863/-Ujm04ueXJn7MtGf91eV4ZBx/image.png)
</blockquote></details>

Of course! Good catch
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.scss` line 24 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrhW91t7neBisoRC0N3:-NrnQPfB5qNi9TW316EN:b-gsx8x6) ([raw file](https://github.com/sillsdev/web-xforge/blob/08327f4804419aee01a40ce5ec60d2d7505a946f/src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.scss#L24)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

I'm ok with - I prefer the space more than no space. To be honest, what bugs me the most is the scripture start/end boxes not lining up nicely with the text container :)
</blockquote></details>

Ok, left spacing as is. Are you saying you want the verse boxes left aligned? That's easy enough. Done. (I'm not a fan of it, but it's easy to change.)
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts` line 186 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrhZljM8VjwEA5KX_S2:-NrnQe-n3QIoeV9vE9PM:bvfc9go) ([raw file](https://github.com/sillsdev/web-xforge/blob/08327f4804419aee01a40ce5ec60d2d7505a946f/src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts#L186)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

It has its place. Actually, do you even get a warning without it? I've tried just now and there is no warning about it being possibly undefined.
</blockquote></details>

Right. I thought it'd be nice to be explicit and fail fast. If you don't assert, then you're saying it's ok to submit when that component is null/undefined, which is not the case! So we'd fail fast in that situation. I liked it, but I'll do whatever!
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts` line 103 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrhWz0QCv6WvTjdRyK2:-Nrne-Xj4GLs2UBTeXfS:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/1db30373e93e802af449d558dcd971f699579986/src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.spec.ts#L103)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

I should have quoted the parts I was referring to.

```
expect(env.scriptureStartValidationMsg.textContent).toContain('Required');
expect(env.scriptureStartValidationMsg.textContent).not.toContain('e.g.');
expect(env.scriptureStartValidationMsg.textContent).not.toContain('range');
```
These lines seem useful to assert in a separate test.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-01 03:58 UTC, nigel-wells requested changes
Thanks.

> Reviewed 1 of 26 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-:-Nrs9Xj867QFdsreKv_Q:b-ucfkn4)* status: 17 of 26 files reviewed, 3 unresolved discussions (waiting on @josephmyers and @Nateowami)

___
*[`src/RealtimeServer/scriptureforge/models/dynamic-value.ts` line 7 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrcJ5jA3_1fDlQj2BZq:-Nrs-Hym0aEGCLqBcQMe:bg4oelj) ([raw file](https://github.com/sillsdev/web-xforge/blob/08327f4804419aee01a40ce5ec60d2d7505a946f/src/RealtimeServer/scriptureforge/models/dynamic-value.ts#L7)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Sorry that I'm not explaining well enough. We for sure can talk about it more next week, but here's me trying to do some more clarification:

TextAndAudioComponent can receive either Question or Answer. The only properties it needs from these are text and audioUrl, as seen in that file. Maybe there's some other way that TS/JS allows you to make those two concretes interchangeable, but the way most apparent to me was to extract the duplicated properties into a shared interface. This allows both to be compatible, which is what makes interfaces so useful. More info [here](https://www.baeldung.com/java-interface-segregation)
</blockquote></details>

Gotcha! I probably would have simply set `@Input() input?: Question | Answer;` in `TextAndAudtioComponent` but I'm lazy like that. I can see value in creating another interface to allow for both`audioUrl` and `text`. Do you think `DynamicValue` is the best name for this rather than something more specific like `TextAndAudio` and `Value` to be....duno, `Text` would likely be confusing - it's a shame we don't support audio on comments :)
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.html` line 24 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrcTnHn1xdk6tnSNwBD:-Nrs7Fz06DJgNT6xXXJt:bz5i6pw) ([raw file](https://github.com/sillsdev/web-xforge/blob/08327f4804419aee01a40ce5ec60d2d7505a946f/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.html#L24)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

I'll try to put this design on Balsamiq, and we can flesh it out there.
https://balsamiq.cloud/sghq53/pejrlz8/rC402
</blockquote></details>

Thanks. I've added some ideas in there - mostly ripped straight out of Google Messages lol
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.scss` line 24 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrhW91t7neBisoRC0N3:-NrruaBbEWhWxXzc1u80:bhhihjq) ([raw file](https://github.com/sillsdev/web-xforge/blob/08327f4804419aee01a40ce5ec60d2d7505a946f/src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.scss#L24)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Ok, left spacing as is. Are you saying you want the verse boxes left aligned? That's easy enough. Done. (I'm not a fan of it, but it's easy to change.)
</blockquote></details>

Another one I should have been more specific on. I think it looks great if you remove the `flex-wrap` on `.references` and then add `flex: 1` on each `mat-form-field`. This will let them stretch to nicely fill the space across most viewports. Once it gets to a small size device then you can stack them but still let them grow with `flex: 1`.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts` line 186 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrhZljM8VjwEA5KX_S2:-Nrs9LBp5WrbGLDJOx1E:b-wc0sq6) ([raw file](https://github.com/sillsdev/web-xforge/blob/08327f4804419aee01a40ce5ec60d2d7505a946f/src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts#L186)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Right. I thought it'd be nice to be explicit and fail fast. If you don't assert, then you're saying it's ok to submit when that component is null/undefined, which is not the case! So we'd fail fast in that situation. I liked it, but I'll do whatever!
</blockquote></details>

In this case you don't have to assert anything as TS has already figured it out and understands that it is defined at this point - no need for a ? or a !.


<!-- Sent from Reviewable.io -->

2024-03-01 10:47 UTC, josephmyers reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2287)* status: 15 of 26 files reviewed, 3 unresolved discussions (waiting on @Nateowami and @nigel-wells)

___
*[`src/RealtimeServer/scriptureforge/models/dynamic-value.ts` line 7 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrcJ5jA3_1fDlQj2BZq:-Nrt_-GVDIFo5tZYZwGv:b-a91i26) ([raw file](https://github.com/sillsdev/web-xforge/blob/08327f4804419aee01a40ce5ec60d2d7505a946f/src/RealtimeServer/scriptureforge/models/dynamic-value.ts#L7)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Gotcha! I probably would have simply set `@Input() input?: Question | Answer;` in `TextAndAudtioComponent` but I'm lazy like that. I can see value in creating another interface to allow for both`audioUrl` and `text`. Do you think `DynamicValue` is the best name for this rather than something more specific like `TextAndAudio` and `Value` to be....duno, `Text` would likely be confusing - it's a shame we don't support audio on comments :)
</blockquote></details>

Yeah, you're right, DynamicValue isn't knocking anybody's socks off. Is there some way to capture that at least one is required, but you can have both, too? That may not need to be captured at the interface level.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.html` line 24 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrcTnHn1xdk6tnSNwBD:-Nrt_qdmEu77vKRiinUl:b-58x1nc) ([raw file](https://github.com/sillsdev/web-xforge/blob/08327f4804419aee01a40ce5ec60d2d7505a946f/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.html#L24)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Thanks. I've added some ideas in there - mostly ripped straight out of Google Messages lol
</blockquote></details>

Yeah, let's continue fleshing things out there. I'll be happy as long as we get away from the tab's
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.scss` line 24 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrhW91t7neBisoRC0N3:-NrtaOG7-wUxOOx-NHfb:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/08327f4804419aee01a40ce5ec60d2d7505a946f/src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.scss#L24)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Another one I should have been more specific on. I think it looks great if you remove the `flex-wrap` on `.references` and then add `flex: 1` on each `mat-form-field`. This will let them stretch to nicely fill the space across most viewports. Once it gets to a small size device then you can stack them but still let them grow with `flex: 1`.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts` line 186 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrhZljM8VjwEA5KX_S2:-Nrta5QF1nw2c9U1JJI9:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/08327f4804419aee01a40ce5ec60d2d7505a946f/src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.ts#L186)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

In this case you don't have to assert anything as TS has already figured it out and understands that it is defined at this point - no need for a ? or a !.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-04 02:18 UTC, nigel-wells requested changes
> Reviewed 4 of 26 files at r1, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2287)* status: 21 of 26 files reviewed, 2 unresolved discussions (waiting on @josephmyers and @Nateowami)

___
*[`src/RealtimeServer/scriptureforge/models/dynamic-value.ts` line 7 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrcJ5jA3_1fDlQj2BZq:-Ns66tnLBHc687pNT4nB:bm596jw) ([raw file](https://github.com/sillsdev/web-xforge/blob/08327f4804419aee01a40ce5ec60d2d7505a946f/src/RealtimeServer/scriptureforge/models/dynamic-value.ts#L7)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Yeah, you're right, DynamicValue isn't knocking anybody's socks off. Is there some way to capture that at least one is required, but you can have both, too? That may not need to be captured at the interface level.
</blockquote></details>

I think it is fine to have both properties on the interface optional. You could create a type that you use to help enforce the rule that one is needed. I looked through some websites, and a little ChatGPT suggestions, and this appears to work ok:

```
type AtLeastOne<T, U = { [K in keyof T]: Pick<T, K> }> = Partial<T> & U[keyof U];

type TextOrAudio = AtLeastOne<Required<TextAudio>>;

interface TextAudio {
  text?: string;
  audioUrl?: string;
}

const foo: TextOrAudio = { text: 'test' };
const bar: TextOrAudio = { audioUrl: 'audio.mp3' };
const fooBar: TextOrAudio = { text: 'test', audioUrl: 'audio.mp3' };
const bad: TextOrAudio = {};
```

You could then have `Questions` and `Answers` extend `TextAudio` - or call it what you prefer.


<!-- Sent from Reviewable.io -->

2024-03-04 02:47 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2287)* status: 21 of 26 files reviewed, 2 unresolved discussions (waiting on @nigel-wells)

___
*[`src/RealtimeServer/scriptureforge/models/dynamic-value.ts` line 7 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrcJ5jA3_1fDlQj2BZq:-Ns6K6qY94fYWmGc5mmA:bf9c9wh) ([raw file](https://github.com/sillsdev/web-xforge/blob/08327f4804419aee01a40ce5ec60d2d7505a946f/src/RealtimeServer/scriptureforge/models/dynamic-value.ts#L7)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

I think it is fine to have both properties on the interface optional. You could create a type that you use to help enforce the rule that one is needed. I looked through some websites, and a little ChatGPT suggestions, and this appears to work ok:

```
type AtLeastOne<T, U = { [K in keyof T]: Pick<T, K> }> = Partial<T> & U[keyof U];

type TextOrAudio = AtLeastOne<Required<TextAudio>>;

interface TextAudio {
  text?: string;
  audioUrl?: string;
}

const foo: TextOrAudio = { text: 'test' };
const bar: TextOrAudio = { audioUrl: 'audio.mp3' };
const fooBar: TextOrAudio = { text: 'test', audioUrl: 'audio.mp3' };
const bad: TextOrAudio = {};
```

You could then have `Questions` and `Answers` extend `TextAudio` - or call it what you prefer.
</blockquote></details>

Can you not just do a union of the three possibilities? `{ text: string; audioUrl: string; } | { text: string;; } | { audioUrl: string; }`

Maybe I'm missing something? I haven't looked at this closely.


<!-- Sent from Reviewable.io -->

2024-03-04 06:29 UTC, josephmyers reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2287)* status: 21 of 26 files reviewed, 2 unresolved discussions (waiting on @nigel-wells)

___
*[`src/RealtimeServer/scriptureforge/models/dynamic-value.ts` line 7 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrcJ5jA3_1fDlQj2BZq:-Ns76bCd0aEUWgzAKn0v:b-l919tq) ([raw file](https://github.com/sillsdev/web-xforge/blob/08327f4804419aee01a40ce5ec60d2d7505a946f/src/RealtimeServer/scriptureforge/models/dynamic-value.ts#L7)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Can you not just do a union of the three possibilities? `{ text: string; audioUrl: string; } | { text: string;; } | { audioUrl: string; }`

Maybe I'm missing something? I haven't looked at this closely.
</blockquote></details>

I tried this, but I get `Property 'text' does not exist on type '{ audioUrl: string; }'.ts(2339)` Maybe there's another edit I need to make?

Nigel, your change appears to work, though I'm not convinced of the readability of
`type AtLeastOne<T, U \= { \[K in keyof T\]: Pick<T, K\> }> \= Partial<T\> & U\[keyof U\];`

I'll do whatever you guys want, but I still think mine is simplest :D and I don't see any downsides other than the name. Seems like TextOrAudio is acceptable? Just let me know what we should do!


<!-- Sent from Reviewable.io -->

2024-03-05 22:01 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2287)* status: 16 of 26 files reviewed, 3 unresolved discussions (waiting on @josephmyers and @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/text-and-audio/text-and-audio.component.ts` line 19 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NsFbx9-0OFafmNk-u3L:-NsFbx90Ekvgijp7erkV:b-wlmtba) ([raw file](https://github.com/sillsdev/web-xforge/blob/bbd7955e9a99e1a7209d0556f9b81d046d2aef94/src/SIL.XForge.Scripture/ClientApp/src/app/checking/text-and-audio/text-and-audio.component.ts#L19)):*
> ```XML
> export class TextAndAudioComponent implements AfterViewInit, OnDestroy {
>   @ViewChild(CheckingAudioRecorderComponent) audioComponent?: CheckingAudioRecorderComponent;
>   @Input() input?: DynamicValue;
> ```

Can't this just be:
``` ts
@Input() input?: { text?: string; audioUrl?: string; };
```
Then there's no need to change the definition of Question and Answer to implement the DynamicValue interface.
___
*[`src/RealtimeServer/scriptureforge/models/dynamic-value.ts` line 7 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrcJ5jA3_1fDlQj2BZq:-NsFbAD71A6Q4twcCAB7:b-wujvvw) ([raw file](https://github.com/sillsdev/web-xforge/blob/08327f4804419aee01a40ce5ec60d2d7505a946f/src/RealtimeServer/scriptureforge/models/dynamic-value.ts#L7)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

I tried this, but I get `Property 'text' does not exist on type '{ audioUrl: string; }'.ts(2339)` Maybe there's another edit I need to make?

Nigel, your change appears to work, though I'm not convinced of the readability of
`type AtLeastOne<T, U \= { \[K in keyof T\]: Pick<T, K\> }> \= Partial<T\> & U\[keyof U\];`

I'll do whatever you guys want, but I still think mine is simplest :D and I don't see any downsides other than the name. Seems like TextOrAudio is acceptable? Just let me know what we should do!
</blockquote></details>

Perhaps I misunderstood what you were trying to accomplish. I thought you were trying to represent the fact that if there's no audio, there is text, and if there's no text, there is audio, and have that understood by the type system.

I think maybe you're trying to be able to do `[input]="someQuestion"` and `[input]="someAnswer"`, and needing a type to specify there? Why can't you specify the type of the input? I'll add a comment in context on that line to show what I mean.


<!-- Sent from Reviewable.io -->

2024-03-06 04:07 UTC, nigel-wells requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2287)* status: 16 of 26 files reviewed, 3 unresolved discussions (waiting on @josephmyers and @Nateowami)

___
*[`src/RealtimeServer/scriptureforge/models/dynamic-value.ts` line 7 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrcJ5jA3_1fDlQj2BZq:-NsGuSoB4PxoKrBVVTTK:b-e5hrfi) ([raw file](https://github.com/sillsdev/web-xforge/blob/08327f4804419aee01a40ce5ec60d2d7505a946f/src/RealtimeServer/scriptureforge/models/dynamic-value.ts#L7)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Perhaps I misunderstood what you were trying to accomplish. I thought you were trying to represent the fact that if there's no audio, there is text, and if there's no text, there is audio, and have that understood by the type system.

I think maybe you're trying to be able to do `[input]="someQuestion"` and `[input]="someAnswer"`, and needing a type to specify there? Why can't you specify the type of the input? I'll add a comment in context on that line to show what I mean.
</blockquote></details>

Yes, passing in question or answer. I think `@Input() input?: { text?: string; audioUrl?: string; };` is fine and the interfaces for Question and Answer could probably remain as they are - do we gain much by splitting them out into more interfaces any more?
You could add a validator to this form to ensure that either text or audio has been set to help make your assertion clear in this component?


<!-- Sent from Reviewable.io -->

2024-03-06 04:35 UTC, josephmyers reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2287)* status: 16 of 26 files reviewed, 2 unresolved discussions (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/text-and-audio/text-and-audio.component.ts` line 19 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NsFbx9-0OFafmNk-u3L:-NsH0QB72GH7YT7IQS78:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/bbd7955e9a99e1a7209d0556f9b81d046d2aef94/src/SIL.XForge.Scripture/ClientApp/src/app/checking/text-and-audio/text-and-audio.component.ts#L19)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Can't this just be:
``` ts
@Input() input?: { text?: string; audioUrl?: string; };
```
Then there's no need to change the definition of Question and Answer to implement the DynamicValue interface.
</blockquote></details>

Done.
___
*[`src/RealtimeServer/scriptureforge/models/dynamic-value.ts` line 7 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrcJ5jA3_1fDlQj2BZq:-NsGz2BB8jLlckxIDlxm:b-omq4if) ([raw file](https://github.com/sillsdev/web-xforge/blob/08327f4804419aee01a40ce5ec60d2d7505a946f/src/RealtimeServer/scriptureforge/models/dynamic-value.ts#L7)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Yes, passing in question or answer. I think `@Input() input?: { text?: string; audioUrl?: string; };` is fine and the interfaces for Question and Answer could probably remain as they are - do we gain much by splitting them out into more interfaces any more?
You could add a validator to this form to ensure that either text or audio has been set to help make your assertion clear in this component?
</blockquote></details>

Well, I don't think it needs to be "set up" on init, unless I'm misunderstanding. It just has to be filled out before we can save/submit. Nathaniel's change is solid -- it's literally just the interface I made without making it an interface.

From a design standpoint, it is valuable to split apart interfaces. Without making an actual interface, as above, you circumvent the clarity you get from things like documentation, including self-documenting code, not mention reusability. Granted, my interface name wasn't great in the first place. Also, given that JS can do basically whatever it wants with types, we're not using interfaces like I'd expect, as building blocks and ways to group an attribute's properties. So we can revert all my interface changes in favor of inline


<!-- Sent from Reviewable.io -->

2024-03-07 01:23 UTC, nigel-wells reviewed
> Reviewed 1 of 26 files at r1, 5 of 6 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2287)* status: 22 of 26 files reviewed, 1 unresolved discussion

___
*[`src/RealtimeServer/scriptureforge/models/dynamic-value.ts` line 7 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NrcJ5jA3_1fDlQj2BZq:-NsLUyhA1Ztl36BIBZFQ:bu699no) ([raw file](https://github.com/sillsdev/web-xforge/blob/08327f4804419aee01a40ce5ec60d2d7505a946f/src/RealtimeServer/scriptureforge/models/dynamic-value.ts#L7)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Well, I don't think it needs to be "set up" on init, unless I'm misunderstanding. It just has to be filled out before we can save/submit. Nathaniel's change is solid -- it's literally just the interface I made without making it an interface.

From a design standpoint, it is valuable to split apart interfaces. Without making an actual interface, as above, you circumvent the clarity you get from things like documentation, including self-documenting code, not mention reusability. Granted, my interface name wasn't great in the first place. Also, given that JS can do basically whatever it wants with types, we're not using interfaces like I'd expect, as building blocks and ways to group an attribute's properties. So we can revert all my interface changes in favor of inline
</blockquote></details>

Ah, yes, I see you're point.


<!-- Sent from Reviewable.io -->

2024-04-26 04:25 UTC, nigel-wells reviewed
I've had an initial look of the newly implemented UI and it looks great! So glad we spent that extra time on it. 

Two quick things I noticed that I thought worth mentioning now before I do a full code review:
1. Adding a question seems to have lost the ability to add audio now
2. The "Save Answer" & "Cancel" buttons will ideally still be text/icon buttons until the viewport gets too small to support it. It is great for mobile but the icons look very small and lonely on larger screens

> Reviewed 8 of 19 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-:-NwNc3DZAwwEQUEkulAI:bza9r4c)* status: 16 of 29 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-04-26 04:46 UTC, nigel-wells requested changes
Partial review - still a few files left to do.

> Reviewed 5 of 19 files at r9.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-:-NwNiMa36bjbdMqyijXf:bj7cnvc)* status: 21 of 29 files reviewed, 6 unresolved discussions (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html` line 51 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NwNgvHa1I9oBjhlfcEY:-NwNgvHa1I9oBjhlfcEZ:bpulp6q) ([raw file](https://github.com/sillsdev/web-xforge/blob/eb95d591caa752522699a9e43f484aed634787c7/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html#L51)):*
> ```HTML
>           ></app-text-and-audio>
>           <div class="bottom-row">
>             <div class="left-side">
> ```

nit  How about `attachments` or similar? There is no "right" side div plus RTL makes it seem odd.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html` line 89 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NwNi6pZ7Ckotz8vCkR5:-NwNi6pZ7Ckotz8vCkR6:bqld0vz) ([raw file](https://github.com/sillsdev/web-xforge/blob/eb95d591caa752522699a9e43f484aed634787c7/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html#L89)):*
> ```HTML
>             <div class="form-actions">
>               <button mat-icon-button type="button" (click)="hideAnswerForm()" id="cancel-answer">
>                 <mat-icon class="material-icons-outlined">cancel</mat-icon>
> ```

As mentioned previously, larger viewports would benefit from still seeing text in the buttons.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss` line 56 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NwNhwel0zabf9iIhFIv:-NwNhwel0zabf9iIhFIw:b-yj629d) ([raw file](https://github.com/sillsdev/web-xforge/blob/eb95d591caa752522699a9e43f484aed634787c7/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss#L56)):*
> ```SCSS
>     justify-content: space-between;
>   }
>   .left-side {
> ```

Add a small top margin so that the spacing above is the same as between each button
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss` line 65 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NwNhLDE1GllQII6u0p9:-NwNhLDE1GllQII6u0pA:b-s9nmk0) ([raw file](https://github.com/sillsdev/web-xforge/blob/eb95d591caa752522699a9e43f484aed634787c7/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss#L65)):*
> ```SCSS
>   }
>   .stop-recording {
>     color: red;
> ```

Use `$errorColor` from `_variables.scss`. We should probably have a "red" variable created which gets assigned to `$errorColor` and this stop button if you wanted to do that as well.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss` line 175 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NwNgQLS-UmaQ0VdUzaS:-NwNgQLS-UmaQ0VdUzaT:b-6qcv47) ([raw file](https://github.com/sillsdev/web-xforge/blob/eb95d591caa752522699a9e43f484aed634787c7/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss#L175)):*
> ```SCSS
>   display: flex;
>   align-items: center;
>   color: checking-vars.$greenDark;
> ```

Can this be set to the `--theme` logic you did for the audio player i.e. make this black
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss` line 179 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NwNgc91AEan17NxYlcr:-NwNgc91AEan17NxYlcs:b-jgc58m) ([raw file](https://github.com/sillsdev/web-xforge/blob/eb95d591caa752522699a9e43f484aed634787c7/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss#L179)):*
> ```SCSS
>   padding-inline-start: 6px;
>   border-radius: 4px;
>   font-size: 0.9em;
> ```

What will this look like at normal 1em? It looks a bit small and lost now.


<!-- Sent from Reviewable.io -->

2024-04-26 16:20 UTC, Nateowami reviewed
This looks amazing. Thank you so much for your persistence on this. 

In regards to Nigel's comments:
> Adding a question seems to have lost the ability to add audio now

I'm not seeing this problem. @nigel-wells Could you elaborate?

> The "Save Answer" & "Cancel" buttons will ideally still be text/icon buttons until the viewport gets too small to support it. It is great for mobile but the icons look very small and lonely on larger screens

I agree; we should keep text on these buttons unless the screen size is too small for it.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-:-NwQ9PLQDkmKn7xN-LfJ:b4gtmei)* status: 21 of 29 files reviewed, 6 unresolved discussions (waiting on @josephmyers and @nigel-wells)



<!-- Sent from Reviewable.io -->

2024-04-29 03:18 UTC, nigel-wells reviewed
This is what I see when adding a question now - no more buttons for audio?
![image.png](https://files.reviewableusercontent.io/images/reviewable/17464863/H3KoUK-yU79cn0f1yjgYEK5f/image.png)

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-:-Nwbqxi8-CXhxo2ljTpI:bwbde57)* status: 21 of 29 files reviewed, 6 unresolved discussions (waiting on @josephmyers)



<!-- Sent from Reviewable.io -->

2024-04-29 04:00 UTC, josephmyers reviewed
Scroll down. Your dialog is a weird height. It looks normal on my laptop and the Chrome-based mobile devices.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-:-Nwc-QcO3Ct76OGGphnn:b-g71zbm)* status: 21 of 29 files reviewed, 5 unresolved discussions (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html` line 89 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NwNi6pZ7Ckotz8vCkR5:-NwbtpoY6iim1r6707vG:b-7uiuil) ([raw file](https://github.com/sillsdev/web-xforge/blob/97cbdea961f7595dd0d4c861e36fb6b71e2af72e/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html#L89)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

As mentioned previously, larger viewports would benefit from still seeing text in the buttons.
</blockquote></details>

Done. Take a look and let me know
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss` line 56 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NwNhwel0zabf9iIhFIv:-Nwbvggm0d-LY8klbVgA:b-4bjoh1) ([raw file](https://github.com/sillsdev/web-xforge/blob/97cbdea961f7595dd0d4c861e36fb6b71e2af72e/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss#L56)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Add a small top margin so that the spacing above is the same as between each button
</blockquote></details>

I'm actually not seeing this. If you use the dev tools Elements tab and hover over "bottom-row," you can see that the spacing is the same for all buttons. Also, in my opinion, the buttons look evenly spaced.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss` line 65 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NwNhLDE1GllQII6u0p9:-NwbyO2c6dDpVCofi1Ux:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/97cbdea961f7595dd0d4c861e36fb6b71e2af72e/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss#L65)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Use `$errorColor` from `_variables.scss`. We should probably have a "red" variable created which gets assigned to `$errorColor` and this stop button if you wanted to do that as well.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss` line 175 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NwNgQLS-UmaQ0VdUzaS:-NwbzCrA5dUUVm4XjooD:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/97cbdea961f7595dd0d4c861e36fb6b71e2af72e/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss#L175)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Can this be set to the `--theme` logic you did for the audio player i.e. make this black
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss` line 179 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NwNgc91AEan17NxYlcr:-Nwc-93t8UAyjq6V-eoe:b-akxm88) ([raw file](https://github.com/sillsdev/web-xforge/blob/97cbdea961f7595dd0d4c861e36fb6b71e2af72e/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss#L179)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

What will this look like at normal 1em? It looks a bit small and lost now.
</blockquote></details>

Done. Caveat is that it takes up more space, i.e. more likely to require line wrapping.


<!-- Sent from Reviewable.io -->

2024-04-29 04:50 UTC, nigel-wells reviewed
Here is another project - there is no where to scroll for me?
![image.png](https://files.reviewableusercontent.io/images/reviewable/17464863/BiBEHmo9ooS6XlAw7rUXPmSh/image.png)

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-:-NwcB9YjC_sK2wDFlGSi:bb04dak)* status: 15 of 30 files reviewed, 5 unresolved discussions



<!-- Sent from Reviewable.io -->

2024-04-29 17:00 UTC, Nateowami reviewed
@nigel-wells Are you sure you're on the latest commit on this branch?

@josephmyers I don't think it's a scroll issue, but if it was, that would be a big enough UX problem that it would need to be fixed. If Nigel couldn't find something because it's hidden, our users probably can't either. But again, I think this isn't the actual issue at hand.

Circular icon buttons like you had before look good:
![](https://files.reviewableusercontent.io/images/reviewable/6140710/YAbYxp20TQHKWi2vcWqCVEBU/Screenshot%20from%202024-04-29%2012-49-13.png)

I don't think these rectangular icon buttons look good:
![](https://files.reviewableusercontent.io/images/reviewable/6140710/DA0JndB0gw12vfU2C2Nnsxv2/Screenshot%20from%202024-04-29%2012-47-53.png)

I don't think having a circle inside of a button makes for a good icon. Having the circle makes sense when the icon is the button, but when it's inside the button, it feels wrong to me:
![](https://files.reviewableusercontent.io/images/reviewable/6140710/OIZRJm_ZUuediHd-aKxQC-8V/Screenshot%20from%202024-04-29%2012-47-45.png)

Just having a X and check mark seems to me the most logical. This check mark does feel a bit too large to me though:
![](https://files.reviewableusercontent.io/images/reviewable/6140710/g8hmX_r4Dit_-sx6aAPT7GXz/Screenshot%20from%202024-04-29%2012-54-06.png)

This icon feels more appropriately sized, though I'm not a big fan of the circle outline, and the fact that it doesn't match the X (which is also available in a circle version).
![](https://files.reviewableusercontent.io/images/reviewable/6140710/_RgCqRZn5mf84Yug6PvwBPaV/Screenshot%20from%202024-04-29%2012-54-24.png)

I think overall I prefer the plain X and check mark, but it's an aesthetic choice, so I don't have confidence in my opinion.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-:-NwejLpUA6a1KpexwxZQ:b-q802dl)* status: 15 of 30 files reviewed, 5 unresolved discussions (waiting on @nigel-wells)



<!-- Sent from Reviewable.io -->

2024-04-30 01:28 UTC, josephmyers reviewed
Thanks, Nathaniel. After I made my comment I was thinking it was probably not the latest commit.

I am fine with any of these. Let's say the plain X and check mark. What should the small-screen version look like? The original? I was attempting to match the pattern of the New Question button we have, particularly the one we have on the Manage Questions page. My interpretation here is that we could/should use a plain X and check with text for large screens and a circled X and check for smaller ones, per my previous attempt.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-:-Nwg_ehsEetdU6syGt79:bng4u2v)* status: 15 of 30 files reviewed, 5 unresolved discussions (waiting on @nigel-wells)



<!-- Sent from Reviewable.io -->

2024-04-30 01:55 UTC, Nateowami reviewed
I think this is a good option:

Large screen | Small screen
-------------------|------------------
![](https://files.reviewableusercontent.io/images/reviewable/6140710/9WSGNIej5DDjakV8qamoaTXn/Screenshot%20from%202024-04-29%2012-54-06.png) | ![](https://files.reviewableusercontent.io/images/reviewable/6140710/8hWA7-HuzalHBqWqZyBLOfeM/Screenshot%20from%202024-04-29%2012-49-13.png)

Is that what you were asking? I'm not entirely certain I understood your question correctly.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-:-NwghJDh8qe5aJhv5FWM:b-wxa9io)* status: 15 of 30 files reviewed, 5 unresolved discussions (waiting on @nigel-wells)



<!-- Sent from Reviewable.io -->

2024-04-30 05:06 UTC, nigel-wells reviewed
@josephmyers I've pulled down your most recent branch from today and it is appearing correctly now - I must have been on a version where you hadn't implemented it in there yet.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-:-NwhOKv2-AMb22Peh9KC:b-olkxoa)* status: 15 of 30 files reviewed, 5 unresolved discussions (waiting on @Nateowami)



<!-- Sent from Reviewable.io -->

2024-05-01 07:40 UTC, nigel-wells requested changes
Remind me, why did we hide the audio buttons to the right of the text area and, instead, create the same buttons outside of the component? Why not just move them down in the text and audio component?

> Reviewed 2 of 26 files at r1, 4 of 19 files at r9, 7 of 9 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-:-Nwn543q40Z4aKVsKl6-:bgli4zt)* status: all files reviewed, 9 unresolved discussions (waiting on @josephmyers and @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html` line 88 at r11](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-Nwn1VC776NIT__55PtN:-Nwn1VC776NIT__55PtO:bi79c59) ([raw file](https://github.com/sillsdev/web-xforge/blob/1eabc1a8d713553e7914dec7f5dc5e37ce3af1d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html#L88)):*
> ```HTML
>             </div>
>             <div class="form-actions">
>               <button mat-icon-button class="small-screen" type="button" (click)="hideAnswerForm()" id="cancel-answer">
> ```

Would be nice if we could have one set of buttons and then show/hide what is in them rather than small/large screen. Doesn't need to hold this up as I know it can be fiddley.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html` line 112 at r11](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NwmXpsS0Uyk8PqjgzXp:-NwmXpsS0Uyk8PqjgzXq:b11c8lh) ([raw file](https://github.com/sillsdev/web-xforge/blob/1eabc1a8d713553e7914dec7f5dc5e37ce3af1d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html#L112)):*
> ```HTML
>                 color="primary"
>                 form="answer-form"
>                 id="save-answer"
> ```

Can the ID be different as we shouldn't use the same ID multiple times in the DOM. Is it even needed?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss` line 56 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NwNhwel0zabf9iIhFIv:-NwmYZGABdxJ-AaHmvBU:b-mc5fkd) ([raw file](https://github.com/sillsdev/web-xforge/blob/97cbdea961f7595dd0d4c861e36fb6b71e2af72e/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss#L56)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

I'm actually not seeing this. If you use the dev tools Elements tab and hover over "bottom-row," you can see that the spacing is the same for all buttons. Also, in my opinion, the buttons look evenly spaced.
</blockquote></details>

A little picky from me. There is a row gap on the form of 2px. There is a margin between the buttons of 4px
![image.png](https://files.reviewableusercontent.io/images/reviewable/17464863/kjskSlCXVUcVF7OvP0MAoTDC/image.png)
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss` line 179 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NwNgc91AEan17NxYlcr:-NwmYrr--Fz4lr3MBn8_:bkieu3b) ([raw file](https://github.com/sillsdev/web-xforge/blob/97cbdea961f7595dd0d4c861e36fb6b71e2af72e/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss#L179)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Done. Caveat is that it takes up more space, i.e. more likely to require line wrapping.
</blockquote></details>

I like it. I could argue the X's look too large now but I won't
![image.png](https://files.reviewableusercontent.io/images/reviewable/17464863/tSlfDpmnGsWSjrdSGDpgfdaW/image.png)
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.scss` line 0 at r11](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-Nwn4xEK-cJsyspRSfnO:-Nwn4xEK-cJsyspRSfnP:b-jhpq0r) ([raw file](https://github.com/sillsdev/web-xforge/blob/1eabc1a8d713553e7914dec7f5dc5e37ce3af1d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.scss#L0)):*
Are any of these styles still needed as this component is hidden by `audio-container`?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.scss` line 63 at r11](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NwmZWu2CKDEjNQliD-b:-NwmZWu2CKDEjNQliD-c:bd4yyss) ([raw file](https://github.com/sillsdev/web-xforge/blob/1eabc1a8d713553e7914dec7f5dc5e37ce3af1d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.scss#L63)):*
> ```SCSS
> 
> .stop-recording {
>   color: red;
> ```

Change this to the new `$red` variable
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/text-and-audio/text-and-audio.component.scss` line 32 at r11](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NwmynUTBRG2HahUKqAX:-NwmynUTBRG2HahUKqAY:b-34owu3) ([raw file](https://github.com/sillsdev/web-xforge/blob/1eabc1a8d713553e7914dec7f5dc5e37ce3af1d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/text-and-audio/text-and-audio.component.scss#L32)):*
> ```SCSS
>     border-color: rgba(0, 0, 0, 0.4);
>   }
>   .halfHeight {
> ```

Is this still used if uploadEnabled isn't used?

Actually, how many of these styles are still needed as this whole container is set to display none?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/text-and-audio/text-and-audio.component.ts` line 20 at r11](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NwmykPV8cxJ6cE27NfP:-NwmykPV8cxJ6cE27NfQ:b4o3121) ([raw file](https://github.com/sillsdev/web-xforge/blob/1eabc1a8d713553e7914dec7f5dc5e37ce3af1d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/text-and-audio/text-and-audio.component.ts#L20)):*
> ```XML
>   @Input() input?: { text?: string; audioUrl?: string };
>   @Input() textLabel: string = '';
>   @Input() uploadEnabled: boolean = false;
> ```

Is this still used?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/text-and-audio/text-and-audio.component.ts` line 32 at r11](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-Nwn-yQDDm9L6GZkB-Kx:-Nwn-yQE187Q6XGJd1HB:b9tjjbu) ([raw file](https://github.com/sillsdev/web-xforge/blob/1eabc1a8d713553e7914dec7f5dc5e37ce3af1d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/text-and-audio/text-and-audio.component.ts#L32)):*
> ```XML
>   ngOnInit(): void {
>     if (!this.input) {
>       this.input = {};
> ```

Can't this be set as the default?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/text-and-audio/text-and-audio.component.ts` line 75 at r11](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-Nwn0zgrAs4bERphKBM9:-Nwn0zgrAs4bERphKBMA:b4o3121) ([raw file](https://github.com/sillsdev/web-xforge/blob/1eabc1a8d713553e7914dec7f5dc5e37ce3af1d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/text-and-audio/text-and-audio.component.ts#L75)):*
> ```XML
>   }
> 
>   isAudioPlaying(): boolean {
> ```

Is this still used?


<!-- Sent from Reviewable.io -->

2024-05-02 06:22 UTC, josephmyers reviewed
Because, as far as I know, that would completely destroy the current "attachments + actions" row. The only way I could think of to have audio shown on the same line as those other items, while residing in the text-and-audio template, was to use hard-coded negative margins, based on the exact height of the attachments and buttons. I obviously didn't want to do that. Maybe you know of a trick that isn't so hacky?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-:-NwrV-vmErkirNTQiXX_:beofxet)* status: 27 of 30 files reviewed, 9 unresolved discussions (waiting on @Nateowami and @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html` line 88 at r11](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-Nwn1VC776NIT__55PtN:-NwrWPqdBnDiBwzLstXj:b-sb1xqi) ([raw file](https://github.com/sillsdev/web-xforge/blob/1eabc1a8d713553e7914dec7f5dc5e37ce3af1d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html#L88)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Would be nice if we could have one set of buttons and then show/hide what is in them rather than small/large screen. Doesn't need to hold this up as I know it can be fiddley.
</blockquote></details>

That's exactly what I had before Nathaniel made his comments. I don't know how to make the two into one, given how different they are.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html` line 112 at r11](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NwmXpsS0Uyk8PqjgzXp:-NwrWmW15XU8Vvx0y95r:b-mv70vt) ([raw file](https://github.com/sillsdev/web-xforge/blob/1eabc1a8d713553e7914dec7f5dc5e37ce3af1d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html#L112)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Can the ID be different as we shouldn't use the same ID multiple times in the DOM. Is it even needed?
</blockquote></details>

It's used in the tests. I don't like it either, but it's how I know to get two different buttons to be mutually exclusive. They are effectively the same button.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss` line 56 at r9](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NwNhwel0zabf9iIhFIv:-NwrY1-a3Z_1YOaku_aw:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/97cbdea961f7595dd0d4c861e36fb6b71e2af72e/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss#L56)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

A little picky from me. There is a row gap on the form of 2px. There is a margin between the buttons of 4px
![image.png](https://files.reviewableusercontent.io/images/reviewable/17464863/kjskSlCXVUcVF7OvP0MAoTDC/image.png)
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.scss` line  at r11](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-Nwn4xEK-cJsyspRSfnO:-NwrYbvH7L-SYnMzbi-3:b-pmf6dh) ([raw file](https://github.com/sillsdev/web-xforge/blob/1eabc1a8d713553e7914dec7f5dc5e37ce3af1d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.scss#L)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Are any of these styles still needed as this component is hidden by `audio-container`?
</blockquote></details>

Do you want me to remove them or comment them out?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.scss` line 63 at r11](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NwmZWu2CKDEjNQliD-b:-NwrZ-Dn9Ij9woRWoqs1:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/1eabc1a8d713553e7914dec7f5dc5e37ce3af1d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/question-dialog/question-dialog.component.scss#L63)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Change this to the new `$red` variable
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/text-and-audio/text-and-audio.component.scss` line 32 at r11](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NwmynUTBRG2HahUKqAX:-NwrZfes16nPRHeHU0AY:b2rstjr) ([raw file](https://github.com/sillsdev/web-xforge/blob/1eabc1a8d713553e7914dec7f5dc5e37ce3af1d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/text-and-audio/text-and-audio.component.scss#L32)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Is this still used if uploadEnabled isn't used?

Actually, how many of these styles are still needed as this whole container is set to display none?
</blockquote></details>

If we're agreeing that ever enabling this display would require another aesthetics overhaul (since we don't like the large-button implementation), then yes, we can safely remove these styles. Otherwise they're valuable. Future development could simply make the `display: none;` conditional, and we could use either style. Also, if you want me to do that now, then I can.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/text-and-audio/text-and-audio.component.ts` line 20 at r11](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NwmykPV8cxJ6cE27NfP:-NwrZ52eEzA0weIHJxtj:bs3emy6) ([raw file](https://github.com/sillsdev/web-xforge/blob/1eabc1a8d713553e7914dec7f5dc5e37ce3af1d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/text-and-audio/text-and-audio.component.ts#L20)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Is this still used?
</blockquote></details>

Nope. Want me to rip it out or leave it?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/text-and-audio/text-and-audio.component.ts` line 32 at r11](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-Nwn-yQDDm9L6GZkB-Kx:-NwrwF_n0XIVV022l10D:b1296do) ([raw file](https://github.com/sillsdev/web-xforge/blob/1eabc1a8d713553e7914dec7f5dc5e37ce3af1d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/text-and-audio/text-and-audio.component.ts#L32)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Can't this be set as the default?
</blockquote></details>

I had tried this initially, but surprisingly no. My best guess was that if the input was not present as an attribute, it was overwriting the default. It causes an exception on init.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/text-and-audio/text-and-audio.component.ts` line 75 at r11](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-Nwn0zgrAs4bERphKBM9:-NwrweEH7N3_7iD7hu9U:bo8d7lz) ([raw file](https://github.com/sillsdev/web-xforge/blob/1eabc1a8d713553e7914dec7f5dc5e37ce3af1d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/text-and-audio/text-and-audio.component.ts#L75)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Is this still used?
</blockquote></details>

Doesn't appear to be. I don't think it's necessarily hurting anything (I think it's still accurate), but I can remove it.


<!-- Sent from Reviewable.io -->

2024-05-02 23:32 UTC, nigel-wells requested changes
Is it possible to implement in a similar way we do with the audio component where it is defined in memory in the class and not in the DOM?  I haven't thought this through at all. We could look into it as a future PR as what we have here is a great improvement and the longer we take to merge this in the harder it will be to maintain it.

> Reviewed 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-:-NwvcYxCBHCQgmKGPUSJ:biku2ub)* status: all files reviewed, 6 unresolved discussions (waiting on @josephmyers and @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html` line 88 at r11](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-Nwn1VC776NIT__55PtN:-NwvddpK5QVW9J4fYBDN:b-8pb2no) ([raw file](https://github.com/sillsdev/web-xforge/blob/1eabc1a8d713553e7914dec7f5dc5e37ce3af1d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html#L88)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

That's exactly what I had before Nathaniel made his comments. I don't know how to make the two into one, given how different they are.
</blockquote></details>

I answered this below - not sure why I review from the bottom up lol
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html` line 112 at r11](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NwmXpsS0Uyk8PqjgzXp:-Nwvd1mT9sb_RUNQAvvd:bbh568j) ([raw file](https://github.com/sillsdev/web-xforge/blob/1eabc1a8d713553e7914dec7f5dc5e37ce3af1d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html#L112)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

It's used in the tests. I don't like it either, but it's how I know to get two different buttons to be mutually exclusive. They are effectively the same button.
</blockquote></details>

How does the test know which specific button to use though when referencing the ID? It must work in this instance as the buttons do the same thing. If you wanted to go back to a single button then you could just use similar CSS rules to hide the appropriate icons and/or text on the within the button.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.scss` line  at r11](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-Nwn4xEK-cJsyspRSfnO:-NwvdW9W8HtRmyCgAMfm:bmp6xs9) ([raw file](https://github.com/sillsdev/web-xforge/blob/1eabc1a8d713553e7914dec7f5dc5e37ce3af1d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.scss#L)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Do you want me to remove them or comment them out?
</blockquote></details>

As per other comments, let's remove anything not actually in use.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/text-and-audio/text-and-audio.component.scss` line 32 at r11](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NwmynUTBRG2HahUKqAX:-Nwvc0m01vxWay0XYgcW:bcs8be1) ([raw file](https://github.com/sillsdev/web-xforge/blob/1eabc1a8d713553e7914dec7f5dc5e37ce3af1d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/text-and-audio/text-and-audio.component.scss#L32)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

If we're agreeing that ever enabling this display would require another aesthetics overhaul (since we don't like the large-button implementation), then yes, we can safely remove these styles. Otherwise they're valuable. Future development could simply make the `display: none;` conditional, and we could use either style. Also, if you want me to do that now, then I can.
</blockquote></details>

If we remove `uploadEnabled` then we should remove anything related to that as well. My question here does tie in a bit to my overall question about having this hidden element.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/text-and-audio/text-and-audio.component.ts` line 20 at r11](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NwmykPV8cxJ6cE27NfP:-NwvcBVN36tEA71DP2T_:b-hrr4d5) ([raw file](https://github.com/sillsdev/web-xforge/blob/1eabc1a8d713553e7914dec7f5dc5e37ce3af1d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/text-and-audio/text-and-audio.component.ts#L20)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Nope. Want me to rip it out or leave it?
</blockquote></details>

Let's get rid of anything no longer being used by anything. We can always look back in git to restore anything in the future if we did decide to support uploading audio files again.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/text-and-audio/text-and-audio.component.ts` line 75 at r11](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-Nwn0zgrAs4bERphKBM9:-Nwvb_HF6fKW4xxQgmIE:baxsn67) ([raw file](https://github.com/sillsdev/web-xforge/blob/1eabc1a8d713553e7914dec7f5dc5e37ce3af1d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/text-and-audio/text-and-audio.component.ts#L75)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Doesn't appear to be. I don't think it's necessarily hurting anything (I think it's still accurate), but I can remove it.
</blockquote></details>

Let's remove it - keep things clean.


<!-- Sent from Reviewable.io -->

2024-05-06 05:14 UTC, josephmyers reviewed
I'm not sure quite what you're getting at. I think the primary function of text-and-audio is the form validation via the ControlValueAccessor. Is it possible/advisable to extract all that up into the model level?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-:-NxAg_1584-fxVELdz-H:by0g9m5)* status: 21 of 30 files reviewed, 5 unresolved discussions (waiting on @Nateowami and @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html` line 88 at r11](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-Nwn1VC776NIT__55PtN:-NxBI-TJ06d62Iyx0Urj:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/1eabc1a8d713553e7914dec7f5dc5e37ce3af1d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html#L88)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

I answered this below - not sure why I review from the bottom up lol
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html` line 112 at r11](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NwmXpsS0Uyk8PqjgzXp:-NxAyVWqCWhYGqs3UFfc:b-sdkesg) ([raw file](https://github.com/sillsdev/web-xforge/blob/1eabc1a8d713553e7914dec7f5dc5e37ce3af1d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html#L112)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

How does the test know which specific button to use though when referencing the ID? It must work in this instance as the buttons do the same thing. If you wanted to go back to a single button then you could just use similar CSS rules to hide the appropriate icons and/or text on the within the button.
</blockquote></details>

Not really, unless you know how to apply the selector attributes from CSS, e.g. mat-icon-button. I've managed to get it working, but I wouldn't say it's pretty. I'm not confident that duplicating the components here is that much worse than complicating the unified ones. However, I do like the improvement made to the DOM.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.scss` line  at r11](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-Nwn4xEK-cJsyspRSfnO:-NxAq2ONCGvrj2lyKnJ6:b-6y2q92) ([raw file](https://github.com/sillsdev/web-xforge/blob/1eabc1a8d713553e7914dec7f5dc5e37ce3af1d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.scss#L)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

As per other comments, let's remove anything not actually in use.
</blockquote></details>

Done. This class still needs to be a component in order to take advantage of ControlValueAccessor.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/text-and-audio/text-and-audio.component.scss` line 32 at r11](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NwmynUTBRG2HahUKqAX:-NxAmjb227HaJTTNEGlD:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/1eabc1a8d713553e7914dec7f5dc5e37ce3af1d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/text-and-audio/text-and-audio.component.scss#L32)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

If we remove `uploadEnabled` then we should remove anything related to that as well. My question here does tie in a bit to my overall question about having this hidden element.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/text-and-audio/text-and-audio.component.ts` line 20 at r11](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NwmykPV8cxJ6cE27NfP:-NxAlkAdCDJ9zbmnT7zz:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/1eabc1a8d713553e7914dec7f5dc5e37ce3af1d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/text-and-audio/text-and-audio.component.ts#L20)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Let's get rid of anything no longer being used by anything. We can always look back in git to restore anything in the future if we did decide to support uploading audio files again.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/text-and-audio/text-and-audio.component.ts` line 75 at r11](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-Nwn0zgrAs4bERphKBM9:-NxAlkfXDmRTIKqQKnjf:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/1eabc1a8d713553e7914dec7f5dc5e37ce3af1d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/text-and-audio/text-and-audio.component.ts#L75)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Let's remove it - keep things clean.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-07 01:38 UTC, nigel-wells approved these changes
I think we should merge this in and then consider other options. One option might be an @input of another button which would allow the template to work correctly while keeping the logic for the button (verse attachment) separated - I think that could work?

> Reviewed 9 of 9 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-:-NxFgPqD727M_X2AAyU3:bvvl067)* status: all files reviewed, 2 unresolved discussions (waiting on @josephmyers and @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html` line 112 at r11](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NwmXpsS0Uyk8PqjgzXp:-NxFdirJCEkMVvjxTA4y:bg9guvc) ([raw file](https://github.com/sillsdev/web-xforge/blob/1eabc1a8d713553e7914dec7f5dc5e37ce3af1d8/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html#L112)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Not really, unless you know how to apply the selector attributes from CSS, e.g. mat-icon-button. I've managed to get it working, but I wouldn't say it's pretty. I'm not confident that duplicating the components here is that much worse than complicating the unified ones. However, I do like the improvement made to the DOM.
</blockquote></details>

I like the cleaner DOM and now only having a single button to deal with
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss` line 75 at r13](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NxFfB9DB0wu6ODMKj7_:-NxFfB9GDxqYmnYzlD47:b-5cfzxp) ([raw file](https://github.com/sillsdev/web-xforge/blob/4bfe071274a521596871fdb83b78aa403f0a8461/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss#L75)):*
> ```SCSS
>     }
>     .mat-icon-button {
>       ::ng-deep .mat-button-focus-overlay {
> ```

Why the need to do this?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts` line 24 at r13](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NxFeW1O14EHonDG1FGq:-NxFeW1O14EHonDG1FGr:b7yzzri) ([raw file](https://github.com/sillsdev/web-xforge/blob/4bfe071274a521596871fdb83b78aa403f0a8461/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts#L24)):*
> ```XML
>   Breakpoint,
>   MediaBreakpointService
> } from '../../../../xforge-common/media-breakpoints/media-breakpoint.service';
> ```

nit can remove all the `../../../../`


<!-- Sent from Reviewable.io -->

2024-05-07 01:46 UTC, nigel-wells commented
@josephmyers can you add some acceptance tests and then feel free to move over to the test column in Jira

2024-05-07 03:43 UTC, josephmyers reviewed
Done. I think you're suggesting we supply a reference to the (external) audio button to the template, but we should just do a call to pursue further, if you'd like. You've piqued my curiosity.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-:-NxG3rnXBweB8A-4Y2vs:b6x3wmb)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami and @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss` line 75 at r13](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NxFfB9DB0wu6ODMKj7_:-NxG6toW8C9azkZVfiLm:b-6jfhst) ([raw file](https://github.com/sillsdev/web-xforge/blob/4125575ac525ad8c6e7bd797d0951649d62568d1/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.scss#L75)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Why the need to do this?
</blockquote></details>

Because the mat-button attribute gets applied to both states, the mat-icon-button gets hover functionality applied to it. This rule suppresses the hover behavior. And yes, the mat-button is needed for both. There's some difference to Angular between the custom attribute and applying the class with [class], where not all "icon" functionality is present if you just use the [class].
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts` line 24 at r13](https://reviewable.io/reviews/sillsdev/web-xforge/2287#-NxFeW1O14EHonDG1FGq:-NxG8Hg4-mwFxEKIheXV:bnputky) ([raw file](https://github.com/sillsdev/web-xforge/blob/4125575ac525ad8c6e7bd797d0951649d62568d1/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts#L24)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

nit can remove all the `../../../../`
</blockquote></details>

Done. Thanks


<!-- Sent from Reviewable.io -->

2024-05-16 14:32 UTC, merged