SF-2371 Update from Material legacy form related controls
sillsdev/web-xforge pull request #2296
Opened 2024-01-16 03:46 UTC by nigel-wells

* Upgrade material legacy select, form, input, option, autocomplete
* Removed ellipsis from role select cell in system administrator table

This PR upgrades `mat-select`, `mat-option`, `mat-form-field` and `mat-autocomplete` from legacy to the Angular Material mdc version. Used ng generate @angular/material:mdc-migration as a starting point.

I left most style changes as per the new version of material except where we intentionally changed the styling i.e. to make it denser.

Some styles were no longer required as they are part of the latest version.

2024-01-18 21:24 UTC, RaymondLuong3 requested changes
Nice work! I have a couple minor comments, but then it is good to go.

> Reviewed 30 of 30 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2296#-:-NoTSR0mBoeRU-sJ4Or4:b-oalnj4)* status: all files reviewed, 5 unresolved discussions (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.scss` line 77 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2296#-NoTKgDr9dTD8Tm4do8b:-NoTKgDr9dTD8Tm4do8c:b-qvdejl) ([raw file](https://github.com/sillsdev/web-xforge/blob/5c594f7ccf45102b0199265427911bd718e50a93/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.scss#L77)):*
> ```SCSS
> mat-select.book-select-menu ::ng-deep {
>   .mat-mdc-select-arrow-wrapper {
>     margin-right: 5px;
> ```

You will want to do `margin: 0 5px` to handle the dialog in rtl mode.



_Code quote:_
```SCSS
    margin-right: 5px;
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.scss` line 106 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2296#-NoTORrcEI73LoWJk3nO:-NoTORrcEI73LoWJk3nP:bxmup7e) ([raw file](https://github.com/sillsdev/web-xforge/blob/5c594f7ccf45102b0199265427911bd718e50a93/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.scss#L106)):*
> ```SCSS
>     display: flex;
>     align-items: center;
>     mat-form-field:not(.mdc-text-field--textarea) {
> ```

What does the `not(.mdc-text-field` part do?



_Code quote:_
```SCSS
    mat-form-field:not(.mdc-text-field--textarea) {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.scss` line 116 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2296#-NoTOF3L-wb70uImhaW1:-NoTOF3L-wb70uImhaW2:bh28lf) ([raw file](https://github.com/sillsdev/web-xforge/blob/5c594f7ccf45102b0199265427911bd718e50a93/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.scss#L116)):*
> ```SCSS
>       .mat-mdc-text-field-wrapper {
>         div.mat-mdc-form-field-infix {
>           padding: 10px 0;
> ```

It looks like the padding is 16px without this. The comment says it makes it denser, but I don't notice an obvious difference.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.scss` line 132 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2296#-NoTPxqD6uz8SVuTnncg:-NoTPxqD6uz8SVuTnnch:b-f6taj9) ([raw file](https://github.com/sillsdev/web-xforge/blob/5c594f7ccf45102b0199265427911bd718e50a93/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.scss#L132)):*
> ```SCSS
> 
>     label.mat-mdc-floating-label:not(.mdc-floating-label--float-above) {
>       transform: translateY(-100%);
> ```

Nice little adjustment. I'm a fan of trying to stick with the look of the control to the original if it means we do not have to maintain little adjustments like this. Is there a good reason to make the component more narrow than it needs to be?



_Code quote:_
```SCSS
      transform: translateY(-100%);
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-chapter-chooser/book-chapter-chooser.component.scss` line 13 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2296#-NoTS579DYMHZ3zZkq4P:-NoTS579DYMHZ3zZkq4Q:b-e3gy71) ([raw file](https://github.com/sillsdev/web-xforge/blob/5c594f7ccf45102b0199265427911bd718e50a93/src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-chapter-chooser/book-chapter-chooser.component.scss#L13)):*
> ```SCSS
>   .mat-mdc-text-field-wrapper {
>     border-top-right-radius: 0;
>     border-bottom-right-radius: 0;
> ```

This looks like it does not have an effect since `.mdc-notched-outline__trailing` and `.mdc-noted-outline__leading` are enough to get the book and chapter selects flush against each other. So this can be removed?



_Code quote:_
```SCSS
  .mat-mdc-text-field-wrapper {
    border-top-right-radius: 0;
    border-bottom-right-radius: 0;
```


<!-- Sent from Reviewable.io -->

2024-01-19 04:03 UTC, nigel-wells reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2296)* status: 28 of 30 files reviewed, 5 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.scss` line 77 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2296#-NoTKgDr9dTD8Tm4do8b:-NoUj9uGDutkBPy6tLPS:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/5c594f7ccf45102b0199265427911bd718e50a93/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.scss#L77)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

You will want to do `margin: 0 5px` to handle the dialog in rtl mode.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.scss` line 106 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2296#-NoTORrcEI73LoWJk3nO:-NoUqq0j70wihDkAqIsj:bgsf14d) ([raw file](https://github.com/sillsdev/web-xforge/blob/5c594f7ccf45102b0199265427911bd718e50a93/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.scss#L106)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

What does the `not(.mdc-text-field` part do?
</blockquote></details>

This was to make the rule more specific so as to overwrite the other material rules - otherwise I would have to use an `!important`.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.scss` line 116 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2296#-NoTOF3L-wb70uImhaW1:-NoUrBT27kS5XzkNfwcy:b-efjc4x) ([raw file](https://github.com/sillsdev/web-xforge/blob/5c594f7ccf45102b0199265427911bd718e50a93/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.scss#L116)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

It looks like the padding is 16px without this. The comment says it makes it denser, but I don't notice an obvious difference.
</blockquote></details>

I'd prefer to use defaults.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.scss` line 132 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2296#-NoTPxqD6uz8SVuTnncg:-NoUrVaX0Z1GcljAHCJZ:bowh93z) ([raw file](https://github.com/sillsdev/web-xforge/blob/5c594f7ccf45102b0199265427911bd718e50a93/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.scss#L132)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Nice little adjustment. I'm a fan of trying to stick with the look of the control to the original if it means we do not have to maintain little adjustments like this. Is there a good reason to make the component more narrow than it needs to be?
</blockquote></details>

I'm not sure why it was made dense - possibly to make it fit better on mobile? I'd prefer to use the defaults for material as they put all the research into UX/UI across different form factors so why change it? For the purpose of this PR, let's keep it what it is.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-chapter-chooser/book-chapter-chooser.component.scss` line 13 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2296#-NoTS579DYMHZ3zZkq4P:-NoUsXbP6Bqq_HVA2L1I:bj5phet) ([raw file](https://github.com/sillsdev/web-xforge/blob/5c594f7ccf45102b0199265427911bd718e50a93/src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-chapter-chooser/book-chapter-chooser.component.scss#L13)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This looks like it does not have an effect since `.mdc-notched-outline__trailing` and `.mdc-noted-outline__leading` are enough to get the book and chapter selects flush against each other. So this can be removed?
</blockquote></details>

You're right! The initially did something but the rule created further down (along with other tweaks) meant this isn't needed any more. Removed.


<!-- Sent from Reviewable.io -->

2024-01-19 15:14 UTC, RaymondLuong3 approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2296)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.scss` line 77 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2296#-NoTKgDr9dTD8Tm4do8b:-NoXGoVn4TVv_crv5Rud:b53tqq4) ([raw file](https://github.com/sillsdev/web-xforge/blob/5c594f7ccf45102b0199265427911bd718e50a93/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.scss#L77)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

That works too.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.scss` line 106 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2296#-NoTORrcEI73LoWJk3nO:-NoXGxr72By1qFa0OYM-:b-qq4aq7) ([raw file](https://github.com/sillsdev/web-xforge/blob/5c594f7ccf45102b0199265427911bd718e50a93/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.scss#L106)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

This was to make the rule more specific so as to overwrite the other material rules - otherwise I would have to use an `!important`.
</blockquote></details>

Thanks. That was my thought but wanted to hear from you.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.scss` line 132 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2296#-NoTPxqD6uz8SVuTnncg:-NoXH9DQ0-Cmx2wUWWNF:b-piwvsr) ([raw file](https://github.com/sillsdev/web-xforge/blob/5c594f7ccf45102b0199265427911bd718e50a93/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.scss#L132)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

I'm not sure why it was made dense - possibly to make it fit better on mobile? I'd prefer to use the defaults for material as they put all the research into UX/UI across different form factors so why change it? For the purpose of this PR, let's keep it what it is.
</blockquote></details>

Sure, it does look sleek with the narrowed down text input.


<!-- Sent from Reviewable.io -->

2024-01-24 00:07 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2296)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-chapter-chooser/book-chapter-chooser.component.scss` line 18 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2296#-Nosm3FW9OA_HAvxK1LW:-Nosm3FW9OA_HAvxK1LX:b-qi29es) ([raw file](https://github.com/sillsdev/web-xforge/blob/15a3519cdace0dca20616559e12c6fb08690dc0a/src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-chapter-chooser/book-chapter-chooser.component.scss#L18)):*
> ```SCSS
>     padding-top: 7px;
>     padding-bottom: 5px;
>     width: initial;
> ```

How about
``` suggestion
+    min-width: 25px; // prevent weird transparent gap between content and scrollbar in Chromium
```


<!-- Sent from Reviewable.io -->

2024-01-24 00:09 UTC, Nateowami commented on src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-chapter-chooser/book-chapter-chooser.component.scss
>      width: initial;
...and Reviewable did not make my last comment a suggestion like I wanted. Here's try 2.

```suggestion
    width: initial;
    min-width: 25px; // prevent weird transparent gap between content and scrollbar in Chromium
```

2024-01-24 01:53 UTC, nigel-wells reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2296)* status: all files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-chapter-chooser/book-chapter-chooser.component.scss` line 18 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2296#-Nosm3FW9OA_HAvxK1LW:-Not97fC7UNrefGBWgTz:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/15a3519cdace0dca20616559e12c6fb08690dc0a/src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-chapter-chooser/book-chapter-chooser.component.scss#L18)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

How about
``` suggestion
+    min-width: 25px; // prevent weird transparent gap between content and scrollbar in Chromium
```
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-chapter-chooser/book-chapter-chooser.component.scss` line 18 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2296#gh-1464138285:-Not982HEwFWmTvE2_II:b-sn1c4v) ([raw file](https://github.com/sillsdev/web-xforge/blob/15a3519cdace0dca20616559e12c6fb08690dc0a/src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-chapter-chooser/book-chapter-chooser.component.scss#L18)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

...and Reviewable did not make my last comment a suggestion like I wanted. Here's try 2.

```suggestion
    width: initial;
    min-width: 25px; // prevent weird transparent gap between content and scrollbar in Chromium
```
</blockquote></details>

Yeah, that can work. I guess making it dense is not its intended support use case so it may not get an official fix anytime soon.


<!-- Sent from Reviewable.io -->

2024-01-24 22:04 UTC, RaymondLuong3 approved these changes
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2296)* status: all files reviewed, 2 unresolved discussions (waiting on @Nateowami)



<!-- Sent from Reviewable.io -->

2024-01-25 16:41 UTC, merged