SF-2355 Translation Suggestions don't align well in RTL
sillsdev/web-xforge pull request #2312
Opened 2024-01-29 02:40 UTC by nigel-wells

* Give direction preference based on text setting for RTL
* Flip direction if suggestions fit better in the other direction
* Force a CSS word break if needed
* Reset left/right/top properties when no selection

2024-01-30 05:37 UTC, josephmyers requested changes
I like that you were able to simplify this. Good job. I only noticed a couple minor issues.

The first is in RTL, when your cursor is at the far left of the editor. I would expect the suggestions to appear butted up against the left bounds, but it looks like if it can't be shown fully to the left, it reverts to LTR behavior. Here's the screenshot:
![image.png](https://files.reviewableusercontent.io/images/reviewable/43733878/L_5mKcxIrkEbPD_3dTk2pM8Z/image.png)

What do you think about this?

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2312#-:-NpNqgzpEyu4UmAc7lc6:b-vxpzcu)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.scss` line 68 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2312#-NpNU7Gv6uekrtzD2l6h:-NpNU7Gv6uekrtzD2l6i:b-l3ygy2) ([raw file](https://github.com/sillsdev/web-xforge/blob/768422ad0c345b5c855d425cc469d0817700ca54/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.scss#L68)):*
> ```SCSS
>   align-items: baseline;
>   justify-content: space-between;
>   word-break: break-all;
> ```

This causes us to split individual words apart into pieces of words. It's a little weird to me. You felt this was necessary?


<!-- Sent from Reviewable.io -->

2024-01-30 05:42 UTC, josephmyers commented
For the second comment, compare these screenshots:

With setting ---- Without setting

<img src="https://github.com/sillsdev/web-xforge/assets/43733878/bfc8324f-3355-4d10-8339-1aac4d0b5139" height="334" align="absmiddle" alt="Reviewable"/>

<img src="https://github.com/sillsdev/web-xforge/assets/43733878/2ec3c24d-831f-44ee-9734-2c3fd8ae4a57" height="334" align="absmiddle" alt="Reviewable"/>

2024-02-01 01:30 UTC, nigel-wells reviewed
Regarding RTL, I figured if the position was close to the left (or right in LTR) and there was more room in the other direction then show it in the other direction. This feels and looks much better than squashing it into a small space. Tooltips often respond similar when they get too close to the edge and flip to the other side. Does it look odd to you?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2312#-:-NpXGxAgAwwXQSpb7VKO:b-ug8q6p)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.scss` line 68 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2312#-NpNU7Gv6uekrtzD2l6h:-NpXGE9z5flbOYoaWuGE:b-l7hu1j) ([raw file](https://github.com/sillsdev/web-xforge/blob/768422ad0c345b5c855d425cc469d0817700ca54/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.scss#L68)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

This causes us to split individual words apart into pieces of words. It's a little weird to me. You felt this was necessary?
</blockquote></details>

Thanks for raising - I was probably to hasty to add this and it only resolved one ridiculous case I encountered. Basically I added a really long word to see what would happen when it reached the edge of the screen. It carried on and broke out of the container. This one style was added to avoid that but I didn't test anymore beyond that. The case I was testing was probably quite pointless as well to be honest - I'll just remove it.


<!-- Sent from Reviewable.io -->

2024-02-01 08:32 UTC, josephmyers requested changes
It looks a little odd to me, but not too bad. It used to squash until it reached a min width, after which it would shift slightly to prevent it running off. It worked pretty well in practice. The code you removed of course as what controlled this. Here's a video of the oddness. It doesn't look horrible, just a little jarring. But let me know your thoughts
[Recording 2024-02-01 135846.mp4](https://files.reviewableusercontent.io/images/reviewable/43733878/o_e1MrwNgptunTWxUfB65Xtm/Recording%202024-02-01%20135846.mp4)

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2312#-:-NpYkXH625NzbeTl5SYM:bxyk5sf)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.scss` line 68 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2312#-NpNU7Gv6uekrtzD2l6h:-NpYjq-RCKYsDL-zHzpd:b-bbn0aq) ([raw file](https://github.com/sillsdev/web-xforge/blob/768422ad0c345b5c855d425cc469d0817700ca54/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.scss#L68)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Thanks for raising - I was probably to hasty to add this and it only resolved one ridiculous case I encountered. Basically I added a really long word to see what would happen when it reached the edge of the screen. It carried on and broke out of the container. This one style was added to avoid that but I didn't test anymore beyond that. The case I was testing was probably quite pointless as well to be honest - I'll just remove it.
</blockquote></details>

Right. Test complained one time about this, but the only way they could reproduce it was to manually remove all the spaces from a suggestion. All the way at the edge. It was pretty ridiculous, and we have higher priority things to do.


<!-- Sent from Reviewable.io -->

2024-02-02 02:26 UTC, nigel-wells reviewed
Thanks for the video - it is behaving as intended. We could look to squash it in but I do feel giving it more breathing room if flipping it is better UX. Happy to get thoughts from others if you want to post the video in slack.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2312#-:-NpbcLwV32MajZlGcaer:bmt5x0q)* status: all files reviewed, 1 unresolved discussion (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.scss` line 68 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2312#-NpNU7Gv6uekrtzD2l6h:-NpbchinEIMzsOLdzsYk:b-aq1o6x) ([raw file](https://github.com/sillsdev/web-xforge/blob/768422ad0c345b5c855d425cc469d0817700ca54/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/suggestions.component.scss#L68)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Right. Test complained one time about this, but the only way they could reproduce it was to manually remove all the spaces from a suggestion. All the way at the edge. It was pretty ridiculous, and we have higher priority things to do.
</blockquote></details>

I agree. If we hear about real world scenarios then we can create a ticket specific to that.


<!-- Sent from Reviewable.io -->

2024-02-05 03:19 UTC, josephmyers approved these changes
No, let's push it through. If anyone complains, we can change it back

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2312#-:-NprGjbs0ozHZW5lNdfq:b-jyhsrc)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nigel-wells)



<!-- Sent from Reviewable.io -->

2024-02-07 16:56 UTC, merged