SF-2439 Implement tabbed editor
sillsdev/web-xforge pull request #2332
Opened 2024-02-09 23:15 UTC by siltomato

This PR creates a tabbed experience for the source and target editors on the "Edit & Review" page.  The custom tab group component is listed in Storybook under "Shared > Tab Group".

**Tabbed editor can:**
- Add tab
  - Menu is shown with draft and history options.
- Remove tab
- If tab headers exceed tab group width, tabs can scroll with buttons or mouse wheel.
- Tab navigation and display should handle RTL environment.

**Currently available tabs are:**
- History
  - History chooser moved to history tab.
  - Multiple histories tabs with different histories are possible.
- Draft
  - Draft displays draft text interleaved with existing text.
  - Only one draft tab is allowed.
  - Applying draft is still done via existing draft preview page.  This will be changed in a future PR.

2024-02-15 08:33 UTC, josephmyers commented
@pmachapman, you should take a look at the history portion of these changes, since you just worked on this

2024-02-16 05:57 UTC, josephmyers requested changes
Wow, this has been epic. Loving the look of things so far. It's been a lot to review, though, so cut me a little slack as you're looking at my comments, many of which have been made with just a basic understanding. I think we get less benefit from picky comments, but larger architectural comments are harder to make. I'm more concerned with the latter. Did you by any chance make a design doc for any of this? Thanks

General comments:
1. As listed in the JIRA task, persisting which tabs are open is part of this task. Were you wanting to split that off, due to task size? I'm good with that, but we do need that feature soon.
2. ChangedAfterChecked error from the history tab if network drops
3. If you're offline and you open the Auto Draft button, you get a red notice error and the loading spins forever. Is this intended?

> Reviewed 71 of 71 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-:-NqeZdCv0IEmbXJu34ZI:bj4katt)* status: all files reviewed, 24 unresolved discussions (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/sf-tabs.types.ts` line 4 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-NqakhbC06K3oazYXNyb:-NqakhbC06K3oazYXNyc:b-3msrdb) ([raw file](https://github.com/sillsdev/web-xforge/blob/acc926bbe6f3aadd619cae09f25b0f5e97463792/src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/sf-tabs.types.ts#L4)):*
> ```XML
>   Click = 'click',
>   Close = 'close',
>   Select = 'select'
> ```

Why do we need to differentiate between Select and Click? Are there other ways to select a tab? Do we need to know the difference?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group.component.html` line 12 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-NqaqEeb4gXQUSEx1F_K:-NqaqEeb4gXQUSEx1F_L:bmtbd5s) ([raw file](https://github.com/sillsdev/web-xforge/blob/acc926bbe6f3aadd619cae09f25b0f5e97463792/src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group.component.html#L12)):*
> ```HTML
> ></app-tab-group-header>
> 
> <!-- TODO: Determine if there is any benefit to using mat-tab-group  -->
> ```

Unresolved todo here
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group.component.ts` line 14 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-Nqari0aDKtA1JftvkCB:-Nqari0aDKtA1JftvkCC:b-2j0irr) ([raw file](https://github.com/sillsdev/web-xforge/blob/acc926bbe6f3aadd619cae09f25b0f5e97463792/src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group.component.ts#L14)):*
> ```XML
>   @Input() selectedIndex = 0;
>   @Input() showAddTab = true;
>   @Input() showAddTabMenu = true;
> ```

This and the one above don't appear to be used/set externally. Do we need them? Is there a time when they shouldn't be able to add a tab? I couldn't think of one off the top of my head.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group-header/tab-group-header.component.html` line 1 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-NqkTh8y-G8o2Z9svw7z:-NqkTh8y-G8o2Z9svw8-:bnt7kut) ([raw file](https://github.com/sillsdev/web-xforge/blob/acc926bbe6f3aadd619cae09f25b0f5e97463792/src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group-header/tab-group-header.component.html#L1)):*
> ```HTML
> <app-tab-scroll-button
> ```

I'm not exactly sure where the guilty code is, or if it's even that big of an issue, but the date in the history tab header is affected by RTL, but only when opening a new tab. In other words, if tabs are open, and you change direction, the RTL language and direction remain. If you close and reopen, it uses the correct language and direction.

![image.png](https://files.reviewableusercontent.io/images/reviewable/43733878/AT1rggeqkr7Pgs-SAtq01YZX/image.png)
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group-header/tab-group-header.component.scss` line 53 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-NqkDGBYEzeXIdlrpv7O:-NqkDGBYEzeXIdlrpv7P:b-ducddu) ([raw file](https://github.com/sillsdev/web-xforge/blob/acc926bbe6f3aadd619cae09f25b0f5e97463792/src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group-header/tab-group-header.component.scss#L53)):*
> ```SCSS
>   display: flex;
>   align-items: flex-end;
>   gap: 0.2em;
> ```

This is preferential, but I'm not a huge fan of the gap. It seems inefficient with the space, and I think it looks better without. Can we remove it?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group-header/tab-group-header.component.spec.ts` line 6 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-NqaYpt863kZOcrt75lk:-NqaYpt863kZOcrt75ll:b-ijfrxj) ([raw file](https://github.com/sillsdev/web-xforge/blob/acc926bbe6f3aadd619cae09f25b0f5e97463792/src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group-header/tab-group-header.component.spec.ts#L6)):*
> ```XML
> import { TabGroupHeaderComponent } from './tab-group-header.component';
> 
> describe('TabGroupHeaderComponent', () => {
> ```

The component under test is pretty hefty, but these tests are slim. We should add more coverage, unless it's somewhere else
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group-header/tab-scroll-button/tab-scroll-button.component.html` line 1 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-NqkMexqA2TD014G2Bzo:-NqkMexqA2TD014G2Bzp:b-856lg2) ([raw file](https://github.com/sillsdev/web-xforge/blob/acc926bbe6f3aadd619cae09f25b0f5e97463792/src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group-header/tab-scroll-button/tab-scroll-button.component.html#L1)):*
> ```HTML
> <button
> ```

Not exactly sure how I broke this, but I had previously been resizing the window and then was adding and removing tabs (not stress testing):
![image.png](https://files.reviewableusercontent.io/images/reviewable/43733878/FVQFLMe4QLzpQLSCbulYvCy7/image.png)
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-header/tab-header.component.scss` line 71 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-NqkH33a2Al_WS8sAvFZ:-NqkH33bB9wiBelwjw-d:bfjku2k) ([raw file](https://github.com/sillsdev/web-xforge/blob/acc926bbe6f3aadd619cae09f25b0f5e97463792/src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-header/tab-header.component.scss#L71)):*
> ```SCSS
>   line-height: 1.5em;
> 
>   ::ng-deep > mat-icon {
> ```

I think we're slightly overusing icons in one place. Here's a screenshot:
![image.png](https://files.reviewableusercontent.io/images/reviewable/43733878/mVROM2vF_Kw17_oTfivxA2vM/image.png)

We're showing the history icon three times in a very small space, and it looks busy. I think we can get away without one or two of them. I'm on the fence about icons in each tab (maybe not all types need it), but I'm assuming we want to keep those. I think it's the history dropdown (not the code at this comment I'm making) that we don't really need. Can we try that?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-header/tab-header.component.scss` line 80 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-NqkGLOyDYYiQZXdXOhS:-NqkGLOyDYYiQZXdXOhT:bbg1hiu) ([raw file](https://github.com/sillsdev/web-xforge/blob/acc926bbe6f3aadd619cae09f25b0f5e97463792/src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-header/tab-header.component.scss#L80)):*
> ```SCSS
> // 'button' is needed to increase specificity for overriding hover text color
> button.close-button {
>   visibility: hidden;
> ```

I don't think hiding the close button by default is great. It looks odd unless they're hovering (because of the empty space), and it doesn't work well on mobile (not that that's our top priority).
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-men [...]

2024-02-18 21:30 UTC, pmachapman reviewed
Looks awesome!

I wonder if the history chooser component could be made to look more like a toolbar (either a different color, or a line at the bottom like my screenshot below), and have it float so is always visible when the user scrolls?

I think this will also help if we add other functions that require a form of tab-toolbar - I foresee the auto draft tab having buttons for download chapter, download book, apply draft to entire book, etc.

![image.png](https://files.reviewableusercontent.io/images/reviewable/8665431/j3zBQDQlDIwGfeapdmEDGscY/image.png)

Also, I noticed a bug where I had a Chapter History tab open for a book that has a source and a target, and navigated to a book which does not have a source, then all of my tabs closed. This didn't happen when navigating between books that have both a source and target.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-:-Nqy5eD10VTNlf8a35qz:bh60lmi)* status: all files reviewed, 26 unresolved discussions (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 236 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-Nqy3bo11LKOBq5Nv0QE:-Nqy3bo11LKOBq5Nv0QF:bryoigk) ([raw file](https://github.com/sillsdev/web-xforge/blob/acc926bbe6f3aadd619cae09f25b0f5e97463792/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L236)):*
> ```JSON
>   },
>   "history_chooser": {
>     "hide_diff": "Hide differences with previous version",
> ```

Given the change in contact for the dropdown to being inside the history tab, can we rename this to:
```
"hide_diff": "Hide differences from the latest version"
```



_Code quote:_
```JSON
"hide_diff": "Hide differences with previous version",
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 237 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-Nqy3soh-hnnVsAlW3jx:-Nqy3soh-hnnVsAlW3jy:bn0mpfj) ([raw file](https://github.com/sillsdev/web-xforge/blob/acc926bbe6f3aadd619cae09f25b0f5e97463792/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L237)):*
> ```JSON
>   "history_chooser": {
>     "hide_diff": "Hide differences with previous version",
>     "show_diff": "Show differences with previous version"
> ```

And rename this to:
```
"show_diff": "Show differences from the latest version"
```



_Code quote:_
```JSON
"show_diff": "Show differences with previous version"
```


<!-- Sent from Reviewable.io -->

2024-02-22 00:49 UTC, siltomato reviewed
Thank you both for taking the time to go through this!  Some issues are addressed in the tab reorder branch I'm working on now (SF-2528).  If that is the case, I'll mention it in the comment.

@pmachapman Good find on the tab clearing bug.  I think the cause is that the route change is causing the editor component to reload.  The component won't reload if it is just a route param change, but in the case of going from book-only path to book+chapter path, it counts as a route change.  Once we implement tab persistence, this problem should go away.  I added a `TODO` note regarding persistence in the 'populate' method.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-:-NqwsbBR3QwFNi2GdqW1:b52si2w)* status: 39 of 71 files reviewed, 26 unresolved discussions (waiting on @josephmyers and @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/sf-tabs.types.ts` line 4 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-NqakhbC06K3oazYXNyb:-Nqx03V35dmb8djT6JsQ:bfcp214) ([raw file](https://github.com/sillsdev/web-xforge/blob/acc926bbe6f3aadd619cae09f25b0f5e97463792/src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/sf-tabs.types.ts#L4)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Why do we need to differentiate between Select and Click? Are there other ways to select a tab? Do we need to know the difference?
</blockquote></details>

Yeah, good question.  My thinking was that a click could be interpreted differently depending on the button clicked.  However, now that the implementation has been fleshed out since `TabEventType` was created, I'm not sure the type is needed at all.  Removed `TabEventType`.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group.component.html` line 12 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-NqaqEeb4gXQUSEx1F_K:-NqwrQf73z1LW0DcVgFW:b-w58b2z) ([raw file](https://github.com/sillsdev/web-xforge/blob/acc926bbe6f3aadd619cae09f25b0f5e97463792/src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group.component.html#L12)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Unresolved todo here
</blockquote></details>

Addressed in SF-2528.  (mat-tab-group is removed)
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group.component.ts` line 14 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-Nqari0aDKtA1JftvkCB:-Nqx4WXoBDYycQy4VUrT:bwecfqg) ([raw file](https://github.com/sillsdev/web-xforge/blob/acc926bbe6f3aadd619cae09f25b0f5e97463792/src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group.component.ts#L14)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

This and the one above don't appear to be used/set externally. Do we need them? Is there a time when they shouldn't be able to add a tab? I couldn't think of one off the top of my head.
</blockquote></details>

Good question.  I was considering the possibility and leaving the option open that perhaps the add-tab button shows a blank tab with options instead of a menu.  Another possibly use might be that perhaps the add-tab menu or button isn't shown at all if offline.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group-header/tab-group-header.component.html` line 1 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-NqkTh8y-G8o2Z9svw7z:-Nr72RIA1wQRU6lSLHS4:b-6y0z2z) ([raw file](https://github.com/sillsdev/web-xforge/blob/acc926bbe6f3aadd619cae09f25b0f5e97463792/src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group-header/tab-group-header.component.html#L1)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

I'm not exactly sure where the guilty code is, or if it's even that big of an issue, but the date in the history tab header is affected by RTL, but only when opening a new tab. In other words, if tabs are open, and you change direction, the RTL language and direction remain. If you close and reopen, it uses the correct language and direction.

![image.png](https://files.reviewableusercontent.io/images/reviewable/43733878/AT1rggeqkr7Pgs-SAtq01YZX/image.png)
</blockquote></details>

Good catch.  The localization of tab headers is a problem currently, especially for changing locales.  I'm not sure the best way to handle this ATM.  Since this is a minor issue, I'll add a TODO, and this can be addressed in a later PR.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group-header/tab-group-header.component.scss` line 53 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-NqkDGBYEzeXIdlrpv7O:-Nqx6UDoB0o1jxNADS_Z:bw0tix4) ([raw file](https://github.com/sillsdev/web-xforge/blob/acc926bbe6f3aadd619cae09f25b0f5e97463792/src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group-header/tab-group-header.component.scss#L53)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

This is preferential, but I'm not a huge fan of the gap. It seems inefficient with the space, and I think it looks better without. Can we remove it?
</blockquote></details>

Ooh, interesting.  The space efficiency issue is a great point, but to me it looks better with some space.  That makes me wonder if we should perhaps make a list of such tweak suggestions to look at during a future team meeting once it is more feature complete.

For now, I reduced it to `0.1em` to tighten it up a bit but still leave some air.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group-header/tab-group-header.component.spec.ts` line 6 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-NqaYpt863kZOcrt75lk:-Nr8HkGWDRyM_nCqDFiQ:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/acc926bbe6f3aadd619cae09f25b0f5e97463792/src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group-header/tab-group-header.component.spec.ts#L6)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

The component under test is pretty hefty, but these tests are slim. We should add more coverage, unless it's somewhere else
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group-header/tab-scroll-button/tab-scroll-button.component.html` line 1 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-NqkMexqA2TD014G2Bzo:-Nqx8ic49n75RbSYDyLz:b-584hcn) ([raw file](https://github.com/sillsdev/web-xforge/blob/acc926bbe6f3aadd619cae09f25b0f5e97463792/src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group-header/tab-scroll-button/tab-scroll-button.component.html#L1)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Not exactly sure how I broke this, but I had previously been resizing the window and then was adding and removing tabs (not stress testing):
![image.png](https://files.reviewableusercontent.io/images/reviewable/43733878/FVQFLMe4QLzpQLSCbulYvCy7/image.png)
</blockquote></details>

Good find.  I haven't been able to reproduce this yet.  Maybe not a stopper, and we can create an issue if it creeps up again?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-header/tab-header.component.scss` line 71 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-NqkH33a2Al_WS8sAvFZ:-Nr8I8KH09uRWlUnnWsJ:b-xcoj4a) ([raw file](https://github.com/sillsdev/web-xforge/blob/acc926bbe6f3aadd619cae09f25b0f5e97463792/src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-header/tab-header.component.scss#L71)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

I think we're slightly overusing icons in one place. Here's a screenshot:
![image.png](https://files.reviewableusercontent.io/images/reviewable/43733878/mVROM2vF_Kw17_oTfivxA2vM/image.png)

We're showing the history  [...]

2024-02-22 09:43 UTC, josephmyers requested changes
The changes you've made so far really make this look slick. Great job!

I'm still seeing the two offline errors I mentioned as general comments above.

> Reviewed 31 of 32 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-:-NrFA_-kDzWmp3xFzkGe:bwhyt25)* status: all files reviewed, 8 unresolved discussions (waiting on @pmachapman and @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group.component.ts` line 14 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-Nqari0aDKtA1JftvkCB:-NrEweOw5_TPhcwYl1yb:b-dxjkk0) ([raw file](https://github.com/sillsdev/web-xforge/blob/acc926bbe6f3aadd619cae09f25b0f5e97463792/src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group.component.ts#L14)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Good question.  I was considering the possibility and leaving the option open that perhaps the add-tab button shows a blank tab with options instead of a menu.  Another possibly use might be that perhaps the add-tab menu or button isn't shown at all if offline.
</blockquote></details>

Ok, well, I think the way it turned out is really solid, and I see opening tabs as being desirable when offline. And given how simple these two would be to add later, can we go ahead and remove them for now? I follow YAGNI, when it makes sense.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group-header/tab-group-header.component.html` line 1 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-NqkTh8y-G8o2Z9svw7z:-NrExrhUC5veMz6SWgti:b-k6rpab) ([raw file](https://github.com/sillsdev/web-xforge/blob/acc926bbe6f3aadd619cae09f25b0f5e97463792/src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group-header/tab-group-header.component.html#L1)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Good catch.  The localization of tab headers is a problem currently, especially for changing locales.  I'm not sure the best way to handle this ATM.  Since this is a minor issue, I'll add a TODO, and this can be addressed in a later PR.
</blockquote></details>

Sounds good, thanks.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group-header/tab-group-header.component.ts` line 198 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-NrEyiyM6TGrcHyoS4f9:-NrEyiyM6TGrcHyoS4fA:b-vt478j) ([raw file](https://github.com/sillsdev/web-xforge/blob/9c88b541456c1501908692118863a66b960f8cad/src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group-header/tab-group-header.component.ts#L198)):*
> ```XML
>     const scrollBox = this.tabsWrapper;
>     const overflowAmount = scrollBox.scrollWidth - scrollBox.clientWidth;
>     const scrollMagnitude = Math.abs(scrollBox.scrollLeft); // 'scrollLeft' increases to the negative when 'rtl'
> ```

Forgot to mention, but I'm loving how well the tab scrolling works. 
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group-header/tab-group-header.component.spec.ts` line 6 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-NqaYpt863kZOcrt75lk:-NrEy__08rjjmeMWU3P9:bccpe83) ([raw file](https://github.com/sillsdev/web-xforge/blob/acc926bbe6f3aadd619cae09f25b0f5e97463792/src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group-header/tab-group-header.component.spec.ts#L6)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Awesome!
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group-header/tab-scroll-button/tab-scroll-button.component.html` line 1 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-NqkMexqA2TD014G2Bzo:-NrEzBn06jUa6XGmGlPR:bws3vyo) ([raw file](https://github.com/sillsdev/web-xforge/blob/acc926bbe6f3aadd619cae09f25b0f5e97463792/src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group-header/tab-scroll-button/tab-scroll-button.component.html#L1)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Good find.  I haven't been able to reproduce this yet.  Maybe not a stopper, and we can create an issue if it creeps up again?
</blockquote></details>

Yeah, absolutely
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/tab-state/tab-state.service.ts` line 24 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-Nqf21hiE1LYNc7T5u_R:-NrF1ReIE5B8ewHWhoOs:b-5ciciw) ([raw file](https://github.com/sillsdev/web-xforge/blob/acc926bbe6f3aadd619cae09f25b0f5e97463792/src/SIL.XForge.Scripture/ClientApp/src/app/shared/tab-state/tab-state.service.ts#L24)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

My thought was to allow `TabStateService` to be able to manage tab state in a general way but still get the benefits of type safety.  In fact, I found `EditorTabsStateService` to be unnecessary and I have eliminated in SF-2528 (tab drag/drop reorder).

...actually, I went ahead and removed `EditorTabsStateService` in this PR as well.
</blockquote></details>

Awesome. Rip!
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts` line 122 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-NrF9Z3F1Ef_Zk1TokCM:-NrF9Z3F1Ef_Zk1TokCN:bzi19uf) ([raw file](https://github.com/sillsdev/web-xforge/blob/9c88b541456c1501908692118863a66b960f8cad/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts#L122)):*
> ```XML
>   }
> 
>   private cleanAttributes(attributes: StringMap | undefined): StringMap | undefined {
> ```

Not a problem necessarily, but what's the reasoning for this? Is this for a bug?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html` line 63 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-Nqf4_2QDC7ohiPal9-v:-NrF1u-z0rajtik8w7TX:bk0o2gu) ([raw file](https://github.com/sillsdev/web-xforge/blob/acc926bbe6f3aadd619cae09f25b0f5e97463792/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html#L63)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

I'm not sure I'm following.  I may need some elaboration on what this might look like.
</blockquote></details>

Sure, I think I may have overcomplicated it. Can you move TabStateService (in editor.component.ts) to tab-group.component.ts?

Reasoning: Interactions bubble up from tab-group and are caught by the editor, which is the one who interacts with TabStateService. I feel like the editor is a middleman unnecessarily. You may be able to move the TabStateService reference out of editor and into tab-group, which would allow any future consumers to share this functionality. Plus, it keeps stuff out of our bloated editor class. Based on the usages in editor.component.ts, the only things we need to give to tab-group are sourceLabel and targetLabel.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 1154 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-NqkKWlcBTJm3dfbKlmZ:-NrF5io2EW-aa2-DVLo3:b-qi9t0p) ([raw file](https://github.com/sillsdev/web-xforge/blob/acc926bbe6f3aadd619cae09f25b0f5e97463792/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1154)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Sounds good.  Removed time and made dates within last 6 months in format like 'Jan 5'.  More than 6 months ago includes the year with format `mm/dd/yy`.

6 months is kinda arbitrary, but it seems like at some point the year becomes necessary.
</blockquote></details>

Agreed. Certainly good enough to start!
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tabs-menu.service.ts` line 83 at r1](https://reviewable.io/rev [...]

2024-02-25 19:05 UTC, pmachapman reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2332)* status: all files reviewed, 6 unresolved discussions (waiting on @siltomato)



<!-- Sent from Reviewable.io -->

2024-02-26 05:18 UTC, siltomato reviewed
The offline errors should also be fixed now.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-:-NrMsvJcDTG7GoHAiAG2:behmqxd)* status: all files reviewed, 5 unresolved discussions (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group.component.ts` line 14 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-Nqari0aDKtA1JftvkCB:-NrM3nxb048vt-RlWoFx:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/acc926bbe6f3aadd619cae09f25b0f5e97463792/src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group.component.ts#L14)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Ok, well, I think the way it turned out is really solid, and I see opening tabs as being desirable when offline. And given how simple these two would be to add later, can we go ahead and remove them for now? I follow YAGNI, when it makes sense.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group-header/tab-group-header.component.ts` line 198 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-NrEyiyM6TGrcHyoS4f9:-NrHapog1pWu0d9OImQF:b9ldnc3) ([raw file](https://github.com/sillsdev/web-xforge/blob/9c88b541456c1501908692118863a66b960f8cad/src/SIL.XForge.Scripture/ClientApp/src/app/shared/sf-tab-group/tab-group-header/tab-group-header.component.ts#L198)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Forgot to mention, but I'm loving how well the tab scrolling works.
</blockquote></details>

Cool, thanks.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts` line 122 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-NrF9Z3F1Ef_Zk1TokCM:-NrHbMoeEUCxfeKruVFY:b-o7ls3h) ([raw file](https://github.com/sillsdev/web-xforge/blob/9c88b541456c1501908692118863a66b960f8cad/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts#L122)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Not a problem necessarily, but what's the reasoning for this? Is this for a bug?
</blockquote></details>

The verse that was highlighted in the 'target' editor at the time of opening the draft tab retained its highlight attribute.

However... your question got me wondering why I'm getting the ops from a component instead of directly from the project service.  I can't think of a good reason other than that is what the draft viewer component does (and it probably shouldn't either).

I modified `EditorDraftComponent` (auto draft tab) to get target ops directly from the project service instead of a text component, and removed the unnecessary `cleanAttributes()` from `DraftViewerService`.  I'll leave the existing draft viewer component as-is, as it works fine and will be obsolete soon enough.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html` line 63 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-Nqf4_2QDC7ohiPal9-v:-NrYdaMmDQM4bjSlMjeo:b-oaehle) ([raw file](https://github.com/sillsdev/web-xforge/blob/acc926bbe6f3aadd619cae09f25b0f5e97463792/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.html#L63)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Sure, I think I may have overcomplicated it. Can you move TabStateService (in editor.component.ts) to tab-group.component.ts?

Reasoning: Interactions bubble up from tab-group and are caught by the editor, which is the one who interacts with TabStateService. I feel like the editor is a middleman unnecessarily. You may be able to move the TabStateService reference out of editor and into tab-group, which would allow any future consumers to share this functionality. Plus, it keeps stuff out of our bloated editor class. Based on the usages in editor.component.ts, the only things we need to give to tab-group are sourceLabel and targetLabel.
</blockquote></details>

Ok, makes sense.  I wanted to make the tab group component as dumb as possible, but a shared state service would still decouple the state management from the component.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 1154 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-NqkKWlcBTJm3dfbKlmZ:-NrI5KGYE_cHTqNVgsHU:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/acc926bbe6f3aadd619cae09f25b0f5e97463792/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1154)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Agreed. Certainly good enough to start!
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tabs-menu.service.ts` line 83 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-NqkFTx5-6FOHxpUElZg:-NrM5jBv-CMUphya7e8n:b9duxqc) ([raw file](https://github.com/sillsdev/web-xforge/blob/acc926bbe6f3aadd619cae09f25b0f5e97463792/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tabs-menu.service.ts#L83)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

My understanding of what you're getting at: You're envisioning that clicking the Auto Draft button when there's no draft for that chapter would open a new tab which contains a link to the Draft Preview or even contains the Draft Preview.

I like this idea -- would you be interested in fleshing it out in Balsamiq?

(We should absolutely handle the "change chapters while draft tab is selected" scenario when we implement tab persistence. My guess is you're trying to futureproof things to be able to keep the Auto Draft tab open even when they move from a book with a draft to a book without. Let's keep this in mind.)
</blockquote></details>

Added TODO in the editor draft component calling for more functionality when there is no draft for the chapter.  I believe there was an jira issue for adding this info to the draft generation page (jira is down, so i can't reference it directly ATM).  If there is, we could possibly place that same component in the tab.

I will take a look Monday at what has currently been done in this area and then take a stab at describing it with Balsamiq.  BTW, I really appreciate your work there.  What you, Nigel, and Nathaniel have done really makes it easier to brainstorm and visualize ideas.


<!-- Sent from Reviewable.io -->

2024-02-26 08:33 UTC, josephmyers requested changes
Thanks. History is no longer throwing an exception, but if the network drops with a History tab open and then returns, the history text content doesn't reappear. Are you seeing this?

> Reviewed 17 of 17 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-:-NrZUKj27baklw5-bfeK:bs4fz36)* status: all files reviewed, 1 unresolved discussion (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts` line 122 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-NrF9Z3F1Ef_Zk1TokCM:-NrZ4Wpr442JjbhGt47G:bowj2yk) ([raw file](https://github.com/sillsdev/web-xforge/blob/9c88b541456c1501908692118863a66b960f8cad/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts#L122)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

The verse that was highlighted in the 'target' editor at the time of opening the draft tab retained its highlight attribute.

However... your question got me wondering why I'm getting the ops from a component instead of directly from the project service.  I can't think of a good reason other than that is what the draft viewer component does (and it probably shouldn't either).

I modified `EditorDraftComponent` (auto draft tab) to get target ops directly from the project service instead of a text component, and removed the unnecessary `cleanAttributes()` from `DraftViewerService`.  I'll leave the existing draft viewer component as-is, as it works fine and will be obsolete soon enough.
</blockquote></details>

Nice. This is a great improvement
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 1143 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-NrZQc6W-TD8Tis5YjFw:-NrZQc6X-xV03dr-54w3:bniyjrm) ([raw file](https://github.com/sillsdev/web-xforge/blob/8c0a9a7553cbd1ae569eb491324e87f5280f67d2/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1143)):*
> ```XML
>   }
> 
>   addTab(tabGroupType: EditorTabGroupType, newTabType: string | null): void {
> ```

Any reason you didn't get this guy, too?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tabs-menu.service.ts` line 83 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-NqkFTx5-6FOHxpUElZg:-NrZWgGEEV4GdXvprJy6:b-mz4t42) ([raw file](https://github.com/sillsdev/web-xforge/blob/acc926bbe6f3aadd619cae09f25b0f5e97463792/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tabs-menu.service.ts#L83)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

Added TODO in the editor draft component calling for more functionality when there is no draft for the chapter.  I believe there was an jira issue for adding this info to the draft generation page (jira is down, so i can't reference it directly ATM).  If there is, we could possibly place that same component in the tab.

I will take a look Monday at what has currently been done in this area and then take a stab at describing it with Balsamiq.  BTW, I really appreciate your work there.  What you, Nigel, and Nathaniel have done really makes it easier to brainstorm and visualize ideas.
</blockquote></details>

Thanks, man. Yes, that JIRA issue is the one Raymond has been working on. SF-2448


<!-- Sent from Reviewable.io -->

2024-02-27 19:39 UTC, siltomato reviewed
- Created a base `TabFactoryService` that can be provided with `EditorTabFactoryService`
- Moved and renamed some files
- Fixed editor history issue

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-:-Nrg20GACQrRgp210OLi:b-qxkta1)* status: 46 of 73 files reviewed, 1 unresolved discussion (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 1143 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-NrZQc6W-TD8Tis5YjFw:-NraN4sf-9HJEv5jb2lw:b-g7k03m) ([raw file](https://github.com/sillsdev/web-xforge/blob/8c0a9a7553cbd1ae569eb491324e87f5280f67d2/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1143)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Any reason you didn't get this guy, too?
</blockquote></details>

This one was a little more involved, but after thinking about it some more, I created a base `TabFactoryService` that can overridden via providers with `EditorTabFactoryService` (similar to the `EditorTabMenuService`).


<!-- Sent from Reviewable.io -->

2024-02-28 03:20 UTC, josephmyers requested changes
Thanks, man. The History bug is fixed, but it uncovered another one. I have a couple more comments about History in general. Feel free to dismiss, if it's something already discussed/approved when we implemented it:
- I just noticed the History font is significantly smaller than the editor text. Is this intentional? I have concerns about this from an accessibility standpoint. It doesn't have to be exactly the same as the editor, but shrinking it this much seems unnecessary.
- Is there any actual reason we disallow History and AI Draft while offline? It's a little odd to me that we actively hide their current tab content if the network drops. Couldn't we at least preserve that until the network returns? Maybe this could be a separate task.
- History is still largely broken if the network blips. Neither the dropdown nor the "diff" button works. (This we need to fix)

> Reviewed 27 of 27 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-:-NrhaL4x2Kl96a4cKF29:b3p5nu2)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 1143 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-NrZQc6W-TD8Tis5YjFw:-NrhhKm63IQomsZ1_ZiN:br06oxv) ([raw file](https://github.com/sillsdev/web-xforge/blob/8c0a9a7553cbd1ae569eb491324e87f5280f67d2/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L1143)):*
<details><summary><i>Previously, siltomato wrote…</i></summary><blockquote>

This one was a little more involved, but after thinking about it some more, I created a base `TabFactoryService` that can overridden via providers with `EditorTabFactoryService` (similar to the `EditorTabMenuService`).
</blockquote></details>

Looks good, thanks.


<!-- Sent from Reviewable.io -->

2024-02-28 08:52 UTC, siltomato reviewed
Yes, it makes sense that the loaded history snapshot should be viewable.  Same for draft.  I'm not sure what the reasoning is for the font choice for history.  If it's an issue, it makes sense to separate it from this one, I think.
- Updated history to make last snapshot viewable when offline
  - History will show 'offline' notice only if offline before any snapshots loaded
- Fixed online/offline history issue (I think!)
- The last draft that was fetched when online should now be viewable when going offline
- Rebased on master

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-:-NrigeU4-LSqYld89bgm:b-r7c8r1)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @siltomato)



<!-- Sent from Reviewable.io -->

2024-02-29 03:44 UTC, josephmyers approved these changes
Looks good, man. Thanks for all your work. Let's see what test finds!

> Reviewed 16 of 16 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-:-NrmxX-EE53ufxeGvnGn:b-94yn5g)* status: all files reviewed, 1 unresolved discussion (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.ts` line 101 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-NrmwZm6712U3BHK3NXI:-NrmwZm6712U3BHK3NXJ:b-vzseyl) ([raw file](https://github.com/sillsdev/web-xforge/blob/c8214eed47a40760c29582a005ec2d384ad25d98/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.ts#L101)):*
> ```XML
>   private canShowHistory(projectDoc: SFProjectProfileDoc | undefined): boolean {
>     // The user must be a Paratext user. No specific edit permission for the chapter is required.
>     return isParatextRole(projectDoc?.data?.userRoles[this.userService.currentUserId]);
> ```

I'm sure you had a reason for doing this, so I'm not blocking the PR for it. But why the change? It doesn't seem related.


<!-- Sent from Reviewable.io -->

2024-02-29 04:12 UTC, siltomato reviewed
Yes, and thank you!  It's much better thanks to your feedback.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-:-Nrn2gpx5wPjGUpZdNKM:borejy1)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.ts` line 101 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-NrmwZm6712U3BHK3NXI:-Nrn1xMN8KYvOcOAeucb:bjujnim) ([raw file](https://github.com/sillsdev/web-xforge/blob/c8214eed47a40760c29582a005ec2d384ad25d98/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-menu.service.ts#L101)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

I'm sure you had a reason for doing this, so I'm not blocking the PR for it. But why the change? It doesn't seem related.
</blockquote></details>

It was part of the rebase on master.  The change was done in `EditorComponent` by Peter, so I mirrored the change here since I moved this code from master.


<!-- Sent from Reviewable.io -->

2024-03-01 22:41 UTC, siltomato reviewed
Fixed a few issues found by tester:
- Source text was not scroll syncing to highlighted verse in target editor
- Remote project changes when project has no source text was throwing error
- Left/right scroll buttons were not working in browser dev tools mobile view

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2332#-:-Nrw9HqpApkb_vXtd_mU:bnv42ft)* status: 64 of 77 files reviewed, all discussions resolved (waiting on @josephmyers)



<!-- Sent from Reviewable.io -->

2024-03-04 06:56 UTC, josephmyers approved these changes
> Reviewed 13 of 13 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2332)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @siltomato)



<!-- Sent from Reviewable.io -->

2024-03-20 21:24 UTC, merged