SF-2594 Allow saving comments with the bottomsheet with XML symbols
sillsdev/web-xforge pull request #2365
Opened 2024-03-06 23:47 UTC by RaymondLuong3

The content for a note needs to have any xml related symbols such as `>` and `<` encoded to be stored in mongo. This was previously done when editing or adding a note to a thread in the note dialog, but adding notes through the bottom sheet was missed.

2024-03-07 01:12 UTC, nigel-wells requested changes
This fix looks fine but it has created another issue. Both the dialog and bottom sheet utilize `saveNote()` which means the dialog is now applying `XmlUtils.encodeForXml()` twice. If you remove it from the dialog and let the `saveNote()` method take care of it then that would be best. This way if we ever need to save a note via some other component in the future we can safely use `saveNote`. You may want to rename the test name as it isn't bottomsheet specific - it still tests fine though.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2365#-:-NsLRxpG06iEcFPBRJxQ:botwc2w)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2024-05-13 19:08 UTC, RaymondLuong3 reviewed
@nigel-wells Looks like we have let this PR slide for a while. This is rebased and ready for a re-review.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2365#-:-NxnLbht0Mwz3kQM5B1n:bclstli)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @nigel-wells)



<!-- Sent from Reviewable.io -->

2024-05-14 00:04 UTC, nigel-wells requested changes
Great - will be nice to get this across. Just one small tweak to the test.

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2365#-:-NxoPQLtBKxcKNv2t1yY:bodwahi)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts` line 2820 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2365#-NxoP03sB4cuQ_SC818O:-NxoP03sB4cuQ_SC818P:bgx5mia) ([raw file](https://github.com/sillsdev/web-xforge/blob/b3e65483c7bfb032af7db07f05be631343cceb67/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L2820)):*
> ```XML
>       const iconElement: HTMLElement = env.getNoteThreadIconElementAtIndex('verse_1_2', 0)!;
>       iconElement.click();
>       const editedContent = 'edited content <xml> tags';
> ```

Can we add the `&` character in here as well as that was also a specific part of the previous tests.


<!-- Sent from Reviewable.io -->

2024-05-14 15:49 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2365)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts` line 2820 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2365#-NxoP03sB4cuQ_SC818O:-Nxrmg_XAgOkTEZ5nwPh:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/b3e65483c7bfb032af7db07f05be631343cceb67/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L2820)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Can we add the `&` character in here as well as that was also a specific part of the previous tests.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-14 19:44 UTC, nigel-wells approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2365#-:-NxscXdtB8e9tJ-grg4w:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2024-05-16 16:13 UTC, merged