SF-2574 Provide project data to NMT forward drafting approval team
sillsdev/web-xforge pull request #2373
Opened 2024-03-14 01:31 UTC by pmachapman

This PR:
 * Adds a Serval Administration Panel where users with the role ServalAdmin can activate pre-translation drafting for projects.

2024-04-08 03:08 UTC, nigel-wells requested changes
> Reviewed 28 of 34 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2373)* status: all files reviewed, 52 unresolved discussions (waiting on @pmachapman)

*[a discussion](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-NuvLYiW7a9zpqPj4LBl:-NuvLYiW7a9zpqPj4LBm:b-ovuaxp) (no related file):*
Nice work on this Peter - this will provide a great way for admins to get insight into Serval. Question: Is Serval Admin `>` System Admin?

There will need to be some offline notices added to the serval admin project page if someone was on that page when they went offline i.e. downloading is not available.

___
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts` line 355 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-Nufv4lU0lrSDA34qM8l:-Nufv4lU0lrSDA34qM8m:b-dl5yy3) ([raw file](https://github.com/sillsdev/web-xforge/blob/64b97d88d9e55ab614b4895ebbf6c2defefcb5f6/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts#L355)):*
> ```XML
>       env.init();
> 
>       // Show the user menu
> ```

For simplicity across all the tests, how about we create a `env.showUserMenu()` and `env.closeUserMenu()` - will save some repeating lines across all the tests.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts` line 360 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-NufurWl6W5w9ZGuT7iA:-NufurWl6W5w9ZGuT7iB:b-8a3w1z) ([raw file](https://github.com/sillsdev/web-xforge/blob/64b97d88d9e55ab614b4895ebbf6c2defefcb5f6/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts#L360)):*
> ```XML
> 
>       // Verify the menu item is visible
>       expect(env.component.isServalAdmin).toBeTruthy();
> ```

nit  change these to `toBeTrue()` as `toBeTruthy()` can apply to lots of variables which we wouldn't want to pass if it did.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts` line 362 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-Nufub_gB0z9s0L4YsKu:-Nufub_gB0z9s0L4YsKv:b5q77z0) ([raw file](https://github.com/sillsdev/web-xforge/blob/64b97d88d9e55ab614b4895ebbf6c2defefcb5f6/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts#L362)):*
> ```XML
>       expect(env.component.isServalAdmin).toBeTruthy();
>       expect(env.userMenu).not.toBeNull();
>       expect(env.userMenu.query(By.css('#serval-admin-btn'))).not.toBeNull();
> ```

Make a getter for these css queries to keep the logic in the TestEnvironment which will make future changes easier if needed
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-admin-auth.guard.spec.ts` line 26 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-NufvcMGDQirwkN8UK7e:-NufvcMGDQirwkN8UK7f:bhw08q2) ([raw file](https://github.com/sillsdev/web-xforge/blob/64b97d88d9e55ab614b4895ebbf6c2defefcb5f6/src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-admin-auth.guard.spec.ts#L26)):*
> ```XML
> 
>     env.service.canActivate({} as ActivatedRouteSnapshot, {} as RouterStateSnapshot).subscribe(result => {
>       expect(result).toBeTruthy();
> ```

nit  make these `toBeTrue()` as well
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-administration.component.html` line 1 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-Nug-oZXBtZSgd2eOTff:-Nug-oZXBtZSgd2eOTfg:bj1oh51) ([raw file](https://github.com/sillsdev/web-xforge/blob/64b97d88d9e55ab614b4895ebbf6c2defefcb5f6/src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-administration.component.html#L1)):*
> ```HTML
> <div fxLayout="column" fxLayoutAlign="center start" class="body-content">
> ```

Is this `<div>` adding any value? I think it can just be removed as it doesn't need to make use of flex in anyway
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-administration.service.ts` line 32 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-Nug0gyC6PljaYoNBQjs:-Nug0gyC6PljaYoNBQjt:b-ougj8h) ([raw file](https://github.com/sillsdev/web-xforge/blob/64b97d88d9e55ab614b4895ebbf6c2defefcb5f6/src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-administration.service.ts#L32)):*
> ```XML
>    * @returns An observable.
>    */
>   downloadProject(projectId: string): Observable<Blob> {
> ```

Are these methods serval specific or would the be better in the `ProjectService`? They sound generic at first glance.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-administration.service.ts` line 33 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-Nug1I6P8xQJtlBsWplG:-Nug1I6P8xQJtlBsWplH:bjyanx6) ([raw file](https://github.com/sillsdev/web-xforge/blob/64b97d88d9e55ab614b4895ebbf6c2defefcb5f6/src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-administration.service.ts#L33)):*
> ```XML
>    */
>   downloadProject(projectId: string): Observable<Blob> {
>     return this.httpClient.get(`paratext-api/projects/${projectId}/download`, {
> ```

Perhaps we could add `paratext-api` to our list of consts in `url-constants.ts` for consistency
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-administration.service.spec.ts` line 28 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-NuvHkGt1Ks3vi9OzJs7:-NuvHkGt1Ks3vi9OzJs8:bmpmx05) ([raw file](https://github.com/sillsdev/web-xforge/blob/64b97d88d9e55ab614b4895ebbf6c2defefcb5f6/src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-administration.service.spec.ts#L28)):*
> ```XML
>       const env = new TestEnvironment();
>       const id = '1234567890abcdef';
>       expect(env.service.isResource(id)).toBeTruthy();
> ```

Change to `toBeTrue()` and below
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-administration.service.spec.ts` line 31 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-NuvI9Zn7ZzFyErOw3Eu:-NuvI9Zn7ZzFyErOw3Ev:bbwjdx5) ([raw file](https://github.com/sillsdev/web-xforge/blob/64b97d88d9e55ab614b4895ebbf6c2defefcb5f6/src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-administration.service.spec.ts#L31)):*
> ```XML
>     });
> 
>     it('should return true for a project id', () => {
> ```

should return "false"
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html` line 1 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-NuvIgHD9GfJQt1MwdAs:-NuvIgHD9GfJQt1MwdAt:b-wn5lww) ([raw file](https://github.com/sillsdev/web-xforge/blob/64b97d88d9e55ab614b4895ebbf6c2defefcb5f6/src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html#L1)):*
> ```HTML
> <div fxLayout="column" fxLayoutAlign="center start" class="body-content">
> ```

Is this `<div>` needed?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html` line 2 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-NuvIr3VDBbqgEMAuhdp:-NuvIr3VDBbqgEMAuhdq:be363ot) ([raw file](https://github.com/sillsdev/web-xforge/blob/64b97d88d9e55ab614b4895ebbf6c2defefcb5f6/src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html#L2)):*
> ```HTML
> <div fxLayout="column" fxLayoutAlign="center start" class="body-content">
>   <h1>{{ projectName }}</h1>
> ```

I wonder if this isn't needed. The route has already switched to the project and the name can be seen in the nav bar so its obvious which one we're on. Maybe this should be "Serval Settings" or something like that? Is it worth having this in the main nav menu as well otherwise you're always forced to go to the serval admin page and then back to the project you were already on.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html` line 3 at r2](https://reviewable.io/reviews/sil [...]

2024-04-09 02:12 UTC, pmachapman reviewed
> Dismissed @github-advanced-security[bot] from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2373)* status: all files reviewed, 43 unresolved discussions (waiting on @nigel-wells)

*[a discussion](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-NuvLYiW7a9zpqPj4LBl:-Nv-5RbCCpduSI6B0tTr:begs73l) (no related file):*
> Is Serval Admin `>` System Admin?

No - they are different roles. You can be one, the other, or both.

> There will need to be some offline notices added to the serval admin project page if someone was on that page when they went offline i.e. downloading is not available.

Do we need it given this is an special admin only area, and not accessible to the general public? The Serval Admin menu item is disabled when offline, and the red network message appears when I go offline, or there is a connection interruption.

This change is an admin panel - no users will access it, except specific staff of SIL or developers. For this reason, it will not be translated, like how the System Admin page is not translated. (I pasted the message "This page/component will not be translated as it is not for general users." into each of the comments to do with this, as I had to keep track of ones I had not yet relied too - it got a bit confusing :-S)

___
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts` line 355 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-Nufv4lU0lrSDA34qM8l:-Nv-EXHw-_FUMSeH__u0:bvkveji) ([raw file](https://github.com/sillsdev/web-xforge/blob/64b97d88d9e55ab614b4895ebbf6c2defefcb5f6/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts#L355)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

For simplicity across all the tests, how about we create a `env.showUserMenu()` and `env.closeUserMenu()` - will save some repeating lines across all the tests.
</blockquote></details>

Done. I have created a method called `showHideUserMenu()` as the logic is precisely the same to show and hide the menu.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts` line 360 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-NufurWl6W5w9ZGuT7iA:-Nv-EpOjCeHlcHOofAuX:b-rxnzo5) ([raw file](https://github.com/sillsdev/web-xforge/blob/64b97d88d9e55ab614b4895ebbf6c2defefcb5f6/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts#L360)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

nit  change these to `toBeTrue()` as `toBeTruthy()` can apply to lots of variables which we wouldn't want to pass if it did.
</blockquote></details>

Done. I have changed these `toBe(true)`, as `toBe(false)` was used elsewhere. Also `toBeTrue()` caused me an error in my intellisense for some reason...
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts` line 362 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-Nufub_gB0z9s0L4YsKu:-Nv-H7wVE-AQx-nGGVoC:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/64b97d88d9e55ab614b4895ebbf6c2defefcb5f6/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts#L362)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Make a getter for these css queries to keep the logic in the TestEnvironment which will make future changes easier if needed
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-admin-auth.guard.spec.ts` line 26 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-NufvcMGDQirwkN8UK7e:-Nv-HXGf4EO_7GwjedYv:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/64b97d88d9e55ab614b4895ebbf6c2defefcb5f6/src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-admin-auth.guard.spec.ts#L26)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

nit  make these `toBeTrue()` as well
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-administration.component.html` line 1 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-Nug-oZXBtZSgd2eOTff:-Nv-JyKJ2rhwEI98tDNY:b-wnfmk9) ([raw file](https://github.com/sillsdev/web-xforge/blob/64b97d88d9e55ab614b4895ebbf6c2defefcb5f6/src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-administration.component.html#L1)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Is this `<div>` adding any value? I think it can just be removed as it doesn't need to make use of flex in anyway
</blockquote></details>

Done. Removed.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-administration.service.ts` line 32 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-Nug0gyC6PljaYoNBQjs:-Nv-K-Um-LKO6RKBqdNb:bxk0es8) ([raw file](https://github.com/sillsdev/web-xforge/blob/64b97d88d9e55ab614b4895ebbf6c2defefcb5f6/src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-administration.service.ts#L32)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Are these methods serval specific or would the be better in the `ProjectService`? They sound generic at first glance.
</blockquote></details>

These methods should not be accessible by the general public, so I moved them into this service, to stop project.service from getting cluttered. There will be more methods coming here in future PRs.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-administration.service.ts` line 33 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-Nug1I6P8xQJtlBsWplG:-Nv-LL7XEhcM5weLQivg:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/64b97d88d9e55ab614b4895ebbf6c2defefcb5f6/src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-administration.service.ts#L33)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Perhaps we could add `paratext-api` to our list of consts in `url-constants.ts` for consistency
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-administration.service.spec.ts` line 28 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-NuvHkGt1Ks3vi9OzJs7:-Nv-LVJNCjRGFlgXlrNt:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/64b97d88d9e55ab614b4895ebbf6c2defefcb5f6/src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-administration.service.spec.ts#L28)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Change to `toBeTrue()` and below
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-administration.service.spec.ts` line 31 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-NuvI9Zn7ZzFyErOw3Eu:-Nv-LTb88D-sHlCrMAx_:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/64b97d88d9e55ab614b4895ebbf6c2defefcb5f6/src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-administration.service.spec.ts#L31)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

should return "false"
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html` line 1 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-NuvIgHD9GfJQt1MwdAs:-Nv-LptO-X2JQVwxhzty:b-wnfmk9) ([raw file](https://github.com/sillsdev/web-xforge/blob/64b97d88d9e55ab614b4895ebbf6c2defefcb5f6/src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html#L1)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Is this `<div>` needed?
</blockquote></details>

Done. R [...]

2024-04-10 01:57 UTC, nigel-wells requested changes
> Reviewed 3 of 15 files at r3, 12 of 12 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2373)* status: all files reviewed, 4 unresolved discussions (waiting on @pmachapman)

*[a discussion](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-NuvLYiW7a9zpqPj4LBl:-Nv4htM50kY5us__jZT1:b-mt9tzc) (no related file):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

> Is Serval Admin `>` System Admin?

No - they are different roles. You can be one, the other, or both.

> There will need to be some offline notices added to the serval admin project page if someone was on that page when they went offline i.e. downloading is not available.

Do we need it given this is an special admin only area, and not accessible to the general public? The Serval Admin menu item is disabled when offline, and the red network message appears when I go offline, or there is a connection interruption.

This change is an admin panel - no users will access it, except specific staff of SIL or developers. For this reason, it will not be translated, like how the System Admin page is not translated. (I pasted the message "This page/component will not be translated as it is not for general users." into each of the comments to do with this, as I had to keep track of ones I had not yet relied too - it got a bit confusing :-S)
</blockquote></details>

If we're confident that the users on the screen are savvy enough to know things may break if they're offline then I'm happy to not worry about it. You'll need to add a note to the testers to not worry about testing the components in offline mode.

___
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts` line 360 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-NufurWl6W5w9ZGuT7iA:-Nv4_n2lAuaMTzE8sAGt:b-ss7oti) ([raw file](https://github.com/sillsdev/web-xforge/blob/64b97d88d9e55ab614b4895ebbf6c2defefcb5f6/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.spec.ts#L360)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Done. I have changed these `toBe(true)`, as `toBe(false)` was used elsewhere. Also `toBeTrue()` caused me an error in my intellisense for some reason...
</blockquote></details>

Yes, good call. I forgot `toBeTrue()` also does an optional check for a boolean object which we wouldn't want to be true for these. Good discussion here around the three options : https://stackoverflow.com/questions/32615713/tobetrue-vs-tobetruthy-vs-tobetrue
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html` line 2 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-NuvIr3VDBbqgEMAuhdp:-Nv4brDl8GwZwXmXExIe:b-vpt7qm) ([raw file](https://github.com/sillsdev/web-xforge/blob/64b97d88d9e55ab614b4895ebbf6c2defefcb5f6/src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html#L2)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

This is here because the project won't appear in the main nav if you do not have access to this project. That will be the case for most projects opened using this page - the Serval Admin will not have access to the project, and so will configure it here (there will be future PRs adding functionality to do these Serval configurations actions)
</blockquote></details>

Ah, ok, that makes sense. What will the main nav show for projects you do not have access to?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html` line 14 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-NuvJRrW5ctb2mFk5wAK:-Nv4fTPFDUxytEEdsiZB:b-e279ue) ([raw file](https://github.com/sillsdev/web-xforge/blob/64b97d88d9e55ab614b4895ebbf6c2defefcb5f6/src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html#L14)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

It would be a separate timestamp for each project (i.e. each download link), and the last sync timestamp includes the last failed sync - which may not reflect the time the files were actually synced to disk.

I could add it, but I don't think it is really necessary as the last updated timestamp will be visible in the files when downloaded and extracted from the zip file?
</blockquote></details>

All good - only do if there is value in knowing what that date/time is without having to look i.e. would seeing the date/time on the screen change/influence someone's decision around downloading the documents.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.ts` line 136 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-NuvMGGR4tNYtsL94izD:-Nv4fs_A4ZrUhoUy5QzQ:bvt35wx) ([raw file](https://github.com/sillsdev/web-xforge/blob/64b97d88d9e55ab614b4895ebbf6c2defefcb5f6/src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.ts#L136)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

The `HttpInterceptor` we use could not be used with a traditional download link, as download actions have to be triggered by the user clicking on an `<a>` element and that element directly downloading the file. I would presume this is to stop websites throwing random downloads at you without you wanting them.

For this reason, the code gets the download as a blob, then presents it to the user an in anchor tag which is clicked in the background.

I could have gotten around it by passing the token in the URL in an anchor tag, but I wasn't really keen on that for security reasons.
</blockquote></details>

Yes, a user needs to click on the link but my question is around why the backend doesn't then serve up the appropriate headers for downloading a file. The backend is already fetching the file to be downloaded but it is returned in a request to the client to process rather than headers to trigger the browser to download it. Should be a lot less code if the backend does it. Something along the lines of:
```
httpResponseMessage.Content.Headers.ContentDisposition = new System.Net.Http.Headers.ContentDispositionHeaderValue("attachment");
httpResponseMessage.Content.Headers.ContentDisposition.FileName = FileName;
httpResponseMessage.Content.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue("application/octet-stream");
```
It may be that our requests to the backend are configured to allow for a response like that?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-projects.component.html` line 8 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-NuvNMB08kEHGKxjfXz5:-Nv4cpVO-tS-tyVC_oE2:b-yog3oj) ([raw file](https://github.com/sillsdev/web-xforge/blob/64b97d88d9e55ab614b4895ebbf6c2defefcb5f6/src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-projects.component.html#L8)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

If I do that, I would have to duplicate the inverse of the logic in the "No projects found" div at the bottom. Nesting I think is simpler?
</blockquote></details>

Agreed - this is the nature of code reviewing from the top down :)
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-projects.component.html` line 58 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-NuvOvtR7xk3hCZmyo4q:-Nv4d-DI8x9ocSxWbaXX:b-ia9o4g) ([raw file](https://github.com/sillsdev/web-xforge/blob/64b97d88d9e55ab614b4895ebbf6c2defefcb5f6/src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-projects.component.html#L58)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

I have no idea what is causing that. It is with th [...]

2024-04-10 02:14 UTC, pmachapman reviewed
> Dismissed @github-advanced-security[bot] from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2373)* status: all files reviewed, 3 unresolved discussions (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html` line 2 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-NuvIr3VDBbqgEMAuhdp:-Nv4j6TH6CijE-zcodym:bh5fuow) ([raw file](https://github.com/sillsdev/web-xforge/blob/64b97d88d9e55ab614b4895ebbf6c2defefcb5f6/src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html#L2)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Ah, ok, that makes sense. What will the main nav show for projects you do not have access to?
</blockquote></details>

It didn't display at all in my tests.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html` line 14 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-NuvJRrW5ctb2mFk5wAK:-Nv4jDbE9N26ucH9pg9L:bg6438z) ([raw file](https://github.com/sillsdev/web-xforge/blob/64b97d88d9e55ab614b4895ebbf6c2defefcb5f6/src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html#L14)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

All good - only do if there is value in knowing what that date/time is without having to look i.e. would seeing the date/time on the screen change/influence someone's decision around downloading the documents.
</blockquote></details>

No, I don't think it will affect it. There will be a need to view them anyway. I plan to add a "sync now" type feature in future (as a sync is run before a build is run), but I haven't thought through exactly how that would work (permissions make this interesting...).
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.ts` line 136 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-NuvMGGR4tNYtsL94izD:-Nv4jUGU1JGGPDJH5TvO:bkej5df) ([raw file](https://github.com/sillsdev/web-xforge/blob/64b97d88d9e55ab614b4895ebbf6c2defefcb5f6/src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.ts#L136)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Yes, a user needs to click on the link but my question is around why the backend doesn't then serve up the appropriate headers for downloading a file. The backend is already fetching the file to be downloaded but it is returned in a request to the client to process rather than headers to trigger the browser to download it. Should be a lot less code if the backend does it. Something along the lines of:
```
httpResponseMessage.Content.Headers.ContentDisposition = new System.Net.Http.Headers.ContentDispositionHeaderValue("attachment");
httpResponseMessage.Content.Headers.ContentDisposition.FileName = FileName;
httpResponseMessage.Content.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue("application/octet-stream");
```
It may be that our requests to the backend are configured to allow for a response like that?
</blockquote></details>

That method doesn't work, as the HttpInterceptor cannot intercept links that are clicked by the user. Downloads can only be triggered by links that are clicked. Its kind of a weird paradox which I find the solution to be unusual:

The solution is that we download the data as a blob in memory, create a link to a that blob in the DOM, and script a "click" on it.

This stack overflow question explains the sort of problem I encountered, and has a similar solution: https://stackoverflow.com/questions/54753021/how-can-i-pass-an-auth-token-when-downloading-a-file

Also, the `return File(outputStream, "application/zip", fileName);` in the C# code does cause those headers to be set (see https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.controllerbase.file), but they obviously aren't really used (I kept them for completeness' sake).
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-projects.component.html` line 58 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-NuvOvtR7xk3hCZmyo4q:-Nv4kTr29S81Vy1eva9C:b4obkz5) ([raw file](https://github.com/sillsdev/web-xforge/blob/64b97d88d9e55ab614b4895ebbf6c2defefcb5f6/src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-projects.component.html#L58)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Thanks - happy for it to be resolved in another PR if not specific to this one.
</blockquote></details>

I have created https://jira.sil.org/browse/SF-2689 to document these issues.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-projects.component.ts` line 146 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-NuvTQ5xCkek034EfEyX:-Nv4kjRA58BFQo-OyCrq:b-4n4tyd) ([raw file](https://github.com/sillsdev/web-xforge/blob/64b97d88d9e55ab614b4895ebbf6c2defefcb5f6/src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-projects.component.ts#L146)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

I guess if we're potentially dealing with 1000s of records then this makes sense. Normally I'd expect pagination in a SPA just to go through the data in memory. This page is also only for admins and is online only.
</blockquote></details>

I think the problem is related to the second bug documented at https://jira.sil.org/browse/SF-2689, which occurs on the system administration page. Not sure of a solution, as I haven't bug through the commit history which lead to the bug yet.


<!-- Sent from Reviewable.io -->

2024-04-10 02:57 UTC, nigel-wells approved these changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2373)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html` line 2 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-NuvIr3VDBbqgEMAuhdp:-Nv4n1Wr8McTB0EbArLm:b2xhlps) ([raw file](https://github.com/sillsdev/web-xforge/blob/64b97d88d9e55ab614b4895ebbf6c2defefcb5f6/src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html#L2)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

It didn't display at all in my tests.
</blockquote></details>

Oh! So the side effect is the menu shows on projects you do have access to? Should it? I guess I found it confusing but, as this is an admin only thing, I'm not overly fussed. It would be nice if it was consistent though. I won't hold this as a blocker.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.ts` line 136 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-NuvMGGR4tNYtsL94izD:-Nv4quj39LUw9Te8yAsg:b-7nxs66) ([raw file](https://github.com/sillsdev/web-xforge/blob/64b97d88d9e55ab614b4895ebbf6c2defefcb5f6/src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.ts#L136)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

That method doesn't work, as the HttpInterceptor cannot intercept links that are clicked by the user. Downloads can only be triggered by links that are clicked. Its kind of a weird paradox which I find the solution to be unusual:

The solution is that we download the data as a blob in memory, create a link to a that blob in the DOM, and script a "click" on it.

This stack overflow question explains the sort of problem I encountered, and has a similar solution: https://stackoverflow.com/questions/54753021/how-can-i-pass-an-auth-token-when-downloading-a-file

Also, the `return File(outputStream, "application/zip", fileName);` in the C# code does cause those headers to be set (see https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.controllerbase.file), but they obviously aren't really used (I kept them for completeness' sake).
</blockquote></details>

I'm with you now - seems like there should be a "normal" work around as at the end of the day it is still a request taking place. Browsers are being picky though for security reasons so we have work with that.


<!-- Sent from Reviewable.io -->

2024-04-10 02:59 UTC, nigel-wells approved these changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2373)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

*[a discussion](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-Nv4wLZDBT-Nl1spDKFE:-Nv4wLZDBT-Nl1spDKFF:b-c9zj2o) (no related file):*
Just the one comment there around the menu. If you're happy for that to hold anything up then feel free to move it to testing.

___


<!-- Sent from Reviewable.io -->

2024-04-10 03:27 UTC, pmachapman reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2373)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html` line 2 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-NuvIr3VDBbqgEMAuhdp:-Nv51YsqENu6dw-UkA-a:br06uw5) ([raw file](https://github.com/sillsdev/web-xforge/blob/64b97d88d9e55ab614b4895ebbf6c2defefcb5f6/src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.html#L2)):*
> Should it?

I don't know. I think for the purposes of this admin area, it is acceptable, as there is no need to access anything in the menu.


<!-- Sent from Reviewable.io -->

2024-04-17 16:51 UTC, Nateowami requested changes
> Reviewed 4 of 8 files at r7.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2373)* status: 33 of 37 files reviewed, 1 unresolved discussion (waiting on @nigel-wells and @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.spec.ts` line 25 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-Nvgy2SHAD8RfjMM5azL:-Nvgy2SHAD8RfjMM5azM:b-4qsbgg) ([raw file](https://github.com/sillsdev/web-xforge/blob/712026775800c62b720e73596cd9c0bd05137a0c/src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-project.component.spec.ts#L25)):*
> ```XML
> const mockServalAdministrationService = mock(ServalAdministrationService);
> 
> fdescribe('ServalProjectComponent', () => {
> ```

Should be describe


<!-- Sent from Reviewable.io -->

2024-04-17 18:47 UTC, Nateowami requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2373)* status: 33 of 37 files reviewed, 1 unresolved discussion (waiting on @nigel-wells and @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error-dialog/error-dialog.component.spec.ts` line 55 at r8](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-NvhNKfqB9-eMKa87bvB:-NvhNKfqB9-eMKa87bvC:bg0dqb7) ([raw file](https://github.com/sillsdev/web-xforge/blob/ba370d9a2a81861563859e6379375c57c031c179/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error-dialog/error-dialog.component.spec.ts#L55)):*
> ```XML
> 
>     env.closeButton.click();
>     flush();
> ```

The tests pass for me without `flush()`. Is it still needed?


<!-- Sent from Reviewable.io -->

2024-04-17 18:58 UTC, pmachapman reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2373)* status: 33 of 37 files reviewed, 1 unresolved discussion (waiting on @Nateowami and @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error-dialog/error-dialog.component.spec.ts` line 55 at r8](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-NvhNKfqB9-eMKa87bvB:-NvhP_OzCIDzLQ18O-KY:b-9ad7hm) ([raw file](https://github.com/sillsdev/web-xforge/blob/ba370d9a2a81861563859e6379375c57c031c179/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error-dialog/error-dialog.component.spec.ts#L55)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

The tests pass for me without `flush()`. Is it still needed?
</blockquote></details>

I think so - when rebased on last week's master, these tests failed and required the `flush()` statements. I think that bug will occur again sometime in future. It has stopped with the new test order based on the 12345 seed with the current tests in master.

If you think we should revert it and wait for the bug to reappear in future, that is OK too, and I can do that.


<!-- Sent from Reviewable.io -->

2024-04-23 23:30 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2373)* status: 27 of 37 files reviewed, all discussions resolved (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error-dialog/error-dialog.component.spec.ts` line 55 at r8](https://reviewable.io/reviews/sillsdev/web-xforge/2373#-NvhNKfqB9-eMKa87bvB:-NvhSLcjEqMRAUWsya6A:b-l4ie7i) ([raw file](https://github.com/sillsdev/web-xforge/blob/6e6fab64949917533f82fca804696f7f5342446a/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/error-dialog/error-dialog.component.spec.ts#L55)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

I think so - when rebased on last week's master, these tests failed and required the `flush()` statements. I think that bug will occur again sometime in future. It has stopped with the new test order based on the 12345 seed with the current tests in master.

If you think we should revert it and wait for the bug to reappear in future, that is OK too, and I can do that.
</blockquote></details>

~Jasmine always reports what the seed was for each test run, so it should be possible to get the seed whenever they fail:
![](https://files.reviewableusercontent.io/images/reviewable/6140710/bxdoTb2KzACBWyuKVeTIG-XV/Screenshot%20from%202024-04-17%2015-10-02.png)~

~Of course, that only helps if the failure depends on the seed.~

~Looking at the error dialog, it is an extremely simple component, with nothing that even creates any kind of timer. The only thing I can think of that might create a timer of some sort would be the Material dialog component.~


<!-- Sent from Reviewable.io -->

2024-04-23 23:42 UTC, merged