SF-2443 Added Apply button to draft tabs
sillsdev/web-xforge pull request #2391
Opened 2024-04-01 08:05 UTC by josephmyers

2024-04-11 05:01 UTC, Nateowami requested changes
Not a full review, but leaving a few comments.

> Reviewed 2 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-:-NvAX7LaCmcWlxtivJaw:b-vy4gzo)* status: 2 of 10 files reviewed, 4 unresolved discussions (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.html` line 20 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-Nv8K1py5rY2aXkM4h7A:-Nv8K1pz0ynPIj_9tR7V:b-m50hfr) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.html#L20)):*
> ```HTML
>     <span *ngIf="isDraftApplied && hasDraft" class="draft-indicator">
>       <transloco key="editor_draft_tab.draft_indicator_applied"></transloco>
>       <mat-icon class="check-icon">check</mat-icon>
> ```

Can we put the check _before_ the text?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.scss` line 16 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-Nv8Kuq2A8daLw2qJk_3:-Nv8Kuq2A8daLw2qJk_4:b-3b4sxh) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.scss#L16)):*
> ```SCSS
> 
> .toolbar {
>   position: sticky;
> ```

I don't think this is the right approach. The problem isn't that it needs to be sticky, have a white background, and have a z-index of 1. The problem is that _the wrong element is scrolling_.

But, it's a minor point, and I don't really want it to hold up this PR. Just something I wanted to point out.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 242 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-Nv8HdUOESU3gn4PFTMc:-Nv8HdUOESU3gn4PFTMd:b6vy0hu) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L242)):*
> ```JSON
>   },
>   "editor_draft_tab": {
>     "apply_to_project": "Apply to project",
> ```

Let's change this to "Add to project"
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 243 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-Nv8IV8zBJtKJXyWGDDK:-Nv8IV9-Cuol8FxZI6G_:bjlwp43) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L243)):*
> ```JSON
>   "editor_draft_tab": {
>     "apply_to_project": "Apply to project",
>     "draft_indicator_applied": "DRAFT APPLIED",
> ```

All caps do not work in all languages and writing systems. I would suggest we avoid it. Also, draft applied is less clear than it could be. How about "Draft has been added to the project"? I think it will be clearer not just to users that are not native English speakers, but also for localizers to understand what it means and how to translate it.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json` line 246 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-Nv8I-N-9LBTkgXT5rc8:-Nv8I-N-9LBTkgXT5rc9:b644p55) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L246)):*
Instead of explaining followed by a "continue" question, how about:

> Adding the draft will overwrite the current chapter. Are you sure you want to continue?
> [ Cancel ] - or - [ Overwrite chapter ]


<!-- Sent from Reviewable.io -->

2024-04-11 05:05 UTC, Nateowami commented
> The diff used for applying should also match Draft Previewer, but it is pretty easy to break. I'm leaning against putting a great amount of effort into this part, given that we'll be changing it when the USFM roundtripping ([SF-2589](https://jira.sil.org/browse/SF-2589)) is in.

It's already in. Have you updated for that already? I would think yes, but the PR description hasn't been updated, so that makes me think no. I haven't read through all the changes yet.

2024-04-11 05:06 UTC, josephmyers commented
Yes. I'll pull that part out of the description.

2024-04-12 03:16 UTC, nigel-wells requested changes
This seems to work pretty well - good job.
Just minor thing and one bigger question about how we could tackle the duplicated methods.

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-:-NvFIU6NERBSOVt7zJ3i:bpjy3rh)* status: all files reviewed, 12 unresolved discussions (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts` line 13 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-NvFBi7N5p5OkUMj9-Zw:-NvFBi7N5p5OkUMj9-Zx:b-cdu67w) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts#L13)):*
> ```XML
> }
> 
> export interface DraftDiff {
> ```

It's not really a diff is it? What about `AppliedDraftOps` or something similar?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 749 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-NvF6ciECJB5ya7jHIns:-NvF6ciECJB5ya7jHInt:b-mpmst8) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L749)):*
> ```XML
> 
>           this.draftAppliedSub = this.draftViewerService.draftApplied.subscribe(e => {
>             if (this.target?.id?.toString() === e.id.toString()) {
> ```

You could `pipe` and `filter` this
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts` line 3743 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-NvFGhkTCvcBUjwjYot_:-NvFGhkTCvcBUjwjYota:b-ejhyhp) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L3743)):*
> ```XML
>     }));
> 
>     it('updates editor when a draft is applied', fakeAsync(() => {
> ```

Can you also assert that a `hasDraft` was `true` and that the existing contents were different from the new ones.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.scss` line 33 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-NvFAbvj2xtK1zkUonrI:-NvFAbvj2xtK1zkUonrJ:b-y8o1o4) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.scss#L33)):*
> ```SCSS
> 
> .draft-indicator {
>   color: green;
> ```

Let's use one of our existing colors - `$greenDark` is closest to what you have.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts` line 130 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-NvFCUNp1uJHPAn_rXm6:-NvFCUNp1uJHPAn_rXm7:b1komuo) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts#L130)):*
> ```XML
>         // Set the draft editor with the pre-translation segments
>         this.draftText.editor?.setContents(new Delta(draftOps), 'api');
>         this.isDraftApplied = (await this.getDiff()).length() === 0;
> ```

Just noting here that I have a book/chapter which this registered as `true` even though I hadn't applied anything. The source had text but the draft only had verse numbers. 

This could easily be bad data on my local machine (probably) but wanted to point it out in case there is more to it.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts` line 175 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-NvFDEDl01r5yXeQz9_s:-NvFDEDl01r5yXeQz9_t:b-t7v7mh) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts#L175)):*
> ```XML
>       }
> 
>       const isInsertBlank = (isString(op.insert) && op.insert.trim().length === 0) || op.insert.blank === true;
> ```

Can just inline this without creating the variable.

If the existing target was full of blanks then do we care about warning for that?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts` line 184 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-NvFFcwM8-LzOHTWyiT1:-NvFFcwM8-LzOHTWyiT2:bw7xvvp) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts#L184)):*
> ```XML
>    * This code is reimplemented from editor.component.ts
>    */
>   get canEdit(): boolean {
> ```

Is there another way we can share this logic across both components - 4 seems a bit too many to duplicate. Could they move refactored into a service?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.spec.ts` line 178 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-NvFIOcs87-yT8Rk4Qtd:-NvFIOcs87-yT8Rk4Qte:b4sr5ws) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.spec.ts#L178)):*
> ```XML
>       )
>     ).once();
>     expect(component.isDraftApplied).toBe(true);
> ```

Let's assert this was `false` to begin with.


<!-- Sent from Reviewable.io -->

2024-04-12 03:48 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2391)* status: all files reviewed, 12 unresolved discussions (waiting on @josephmyers and @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.scss` line 33 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-NvFAbvj2xtK1zkUonrI:-NvFNhHm7Wuw3t3E7Z5R:b-8fx2u7) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.scss#L33)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Let's use one of our existing colors - `$greenDark` is closest to what you have.
</blockquote></details>

:+1: 
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts` line 175 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-NvFDEDl01r5yXeQz9_s:-NvFNxbe1xa4qovfZyW8:b-6uv9jj) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts#L175)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Can just inline this without creating the variable.

If the existing target was full of blanks then do we care about warning for that?
</blockquote></details>

Creating the variable isn't necessary, but can often be more readable. In this case, I can read from the beginning of the line and know what we're trying to figure out (whether the op is blank) and then read the logic and make sure it is doing the right thing. If we just returned an expression, it would be necessary to spend time looking at the logic to find out what it's checking.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts` line 184 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-NvFFcwM8-LzOHTWyiT1:-NvFOQ0B2d4JaqeSVyIB:bix593q) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts#L184)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Is there another way we can share this logic across both components - 4 seems a bit too many to duplicate. Could they move refactored into a service?
</blockquote></details>

:+1: although I don't see an obvious solution.


<!-- Sent from Reviewable.io -->

2024-04-15 08:23 UTC, josephmyers reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2391)* status: 4 of 10 files reviewed, 11 unresolved discussions (waiting on @Nateowami and @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts` line 13 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-NvFBi7N5p5OkUMj9-Zw:-NvU4_pc0xOkCLysVqel:bjgzp8) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts#L13)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

It's not really a diff is it? What about `AppliedDraftOps` or something similar?
</blockquote></details>

Well, it kind of is. Maybe I'm not seeing what you're saying. To me, a DeltaStatic is a diff. It's what's output by DeltaStatic.diff(), which is what I'm supplying to these ops.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 749 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-NvF6ciECJB5ya7jHIns:-NvU7nqQ3Var0kM8KP1k:b-af183f) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L749)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

You could `pipe` and `filter` this
</blockquote></details>

Yep, thanks!
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts` line 3743 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-NvFGhkTCvcBUjwjYot_:-NvU9lt69noFkWbJ-6yX:b7mofu2) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L3743)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Can you also assert that a `hasDraft` was `true` and that the existing contents were different from the new ones.
</blockquote></details>

That would be difficult in this test. I haven't set up the editor's contents or the draft contents, because it's not required by or the point of this test. This test demonstrates simply that when the editor receives the draftApplied event, it takes the passed diff and applies it. It has no bearing on the contents of either text, as that was determined in the draft tab.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.html` line 20 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-Nv8K1py5rY2aXkM4h7A:-NvUHhwF0jLXhRdEw_8R:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.html#L20)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Can we put the check _before_ the text?
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.scss` line 16 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-Nv8Kuq2A8daLw2qJk_3:-NvUHnSn4ZJDbeQeZYvs:b-l5hd0f) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.scss#L16)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I don't think this is the right approach. The problem isn't that it needs to be sticky, have a white background, and have a z-index of 1. The problem is that _the wrong element is scrolling_.

But, it's a minor point, and I don't really want it to hold up this PR. Just something I wanted to point out.
</blockquote></details>

Thanks. I'm following the pattern from the history tab. So if we want to refactor things, we'd need to get all occurrences.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.scss` line 33 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-NvFAbvj2xtK1zkUonrI:-NvUJkkL2d8HmP7x_JK6:b-h2szml) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.scss#L33)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

:+1:
</blockquote></details>

I certainly can
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts` line 130 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-NvFCUNp1uJHPAn_rXm6:-NvUKeNH2u-uO_NVmAoO:b-g9ct8k) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts#L130)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Just noting here that I have a book/chapter which this registered as `true` even though I hadn't applied anything. The source had text but the draft only had verse numbers. 

This could easily be bad data on my local machine (probably) but wanted to point it out in case there is more to it.
</blockquote></details>

That is interesting! I can put a check in here, but how did you get an empty draft? You'll have to be the one to test this change, haha
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts` line 175 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-NvFDEDl01r5yXeQz9_s:-NvUNLA85tRWXbKuVv0k:bdt528l) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts#L175)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Creating the variable isn't necessary, but can often be more readable. In this case, I can read from the beginning of the line and know what we're trying to figure out (whether the op is blank) and then read the logic and make sure it is doing the right thing. If we just returned an expression, it would be necessary to spend time looking at the logic to find out what it's checking.
</blockquote></details>

Yep, thanks, Nathaniel!
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts` line 184 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-NvFFcwM8-LzOHTWyiT1:-NvUNStYAFbbT3tPmKC2:b-23ntrq) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts#L184)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

:+1: although I don't see an obvious solution.
</blockquote></details>

It will go down to 3 when we remove the draft previewer :)
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.spec.ts` line 178 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-NvFIOcs87-yT8Rk4Qtd:-NvUYhp82vUyRWcbESBB:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.spec.ts#L178)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Let's assert this was `false` to begin with.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientA [...]

2024-04-16 02:59 UTC, nigel-wells requested changes
I have a state here - which may be bad data - but I have a book (which I didn't ask for a draft on) that has an apply button but there is no source available. I'm guessing this isn't related to this PR but wanted  to point it out just in case:
![image.png](https://files.reviewableusercontent.io/images/reviewable/17464863/AWiVzKIU5nMGMed53dJosK31/image.png)

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-:-NvZpiwMAeJAVCAy1H2F:b-nae5dc)* status: all files reviewed, 6 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts` line 13 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-NvFBi7N5p5OkUMj9-Zw:-NvZch1YABEruI3deGIW:bshtq2) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts#L13)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Well, it kind of is. Maybe I'm not seeing what you're saying. To me, a DeltaStatic is a diff. It's what's output by DeltaStatic.diff(), which is what I'm supplying to these ops.
</blockquote></details>

DeltaStatic can help provide a diff but it isn't its only purpose. `DraftDiff` only contains a diff because those were the ops set - it could have any ops if it wanted to. Doesn't need to hold anything up.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts` line 3743 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-NvFGhkTCvcBUjwjYot_:-NvZbx9e1je64KZLlAko:b-61qij9) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L3743)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

That would be difficult in this test. I haven't set up the editor's contents or the draft contents, because it's not required by or the point of this test. This test demonstrates simply that when the editor receives the draftApplied event, it takes the passed diff and applies it. It has no bearing on the contents of either text, as that was determined in the draft tab.
</blockquote></details>

Fair point - thanks.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.scss` line 33 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-NvFAbvj2xtK1zkUonrI:-NvZD8W2-waKykB7piIC:b-8riw0z) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.scss#L33)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

I certainly can
</blockquote></details>

Thanks.
Can you change from `@import` to `@use`. It won't overly affect anything for this PR but it is good practice that we've started introducing to the repo.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts` line 130 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-NvFCUNp1uJHPAn_rXm6:-NvZZO_K1OzX1et5rAdv:b5j37kl) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts#L130)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

That is interesting! I can put a check in here, but how did you get an empty draft? You'll have to be the one to test this change, haha
</blockquote></details>

Yep, that fixed it thanks!
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts` line 175 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-NvFDEDl01r5yXeQz9_s:-NvZZo1S53JbC9dJmsgl:bjwdd6v) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts#L175)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Yep, thanks, Nathaniel!
</blockquote></details>

Fair point.
What about the white space? My question is in relation to showing a dialog to confirm overwriting content and I think that isn't needed if all the content is blanks.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts` line 184 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-NvFFcwM8-LzOHTWyiT1:-NvZcBqI3tR73gN6veQd:b9jye7) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts#L184)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

It will go down to 3 when we remove the draft previewer :)
</blockquote></details>

Well, if it's 3 then go for it :)
Can we at least add the same comment on the methods in `editor.component.ts` as a reminder to update them here as well for now.


<!-- Sent from Reviewable.io -->

2024-04-16 06:58 UTC, josephmyers reviewed
This is quite interesting, because I thought we had just covered in this a comment below. If you're saying (again?) that a blank draft chapter, however you got there, has the button, then the doesDeltaHaveContent method I just made to prevent that isn't fully working. Can you step into that method and see what's causing it to think that there's content? Whenever I have a chapter with no draft data, I get the blue "x has no draft" blurb. I would think the `op.insert.trim().length === 0` check would cover this.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-:-Nv_cSC73yP-QqINx4di:b-w5c4y3)* status: 7 of 10 files reviewed, 6 unresolved discussions (waiting on @Nateowami and @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts` line 13 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-NvFBi7N5p5OkUMj9-Zw:-Nv_XjZuBFePh8okS0Ln:brr9t9b) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-viewer/draft-viewer.service.ts#L13)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

DeltaStatic can help provide a diff but it isn't its only purpose. `DraftDiff` only contains a diff because those were the ops set - it could have any ops if it wanted to. Doesn't need to hold anything up.
</blockquote></details>

Right, I kinda see what you're saying. Given that a set of ops could be (for example) a whole document, I wanted to specify that we should only be passing a diff, which importantly will then be used to update the contents of the target editor. I think my reasoning is still sound, but maybe my implementation wasn't. I thought that specifying that in the name itself would be sufficient to prevent misuse, but maybe we should be doing something else. I'm open to ideas!

(To be clear, I think naming it more generically is the wrong direction to go. Given that DeltaStatic can be more than a diff, we need to be all the more explicit in how we want it to be used here.)
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.scss` line 33 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-NvFAbvj2xtK1zkUonrI:-Nv_cK7-5avPVD9TCWn1:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.scss#L33)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Thanks.
Can you change from `@import` to `@use`. It won't overly affect anything for this PR but it is good practice that we've started introducing to the repo.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts` line 175 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-NvFDEDl01r5yXeQz9_s:-Nv_efHcEm8kSLJqtoPo:bde6zwq) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts#L175)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Fair point.
What about the white space? My question is in relation to showing a dialog to confirm overwriting content and I think that isn't needed if all the content is blanks.
</blockquote></details>

Let's continue this discussion up where your screenshot is.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts` line 184 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-NvFFcwM8-LzOHTWyiT1:-Nv_g3zP7tfiq9eJIkF4:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts#L184)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Well, if it's 3 then go for it :)
Can we at least add the same comment on the methods in `editor.component.ts` as a reminder to update them here as well for now.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-16 07:02 UTC, josephmyers reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2391)* status: 8 of 10 files reviewed, 6 unresolved discussions (waiting on @Nateowami and @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.scss` line 33 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-NvFAbvj2xtK1zkUonrI:-Nv_hc7P0vDC9IscTVM-:b9fv38x) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.scss#L33)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Um this broke the build. Reverting until we figure out why.


<!-- Sent from Reviewable.io -->

2024-04-17 04:17 UTC, nigel-wells requested changes
The previous comment was to fix "DRAFT APPLIED" from appearing when I hadn't applied anything - that is fixed. This instance I wasn't expecting to be able to get into and it may not be related to what you're doing. The source project (I think Mark created?) Only has Genesis Chapter 1 available. When `getGeneratedDraftDeltaOperations`is called it does return valid ops so I must be wrong and had requested a draft at some point. I guess this is still correct and the add button should be available even if it seems like an odd state?

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-:-NveDXAQ8xuEFuaiUZNI:b-5ft9v3)* status: all files reviewed, 6 unresolved discussions (waiting on @josephmyers and @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.scss` line 33 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-NvFAbvj2xtK1zkUonrI:-NveGVen1tW54fW2CRaw:b-sffk6n) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.scss#L33)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Um this broke the build. Reverting until we figure out why.
</blockquote></details>

What exactly broke?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts` line 161 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-NveGN4X4VyCcqXVV79n:-NveGN4X4VyCcqXVV79o:b-tk7cb5) ([raw file](https://github.com/sillsdev/web-xforge/blob/af789d16cc0df367fa7a30d57cebc0f82338fe5d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts#L161)):*
> ```XML
>       if (!proceed) return;
>     } else {
>       return;
> ```

Did you mean to commit this as now nothing happens?


<!-- Sent from Reviewable.io -->

2024-04-17 07:33 UTC, josephmyers reviewed
Yeah, that is odd, but if it's got content, then the button should be there. We can keep an eye on it

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-:-Nvexz_QD_lPkXT236YM:b-lh2019)* status: 9 of 10 files reviewed, 6 unresolved discussions (waiting on @Nateowami, @nigel-wells, and @use)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.scss` line 33 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-NvFAbvj2xtK1zkUonrI:-NveyAebBwrEbsRan8Ff:bb6s7nw) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.scss#L33)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

What exactly broke?
</blockquote></details>

@use
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts` line 161 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-NveGN4X4VyCcqXVV79n:-NveyJkA5QIR4mfJVVvw:b-834n6v) ([raw file](https://github.com/sillsdev/web-xforge/blob/af789d16cc0df367fa7a30d57cebc0f82338fe5d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.ts#L161)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Did you mean to commit this as now nothing happens?
</blockquote></details>

Oops!


<!-- Sent from Reviewable.io -->

2024-04-17 07:37 UTC, josephmyers reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2391)* status: 9 of 10 files reviewed, 6 unresolved discussions (waiting on @Nateowami, @nigel-wells, and @use)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.scss` line 33 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-NvFAbvj2xtK1zkUonrI:-Nvez6A58L5sNfzxt7d8:b-nomyfp) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.scss#L33)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

@use
</blockquote></details>

`@use` -- sorry, Will Hall?


<!-- Sent from Reviewable.io -->

2024-04-17 15:51 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2391)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @nigel-wells and @use)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.scss` line 33 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-NvFAbvj2xtK1zkUonrI:-NvgjtBH1zFC2gOb7QTD:bi9e6fk) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.scss#L33)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

`@use` -- sorry, Will Hall?
</blockquote></details>

`@use` is not identical to `@import`. You will need to make this change as well. Actually, this is part of why `@use` is preferable.
``` diff
-  color: $greenDark;
+  color: variables.$greenDark;
```


<!-- Sent from Reviewable.io -->

2024-04-17 20:50 UTC, nigel-wells requested changes
Agreed.

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-:-Nvhm_pw-uhazFxxOgNW:b-pbdqz3)* status: all files reviewed, 1 unresolved discussion (waiting on @use)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.scss` line 33 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-NvFAbvj2xtK1zkUonrI:-NvhnI_g3Oij1vUmHQcL:b-a036yy) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.scss#L33)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

`@use` is not identical to `@import`. You will need to make this change as well. Actually, this is part of why `@use` is preferable.
``` diff
-  color: $greenDark;
+  color: variables.$greenDark;
```
</blockquote></details>

Sorry, I should have been more specific. Changing `@import 'src/variables';` to `@use 'src/variables';` is the first part. You then need to reference the namespace for the variable as Nathaniel has indicated.


<!-- Sent from Reviewable.io -->

2024-04-18 00:56 UTC, josephmyers reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2391)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @Nateowami, @nigel-wells, and @use)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.scss` line 33 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-NvFAbvj2xtK1zkUonrI:-NvieZm8AMRyw7uDd50G:b-nvr5un) ([raw file](https://github.com/sillsdev/web-xforge/blob/884247983ba124757258a715565a66dda1e4925d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor-draft/editor-draft.component.scss#L33)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Sorry, I should have been more specific. Changing `@import 'src/variables';` to `@use 'src/variables';` is the first part. You then need to reference the namespace for the variable as Nathaniel has indicated.
</blockquote></details>

Ah, good to know.


<!-- Sent from Reviewable.io -->

2024-04-18 01:18 UTC, nigel-wells approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-:-NvimAj37kXZMdME84tJ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Nateowami)



<!-- Sent from Reviewable.io -->

2024-04-18 01:18 UTC, nigel-wells approved these changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2391)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Nateowami)



<!-- Sent from Reviewable.io -->

2024-04-18 03:20 UTC, Nateowami commented
I am seeing a chapter become corrupted after applying a draft. I'm trying to work out what in particular makes this chapter get corrupted, but the build queue is full, so I can't re-generate a draft. I will try again tomorrow.
![](https://github.com/sillsdev/web-xforge/assets/6140710/bde56484-1550-4a8a-87c5-f681d0ad937e)

2024-04-22 07:43 UTC, josephmyers commented
> I am seeing a chapter become corrupted after applying a draft. I'm trying to work out what in particular makes this chapter get corrupted, but the build queue is full, so I can't re-generate a draft. I will try again tomorrow.

I saw this early on in development, when I still had legacy drafts. I haven't seen it with any new drafts. Test hasn't mentioned anything like this, though they did see an error in the History tab which I believe to be related to the new format, and potentially on master, as well. I'm not doing any special processing for the new style (or the old). Maybe that's causing an issue?

2024-04-24 15:14 UTC, Nateowami commented
@josephmyers I can consistently reproduce the problem. It appears it requires there to be two notes in the verse, and that's what triggers it.

2024-04-25 00:53 UTC, josephmyers commented
@Nateowami That is bizarre. Any idea as to the cause or fix? I won't have time this week to do a full research and implementation, so feel free to hijack this PR if time is critical.

2024-04-29 07:43 UTC, josephmyers commented
Yes, I'm seeing this, as well. My chapter looks _really_ messed up.

![image](https://github.com/sillsdev/web-xforge/assets/43733878/f330c473-ebd5-4885-bbfd-135eb6c94d9e)

2024-04-30 03:15 UTC, josephmyers commented
So it sounds like @siltomato has the latest information on this and is the best one suited to finish this bug out. From the brief investigation I did yesterday, you just need to match what Peter's done in the latest Draft Viewer code. It doesn't have this issue.

2024-05-03 20:45 UTC, siltomato reviewed
I made some changes to fix the draft detection issue and the corruption issue.

**To fix corruption**
- Added `TextDocService`
  - Has method to overwrite a `TextDoc` with the supplied delta.
    - This avoids going through the editor and having to handle 'view model' ops like note embeds.
    - Could possibly be used in the future for applying history revisions.
    - Since this is a local change, `TextViewModel` does not respond to update the editor with the changes.
    - So, a new event is emitted that `TextViewModel` can listen to.
  - Has method to get an observable that emits local 'system' changes for a `TextDocId` (emitted by the `overwrite()` method).
- `TextViewModel` is now `@Injectable()`, and is provided at the `TextComponent` level
  - Allows injection of `TextDocService` to listen for local 'system' changes emissions.

**To fix draft existence detection**
- Added request to legacy draft API endpoint to check for draft existence (until better way provided by serval).

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-:-Nx-8Uq78lObRB5cgykb:b-2kv4kp)* status: 3 of 18 files reviewed, 1 unresolved discussion (waiting on @josephmyers, @Nateowami, and @nigel-wells)



<!-- Sent from Reviewable.io -->

2024-05-08 17:48 UTC, Nateowami commented
Excellent work @siltomato! This is working well in my testing.

@nigel-wells or @josephmyers can you review @siltomato's changes?

2024-05-09 00:19 UTC, josephmyers reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-:-NxPi14B2vlRsn4oFDjf:bnfp4nl)* status: 3 of 18 files reviewed, 1 unresolved discussion (waiting on @Nateowami and @nigel-wells)



<!-- Sent from Reviewable.io -->

2024-05-09 09:48 UTC, nigel-wells approved these changes
> Reviewed 11 of 15 files at r8, 3 of 3 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2391)* status: all files reviewed, 1 unresolved discussion (waiting on @josephmyers and @Nateowami)



<!-- Sent from Reviewable.io -->

2024-05-09 09:48 UTC, nigel-wells approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2391#-:-NxRkEU8-EHKsJ266vnV:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @josephmyers and @Nateowami)



<!-- Sent from Reviewable.io -->

2024-05-10 15:56 UTC, merged