SF-2656 Skip the handle called on subscribe.
sillsdev/web-xforge pull request #2447
Opened 2024-05-07 06:02 UTC by josephmyers

Since rxjs calls its event handlers immediately after subscribing to them, the verse change subscription value gets initially set to -1, given the currentTime will be 0 and not resolve to any segment in the timing data. And since we're using distinctUntilChanged(), the handler isn't called again until we reach a found index, e.g. the chapter header/title.

This was causing the software to keep the previous highlight when playing chapter audio until the first timing index was reached. This was confusing for users.

My change ignores the handle called on subscribe, when the time was 0 and the audio hasn't fully loaded yet. Now, the first time the event is handled, the audio will be playing, and thus the checking component will update/clear the highlight correctly.

2024-05-13 03:34 UTC, pmachapman requested changes
I am not sure skipping is the best option? From what I understand, `BehaviorSubject` will always emit the latest value when subscribed to. In the case of the component initialization, the undefined value will be emitted (and so it is useful to skip, as per your change). Your skip is relying on the `AudioPlayer` to have just been initialized, rather than perhaps mid playback when `timeUpdated$` is subscribed to.

What if we changed `timeUpdated$` to a `Subject<void>`? This would mean that when it is subscribed to, it will not emit the previous event, just any following `this.timeUpdated$.next();` calls.

If I am misunderstanding things (rxjs is not an area I am strong in), let me know, then I will happily approve, as the test, etc look good.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2447#-:-NxjzTev-4qV_zTW6PeJ:b-n0gxz4)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @josephmyers)



<!-- Sent from Reviewable.io -->

2024-05-13 05:43 UTC, josephmyers reviewed
Sure, thanks for the feedback. I like your idea better!

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2447#-:-NxkS_RG8ywCn9uzjtIb:b856x55)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @josephmyers)



<!-- Sent from Reviewable.io -->

2024-05-13 19:39 UTC, pmachapman approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2447#-:-NxnShse3h4rknE1DFhp:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @josephmyers)



<!-- Sent from Reviewable.io -->

2024-05-20 22:35 UTC, pmachapman approved these changes
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2447)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @josephmyers)



<!-- Sent from Reviewable.io -->

2024-06-03 15:18 UTC, merged