SF-2730 Specify null when scripture range is empty for Serval builds
sillsdev/web-xforge pull request #2453
Opened 2024-05-12 21:46 UTC by pmachapman

This PR fixes a bug where Serval returns a 400 error when starting a build that has no training books specified.

This bug currently affects QA.

2024-05-13 08:24 UTC, josephmyers requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2453)* status: all files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs` line 838 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2453#-Nxl20Tl0WDGUoOPFRIf:-Nxl20Tm7rl4QnZq0GGG:b-xf4c8v) ([raw file](https://github.com/sillsdev/web-xforge/blob/7d870346517157cc3702f125da4f287e44e0d0f8/test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs#L838)):*
> ```Smalltalk
> 
>     [Test]
>     public async Task BuildProjectAsync_SpecifiesNullScriptureRangeIfEmpty()
> ```

Given that these two tests are essentially the same other than the input, can we not use TestCase to combine these two into a single test? It would have two test cases, one for blank and one for empty.


<!-- Sent from Reviewable.io -->

2024-05-13 19:37 UTC, pmachapman reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2453)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @josephmyers)

___
*[`test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs` line 838 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2453#-Nxl20Tl0WDGUoOPFRIf:-NxnSP470J8sDPS-DHOS:b-jsrqjm) ([raw file](https://github.com/sillsdev/web-xforge/blob/7d870346517157cc3702f125da4f287e44e0d0f8/test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs#L838)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Given that these two tests are essentially the same other than the input, can we not use TestCase to combine these two into a single test? It would have two test cases, one for blank and one for empty.
</blockquote></details>

Done. Great idea!


<!-- Sent from Reviewable.io -->

2024-05-14 00:35 UTC, josephmyers approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

Awesome, thanks

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2453#-:-NxoWXcr2WCIlD672tLn:bsdl95b)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)



<!-- Sent from Reviewable.io -->

2024-05-14 15:32 UTC, Nateowami reviewed
@josephmyers I have no option to generate a new draft here:

![](https://files.reviewableusercontent.io/images/reviewable/6140710/ZB6nqdxAg0vCyguV3jR7d5vx/Screenshot%20from%202024-05-14%2011-31-38.png)

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2453#-:-Nxrima41WfnwzpLArTv:b-agurss)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @pmachapman)



<!-- Sent from Reviewable.io -->

2024-05-14 15:32 UTC, Nateowami reviewed
Previous comment was on the wrong PR. My mistake.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2453#-:-NxriyJE37i2nD6S3g42:bdjpmtl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @pmachapman)



<!-- Sent from Reviewable.io -->

2024-05-15 14:47 UTC, merged