SF-2732 Hide history tab option when viewing a resource project
sillsdev/web-xforge pull request #2510
Opened 2024-06-06 19:25 UTC by RaymondLuong3

Resource projects have a 16 character paratextId. This PR determines if the active project is a resource and will hide the option to show the project history in a tab.

2024-06-07 02:34 UTC, nigel-wells commented
This seems good. Funnily enough the resource check you did is almost identical to the one @marksvc has implemented for the new my projects page except you both chose different service files to put it in 😃  I'm not sure which PR should be let in first to implement that code 🤔

2024-06-10 17:56 UTC, RaymondLuong3 commented
Right! And SF-1444 is currently being tested to also implement the resource check. So there are 3 PRs introducing this change. Perhaps we wait for SF-1444 and then we can rebase this on top.

2024-06-11 16:57 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2510)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @nigel-wells and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/core/paratext.service.ts` line 40 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2510#-O-7DCxx94nkV-Cejysi:-O-7DCxx94nkV-Cejysj:b-1bp2pr) ([raw file](https://github.com/sillsdev/web-xforge/blob/ae068bfcf0fab605dfd3312084766aa3fe329484/src/SIL.XForge.Scripture/ClientApp/src/app/core/paratext.service.ts#L40)):*
> ```XML
>    */
>   static isResource(paratextId: string): boolean {
>     return paratextId.length === RESOURCE_IDENTIFIER_LENGTH;
> ```

This logic is duplicated in https://github.com/sillsdev/web-xforge/blob/575bc06df329160d35cabb99c5be2b4f635e1d57/src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-administration.service.ts#L45

Also, in Marks' PR linked by Nigel, I like that it passes a project to the function, not just the ID. We may have new project types in the future, and not be able to use just the ID to determine what type it is. In fact, it's kind of a happy accident that we can determine project type this way; I think we really should a have a property on each project saying what type it is, and we may add that in the future.


<!-- Sent from Reviewable.io -->

2024-06-11 22:08 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2510)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @Nateowami and @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/core/paratext.service.ts` line 40 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2510#-O-7DCxx94nkV-Cejysi:-O-8KyAn6l3HwRclS2v0:b-h1h4mt) ([raw file](https://github.com/sillsdev/web-xforge/blob/ae068bfcf0fab605dfd3312084766aa3fe329484/src/SIL.XForge.Scripture/ClientApp/src/app/core/paratext.service.ts#L40)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This logic is duplicated in https://github.com/sillsdev/web-xforge/blob/575bc06df329160d35cabb99c5be2b4f635e1d57/src/SIL.XForge.Scripture/ClientApp/src/app/serval-administration/serval-administration.service.ts#L45

Also, in Marks' PR linked by Nigel, I like that it passes a project to the function, not just the ID. We may have new project types in the future, and not be able to use just the ID to determine what type it is. In fact, it's kind of a happy accident that we can determine project type this way; I think we really should a have a property on each project saying what type it is, and we may add that in the future.
</blockquote></details>

The duplicate logic will be removed in SF-2444. I think the current plan is to wait for that PR before moving this one forward.


<!-- Sent from Reviewable.io -->

2024-06-12 17:21 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2510)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @Nateowami and @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/core/paratext.service.ts` line 40 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2510#-O-7DCxx94nkV-Cejysi:-O-CS8z-4VtkLvQIqxNu:bj86v8m) ([raw file](https://github.com/sillsdev/web-xforge/blob/ae068bfcf0fab605dfd3312084766aa3fe329484/src/SIL.XForge.Scripture/ClientApp/src/app/core/paratext.service.ts#L40)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

The duplicate logic will be removed in SF-2444. I think the current plan is to wait for that PR before moving this one forward.
</blockquote></details>

Ok, the duplicate logic is now removed. In Marks PR, there are 2 versions of `isResource`. One checks the project, while the other checks the paratextId. We cannot remove the `isResource(paratextId)` because in the `serval-project.component` we need to know if drafting source or alternate source are resources based on their paratext ids. It seems we either keep both, or we have to discard the `isResource(sfProject)` version.


<!-- Sent from Reviewable.io -->

2024-06-12 17:22 UTC, RaymondLuong3 reviewed
@nigel-wells Now that SF-2444 is merged, this is ready for a review.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2510#-:-O-CT7QJ1f6Y9UD08mhB:bg60g1o)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @Nateowami and @nigel-wells)



<!-- Sent from Reviewable.io -->

2024-06-17 02:59 UTC, nigel-wells requested changes
Looks good to me - just one tweak to the tests.

> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2510#-:-O-Z7_Of-fOe6MLsrs6X:b-slsnix)* status: all files reviewed, 2 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/core/permissions.service.spec.ts` line 32 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2510#-O-Z7Abx2ii_7e_FKKlP:-O-Z7Abx2ii_7e_FKKlQ:b-5xi1d3) ([raw file](https://github.com/sillsdev/web-xforge/blob/8e0c97a712b7d51b51d39a463dee8a4aba842164/src/SIL.XForge.Scripture/ClientApp/src/app/core/permissions.service.spec.ts#L32)):*
> ```XML
>   afterEach(() => {
>     // suppress no expectations warning
>     expect(true).toBe(true);
> ```

I think it would be better to add `expect().nothing();` to the relevant tests that don't "expect" something (because they use "verify") then a catch all over everything now (and in the future) which might hide something important. It's only 2 tests that need it by the looks.


<!-- Sent from Reviewable.io -->

2024-06-26 22:45 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2510)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @Nateowami and @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/core/permissions.service.spec.ts` line 32 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2510#-O-Z7Abx2ii_7e_FKKlP:-O0Li9Yc4RyfOwdLgr6g:b-eguevs) ([raw file](https://github.com/sillsdev/web-xforge/blob/8e0c97a712b7d51b51d39a463dee8a4aba842164/src/SIL.XForge.Scripture/ClientApp/src/app/core/permissions.service.spec.ts#L32)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

I think it would be better to add `expect().nothing();` to the relevant tests that don't "expect" something (because they use "verify") then a catch all over everything now (and in the future) which might hide something important. It's only 2 tests that need it by the looks.
</blockquote></details>

Yes, I think that is the right way to go. I saw this type of suppression come in on other PR's and just followed the convention.


<!-- Sent from Reviewable.io -->

2024-06-27 03:04 UTC, nigel-wells approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2510#-:-O0MdlrY44fo6gaaIUkw:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)



<!-- Sent from Reviewable.io -->

2024-06-28 16:04 UTC, merged