SF-2758 Cause import questions dialog buttons to stack on small devices
sillsdev/web-xforge pull request #2511
Opened 2024-06-06 20:13 UTC by RaymondLuong3

Before

![Import questions dialog before](https://github.com/sillsdev/web-xforge/assets/17931130/5117992d-99f2-4c6c-9d60-0d129e1747b4)

After

![Import Questions Dialog After](https://github.com/sillsdev/web-xforge/assets/17931130/c595b603-f56f-4517-95b1-b168d2d7e0ec)

2024-06-07 02:47 UTC, nigel-wells requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2511)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.scss` line 61 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2511#-Nzk_Zr707Xv_Z9A5ZS4:-Nzk_Zr707Xv_Z9A5ZS5:b-yyz3jt) ([raw file](https://github.com/sillsdev/web-xforge/blob/cbebb0f3e6f16f2e52180d44fdd6efe5d51f529e/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.scss#L61)):*
> ```SCSS
> 
>   mat-card-actions {
>     display: unset;
> ```

I'd suggest we use `flex-wrap: wrap;` instead. The card actions is using flex which includes some nice alignment features which we'd want to keep.

You could optional add a `gap` if you felt the buttons were too close together as they are technically touching but the background on one is white so it looks ok.


<!-- Sent from Reviewable.io -->

2024-06-07 18:07 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2511)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.scss` line 61 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2511#-Nzk_Zr707Xv_Z9A5ZS4:-NznpObLBJc1_lSwrowQ:b-k6u8gq) ([raw file](https://github.com/sillsdev/web-xforge/blob/cbebb0f3e6f16f2e52180d44fdd6efe5d51f529e/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.scss#L61)):*
`display: unset` will virtually never be the best option. See the definition of unset at MDN https://developer.mozilla.org/en-US/docs/Web/CSS/unset:

> The **`unset`** CSS keyword resets a property to its inherited value if the property naturally inherits from its parent, and to its [initial value](https://developer.mozilla.org/en-US/docs/Web/CSS/initial_value) if not. In other words, it behaves like the [`inherit`](https://developer.mozilla.org/en-US/docs/Web/CSS/inherit) keyword in the first case, when the property is an [inherited property](https://developer.mozilla.org/en-US/docs/Web/CSS/Inheritance#inherited_properties), and like the [`initial`](https://developer.mozilla.org/en-US/docs/Web/CSS/initial) keyword in the second case, when the property is a [non-inherited property](https://developer.mozilla.org/en-US/docs/Web/CSS/Inheritance#non-inherited_properties).

Understanding what this line does requires:
1. Knowing the meaning of `unset` defined above
2. Knowing whether the property at hand is inherited or not ([MDN says it's not](https://developer.mozilla.org/en-US/docs/Web/CSS/display#formal_definition))
3. Knowing what the default value is (`inline`, [according to MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/display#formal_definition))

So, this will be the same as setting `display: inline`. Except that it won't; if you check dev tools you'll find it ends up being a block element, even though the default value for `display` is `inline`. I *think* this is because being a child of a flex container changes the default display value, but I can't even find the documentation that says that.

Tl;dr: Be as explicit about what value a CSS property should be set to as possible. 

I would concur with Nigel's suggestion, and add that when you hover the button you can see that there's no gap with the other button, so adding a 8px gap would probably be a good idea.


<!-- Sent from Reviewable.io -->

2024-06-10 17:41 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2511)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.scss` line 61 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2511#-Nzk_Zr707Xv_Z9A5ZS4:-O-2DxxQAdefk0ERp6im:bg44ixj) ([raw file](https://github.com/sillsdev/web-xforge/blob/cbebb0f3e6f16f2e52180d44fdd6efe5d51f529e/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.scss#L61)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

`display: unset` will virtually never be the best option. See the definition of unset at MDN https://developer.mozilla.org/en-US/docs/Web/CSS/unset:

> The **`unset`** CSS keyword resets a property to its inherited value if the property naturally inherits from its parent, and to its [initial value](https://developer.mozilla.org/en-US/docs/Web/CSS/initial_value) if not. In other words, it behaves like the [`inherit`](https://developer.mozilla.org/en-US/docs/Web/CSS/inherit) keyword in the first case, when the property is an [inherited property](https://developer.mozilla.org/en-US/docs/Web/CSS/Inheritance#inherited_properties), and like the [`initial`](https://developer.mozilla.org/en-US/docs/Web/CSS/initial) keyword in the second case, when the property is a [non-inherited property](https://developer.mozilla.org/en-US/docs/Web/CSS/Inheritance#non-inherited_properties).

Understanding what this line does requires:
1. Knowing the meaning of `unset` defined above
2. Knowing whether the property at hand is inherited or not ([MDN says it's not](https://developer.mozilla.org/en-US/docs/Web/CSS/display#formal_definition))
3. Knowing what the default value is (`inline`, [according to MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/display#formal_definition))

So, this will be the same as setting `display: inline`. Except that it won't; if you check dev tools you'll find it ends up being a block element, even though the default value for `display` is `inline`. I *think* this is because being a child of a flex container changes the default display value, but I can't even find the documentation that says that.

Tl;dr: Be as explicit about what value a CSS property should be set to as possible. 

I would concur with Nigel's suggestion, and add that when you hover the button you can see that there's no gap with the other button, so adding a 8px gap would probably be a good idea.
</blockquote></details>

Great idea. Thanks for the info. Yes, I agree that whenever we can be explicit, it is best to do that because it will limit the chance of misunderstanding. I'll make these improvements.


<!-- Sent from Reviewable.io -->

2024-06-11 01:00 UTC, nigel-wells approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2511#-:-O-3ntt8DZXQuq_Rhp4m:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2024-06-11 01:03 UTC, merged