SF-2776 Cannot download a previously generated draft when generating a new draft
sillsdev/web-xforge pull request #2516
Opened 2024-06-11 19:20 UTC by pmachapman

This PR fixes a bug that causes the download/view draft functionality to disappear when you generate a new draft, and you already have a previous completed draft.

2024-06-12 07:28 UTC, josephmyers requested changes
Sorry for the confusion, Peter. We intentionally removed this a couple weeks ago. It's unfortunate you've already spent the time to add it back! Unless you know something I don't? Maybe @Nateowami has some input here

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2516#-:-O-AKq9604zHUvW_tgX5:b-cxpqwa)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)



<!-- Sent from Reviewable.io -->

2024-06-12 08:21 UTC, pmachapman reviewed
@josephmyers No problem - it didn't take me long to write. I noticed it while testing Serval QA, and trying to access a draft I generated while generating a new one (it looked like a bug cause by the zip PR I wrote, so I thought to fix it as it was holding up my testing). No problem if @Nateowami thinks it should be declined. 

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2516#-:-O-AVuo5B2X9goBz5-Et:b60e0o7)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)



<!-- Sent from Reviewable.io -->

2024-06-12 17:41 UTC, Nateowami commented
@josephmyers is correct that we did come to this conclusion, though by my recollection it was mainly because couldn't find a good way to fit it in at the same time, and we left it as something we might add back in the future. 

I actually think the way this PR brings it back looks fine to me. I've added this as a topic of discussion for our next meeting.

Let's put this PR on hold until we have that discussion though.

2024-06-18 01:11 UTC, josephmyers approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

Nathaniel and I talked about this in person. The main reason we removed it was out of convenience. I'm also not confident we have a large user demand for it, but we know of at least one person :D

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2516#-:-O-ctGupEw7nPh-FfeYU:b-2iszag)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)



<!-- Sent from Reviewable.io -->

2024-06-18 20:28 UTC, Nateowami commented
@josephmyers The Jira card should have been moved to "ready to test" when this PR was approved. I've moved it.

2024-06-19 00:59 UTC, josephmyers commented
Thanks, I've updated the label

2024-06-26 15:24 UTC, merged