Fix paratext login button content misaligned
sillsdev/web-xforge pull request #2524
Opened 2024-06-13 20:01 UTC by RaymondLuong3

Paratext login button was misaligned due to the mat-button mdc upgrade
Before
![Paratext logo button before](https://github.com/sillsdev/web-xforge/assets/17931130/3dbeb568-47c4-4072-875a-4f2b2ccdb075)

After
![Paratext logo button](https://github.com/sillsdev/web-xforge/assets/17931130/e13814ab-dff2-4165-b772-74eecfa980fb)

2024-06-14 01:11 UTC, Nateowami requested changes
There's a cleaner option. Make the image a `mat-icon`:
``` html
<mat-icon><img src="/assets/images/logo-pt9.png" alt="Paratext Logo" class="paratext-logo" /></mat-icon>
{{ t("log_in_to_paratext") }}
```
Then simplify the CSS (for example, here's what I did in the sync component):
```diff
 .paratext-logo {
-  width: 2rem;
-  height: 2rem;
-  margin-right: 0.5rem;
+  width: 100%;
 }
```

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2524#-:-O-JHPbvEchem4zVlDYp:bg2j5hl)* status: 0 of 3 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-06-18 02:33 UTC, josephmyers commented
SF-2789

2024-06-26 21:16 UTC, RaymondLuong3 reviewed
Thanks. I do think that looks better, even with the smaller icon. Here are the images of the updated components.
![Paratext logo sync.png](https://files.reviewableusercontent.io/images/reviewable/17931130/XvBqscgReFSiJZ3x5C3o9nox/Paratext%20logo%20sync.png)
![Paratext logo settings.png](https://files.reviewableusercontent.io/images/reviewable/17931130/lpr5YqeET69Xfw699qkEoYdy/Paratext%20logo%20settings.png)
![Paratext logo Connect projects.png](https://files.reviewableusercontent.io/images/reviewable/17931130/_7xrNEIs6vi6ky1nFt_yfO2i/Paratext%20logo%20Connect%20projects.png)

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2524#-:-O0LOmsG7WQnQtmELVQ0:bgm0u26)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @Nateowami)



<!-- Sent from Reviewable.io -->

2024-06-26 21:45 UTC, Nateowami approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2524#-:-O0LVgtTClIfeDXV2FRt:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2024-06-27 04:34 UTC, merged