SF-2687 Remove global styles for checkboxes.
sillsdev/web-xforge pull request #2557
Opened 2024-07-01 08:31 UTC by josephmyers

This fixes a click area bug in roles and permissions dialog.

I did need a couple of these rules in the settings page, since the whole page is structured off the assumption that the checkboxes are that height. Using the default sizing really messes with the page layout.

2024-07-02 00:41 UTC, pmachapman approved these changes
The change looks good, but it breaks some alignments for checkboxes in these areas:

The PR is on the left, QA on the right.

Connect to Project:
![image.png](https://files.reviewableusercontent.io/images/reviewable/8665431/QVAeMYGvCwd5KY97AnFXS46J/image.png)

Feature Flags: (I think this is too far spaced out now?)
![image copy 1.png](https://files.reviewableusercontent.io/images/reviewable/8665431/adfy6u-IWgachT2SxSoh0N-G/image.png)

The PR does make alignment/spacing changes elsewhere, but I think these are an improvement (i.e. for import questions, serval admin)

> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2557#-:-O0koDV-2x92kdwS6b37:b-wc5193)* status: 1 of 2 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2024-07-02 00:42 UTC, pmachapman requested changes
Accidentally clicked approve :-/

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2557#-:-O0kt0gz6Mt0eGDe8xpP:b-t7i15w)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @josephmyers)



<!-- Sent from Reviewable.io -->

2024-07-02 07:50 UTC, josephmyers reviewed
Thanks. I totally missed those

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2557#-:-O0mPymkAPcntAAMts4t:bz00zy)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @pmachapman)



<!-- Sent from Reviewable.io -->

2024-07-02 13:31 UTC, Nateowami submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2557)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @josephmyers and @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flags-dialog.component.scss` line 19 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2557#-O0ncja88shXcNKe5dqf:-O0ncja88shXcNKe5dqg:b-5dpqmn) ([raw file](https://github.com/sillsdev/web-xforge/blob/3957fc897f72e556b45f2fd1874a00d96a37e8d0/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flags-dialog.component.scss#L19)):*
> ```SCSS
> 
> .mat-mdc-checkbox {
>   --mdc-checkbox-state-layer-size: 18px;
> ```

I think this is the wrong approach, both here and on other pages. If there's too much spacing, just adjust the spacing to fit. For example, in this dialog, it's a simple matter of removing the row-gap several lines up.

Otherwise, I have serious concerns that this won't survive another Material upgrade without needing changes yet again.


<!-- Sent from Reviewable.io -->

2024-07-03 03:50 UTC, josephmyers reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2557)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @Nateowami and @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flags-dialog.component.scss` line 19 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2557#-O0ncja88shXcNKe5dqf:-O0psH-T5t2cnbbeC05J:b-c3cz6x) ([raw file](https://github.com/sillsdev/web-xforge/blob/3957fc897f72e556b45f2fd1874a00d96a37e8d0/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flags-dialog.component.scss#L19)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I think this is the wrong approach, both here and on other pages. If there's too much spacing, just adjust the spacing to fit. For example, in this dialog, it's a simple matter of removing the row-gap several lines up.

Otherwise, I have serious concerns that this won't survive another Material upgrade without needing changes yet again.
</blockquote></details>

That works for the simplest page, sure. The other pages obviously aren't that simple. I've updated all cases to remove the overrides.


<!-- Sent from Reviewable.io -->

2024-07-03 19:57 UTC, pmachapman requested changes
Thank you for the tweaks you have made in this PR.

Just one minor nit. If you think the nit shouldn't be fixed, let me know and I will approve this!

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2557#-:-O0u9_zR1jw8MWVsiPWU:b-5jt3ot)* status: all files reviewed, 2 unresolved discussions (waiting on @josephmyers and @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html` line 268 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2557#-O0u8d_x9MexJm19OKGs:-O0u8d_x9MexJm19OKGt:bk6xbq4) ([raw file](https://github.com/sillsdev/web-xforge/blob/3a724ad176c8ce7df48a3656ab2342cdc8a37c2c/src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html#L268)):*
> ```HTML
>                     id="checkbox-hide-community-checking-text"
>                     >{{ t("hide_community_checking_text") }}</mat-checkbox
>                   >
> ```

Nit: The autoformatting here is kind of crazy. Are you able to push `{{ t("hide_community_checking_text") }}` onto a new line, which should make the start and end tags look more normal?

i.e.
```html
                  <mat-checkbox formControlName="hideCommunityCheckingText" id="checkbox-hide-community-checking-text">
                    {{ t("hide_community_checking_text") }}
                  </mat-checkbox>
```



_Code quote:_
```HTML
                  <mat-checkbox
                    formControlName="hideCommunityCheckingText"
                    id="checkbox-hide-community-checking-text"
                    >{{ t("hide_community_checking_text") }}</mat-checkbox
                  >
```


<!-- Sent from Reviewable.io -->

2024-07-04 01:05 UTC, josephmyers reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2557)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @Nateowami and @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html` line 268 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2557#-O0u8d_x9MexJm19OKGs:-O0vGSoJ-Wo1LL54P2F6:b-gakyhq) ([raw file](https://github.com/sillsdev/web-xforge/blob/1272a9a4208d6b0e63c2c428fa9142b7c561ee6c/src/SIL.XForge.Scripture/ClientApp/src/app/settings/settings.component.html#L268)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Nit: The autoformatting here is kind of crazy. Are you able to push `{{ t("hide_community_checking_text") }}` onto a new line, which should make the start and end tags look more normal?

i.e.
```html
                  <mat-checkbox formControlName="hideCommunityCheckingText" id="checkbox-hide-community-checking-text">
                    {{ t("hide_community_checking_text") }}
                  </mat-checkbox>
```
</blockquote></details>

Thanks. It's annoying when it does that!


<!-- Sent from Reviewable.io -->

2024-07-04 01:08 UTC, pmachapman approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2557#-:-O0vHKfg4mHNPMnwY8So:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)



<!-- Sent from Reviewable.io -->

2024-07-08 02:53 UTC, pmachapman approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2557)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)



<!-- Sent from Reviewable.io -->

2024-07-08 17:09 UTC, RaymondLuong3 commented
@josephmyers It looks like chromatic caught an issue with the global styles changes. Have a look at it. I was about to merge it until I say the chromatic check.

2024-07-09 00:05 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2557)* status: 5 of 8 files reviewed, 2 unresolved discussions (waiting on @josephmyers and @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/styles.scss` line 87 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/2557#-O1JnhUz9IqGHPNLVz8C:-O1JnhUz9IqGHPNLVz8D:bob1b6w) ([raw file](https://github.com/sillsdev/web-xforge/blob/b7371adb916ba005f6367e9390897828b448f83e/src/SIL.XForge.Scripture/ClientApp/src/styles.scss#L87)):*
> ```SCSS
> 
> .mat-mdc-checkbox {
>   --mdc-checkbox-unselected-focus-state-layer-opacity: 0.08;
> ```

What is the purpose of this?


<!-- Sent from Reviewable.io -->

2024-07-09 00:46 UTC, josephmyers commented
> @josephmyers It looks like chromatic caught an issue with the global styles changes. Have a look at it. I was about to merge it until I say the chromatic check.

> What is the purpose of this?

I only see one change in Chromatic, and it's specifically either the checkbox "hover" or "focus" color (in Bulk Import). A test comment caused me to evaluate this and closely surrounding behaviors, and I think we can improve the experience. On this dialog, and where other checkboxes are, except for one state there is no "focus" indicator (e.g. keyboard navigation), default for Material, which I wanted to accept when possible, given this entire PR. Removing the global styles reinstated this indicator and made keyboard navigation consistent; however, the color for unchecked state was jarring, being much darker than the adjacent checked state color, so I lightened it.

2024-07-11 18:12 UTC, RaymondLuong3 commented
@josephmyers in the UI tests, there is one that needed to be reviewed. You can see it in the check titled UI Tests. It looks like the selection box background color is bright green?
https://www.chromatic.com/test?appId=644bffe327c540a62f0fd260&id=668c16058056aec6e9109506

2024-07-12 19:40 UTC, Nateowami reviewed
@RaymondLuong3 That's the diff. Turn off the diff, and you'll see it's a different color of grey.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2557#-:-O1cSQgeAVKroZDQP_4F:bd1kap0)* status: 5 of 8 files reviewed, 2 unresolved discussions (waiting on @josephmyers and @pmachapman)



<!-- Sent from Reviewable.io -->

2024-07-12 19:50 UTC, RaymondLuong3 commented
You are right. My mistake! I approved the UI changes

2024-07-15 05:13 UTC, josephmyers reviewed
> Dismissed @Nateowami from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2557)* status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @pmachapman)



<!-- Sent from Reviewable.io -->

2024-07-15 05:23 UTC, josephmyers commented
@pmachapman apparently GH thinks there's an unresolved discussion on Reviewable, though Reviewable doesn't show anything to me. This PR appears to be waiting on you. Can you re-approve?

@Nateowami also had some comments which I have addressed and resolved. Feel free to push back on those

2024-07-15 06:30 UTC, pmachapman approved these changes
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2557)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @josephmyers)



<!-- Sent from Reviewable.io -->

2024-07-16 02:38 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2557)* status: 6 of 8 files reviewed, all discussions resolved (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/styles.scss` line 87 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/2557#-O1JnhUz9IqGHPNLVz8C:-O1tOiqZ0Pvic85ZCqGy:b-s098ug) ([raw file](https://github.com/sillsdev/web-xforge/blob/acf01a70d9344ca6a32dafca390b9dd51d74a7b1/src/SIL.XForge.Scripture/ClientApp/src/styles.scss#L87)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

What is the purpose of this?
</blockquote></details>

Still don't understand your rationale, but I'm resolving as I'm not around to have the conversation. 


<!-- Sent from Reviewable.io -->

2024-07-16 03:07 UTC, josephmyers reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2557)* status: 6 of 8 files reviewed, all discussions resolved (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/styles.scss` line 87 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/2557#-O1JnhUz9IqGHPNLVz8C:-O1tTc2R7iBh362CMDmr:b-v12r83) ([raw file](https://github.com/sillsdev/web-xforge/blob/acf01a70d9344ca6a32dafca390b9dd51d74a7b1/src/SIL.XForge.Scripture/ClientApp/src/styles.scss#L87)):*
Apologies. I tried to answer this above but didn't see any further objections. It seemed like your and Raymond's concerns were addressed.

> Removing the global styles reinstated this indicator and made keyboard navigation consistent; however, the color for unchecked state was jarring, being much darker than the adjacent checked state color, so I lightened it.

In my mind, both the purpose and rationale are here. Is there something I can explain more?


<!-- Sent from Reviewable.io -->

2024-07-16 14:50 UTC, pmachapman approved these changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2557)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @josephmyers)



<!-- Sent from Reviewable.io -->

2024-07-17 00:27 UTC, merged