SF-2617 Add ability to add a draft by book
sillsdev/web-xforge pull request #2571
Opened 2024-07-04 22:32 UTC by RaymondLuong3

This PR adds the ability for a user to add the draft of an entire book. Along with the added feature, I refactored the code that handled applying a draft, removed it from the `editor-draft` component, and moved it to the `draft-viewer` service which has been renamed `draft-handling.service`.

Adding draft to the book
![image](https://github.com/sillsdev/web-xforge/assets/17931130/652e813b-a392-43ae-ac30-9dc84dee2684)

Confirmation dialog
![image](https://github.com/sillsdev/web-xforge/assets/17931130/82473ec1-c9f7-465b-a711-b3bfb078ea8e)

Drafts did not apply message
![image](https://github.com/sillsdev/web-xforge/assets/17931130/3a732c67-dcf6-4b97-91e2-bb6ec00af8bc)

2024-07-04 22:36 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2571)* status: 0 of 13 files reviewed, 1 unresolved discussion

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.html` line 4 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2571#-O0zsYcV0x5krWguTtRc:-O0zsYcV0x5krWguTtRd:btxdsv8) ([raw file](https://github.com/sillsdev/web-xforge/blob/528379ec042fd191d1e4358aa0aa6e38c4646687/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-preview-books/draft-preview-books.component.html#L4)):*
> ```HTML
>   @for (book of booksWithDrafts$ | async; track book.bookNumber) {
>   <div class="draft-book-option">
>     <a [routerLink]="linkForBookAndChapter(book.bookNumber, book.chaptersWithDrafts[0])">
> ```

I am not big fan of the <a> tag here which makes the word of the book clickable, but it is no longer a button. This was the best solution I could come up with that matched the design in balsamiq. I am very open to suggestions on a better implementation.



_Code quote:_
```HTML
    <a [routerLink]="linkForBookAndChapter(book.bookNumber, book.chaptersWithDrafts[0])">
```


<!-- Sent from Reviewable.io -->

2024-07-04 22:54 UTC, nigel-wells commented
Are you able to take a similar approach you did in the note dialog?
![image](https://github.com/sillsdev/web-xforge/assets/17464863/62dbcc8e-0249-4af6-b162-e81f34914bfe)
The spacing around the icon I think is too much but you should be able to adjust that to suit.

2024-07-05 22:51 UTC, RaymondLuong3 reviewed
I think that could work. How does this look? I think it could look better without the dividing line.
![image.png](https://files.reviewableusercontent.io/images/reviewable/17931130/x6HG_oIGvZQULBygejeDV3qZ/image.png)

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2571#-:-O144wFU4oQ0fNlZtcBH:bmjkyxm)* status: 0 of 13 files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2024-07-07 23:28 UTC, pmachapman requested changes
The code looks good. Just one question and a bug:

Is the text in the buttons supposed to looks like hyperlinks? I tested in Chrome and Firefox on Windows:
![image.png](https://files.reviewableusercontent.io/images/reviewable/8665431/MKVsVX9WcFfEZyFH8hAM-JF9/image.png)

Also, I was able to add to project for a book that my user did not have permission to edit in Scripture Forge:
![image copy 1.png](https://files.reviewableusercontent.io/images/reviewable/8665431/66YSwG0_bQxg0mHuZIFNOztj/image.png)

I appreciate the refactoring, and a small heads up that [SF-2802](https://github.com/sillsdev/web-xforge/pull/2556) which is currently in testing will affect your PR (in a minor way), particularly the addition of the source argument to `overwrite()`:
```ts
await this.textDocService.overwrite(this.textDocId!, this.draftDelta, 'Draft');
```

> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2571#-:-O1ECr1hBCv-Q02sX3kf:b88ymem)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2024-07-07 23:33 UTC, nigel-wells commented
That is looking much better @RaymondLuong3 . I'd remove the dividing line if you can. The layout should be similar to this date picked component. Can you reset the padding you have on the left/right of the main button so the text isn't so close to the edges. The vertical dot icon still needs the normal (small?) padding around it so that fat fingers aren't trying to push two buttons at the same time - the screenshot below shows what it should be.
![image](https://github.com/sillsdev/web-xforge/assets/17464863/52097120-2dd7-418f-9ba1-4ce887e7c6bf)

2024-07-09 22:48 UTC, RaymondLuong3 reviewed
Thanks Nigel. This looks different from what is in [balsamiq](https://balsamiq.cloud/sghq53/pejrlz8/r1550). I came up with this look to match more with what is in balsamiq.
@pmachapman I have fixed the issue with text permissions. Now there is a chapter level check before applying the draft to the chapter of a book. In addition to that, I've added a book level check which will notify the user if they do not have book level edit permissions.

![Draft books add menu.png](https://files.reviewableusercontent.io/images/reviewable/17931130/NKdcAxFEI_gMyvowJjVP148w/Draft%20books%20add%20menu.png)

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2571#-:-O1OeLQF3pPILUIYXk4W:b-pmhcls)* status: 6 of 13 files reviewed, all discussions resolved (waiting on @pmachapman)



<!-- Sent from Reviewable.io -->

2024-07-09 23:12 UTC, nigel-wells commented
Amazing @RaymondLuong3  - I think that looks great!

2024-07-10 02:25 UTC, pmachapman approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> What @nigel-wells said :-)

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2571#-:-O1PSHuM2G4zl0PaMHSm:b-dlml15)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2024-07-15 16:01 UTC, merged