Improve draft preview books appearance and implementation
sillsdev/web-xforge pull request #2604
Opened 2024-07-23 02:37 UTC by Nateowami

### Before

![](https://github.com/user-attachments/assets/71f27904-06eb-42fb-8f26-65da6067ec10)

### After

![](https://github.com/user-attachments/assets/e67d6efe-ad77-4b65-8fd3-289f2d274ce8)

2024-07-24 20:22 UTC, Nateowami commented
@RaymondLuong3 Not trying to keep you from reviewing this. I requested Joseph because he and I had talked about this design, so I thought he might be a relevant party to look at it. Probably would have been better to just `@mention` him with a comment saying "here's what we discussed earlier", as that would probably communicate to everyone more clearly.

2024-07-24 21:54 UTC, RaymondLuong3 commented
No problem. I am happy to let Joseph review. I think I might be reviewed-out today

2024-07-29 02:51 UTC, josephmyers requested changes
This makes sense to me, and it's a good improvement. Can you shift the `mat-icon` (or its contents) up a pixel? The first thing I notice is that it's vertically off center.

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2604#-:-O2wONLy32hZuKXPVbmq:b-z3ywgz)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Nateowami)



<!-- Sent from Reviewable.io -->

2024-07-29 03:20 UTC, Nateowami commented
Done.

2024-07-29 03:39 UTC, josephmyers approved these changes
Thanks

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2604#-:-O2wZ_kgBo8JCp_OxQbv:b-zcjvte)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @Nateowami)



<!-- Sent from Reviewable.io -->

2024-07-31 13:32 UTC, merged