SF-2842 Improve font unsupported notice
sillsdev/web-xforge pull request #2611
Opened 2024-07-23 20:45 UTC by Nateowami

2024-07-25 17:39 UTC, RaymondLuong3 requested changes
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2611)* status: all files reviewed, 8 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.html` line 3 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2611#-O2eqqNm-DOqdmK-HqrR:-O2eqqNm-DOqdmK-HqrS:bq2k66j) ([raw file](https://github.com/sillsdev/web-xforge/blob/3d1c62cae7d9fdb68fa33696540b910828fbee9d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.html#L3)):*
> ```HTML
> <ng-container *transloco="let t; read: 'font_unsupported_message'">
>   <app-notice
>     *ngIf="showUnsupportedFontWarning || showGraphiteWarning"
> ```

We should be using the `@if` branching syntax since the `*ngIf` will be deprecated in angular 18 (IIRC). Here and below



_Code quote:_
```HTML
    *ngIf="showUnsupportedFontWarning || showGraphiteWarning"
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.html` line 8 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2611#-O2erDTx335Wi9h7unS3:-O2erDTx335Wi9h7unS4:bsmvyn8) ([raw file](https://github.com/sillsdev/web-xforge/blob/3d1c62cae7d9fdb68fa33696540b910828fbee9d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.html#L8)):*
> ```HTML
>     class="font-warning"
>   >
>     <ng-container *ngFor="let portion of i18n.interpolateVariables(warningI18nKey, { selectedFont, fallbackFont })">
> ```

This goes for the for loop here and below.



_Code quote:_
```HTML
    <ng-container *ngFor="let portion of i18n.interpolateVariables(warningI18nKey, { selectedFont, fallbackFont })">
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.html` line 14 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2611#-O2es2v76eAWL5fQrrOB:-O2es2v76eAWL5fQrrOC:b-xm3z82) ([raw file](https://github.com/sillsdev/web-xforge/blob/3d1c62cae7d9fdb68fa33696540b910828fbee9d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.html#L14)):*
> ```HTML
>         [href]="externalUrlService.graphite"
>         target="_blank"
>         rel="noopener noreferrer"
> ```

According to [rel=noreferrer - HTML: HyperText Markup Language | MDN (mozilla.org)](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/noreferrer) the noopener value is redundant because noreferrer accomplishs that.



_Code quote:_
```HTML
        rel="noopener noreferrer"
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.html` line 15 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2611#-O2erg5lCJcJ_VcUtwGJ:-O2erg5lCJcJ_VcUtwGK:b982uhv) ([raw file](https://github.com/sillsdev/web-xforge/blob/3d1c62cae7d9fdb68fa33696540b910828fbee9d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.html#L15)):*
> ```HTML
>         target="_blank"
>         rel="noopener noreferrer"
>         >{{ t("graphite") }}</a
> ```

Does graphite really need to be translated. I imagine that is not helpful for users and translators won't know how to translate that.



_Code quote:_
```HTML
        >{{ t("graphite") }}</a
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.html` line 20 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2611#-O2eu7AG7f5EM_jhmQwn:-O2eu7AG7f5EM_jhmQwo:btbysts) ([raw file](https://github.com/sillsdev/web-xforge/blob/3d1c62cae7d9fdb68fa33696540b910828fbee9d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.html#L20)):*
> ```HTML
> 
>     <ng-container *ngFor="let portion of i18n.interpolate(suggestedRemedyI18nKey)">
>       <a *ngIf="portion.id === 1" [href]="issueMailTo" target="_blank" rel="noopener noreferrer">
> ```

This way of using i18n strings in templates is nice, but if the translation ever changes, this won't show correctly. I expect if we do change it that the developer will see that, but just wanted to point out how brittle this could be.
The noopener can be omitted



_Code quote:_
```HTML
      <a *ngIf="portion.id === 1" [href]="issueMailTo" target="_blank" rel="noopener noreferrer">
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.ts` line 4 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2611#-O2ex9QH5_qqDeg_Kzvd:-O2ex9QIEK7Z_dsbS9Ts:bkgpk1) ([raw file](https://github.com/sillsdev/web-xforge/blob/3d1c62cae7d9fdb68fa33696540b910828fbee9d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.ts#L4)):*
> ```XML
> import { Component } from '@angular/core';
> import { TranslocoModule } from '@ngneat/transloco';
> import { ActivatedProjectService } from '../../../xforge-common/activated-project.service';
> ```

The xForge relative path should just be the absolute path.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.ts` line 38 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2611#-O2exeheDbQ9h8PIu61Q:-O2exeheDbQ9h8PIu61R:b-rl795j) ([raw file](https://github.com/sillsdev/web-xforge/blob/3d1c62cae7d9fdb68fa33696540b910828fbee9d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.ts#L38)):*
> ```XML
>   get projectDoc(): SFProjectProfileDoc | undefined {
>     return this.activatedProjectService.projectDoc;
>   }
> ```

I don't see where projectDoc is being used.



_Code quote:_
```XML
  get projectDoc(): SFProjectProfileDoc | undefined {
    return this.activatedProjectService.projectDoc;
  }
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/src/app/translate/font-unsupported-message/font-unsupported-message.component.ts` line 0 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2611#-O2ewuDv8BwtYfR4YRaM:-O2ewuDv8BwtYfR4YRaN:bwsdgeo) ([raw file](https://github.com/sillsdev/web-xforge/blob/5b171944541fb3f116aef92d5e3cd20b8a0799e4/src/SIL.XForge.Scripture/ClientApp/src/app/translate/src/app/translate/font-unsupported-message/font-unsupported-message.component.ts#L0)):*
I don't know how this file got in here with the same path as the other `font-unsupported-message.component`. Remove it if you can.


<!-- Sent from Reviewable.io -->

2024-07-25 18:53 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2611)* status: all files reviewed, 8 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.html` line 3 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2611#-O2eqqNm-DOqdmK-HqrR:-O2f4Y9D5MPRxgB8PGvY:bivjm5v) ([raw file](https://github.com/sillsdev/web-xforge/blob/3d1c62cae7d9fdb68fa33696540b910828fbee9d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.html#L3)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

We should be using the `@if` branching syntax since the `*ngIf` will be deprecated in angular 18 (IIRC). Here and below
</blockquote></details>

Personally I think the `*ngIf` syntax is more readable in a lot of contexts (matching curly braces, weird indention, and weird formatting by Prettier make the new syntax hard to work with), and less readable in others. I can't find anything online about it being deprecated, except some people speculating that it eventually will be.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.html` line 8 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2611#-O2erDTx335Wi9h7unS3:-O2fDLQ_7R9t_-1_ViPL:b-k0o697) ([raw file](https://github.com/sillsdev/web-xforge/blob/3d1c62cae7d9fdb68fa33696540b910828fbee9d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.html#L8)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This goes for the for loop here and below.
</blockquote></details>

Done. Not sure whether I consider this more readable. I added two HTML comments because otherwise Prettier wanted to run everything together and make it very hard to read. Our version of Prettier is out of date, and it's possible this would be improved in an update.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.html` line 14 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2611#-O2es2v76eAWL5fQrrOB:-O2f6_HXCouQEN14ZsbU:bfa9t4q) ([raw file](https://github.com/sillsdev/web-xforge/blob/3d1c62cae7d9fdb68fa33696540b910828fbee9d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.html#L14)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

According to [rel=noreferrer - HTML: HyperText Markup Language | MDN (mozilla.org)](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/noreferrer) the noopener value is redundant because noreferrer accomplishs that.
</blockquote></details>

Thanks; I was not aware of that. Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.html` line 15 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2611#-O2erg5lCJcJ_VcUtwGJ:-O2f6mriB2pr9iqFznUo:bkvr7dt) ([raw file](https://github.com/sillsdev/web-xforge/blob/3d1c62cae7d9fdb68fa33696540b910828fbee9d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.html#L15)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Does graphite really need to be translated. I imagine that is not helpful for users and translators won't know how to translate that.
</blockquote></details>

I debated about this one. The idea wasn't that it needed to be translated, but that it needed to be a separate string in order to be interpolated here (limitation of our i18n service). I then had the option to hard code "Graphite" in the template, which seemed odd, as we don't normally do that. Also, there's a possibility that someone would want to render it something like "Graphite font software" (leaving Graphite in English, but giving context as to what it is referring to).
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.html` line 20 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2611#-O2eu7AG7f5EM_jhmQwn:-O2fDm9d58dHCChFNJCX:bif0ppa) ([raw file](https://github.com/sillsdev/web-xforge/blob/3d1c62cae7d9fdb68fa33696540b910828fbee9d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.html#L20)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This way of using i18n strings in templates is nice, but if the translation ever changes, this won't show correctly. I expect if we do change it that the developer will see that, but just wanted to point out how brittle this could be.
The noopener can be omitted
</blockquote></details>

I don't understand how this is brittle, or how you think it could be improved. If we ever update the string to have different variables we would be updating the template at the same time.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.ts` line 4 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2611#-O2ex9QH5_qqDeg_Kzvd:-O2f6Kij0zX_P_OtHS_4:bry22c4) ([raw file](https://github.com/sillsdev/web-xforge/blob/3d1c62cae7d9fdb68fa33696540b910828fbee9d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.ts#L4)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

The xForge relative path should just be the absolute path.
</blockquote></details>

Updated. I wish VSCode would just do this correctly itself.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.ts` line 38 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2611#-O2exeheDbQ9h8PIu61Q:-O2f6Gz6CkK4oOwofJNE:b-8rrwzv) ([raw file](https://github.com/sillsdev/web-xforge/blob/3d1c62cae7d9fdb68fa33696540b910828fbee9d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.ts#L38)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I don't see where projectDoc is being used.
</blockquote></details>

It's being used two places. Click on it in an IDE and it will highlight the places it's used.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/src/app/translate/font-unsupported-message/font-unsupported-message.component.ts` line  at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2611#-O2ewuDv8BwtYfR4YRaM:-O2f6FYq-PAJ-v7Z1lA1:b-x3gtb4) ([raw file](https://github.com/sillsdev/web-xforge/blob/5b171944541fb3f116aef92d5e3cd20b8a0799e4/src/SIL.XForge.Scripture/ClientApp/src/app/translate/src/app/translate/font-unsupported-message/font-unsupported-message.component.ts#L)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I don't know how this file got in here with the same path as the other `font-unsupported-message.component`. Remove it if you can.
</blockquote></details>

Thanks for catching this.


<!-- Sent from Reviewable.io -->

2024-07-25 19:17 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2611)* status: 8 of 12 files reviewed, 8 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.html` line 8 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2611#-O2erDTx335Wi9h7unS3:-O2fJoMn56rCylquowgL:baz4jkz) ([raw file](https://github.com/sillsdev/web-xforge/blob/3d1c62cae7d9fdb68fa33696540b910828fbee9d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.html#L8)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Done. Not sure whether I consider this more readable. I added two HTML comments because otherwise Prettier wanted to run everything together and make it very hard to read. Our version of Prettier is out of date, and it's possible this would be improved in an update.
</blockquote></details>

Updating Prettier fixes this. I have a PR at https://github.com/sillsdev/web-xforge/pull/2616


<!-- Sent from Reviewable.io -->

2024-07-25 20:57 UTC, RaymondLuong3 approved these changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2611)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.html` line 3 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2611#-O2eqqNm-DOqdmK-HqrR:-O2fdolB7veKFIxFxQl4:b-1k6f8x) ([raw file](https://github.com/sillsdev/web-xforge/blob/3d1c62cae7d9fdb68fa33696540b910828fbee9d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.html#L3)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Personally I think the `*ngIf` syntax is more readable in a lot of contexts (matching curly braces, weird indention, and weird formatting by Prettier make the new syntax hard to work with), and less readable in others. I can't find anything online about it being deprecated, except some people speculating that it eventually will be.
</blockquote></details>

You're right, I thought I had read that it is deprecated, but so far no serious timeline for that.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.html` line 15 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2611#-O2erg5lCJcJ_VcUtwGJ:-O2feGrZE82hDj_vbRjh:b-pwzbmp) ([raw file](https://github.com/sillsdev/web-xforge/blob/3d1c62cae7d9fdb68fa33696540b910828fbee9d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.html#L15)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I debated about this one. The idea wasn't that it needed to be translated, but that it needed to be a separate string in order to be interpolated here (limitation of our i18n service). I then had the option to hard code "Graphite" in the template, which seemed odd, as we don't normally do that. Also, there's a possibility that someone would want to render it something like "Graphite font software" (leaving Graphite in English, but giving context as to what it is referring to).
</blockquote></details>

Right, I was thinking maybe we hard code it in the template, or set a variable in the ts file and use that. This is probably good enough, but there is the risk that a translator will get this wrong and try to translate "Graphite" literally. We can cross that bridge when we get there.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.html` line 20 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2611#-O2eu7AG7f5EM_jhmQwn:-O2feppW6J9Eav-F4xsL:b-kekffr) ([raw file](https://github.com/sillsdev/web-xforge/blob/3d1c62cae7d9fdb68fa33696540b910828fbee9d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.html#L20)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I don't understand how this is brittle, or how you think it could be improved. If we ever update the string to have different variables we would be updating the template at the same time.
</blockquote></details>

It is just brittle in the sense that the template is so dependent on the localization to conform to a format. But yes, it is likely this issue with the localization string and the template would be out of sync.


<!-- Sent from Reviewable.io -->

2024-07-26 04:15 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2611)* status: 11 of 12 files reviewed, all discussions resolved (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.html` line 15 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2611#-O2erg5lCJcJ_VcUtwGJ:-O2hE8O23M4ZH_U8PXsW:bbqxqnm) ([raw file](https://github.com/sillsdev/web-xforge/blob/3d1c62cae7d9fdb68fa33696540b910828fbee9d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.html#L15)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Right, I was thinking maybe we hard code it in the template, or set a variable in the ts file and use that. This is probably good enough, but there is the risk that a translator will get this wrong and try to translate "Graphite" literally. We can cross that bridge when we get there.
</blockquote></details>

I'm not sure if you noticed that I actually have changed it to hard code it in the template.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.html` line 10 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2611#-O2hEfYX4h9FbL8n1THn:-O2hEfYY4u91bLPHRRSo:b3emdn2) ([raw file](https://github.com/sillsdev/web-xforge/blob/753ea10671928885ba2f849118d9a4ca8ec29a7e/src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.html#L10)):*
> ```HTML
>           <a [href]="externalUrlService.graphite" target="_blank" rel="noreferrer">Graphite</a>
>         }
>         <!-- prettier-ignore -->
> ```

I had to add this, otherwise Prettier reformats it to:
``` html
        @if (portion.id == null) {
          {{ portion.text }}
        }
```
which adds actual whitespace where it shouldn't in the output.


<!-- Sent from Reviewable.io -->

2024-07-26 15:54 UTC, RaymondLuong3 approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2611)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.html` line 15 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2611#-O2erg5lCJcJ_VcUtwGJ:-O2jjJM96Wn6KIm6wGMT:b-xt326t) ([raw file](https://github.com/sillsdev/web-xforge/blob/3d1c62cae7d9fdb68fa33696540b910828fbee9d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/font-unsupported-message/font-unsupported-message.component.html#L15)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I'm not sure if you noticed that I actually have changed it to hard code it in the template.
</blockquote></details>

Yes, you did! I don't know how I missed that. I see we aren't providing a string for the "graphite" variable for the i18n localization, but that is probably fine.


<!-- Sent from Reviewable.io -->

2024-07-27 22:36 UTC, Nateowami commented
@RaymondLuong3 I've fixed a bug the test team found.

2024-07-29 13:42 UTC, merged