SF-2878 Migrate component templates to new control flow syntax
sillsdev/web-xforge pull request #2617
Opened 2024-07-25 22:44 UTC by RaymondLuong3

The control flow template syntax is new in Angular 17. There is no immediate target for when the previous template structural directives will not supported. This PR used `ng g @angular/core:control-flow` as the starting point.

2024-07-29 00:14 UTC, pmachapman requested changes
I like the flexibility of the new syntax, and its similarity to Razor syntax.

I have listed a ~bunch~ lot of nits to improve the logic and hopefully make it clearer (and so hopefully faster for the template engine). If this is a pain or outside the scope of this PR, let me know and we can figure out what to do instead.

> Reviewed 76 of 76 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2617#-:-O2vIxNs7tVJuC96GO0H:b-suqyv3)* status: all files reviewed, 75 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html` line 153 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2617#-O2vImXRAp9HCd0R0-mL:-O2vImXRAp9HCd0R0-mM:b-ou17fe) ([raw file](https://github.com/sillsdev/web-xforge/blob/f082e548f2af5cb056524a94365372a4aaa914bd/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html#L153)):*
> ```HTML
>               {{ t("online") }}
>             }
>             @if (!isAppOnline) {
> ```

NIT: You could change this to:
```
} @else {
```



_Code quote:_
```HTML
            }
            @if (!isAppOnline) {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html` line 16 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2617#-O2vKt_G4T_zXCK6x9EV:-O2vKt_G4T_zXCK6x9EW:b-ejeiod) ([raw file](https://github.com/sillsdev/web-xforge/blob/f082e548f2af5cb056524a94365372a4aaa914bd/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html#L16)):*
> ```HTML
>         @if (selectionHasAudioAlready && !inEditState) {
>           <app-info [text]="t('audio_already_exists')" icon="warning" type="warning"></app-info>
>         }
> ```

NIT If I understand this correctly, I believe this should be:
```
        @if (selectionHasAudioAlready && !inEditState) {
          <app-info [text]="t('audio_already_exists')" icon="warning" type="warning"></app-info>
        } @else {
          <mat-icon>book</mat-icon>
        }
```



_Code quote:_
```HTML
        @if (!selectionHasAudioAlready || inEditState) {
          <mat-icon>book</mat-icon>
        }
        @if (selectionHasAudioAlready && !inEditState) {
          <app-info [text]="t('audio_already_exists')" icon="warning" type="warning"></app-info>
        }
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html` line 53 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2617#-O2vM5G3BmszJ6xQX9vQ:-O2vM5G3BmszJ6xQX9vR:blky4n2) ([raw file](https://github.com/sillsdev/web-xforge/blob/f082e548f2af5cb056524a94365372a4aaa914bd/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html#L53)):*
> ```HTML
>             <span>{{ audioFilename }}</span>
>           }
>           @if (hasAudioBeenUploaded) {
> ```

NIT This could be changed to:
```
} @else {
```



_Code quote:_
```HTML
          }
          @if (hasAudioBeenUploaded) {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html` line 62 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2617#-O2vMBWM5KAnaYjSILqq:-O2vMBWM5KAnaYjSILqr:blky4n2) ([raw file](https://github.com/sillsdev/web-xforge/blob/f082e548f2af5cb056524a94365372a4aaa914bd/src/SIL.XForge.Scripture/ClientApp/src/app/checking/chapter-audio-dialog/chapter-audio-dialog.component.html#L62)):*
> ```HTML
>             <span>{{ t("no_audio_file_uploaded") }}</span>
>           }
>           @if (hasAudioDataError) {
> ```

NIT This could be changed to:
```
} @else {
```



_Code quote:_
```HTML
          }
          @if (hasAudioDataError) {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html` line 94 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2617#-O2vOVpiA4BLBz_txAhs:-O2vOVpiA4BLBz_txAht:bt54f0w) ([raw file](https://github.com/sillsdev/web-xforge/blob/f082e548f2af5cb056524a94365372a4aaa914bd/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html#L94)):*
> ```HTML
>                   </button>
>                 }
>                 @if (selectedText) {
> ```

NIT: This could be changed to:
```
} @else {
```



_Code quote:_
```HTML
                }
                @if (selectedText) {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html` line 205 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2617#-O2vOn5A7fd56qykC7-L:-O2vOn5A7fd56qykC7-M:b-ttlprh) ([raw file](https://github.com/sillsdev/web-xforge/blob/f082e548f2af5cb056524a94365372a4aaa914bd/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html#L205)):*
> ```HTML
>                       </button>
>                     }
>                     @if (canChangeAnswerStatus(answer)) {
> ```

NIT: This can be removed.



_Code quote:_
```HTML
                    }
                    @if (canChangeAnswerStatus(answer)) {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html` line 226 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2617#-O2vOtbtD0SiITYRzDO1:-O2vOtbtD0SiITYRzDO2:b-ttlprh) ([raw file](https://github.com/sillsdev/web-xforge/blob/f082e548f2af5cb056524a94365372a4aaa914bd/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.html#L226)):*
> ```HTML
>                       <div class="delete-divider">|</div>
>                     }
>                     @if (canDeleteAnswer(answer)) {
> ```

NIT: This can be removed.



_Code quote:_
```HTML
                    }
                    @if (canDeleteAnswer(answer)) {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.html` line 30 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2617#-O2vPNVm8SKywIwhrXMU:-O2vPNVm8SKywIwhrXMV:bt54f0w) ([raw file](https://github.com/sillsdev/web-xforge/blob/f082e548f2af5cb056524a94365372a4aaa914bd/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-question/checking-question.component.html#L30)):*
> ```HTML
>         </div>
>       }
>       @if (questionAudioUrl) {
> ```

NIT: This could be changed to:
```
} @else {
```



_Code quote:_
```HTML
      }
      @if (questionAudioUrl) {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.html` line 11 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2617#-O2vPemN2voXC0Kw8mkO:-O2vPemN2voXC0Kw8mkP:bt54f0w) ([raw file](https://github.com/sillsdev/web-xforge/blob/f082e548f2af5cb056524a94365372a4aaa914bd/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.html#L11)):*
> ```HTML
>             </button>
>           }
>           @if (isPlaying()) {
> ```

NIT: This could be changed to:
```
} @else {
```



_Code quote:_
```HTML
          }
          @if (isPlaying()) {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.html` line 15 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2617#-O2vPmU67oltISE3Qv21:-O2vPmU67oltISE3Qv22:bt54f0w) ([raw file](https://github.com/sillsdev/web-xforge/blob/f082e548f2af5cb056524a94365372a4aaa914bd/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-recorder/checking-audio-recorder.component.html#L15)):*
> ```HTML
>         </button>
>       }
>       @if (isRecording) {
> ```

NIT: This could be changed to:
```
} @else {
```



_Code quote:_
```HTML
      }
      @if (isRecording) {
```
___
*[`src/SIL.XForg [...]

2024-07-29 16:19 UTC, Nateowami commented
I haven't looked at all of @pmachapman's suggested changes, but I would suggest that we make any manual changes in a followup PR. The main reason being that we already have a bunch of merge conflicts, and it's much easier to run the migration and merge the change right away. There will then be conflicts on branches, but it should be possible to run the migration on those branches to reconcile the conflicts.

A second, less significant reason to make it a separate change it to make it easier to tack down any regressions. In general I don't like to mix manual changes and automated changes into the same revision.

I would also note that a regression is more likely than you might think, since there is a potential for white space changes. In `font-unsupported-message.component.html` I had to do:
```
        <!-- prettier-ignore -->
        @if (portion.id == null) {{{ portion.text }}}
```
to prevent it from being reformatted as:
```
        @if (portion.id == null) {
          {{ portion.text }}
        }
```
which causes undesirable white space in the rendered result.

2024-07-29 20:15 UTC, RaymondLuong3 commented
I agree with Nathaniel, I can make the changes in a follow up PR. We can say that this change is just the step to get us onto using control flow

2024-07-29 21:36 UTC, pmachapman approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2617#-:-O3-PyVzDNsEJj8j5Ujx:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2024-07-30 15:03 UTC, Nateowami commented
@RaymondLuong3 My recommendation would be to fix the conflicts by re-running the migration from scratch.

2024-08-01 19:48 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2617)* status: 65 of 79 files reviewed, 1 unresolved discussion (waiting on @pmachapman and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts` line 102 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2617#-O3EUCGsCHNm8baspPQZ:-O3EUCGt0vPNufwMp3p5:b-4apvpg) ([raw file](https://github.com/sillsdev/web-xforge/blob/bd061a2e4689050f8e9f915164ba77b8c6471683/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts#L102)):*
> ```XML
>   promiseForTransceleratorQuestions: Promise<TransceleratorQuestion[] | undefined>;
>   promiseForQuestionDocQuery: Promise<RealtimeQuery<QuestionDoc>>;
>   helpInstructions: { text: string; id?: number }[];
> ```

How about:
``` ts
  helpInstructions = this.i18n.interpolate('import_questions_dialog.help_options');
  transceleratorInfo= this.i18n.interpolate('import_questions_dialog.transcelerator_paratext');
```
Here, and elsewhere.


<!-- Sent from Reviewable.io -->

2024-08-01 20:59 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2617)* status: 65 of 79 files reviewed, 1 unresolved discussion (waiting on @Nateowami and @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts` line 102 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2617#-O3EUCGsCHNm8baspPQZ:-O3EjIcr7JhophdtOK5G:b25gt12) ([raw file](https://github.com/sillsdev/web-xforge/blob/bd061a2e4689050f8e9f915164ba77b8c6471683/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts#L102)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

How about:
``` ts
  helpInstructions = this.i18n.interpolate('import_questions_dialog.help_options');
  transceleratorInfo= this.i18n.interpolate('import_questions_dialog.transcelerator_paratext');
```
Here, and elsewhere.
</blockquote></details>

Unfortunately we need to do it in the constructor because we don't have access to the i18n service until the class is instantiated.


<!-- Sent from Reviewable.io -->

2024-08-01 21:13 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2617)* status: 65 of 79 files reviewed, 1 unresolved discussion (waiting on @pmachapman and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts` line 102 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2617#-O3EUCGsCHNm8baspPQZ:-O3EmFTbAZcqSRzk8ia_:b6bdzn8) ([raw file](https://github.com/sillsdev/web-xforge/blob/bd061a2e4689050f8e9f915164ba77b8c6471683/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts#L102)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Unfortunately we need to do it in the constructor because we don't have access to the i18n service until the class is instantiated.
</blockquote></details>

@RaymondLuong3 The class is instantiated before the field initializers are run.


<!-- Sent from Reviewable.io -->

2024-08-01 21:26 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2617)* status: 65 of 79 files reviewed, 1 unresolved discussion (waiting on @pmachapman and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts` line 102 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2617#-O3EUCGsCHNm8baspPQZ:-O3Epb8iAN6ugHZ-Qs-8:bi7huyw) ([raw file](https://github.com/sillsdev/web-xforge/blob/bd061a2e4689050f8e9f915164ba77b8c6471683/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts#L102)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

@RaymondLuong3 The class is instantiated before the field initializers are run.
</blockquote></details>

Keep in mind your fix for this means the text no longer updates when switching locales, without reloading the page.


<!-- Sent from Reviewable.io -->

2024-08-01 22:42 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2617)* status: 65 of 79 files reviewed, 1 unresolved discussion (waiting on @Nateowami and @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts` line 102 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2617#-O3EUCGsCHNm8baspPQZ:-O3F5Jz5DlqcZi_sFtQX:bw6vcnu) ([raw file](https://github.com/sillsdev/web-xforge/blob/bd061a2e4689050f8e9f915164ba77b8c6471683/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts#L102)):*
You are correct! I'm not sure why I thought I saw a problem when I wrote it earlier.
> Keep in mind your fix for this means the text no longer updates when switching locales, without reloading the page.
Yes, this affects the draft generation page, but not the import question dialog. I don't think it is worth creating a new issue, but definitely better than an error being thrown.


<!-- Sent from Reviewable.io -->

2024-08-02 15:11 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2617)* status: 65 of 79 files reviewed, 1 unresolved discussion (waiting on @pmachapman and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts` line 102 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2617#-O3EUCGsCHNm8baspPQZ:-O3Ici_a0_5JQ8vZZS3h:bo2vqzd) ([raw file](https://github.com/sillsdev/web-xforge/blob/bd061a2e4689050f8e9f915164ba77b8c6471683/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts#L102)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

You are correct! I'm not sure why I thought I saw a problem when I wrote it earlier.
> Keep in mind your fix for this means the text no longer updates when switching locales, without reloading the page.
Yes, this affects the draft generation page, but not the import question dialog. I don't think it is worth creating a new issue, but definitely better than an error being thrown.
</blockquote></details>

I have a branch that fixes this while maintaining dynamic updates: `fix/control-flow-with-dynamic-updated-translation`


<!-- Sent from Reviewable.io -->

2024-08-02 16:21 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2617)* status: 64 of 81 files reviewed, 1 unresolved discussion (waiting on @Nateowami and @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts` line 102 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2617#-O3EUCGsCHNm8baspPQZ:-O3ItKX124yQcrLCRdUc:b-p9keix) ([raw file](https://github.com/sillsdev/web-xforge/blob/bd061a2e4689050f8e9f915164ba77b8c6471683/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts#L102)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I have a branch that fixes this while maintaining dynamic updates: `fix/control-flow-with-dynamic-updated-translation`
</blockquote></details>

Thanks. I've tested the changes and they look good.


<!-- Sent from Reviewable.io -->

2024-08-02 18:06 UTC, Nateowami requested changes
> Reviewed 1 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2617)* status: 65 of 82 files reviewed, 1 unresolved discussion (waiting on @pmachapman and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.html` line 104 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/2617#-O3J3iaw017YsTTCF1R3:-O3J3iaw017YsTTCF1R4:b-dzw1mh) ([raw file](https://github.com/sillsdev/web-xforge/blob/084f9e925c4491e3a0870c77a7e75b2b8c93c614/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.html#L104)):*
> ```HTML
>           <div class="support-message">
>             @for (i of helpInstructions | async; track i) {
>               @if (i.id == null) {
> ```

This is causing an unwanted space that can be fixed with:
```
              <!-- prettier-ignore -->
              @if (i.id == null) {{{ i.text }}}
```

![](https://files.reviewableusercontent.io/images/reviewable/6140710/5-BXOaDLtEulcfVTiYuMSK-5/localhost_5000_projects_66724b7850302caa474ac8a2_checking.png)


<!-- Sent from Reviewable.io -->

2024-08-02 18:34 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2617)* status: 65 of 82 files reviewed, 1 unresolved discussion (waiting on @Nateowami and @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.html` line 104 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/2617#-O3J3iaw017YsTTCF1R3:-O3JMnZuAzeX7yRMD8sa:b-s0ztqj) ([raw file](https://github.com/sillsdev/web-xforge/blob/084f9e925c4491e3a0870c77a7e75b2b8c93c614/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.html#L104)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This is causing an unwanted space that can be fixed with:
```
              <!-- prettier-ignore -->
              @if (i.id == null) {{{ i.text }}}
```

![](https://files.reviewableusercontent.io/images/reviewable/6140710/5-BXOaDLtEulcfVTiYuMSK-5/localhost_5000_projects_66724b7850302caa474ac8a2_checking.png)
</blockquote></details>

Thanks. I've updated this in both the import questions dialog and the draft generation page.


<!-- Sent from Reviewable.io -->

2024-08-04 19:45 UTC, pmachapman requested changes
> Reviewed 8 of 14 files at r2, 5 of 8 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2617)* status: all files reviewed, 2 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts` line 351 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/2617#-O3TuxuQ69_WWrovSHyK:-O3TuxuQ69_WWrovSHyL:bwgfjbz) ([raw file](https://github.com/sillsdev/web-xforge/blob/6f437eeb277d5d4da90235ac43a15d443ae8e09c/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts#L351)):*
> ```XML
>         }
>         sections.push({ text: translation.substring(i) });
>         console.log(sections);
> ```

Is this debugging code that is left over?



_Code quote:_
```XML
console.log(sections);
```


<!-- Sent from Reviewable.io -->

2024-08-05 00:57 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2617)* status: all files reviewed, 2 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts` line 351 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/2617#-O3TuxuQ69_WWrovSHyK:-O3V1Vj885Wx9R-9Iqvd:b-dhs26e) ([raw file](https://github.com/sillsdev/web-xforge/blob/6f437eeb277d5d4da90235ac43a15d443ae8e09c/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts#L351)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Is this debugging code that is left over?
</blockquote></details>

Yes. I accidentally included it in my suggested change. I was testing how how frequently this method was actually getting called


<!-- Sent from Reviewable.io -->

2024-08-06 18:14 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2617)* status: 81 of 82 files reviewed, 2 unresolved discussions (waiting on @Nateowami and @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts` line 351 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/2617#-O3TuxuQ69_WWrovSHyK:-O3ctZ9P72-358hAdrlZ:bungmby) ([raw file](https://github.com/sillsdev/web-xforge/blob/6f437eeb277d5d4da90235ac43a15d443ae8e09c/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/i18n.service.ts#L351)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Yes. I accidentally included it in my suggested change. I was testing how how frequently this method was actually getting called
</blockquote></details>

Good spotting. Removed.


<!-- Sent from Reviewable.io -->

2024-08-06 18:42 UTC, Nateowami commented
@RaymondLuong3 If you need help reconciling changes, let me know. My recommendation would be:
1. Create a new branch
2. Run the migrator
3. Cherry-pick the "Fix errors from control flow update" commit
4. Hard-reset this branch to the resulting commit

That should ensure all the files get migrated, and I think it will avoid any conflicts with the changes you made.

2024-08-06 19:42 UTC, pmachapman approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> Dismissed @Nateowami from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2617)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2024-08-07 16:01 UTC, Nateowami approved these changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2617)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2024-08-07 16:07 UTC, merged