SF-2885 Fix project deleted message being shown after deleting project
sillsdev/web-xforge pull request #2625
Opened 2024-07-29 19:01 UTC by Nateowami

This is supposed to be an error message, not a confirmation message.

This was broken in 28553e5451ed003cc25d85a505290033f387f5d3 when UserService.currentProjectId was changed from a gettter to a method that requires an argument, and AppComponent was not correctly updated.

2024-07-29 19:35 UTC, pmachapman approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2625#-:-O2zysMKBPYf05BzxbVz:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Nateowami)



<!-- Sent from Reviewable.io -->

2024-08-09 20:30 UTC, Nateowami commented
@pmachapman I've made some changes based on notes from testing, that I think warrant a re-review.

2024-08-11 19:53 UTC, pmachapman requested changes
Just a couple of minor nits, and when running the code, I have the delete dialog appear twice when I am removed from a project.

See the following video: https://youtu.be/iYRxMyHrolA

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2625#-:-O41tYFC0Fpa6Q4CumJH:byh8iii)* status: all files reviewed, 3 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts` line 12 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2625#-O41u2KyDICyPT6Jm860:-O41u2KyDICyPT6Jm861:b1gows1) ([raw file](https://github.com/sillsdev/web-xforge/blob/47fa5befa9190589eddc090a405c4cb1a41661e9/src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts#L12)):*
> ```XML
> import { UserService } from 'xforge-common/user.service';
> import { environment } from '../../environments/environment';
> import { DialogService } from '../../xforge-common/dialog.service';
> ```

NIT: Remove the `../../`



_Code quote:_
```XML
import { DialogService } from '../../xforge-common/dialog.service';
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts` line 70 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2625#-O41zBFm21QjAmwOzH51:-O41zBFm21QjAmwOzH52:bw0izrj) ([raw file](https://github.com/sillsdev/web-xforge/blob/47fa5befa9190589eddc090a405c4cb1a41661e9/src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts#L70)):*
> ```XML
>       } else {
>         await this.dialogService.message('app.project_has_been_deleted');
>         this.router.navigateByUrl('/projects', { replaceUrl: true });
> ```

You may want to consider replacing this with a call to `AppComponent.showProjectDeletedDialog()` (and making that method public?)



_Code quote:_
```XML
        await this.dialogService.message('app.project_has_been_deleted');
        this.router.navigateByUrl('/projects', { replaceUrl: true });
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts` line 23 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2625#-O41tmPB4YsLsZ-ep-lN:-O41tmPB4YsLsZ-ep-lO:b1gows1) ([raw file](https://github.com/sillsdev/web-xforge/blob/47fa5befa9190589eddc090a405c4cb1a41661e9/src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts#L23)):*
> ```XML
> import { UICommonModule } from 'xforge-common/ui-common.module';
> import { UserService } from 'xforge-common/user.service';
> import { DialogService } from '../../xforge-common/dialog.service';
> ```

NIT: Remove the `../../`



_Code quote:_
```XML
import { DialogService } from '../../xforge-common/dialog.service';
```


<!-- Sent from Reviewable.io -->

2024-08-12 18:01 UTC, Nateowami reviewed
Thanks for finding the duplicate dialog. I'll work on it.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2625#-:-O46kApEDXUYprNcjd0T:b-pj3twz)* status: all files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts` line 12 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2625#-O41u2KyDICyPT6Jm860:-O46j0FlB-q_CfUPKure:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/47fa5befa9190589eddc090a405c4cb1a41661e9/src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts#L12)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

NIT: Remove the `../../`
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts` line 70 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2625#-O41zBFm21QjAmwOzH51:-O46iu2pEM0r1qPD7a-Q:b-xdltni) ([raw file](https://github.com/sillsdev/web-xforge/blob/47fa5befa9190589eddc090a405c4cb1a41661e9/src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.ts#L70)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

You may want to consider replacing this with a call to `AppComponent.showProjectDeletedDialog()` (and making that method public?)
</blockquote></details>

This would require making it a static method, but it uses instances properties, so that's not an option.

I don't really feel like the app component should be responsible for handling this; it seems like it should be more of a background service or something.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts` line 23 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2625#-O41tmPB4YsLsZ-ep-lN:-O46izc9Ca5K1zj6LolZ:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/47fa5befa9190589eddc090a405c4cb1a41661e9/src/SIL.XForge.Scripture/ClientApp/src/app/project/project.component.spec.ts#L23)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

NIT: Remove the `../../`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-12 19:25 UTC, pmachapman approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2625)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Nateowami)



<!-- Sent from Reviewable.io -->

2024-08-14 14:41 UTC, marksvc commented
I just wanted to point out that in standup meeting, the testers referred to hoping to hear back on a comment made today on issue SF-2885.

2024-09-07 02:53 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2625)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 176 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2625#-O69OLOb53K_iKjZZ4at:-O69OLOb53K_iKjZZ4au:bi8owc8) ([raw file](https://github.com/sillsdev/web-xforge/blob/233b69896d415fe086c930213588d9f0be95df57/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L176)):*
> ```XML
> 
>   get appIconLink(): string[] {
>     return this.router.url === '/projects' && this.lastSelectedProjectId != null
> ```

I've made a small adjustment so that when no project has been last selected, it links to the my projects page (the current page) rather to a project with ID `''`, which would result in showing a dialog saying the project was not accessible.


<!-- Sent from Reviewable.io -->

2024-09-07 02:54 UTC, Nateowami commented
I've unassigned Peter because he is away.

2024-09-09 16:22 UTC, kylebuss approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2625#-:-O6M_yIt56UKiCBzoOLA:bnfp4nl)* status: all files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2024-09-11 14:30 UTC, merged