SF-2835 Add message for unsupported USFM
sillsdev/web-xforge pull request #2640
Opened 2024-07-31 06:49 UTC by josephmyers

This involved distinguishing between invalid USFM (i.e. formatting errors) and unsupported USFM (i.e. unrecognized tags). We were bundling both into a single error message that misled some users to believe their project had formatting errors.

Now, if the chapter has unsupported tags, we will display a message indicating which tags the user needs to remove to restore editing.

In order to detect invalid tags, I added an extension method to Delta, which will iterate through its ops, searching for either of the 'invalid' attributes, and add the matching 'char.style' to its return list. If an 'invalid' attribute is present but there is no 'char.style,' we infer this as bad formatting.

The 'invalid tag' message will take precedence over the 'bad formatting' message, in the case there are both.

2024-07-31 22:57 UTC, pmachapman requested changes
I am not sure this is the best solution to the problem. It means that every time a text is viewed, we call the server, which loads the USFM from disk, converts it to USX, converts that to Deltas, and then records the invalid tags.

Is there any reason why this cannot be done on the frontend only?

I have created a quick demo that matches the output your code was displaying for me, and only runs on the frontend: https://github.com/sillsdev/web-xforge/compare/master...demo/invalid-usfm-frontend-check

Do you think doing this only on the frontend is a viable solution?

(I also think that we should be consistent for naming the variables, etc as "unsupportedTags", not "invalidTags").

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2640#-:-O39zml18dbApmzE5BL6:b-dd8w08)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @josephmyers)



<!-- Sent from Reviewable.io -->

2024-08-01 00:55 UTC, josephmyers reviewed
Thanks for the review. I figured you had an easier way of doing it. Do note that I intentionally use "invalid" and "unsupported" somewhat interchangeably for tags, because they are the same from SF's perspective. We have no way to distinguish between /zup and /peterchapman that I know of.

Also, I didn't test this, but if the "ngIf" conditions follow logic I've seen from most other languages, my new method is only called when the text is invalid. So it shouldn't be called for every text. I bring this up, because I'd like to learn if I'm missing something.

Your branch is clearly better, but it still needs testing, for one. Should we just close my PR out and make one for yours, or do something else?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2640#-:-O3AOkLjA0_4IoCmWqOj:b-sz2qmd)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @pmachapman)



<!-- Sent from Reviewable.io -->

2024-08-01 02:54 UTC, pmachapman reviewed
> We have no way to distinguish between /zup and /peterchapman that I know of.

True. The only difference between the two is one will be in custom.sty, the other will not. I guess I only raised it as a difference between your warning wording and your variable names.

> Also, I didn't test this, but if the "ngIf" conditions follow logic I've seen from most other languages, my new method is only called when the text is invalid. So it shouldn't be called for every text. I bring this up, because I'd like to learn if I'm missing something.

Your call to `projectService.getInvalidTags()` occurs every time a text is loaded because it is in the `onTextLoaded` event handler, and is not wrapped in an `if` statement or anything similar.

> Your branch is clearly better, but it still needs testing, for one. Should we just close my PR out and make one for yours, or do something else?

My branch is missing unit tests, and I haven't tested it extensively (it was just a proof of concept - I tested against a few chapters in the Greek NT). Up to you what you want to do moving forward. Your logic is spot-on for identifying invalid/unknown USFM tags, so might be useful for a comparison when looking at other test projects?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2640#-:-O3Aof6XBeQqoZHXu9zv:b-n2orgu)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @josephmyers)



<!-- Sent from Reviewable.io -->

2024-08-01 06:33 UTC, josephmyers reviewed
Thanks, I totally whiffed on the "if" condition. I was thinking of the previous iteration. We would just wrap this in an `isValid` check to reduce the frequency of polling.

My current thought is to just undo a portion of my changes and replace them with your code. I'll have to redo the tests and fill in the logic, but it'll be easier than the backend development.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2640#-:-O3B_1yPEXoUS6bEt5wQ:byvwffz)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @pmachapman)



<!-- Sent from Reviewable.io -->

2024-08-01 08:52 UTC, josephmyers reviewed
I think I captured the intent of your solution, while cleaning it up for production and filling out the logic. When I get back to this, I'll remove the old solution and work on the testing.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2640#-:-O3C7fmSBkJnciIyssPt:bge8hxc)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @pmachapman)



<!-- Sent from Reviewable.io -->

2024-08-01 08:56 UTC, josephmyers commented on src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts
> +  } else if (deltaOp && typeof deltaOp === 'object') {
Hm, I'll take a look at this Monday. I thought I was preserving Peter's code -- maybe there's some deadness?

2024-08-05 19:38 UTC, pmachapman requested changes
Just one nit, then it looks good to go!

> Reviewed 2 of 10 files at r1, 1 of 2 files at r3, 10 of 10 files at r5, all commit messages.
> Dismissed @github-advanced-security[bot] from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2640#-:-O3Z2-JlAcQu4nJKHYRu:b-v6x6gb)* status: all files reviewed, 1 unresolved discussion (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts` line 250 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2640#gh-1699723396:-O3Z0iot7g0JbxxBUzSi:bb6un1j) ([raw file](https://github.com/sillsdev/web-xforge/blob/8f1cd0e4a52e179caa7ad317a3a29e9c797c1ba2/src/SIL.XForge.Scripture/ClientApp/src/app/shared/utils.ts#L250)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Hm, I'll take a look at this Monday. I thought I was preserving Peter's code -- maybe there's some deadness?
</blockquote></details>

Done
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 927 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/2640#-O3Z1j0w9807NdS_xZqH:-O3Z1j0w9807NdS_xZqI:b-se95r0) ([raw file](https://github.com/sillsdev/web-xforge/blob/8fba5cd321c48136bc33c3a5a520f77cadf2c05d/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L927)):*
> ```XML
>   }
> 
>   async onTextLoaded(textType: TextType): Promise<void> {
> ```

Nit: This doesn't need to be async:
```ts
onTextLoaded(textType: TextType): void {
```



_Code quote:_
```XML
async onTextLoaded(textType: TextType): Promise<void> {
```


<!-- Sent from Reviewable.io -->

2024-08-06 00:40 UTC, pmachapman approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2640#-:-O3_7JNQ6szAPezPZzK-:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @josephmyers)



<!-- Sent from Reviewable.io -->

2024-08-12 15:36 UTC, Nateowami commented
@josephmyers This just needs merge conflicts resolved. Realistically, I think the easiest option is to copy `editor.component.html` from master, then manually re-do your changes.

2024-08-14 00:49 UTC, merged