SF-2886 Allow adding a draft book to a different project
sillsdev/web-xforge pull request #2667
Opened 2024-08-09 22:58 UTC by RaymondLuong3

This change introduces the ability to add a draft to a different project. Tests need to be fixed, but I wanted to get this under review before I can fully get the tests to work.
See the [balsamiq mockup](https://balsamiq.cloud/sghq53/pejrlz8/r1550)

![Add draft to alternate project dialog](https://github.com/user-attachments/assets/afae464a-67b9-4581-b216-95062dd7dce7)

2024-08-13 19:38 UTC, pmachapman requested changes
Just a few minor comments for the interim review...

> Reviewed 9 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2667#-:-O4CBBZpE10h2k-4P9Gz:blir8th)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-handling.service.ts` line 189 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2667#-O4C84Cd5G4OqqaBSZ9L:-O4C84Cd5G4OqqaBSZ9M:b-ufzmoz) ([raw file](https://github.com/sillsdev/web-xforge/blob/da4ab7144c9af1a8233cdd3334b57d69c3b87331/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-handling.service.ts#L189)):*
> ```XML
>     project: SFProjectProfile,
>     draftTextDocId: TextDocId,
>     targetTextDocId: TextDocId
> ```

Are you able to document all of these arguments in the jsdoc?



_Code quote:_
```XML
    project: SFProjectProfile,
    draftTextDocId: TextDocId,
    targetTextDocId: TextDocId
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-handling.service.ts` line 207 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2667#-O4C7wPS1TeTaUn6BjPs:-O4C7wPT3_xx-a209ZT6:b-jjrwsl) ([raw file](https://github.com/sillsdev/web-xforge/blob/da4ab7144c9af1a8233cdd3334b57d69c3b87331/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-handling.service.ts#L207)):*
> ```XML
>         }
>         const draftDelta: DeltaStatic = new Delta(ops);
>         await this.applyChapterDraftAsync(targetTextDocId ?? draftTextDocId, draftDelta);
> ```

This coalesce doesn't make sense as  `targetTextDocId` is not nullable.



_Code quote:_
```XML
targetTextDocId ?? draftText
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-dialog/draft-apply-dialog.component.html` line 20 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2667#-O4CBeprBMKD2z-CuPim:-O4CBeprBMKD2z-CuPin:b-mhgo4a) ([raw file](https://github.com/sillsdev/web-xforge/blob/da4ab7144c9af1a8233cdd3334b57d69c3b87331/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-dialog/draft-apply-dialog.component.html#L20)):*
> ```HTML
>         <p>
>           <span [innerHTML]="connectOtherProject?.before"></span>
>           <!-- TODO: Get page to open in new tab -->
> ```

I am not sure if a new tab will work for the PWA? Maybe just navigate and close this dialog?



_Code quote:_
```HTML
<!-- TODO: Get page to open in new tab -->
```


<!-- Sent from Reviewable.io -->

2024-08-14 05:42 UTC, josephmyers submitted a review, later dismissed
Assuming the screenshot at the top is up to date, can you center the icon and label with the checkbox and text below it? Similar to Balsamiq. Thanks

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2667#-:-O4EP0aK1pv4cyBmDnZS:bixfdxt)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @pmachapman and @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2024-08-22 23:02 UTC, RaymondLuong3 reviewed
How about this
![image.png](https://files.reviewableusercontent.io/images/reviewable/17931130/7OvHCU-gueXyRCFWqyUZwYiC/image.png)

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2667#-:-O4wJPjP3QCjIiqCIYAT:b-rs6io8)* status: 3 of 10 files reviewed, 3 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-handling.service.ts` line 189 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2667#-O4C84Cd5G4OqqaBSZ9L:-O4wJXs7DYTtzPCarY68:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/da4ab7144c9af1a8233cdd3334b57d69c3b87331/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-handling.service.ts#L189)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Are you able to document all of these arguments in the jsdoc?
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-handling.service.ts` line 207 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2667#-O4C7wPS1TeTaUn6BjPs:-O4wJZnN6YWpFJlAtAqb:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/da4ab7144c9af1a8233cdd3334b57d69c3b87331/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-handling.service.ts#L207)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

This coalesce doesn't make sense as  `targetTextDocId` is not nullable.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-dialog/draft-apply-dialog.component.html` line 20 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2667#-O4CBeprBMKD2z-CuPim:-O4wJgqv7fLwle7Az4iH:b-c5zlhy) ([raw file](https://github.com/sillsdev/web-xforge/blob/da4ab7144c9af1a8233cdd3334b57d69c3b87331/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-dialog/draft-apply-dialog.component.html#L20)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

I am not sure if a new tab will work for the PWA? Maybe just navigate and close this dialog?
</blockquote></details>

I think you might be right which explains why it does not work how I expect.


<!-- Sent from Reviewable.io -->

2024-08-26 00:53 UTC, pmachapman approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

It does look good to me, I just want to point out a minor nit when a book has one chapter that has content. Not sure if or how you want to solve it ("1 chapters"):

![image.png](https://files.reviewableusercontent.io/images/reviewable/8665431/9W6xsHRZ0DARpxgQMfGt0_xF/image.png)

> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2667#-:-O5B9gK16SO12JCnn6z4:b-1as4wj)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2024-08-30 23:22 UTC, marksvc requested changes
I approve of the change from r2 to r3, excepting my comments.

Thanks for your work!

> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2667#-:-O5_a9gdAEWTE2MX9m1E:bxfreej)* status: all files reviewed, 4 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-dialog/draft-apply-dialog.component.spec.ts` line 173 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2667#-O5_UZSQ0A5PDxz7qPnK:-O5_UZSQ0A5PDxz7qPnL:b-s2s032) ([raw file](https://github.com/sillsdev/web-xforge/blob/641d002fc7313bed54dde3704cbf99124be6f760/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-dialog/draft-apply-dialog.component.spec.ts#L173)):*
> ```XML
>     tick();
>     env.fixture.detectChanges();
>     expect(env.targetProjectContent).toBeNull();
> ```

It isn't clear from the test why this would be. A comment would be helpful, or you could use something like
```ts
const projectTheUserCannotAccess='pt02';
```
which would make it more clear why `toBeNull()` happened. (If that is what was happening.)

I see from the previous test that this is probably the situation. Okay, and reading more of the TestEnvironment helps me see that, too.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-dialog/draft-apply-dialog.component.spec.ts` line 177 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2667#-O5_XjOF-OUhabY98sIL:-O5_XjOF-OUhabY98sIM:b-8zgeoq) ([raw file](https://github.com/sillsdev/web-xforge/blob/641d002fc7313bed54dde3704cbf99124be6f760/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-dialog/draft-apply-dialog.component.spec.ts#L177)):*
> ```XML
> 
>   it('notifies user if offline', fakeAsync(async () => {
>     env.component.addToProjectForm.controls.targetParatextId.setValue('pt01');
> ```

I'm confused why targetParatextId.setValue() _and_ projectSelectedAsync() are both done. I would have thought setting the control is going to cause projectSelectedAsync(). But maybe I would understand if I played with it.

However, I'm further confused why in the previous test, only projectSelectedAsync() is called rather than also targetParatextId.setValue().
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-dialog/draft-apply-dialog.component.spec.ts` line 187 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2667#-O5_Vdcn15p68TSxj6q9:-O5_Vdcn15p68TSxj6qA:b-k2kr55) ([raw file](https://github.com/sillsdev/web-xforge/blob/641d002fc7313bed54dde3704cbf99124be6f760/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-dialog/draft-apply-dialog.component.spec.ts#L187)):*
> ```XML
>     env.fixture.detectChanges();
>     expect(env.addButton.attributes['disabled']).toBeUndefined();
>     when(mockedOnlineStatusService.isOnline).thenReturn(false);
> ```

I think it would be good to have a look at `file.service.spec.ts` for an example of how to use the OnlineStatusService in tests.
For example, you import TestOnlineStatusModule and  TestOnlineStatusService, and in tests you can write `env.onlineStatus = true` or `env.onlineStatus = false` to set online or offline status. 

This may seem like overkill since your test is working, but there are several public API pieces exposed on OnlineStatusService, and manually mocking only some of them can lead to false-negative passing tests later on. Using TestOnlineStatusService lets you comprehensively mock the OnlineStatusService and set its values.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-dialog/draft-apply-dialog.component.spec.ts` line 304 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2667#-O5__M4R5KH9J50Hp7D_:-O5__M4R5KH9J50Hp7Da:b9emsci) ([raw file](https://github.com/sillsdev/web-xforge/blob/641d002fc7313bed54dde3704cbf99124be6f760/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-dialog/draft-apply-dialog.component.spec.ts#L304)):*
> ```XML
>             ]
>           },
>           projectNum++
> ```

I think this and the `let projectNum = 1;` above might be left over from something?


<!-- Sent from Reviewable.io -->

2024-09-03 20:19 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2667)* status: all files reviewed, 3 unresolved discussions (waiting on @marksvc)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-dialog/draft-apply-dialog.component.spec.ts` line 173 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2667#-O5_UZSQ0A5PDxz7qPnK:-O5sp24e9zNPXl7260Aa:btyeq5o) ([raw file](https://github.com/sillsdev/web-xforge/blob/641d002fc7313bed54dde3704cbf99124be6f760/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-dialog/draft-apply-dialog.component.spec.ts#L173)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

It isn't clear from the test why this would be. A comment would be helpful, or you could use something like
```ts
const projectTheUserCannotAccess='pt02';
```
which would make it more clear why `toBeNull()` happened. (If that is what was happening.)

I see from the previous test that this is probably the situation. Okay, and reading more of the TestEnvironment helps me see that, too.
</blockquote></details>

Good thinking. Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-dialog/draft-apply-dialog.component.spec.ts` line 177 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2667#-O5_XjOF-OUhabY98sIL:-O5t6s5t2OZqv0ou2_Lj:bf52s9n) ([raw file](https://github.com/sillsdev/web-xforge/blob/641d002fc7313bed54dde3704cbf99124be6f760/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-dialog/draft-apply-dialog.component.spec.ts#L177)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I'm confused why targetParatextId.setValue() _and_ projectSelectedAsync() are both done. I would have thought setting the control is going to cause projectSelectedAsync(). But maybe I would understand if I played with it.

However, I'm further confused why in the previous test, only projectSelectedAsync() is called rather than also targetParatextId.setValue().
</blockquote></details>

Yea, it's a bit unfortunate. It seems that force setting the value into the form control doesn't trigger the event to emit from the project select. But it is required to get the form to be valid and the select button to be enabled. I've added a helper function for selecting a project which will simulate triggering the right things.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-dialog/draft-apply-dialog.component.spec.ts` line 187 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2667#-O5_Vdcn15p68TSxj6q9:-O5tXH0h9ABISYG_85g6:b-2332di) ([raw file](https://github.com/sillsdev/web-xforge/blob/641d002fc7313bed54dde3704cbf99124be6f760/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-dialog/draft-apply-dialog.component.spec.ts#L187)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I think it would be good to have a look at `file.service.spec.ts` for an example of how to use the OnlineStatusService in tests.
For example, you import TestOnlineStatusModule and  TestOnlineStatusService, and in tests you can write `env.onlineStatus = true` or `env.onlineStatus = false` to set online or offline status. 

This may seem like overkill since your test is working, but there are several public API pieces exposed on OnlineStatusService, and manually mocking only some of them can lead to false-negative passing tests later on. Using TestOnlineStatusService lets you comprehensively mock the OnlineStatusService and set its values.
</blockquote></details>

That is a good point. It might be overkill, but since it is not too difficult I've made the change to use the TestOnlineStatusService.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-dialog/draft-apply-dialog.component.spec.ts` line 304 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2667#-O5__M4R5KH9J50Hp7D_:-O5tXT1iEvlfdFF_o6Gf:b7cbhui) ([raw file](https://github.com/sillsdev/web-xforge/blob/641d002fc7313bed54dde3704cbf99124be6f760/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-apply-dialog/draft-apply-dialog.component.spec.ts#L304)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I think this and the `let projectNum = 1;` above might be left over from something?
</blockquote></details>

No, this is necessary when calling createTestProjectProfile so that each instance of the testProjectProfile gets the correct project name.


<!-- Sent from Reviewable.io -->

2024-09-04 03:00 UTC, merged