SF-2894 Create new record dialog
sillsdev/web-xforge pull request #2676
Opened 2024-08-20 04:29 UTC by nigel-wells

This functionality is NOT in use within the app. 

The intention of this new component is to provide a consistent way of recording audio anywhere in SF. It has been heavily based off the current `CheckingAudioRecorderComponent` component.

Stories have been created to show the intention of the different states. The main new flow is when this dialog opens it immediately starts a countdown for the user and then starts recording.

New Jira tasks can be created to integrate it into the Community Checking components to replace the existing `CheckingAudioRecorderComponent`

2024-08-20 04:58 UTC, josephmyers commented
Is there any way we can get a diff between these new files and the original `CheckingAudioRecorderComponent`? That'd be really helpful for reviewing.

And backing up a second, what is the big risk with editing the original files? Is it that breaking? Can we not get it to a point where what we have can be merged to production?

2024-08-20 20:49 UTC, Nateowami commented
Great work. I think on this screen
1. The tooltip would be better above or below the button.
2. The "stop" button would be better if it remained white, like the mic button. At it's darkest, there's not that much contrast between the black stop button, and the dark red background.

![](https://github.com/user-attachments/assets/6ffa06bf-a16a-4382-8321-5d6f74eb974b)

2024-08-22 03:45 UTC, nigel-wells commented
I've made those adjustments @Nateowami - looks much better now.
I've given the stories an overhaul as well - hopefully Chromatic allows the tests to pass now.

2024-08-22 17:11 UTC, RaymondLuong3 requested changes
> Reviewed 1 of 7 files at r1, 2 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2676)* status: 3 of 7 files reviewed, 12 unresolved discussions (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.html` line 27 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2676#-O4uvUaw153kSaNFMLM0:-O4uvUaw153kSaNFMLM1:bfba1br) ([raw file](https://github.com/sillsdev/web-xforge/blob/828424edd661623e223d4d19e9bd056dd5e2614a/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.html#L27)):*
> ```HTML
>             >
>               <mat-icon class="mic-icon">mic</mat-icon>
>               <mat-icon class="stop-icon">stop</mat-icon>
> ```

What would happen if the user was on a mobile device. They would never see the stop recording icon or the tooltip. It would be best to just keep the stop icon so the user knows the button will stop the recording.
Alternatively, you could detect the user's screensize, but even then you can't be sure the user is using a laptop.



_Code quote:_
```HTML
              <mat-icon class="stop-icon">stop</mat-icon>
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.html` line 40 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2676#-O4usnfeEKIvcJ-gj3p8:-O4usnfeEKIvcJ-gj3p9:b9xrzjf) ([raw file](https://github.com/sillsdev/web-xforge/blob/828424edd661623e223d4d19e9bd056dd5e2614a/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.html#L40)):*
> ```HTML
>       }
>     </div>
>     <div class="has-attachment" [ngClass]="{ visible: hasAudioAttachment }">
> ```

By setting the visible class on this `div`, are you trying to keep the elements on the page from shifting up. Otherwise, this could have been inside of an `@if`.



_Code quote:_
```HTML
    <div class="has-attachment" [ngClass]="{ visible: hasAudioAttachment }">
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.html` line 42 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2676#-O4usNFWBRpeqT854CmV:-O4usNFWBRpeqT854CmW:b-eybwcv) ([raw file](https://github.com/sillsdev/web-xforge/blob/828424edd661623e223d4d19e9bd056dd5e2614a/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.html#L42)):*
> ```HTML
>     <div class="has-attachment" [ngClass]="{ visible: hasAudioAttachment }">
>       <button mat-flat-button color="primary" (click)="resetRecording()" class="remove-audio-file">
>         <mat-icon>mic</mat-icon> Re-record
> ```

This should be internationalized



_Code quote:_
```HTML
 Re-record
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.html` line 44 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2676#-O4usR1ODOr9HEBRyavC:-O4usR1ODOr9HEBRyavD:b-eybwcv) ([raw file](https://github.com/sillsdev/web-xforge/blob/828424edd661623e223d4d19e9bd056dd5e2614a/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.html#L44)):*
> ```HTML
>         <mat-icon>mic</mat-icon> Re-record
>       </button>
>       <button mat-button (click)="saveRecording()" class="save-audio-file"><mat-icon>check</mat-icon> Save</button>
> ```

This should be internationalized



_Code quote:_
```HTML
 Save</button>
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.ts` line 43 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2676#-O4uyktJ5uU3__9hqU3X:-O4uyktJ5uU3__9hqU3Y:bw9dygg) ([raw file](https://github.com/sillsdev/web-xforge/blob/828424edd661623e223d4d19e9bd056dd5e2614a/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.ts#L43)):*
> ```XML
>       provide: NG_VALUE_ACCESSOR,
>       multi: true,
>       useExisting: AudioRecorderDialogComponent
> ```

What does this mean? Since this is the audio recorder dialog, what does this do?



_Code quote:_
```XML
      useExisting: AudioRecorderDialogComponent
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.ts` line 107 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2676#-O4v-ASH0hrtsPkmdHGw:-O4v-ASH0hrtsPkmdHGx:b3lz2cb) ([raw file](https://github.com/sillsdev/web-xforge/blob/828424edd661623e223d4d19e9bd056dd5e2614a/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.ts#L107)):*
> ```XML
>   get isRecording(): boolean {
>     return this.mediaRecorder != null && this.mediaRecorder.state === 'recording';
>   }
> ```

move these getters under the constructor and above the class methods.



_Code quote:_
```XML
  get hasAudioAttachment(): boolean {
    return this.audio.url !== undefined;
  }

  get isRecording(): boolean {
    return this.mediaRecorder != null && this.mediaRecorder.state === 'recording';
  }
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.ts` line 118 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2676#-O4v-HWY0GFUh6b5MnGg:-O4v-HWY0GFUh6b5MnGh:batate8) ([raw file](https://github.com/sillsdev/web-xforge/blob/828424edd661623e223d4d19e9bd056dd5e2614a/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.ts#L118)):*
> ```XML
>     this.mediaDevicesUnsupported =
>       this.navigator.mediaDevices?.getUserMedia == null || typeof MediaRecorder === 'undefined';
>   }
> ```

Nit: Move these to just under the getters



_Code quote:_
```XML
  ngOnDestroy(): void {
    if (this.isRecording) {
      this.stopRecording();
    }
  }

  async ngOnInit(): Promise<void> {
    this.mediaDevicesUnsupported =
      this.navigator.mediaDevices?.getUserMedia == null || typeof MediaRecorder === 'undefined';
  }
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.ts` line 191 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2676#-O4v2kiRDzaZZGEG6r4v:-O4v2kiRDzaZZGEG6r4w:b-58wmre) ([raw file](https://github.com/sillsdev/web-xforge/blob/828424edd661623e223d4d19e9bd056dd5e2614a/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.ts#L191)):*
> ```XML
>       const statusPromise = this.status.subscribe((status: AudioAttachment) => {
>         if (status.status === 'processed') {
>           resolve();
> ```

Nit: It feels better to unsubscribe before resolving the promise


<!-- Sent from Reviewable.io -->

2024-08-22 19:58 UTC, RaymondLuong3 requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2676)* status: 3 of 7 files reviewed, 18 unresolved discussions (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.spec.ts` line 66 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2676#-O4v_K872tvDI93rMxVD:-O4v_K872tvDI93rMxVE:b-hom9kz) ([raw file](https://github.com/sillsdev/web-xforge/blob/828424edd661623e223d4d19e9bd056dd5e2614a/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.spec.ts#L66)):*
> ```XML
>     expect(env.recordButton).toBeFalsy();
>     expect(env.stopRecordingButton).toBeTruthy();
>     env.clickButton(env.stopRecordingButton);
> ```

You can also check that the recording has stopped. If it is easy, also check the component's audio attachment is processed.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.spec.ts` line 82 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2676#-O4vacf85ywJv18WQLJ4:-O4vacf85ywJv18WQLJ5:btc8413) ([raw file](https://github.com/sillsdev/web-xforge/blob/828424edd661623e223d4d19e9bd056dd5e2614a/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.spec.ts#L82)):*
> ```XML
>     env.clickButton(env.tryAgainButton);
>     expect(env.recordButton).toBeTruthy();
>   });
> ```

Can we write a test to show that if the countdown is provided to the dialog, the countdown appears and the recording start automatically after that.
Update: I see you have a story book that is testing this behaviour. So feel free to ignore this.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.spec.ts` line 114 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2676#-O4vaK1F8BsQ3Yg3mlbg:-O4vaK1F8BsQ3Yg3mlbh:b-jnruuu) ([raw file](https://github.com/sillsdev/web-xforge/blob/828424edd661623e223d4d19e9bd056dd5e2614a/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.spec.ts#L114)):*
> ```XML
>     verify(mockedDialog.openMatDialog(SupportedBrowsersDialogComponent, anything())).once();
>     expect().nothing();
>   });
> ```

Are you able to test whether the audio attachment is returned when the user clicks on "Save Recording"?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.spec.ts` line 142 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2676#-O4vYd0X4CfDM7SwFua0:-O4vYd0X4CfDM7SwFua1:bl3cq8n) ([raw file](https://github.com/sillsdev/web-xforge/blob/828424edd661623e223d4d19e9bd056dd5e2614a/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.spec.ts#L142)):*
> ```XML
>     when(mockedNavigator.mediaDevices).thenReturn({
>       getUserMedia: (mediaConstraints: MediaStreamConstraints) =>
>         this.rejectUserMedia ? Promise.reject('No microphone') : navigator.mediaDevices.getUserMedia(mediaConstraints)
> ```

This looks like it is using the actual navigator for the window. Is this something we want to mock? It's possible that these tests will be run on different browsers, and the test won't behave correctly if there is no access to user media for the browser (I suspect these tests are only run on chrome and chrome headless).
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.spec.ts` line 147 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2676#-O4vZOz6AVvfQ3cY5ALc:-O4vZOz6AVvfQ3cY5ALd:bjxyhle) ([raw file](https://github.com/sillsdev/web-xforge/blob/828424edd661623e223d4d19e9bd056dd5e2614a/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.spec.ts#L147)):*
> ```XML
>   }
> 
>   async getAudioDuration(): Promise<number> {
> ```

Move this below the getters



_Code quote:_
```XML
  async getAudioDuration(): Promise<number> {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.stories.ts` line 27 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2676#-O4vbgI7-P66qafwL1Bo:-O4vbgI7-P66qafwL1Bp:b-1s53dc) ([raw file](https://github.com/sillsdev/web-xforge/blob/828424edd661623e223d4d19e9bd056dd5e2614a/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.stories.ts#L27)):*
> ```XML
>   const audioContext = new window.AudioContext();
>   const oscillator = audioContext.createOscillator();
>   const destination = audioContext.createMediaStreamDestination();
> ```

Nit: Add types here



_Code quote:_
```XML
  const oscillator = audioContext.createOscillator();
  const destination = audioContext.createMediaStreamDestination();
```


<!-- Sent from Reviewable.io -->

2024-08-26 02:34 UTC, nigel-wells reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2676)* status: 1 of 8 files reviewed, 15 unresolved discussions (waiting on @github-advanced-security[bot] and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.html` line 27 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2676#-O4uvUaw153kSaNFMLM0:-O5BW7kz68C-MGqKU63f:byue0lh) ([raw file](https://github.com/sillsdev/web-xforge/blob/828424edd661623e223d4d19e9bd056dd5e2614a/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.html#L27)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

What would happen if the user was on a mobile device. They would never see the stop recording icon or the tooltip. It would be best to just keep the stop icon so the user knows the button will stop the recording.
Alternatively, you could detect the user's screensize, but even then you can't be sure the user is using a laptop.
</blockquote></details>

Fair point - I've changed it to always be the stop icon while recording.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.html` line 40 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2676#-O4usnfeEKIvcJ-gj3p8:-O5BMwLz6kxrw7Tfp_F9:buo5xma) ([raw file](https://github.com/sillsdev/web-xforge/blob/828424edd661623e223d4d19e9bd056dd5e2614a/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.html#L40)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

By setting the visible class on this `div`, are you trying to keep the elements on the page from shifting up. Otherwise, this could have been inside of an `@if`.
</blockquote></details>

Correct, I wanted to avoid the dialog growing/shrinking depending on what state it was in.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.html` line 42 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2676#-O4usNFWBRpeqT854CmV:-O5BNVuG1-IXSVUSDaWC:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/828424edd661623e223d4d19e9bd056dd5e2614a/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.html#L42)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This should be internationalized
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.html` line 44 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2676#-O4usR1ODOr9HEBRyavC:-O5BNW9H4YQ7_RImX4nz:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/828424edd661623e223d4d19e9bd056dd5e2614a/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.html#L44)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This should be internationalized
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.ts` line 14 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2676#gh-1722671477:-O5BNf4X7Y59AWZqm7D7:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/ac86f5405385f50dccb76b1acbb313a6fbc49edd/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.ts#L14)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Unused variable, import, function or class

Unused import interval.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/850)
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.ts` line 15 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2676#gh-1722671479:-O5BNjY13FzQKgedtHMg:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/ac86f5405385f50dccb76b1acbb313a6fbc49edd/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.ts#L15)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Unused variable, import, function or class

Unused import startWith.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/851)
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.ts` line 43 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2676#-O4uyktJ5uU3__9hqU3X:-O5BOHkT9Ve5W2evqO-o:b-bpw9ag) ([raw file](https://github.com/sillsdev/web-xforge/blob/828424edd661623e223d4d19e9bd056dd5e2614a/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.ts#L43)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

What does this mean? Since this is the audio recorder dialog, what does this do?
</blockquote></details>

I have removed. This was part of the CheckingAudioRecorderComponent which this new component is mostly an exact copy of. That code appears to relate to offering state changes to forms which isn't relevant for this new implementation.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.ts` line 107 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2676#-O4v-ASH0hrtsPkmdHGw:-O5BOgSKC2DcGkFKdcrU:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/828424edd661623e223d4d19e9bd056dd5e2614a/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.ts#L107)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

move these getters under the constructor and above the class methods.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.spec.ts` line 1 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2676#gh-1722671474:-O5BPLyRCMpO50KNPAkG:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/ac86f5405385f50dccb76b1acbb313a6fbc49edd/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.spec.ts#L1)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Unused variable, import, function or class

Unused import DebugElement.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/848)
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.spec.ts` line 3 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2676#gh-1722671475:-O5BPMFO36zM94mcqVCu:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/ac86f5405385f50dccb76b1acbb313a6fbc49edd/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.spec.ts#L3)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Unused variable, import, function or class

Unused import By.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/849)
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.spec.ts` line 66 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2676#-O4v_K872tvDI93rMxVD:-O5BQhAz9dl3-KJL3rgx:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/828424edd661 [...]

2024-08-26 18:35 UTC, RaymondLuong3 reviewed
Things look good here. On to the point that @josephmyers mentioned, I wonder if we should try to put the audio recorder logic into a service and then use that service for both the audio recorder dialog and audio recorder component... Or maybe the goal is to remove the audio recorder component (that probably won't be the case since answers will still be recorded with the audio recorder component).
That can be a follow-up PR.

> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2676#-:-O5EwwMf3MZH1njBLgvR:b8mieek)* status: all files reviewed, 4 unresolved discussions (waiting on @github-advanced-security[bot])



<!-- Sent from Reviewable.io -->

2024-08-26 23:32 UTC, nigel-wells reviewed
I had understood the intention was for all instances where we record audio need to switch over to use the new dialog - these would be new Jira tasks. If we were planning on having multiple recording components then, yes, it would make sense to have a better way to share common functionality in a service.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2676#-:-O5G0lNiCa-Xl_Q5i37R:b-6bpxa6)* status: all files reviewed, 4 unresolved discussions (waiting on @github-advanced-security[bot])



<!-- Sent from Reviewable.io -->

2024-08-27 15:47 UTC, merged