SF-2950 Users authentication fails when trying to join a project with a share link
sillsdev/web-xforge pull request #2709
Opened 2024-09-06 04:22 UTC by nigel-wells

I've added comments to the Jira card explaining the situation as well as some to our `auth.service`.

TLDR: Tokens had expired in Scripture Forge but were still valid when on the Auth0 website login page

2024-09-06 12:02 UTC, kylebuss reviewed
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2709)* status: all files reviewed, 3 unresolved discussions (waiting on @nigel-wells)

*[a discussion](https://reviewable.io/reviews/sillsdev/web-xforge/2709#-O66-QMyDag9kxslpABi:-O66-QMzCnFLQ3XzpCzx:b63xswq) (no related file):*
Thanks for looking into/working on this!

___
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts` line 432 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2709#-O66ASEHBuH_FZP19DpX:-O66ASEHBuH_FZP19DpY:blmqemu) ([raw file](https://github.com/sillsdev/web-xforge/blob/7e45efe781de78dd965658a15915b90ba1ac4a26/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts#L432)):*
> ```XML
>             // Return a NEVER promise to graceful wait for the redirection to complete without showing the join page
>             return new Promise<never>(() => {});
>           } else if (await this.tryTransparentAuthentication()) {
> ```

This does resolve the issue.

I might be missing something as I'm not 100% sure we need to use the `auth0.loginWithRedirect` here. We appear to be utilizing auth0's refresh tokens and I wonder if refreshing the token that way would be a better way of handling cases like this?

I don't think we need to change anything for this issue, but something we may want to consider looking into.



_Code quote:_
```XML
          if (this.idToken != null) {
            await this.logIn({ returnUrl: this.locationService.pathname + this.locationService.search });
            // Return a NEVER promise to graceful wait for the redirection to complete without showing the join page
            return new Promise<never>(() => {});
          } else if (await this.tryTransparentAuthentication()) {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.spec.ts` line 697 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2709#-O663jmF70b8TyVb4HHS:-O663jmF70b8TyVb4HHT:b-6w0qym) ([raw file](https://github.com/sillsdev/web-xforge/blob/7e45efe781de78dd965658a15915b90ba1ac4a26/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.spec.ts#L697)):*
> ```XML
>   }));
> 
>   it('should not try join with transparent authentication if a user was previously logged in at some point', fakeAsync(() => {
> ```

nit Not sure this test name is clear. Maybe something like 'should verify if user is still logged in via auth0 and join project without transparent authentication'



_Code quote:_
```XML
should not try join with transparent authentication if a user was previously logged in at some point
```


<!-- Sent from Reviewable.io -->

2024-09-09 04:47 UTC, nigel-wells reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2709)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @kylebuss)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts` line 432 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2709#-O66ASEHBuH_FZP19DpX:-O6Jqcy9DImrYo4m3ZuK:byw6gym) ([raw file](https://github.com/sillsdev/web-xforge/blob/7e45efe781de78dd965658a15915b90ba1ac4a26/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts#L432)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

This does resolve the issue.

I might be missing something as I'm not 100% sure we need to use the `auth0.loginWithRedirect` here. We appear to be utilizing auth0's refresh tokens and I wonder if refreshing the token that way would be a better way of handling cases like this?

I don't think we need to change anything for this issue, but something we may want to consider looking into.
</blockquote></details>

Thanks for raising. I initially went with redirecting to Auth0 as it was more full proof. We can try and renew tokens for users who are in between states and then only redirect to Auth0 if it really doesn't work. Initially testing showed this worked well.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.spec.ts` line 697 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2709#-O663jmF70b8TyVb4HHS:-O6K4svMDoMwY7_B4Jjz:bekrhth) ([raw file](https://github.com/sillsdev/web-xforge/blob/7e45efe781de78dd965658a15915b90ba1ac4a26/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.spec.ts#L697)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

nit Not sure this test name is clear. Maybe something like 'should verify if user is still logged in via auth0 and join project without transparent authentication'
</blockquote></details>

Have refactored this a bit based on your previous comment - let me know what you think now.


<!-- Sent from Reviewable.io -->

2024-09-09 12:37 UTC, kylebuss requested changes
Glad to see that renewing tokens was an easy change and is working well. Thanks for working on this!

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2709#-:-O6LiV-h4wGAYqk2UDIq:b-7gbg4k)* status: all files reviewed, 3 unresolved discussions (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts` line 266 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2709#-O6Li6eXDd0xJ5MjQ7SD:-O6Li6eXDd0xJ5MjQ7SE:b-9hxkvb) ([raw file](https://github.com/sillsdev/web-xforge/blob/415b04b611e67ce229ec462ebbb7975c1bf99b85/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts#L266)):*
> ```XML
>     this.unscheduleRenewal();
>     console.log(returnUrl);
>     console.log(auth0Parameters);
> ```

These can be removed.



_Code quote:_
```XML
    console.log(returnUrl);
    console.log(auth0Parameters);
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts` line 443 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2709#-O6Lh1Da7qZAVuk7GHDt:-O6Lh1Da7qZAVuk7GHDu:b-x6dyiz) ([raw file](https://github.com/sillsdev/web-xforge/blob/415b04b611e67ce229ec462ebbb7975c1bf99b85/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts#L443)):*
> ```XML
>             console.log('Tokens have been renewed');
>             await this.remoteStore.init(() => this.getAccessToken());
>             return { loggedIn: true, newlyLoggedIn: true, anonymousUser: true };
> ```

This looks good, the `console.log` statements can be removed.



_Code quote:_
```XML
          console.log('Joining with share key');
          if (this.idToken != null) {
            console.log('User may be logged in - renew tokens');
            // Attempt to renew tokens first otherwise send them to Auth0
            await this.renewTokens();
            if (await this.hasExpired()) {
              console.log('Tokens have expired - send to Auth0');
              // Return a NEVER promise to graceful wait for the redirection to complete from renewTokens
              // without showing the join page
              return new Promise<never>(() => {});
            }
            console.log('Tokens have been renewed');
            await this.remoteStore.init(() => this.getAccessToken());
            return { loggedIn: true, newlyLoggedIn: true, anonymousUser: true };
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts` line 607 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2709#-O6LiQNHD_qwBJos9L8y:-O6LiQNHD_qwBJos9L8z:b-1qn7z6) ([raw file](https://github.com/sillsdev/web-xforge/blob/415b04b611e67ce229ec462ebbb7975c1bf99b85/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts#L607)):*
> ```XML
> 
>   private async renewTokens(): Promise<void> {
>     console.log('Renewing tokens');
> ```

This can be removed.



_Code quote:_
```XML
console.log('Renewing tokens');
```


<!-- Sent from Reviewable.io -->

2024-09-09 20:26 UTC, nigel-wells reviewed
Whoops! Forgot about those logs :)

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2709#-:-O6NSptP8hgDtnSNuOIX:b4br3p)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @kylebuss)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts` line 266 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2709#-O6Li6eXDd0xJ5MjQ7SD:-O6NSo_oDfIWDnn2Zbla:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/415b04b611e67ce229ec462ebbb7975c1bf99b85/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts#L266)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

These can be removed.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts` line 443 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2709#-O6Lh1Da7qZAVuk7GHDt:-O6NSp4u9xeI7nek4EMA:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/415b04b611e67ce229ec462ebbb7975c1bf99b85/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts#L443)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

This looks good, the `console.log` statements can be removed.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts` line 607 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2709#-O6LiQNHD_qwBJos9L8y:-O6NSpMm4nDE73bJqeuv:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/415b04b611e67ce229ec462ebbb7975c1bf99b85/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts#L607)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

This can be removed.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-09 20:45 UTC, kylebuss approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2709#-:-O6NX9USCZgjsioSSFAz:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nigel-wells)



<!-- Sent from Reviewable.io -->

2024-09-12 16:43 UTC, merged