SF-2963 Feature flag/overlay for developer diagnostics
sillsdev/web-xforge pull request #2735
Opened 2024-09-23 16:08 UTC by kylebuss

Added a feature flag to show/hide developer overlay.
Added overlay to display the number of docs subscribed to by the `realtime.service.ts`.

2024-09-23 18:17 UTC, Nateowami requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2735)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @kylebuss and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json` line 296 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O7V4_GjCRZpRApq4aPW:-O7V4_GjCRZpRApq4aPX:byl9tg0) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f21b11898f6363037bafc272d170360d8faa998/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json#L296)):*
> ```JSON
>     "view_answers": "View answers"
>   },
>   "diagnostic-overlay": {
> ```

We shouldn't be internationalizing components that are only for diagnostics. It's extra work for us, and extra work for translators. 
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime.service.ts` line 3 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O7V4ev44u4svqhgsFQm:-O7V4ev44u4svqhgsFQn:bn89xqm) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f21b11898f6363037bafc272d170360d8faa998/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime.service.ts#L3)):*
> ```XML
> import { Injectable, Optional } from '@angular/core';
> import { AppError } from 'xforge-common/exception-handling.service';
> //import { BehaviorSubject, Observable } from 'rxjs';
> ```

Here and lower in the file some lines are commented out.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts` line 208 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O7V4oe-7yBe35FMzVV2:-O7V4oe-7yBe35FMzVV3:basajxw) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f21b11898f6363037bafc272d170360d8faa998/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts#L208)):*
> ```XML
> })
> export class FeatureFlagService {
>   [x: string]: any;
> ```

Why has this been added?


<!-- Sent from Reviewable.io -->

2024-09-23 18:31 UTC, RaymondLuong3 requested changes
This is neat. Thanks for the work. Here are some of what I noticed.

The collapse button could use some spacing.
![image.png](https://files.reviewableusercontent.io/images/reviewable/17931130/efGLY0k1vePPNFoaYdFhYajS/image.png)

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-:-O7V1GGq810yxUNT_PTF:bwtf9qg)* status: all files reviewed, 18 unresolved discussions (waiting on @kylebuss)

___
*[`scripts/db_tools/parse-version.ts` line 40 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O7V-lUn9Kv2pmVim_9r:-O7V-lUn9Kv2pmVim_9s:brk6kk6) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f21b11898f6363037bafc272d170360d8faa998/scripts/db_tools/parse-version.ts#L40)):*
> ```XML
>     'Upload Paratext Zip Files for Pre-Translation Drafting',
>     'Allow mixing in an additional training source',
>     'Display overlay for diagnosing subscribed to docs'
> ```

Nit: I would change this to "doc subscriptions" rather than "subscribed to docs"



_Code quote:_
```XML
 subscribed to docs'
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html` line 197 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O7V8_9T1X-aPN2XshD2:-O7V8_9UEhI13bGVJiF4:bnu5qpu) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f21b11898f6363037bafc272d170360d8faa998/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html#L197)):*
> ```HTML
>       class="app-content"
>       [class.app-content-with-overlay-expanded]="showDiagnosticOverlay && isOverlayExpanded"
>       [class.app-content-with-overlay-collapsed]="showDiagnosticOverlay && !isOverlayExpanded"
> ```

This is not needed. We do not need to collapse the app content when showing this overlay. I am happy with the overlay sitting on top of the content.



_Code quote:_
```HTML
      [class.app-content-with-overlay-expanded]="showDiagnosticOverlay && isOverlayExpanded"
      [class.app-content-with-overlay-collapsed]="showDiagnosticOverlay && !isOverlayExpanded"
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss` line 66 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O7V8lSD3uOB27MLA9n3:-O7V8lSD3uOB27MLA9n4:b-1qn7z6) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f21b11898f6363037bafc272d170360d8faa998/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss#L66)):*
> ```SCSS
>   }
>   .app-content-with-overlay-collapsed {
>     margin-right: 32px;
> ```

This can be removed.



_Code quote:_
```SCSS
  .app-content-with-overlay-expanded {
    margin-right: 25vw;
  }
  .app-content-with-overlay-collapsed {
    margin-right: 32px;
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 67 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O7V2yfJA8Zip1bdtazN:-O7V2yfJA8Zip1bdtazO:b-3ksxfr) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f21b11898f6363037bafc272d170360d8faa998/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L67)):*
> ```XML
>   private permissionsChangedSub?: Subscription;
>   private _isDrawerPermanent: boolean = true;
>   isOverlayExpanded$ = new BehaviorSubject<boolean>(false);
> ```

This overlay is redundant. You can remove it and just read to value for `isOverlayExpanded`.



_Code quote:_
```XML
  isOverlayExpanded$ = new BehaviorSubject<boolean>(false);
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/diagnostic-overlay/diagnostic-overlay.component.html` line 18 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O7V3Onm8kaZF_sl-1HC:-O7V3Onm8kaZF_sl-1HD:brqpasb) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f21b11898f6363037bafc272d170360d8faa998/src/SIL.XForge.Scripture/ClientApp/src/app/diagnostic-overlay/diagnostic-overlay.component.html#L18)):*
> ```HTML
>             <th>{{ t("collection") }}</th>
>             <th>{{ t("doc_count") }}</th>
>           </tr>
> ```

You do not need to internationalize this component. Since it is for developer only, we accept hard coded labels.



_Code quote:_
```HTML
      <h1>{{ t("header") }}</h1>
      <h3>{{ t("total_docs", { totalDocsCount: totalDocsCount }) }}</h3>
      <table class="diagnostic-overlay-table">
        <thead>
          <tr>
            <th>{{ t("collection") }}</th>
            <th>{{ t("doc_count") }}</th>
          </tr>
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/diagnostic-overlay/diagnostic-overlay.component.scss` line 3 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O7V5mk3E9ilCJwCEgaR:-O7V5mk4EzfpZmC8eyvw:b-kcjo2z) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f21b11898f6363037bafc272d170360d8faa998/src/SIL.XForge.Scripture/ClientApp/src/app/diagnostic-overlay/diagnostic-overlay.component.scss#L3)):*
> ```SCSS
> @use 'src/variables';
> 
> @import 'bootstrap/scss/mixins/breakpoints';
> ```

This looks unused. Remove



_Code quote:_
```SCSS
@import 'bootstrap/scss/mixins/breakpoints';
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/diagnostic-overlay/diagnostic-overlay.component.scss` line 12 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O7V6Ws2DbwYDxqkOD0C:-O7V6Ws2DbwYDxqkOD0D:bqwghhr) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f21b11898f6363037bafc272d170360d8faa998/src/SIL.XForge.Scripture/ClientApp/src/app/diagnostic-overlay/diagnostic-overlay.component.scss#L12)):*
> ```SCSS
>   right: 0;
>   width: 25vw; /* Adjust the width as needed */
>   height: 100vh;
> ```

This can be updated to 25% and 100%. For me, that is easier to understand.



_Code quote:_
```SCSS
  width: 25vw; /* Adjust the width as needed */
  height: 100vh;
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/diagnostic-overlay/diagnostic-overlay.component.scss` line 17 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O7V6carEGmv3gPnomyQ:-O7V6carEGmv3gPnomyR:b-kvg1bg) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f21b11898f6363037bafc272d170360d8faa998/src/SIL.XForge.Scripture/ClientApp/src/app/diagnostic-overlay/diagnostic-overlay.component.scss#L17)):*
> ```SCSS
>   box-shadow: 0 2px 10px rgba(0, 0, 0, 0.2);
>   padding: 16px;
>   background-color: #fff;
> ```

Nit: this is not necessary



_Code quote:_
```SCSS
  background-color: #fff;
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/diagnostic-overlay/diagnostic-overlay.component.scss` line 21 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O7V6jZR1eHKcoIUGMCu:-O7V6jZR1eHKcoIUGMCv:b-8px13f) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f21b11898f6363037bafc272d170360d8faa998/src/SIL.XForge.Scripture/ClientApp/src/app/diagnostic-overlay/diagnostic-overlay.component.scss#L21)):*
> ```SCSS
> 
>   &.collapsed {
>     width: 50px; /* Adjust the collapsed width as needed */
> ```

This comments really aren't needed. I think we can remove them



_Code quote:_
```SCSS
/* Adjust the collapsed width as needed */
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json` line 299 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O7V3x7SEpjL54HeqjTP:-O7V3x7SEpjL54HeqjTQ:baah380) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f21b11898f6363037bafc272d170360d8faa998/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json#L299)):*
> ```JSON
>     "collection": "Collection",
>     "doc_count": "Doc Count",
>     "header": "Developer Diagnostics",
> ```

Remove these strings as per above.



_Code quote:_
```JSON
  "diagnostic-overlay": {
    "collection": "Collection",
    "doc_count": "Doc Count",
    "header": "Developer Diagnostics",
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime.service.ts` line 3 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O7V4DbJ2nKsg3ATBcVk:-O7V4DbJ2nKsg3ATBcVl:ba3dfmt) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f21b11898f6363037bafc272d170360d8faa998/src/SIL.XForge.Scripture/ClientApp/src/xforge-com [...]

2024-09-23 18:56 UTC, Nateowami commented
Thanks for your work on this Kyle. I think the approach to the UI however could be significantly improved. Rather than adding something to the app component, I think it would be better to create a dialog or other type of overlay that can open without being part of another component. It can then be opened via a menu item.

There are several reasons for this:
1. In general there's a tendency to add things to the app component whenever we want them to be global, but this leads to a giant complex component. It makes it harder to make changes to the app component. In this particular case, the layout of the app component has actually broken on this branch.
2. I foresee a future where the app component may not be the only top level component.

2024-09-23 22:03 UTC, RaymondLuong3 commented
On a side note, in /scripts/db_tools/parse-version.ts, you will need to update it with the addition of your feature flag.

2024-09-25 20:42 UTC, kylebuss reviewed
Updates have been made. Is this closer to what you were thinking @Nateowami with not putting it in the `app.component` or is there a better way of doing this?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-:-O7euhjJ71UnRcXqoQ2V:b-uieh7t)* status: 1 of 28 files reviewed, 15 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime.service.ts` line 3 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O7V4DbJ2nKsg3ATBcVk:-O7YyV8aCVxkxctCTt6c:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f21b11898f6363037bafc272d170360d8faa998/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime.service.ts#L3)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Remove.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime.service.ts` line 3 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O7V4ev44u4svqhgsFQm:-O7YyVKI8NaY8ENluJ0Z:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f21b11898f6363037bafc272d170360d8faa998/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime.service.ts#L3)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Here and lower in the file some lines are commented out.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime.service.ts` line 27 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O7V4AYP99iGgKY4hIc9:-O7YyWLTC-2__1QWgi9B:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f21b11898f6363037bafc272d170360d8faa998/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime.service.ts#L27)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Remove.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime.service.ts` line 102 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O7V4FTw2FKBDMldrp4u:-O7YyWnW9n7R65kCMQZq:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f21b11898f6363037bafc272d170360d8faa998/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime.service.ts#L102)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Remove.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts` line 36 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O7V4jlA7IhgwN7iC8b7:-O7Yz5od-Q5UFOZOBUYN:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f21b11898f6363037bafc272d170360d8faa998/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts#L36)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I don't see that localFeatureFlags are ever read anywhere. I think they can be removed.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts` line 208 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O7V4oe-7yBe35FMzVV2:-O7euTdw4AH4nGvqr8tj:bh6tk98) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f21b11898f6363037bafc272d170360d8faa998/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts#L208)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Why has this been added?
</blockquote></details>

Not sure what I was trying to do, I've removed it.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html` line 197 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O7V8_9T1X-aPN2XshD2:-O7Ywpo_A_fUYB_JTCgU:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f21b11898f6363037bafc272d170360d8faa998/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.html#L197)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This is not needed. We do not need to collapse the app content when showing this overlay. I am happy with the overlay sitting on top of the content.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss` line 66 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O7V8lSD3uOB27MLA9n3:-O7YwqYp2aYq6cYPVeZq:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f21b11898f6363037bafc272d170360d8faa998/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.scss#L66)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This can be removed.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 67 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O7V2yfJA8Zip1bdtazN:-O7YwrPm5VRMcslL-qz4:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f21b11898f6363037bafc272d170360d8faa998/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L67)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This overlay is redundant. You can remove it and just read to value for `isOverlayExpanded`.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json` line 296 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O7V4_GjCRZpRApq4aPW:-O7YyIhzBcySSXGpTF9l:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f21b11898f6363037bafc272d170360d8faa998/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json#L296)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

We shouldn't be internationalizing components that are only for diagnostics. It's extra work for us, and extra work for translators.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json` line 299 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O7V3x7SEpjL54HeqjTP:-O7YyJDR1hAN1NVFoKgP:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f21b11898f6363037bafc272d170360d8faa998/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json#L299)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Remove these strings as per above.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/diagnostic-overlay/diagnostic-overlay.component.html` line 18 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O7V3Onm8kaZF_sl-1HC:-O7YxP762nW5aMQcRzXC:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f21b11898f6363037bafc272d170360d8faa998/src/SIL.XForge.Scripture/ClientApp/src/app/diagnostic-overlay/diagnostic-overlay.component.html#L18)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

You do not need to internationalize this component. Since it is for developer only, we accept hard coded labels.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/diagnostic-overlay/diagnostic-overlay.component.scss` line 3 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O7V5mk3E9ilCJwCEgaR:-O7YxRuE1nxuflY1tnOW:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f21b11898f6363037bafc272d170360d8faa998/src/SIL.XForge.Scripture/ClientApp/src/app/diagnostic-overlay/diagnostic-overlay.component.scss#L3)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This looks unused. Remove
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/diagnostic-overlay/diagnostic-overlay.component.scss` line 12 at r1](https://review [...]

2024-09-25 21:38 UTC, kylebuss reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2735)* status: 1 of 29 files reviewed, 17 unresolved discussions (waiting on @github-advanced-security[bot], @Nateowami, and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.stories.ts` line 12 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2735#gh-1776007733:-O7f6kJK6ZJ8cOJM_fvq:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/c7c69403177459e9a0ba224ebf8cf0110f325bc1/src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.stories.ts#L12)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Unused variable, import, function or class

Unused import SF_PROJECTS_COLLECTION.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/860)
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.stories.ts` line 34 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2735#gh-1776007735:-O7f6oF23gfMgMOvMvqV:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/c7c69403177459e9a0ba224ebf8cf0110f325bc1/src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.stories.ts#L34)):*
<details><summary><i>Previously, github-advanced-security[bot] wrote…</i></summary><blockquote>

## Unused variable, import, function or class

Unused import SF_DEFAULT_SHARE_ROLE.

[Show more details](https://github.com/sillsdev/web-xforge/security/code-scanning/861)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-09-26 15:22 UTC, Nateowami commented
This is not the right approach. Adding a component to every other major component is not sustainable. Please take a look at how the FeatureFlagsDialogComponent is implemented and use the same strategy there. A menu item can be added to the help menu to trigger the opening of the dialog.

2024-09-27 16:54 UTC, Nateowami commented
Also, please update the PR title to conform to the guidelines in [CONTRIBUTING.md](https://github.com/sillsdev/web-xforge/blob/master/CONTRIBUTING.md)

2024-09-30 21:05 UTC, kylebuss reviewed
Let me know if using the `dialog.service` is okay to use for this or if you think we need a new service for overlays.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-:-O83jmgV0QdjbVWVPLAG:b-5yczxa)* status: 1 of 30 files reviewed, 17 unresolved discussions (waiting on @github-advanced-security[bot], @Nateowami, and @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2024-10-02 18:37 UTC, RaymondLuong3 submitted a review, later dismissed
I think this is much better. I do like that instead of this being a dialog, it is an overlay which allows me to still interact with the app. Nice touch. I think dialog service is a reasonable place to put it, but if you wanted to make an overlay service, that could be re-useable for other overlays.
Remember to make the changes to `/scripts/db_tools/parse-version.ts`

> Reviewed 13 of 28 files at r2, 1 of 1 files at r3, 17 of 17 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-:-O8DW26j6KgZgT5xvRHK:bvo67yb)* status: all files reviewed, 10 unresolved discussions (waiting on @github-advanced-security[bot], @kylebuss, and @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.spec.ts` line 30 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O8DSSHC8Dwx7wjlvjM_:-O8DSSHC8Dwx7wjlvjMa:b53topx) ([raw file](https://github.com/sillsdev/web-xforge/blob/f581cb8141d3e5f0985fe6ab597e2896638cb18c/src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.component.spec.ts#L30)):*
> ```XML
> import { SharedModule } from '../shared/shared.module';
> import { MyProjectsComponent } from './my-projects.component';
> import { TestRealtimeModule } from '../../xforge-common/test-realtime.module';
> ```

Nit: this can be an absolute path path



_Code quote:_
```XML
'../../xforge-common/test-realtime.module';
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.stories.ts` line 29 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O8DSbIlDnsbJZQFXejZ:-O8DSbIlDnsbJZQFXej_:b-55fq2a) ([raw file](https://github.com/sillsdev/web-xforge/blob/f581cb8141d3e5f0985fe6ab597e2896638cb18c/src/SIL.XForge.Scripture/ClientApp/src/app/my-projects/my-projects.stories.ts#L29)):*
> ```XML
> import { SharedModule } from '../shared/shared.module';
> import { MyProjectsComponent } from './my-projects.component';
> import { TestRealtimeModule } from '../../xforge-common/test-realtime.module';
> ```

Nit: this can be an absolute path.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts` line 38 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O8DV3cxBK27ybwrKXf9:-O8DV3cxBK27ybwrKXfA:b-gstuc2) ([raw file](https://github.com/sillsdev/web-xforge/blob/f581cb8141d3e5f0985fe6ab597e2896638cb18c/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts#L38)):*
> ```XML
> import { PreTranslationSignupUrlService } from './pretranslation-signup-url.service';
> import { TrainingDataService } from './training-data/training-data.service';
> import { TestRealtimeModule } from '../../../xforge-common/test-realtime.module';
> ```

Nit: This can be an absolute path.



_Code quote:_
```XML
'../../../xforge-common/test-realtime.module';
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/dialog.service.ts` line 59 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O8DVLFh2Bv_0TdxEVxS:-O8DVLFh2Bv_0TdxEVxT:b-q9t1qq) ([raw file](https://github.com/sillsdev/web-xforge/blob/f581cb8141d3e5f0985fe6ab597e2896638cb18c/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/dialog.service.ts#L59)):*
> ```XML
> 
>   closeDiagnosticOverlay(): void {
>     if (this.diagnosticOverlay) {
> ```

Nit: You could use optional chaining



_Code quote (i):_
```XML
 if (this.diagnosticOverlay) {
```



_Code snippet (ii):_
```XML
this.diagnosticOverlay?.dispose()
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/diagnostic-overlay/diagnostic-overlay.component.scss` line 12 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O7V6Ws2DbwYDxqkOD0C:-O8DUEAG0AtheaZzVGEh:b-b8g5ns) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f21b11898f6363037bafc272d170360d8faa998/src/SIL.XForge.Scripture/ClientApp/src/app/diagnostic-overlay/diagnostic-overlay.component.scss#L12)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

I was concerned with using % as it can get nested withing another element so rather than 25% of the screen width it's 25% of the outer element. When in doubt I use view width. That doesn't seem to be the case here so I've changed it to use `%`.
</blockquote></details>

On smaller screens or when I have dev tools open, the 25% is not large enough to see the whole tab. You will want to remove the width rule.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/diagnostic-overlay/diagnostic-overlay.component.scss` line 17 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O7V6carEGmv3gPnomyQ:-O8DTTwq2D60PkwLZee4:btyeq5o) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f21b11898f6363037bafc272d170360d8faa998/src/SIL.XForge.Scripture/ClientApp/src/app/diagnostic-overlay/diagnostic-overlay.component.scss#L17)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

Without setting the `background-color` the overlay is relatively transparent and displaying it over the editor/checking makes it difficult to read.
</blockquote></details>

Good thinking. Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.ts` line 2 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O8DUry4-9NKUh0A1Alh:-O8DUry4-9NKUh0A1Ali:bajk6v3) ([raw file](https://github.com/sillsdev/web-xforge/blob/f581cb8141d3e5f0985fe6ab597e2896638cb18c/src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.ts#L2)):*
> ```XML
> import { OverlayModule } from '@angular/cdk/overlay';
> import { KeyValuePipe } from '@angular/common';
> ```

Import the CommonModule instead which should include the KeyValuePipe.



_Code quote:_
```XML
import { KeyValuePipe } from '@angular/common';
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.ts` line 4 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O8DUkUHBUmRyDKNdW--:-O8DUkUHBUmRyDKNdW-0:b-wyp7ai) ([raw file](https://github.com/sillsdev/web-xforge/blob/f581cb8141d3e5f0985fe6ab597e2896638cb18c/src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.ts#L4)):*
> ```XML
> import { KeyValuePipe } from '@angular/common';
> import { Component } from '@angular/core';
> import { MatIcon } from '@angular/material/icon';
> ```

Import the `UICommonModule` instead of individual components.



_Code quote:_
```XML
import { MatIcon } from '@angular/material/icon';
```


<!-- Sent from Reviewable.io -->

2024-10-02 19:35 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2735)* status: all files reviewed, 11 unresolved discussions (waiting on @github-advanced-security[bot], @kylebuss, and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.html` line 22 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O8Dgdva97WhOCUjvfbX:-O8Dgdva97WhOCUjvfbY:b-tquwn0) ([raw file](https://github.com/sillsdev/web-xforge/blob/f581cb8141d3e5f0985fe6ab597e2896638cb18c/src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.html#L22)):*
> ```HTML
>         <tbody>
>           @for (docType of showDocCollections | keyvalue; track docType.key) {
>             @if (docType) {
> ```

I don't think this if statement is needed. If you're iterating a list of things, it's possible for the list to be empty, but not for one of the items in the list to not exist.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.ts` line 4 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O8DUkUHBUmRyDKNdW--:-O8DgEm07DCy397w6ujT:bq550j9) ([raw file](https://github.com/sillsdev/web-xforge/blob/f581cb8141d3e5f0985fe6ab597e2896638cb18c/src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.ts#L4)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Import the `UICommonModule` instead of individual components.
</blockquote></details>

This is actually something we need to discuss and decide how to handle. There are advantages to having every component import things directly, but we also have some global configuration in UICommonModule. Looking at what we've done already, it's a mix. For right now, I think we should import it so global config things get set.


<!-- Sent from Reviewable.io -->

2024-10-02 20:30 UTC, kylebuss reviewed
On `/scripts/db_tools/parse-version.ts` do I need to do more then add it to the `featureFlags` array? As this has been done.

I'm also not sure why adding `x-forge/...` imports to our .ts files from the vscode quickfix always adds the `../../` at the beginning.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-:-O8Ddeo648yYmxHVk_sQ:bv2k6by)* status: 20 of 30 files reviewed, 6 unresolved discussions (waiting on @github-advanced-security[bot], @Nateowami, and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.ts` line 2 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O8DUry4-9NKUh0A1Alh:-O8DfA-m6_Olywe7roMf:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/f581cb8141d3e5f0985fe6ab597e2896638cb18c/src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.ts#L2)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Import the CommonModule instead which should include the KeyValuePipe.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.ts` line 4 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O8DUkUHBUmRyDKNdW--:-O8DuwR01IqG3Dpa3k-S:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/f581cb8141d3e5f0985fe6ab597e2896638cb18c/src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.ts#L4)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This is actually something we need to discuss and decide how to handle. There are advantages to having every component import things directly, but we also have some global configuration in UICommonModule. Looking at what we've done already, it's a mix. For right now, I think we should import it so global config things get set.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-07 19:06 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2735)* status: 15 of 30 files reviewed, 5 unresolved discussions (waiting on @github-advanced-security[bot], @kylebuss, and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts` line 309 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O8cMsZJEd9jvIzQaIig:-O8cMsZJEd9jvIzQaIih:bng8zfc) ([raw file](https://github.com/sillsdev/web-xforge/blob/8346816b77a92a685771b0380686b5508cc1682c/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/feature-flags/feature-flag.service.ts#L309)):*
> ```XML
>   );
> 
>   readonly showDiagnosticOverlay: ObservableFeatureFlag = new FeatureFlagFromStorage(
> ```

Can you get rid of this feature flag? There's no reason we need a feature flag just to open/close an overlay.


<!-- Sent from Reviewable.io -->

2024-10-08 15:46 UTC, kylebuss reviewed
Turns out I was overthinking what needed to be done to show/hide the overlay after removing the feature flag. 

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-:-O8glDxK2f3hx93errL7:byeqdn0)* status: 14 of 30 files reviewed, 4 unresolved discussions (waiting on @github-advanced-security[bot] and @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2024-10-08 16:59 UTC, Nateowami requested changes
@kylebuss I unfortunately still have quite a lot of comments/requested changes. I don't know exactly what your process is, but when I look at the changes, I'm looking at the entire set of changes as a whole. My guess is that you're mostly seeing what you changed in each commit, and that might be causing you to miss some things that might become apparent if looking at the full change set. I think it would be useful to review the changes as a whole yourself in GitHub or Reviewable and make sure everything still makes sense.

My personal process for most branches is to just keep amending a single commit, instead of adding more commits. I find this works fairly well for me. I don't know whether that might be useful for you. It helps me always see the change as a single unit.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-:-O8h2GkA4maGDQNOcNA8:b-v4qlp5)* status: 14 of 30 files reviewed, 14 unresolved discussions (waiting on @github-advanced-security[bot], @kylebuss, and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 68 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O8h0Yg45hUngE4iQ_4A:-O8h0Yg45hUngE4iQ_4B:b-b76x0i) ([raw file](https://github.com/sillsdev/web-xforge/blob/b0ad051a504b5ca487560710f808471f8e6a6937/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L68)):*
> ```XML
>   private permissionsChangedSub?: Subscription;
>   private _isDrawerPermanent: boolean = true;
>   private showDiagnosticOverlay: boolean = false;
> ```

Is this property being used for anything?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts` line 98 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O8h1gB_BzDjVxRIOsHX:-O8h1gB_BzDjVxRIOsHY:bg1vrru) ([raw file](https://github.com/sillsdev/web-xforge/blob/b0ad051a504b5ca487560710f808471f8e6a6937/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts#L98)):*
> ```XML
>           TestOnlineStatusModule.forRoot(),
>           RouterModule.forRoot([]),
>           TestRealtimeModule.forRoot(SF_TYPE_REGISTRY),
> ```

This change is not needed. I think you can revert this entire file, and likely others. I reverted it locally, and the tests still passed. I don't think it's the only file that can be reverted though; it's just the only one I tested.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime.service.ts` line 49 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O8gyF7B4MLAtWHAhxJ9:-O8gyF7B4MLAtWHAhxJA:bhmdh48) ([raw file](https://github.com/sillsdev/web-xforge/blob/b0ad051a504b5ca487560710f808471f8e6a6937/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime.service.ts#L49)):*
> ```XML
>   }
> 
>   get docCollection(): { [key: string]: number } {
> ```

This name seems like a misnomer. Should it say docCountsByCollection?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.html` line 15 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O8gyR5A6PDKT1py507j:-O8gyR5A6PDKT1py507k:b-wzh34z) ([raw file](https://github.com/sillsdev/web-xforge/blob/b0ad051a504b5ca487560710f808471f8e6a6937/src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.html#L15)):*
> ```HTML
>     @if (isExpanded) {
>       <h1>Developer Diagnostics</h1>
>       <h3>Currently subscribed to {{ totalDocsCount }} documents</h3>
> ```

These aren't actually necessarily subscribed to (at least I don't think). We will probably need to add separate diagnostics for subscription counts. Can you change it to say "in memory" or "tracked by realtime service" or something of the sort?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.scss` line 34 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O8h-WQe8jkzcse65EBc:-O8h-WQe8jkzcse65EBd:b-m2dhfs) ([raw file](https://github.com/sillsdev/web-xforge/blob/b0ad051a504b5ca487560710f808471f8e6a6937/src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.scss#L34)):*
> ```SCSS
> }
> 
> .toggle-button {
> ```

There's a lot of repetitive CSS in this file, especially with the buttons. Can you clean it up a bit? (Actually, see the comment below before doing that, as it's related).
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.scss` line 41 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O8h0BWPE9cdcChLytyS:-O8h0BWQ7zVuJ_zBedfB:b-h8o6jm) ([raw file](https://github.com/sillsdev/web-xforge/blob/b0ad051a504b5ca487560710f808471f8e6a6937/src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.scss#L41)):*
> ```SCSS
>   border: none;
>   font-size: 16px;
>   cursor: pointer;
> ```

If you used a a mat-icon-button, as we do elsewhere, you wouldn't need to set `cursor: pointer`, or likely a number of other properties.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.ts` line 35 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O8gzFs15HrIWH5CXtkE:-O8gzFs15HrIWH5CXtkF:bv3js8i) ([raw file](https://github.com/sillsdev/web-xforge/blob/b0ad051a504b5ca487560710f808471f8e6a6937/src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.ts#L35)):*
> ```XML
>   }
> 
>   get showDocCollections(): { [key: string]: number } {
> ```

`showXYZ` sounds like a boolean indicating whether or not to show something. This should probably be called something like docCountsByCollection
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.ts` line 43 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O8gzTIv3fdGkHDZ_qXt:-O8gzTIv3fdGkHDZ_qXu:bd1g2wa) ([raw file](https://github.com/sillsdev/web-xforge/blob/b0ad051a504b5ca487560710f808471f8e6a6937/src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.ts#L43)):*
> ```XML
>   }
> 
>   onToggle(): void {
> ```

By convention, `onevent` is used to register an even handler. For example, `element.onclick = () => { ... }`. (Though in general you would instead use `element.addEventListener(...)`, since it doesn't risk overwriting another event handler, like `element.onclick` does).

A method that performs an action should have the name of that action, not onAction. So `toggle` would be a good name for this.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.ts` line 47 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O8h-JDh6CKr_M1CYHPo:-O8h-JDh6CKr_M1CYHPp:b-6nsrnj) ([raw file](https://github.com/sillsdev/web-xforge/blob/b0ad051a504b5ca487560710f808471f8e6a6937/src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.ts#L47)):*
> ```XML
>   }
> 
>   onClose(): void {
> ```

Same issue as above with naming.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.ts` line 48 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O8h-LY-3diBlRihvvp8:-O8h-LY-3diBlRihvvp9:blkfk70) ([raw file](https://github.com/sillsdev/web-xforge/blob/b0ad051a504b5ca487560710f808471f8e6a6937/src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.ts#L48)):*
> ```XML
> 
>   onClose(): void {
>     this.isOpen = !this.isOpen;
> ```

Shouldn't it just set `isOpen` to `false`? In the odd situation where this might be called when it's already closed, this would make the internal state invalid.


<!-- Sent from Reviewable.io -->

2024-10-09 14:05 UTC, kylebuss reviewed
@Nateowami, I think I have everything cleaned up. I will adjust my process to amend commits and do a full compare on my changes. Let me know if it looks like I missed something.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-:-O8l__jN3m72e2Agi6R6:b-9tsq1x)* status: 12 of 30 files reviewed, 13 unresolved discussions (waiting on @github-advanced-security[bot], @Nateowami, and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts` line 68 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O8h0Yg45hUngE4iQ_4A:-O8lGAVg4jxWvxN142Fm:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/b0ad051a504b5ca487560710f808471f8e6a6937/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L68)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Is this property being used for anything?
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime.service.ts` line 49 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O8gyF7B4MLAtWHAhxJ9:-O8hif392tZmor4dKVRL:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/b0ad051a504b5ca487560710f808471f8e6a6937/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/realtime.service.ts#L49)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This name seems like a misnomer. Should it say docCountsByCollection?
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts` line 98 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O8h1gB_BzDjVxRIOsHX:-O8l_NMx-fDL_s7U0EB_:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/b0ad051a504b5ca487560710f808471f8e6a6937/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation.component.spec.ts#L98)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This change is not needed. I think you can revert this entire file, and likely others. I reverted it locally, and the tests still passed. I don't think it's the only file that can be reverted though; it's just the only one I tested.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.scss` line 34 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O8h-WQe8jkzcse65EBc:-O8hgvgT5KW1NQVoMfUV:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/b0ad051a504b5ca487560710f808471f8e6a6937/src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.scss#L34)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

There's a lot of repetitive CSS in this file, especially with the buttons. Can you clean it up a bit? (Actually, see the comment below before doing that, as it's related).
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.scss` line 41 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O8h0BWPE9cdcChLytyS:-O8hgw3i1y12g3FUQi77:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/b0ad051a504b5ca487560710f808471f8e6a6937/src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.scss#L41)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

If you used a a mat-icon-button, as we do elsewhere, you wouldn't need to set `cursor: pointer`, or likely a number of other properties.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.ts` line 35 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O8gzFs15HrIWH5CXtkE:-O8l_LZu7bRfRbEnyEvK:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/b0ad051a504b5ca487560710f808471f8e6a6937/src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.ts#L35)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

`showXYZ` sounds like a boolean indicating whether or not to show something. This should probably be called something like docCountsByCollection
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.ts` line 43 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O8gzTIv3fdGkHDZ_qXt:-O8hiH4C55slpCtnV4kT:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/b0ad051a504b5ca487560710f808471f8e6a6937/src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.ts#L43)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

By convention, `onevent` is used to register an even handler. For example, `element.onclick = () => { ... }`. (Though in general you would instead use `element.addEventListener(...)`, since it doesn't risk overwriting another event handler, like `element.onclick` does).

A method that performs an action should have the name of that action, not onAction. So `toggle` would be a good name for this.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.ts` line 47 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O8h-JDh6CKr_M1CYHPo:-O8hiHMbCy8wxger8U-X:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/b0ad051a504b5ca487560710f808471f8e6a6937/src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.ts#L47)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Same issue as above with naming.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.ts` line 48 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O8h-LY-3diBlRihvvp8:-O8hiIPH0JVPvVGKDsMj:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/b0ad051a504b5ca487560710f808471f8e6a6937/src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.ts#L48)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Shouldn't it just set `isOpen` to `false`? In the odd situation where this might be called when it's already closed, this would make the internal state invalid.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-09 14:48 UTC, Nateowami requested changes
Good work; one last item.

> Reviewed 3 of 28 files at r2, 9 of 17 files at r4, 1 of 10 files at r5, 2 of 11 files at r6, 6 of 10 files at r7, 9 of 9 files at r8, all commit messages.
> Dismissed @RaymondLuong3 from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-:-O8lhxU_5XJNBP7DAOCp:b-twefpd)* status: all files reviewed, 3 unresolved discussions (waiting on @github-advanced-security[bot], @kylebuss, and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.ts` line 24 at r8](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O8ljRaJ1y8T1SnrysAw:-O8ljRaJ1y8T1SnrysAx:b-uui82r) ([raw file](https://github.com/sillsdev/web-xforge/blob/c22d1c764a645fbfafc5418eaa129b3934f89f9c/src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.ts#L24)):*
> ```XML
>   imports: [OverlayModule, CommonModule, UICommonModule]
> })
> export class DiagnosticOverlayComponent extends SubscriptionDisposable {
> ```

This does not need to extend SubscriptionDisposable.


<!-- Sent from Reviewable.io -->

2024-10-09 15:27 UTC, Nateowami approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

I have a followup where I'll remove the `extends SubscriptionDisposable`

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-:-O8lt5un0zkxlJc1vFMT:bsbvwgz)* status: all files reviewed, 3 unresolved discussions (waiting on @github-advanced-security[bot], @kylebuss, and @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2024-10-09 15:29 UTC, kylebuss reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2735)* status: all files reviewed, 3 unresolved discussions (waiting on @github-advanced-security[bot], @Nateowami, and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.ts` line 24 at r8](https://reviewable.io/reviews/sillsdev/web-xforge/2735#-O8ljRaJ1y8T1SnrysAw:-O8lshbgBWtTEXsnQ7hU:b-1z398h) ([raw file](https://github.com/sillsdev/web-xforge/blob/19196d06a19946ac8c29679091258cf4ff9f46d0/src/SIL.XForge.Scripture/ClientApp/src/app/shared/diagnostic-overlay/diagnostic-overlay.component.ts#L24)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This does not need to extend SubscriptionDisposable.
</blockquote></details>

:man_facepalming: 


<!-- Sent from Reviewable.io -->

2024-10-09 15:37 UTC, merged