SF-2998 Revert Biblical Terms migration
sillsdev/web-xforge pull request #2740
Opened 2024-09-24 22:43 UTC by pmachapman

A bug was discovered on QA when a user had Biblical Terms enabled for their project and visible, the following error displays if the user has not yet updated SF to the latest version.

This PR fixes this by removing the migration, and restoring the `biblicalTermsEnabled` property in `SFProjectUserConfig` and making it nullable.

The downside of this PR is that users who previously had the Biblical Terms panel open will no longer have it open when the update their Scripture Forge PWA.

**Error**

![image](https://github.com/user-attachments/assets/8121869e-4ae5-4666-9925-d8ea85fc98bc)

2024-09-25 04:15 UTC, nigel-wells requested changes
Just one query Peter. 
Just to confirm, this issue only relates to testers on QA and it hasn't made its way onto live yet?

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2740#-:-O7bO-3qAkBAnS-5N_Um:byukt9p)* status: all files reviewed, 1 unresolved discussion (waiting on @pmachapman)

___
*[`src/RealtimeServer/scriptureforge/services/sf-project-user-config-service.ts` line 53 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2740#-O7bNm5DDMah2POjvaVc:-O7bNm5DDMah2POjvaVd:bhewv0b) ([raw file](https://github.com/sillsdev/web-xforge/blob/6b3e4cc02df0e0181dd2ae6488ff2e7c67ec441c/src/RealtimeServer/scriptureforge/services/sf-project-user-config-service.ts#L53)):*
> ```XML
>       },
>       biblicalTermsEnabled: {
>         bsonType: 'bool'
> ```

Should this be `['null', 'bool']`?


<!-- Sent from Reviewable.io -->

2024-09-25 06:40 UTC, josephmyers commented
@pmachapman had mentioned to me a front-end migration, instead of just removing the back-end one, where we auto open the BT tab. I think this would be better than having the panel gone with the previous method of opening it gone and the user confused as to if BT has totally disappeared. We would do that in this PR, right?

2024-09-25 19:23 UTC, pmachapman reviewed
> Just to confirm, this issue only relates to testers on QA and it hasn't made its way onto live yet?

Correct. This has not been deployed to live yet, or we would be swamped with errors.

> [@pmachapman](https://github.com/pmachapman) had mentioned to me a front-end migration, instead of just removing the back-end one, where we auto open the BT tab. I think this would be better than having the panel gone with the previous method of opening it gone and the user confused as to if BT has totally disappeared. We would do that in this PR, right?

Yes. I am going to investigate, and discuss with @Nateowami options regarding this.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2740#-:-O7ec0SB81BCwwvNA0-4:bs0f472)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[`src/RealtimeServer/scriptureforge/services/sf-project-user-config-service.ts` line 53 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2740#-O7bNm5DDMah2POjvaVc:-O7ecFpK6LCSH1Z45Ygx:b-2vub79) ([raw file](https://github.com/sillsdev/web-xforge/blob/6b3e4cc02df0e0181dd2ae6488ff2e7c67ec441c/src/RealtimeServer/scriptureforge/services/sf-project-user-config-service.ts#L53)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Should this be `['null', 'bool']`?
</blockquote></details>

No, because it will be omitted, not stored as null if the field is set to null.


<!-- Sent from Reviewable.io -->

2024-09-25 21:24 UTC, pmachapman reviewed
> [@pmachapman](https://github.com/pmachapman) had mentioned to me a front-end migration, instead of just removing the back-end one, where we auto open the BT tab. I think this would be better than having the panel gone with the previous method of opening it gone and the user confused as to if BT has totally disappeared. We would do that in this PR, right?

@josephmyers @Nateowami @nigel-wells I have added code to the editor to display the biblical terms tab, if the user had it enabled previously, and then "migrate" that old setting by unsetting it.

I am really open to feedback on how I did this. Another possible way would to be always add a Biblical Terms tab if it is enabled for the project, but that might get annoying if you don't want it to be auto-added.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2740#-:-O7f35Rr2n72WIgjWPgJ:bonfe1j)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @nigel-wells)



<!-- Sent from Reviewable.io -->

2024-09-29 20:36 UTC, Nateowami approved these changes

2024-09-29 22:05 UTC, nigel-wells approved these changes
This works but it does mean we will have this code sitting in the repo forever? Is there a script we can run to keep an eye on who is in this boat based on the config of the project and users?

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2740#-:-O7zo0VP8jYREJKsNANh:b-q1y6pj)* status: all files reviewed, 2 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts` line 3951 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2740#-O7znt1-9KLxQHGLCbob:-O7znt1045YJr-5WJ8cm:bto8ipf) ([raw file](https://github.com/sillsdev/web-xforge/blob/9a3edb5f7a42555c2b911cd475df6726d9ea4241/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L3951)):*
> ```XML
>         env.wait();
> 
>         const tabGroup = env.component.tabState.getTabGroup('source');
> ```

nit  rename to `sourceTabGroup` for consistency
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts` line 3994 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2740#-O7znm2sDs5xXkwXMi0p:-O7znm2sDs5xXkwXMi0q:b-1soumq) ([raw file](https://github.com/sillsdev/web-xforge/blob/9a3edb5f7a42555c2b911cd475df6726d9ea4241/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L3994)):*
> ```XML
>       }));
> 
>       it('should not add the biblical terms tab when if the user had biblical terms disabled', fakeAsync(() => {
> ```

nit  remove "when"


<!-- Sent from Reviewable.io -->

2024-09-29 22:18 UTC, pmachapman reviewed
I think we could remove this code when we remove the `BiblicalTermsEnabled` property I marked with the `[Obsolete]` attribute. I'm not sure what our policy is for the period of time before removing obsolete attributes, but I imagine it may be after a year or so?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2740#-:-O7zqSTAA0e2jZBNeTWy:be3or88)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts` line 3951 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2740#-O7znt1-9KLxQHGLCbob:-O7zqvyVCtul91GuSiSH:boyexb3) ([raw file](https://github.com/sillsdev/web-xforge/blob/9a3edb5f7a42555c2b911cd475df6726d9ea4241/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L3951)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

nit  rename to `sourceTabGroup` for consistency
</blockquote></details>

Done. Thanks!
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts` line 3994 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2740#-O7znm2sDs5xXkwXMi0p:-O7zqxgpBv4pSZCgCrJL:b-ioxi27) ([raw file](https://github.com/sillsdev/web-xforge/blob/9a3edb5f7a42555c2b911cd475df6726d9ea4241/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.spec.ts#L3994)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

nit  remove "when"
</blockquote></details>

Done. Thank you!


<!-- Sent from Reviewable.io -->

2024-09-29 22:24 UTC, nigel-wells approved these changes
I'm not sure if we have a policy - they probably just remain until someone asks the question :)

We can discuss that later. Merge it in.

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2740#-:-O7zsRTkB2H-n75wpj2c:b-91ghzb)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)



<!-- Sent from Reviewable.io -->

2024-09-29 22:39 UTC, merged