SF-2911 Support syncing notes when user has changed PT username
sillsdev/web-xforge pull request #2747
Opened 2024-09-26 18:31 UTC by RaymondLuong3

This PR updates our current Paratext users records for a project prior to attempting to synchronize the notes. It was important to retain the records of users that have had their Paratext name changed, but the SF user ID would be removed from old records and moved to the new record for a Paratext user.

We do not expect too many users to need to update their usernames, but this allows it to happen and for a sync to continue to work. It would be critical to ensure that old notes created by the user before changing their name continues to work.

2024-09-26 20:14 UTC, kylebuss requested changes
Thank you for taking a look at this.  I think it will be good for us to meet with Peter and discuss this further. My main concern is the potential for data loss if the user does not sync before creating new notes after changing their username.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2747#-:-O7jjj-m1_LKJfE7DMPh:bu7opsy)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @github-advanced-security[bot] and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 2009 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2747#-O7jxG2M0cfim0B6jiRL:-O7jxG2M0cfim0B6jiRM:b-otx5fc) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f04c549d90f512461980c373be13a080bae4653/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L2009)):*
> ```Smalltalk
>                         SFUserId = string.Empty
>                     };
>                 }
> ```

One scenario I considered was if the user changes their username back to what it was previously. This will only update the `SFUserId` in the database if the username is changed to something new and not a previously used username.

Steps:
  a) Change username in Paratext Registry
  b) Logout and Login to SF.
  c) Sync with Paratext.
  d) Observer SFUserId in database is showing on new username.
  e) Repeat a) - c) changing username back to the old username.
Note the SFUserId in the database is still showing for the new username and not the old username. 



_Code quote:_
```Smalltalk
                if (
                    !string.IsNullOrEmpty(paratextUser.Id)
                    && paratextUsers.Values.Any(u => u.SFUserId == paratextUser.Id)
                )
                {
                    // If the user is already in the project but with a different username, update the username
                    ParatextUserProfile oldPtUser = paratextUsers.Values.Single(u => u.SFUserId == paratextUser.Id);
                    paratextUsers[oldPtUser.Username] = new ParatextUserProfile
                    {
                        Username = oldPtUser.Username,
                        OpaqueUserId = oldPtUser.OpaqueUserId,
                        SFUserId = string.Empty
                    };
                }
```
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs` line 3709 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2747#-O7jv0i4-6whimSu8H2y:-O7jv0i4-6whimSu8H2z:b8jdwdj) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f04c549d90f512461980c373be13a080bae4653/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L3709)):*
> ```Smalltalk
>         );
> 
>         CommentThread thread1 = env.ProjectCommentManager.FindThread("thread1");
> ```

I am still seeing the issue of notes getting deleted on sync when I manually test. I am wondering if the way we set these tests up is behaving differently than how the app is actually working. Here are the steps to reproduce the note deletion on sync:

  a) Change username in Paratext Registry.
  b) Logout and Login to SF.
  c) Add a new note.
  d) Sync with Paratext.
Note added in c) has been deleted.



_Code quote:_
```Smalltalk
env.ProjectCommentManager.FindThread("thread1");
```


<!-- Sent from Reviewable.io -->

2024-09-26 22:16 UTC, RaymondLuong3 commented
I have been trying to reproduce the note being deleted after the Paratext name is changed. I do not see that happening. Maybe I am missing a step. Let's pair tomorrow and try to get to the bottom of it.

2024-10-01 19:28 UTC, pmachapman requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2747)* status: all files reviewed, 5 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 2007 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2747#-O88XR6v4bN2bibCG91_:-O88XR6v4bN2bibCG91a:bx5du7p) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f04c549d90f512461980c373be13a080bae4653/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L2007)):*
> ```Smalltalk
>                         Username = oldPtUser.Username,
>                         OpaqueUserId = oldPtUser.OpaqueUserId,
>                         SFUserId = string.Empty
> ```

Why do you set this value to an empty string? Is this to stop it triggering the code in the `else` block below this block?

If it is deliberate, please add a comment on your rationale, etc.

Also, after a name change, was a new `paratextUsers` entry supposed to be created?

If this was expected, is the comment above about "update the username" accurate? If anything the code appeared to clear the `sfUserId` field.

![image.png](https://files.reviewableusercontent.io/images/reviewable/8665431/MR14LF-bE4H_LWkiHEzADh__/image.png)



_Code quote:_
```Smalltalk
SFUserId = string.Empty
```


<!-- Sent from Reviewable.io -->

2024-10-01 21:06 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2747)* status: all files reviewed, 5 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 2007 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2747#-O88XR6v4bN2bibCG91_:-O88r6Bx50UOxY312ya2:b-dstkm0) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f04c549d90f512461980c373be13a080bae4653/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L2007)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Why do you set this value to an empty string? Is this to stop it triggering the code in the `else` block below this block?

If it is deliberate, please add a comment on your rationale, etc.

Also, after a name change, was a new `paratextUsers` entry supposed to be created?

If this was expected, is the comment above about "update the username" accurate? If anything the code appeared to clear the `sfUserId` field.

![image.png](https://files.reviewableusercontent.io/images/reviewable/8665431/MR14LF-bE4H_LWkiHEzADh__/image.png)
</blockquote></details>

Thanks for pointing that out. I meant that we need to update the `paratextUsers` to have the `SFUserId` removed and a new record added and the `SFUserId` added to that user. The comment did not have enough information.

Setting it to the empty string was the suggestion from the Jira task. It is possible it would be better to set it to null. I will need to investigate.


<!-- Sent from Reviewable.io -->

2024-10-01 21:21 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2747)* status: all files reviewed, 5 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 2007 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2747#-O88XR6v4bN2bibCG91_:-O88v8AaAmfmzhPsWDcq:bs9as5j) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f04c549d90f512461980c373be13a080bae4653/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L2007)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Thanks for pointing that out. I meant that we need to update the `paratextUsers` to have the `SFUserId` removed and a new record added and the `SFUserId` added to that user. The comment did not have enough information.

Setting it to the empty string was the suggestion from the Jira task. It is possible it would be better to set it to null. I will need to investigate.
</blockquote></details>

I see that `ParatextProjectUser` is initialized to the empty string. I don't see a strong argument to set it to null or the empty string is better. It is important to note that this change will have the effect that all `ParatextUserProfile` records on a project will have their `SFUserId` updated to the empty string.


<!-- Sent from Reviewable.io -->

2024-10-02 18:17 UTC, pmachapman requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2747)* status: all files reviewed, 7 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 2007 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2747#-O88XR6v4bN2bibCG91_:-O8DRO5C6BwymOdxs3gb:bkpvxv9) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f04c549d90f512461980c373be13a080bae4653/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L2007)):*
> I don't see a strong argument to set it to null or the empty string is better. It is important to note that this change will have the effect that all `ParatextUserProfile` records on a project will have their `SFUserId` updated to the empty string.

I don't follow? My main reason for raising empty string vs null is the logic in the block below:
```cs
              // If we do not have the SF user Id set, set the SF user Id to be stored when CompleteSync() is called.
              // We create a new object to so that the logic in projectDoc.SubmitJson0OpAsync() will see the change.
              if (profile.SFUserId is null)
              {
                  paratextUsers[paratextUser.Username] = new ParatextUserProfile
                  {
                      Username = profile.Username,
                      SFUserId = paratextUser.Id,
                      OpaqueUserId = profile.OpaqueUserId,
                  };
              }
```
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs` line 3700 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2747#-O8DQXpG4FE375DsSnLS:-O8DQXpG4FE375DsSnLT:b-uz62v) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f04c549d90f512461980c373be13a080bae4653/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L3700)):*
> ```Smalltalk
>         };
> 
>         var syncMetricInfo = await env.Service.UpdateParatextCommentsAsync(
> ```

The test should assert that `syncMetricInfo.Added` is 2.



_Code quote:_
```Smalltalk
var syncMetricInfo = await
```
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs` line 3716 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2747#-O8DOY-G0o8KIClceb80:-O8DOY-G0o8KIClceb81:bi4cw11) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f04c549d90f512461980c373be13a080bae4653/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L3716)):*
> ```Smalltalk
>         Assert.That(comment2.User, Is.EqualTo(env.Username01));
>         var comment3 = thread1.Comments[2];
>         Assert.That(comment2.User, Is.EqualTo(env.Username01));
> ```

Should this be:
```
Assert.That(comment3.User, Is.EqualTo(env.Username01));
```



_Code quote:_
```Smalltalk
Assert.That(comment2.User, Is.EqualTo(env.Username01));
```


<!-- Sent from Reviewable.io -->

2024-10-03 18:28 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2747)* status: 0 of 5 files reviewed, 8 unresolved discussions (waiting on @github-advanced-security[bot], @kylebuss, and @pmachapman)

___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 2007 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2747#-O88XR6v4bN2bibCG91_:-O8IbJgm5GFI5qB3JLIf:b6501hs) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f04c549d90f512461980c373be13a080bae4653/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L2007)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

> I don't see a strong argument to set it to null or the empty string is better. It is important to note that this change will have the effect that all `ParatextUserProfile` records on a project will have their `SFUserId` updated to the empty string.

I don't follow? My main reason for raising empty string vs null is the logic in the block below:
```cs
              // If we do not have the SF user Id set, set the SF user Id to be stored when CompleteSync() is called.
              // We create a new object to so that the logic in projectDoc.SubmitJson0OpAsync() will see the change.
              if (profile.SFUserId is null)
              {
                  paratextUsers[paratextUser.Username] = new ParatextUserProfile
                  {
                      Username = profile.Username,
                      SFUserId = paratextUser.Id,
                      OpaqueUserId = profile.OpaqueUserId,
                  };
              }
```
</blockquote></details>

OK, I see what you mean now. It turns out the using the empty string had unintended side effects on the front-end. The logic has been updated to do the opposite now. The newer `ParatextUserProfile` will have its `SFUserId` set to `null` until the project is saved. The old "ParatextUserProfile` will be used instead, since that user has permission to write to the PT repository based on the permissions from the repository.
___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 2009 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2747#-O7jxG2M0cfim0B6jiRL:-O8IcFZtAXLqt7C0Ww0c:b7km1gz) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f04c549d90f512461980c373be13a080bae4653/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L2009)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

One scenario I considered was if the user changes their username back to what it was previously. This will only update the `SFUserId` in the database if the username is changed to something new and not a previously used username.

Steps:
  a) Change username in Paratext Registry
  b) Logout and Login to SF.
  c) Sync with Paratext.
  d) Observer SFUserId in database is showing on new username.
  e) Repeat a) - c) changing username back to the old username.
Note the SFUserId in the database is still showing for the new username and not the old username.
</blockquote></details>

That is a case we will want to handle. I've updated the logic to handle the case where the `ParatextUserProfile` exists for a given username.
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs` line 3700 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2747#-O8DQXpG4FE375DsSnLS:-O8IcmEh73rvc2hMkfyU:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f04c549d90f512461980c373be13a080bae4653/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L3700)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

The test should assert that `syncMetricInfo.Added` is 2.
</blockquote></details>

Done.
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs` line 3709 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2747#-O7jv0i4-6whimSu8H2y:-O8IcYIC5ZLu4wxxqSj1:b-2d5hqu) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f04c549d90f512461980c373be13a080bae4653/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L3709)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

I am still seeing the issue of notes getting deleted on sync when I manually test. I am wondering if the way we set these tests up is behaving differently than how the app is actually working. Here are the steps to reproduce the note deletion on sync:

  a) Change username in Paratext Registry.
  b) Logout and Login to SF.
  c) Add a new note.
  d) Sync with Paratext.
Note added in c) has been deleted.
</blockquote></details>

I believe I have fixed this issue by asserting the old user as the sync user. The old user will have permission to write to the repository based on permissions from the repository.
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs` line 3716 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2747#-O8DOY-G0o8KIClceb80:-O8Icj6756ZBXaw9H2qL:b-u4hxai) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f04c549d90f512461980c373be13a080bae4653/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L3716)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Should this be:
```
Assert.That(comment3.User, Is.EqualTo(env.Username01));
```
</blockquote></details>

Good catch. Not longer relevant.


<!-- Sent from Reviewable.io -->

2024-10-03 21:06 UTC, kylebuss requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2747)* status: 0 of 5 files reviewed, 7 unresolved discussions (waiting on @github-advanced-security[bot], @pmachapman, and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 2009 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2747#-O7jxG2M0cfim0B6jiRL:-O8JBrzn8qNgS11XbrVc:bifwc9g) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f04c549d90f512461980c373be13a080bae4653/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L2009)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

That is a case we will want to handle. I've updated the logic to handle the case where the `ParatextUserProfile` exists for a given username.
</blockquote></details>

I am not seeing the db updating the `sfUserId` back to the old name change.
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs` line 3709 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2747#-O7jv0i4-6whimSu8H2y:-O8JAMuI3pTB7zGHQuqf:b-yax22b) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f04c549d90f512461980c373be13a080bae4653/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L3709)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I believe I have fixed this issue by asserting the old user as the sync user. The old user will have permission to write to the repository based on permissions from the repository.
</blockquote></details>

Looks like the sync is working and the note does not get deleted. In PT the note does still show the old username but I'm okay with that.


<!-- Sent from Reviewable.io -->

2024-10-04 19:41 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2747)* status: 0 of 5 files reviewed, 7 unresolved discussions (waiting on @github-advanced-security[bot], @kylebuss, and @pmachapman)

___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 2009 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2747#-O7jxG2M0cfim0B6jiRL:-O8O1yjOD3Lvyx4SAJ0b:bm6b22b) ([raw file](https://github.com/sillsdev/web-xforge/blob/5f04c549d90f512461980c373be13a080bae4653/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L2009)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

I am not seeing the db updating the `sfUserId` back to the old name change.
</blockquote></details>

Ah yes, I was trying to take a shortcut and not write a test which would have caught this. I've added a test and fixed it.


<!-- Sent from Reviewable.io -->

2024-10-07 13:30 UTC, kylebuss requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2747)* status: 0 of 5 files reviewed, 7 unresolved discussions (waiting on @github-advanced-security[bot], @pmachapman, and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 2051 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2747#-O8b8ggT3l4RBtgbakXh:-O8b8ggT3l4RBtgbakXi:b-f6285c) ([raw file](https://github.com/sillsdev/web-xforge/blob/a98972e8fb4ad03ebe7dba2843a507f38d7bbe7c/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L2051)):*
> ```Smalltalk
>                 if (oldPtUser is not null)
>                 {
>                     userProfileToAdd.SFUserId = null;
> ```

Should this be `activePtUsers[oldPtUser.Username].SFUserId`? Currently this appears to be undoing the above else statement and not updating the `SFUserId` in the database.



_Code quote:_
```Smalltalk
userProfileToAdd.SFUserId
```


<!-- Sent from Reviewable.io -->

2024-10-07 20:20 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2747)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @github-advanced-security[bot], @kylebuss, and @pmachapman)

___
*[`src/SIL.XForge/Models/UserSecret.cs` line 13 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2747#-O8cTKUb9F_o5JojsfOA:-O8cbjJy46TTw2_dgNaU:b-bll9gx) ([raw file](https://github.com/sillsdev/web-xforge/blob/a98972e8fb4ad03ebe7dba2843a507f38d7bbe7c/src/SIL.XForge/Models/UserSecret.cs#L13)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Dictionaries are not thread safe, so there may be weird/random bugs using one in a static field, and potentially additional problems because it is not readonly.

Instead of a static, is it possible to have this dictionary as a non-static readonly field in ParatextService? As ParatextService is singleton, it will provide similar functionality to a static?
</blockquote></details>

Yes, that would have been my second solution. I was trying to keep `ParatextService` as stateless as possible, so I thought that passing the state to `UserSecret` was a better solution. But I see that `ParatextService` already has some members that retain state throughout a sync, so it makes sense to add it in `ParatextService`. 
It always gives me an uncertain feeling adding dependencies to our services having a state, but a singleton seems to have many members set at initialization.


<!-- Sent from Reviewable.io -->

2024-10-07 20:59 UTC, kylebuss requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2747)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @github-advanced-security[bot], @pmachapman, and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 1859 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2747#-O8cieXB8lk_gXaWuc_i:-O8cieXB8lk_gXaWuc_j:b-sqziki) ([raw file](https://github.com/sillsdev/web-xforge/blob/a98972e8fb4ad03ebe7dba2843a507f38d7bbe7c/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L1859)):*
> ```Smalltalk
>                         string? userId = _paratextUsers
>                             .SingleOrDefault(u => u.Username == activePtSyncUser.Username)
>                             ?.Id;
> ```

We need a way to get the `oldPtUser.SFUserId` here. Currently this is returning null so the set operation never executes to update the user in the database.



_Code quote:_
```Smalltalk
                        string? userId = _paratextUsers
                            .SingleOrDefault(u => u.Username == activePtSyncUser.Username)
                            ?.Id;
```
___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 2051 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2747#-O8b8ggT3l4RBtgbakXh:-O8cadGe7Yvw6fydknjg:bwj4d05) ([raw file](https://github.com/sillsdev/web-xforge/blob/a98972e8fb4ad03ebe7dba2843a507f38d7bbe7c/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L2051)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This can be relatively confusing, so I added the comment above. This is looking to see if the user we are attempting to add to `availablePtUsers` already has an entry in `availablePtUser` that has the same `sfUserId`. If so, we don't want 2 entries with the same `sfUserId`, so we strip the `SFUserId` from `userProfileToAdd` and pretend that the other user is the one acting on behalf of the new users.
When we update the `project.ParatextUsers` at the end of the sync, that is when we switch the `SFUserId` from the old to the new users.
Does that make sense?
</blockquote></details>

My bad. Yes, this makes sense. Please see comments above when sync completes.


<!-- Sent from Reviewable.io -->

2024-10-08 17:00 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2747)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @github-advanced-security[bot], @kylebuss, and @pmachapman)

___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 1859 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2747#-O8cieXB8lk_gXaWuc_i:-O8h28YpBdPfp62-oZF_:b-gzb8vs) ([raw file](https://github.com/sillsdev/web-xforge/blob/a98972e8fb4ad03ebe7dba2843a507f38d7bbe7c/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L1859)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

We need a way to get the `oldPtUser.SFUserId` here. Currently this is returning null so the set operation never executes to update the user in the database.
</blockquote></details>

What do you mean? In this branch, we take what is saved in `project.ParatextUsers` and try to add the `SFUserId` to it if we find one. If a user joined Scripture Forge recently, then we can set the`SFUserId` which we would get from `_paratextUser`.
It is OK if we get `null` from `_paratextUsers` because all that means is no user in SF is associated with a PT Username. Let me know if you want to chat about it.


<!-- Sent from Reviewable.io -->

2024-10-09 01:26 UTC, pmachapman reviewed
> Reviewed 1 of 2 files at r4, 5 of 5 files at r5, all commit messages.
> Dismissed @github-advanced-security[bot] from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2747)* status: all files reviewed, 2 unresolved discussions (waiting on @kylebuss and @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2024-10-09 11:35 UTC, kylebuss approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2747)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 1859 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2747#-O8cieXB8lk_gXaWuc_i:-O8l1Ow9CwSUYPssT0O5:b-mnyan7) ([raw file](https://github.com/sillsdev/web-xforge/blob/a98972e8fb4ad03ebe7dba2843a507f38d7bbe7c/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L1859)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

What do you mean? In this branch, we take what is saved in `project.ParatextUsers` and try to add the `SFUserId` to it if we find one. If a user joined Scripture Forge recently, then we can set the`SFUserId` which we would get from `_paratextUser`.
It is OK if we get `null` from `_paratextUsers` because all that means is no user in SF is associated with a PT Username. Let me know if you want to chat about it.
</blockquote></details>

Not sure what was going on but while discussing with Raymond I was unable to reproduce the issue of the SFUserId not being reassigned back to the old user. I am good with this change. @pmachapman, if you would like to double check this locally here are the steps:

1) Login to a project with a translator user and confirm project syncs.
2) Log out.
3) In Paratext Registry, change the translators username.
4) Repeat Step 1.
5) Verify in database the SFUserId is now showing for the new user name.
6) Repeat steps 2-5, changing the username back to what it originally was and verify database has SFUserId for original username.


<!-- Sent from Reviewable.io -->

2024-10-09 18:51 UTC, pmachapman approved these changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2747)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 1859 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2747#-O8cieXB8lk_gXaWuc_i:-O8mba1Z8b77p7uGWvDb:b2bwi2c) ([raw file](https://github.com/sillsdev/web-xforge/blob/a98972e8fb4ad03ebe7dba2843a507f38d7bbe7c/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L1859)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

Not sure what was going on but while discussing with Raymond I was unable to reproduce the issue of the SFUserId not being reassigned back to the old user. I am good with this change. @pmachapman, if you would like to double check this locally here are the steps:

1) Login to a project with a translator user and confirm project syncs.
2) Log out.
3) In Paratext Registry, change the translators username.
4) Repeat Step 1.
5) Verify in database the SFUserId is now showing for the new user name.
6) Repeat steps 2-5, changing the username back to what it originally was and verify database has SFUserId for original username.
</blockquote></details>

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> This code worked great for me. After rename, two users mapped to the same SF user, the old and new user. Only the new had the sfUserId set:

![image.png](https://files.reviewableusercontent.io/images/reviewable/8665431/fQaHp40NBvsP4ZcEQ3Cw4OuT/image.png)


<!-- Sent from Reviewable.io -->

2024-10-09 19:15 UTC, kylebuss approved these changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2747)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 1859 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2747#-O8cieXB8lk_gXaWuc_i:-O8mgn7FE48cwoMLWUsN:b-h3b5wv) ([raw file](https://github.com/sillsdev/web-xforge/blob/a98972e8fb4ad03ebe7dba2843a507f38d7bbe7c/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L1859)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> This code worked great for me. After rename, two users mapped to the same SF user, the old and new user. Only the new had the sfUserId set:

![image.png](https://files.reviewableusercontent.io/images/reviewable/8665431/fQaHp40NBvsP4ZcEQ3Cw4OuT/image.png)
</blockquote></details>

Did you by chance check if you change the name back to the "old" name that db shows the sfUserId on the old user?


<!-- Sent from Reviewable.io -->

2024-10-09 19:27 UTC, pmachapman approved these changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2747)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 1859 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2747#-O8cieXB8lk_gXaWuc_i:-O8mk-hk9RvkALGpIlkc:bhl2f2k) ([raw file](https://github.com/sillsdev/web-xforge/blob/a98972e8fb4ad03ebe7dba2843a507f38d7bbe7c/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L1859)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

Did you by chance check if you change the name back to the "old" name that db shows the sfUserId on the old user?
</blockquote></details>

It reverted correctly for me:
![image.png](https://files.reviewableusercontent.io/images/reviewable/8665431/t1nw_PNt1Has50QumMspENrL/image.png)


<!-- Sent from Reviewable.io -->

2024-10-09 19:30 UTC, kylebuss approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2747#-:-O8mkeqW2bx-VDBX279-:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs` line 1859 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2747#-O8cieXB8lk_gXaWuc_i:-O8mkZOx7bro0HcCR2Tu:b-62gsma) ([raw file](https://github.com/sillsdev/web-xforge/blob/a98972e8fb4ad03ebe7dba2843a507f38d7bbe7c/src/SIL.XForge.Scripture/Services/ParatextSyncRunner.cs#L1859)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

It reverted correctly for me:
![image.png](https://files.reviewableusercontent.io/images/reviewable/8665431/t1nw_PNt1Has50QumMspENrL/image.png)
</blockquote></details>

Awesome, thanks! :thumbsup: 


<!-- Sent from Reviewable.io -->

2024-10-16 16:02 UTC, merged