SF-2972 Improve drafting bulk-book selection UI
sillsdev/web-xforge pull request #2748
Opened 2024-09-26 21:26 UTC by kylebuss

Improves the visualization and functionality of the bulk-book selection when the user is setting up a new draft. Using an indeterminant checkbox allows the user to see if None/Some/All of the Old Testament, New Testament, or Deuterocanon books have been selected. The checkbox will change from None/Some to All or from All to None. When selecting individual books the checkbox will show an indeterminant state.

2024-09-27 15:10 UTC, Nateowami requested changes
Good work. This seems to behave correctly.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2748#-:-O7nufXgEntZURLmWdyi:b-eip0a9)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @kylebuss)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.ts` line 101 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2748#-O7nuv2D7FGOPn3fvt9V:-O7nuv2D7FGOPn3fvt9W:bup6oa8) ([raw file](https://github.com/sillsdev/web-xforge/blob/b89c6a0e1556521b107df2dcca0889cd8dc1fd14/src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.ts#L101)):*
> ```XML
>   }
> 
>   async select(eventValue: string): Promise<void> {
> ```

Instead of having 6 separate values that can be passed, how about having two arguments: one for the scope, and one to indicate whether it should be selected?

For example:
``` ts
// define a type Scope before the start of the class
type Scope = 'OT' | 'NT' | 'DC';

  isBookInScope(bookNum: number, scope: Scope): boolean {
    if (scope === 'OT') return Canon.isBookOT(bookNum);
    else if (scope === 'NT') return Canon.isBookNT(bookNum);
    else if (scope === 'DC') return Canon.isBookDC(bookNum);
    throw new Error('Invalid scope');
  }

  async select(scope: Scope, value: boolean): Promise<void> {
    if (value) {
      this.selectedBooks.push(
        ...this.availableBooks.filter(n => this.isBookInScope(n, scope) && this.selectedBooks.includes(n))
      );
    } else {
      this.selectedBooks = this.selectedBooks.filter(n => !this.isBookInScope(n, scope));
    }

    await this.initBookOptions();
    this.bookSelect.emit(this.selectedBooks);
  }
```


<!-- Sent from Reviewable.io -->

2024-09-30 14:16 UTC, kylebuss reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2748)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.html` line 9 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2748#-O7o1PZi3iIbmhY76WTf:-O82AODd3414RGVomzqv:b12kz11) ([raw file](https://github.com/sillsdev/web-xforge/blob/b89c6a0e1556521b107df2dcca0889cd8dc1fd14/src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.html#L9)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

This is creating an event binding. See https://angular.dev/guide/templates/two-way-binding for an explanation of the syntax.
</blockquote></details>

Please correct me if I'm wrong: Reading through the explanation leads me to believe that event binding is not necessary here. So `[(indeterminate)]` should instead be `[indeterminate]` as it is not a part of the book-multi-select model.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.ts` line 101 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2748#-O7nuv2D7FGOPn3fvt9V:-O82HBqb3Tcz7J-gPso4:b-rlob0q) ([raw file](https://github.com/sillsdev/web-xforge/blob/b89c6a0e1556521b107df2dcca0889cd8dc1fd14/src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.ts#L101)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Instead of having 6 separate values that can be passed, how about having two arguments: one for the scope, and one to indicate whether it should be selected?

For example:
``` ts
// define a type Scope before the start of the class
type Scope = 'OT' | 'NT' | 'DC';

  isBookInScope(bookNum: number, scope: Scope): boolean {
    if (scope === 'OT') return Canon.isBookOT(bookNum);
    else if (scope === 'NT') return Canon.isBookNT(bookNum);
    else if (scope === 'DC') return Canon.isBookDC(bookNum);
    throw new Error('Invalid scope');
  }

  async select(scope: Scope, value: boolean): Promise<void> {
    if (value) {
      this.selectedBooks.push(
        ...this.availableBooks.filter(n => this.isBookInScope(n, scope) && this.selectedBooks.includes(n))
      );
    } else {
      this.selectedBooks = this.selectedBooks.filter(n => !this.isBookInScope(n, scope));
    }

    await this.initBookOptions();
    this.bookSelect.emit(this.selectedBooks);
  }
```
</blockquote></details>

I like this!


<!-- Sent from Reviewable.io -->

2024-09-30 15:59 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2748)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @kylebuss)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.html` line 9 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2748#-O7o1PZi3iIbmhY76WTf:-O82e2-w5t0TFgqEpfhR:bp8eu3) ([raw file](https://github.com/sillsdev/web-xforge/blob/b89c6a0e1556521b107df2dcca0889cd8dc1fd14/src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.html#L9)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

Please correct me if I'm wrong: Reading through the explanation leads me to believe that event binding is not necessary here. So `[(indeterminate)]` should instead be `[indeterminate]` as it is not a part of the book-multi-select model.
</blockquote></details>

Yes, that's correct.


<!-- Sent from Reviewable.io -->

2024-09-30 19:01 UTC, kylebuss reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2748)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.html` line 9 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2748#-O7o1PZi3iIbmhY76WTf:-O83IgJA3MJ6u5Mp-3Fj:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/b89c6a0e1556521b107df2dcca0889cd8dc1fd14/src/SIL.XForge.Scripture/ClientApp/src/app/shared/book-multi-select/book-multi-select.component.html#L9)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

Yes, that's correct.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-02 20:37 UTC, kylebuss reviewed
This is ready to be re-reviewed.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2748#-:-O8DwrHL7BpB7rJO-Woz:b-zaycmt)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @Nateowami)



<!-- Sent from Reviewable.io -->

2024-10-09 19:29 UTC, kylebuss reviewed
@Nateowami have you gotten a chance to look at this again?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2748#-:-O8mkIte3c5nAy5z5VFH:b-1f4tib)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @Nateowami)



<!-- Sent from Reviewable.io -->

2024-10-10 00:33 UTC, Nateowami approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 6 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2748#-:-O8npxhe3faRW4mUowI8:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kylebuss)



<!-- Sent from Reviewable.io -->

2024-10-10 14:12 UTC, merged