SF-3003 Fix Biblical Terms tab not showing in editor tabs
sillsdev/web-xforge pull request #2761
Opened 2024-10-02 13:22 UTC by kylebuss

When editing with a source project and biblical terms the tab for Biblical terms can end up being hidden if they were opened in the source pane and the user navigates to a book that does not exist in the source. This change will keep the source pane open if a persistent tab (biblical terms, draft, resource, history) has been opened in it.

2024-10-02 18:17 UTC, RaymondLuong3 requested changes
I think there is some merit in keeping the source editor tab group open when the user has intentionally opened tabs in that group. In practice, I think it is not very common for a user to be viewing a text without a corresponding source book, but we still want to have the view look good.
Your approach sounds good, so I think it is moving in the right direction. I get an error when changing books. You may have to find a way to skirt around the problem.

![error changing chapters.png](https://files.reviewableusercontent.io/images/reviewable/17931130/-GuaOCUmz7CocoPKBw7Ru1kd/error%20changing%20chapters.png)

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2761#-:-O8DQv9B1ETpgKGp_Ou7:b65y6ao)* status: all files reviewed, 3 unresolved discussions (waiting on @kylebuss)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 393 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2761#-O8DOSaK-1sWPQHs3cNu:-O8DOSaK-1sWPQHs3cNv:b-k3myx4) ([raw file](https://github.com/sillsdev/web-xforge/blob/8e5dfce41403e28acf1164fda199fbacab3cbae3/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L393)):*
> ```XML
>   }
> 
>   get persistentTabs(): boolean {
> ```

when getters have a boolean return type, it is better to name it so it is obvious. Something like `shouldTabGroupPersist`



_Code quote:_
```XML
  get persistentTabs(): boolean {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 775 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2761#-O8DOBR065OVeDu0DGuI:-O8DOBR065OVeDu0DGuJ:bqfxxnw) ([raw file](https://github.com/sillsdev/web-xforge/blob/8e5dfce41403e28acf1164fda199fbacab3cbae3/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L775)):*
> ```XML
>       });
> 
>     this.editorTabPersistenceService.persistedTabs$.subscribe(tabs => {
> ```

You will want to unsubscribe from this. See above for how it is done. You'll also want to be more specific, this should be checking for persisted tabs on the source group.



_Code quote:_
```XML
    this.editorTabPersistenceService.persistedTabs$.subscribe(tabs => {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 776 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2761#-O8DOrU02QoRK60-YBBf:-O8DOrU02QoRK60-YBBg:b-fmm3et) ([raw file](https://github.com/sillsdev/web-xforge/blob/8e5dfce41403e28acf1164fda199fbacab3cbae3/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L776)):*
> ```XML
> 
>     this.editorTabPersistenceService.persistedTabs$.subscribe(tabs => {
>       const persistentTabTypes = ['biblical-terms', 'history', 'draft', 'project-resource'];
> ```

Add a type here.



_Code quote:_
```XML
      const persistentTabTypes 
```


<!-- Sent from Reviewable.io -->

2024-10-03 21:30 UTC, RaymondLuong3 approved these changes
In my testing this is working well. I really like that the source panel persists even if the book is not available in the source.

I saw a minor issue with a book showing 'loading' when it does not actually exist in the source when I navigate to a book in the target project that does not exist in the source. I don't think it is going to be a significant problem but adding the comment here.
![image.png](https://files.reviewableusercontent.io/images/reviewable/17931130/Hwo80H4SUrt3_QlzorPC8u5c/image.png)

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2761#-:-O8JGSOF7ltGHbZna35n:b4nfjbj)* status: all files reviewed, 1 unresolved discussion (waiting on @kylebuss)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts` line 388 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2761#-O8JElfY1qHKePe8ggh1:-O8JElfY1qHKePe8ggh2:b2x66sb) ([raw file](https://github.com/sillsdev/web-xforge/blob/f8376823e78a1d6bdb70197fbf9dc2c951606c1f/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/editor.component.ts#L388)):*
> ```XML
>   }
> 
>   get showPersistentTabs(): boolean {
> ```

Nit: To keep this from being confused with "show when any tabs are persistent", name this `showPersistedTabsOnSource`



_Code quote:_
```XML
get showPersistentTabs(): boolean {
```


<!-- Sent from Reviewable.io -->

2024-10-04 10:24 UTC, kylebuss reviewed
I looked into this a bit and it appears to be with `updatePlaceholderText()` in `text.component.ts`. I played around with removing the 'project-source' tab and updating the text component to show a better message but did not have much success with either. I can keep working at it if you want?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2761#-:-O8M1g-B1nXYAYIoPSh-:bojlioz)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2024-10-04 17:24 UTC, RaymondLuong3 commented
Thanks for your work on this. If I thought this was a common think for a user to work on a project without a source for the book, I would say we should try to improve this. But I am happy with it as is.

2024-10-09 14:33 UTC, Nateowami commented
@kylebuss This needs merge conflicts fixed and then it can be merged.

2024-10-09 14:56 UTC, kylebuss reviewed
@Nateowami merge conflicts resolved.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2761#-:-O8lj7MVDLE-lTXPaoB8:b6xuq9x)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2024-10-09 15:06 UTC, merged