Add message to tap button in audio recorder dialog
sillsdev/web-xforge pull request #2777
Opened 2024-10-07 17:04 UTC by RaymondLuong3

A user may not recognize that to start a recording, they need to click the button. The tooltip partially fixed the problem, but not for users on mobile devices. This was suggested by the test team.

![image](https://github.com/user-attachments/assets/0df33202-25ab-4bec-aa75-a7133eab0a47)

2024-10-07 17:06 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2777)* status: 0 of 3 files reviewed, 1 unresolved discussion

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.scss` line 78 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2777#-O8bwHC0-3ZYxrGKJRoc:-O8bwHC0-3ZYxrGKJRod:bc924q6) ([raw file](https://github.com/sillsdev/web-xforge/blob/c37811c96658033244e885037b33570831ccbd09/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.scss#L78)):*
> ```SCSS
>     opacity: 0%;
>     &.visible {
>       animation: fadein 0.5s;
> ```

there was a momentary flash of the "tap to record" message when the recording first starts. This animation makes the flash not be so distracting.



_Code quote:_
```SCSS
      animation: fadein 0.5s;
```


<!-- Sent from Reviewable.io -->

2024-10-07 19:19 UTC, Nateowami commented
How many people do you think will read "tap to record" and tap on the text (or somewhere on the dialog outside the button)?

2024-10-07 19:34 UTC, RaymondLuong3 commented
Good point, I can update that to "Tap the icon to record". That would make it much less likely to be confused.

2024-10-07 19:40 UTC, Nateowami commented
Maybe just register a tap anywhere on the dialog as a record action?

I thought maybe this concept would work, until I actually saw it:
![](https://github.com/user-attachments/assets/5e03cf1a-ef2e-40b5-9235-0288871f31cc)

2024-10-08 18:10 UTC, RaymondLuong3 reviewed
Hmm, it is possible that tap anywhere on the dialog would be helpful, but not very discoverable. I did try your suggested message, and I think it could work. I've updated this PR to include this and the clean-up changes we discussed.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2777#-:-O8hJSUa2IIFHUj_h_l5:by4jl4w)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @nigel-wells)



<!-- Sent from Reviewable.io -->

2024-10-14 18:00 UTC, Nateowami commented
I brought this concept up as one I don't like after seeing it; I don't understand why you've updated this PR to implement it:

![](https://github.com/user-attachments/assets/56cd9990-5ec4-4dbf-8c6f-77633e446972)

I was thinking of it as a potential improvement to style below, replacing "the icon" with the actual icon, but I don't think having two of the same icon together looks good.

![](https://github.com/user-attachments/assets/5a98cc4a-c65f-40e3-a51b-e5253aeb1ed6)

I kind of like the option below (what you started with), though as I mentioned "tap to record" could be taken to mean tap anywhere on the dialog. My suggestion to address that was to consider making a tap anywhere on the dialog start recording. I don't see how that wouldn't be discoverable. If the user taps the icon, the recording would start; if the user taps the text, the recording would start, and if the user tapped anywhere else on the dialog it would start.

![](https://github.com/user-attachments/assets/5e7391c4-f690-44c8-a3fc-226e968107c9)

2024-10-15 03:53 UTC, nigel-wells commented
What about turning the whole thing into a button which then helps indicate where the tap should take place.
![image](https://github.com/user-attachments/assets/69895b4c-56d2-4ea0-85fd-161570ccd84c)
You could take it a step further to animate the drop shadow to have it bouncing up and down
![image](https://github.com/user-attachments/assets/9bb82984-d7ed-498c-81d2-9351e75bcac5)

2024-10-15 20:26 UTC, RaymondLuong3 reviewed
@Nateowami I misunderstood your comment and thought you wanted that message. I've removed it. I like Nigel's suggestion and decided to implement it. It makes it clear that tapping the button will cause the recording to start.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2777#-:-O9Gqr0n1liqptonfdZp:b-9jgtth)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @nigel-wells)



<!-- Sent from Reviewable.io -->

2024-10-17 02:01 UTC, nigel-wells requested changes
> Reviewed 1 of 5 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2777)* status: all files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.scss` line 78 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2777#-O8bwHC0-3ZYxrGKJRoc:-O9NCA_RDuLShu0I1Ecb:bp8ohn9) ([raw file](https://github.com/sillsdev/web-xforge/blob/c37811c96658033244e885037b33570831ccbd09/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.scss#L78)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

there was a momentary flash of the "tap to record" message when the recording first starts. This animation makes the flash not be so distracting.
</blockquote></details>

Yeah, nice. I think I see the flash you mention happen after the countdown has ended - can you do it there as well?
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.scss` line 59 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2777#-O9NBjvXCVTsStKmygz0:-O9NBjvXCVTsStKmygz1:b1tbyz7) ([raw file](https://github.com/sillsdev/web-xforge/blob/2e80fb1e0a2b06ba8ff553d4a6ae4d17c280f25b/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.scss#L59)):*
> ```SCSS
>     border-radius: 50%;
>     cursor: pointer;
>     background-color: rgba(0, 0, 0, 0.1);
> ```

Let's go for these slight tweaks:
```
background-color: rgba(0, 0, 0, 0.08);
box-shadow: 3px 4px 4px rgba(0, 0, 0, 0.15);
```

And add a hover transition as well


<!-- Sent from Reviewable.io -->

2024-10-17 15:32 UTC, Nateowami commented
What about just "Record" on the button? It seems like the original problem is that there was a button that didn't look much like a button, and with no text. If it's made to look like a button, and has the text "Record" on it, I don't think we need "Tap to record"

2024-10-17 18:04 UTC, RaymondLuong3 reviewed
Yes, I can change that to a simple "record"

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2777#-:-O9QdAT50PiGHpX24Fhf:bem4e3j)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.scss` line 78 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2777#-O8bwHC0-3ZYxrGKJRoc:-O9QdL4D9RgF8mDyLsAD:b-tukp2f) ([raw file](https://github.com/sillsdev/web-xforge/blob/c37811c96658033244e885037b33570831ccbd09/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.scss#L78)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Yeah, nice. I think I see the flash you mention happen after the countdown has ended - can you do it there as well?
</blockquote></details>

I have updated it. Do you still see a flash after the countdown? I applied the fade in animation to both the record and stop elements.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.scss` line 59 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2777#-O9NBjvXCVTsStKmygz0:-O9QdEgTBAhpwVUz5hjh:bo5nztk) ([raw file](https://github.com/sillsdev/web-xforge/blob/2e80fb1e0a2b06ba8ff553d4a6ae4d17c280f25b/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.scss#L59)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Let's go for these slight tweaks:
```
background-color: rgba(0, 0, 0, 0.08);
box-shadow: 3px 4px 4px rgba(0, 0, 0, 0.15);
```

And add a hover transition as well
</blockquote></details>

Nice. Done.


<!-- Sent from Reviewable.io -->

2024-10-17 18:40 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2777)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @nigel-wells and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.scss` line 71 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/2777#-O9QhCeO2S8NSWfHxX8L:-O9QhCeO2S8NSWfHxX8M:b-ttwbsv) ([raw file](https://github.com/sillsdev/web-xforge/blob/d2abda2837f3e56068564c68279e96c838a1ea9f/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.scss#L71)):*
> ```SCSS
> 
>     &:hover {
>       background-color: variables.$greenLight;
> ```

I like some of these improvements to making this look like a button, but I don't think the hover effect should dramatically change the color, only change it slightly. 

If you look at the Material example buttons, none of them change dramatically, and I think this is standard practice https://material.angular.io/components/button/overview


<!-- Sent from Reviewable.io -->

2024-10-17 19:34 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2777)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @nigel-wells)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.scss` line 71 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/2777#-O9QhCeO2S8NSWfHxX8L:-O9QyHG6EEVyi5dKIoMw:b-p4qk33) ([raw file](https://github.com/sillsdev/web-xforge/blob/d2abda2837f3e56068564c68279e96c838a1ea9f/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.scss#L71)):*
<details><summary><i>Previously, Nateowami wrote…</i></summary><blockquote>

I like some of these improvements to making this look like a button, but I don't think the hover effect should dramatically change the color, only change it slightly. 

If you look at the Material example buttons, none of them change dramatically, and I think this is standard practice https://material.angular.io/components/button/overview
</blockquote></details>

Thanks for the tip. You're right, the more subtle colour change is more in line with the button examples. I've adjusted it to be a slightly darker background colour.


<!-- Sent from Reviewable.io -->

2024-10-18 00:29 UTC, nigel-wells approved these changes
Just the one minor comment there about the flash - I don't want to hold it up if you can figure out how to resolve as I'm about to head off for the weekend.

> Reviewed 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2777#-:-O9S0k8M0Hr74ByAp0h0:bw6hz4c)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.scss` line 78 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2777#-O8bwHC0-3ZYxrGKJRoc:-O9S0M2rCHHG_DWRkKq5:bc1q6m9) ([raw file](https://github.com/sillsdev/web-xforge/blob/c37811c96658033244e885037b33570831ccbd09/src/SIL.XForge.Scripture/ClientApp/src/app/shared/audio-recorder-dialog/audio-recorder-dialog.component.scss#L78)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I have updated it. Do you still see a flash after the countdown? I applied the fade in animation to both the record and stop elements.
</blockquote></details>

I do - its very quick though. I've done a recording and it looks like the flash shows the new tap to record button briefly before the recording state has had a chance to kick in
[Recording 2024-10-18 132809.mp4](https://files.reviewableusercontent.io/images/reviewable/17464863/8SxCDPjDzxDhW-ES3XstY4tc/Recording%202024-10-18%20132809.mp4)


<!-- Sent from Reviewable.io -->

2024-10-18 17:48 UTC, RaymondLuong3 commented
Thanks for the recording! It is so fast, but I was able to see it when I slowed it down to 0.25 speed. I've updated the fade in animation so that the fade holds off longer, and it seems to do the trick.

2024-10-18 17:56 UTC, merged