SF-3027 Fix inconsistent styles of page titles
sillsdev/web-xforge pull request #2796
Opened 2024-10-10 20:30 UTC by kylebuss

This PR makes the styling of the pages title consistent across the app.

2024-10-10 21:33 UTC, RaymondLuong3 requested changes
You should be able to apply styling using a material theme. I haven't tried this, but this article should give you some ideas. [Theming Angular Material | Angular Material](https://material.angular.io/guide/theming#customizing-your-typography)
I like the slim look of the characters for our headline labels. Sometimes it looks too large, such as on the checking overview page, but other than that, the consistency is a plus.

> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2796#-:-O8sIj4g1horz5FQmJM_:b84lucl)* status: all files reviewed, 2 unresolved discussions (waiting on @josephmyers and @kylebuss)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss` line 222 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2796#-O8sK7207XvZIyfdqd6F:-O8sK7207XvZIyfdqd6G:b-wuxvr3) ([raw file](https://github.com/sillsdev/web-xforge/blob/35030863a20489863907894026daa7a8a1681f6e/src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss#L222)):*
> ```SCSS
> 
> div {
>   .title {
> ```

I would use a more descriptive class, like "headline-4" or just "headline"



_Code quote:_
```SCSS
  .title {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss` line 225 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2796#-O8sHPUI2gQ2OE1iHhQ9:-O8sHPUI2gQ2OE1iHhQA:b-3iztf1) ([raw file](https://github.com/sillsdev/web-xforge/blob/35030863a20489863907894026daa7a8a1681f6e/src/SIL.XForge.Scripture/ClientApp/src/material-styles.scss#L225)):*
> ```SCSS
>     @extend .mat-headline-4;
>     margin-bottom: 0;
>   }
> ```

You probably want this instead, what you have says select an element with the title class that is a child of a div element.



_Code quote (i):_
```SCSS
div {
  .title {
    @extend .mat-headline-4;
    margin-bottom: 0;
  }
```



_Code snippet (ii):_
```SCSS
div.title {
  @extend ...
```


<!-- Sent from Reviewable.io -->

2024-10-11 01:36 UTC, Nateowami commented
After looking at this very briefly, I don't think I agree with either direction that's being discussed here. I suggest working on other things until we get a chance to talk and get on the same page.

2024-10-29 13:00 UTC, kylebuss reviewed
@Nateowami and @RaymondLuong3, any update on where we are at on this one? Should we schedule a time to meet?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2796#-:-OANM-jDBwQtthnrIt-f:bvltjuu)* status: all files reviewed, 2 unresolved discussions (waiting on @josephmyers)



<!-- Sent from Reviewable.io -->

2025-03-19 16:42 UTC, Nateowami commented
We'll put this off until after the Material theme upgrade. It's likely to change how this is done.

2025-03-19 16:42 UTC, closed without merging