SF-3038 ProgressService listens to project changes (and initializes itself)
sillsdev/web-xforge pull request #2810
Opened 2024-10-16 04:50 UTC by josephmyers

Project changes can be adding books, for example. It now listens to the activated project to retrieve its project id, where beforehand it was waiting for the components to supply this.

Similarly, the initialize() call now can happen even when the project hasn't been switched. This accounts for the addition of books. It is on a 1s throttle, like the calculate() call.

2024-10-16 16:12 UTC, Nateowami commented
Please update the PR title to meet the commit message guidelines: https://github.com/sillsdev/web-xforge/blob/master/CONTRIBUTING.md

2024-10-16 18:17 UTC, RaymondLuong3 requested changes
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2810)* status: all files reviewed, 5 unresolved discussions (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/progress-service/progress.service.ts` line 61 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2810#-O9LLt1K84LhzMe1IOLz:-O9LLt1K84LhzMe1IOM-:b-yiuhwe) ([raw file](https://github.com/sillsdev/web-xforge/blob/89c363cf477096af5e30f60bb37613323a64111f/src/SIL.XForge.Scripture/ClientApp/src/app/shared/progress-service/progress.service.ts#L61)):*
> ```XML
>         tap(async project => {
>           this.initialize(project.id);
>           merge(project.remoteChanges$, project.changes$)
> ```

I would have that `project.changes$` also covers remote changes also. Is this not the case?
It's really not a good idea to have a subscription create more subscriptions. The better way is to map the observable to the one you want. Actually, this could be more simplified to listen to the `changes$` observable.



_Code quote (i):_
```XML
      merge(project.remoteChanges$, project.changes$)
```



_Code snippet (ii):_
```XML
    this.subscribe(
      this.activatedProject.changes$.pipe(
        filterNullish(),
        tap(async project => {
          this.initialize(project.id);
        }),
        throttleTime(1000, asyncScheduler, { leading: false, trailing: true })
      ),
      project => {
        this.initialize(project.id);
      }
    );
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/progress-service/progress.service.ts` line 74 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2810#-O9LLlZ15La-MI6qtiiR:-O9LLlZ15La-MI6qtiiS:bi9p8g9) ([raw file](https://github.com/sillsdev/web-xforge/blob/89c363cf477096af5e30f60bb37613323a64111f/src/SIL.XForge.Scripture/ClientApp/src/app/shared/progress-service/progress.service.ts#L74)):*
> ```XML
>     super.ngOnDestroy();
>     this._allChaptersChangeSub?.unsubscribe();
>   }
> ```

Nit: This should be moved below the getters.



_Code quote:_
```XML
  ngOnDestroy(): void {
    super.ngOnDestroy();
    this._allChaptersChangeSub?.unsubscribe();
  }
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/progress-service/progress.service.spec.ts` line 15 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2810#-O9LM39x9cQfcaqrohLm:-O9LM39x9cQfcaqrohLn:br2rfgj) ([raw file](https://github.com/sillsdev/web-xforge/blob/89c363cf477096af5e30f60bb37613323a64111f/src/SIL.XForge.Scripture/ClientApp/src/app/shared/progress-service/progress.service.spec.ts#L15)):*
> ```XML
> import { TestRealtimeModule } from 'xforge-common/test-realtime.module';
> import { configureTestingModule } from 'xforge-common/test-utils';
> import { ActivatedProjectService } from '../../../xforge-common/activated-project.service';
> ```

This can be an absolute path.



_Code quote:_
```XML
'../../../xforge-common/activated-project.service';
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/progress-service/progress.service.spec.ts` line 80 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2810#-O9LXsyU7ZRebuVnil0V:-O9LXsyU7ZRebuVnil0W:b-7q943s) ([raw file](https://github.com/sillsdev/web-xforge/blob/89c363cf477096af5e30f60bb37613323a64111f/src/SIL.XForge.Scripture/ClientApp/src/app/shared/progress-service/progress.service.spec.ts#L80)):*
> ```XML
>   }));
> 
>   it('re-initializes for local project changes', fakeAsync(() => {
> ```

This test and the one below can be combined if you listen to the `changes$` observable from `activatedProjectService`



_Code quote:_
```XML
  it('re-initializes for local project changes', fakeAsync(() => {
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts` line 288 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2810#-O9LOETJE548VuN76XMO:-O9LOETJE548VuN76XMP:b-ifp9b9) ([raw file](https://github.com/sillsdev/web-xforge/blob/89c363cf477096af5e30f60bb37613323a64111f/src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts#L288)):*
> ```XML
>     when(mockedProgressService.overallProgress).thenReturn(new Progress());
>     when(mockedProgressService.texts).thenReturn([
>       { translated: 10, blank: 10, total: 20, percentage: 50, text: { bookNum: 40 } as any } as any,
> ```

Is there a reason to not cast it to be the TextInfo and TextProgress types?



_Code quote:_
```XML
   { translated: 10, blank: 10, total: 20, percentage: 50, text: { bookNum: 40 } as any } as any,
```


<!-- Sent from Reviewable.io -->

2024-10-16 18:34 UTC, Nateowami commented
@RaymondLuong3 I have a guess as to what you were saying, but "I would have that `project.changes$`" is missing a word. I think you mean you would have thought?

2024-10-16 20:56 UTC, RaymondLuong3 reviewed
That is correct. Thanks for catching that.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2810#-:-O9M6Ts5155UCHRM2V9f:b-ycvdi6)* status: all files reviewed, 5 unresolved discussions (waiting on @josephmyers)



<!-- Sent from Reviewable.io -->

2024-10-17 02:09 UTC, josephmyers reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2810)* status: 4 of 7 files reviewed, 3 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/progress-service/progress.service.ts` line 61 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2810#-O9LLt1K84LhzMe1IOLz:-O9N5_kf5DIAazQGmUx9:b-55krxf) ([raw file](https://github.com/sillsdev/web-xforge/blob/89c363cf477096af5e30f60bb37613323a64111f/src/SIL.XForge.Scripture/ClientApp/src/app/shared/progress-service/progress.service.ts#L61)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I would have that `project.changes$` also covers remote changes also. Is this not the case?
It's really not a good idea to have a subscription create more subscriptions. The better way is to map the observable to the one you want. Actually, this could be more simplified to listen to the `changes$` observable.
</blockquote></details>

Thanks for correcting my rxjs!
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/progress-service/progress.service.ts` line 74 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2810#-O9LLlZ15La-MI6qtiiR:-O9N5okX3bBz5_JlO5pw:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/89c363cf477096af5e30f60bb37613323a64111f/src/SIL.XForge.Scripture/ClientApp/src/app/shared/progress-service/progress.service.ts#L74)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Nit: This should be moved below the getters.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/progress-service/progress.service.spec.ts` line 15 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2810#-O9LM39x9cQfcaqrohLm:-O9N5urT1EX-BThZVVgu:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/89c363cf477096af5e30f60bb37613323a64111f/src/SIL.XForge.Scripture/ClientApp/src/app/shared/progress-service/progress.service.spec.ts#L15)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This can be an absolute path.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/progress-service/progress.service.spec.ts` line 80 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2810#-O9LXsyU7ZRebuVnil0V:-O9N64YW7NJV2zXY2U4Q:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/89c363cf477096af5e30f60bb37613323a64111f/src/SIL.XForge.Scripture/ClientApp/src/app/shared/progress-service/progress.service.spec.ts#L80)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This test and the one below can be combined if you listen to the `changes$` observable from `activatedProjectService`
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts` line 288 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2810#-O9LOETJE548VuN76XMO:-O9N6dAv8K6pmRay_vmo:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/89c363cf477096af5e30f60bb37613323a64111f/src/SIL.XForge.Scripture/ClientApp/src/app/translate/translate-overview/translate-overview.component.spec.ts#L288)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Is there a reason to not cast it to be the TextInfo and TextProgress types?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-18 16:08 UTC, merged