SF-3048 Hide unusable books details on draft generation stepper
sillsdev/web-xforge pull request #2817
Opened 2024-10-18 21:55 UTC by RaymondLuong3

Please reference the [balsamiq](https://balsamiq.cloud/sghq53/pejrlz8/r49DC) for the mock up of this change.

This PR add a way to hide the info for unusable translate and training books on the draft generation stepper.

Collapsed:
![Draft generation steps hidden](https://github.com/user-attachments/assets/0971da1b-abc3-40b5-a8ee-36828c091cb8)

Expanded:
![Draft generation steps expanded](https://github.com/user-attachments/assets/4ac9083a-6daf-4802-b4bd-0aae01b36261)

2024-10-21 04:18 UTC, josephmyers requested changes
Your code looks fine, good job. I'm looking at the placement of this on the page itself, now, and I think it'd make more sense to put this above the "can't find your book" notice. Thoughts?

Also, I'm on the fence about the heavy use of coloring for this box. It seems like a lot to me, given what this box is. Does it really need to be the most colorful thing on the page, even at its smaller form? I thought Nathaniel had a good design [here](https://github.com/sillsdev/web-xforge/pull/2730#issuecomment-2418072575), even for something as important as language codes, and I wonder if you experimented with other styles that might match closer the subtlety of this or the wireframe.

Lastly, minor comment that the icon looks weird shifting between open and closed states. The wireframe has it staying at the top all the time. Did you try that?

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2817#-:-O9hCxn87AY5GySTOGXM:bo4t9za)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html` line 106 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2817#-O9hGEphA5Rrs_4nQYpm:-O9hGEphA5Rrs_4nQYpn:bgatb4x) ([raw file](https://github.com/sillsdev/web-xforge/blob/3e42c8adcb5461ab7ad07c1d0ed6200143c13c5e/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html#L106)):*
> ```HTML
>                   ></transloco>
>                 </h4>
>                 <span class="book-names">{{ bookNames(unusableTrainingSourceBooks) }}</span>
> ```

The styling of the books needs some touching up. It looks fine in some cases, but when there are many books they look too much like the other text in the box:

![image.png](https://files.reviewableusercontent.io/images/reviewable/43733878/rkh4sT-Gz9LofDX9g0XtP4Wq/image.png)

You have lots of options. Adding some space above the books, to break up the sameness in the layout, could help. You could also adjust how the books look, maybe the font size, to help them stand out.


<!-- Sent from Reviewable.io -->

2024-10-21 22:39 UTC, RaymondLuong3 reviewed
Thanks for the suggestions. You are right, the color is not necessary and draws too much attention. I added a 'basic' mode to the modes for a notice that just does a background color without a border.
I also matched the icon position on the wireframe, I think that is nice for notices that can be expanded so it doesn't look like the icon jumps around.

I think having the books hidden message makes sense above the message for "cannot find the books you are looking for" since it notifies the user that some books are hidden before the actionable message of creating books in paratext.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2817#-:-O9lCgHKAI-Xnq9fHLvy:b-w1cf18)* status: 2 of 7 files reviewed, 1 unresolved discussion (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html` line 106 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2817#-O9hGEphA5Rrs_4nQYpm:-O9lDpdW14zNVtys3a1D:bg5rdty) ([raw file](https://github.com/sillsdev/web-xforge/blob/3e42c8adcb5461ab7ad07c1d0ed6200143c13c5e/src/SIL.XForge.Scripture/ClientApp/src/app/translate/draft-generation/draft-generation-steps/draft-generation-steps.component.html#L106)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

The styling of the books needs some touching up. It looks fine in some cases, but when there are many books they look too much like the other text in the box:

![image.png](https://files.reviewableusercontent.io/images/reviewable/43733878/rkh4sT-Gz9LofDX9g0XtP4Wq/image.png)

You have lots of options. Adding some space above the books, to break up the sameness in the layout, could help. You could also adjust how the books look, maybe the font size, to help them stand out.
</blockquote></details>

I added a heavier weight to the books, and adding a slight indent and padding. It should stand out more now.


<!-- Sent from Reviewable.io -->

2024-10-22 00:48 UTC, josephmyers approved these changes
Cool, this looks good. 

> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2817#-:-O9lgWk1CvINU81IjV6K:b-6rgmrp)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2024-10-22 00:49 UTC, josephmyers commented
@RaymondLuong3 It feels weird for me to merge this, so I'll let you do the slam dunking :D

2024-10-22 02:50 UTC, merged