WIP: SF-2900 Mixed Source: Selecting books from each source
sillsdev/web-xforge pull request #2825
Opened 2024-10-28 18:58 UTC by pmachapman

**To Do**

 * Model to specify books for each source
 * Passing these books to Serval

**Done**

 * Updating to latest Serval Client
 * Removing legacy code
 * Support for new Parallel Corpora

2024-10-29 21:22 UTC, kylebuss requested changes
Looking good! I can definitely see what you meant when you mentioned waiting on SF-2525 for these changes.

> Reviewed 6 of 9 files at r1, 23 of 23 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-:-OAP8s8C3pZYVpiIFCav:b-rqj54e)* status: all files reviewed, 9 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/Models/ServalAdditionalTrainingData.cs` line 7 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-OAO9iRw3X_nUVGEOTdT:-OAO9iRw3X_nUVGEOTdU:bds7uf) ([raw file](https://github.com/sillsdev/web-xforge/blob/012546dfeb134619e461f967d237ddad0fd94e24/src/SIL.XForge.Scripture/Models/ServalAdditionalTrainingData.cs#L7)):*
> ```Smalltalk
> /// <summary>
> /// Serval Configuration for Additional Training Data.
> /// </summary>
> ```

Is there a link or class in Serval for reference to this?



_Code quote:_
```Smalltalk
/// </summary>
```
___
*[`src/SIL.XForge.Scripture/Services/MachineApiService.cs` line 729 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-OAOBjpx3yuKWT7VxCVG:-OAOBjpx3yuKWT7VxCVH:byf2s4q) ([raw file](https://github.com/sillsdev/web-xforge/blob/012546dfeb134619e461f967d237ddad0fd94e24/src/SIL.XForge.Scripture/Services/MachineApiService.cs#L729)):*
> ```Smalltalk
>             );
>         }
> ```

Can you add a comment here to specify Translation section and above (line 702) for Training Section? The code is so similar I thought it was duplicated.
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 394 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-OAO4NxV6Aq4k8dQhSFY:-OAO4NxV6Aq4k8dQhSFZ:biswi5i) ([raw file](https://github.com/sillsdev/web-xforge/blob/012546dfeb134619e461f967d237ddad0fd94e24/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L394)):*
> ```Smalltalk
> 
>         // If there is an alternate source, ensure that writing system and RTL is correct
>         if (projectDoc.Data.TranslateConfig.DraftConfig.AlternateSource is not null)
> ```

We might consider updating the `settings.FullName`, as that can also be changed in the Paratext registry.



_Code quote:_
```Smalltalk
if (projectDoc.Data.TranslateConfig.DraftConfig.AlternateSource is not null)
```
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 408 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-OAOFJk4AKPxTH44mYUf:-OAOFJk4AKPxTH44mYUg:b-6hrxbo) ([raw file](https://github.com/sillsdev/web-xforge/blob/012546dfeb134619e461f967d237ddad0fd94e24/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L408)):*
> ```Smalltalk
>                         alternateSourceSettings.IsRightToLeft
>                     );
>                     if (alternateSourceSettings.LanguageTag is not null)
> ```

While unlikely, should we verify the primary source and alternate/additional source language tags match and error if they do not?



_Code quote:_
```Smalltalk
if (alternateSourceSettings.LanguageTag is not null)
```
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 587 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-OAOIZSy7MqeZj6QOEmy:-OAOIZSy7MqeZj6QOEmz:bl2xd0p) ([raw file](https://github.com/sillsdev/web-xforge/blob/012546dfeb134619e461f967d237ddad0fd94e24/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L587)):*
> ```Smalltalk
>     /// <returns>The parallel corpus identifier.</returns>
>     /// <remarks>This can be mocked in unit tests.</remarks>
>     protected internal virtual async Task<string> CreateOrUpdateParallelCorpusAsync(
> ```

Curious to the reasoning behind making this method's virtual?



_Code quote:_
```Smalltalk
internal virtual async
```
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 860 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-OAOKzmlCTGCVVMfKNtD:-OAOKzmlCTGCVVMfKNtE:b-sqyp33) ([raw file](https://github.com/sillsdev/web-xforge/blob/012546dfeb134619e461f967d237ddad0fd94e24/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L860)):*
> ```Smalltalk
>                 }
> 
>                 // Update the source writing system tag
> ```

It might be an unlikely scenario, but I wonder if we may want to check if RTL has changed for the source?



_Code quote:_
```Smalltalk
// Update the source writing system tag
```
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 1162 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-OAOOqaR-b6cBiV1lyr8:-OAOOqaR-b6cBiV1lyr9:b-7pl8as) ([raw file](https://github.com/sillsdev/web-xforge/blob/012546dfeb134619e461f967d237ddad0fd94e24/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L1162)):*
> ```Smalltalk
>                 cancellationToken
>             );
>             bool recreateTranslationEngine = false;
> ```

If RTL has changed should we also recreate the translation engine?



_Code quote:_
```Smalltalk
recreateTranslationEngine
```
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 1346 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-OAOQa7W9DKB7s5Z_BUs:-OAOQa7X-7tdUTHFgqG1:b-6jox9t) ([raw file](https://github.com/sillsdev/web-xforge/blob/012546dfeb134619e461f967d237ddad0fd94e24/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L1346)):*
> ```Smalltalk
> 
>             // Upload the source texts
>             List<ServalCorpusFile> sourceCorpusFiles = [.. additionalTrainingData.CorpusFiles];
> ```

Seen the Range operator used a few times with this PR, what are some of the benefits to using this over simply having `= additionalTrainingData.CorpusFiles;`?



_Code quote:_
```Smalltalk
[.. additionalTrainingData.CorpusFiles]
```
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 1701 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-OAOxgaKBwLos8IIT82W:-OAOxgaL31Qi8NZFbduG:b-5cwj50) ([raw file](https://github.com/sillsdev/web-xforge/blob/012546dfeb134619e461f967d237ddad0fd94e24/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L1701)):*
> ```Smalltalk
>                 translationParallelCorpusId
>             );
>         }
> ```

Do we need the if/else here?

I wonder if we can differentiate between NMT and SMT in the few places like this:
```
string sourceProjectId = preTranslate ? hasAlternateSource
        ? project.TranslateConfig.DraftConfig.AlternateSource.ProjectRef
        : project.TranslateConfig.Source.ProjectRef
        : project.TranslateConfig.Source.ProjectRef;
```
And then put the alternate/additional sources in a single `if(preTranslate) { ...}`?



_Code quote:_
```Smalltalk
        else
        {
            // Set up the parallel corpus for SMT translation
            string sourceProjectId = project.TranslateConfig.Source.ProjectRef;
            List<ServalCorpusFile> sourceCorpora = [servalCorpusFiles.Single(f => f.ProjectId == sourceProjectId)];
            List<ServalCorpusFile> targetCorpora = [servalCorpusFiles.Single(f => f.ProjectId == project.Id)];
            List<string> sourceCorpusIds = sourceCorpora.Select(f => f.CorpusId).ToList();
            List<string> targetCorpusIds = targetCorpora.Select(f => f.CorpusId).ToList();

            // Get the pre-translate parallel corpus id (might be null)
            translationParallelCorpusId = projectSecret.ServalData.ParallelCorpusIdForSmt;

            // Create or update the pre-translate parallel corpora
            translationParallelCorpusId = await CreateOrUpdateParallelCorpusAsync(
                translationEngineId,
                translationParallelCorpusId,
                name: "SmtTranslation",
                sourceCorpusIds,
                targetCorpusIds,
                cancellationToken
            );

            // Record the corpus sync info
            corporaSyncInfo = RecordServalCorpusSyncInfo(
                corporaSyncInfo,
                sourceCorpora,
                targetCorpora,
              [...]

2024-10-29 23:18 UTC, pmachapman reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2825)* status: 25 of 30 files reviewed, 8 unresolved discussions (waiting on @kylebuss)

___
*[`src/SIL.XForge.Scripture/Models/ServalAdditionalTrainingData.cs` line 7 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-OAO9iRw3X_nUVGEOTdT:-OAPBJT_1XkPnfXS9CIs:bsy0wc7) ([raw file](https://github.com/sillsdev/web-xforge/blob/012546dfeb134619e461f967d237ddad0fd94e24/src/SIL.XForge.Scripture/Models/ServalAdditionalTrainingData.cs#L7)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

Is there a link or class in Serval for reference to this?
</blockquote></details>

No, because this is the class where we keep our configuration data for specifying the additional training data on Serval. I have updated the comment to be clearer.
___
*[`src/SIL.XForge.Scripture/Services/MachineApiService.cs` line 729 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-OAOBjpx3yuKWT7VxCVG:-OAPCCiD6WSxxzpTwDyt:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/012546dfeb134619e461f967d237ddad0fd94e24/src/SIL.XForge.Scripture/Services/MachineApiService.cs#L729)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

Can you add a comment here to specify Translation section and above (line 702) for Training Section? The code is so similar I thought it was duplicated.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 394 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-OAO4NxV6Aq4k8dQhSFY:-OAPCYRGAMU3mv7OHELi:b35wj2g) ([raw file](https://github.com/sillsdev/web-xforge/blob/012546dfeb134619e461f967d237ddad0fd94e24/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L394)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

We might consider updating the `settings.FullName`, as that can also be changed in the Paratext registry.
</blockquote></details>

Done. Good point.
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 408 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-OAOFJk4AKPxTH44mYUf:-OAPDffi6rDHIFtciIyH:bj83yzl) ([raw file](https://github.com/sillsdev/web-xforge/blob/012546dfeb134619e461f967d237ddad0fd94e24/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L408)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

While unlikely, should we verify the primary source and alternate/additional source language tags match and error if they do not?
</blockquote></details>

I think our checks before we start are sufficient, and Serval will return if they are not compatible.

There is also the complexity of en_GB vs en_NZ - both are English, and so we may incorrectly mark as not equal. I think it's best not to do the checking here, and let Serval notify us if there is something wrong.
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 587 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-OAOIZSy7MqeZj6QOEmy:-OAPECmbC0Df3pr7CcbY:b4iyfdv) ([raw file](https://github.com/sillsdev/web-xforge/blob/012546dfeb134619e461f967d237ddad0fd94e24/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L587)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

Curious to the reasoning behind making this method's virtual?
</blockquote></details>

So it can be overridden in unit tests.
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 860 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-OAOKzmlCTGCVVMfKNtD:-OAPENGU6JlrGJ4a4Iqn:bw4juah) ([raw file](https://github.com/sillsdev/web-xforge/blob/012546dfeb134619e461f967d237ddad0fd94e24/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L860)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

It might be an unlikely scenario, but I wonder if we may want to check if RTL has changed for the source?
</blockquote></details>

This code is for a specific bug with back translations not being in the registry (see the big comment above the block). IsRighttoLeft was not affected by it, as far as I am aware. I'll make a note to investigate further if it is, as it would affect other areas of Scripture Forge if it is applicable.
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 1162 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-OAOOqaR-b6cBiV1lyr8:-OAPGFp1E7bbpX9XIiiT:b-7l06s4) ([raw file](https://github.com/sillsdev/web-xforge/blob/012546dfeb134619e461f967d237ddad0fd94e24/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L1162)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

If RTL has changed should we also recreate the translation engine?
</blockquote></details>

No. We don't send RTL to Serval.
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 1346 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-OAOQa7W9DKB7s5Z_BUs:-OAPGL4x5Lpi2ZZSlZOG:bjt8eu) ([raw file](https://github.com/sillsdev/web-xforge/blob/012546dfeb134619e461f967d237ddad0fd94e24/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L1346)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

Seen the Range operator used a few times with this PR, what are some of the benefits to using this over simply having `= additionalTrainingData.CorpusFiles;`?
</blockquote></details>

This syntax passes the items in the list, not a reference to the list. The older (pre-.NET 8.0) syntax would be:

```cs
List<ServalCorpusFile> sourceCorpusFiles = new List<ServalCorpusFile>(additionalTrainingData.CorpusFiles);
```

Passing a reference to the list would cause the original list to get trashed and all sorts of other bugs.
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 1701 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-OAOxgaKBwLos8IIT82W:-OAPVKOtDa_no0gRpJrE:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/012546dfeb134619e461f967d237ddad0fd94e24/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L1701)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

Do we need the if/else here?

I wonder if we can differentiate between NMT and SMT in the few places like this:
```
string sourceProjectId = preTranslate ? hasAlternateSource
        ? project.TranslateConfig.DraftConfig.AlternateSource.ProjectRef
        : project.TranslateConfig.Source.ProjectRef
        : project.TranslateConfig.Source.ProjectRef;
```
And then put the alternate/additional sources in a single `if(preTranslate) { ...}`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-30 14:07 UTC, kylebuss approved these changes
Looks good! Thanks for the explanations and clean up. I especially like the `GetPreTranslationParametersAsync` that was added!

> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-:-OASjzO0BaSptHspMzUw:b-knqp7u)* status: all files reviewed, 2 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 587 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-OAOIZSy7MqeZj6QOEmy:-OASdPNB8iTMK4uFPxME:b-x51s74) ([raw file](https://github.com/sillsdev/web-xforge/blob/012546dfeb134619e461f967d237ddad0fd94e24/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L587)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

So it can be overridden in unit tests.
</blockquote></details>

Thanks for clarifying. Looks like Raymond had it correct in our discussion!
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 1346 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-OAOQa7W9DKB7s5Z_BUs:-OASdzW35phTqmdmDnK5:b-33izv3) ([raw file](https://github.com/sillsdev/web-xforge/blob/012546dfeb134619e461f967d237ddad0fd94e24/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L1346)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

This syntax passes the items in the list, not a reference to the list. The older (pre-.NET 8.0) syntax would be:

```cs
List<ServalCorpusFile> sourceCorpusFiles = new List<ServalCorpusFile>(additionalTrainingData.CorpusFiles);
```

Passing a reference to the list would cause the original list to get trashed and all sorts of other bugs.
</blockquote></details>

Raymond was right again! And thanks for the explanation, I had never seen the [.. ] before this.
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 1701 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-OAOxgaKBwLos8IIT82W:-OASesPN-tbVrQHhhpcB:b-hay2ib) ([raw file](https://github.com/sillsdev/web-xforge/blob/012546dfeb134619e461f967d237ddad0fd94e24/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L1701)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks! 


<!-- Sent from Reviewable.io -->

2024-10-31 22:02 UTC, RaymondLuong3 requested changes
Nice work! I have a few minor suggestions and a couple blocking comments. Can you add acceptance tests to the Jira issue? It may be a big list of scenarios so I almost don't want to ask hah

> Reviewed 5 of 9 files at r1, 20 of 23 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-:-OAZa3AJ84qJR0tgQhrN:bwf9z6x)* status: all files reviewed, 7 unresolved discussions (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 639 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-OAZ4iAD65XcGVY33p8q:-OAZ4iAE8i3a3gZ34hzk:b-jry25k) ([raw file](https://github.com/sillsdev/web-xforge/blob/9dfa067534ae2d1170a92c0c4bd66b1c0348fe56/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L639)):*
> ```Smalltalk
>         else
>         {
>             await translationEnginesClient.UpdateParallelCorpusAsync(
> ```

Calling UpdateParallelCorpusAsync will update the parallelCorpusId? It doesn't seem like a good idea to do that in an async method. Can you leave a comment stating this?



_Code quote:_
```Smalltalk
            await translationEnginesClient.UpdateParallelCorpusAsync(
```
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 838 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-OAZ6DMNBWqfJjEkv727:-OAZ6DMNBWqfJjEkv728:b-we1mxu) ([raw file](https://github.com/sillsdev/web-xforge/blob/9dfa067534ae2d1170a92c0c4bd66b1c0348fe56/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L838)):*
> ```Smalltalk
>         string translationEngineId = preTranslate
>             ? projectSecret.ServalData?.PreTranslationEngineId
>             : projectSecret.ServalData?.TranslationEngineId;
> ```

I have seen this a number of times. Perhaps we would be worth creating a helper method to get the translation engine Id and keep it more readable.



_Code quote:_
```Smalltalk
        string translationEngineId = preTranslate
            ? projectSecret.ServalData?.PreTranslationEngineId
            : projectSecret.ServalData?.TranslationEngineId;
```
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 932 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-OAZ79Oi96ECdv-t-li6:-OAZ79Oi96ECdv-t-li7:b-mcnyfv) ([raw file](https://github.com/sillsdev/web-xforge/blob/9dfa067534ae2d1170a92c0c4bd66b1c0348fe56/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L932)):*
> ```Smalltalk
>         if (string.IsNullOrWhiteSpace(translationEngineId))
>         {
>             throw new DataNotFoundException("The translation engine is not specified.");
> ```

A better message would be "Failed to create a translation engine"



_Code quote:_
```Smalltalk
            throw new DataNotFoundException("The translation engine is not specified.");
```
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 1335 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-OAZNVap5sMS7OvRBKvB:-OAZNVaq9sXdi_8CVzYL:b-uqy1vr) ([raw file](https://github.com/sillsdev/web-xforge/blob/9dfa067534ae2d1170a92c0c4bd66b1c0348fe56/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L1335)):*
> ```Smalltalk
>     /// <returns>The updated <paramref name="additionalTrainingData"/>.</returns>
>     /// <remarks>This can be mocked in unit tests.</remarks>
>     protected internal virtual async Task<ServalAdditionalTrainingData?> SyncAdditionalTrainingData(
> ```

It seems that this method is really doing two separate things. If the buildConfig.TrainingDataFiles exists, then we get it and update the parallel corpus. However, if it trainingDataFiles is empty, then we delete the parallel corpus and return null. Would it be more clear to split this into two methods have the caller can decide which one to call?



_Code quote:_
```Smalltalk
    protected internal virtual async Task<ServalAdditionalTrainingData?> SyncAdditionalTrainingData(
```
___
*[`test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs` line 129 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-OAZW2od69sARSP4RnI2:-OAZW2oe-qhjiz-hfmfA:b-jp4epe) ([raw file](https://github.com/sillsdev/web-xforge/blob/9dfa067534ae2d1170a92c0c4bd66b1c0348fe56/test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs#L129)):*
> ```Smalltalk
>         Assert.IsNull(env.ProjectSecrets.Get(Project02).ServalData!.PreTranslationErrorMessage);
>         Assert.IsNull(env.ProjectSecrets.Get(Project01).ServalData!.PreTranslationJobId);
>         Assert.IsNull(env.ProjectSecrets.Get(Project02).ServalData!.PreTranslationQueuedAt);
> ```

Why are we getting the project secrets for both Project01 and Project02 here? I was expecting just Project01.



_Code quote:_
```Smalltalk
        Assert.IsNull(env.ProjectSecrets.Get(Project02).ServalData!.PreTranslationErrorMessage);
        Assert.IsNull(env.ProjectSecrets.Get(Project01).ServalData!.PreTranslationJobId);
        Assert.IsNull(env.ProjectSecrets.Get(Project02).ServalData!.PreTranslationQueuedAt);
```


<!-- Sent from Reviewable.io -->

2024-11-03 22:33 UTC, pmachapman reviewed
> Can you add acceptance tests to the Jira issue?

I will when the changes to Serval are finalized (and before I send to QA). I still have a few questions I am investigating on the full scope of these changes across all systems (i.e. Serval, SF Backend, previous versions of SF Frontend).

> Dismissed @github-advanced-security[bot] from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-:-OAo1YqX5k2xgjNoowZM:bapx88s)* status: 23 of 30 files reviewed, 3 unresolved discussions (waiting on @kylebuss and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 639 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-OAZ4iAD65XcGVY33p8q:-OAo2KHc1mVyuZMRtl_L:bqvfavq) ([raw file](https://github.com/sillsdev/web-xforge/blob/9dfa067534ae2d1170a92c0c4bd66b1c0348fe56/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L639)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Calling UpdateParallelCorpusAsync will update the parallelCorpusId? It doesn't seem like a good idea to do that in an async method. Can you leave a comment stating this?
</blockquote></details>

I am unsure what you mean? I have updated the code documentation to be a bit more descriptive.
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 838 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-OAZ6DMNBWqfJjEkv727:-OAo3XtN0QYRqP0m_XUR:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/9dfa067534ae2d1170a92c0c4bd66b1c0348fe56/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L838)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

I have seen this a number of times. Perhaps we would be worth creating a helper method to get the translation engine Id and keep it more readable.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 932 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-OAZ79Oi96ECdv-t-li6:-OAo5irp1M5slBtuiKjH:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/9dfa067534ae2d1170a92c0c4bd66b1c0348fe56/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L932)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

A better message would be "Failed to create a translation engine"
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 1335 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-OAZNVap5sMS7OvRBKvB:-OAo66CL8rDnod6v463X:b75z1e0) ([raw file](https://github.com/sillsdev/web-xforge/blob/9dfa067534ae2d1170a92c0c4bd66b1c0348fe56/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L1335)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

It seems that this method is really doing two separate things. If the buildConfig.TrainingDataFiles exists, then we get it and update the parallel corpus. However, if it trainingDataFiles is empty, then we delete the parallel corpus and return null. Would it be more clear to split this into two methods have the caller can decide which one to call?
</blockquote></details>

My thinking is whether it was creating, updating, or deleting, it would be keeping the data in sync between Serval, and so named this function "SyncAdditionalTrainingData". I have updated the method code documentation to make this a bit clearer.
___
*[`test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs` line 129 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-OAZW2od69sARSP4RnI2:-OAo7EUDCirdH7qfbwyn:b-5on0jr) ([raw file](https://github.com/sillsdev/web-xforge/blob/9dfa067534ae2d1170a92c0c4bd66b1c0348fe56/test/SIL.XForge.Scripture.Tests/Services/MachineProjectServiceTests.cs#L129)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Why are we getting the project secrets for both Project01 and Project02 here? I was expecting just Project01.
</blockquote></details>

Fixed. Good spotting - thank you!


<!-- Sent from Reviewable.io -->

2024-11-04 17:36 UTC, RaymondLuong3 reviewed
Sounds good. I will wait for the acceptance tests before giving the full approval.

> Reviewed 4 of 7 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-:-OAsEq0M7yXLCGeDcrYY:bnbhfya)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 639 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-OAZ4iAD65XcGVY33p8q:-OAsBrfv8Bkf6nJ4aEOg:b-5dst4v) ([raw file](https://github.com/sillsdev/web-xforge/blob/9dfa067534ae2d1170a92c0c4bd66b1c0348fe56/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L639)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

I am unsure what you mean? I have updated the code documentation to be a bit more descriptive.
</blockquote></details>

Right, what I mean is that we can run into problems when we use asynchronous code to update parameters provided to the method since other threads could depend on the value of that parameter if my understanding is correct. Since this is awaited, it should be fine. Thanks for the comments.
___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 1335 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-OAZNVap5sMS7OvRBKvB:-OAsCYan6Z05vwaMw5KQ:b-lfepnr) ([raw file](https://github.com/sillsdev/web-xforge/blob/9dfa067534ae2d1170a92c0c4bd66b1c0348fe56/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L1335)):*
<details><summary><i>Previously, pmachapman (Peter Chapman) wrote…</i></summary><blockquote>

My thinking is whether it was creating, updating, or deleting, it would be keeping the data in sync between Serval, and so named this function "SyncAdditionalTrainingData". I have updated the method code documentation to make this a bit clearer.
</blockquote></details>

Right, that does make sense when you think of Sync that way. Thanks for the additional comment.


<!-- Sent from Reviewable.io -->

2024-11-04 18:13 UTC, pmachapman reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2825)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

___
*[`src/SIL.XForge.Scripture/Services/MachineProjectService.cs` line 639 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-OAZ4iAD65XcGVY33p8q:-OAsM4MQ87T3PAh_33_j:blywqvd) ([raw file](https://github.com/sillsdev/web-xforge/blob/9dfa067534ae2d1170a92c0c4bd66b1c0348fe56/src/SIL.XForge.Scripture/Services/MachineProjectService.cs#L639)):*
> Right, what I mean is that we can run into problems when we use asynchronous code to update parameters provided to the method since other threads could depend on the value of that parameter if my understanding is correct.

Yes, your understanding is correct. This is why, for example, you cannot have a `ref` parameter in an `async` method. Good thinking!


<!-- Sent from Reviewable.io -->

2024-11-25 23:02 UTC, RaymondLuong3 reviewed
> Reviewed 1 of 3 files at r6, 19 of 19 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2825)* status: all files reviewed, 2 unresolved discussions (waiting on @pmachapman)

___
*[`tools/ServalDownloader/Program.cs` line 93 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-OC_YiT47MRqjH0_L_8u:-OC_YiT47MRqjH0_L_8v:bdgz7oh) ([raw file](https://github.com/sillsdev/web-xforge/blob/b6e99ff2ff82ab322fc15ac45c394aba65be0ed6/tools/ServalDownloader/Program.cs#L93)):*
> ```Smalltalk
>             // Create the source directory
>             string sourcePath = Path.Combine(parallelCorpusPath, "source");
>             Directory.CreateDirectory(sourcePath);
> ```

Should this be moved outside the loop?



_Code quote:_
```Smalltalk
            // Create the source directory
            string sourcePath = Path.Combine(parallelCorpusPath, "source");
            Directory.CreateDirectory(sourcePath);
```
___
*[`tools/ServalDownloader/Program.cs` line 117 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-OC_YmpC44AwUNOW9AWj:-OC_YmpD88siMH1A5aSE:bx7dcud) ([raw file](https://github.com/sillsdev/web-xforge/blob/b6e99ff2ff82ab322fc15ac45c394aba65be0ed6/tools/ServalDownloader/Program.cs#L117)):*
> ```Smalltalk
>             // Create the target directory
>             string targetPath = Path.Combine(parallelCorpusPath, "target");
>             Directory.CreateDirectory(targetPath);
> ```

Could this be moved outside the loop?



_Code quote:_
```Smalltalk
            // Create the target directory
            string targetPath = Path.Combine(parallelCorpusPath, "target");
            Directory.CreateDirectory(targetPath);
```


<!-- Sent from Reviewable.io -->

2024-11-26 17:30 UTC, pmachapman reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2825)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)

___
*[`tools/ServalDownloader/Program.cs` line 93 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-OC_YiT47MRqjH0_L_8u:-OCdWFcC6pbgJWgeW7Ep:b-ioxi27) ([raw file](https://github.com/sillsdev/web-xforge/blob/b6e99ff2ff82ab322fc15ac45c394aba65be0ed6/tools/ServalDownloader/Program.cs#L93)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Should this be moved outside the loop?
</blockquote></details>

Done. Thank you!
___
*[`tools/ServalDownloader/Program.cs` line 117 at r7](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-OC_YmpC44AwUNOW9AWj:-OCdWRUF6SdUrR96Umpk:b-ioxi27) ([raw file](https://github.com/sillsdev/web-xforge/blob/b6e99ff2ff82ab322fc15ac45c394aba65be0ed6/tools/ServalDownloader/Program.cs#L117)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Could this be moved outside the loop?
</blockquote></details>

Done. Thank you!


<!-- Sent from Reviewable.io -->

2024-11-26 23:43 UTC, RaymondLuong3 approved these changes
Everything looks good. I was able to follow the acceptance tests on the issue and existing features continued to work as expected. I am moving this to ready to test. Thanks Peter!

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-:-OCegJMfBDdw3VSUdnyi:btahbtb)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)



<!-- Sent from Reviewable.io -->

2024-11-26 23:47 UTC, pmachapman commented
@RaymondLuong3 This PR is not yet ready for testing, as I am awaiting an update to Serval QA.

2024-11-27 17:22 UTC, RaymondLuong3 commented
Thanks Peter, sounds good.

2024-12-06 21:42 UTC, RaymondLuong3 commented
I haven't had any luck trying to generate a draft on this branch. It seems that something may have changed on the Serval client when updating the corpora using the ServalCorpora Client.
![image](https://github.com/user-attachments/assets/2f05e992-b99e-4d99-b699-432b7f344e70)

2024-12-08 20:33 UTC, pmachapman commented
> I haven't had any luck trying to generate a draft on this branch. It seems that something may have changed on the Serval client when updating the corpora using the ServalCorpora Client.

@RaymondLuong3 That error looks like it was caused by the update to the Serval API. I have updated the Serval.Client library to the latest version (1.8.4), which should resolve the issue for you.

2024-12-09 21:06 UTC, RaymondLuong3 approved these changes
The latest version of Serval.Client doesn't produce the error I was seeing and I could successfully generate a draft. Thanks!

> Reviewed 12 of 19 files at r9, 8 of 9 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2825#-:-ODhERU7AFJFISWhCJ28:bday4un)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pmachapman)



<!-- Sent from Reviewable.io -->

2024-12-16 16:33 UTC, merged