SF-3093 Allow adding draft to a book when project plans are used
sillsdev/web-xforge pull request #2865
Opened 2024-11-26 18:37 UTC by RaymondLuong3

When using a project plan, it is possible that a user can have permission on all books and automatic permissions on some books. When that happens, SF incorrectly calculates book level permissions. This change updates our permissions calculations to correctly give permission when automatic book permissions are set.

2024-11-26 21:45 UTC, kylebuss requested changes
Thanks for researching and working on this. A couple comments.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2865#-:-OCeQtjA9ijhSILfCrMa:bbjue1c)* status: all files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 886 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2865#-OCeMfy5BpIAPLQlhiNu:-OCeMfy6CaCU2iUoX8p2:b-9tu1c4) ([raw file](https://github.com/sillsdev/web-xforge/blob/ca131946955da117f896a1bfdd36eee2a71d3e81/src/SIL.XForge.Scripture/Services/ParatextService.cs#L886)):*
> ```Smalltalk
>                         );
>                         // Check if they can edit all books or the specified book
>                         if (scrText.Permissions.CanEditAllBooks(userName) || editable.Contains(book))
> ```

Should this be `(editable?.Contains(book) ?? false)` in the event `GetEditableBooks` returns an empty IEnumerable?



_Code quote:_
```Smalltalk
editable.Contains(book)
```
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs` line 402 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2865#-OCeQUdL4XkYJoWc0Nqj:-OCeQUdL4XkYJoWc0Nqk:b-2bguuo) ([raw file](https://github.com/sillsdev/web-xforge/blob/ca131946955da117f896a1bfdd36eee2a71d3e81/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L402)):*
> ```Smalltalk
>         );
>         string[] expected = [TextInfoPermission.Write, TextInfoPermission.None, TextInfoPermission.None];
>         Assert.That(permissions.Values, Is.EquivalentTo(expected));
> ```

We should also assert that Mark is granted the correct permissions automatically as well.



_Code quote:_
```Smalltalk
Assert.That(permissions.Values, Is.EquivalentTo(expected));
```


<!-- Sent from Reviewable.io -->

2024-11-26 22:08 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2865)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @kylebuss)

___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 886 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2865#-OCeMfy5BpIAPLQlhiNu:-OCeVw4i8NzNuz815sQW:bbxwvj2) ([raw file](https://github.com/sillsdev/web-xforge/blob/ca131946955da117f896a1bfdd36eee2a71d3e81/src/SIL.XForge.Scripture/Services/ParatextService.cs#L886)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

Should this be `(editable?.Contains(book) ?? false)` in the event `GetEditableBooks` returns an empty IEnumerable?
</blockquote></details>

Even with the empty enumable, we don't need to do a null check or null coalescing. That will just return false.
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs` line 402 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2865#-OCeQUdL4XkYJoWc0Nqj:-OCeW8R34aY5-qww19lB:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/ca131946955da117f896a1bfdd36eee2a71d3e81/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L402)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

We should also assert that Mark is granted the correct permissions automatically as well.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-27 13:08 UTC, kylebuss requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2865)* status: all files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 886 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2865#-OCeMfy5BpIAPLQlhiNu:-OChf8bAEOHLkzhiDuP4:b-o27uft) ([raw file](https://github.com/sillsdev/web-xforge/blob/ca131946955da117f896a1bfdd36eee2a71d3e81/src/SIL.XForge.Scripture/Services/ParatextService.cs#L886)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Even with the empty enumable, we don't need to do a null check or null coalescing. That will just return false.
</blockquote></details>

Empty was the wrong word choice. The original code gives the impression the `GetEditableBooks` function can return `null`.  Likely when a user has not been granted manual or automatic permission to any books. 
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs` line 402 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2865#-OCeQUdL4XkYJoWc0Nqj:-OChiZZ_6P-W5Qp66khh:b-j53osg) ([raw file](https://github.com/sillsdev/web-xforge/blob/ca131946955da117f896a1bfdd36eee2a71d3e81/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L402)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Perhaps I'm misunderstanding the expected results here. I would have expected Mark to return [Write, Write, None] not [Write, None, None]. The values are for [Project, Book, Chapter], are they not? 


<!-- Sent from Reviewable.io -->

2024-11-27 16:01 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2865)* status: all files reviewed, 2 unresolved discussions (waiting on @kylebuss)

___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 886 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2865#-OCeMfy5BpIAPLQlhiNu:-OCiL8m6CWVLFJdRQhC0:b-gtw4tn) ([raw file](https://github.com/sillsdev/web-xforge/blob/ca131946955da117f896a1bfdd36eee2a71d3e81/src/SIL.XForge.Scripture/Services/ParatextService.cs#L886)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

Empty was the wrong word choice. The original code gives the impression the `GetEditableBooks` function can return `null`.  Likely when a user has not been granted manual or automatic permission to any books.
</blockquote></details>

Actually a null check is not necessary. The returned value will always be an IEnumerable and never null. Do you have access to the Paratext code? It might be good for you to have.
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs` line 402 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2865#-OCeQUdL4XkYJoWc0Nqj:-OCiLN9k94CZsD68c13L:b-21zalh) ([raw file](https://github.com/sillsdev/web-xforge/blob/ca131946955da117f896a1bfdd36eee2a71d3e81/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L402)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

Perhaps I'm misunderstanding the expected results here. I would have expected Mark to return [Write, Write, None] not [Write, None, None]. The values are for [Project, Book, Chapter], are they not?
</blockquote></details>

The permissions are for the 3 users on the project. User1, User2 and User5. Only User1 has a paratext role on the project so only user! has text permission.


<!-- Sent from Reviewable.io -->

2024-11-27 20:09 UTC, kylebuss requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2865)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 886 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2865#-OCeMfy5BpIAPLQlhiNu:-OCiWSSR4aroYBOKzZbK:bnijpe9) ([raw file](https://github.com/sillsdev/web-xforge/blob/ca131946955da117f896a1bfdd36eee2a71d3e81/src/SIL.XForge.Scripture/Services/ParatextService.cs#L886)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Actually a null check is not necessary. The returned value will always be an IEnumerable and never null. Do you have access to the Paratext code? It might be good for you to have.
</blockquote></details>

I have the Paratext code decompiled.
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs` line 402 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2865#-OCeQUdL4XkYJoWc0Nqj:-OCjAV65EGS0g0bJxLcq:b-cmcj7j) ([raw file](https://github.com/sillsdev/web-xforge/blob/ca131946955da117f896a1bfdd36eee2a71d3e81/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L402)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

The permissions are for the 3 users on the project. User1, User2 and User5. Only User1 has a paratext role on the project so only user! has text permission.
</blockquote></details>

Gotcha, I was a bit confused with the first `setPermissions` being for book 0 and testing Matthew (book 40). 

I wonder if we need to add a test for when a user only has automatic permission for a book.


<!-- Sent from Reviewable.io -->

2024-11-27 21:53 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2865)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @kylebuss)

___
*[`src/SIL.XForge.Scripture/Services/ParatextService.cs` line 886 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2865#-OCeMfy5BpIAPLQlhiNu:-OCjbEnWALhmTC2G2QJv:bza9ute) ([raw file](https://github.com/sillsdev/web-xforge/blob/ca131946955da117f896a1bfdd36eee2a71d3e81/src/SIL.XForge.Scripture/Services/ParatextService.cs#L886)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

I have the Paratext code decompiled.
</blockquote></details>

Nice, that will probably do for now, but we will want to get you onto the Paratext repo at some point.
___
*[`test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs` line 402 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2865#-OCeQUdL4XkYJoWc0Nqj:-OCjbQqr3PkCizFV51hx:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/ca131946955da117f896a1bfdd36eee2a71d3e81/test/SIL.XForge.Scripture.Tests/Services/ParatextServiceTests.cs#L402)):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

Gotcha, I was a bit confused with the first `setPermissions` being for book 0 and testing Matthew (book 40). 

I wonder if we need to add a test for when a user only has automatic permission for a book.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-27 21:55 UTC, kylebuss approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2865#-:-OCjbnhtAOuRKvvy3O5B:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2024-12-05 16:22 UTC, merged