SF-3095 Fix sync progress display when loading a resource.
sillsdev/web-xforge pull request #2873
Opened 2024-11-27 19:27 UTC by kylebuss

This PR fixes how the sync progress is displayed in the tab resource dialog to prevent overlapping of text. Rather than optionally hiding the new sync info, this moves the sync progress into the space where the "Loading..." message previously appeared during the sync progress. This allows users to have the same visual insight into the status of thy sync across the app.

2024-11-27 19:37 UTC, kylebuss commented
I did notice the sync-progress component is using SubscriptionDisposable. Let me know if you want me to address removing that with this PR?


<!-- Sent from Reviewable.io -->

2024-11-29 17:26 UTC, RaymondLuong3 requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2873)* status: all files reviewed, 1 unresolved discussion (waiting on @kylebuss)

___
*[a discussion](https://reviewable.io/reviews/sillsdev/web-xforge/2873#-OCj70gi0pVbMKW-wFl4:-OCswsQf7O0YojUHIeIT:bzggjq8) (no related file):*
<details><summary><i>Previously, kylebuss (Kyle Buss) wrote…</i></summary><blockquote>

I did notice the sync-progress component is using SubscriptionDisposable. Let me know if you want me to address removing that with this PR?
</blockquote></details>

My preference is still to hide the sync messages and keep just the progress bar at the top of the dialog as per the original design. The purpose of the dialog is to load a resource. The user is not expecting the extra info about the progress of the sync.


<!-- Sent from Reviewable.io -->

2024-12-02 16:59 UTC, kylebuss reviewed
Reverted editor resource tab dialog .html back and updated .scss to only show the sync progress bar when loading a resource.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2873#-:-OD7IiuN4U5Iq2rC2WyZ:bfe4j0p)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2024-12-02 18:42 UTC, RaymondLuong3 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2873#-:-OD7fSHu97WT8NmMPo4E:bg7igkv)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kylebuss)



<!-- Sent from Reviewable.io -->

2024-12-02 20:41 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2873)* status: all files reviewed, 1 unresolved discussion (waiting on @kylebuss)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-resource-dialog/editor-tab-add-resource-dialog.component.scss` line 29 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2873#-OD84wT-1iLhm9jLyNAs:-OD84wT-1iLhm9jLyNAt:btws9vh) ([raw file](https://github.com/sillsdev/web-xforge/blob/013f7ca5b67f12c47f89f0859a69e83bec1b3b11/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-resource-dialog/editor-tab-add-resource-dialog.component.scss#L29)):*
> ```SCSS
>       & .sync-header,
>       .sync-status {
>         display: none !important;
> ```

What happens when someone makes a small change to the sync progress component, like renaming one of these classes, or adding another element? 

I think a better option would be to add an option to the SyncProgressComponent like `hideStatus`, or `progressBarMode`. Then this becomes a supported mode of the sync progress component. If it's in Storybook, the progress bar mode would be one of the stories.


<!-- Sent from Reviewable.io -->

2024-12-02 21:40 UTC, kylebuss reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2873)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @Nateowami and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-resource-dialog/editor-tab-add-resource-dialog.component.scss` line 29 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2873#-OD84wT-1iLhm9jLyNAs:-OD8J54WBrgqysgtVjvI:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/013f7ca5b67f12c47f89f0859a69e83bec1b3b11/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-resource-dialog/editor-tab-add-resource-dialog.component.scss#L29)):*
<details><summary><i>Previously, Nateowami wrote…</i></summary><blockquote>

What happens when someone makes a small change to the sync progress component, like renaming one of these classes, or adding another element? 

I think a better option would be to add an option to the SyncProgressComponent like `hideStatus`, or `progressBarMode`. Then this becomes a supported mode of the sync progress component. If it's in Storybook, the progress bar mode would be one of the stories.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-02 21:55 UTC, RaymondLuong3 approved these changes
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2873)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)



<!-- Sent from Reviewable.io -->

2024-12-02 22:06 UTC, Nateowami reviewed
This looks a lot better. Thanks.

> Reviewed 3 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2873#-:-OD8PAsm3mAnFm2syvvl:b-d4axck)* status: all files reviewed, 1 unresolved discussion (waiting on @kylebuss)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-resource-dialog/editor-tab-add-resource-dialog.component.scss` line 25 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2873#-OD8MlZb6G6f0gCT8MpO:-OD8MlZb6G6f0gCT8MpP:b-wvk1qe) ([raw file](https://github.com/sillsdev/web-xforge/blob/874d062856535809e514c804b098ec464b9ff605/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-resource-dialog/editor-tab-add-resource-dialog.component.scss#L25)):*
> ```SCSS
>   position: relative !important;
> 
>   app-sync-progress {
> ```

I can't see any reason this should be inside of `::ng-deep .editor-tab-add-resource-dialog`.


<!-- Sent from Reviewable.io -->

2024-12-03 03:04 UTC, kylebuss commented
*[`src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-resource-dialog/editor-tab-add-resource-dialog.component.scss` line 25 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/2873#-OD8MlZb6G6f0gCT8MpO:-OD9T8cWA2dEyEuT4XMn:b-l1t08) ([raw file](https://github.com/sillsdev/web-xforge/blob/874d062856535809e514c804b098ec464b9ff605/src/SIL.XForge.Scripture/ClientApp/src/app/translate/editor/tabs/editor-tab-add-resource-dialog/editor-tab-add-resource-dialog.component.scss#L25)):*
<details><summary><i>Previously, Nateowami wrote…</i></summary><blockquote>

I can't see any reason this should be inside of `::ng-deep .editor-tab-add-resource-dialog`.
</blockquote></details>

I'll take a further look, but not having it here displays the progress bar with 2em padding at the top.


<!-- Sent from Reviewable.io -->

2024-12-04 20:42 UTC, RaymondLuong3 requested changes
Nice clean-up. Just one more suggestion and we can get this moving along.

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2873#-:-ODIP63-8cJMs4_mAT3C:b-fg2hnw)* status: all files reviewed, 3 unresolved discussions (waiting on @kylebuss and @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.html` line 2 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2873#-ODIOUHM0n_8Dc2AjUud:-ODIOUHM0n_8Dc2AjUue:b-jidoh0) ([raw file](https://github.com/sillsdev/web-xforge/blob/b6401382da1072bc2d5fec28735c84308dae4cdc/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.html#L2)):*
> ```HTML
> @if (showSyncStatus) {
>   <div *transloco="let t; read: 'sync'">
> ```

You can move all of this into a top level `div` and then add a `row-gap: 2em` and `display: flex` rules to the style sheet for the top level div.



_Code quote:_
```HTML
@if (showSyncStatus) {
  <div *transloco="let t; read: 'sync'">
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.scss` line 25 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2873#-ODINrrF5MR57_ArOuFk:-ODINrrF5MR57_ArOuFl:b-f0gxu8) ([raw file](https://github.com/sillsdev/web-xforge/blob/b6401382da1072bc2d5fec28735c84308dae4cdc/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.scss#L25)):*
> ```SCSS
>   &.pad-status {
>     padding-bottom: 2rem;
>   }
> ```

This is not a bad solution, but the better approach is to add a gap between elements. If we get into the habit of adding gaps between elements, I think in the end our code and 'scss' will be cleaner.



_Code quote:_
```SCSS
  &.pad-status {
    padding-bottom: 2rem;
  }
```


<!-- Sent from Reviewable.io -->

2024-12-04 20:43 UTC, RaymondLuong3 requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2873)* status: all files reviewed, 3 unresolved discussions (waiting on @kylebuss and @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.html` line 2 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2873#-ODIOUHM0n_8Dc2AjUud:-ODIPIbY-jCLcDqZ4jc2:b-hzdx2c) ([raw file](https://github.com/sillsdev/web-xforge/blob/b6401382da1072bc2d5fec28735c84308dae4cdc/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.html#L2)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

You can move all of this into a top level `div` and then add a `row-gap: 2em` and `display: flex` rules to the style sheet for the top level div.
</blockquote></details>

Oh, and you'll need to set the `flex-direction: column` rule too.


<!-- Sent from Reviewable.io -->

2024-12-04 21:31 UTC, kylebuss reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2873)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.scss` line 25 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2873#-ODINrrF5MR57_ArOuFk:-ODI_K8jBPnkpXQDWXvl:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/b6401382da1072bc2d5fec28735c84308dae4cdc/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync.component.scss#L25)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

This is not a bad solution, but the better approach is to add a gap between elements. If we get into the habit of adding gaps between elements, I think in the end our code and 'scss' will be cleaner.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.html` line 2 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/2873#-ODIOUHM0n_8Dc2AjUud:-ODI_Jht2qB_C8vqbYvd:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/b6401382da1072bc2d5fec28735c84308dae4cdc/src/SIL.XForge.Scripture/ClientApp/src/app/sync/sync-progress/sync-progress.component.html#L2)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Oh, and you'll need to set the `flex-direction: column` rule too.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-04 21:44 UTC, RaymondLuong3 approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2873)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)



<!-- Sent from Reviewable.io -->

2024-12-04 21:45 UTC, merged