Add global notices component with upcoming downtime message
sillsdev/web-xforge pull request #2888
Opened 2024-12-04 21:55 UTC by Nateowami

This is based off the recent downtime notice that was pushed as a hotfix to live.

This branch:
- Adds a component that shows up globally and can list notices
- Adds a single notice about upcoming downtime (but keeps it hidden)

![](https://github.com/user-attachments/assets/cb5c741a-b084-4647-88d7-a5de8714a9eb)

This is mainly about creating a slot in the UI for showing notices. There are a lot of options for how we might be able to load these notices in the future.

One important aspect of this change is that it adds localization strings for an "upcoming maintenance" notice. By getting this into the project, we can hopefully have it localized before downtime is going to occur, and reuse it as many times as needed.

2024-12-04 22:42 UTC, RaymondLuong3 requested changes
I think we can do better than the warning symbol for maintenance related notices. Do you think it would be worth setting the icon from the parent component? Obviously as the need arises we can make more changes so it's not a big deal for this PR.

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2888#-:-ODIpBqm4Y6rk5XvKBQH:b-xbwvsz)* status: all files reviewed, 3 unresolved discussions (waiting on @marksvc and @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json` line 351 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2888#-ODInPUN3pgsIWnIkue0:-ODInPUN3pgsIWnIkue1:b-d6qryc) ([raw file](https://github.com/sillsdev/web-xforge/blob/06db31cba51b007dbce631a1b2bc3ff9cc63d61f/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json#L351)):*
> ```JSON
>     "learn_more": "Learn more",
>     "minute_range": "{{ min }} to {{ max }} minutes",
>     "upcoming_maintenance": "Scripture Forge will be down for maintenance for about {{ duration }} hours starting at {{ startTime }}."
> ```

You can remove the 'hours' string since the duration already has the time unit info.



_Code quote:_
```JSON
    "upcoming_maintenance": "Scripture Forge will be down for maintenance for about {{ duration }} hours starting at {{ startTime }}."
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/global-notices/global-notices.component.ts` line 7 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2888#-ODImPHW2fcLu9HmEeky:-ODImPHW2fcLu9HmEekz:b-kbeix7) ([raw file](https://github.com/sillsdev/web-xforge/blob/06db31cba51b007dbce631a1b2bc3ff9cc63d61f/src/SIL.XForge.Scripture/ClientApp/src/app/shared/global-notices/global-notices.component.ts#L7)):*
> ```XML
> import { MatTooltipModule } from '@angular/material/tooltip';
> import { TranslocoModule } from '@ngneat/transloco';
> import { I18nService } from '../../../xforge-common/i18n.service';
> ```

You can make this the absolute path.



_Code quote:_
```XML
import { I18nService } from '../../../xforge-common/i18n.service';
```
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/global-notices/global-notices.component.ts` line 22 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2888#-ODImgAd29ypZR8uCHEx:-ODImgAd29ypZR8uCHEy:b-f89zsd) ([raw file](https://github.com/sillsdev/web-xforge/blob/06db31cba51b007dbce631a1b2bc3ff9cc63d61f/src/SIL.XForge.Scripture/ClientApp/src/app/shared/global-notices/global-notices.component.ts#L22)):*
> ```XML
> 
>   upcomingDowntime = {
>     start: new Date('2024-12-04 16:30 UTC'),
> ```

Did you want a comment about this that says "Update this"? Or maybe set "start" as a field with an "Update this" above that field.



_Code quote:_
```XML
    start: new Date('2024-12-04 16:30 UTC'),
```


<!-- Sent from Reviewable.io -->

2024-12-04 23:04 UTC, Nateowami reviewed
> I think we can do better than the warning symbol for maintenance related notices.

Do you have one to suggest?

> Do you think it would be worth setting the icon from the parent component?

The parent component is the app component. I don't think it makes sense to make it the app component's concern.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2888#-:-ODIspkDCCGeiu0P3VHl:bha2jzc)* status: 6 of 8 files reviewed, 3 unresolved discussions (waiting on @marksvc and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/global-notices/global-notices.component.ts` line 7 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2888#-ODImPHW2fcLu9HmEeky:-ODIseKq2xb15eVA_LdO:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/06db31cba51b007dbce631a1b2bc3ff9cc63d61f/src/SIL.XForge.Scripture/ClientApp/src/app/shared/global-notices/global-notices.component.ts#L7)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

You can make this the absolute path.
</blockquote></details>

Done.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/global-notices/global-notices.component.ts` line 22 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2888#-ODImgAd29ypZR8uCHEx:-ODItKnZ4IaLR4Y7Ab_7:b-e6wg6a) ([raw file](https://github.com/sillsdev/web-xforge/blob/06db31cba51b007dbce631a1b2bc3ff9cc63d61f/src/SIL.XForge.Scripture/ClientApp/src/app/shared/global-notices/global-notices.component.ts#L22)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Did you want a comment about this that says "Update this"? Or maybe set "start" as a field with an "Update this" above that field.
</blockquote></details>

*All* these properties have to be updated the next time we want to show a message. The time, estimated duration, and link to details will all be potentially different. Someone will have to manually changed showDowntimeNotice to true, so I'm not really worried that this would get forgotten.
___
*[`src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json` line 351 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2888#-ODInPUN3pgsIWnIkue0:-ODIsjhD7OsfUWI-PXUg:b5vq3ho) ([raw file](https://github.com/sillsdev/web-xforge/blob/06db31cba51b007dbce631a1b2bc3ff9cc63d61f/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json#L351)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

You can remove the 'hours' string since the duration already has the time unit info.
</blockquote></details>

:facepalm: Good catch.


<!-- Sent from Reviewable.io -->

2024-12-05 18:14 UTC, RaymondLuong3 reviewed
The construction symbol may be what we want for maintenance messages.
![image.png](https://files.reviewableusercontent.io/images/reviewable/17931130/Fiky4dPH8oUzYrH-mxtQV3rt/image.png)

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2888#-:-ODMww7685-Qh_LCdKZL:bwdlshf)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc and @Nateowami)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/global-notices/global-notices.component.html` line 6 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2888#-ODN0lZxD7Gw_5MojXYl:-ODN0lZy7DbNKvwDQP52:b47q58g) ([raw file](https://github.com/sillsdev/web-xforge/blob/725f1c54ebbb5c5835057f6cb41abbdc34b84eb5/src/SIL.XForge.Scripture/ClientApp/src/app/shared/global-notices/global-notices.component.html#L6)):*
> ```HTML
>       <div class="downtime-notice-content-wrapper">
>         <div>
>           <!-- TODO Update i18n.formatDate to specify { showTimeZone: true } once #2887 is merged -->
> ```

Looks like this can be updated now.



_Code quote:_
```HTML
          <!-- TODO Update i18n.formatDate to specify { showTimeZone: true } once #2887 is merged -->
```


<!-- Sent from Reviewable.io -->

2024-12-05 18:23 UTC, Nateowami reviewed
I like it. Done.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2888#-:-ODN2v4f-1KtjA25UbNK:bkoke9u)* status: 6 of 8 files reviewed, all discussions resolved (waiting on @marksvc and @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/global-notices/global-notices.component.html` line 6 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2888#-ODN0lZxD7Gw_5MojXYl:-ODN2tBg34GYZl-vVcnz:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/725f1c54ebbb5c5835057f6cb41abbdc34b84eb5/src/SIL.XForge.Scripture/ClientApp/src/app/shared/global-notices/global-notices.component.html#L6)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Looks like this can be updated now.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-05 18:38 UTC, RaymondLuong3 approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2888)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @marksvc)



<!-- Sent from Reviewable.io -->

2024-12-05 18:40 UTC, merged