SF-3114 Chapter audio only hides bottom bar if scripture text is shown
sillsdev/web-xforge pull request #2905
Opened 2024-12-12 03:38 UTC by josephmyers

This fixes an issue where "hide text" projects couldn't navigate questions on mobile, since the bottom bar is now being hidden.

So now, we don't hide the bottom bar if "hide text" is enabled. We will instead only hide the bar if the "hide text" is disabled and the chapter audio is shown. Effectively, this is when "the user opens the chapter audio."

The second case where we hide the bar remains. I did a slight refactoring to make all this clear and readable.

The original reason for the hiding behavior is still intact, that being to free up space on mobile and keep users focused on their intended task.

2024-12-12 04:03 UTC, Nateowami commented
@josephmyers Please update the PR title to conform to the guidelines in [CONTRIBUTING.md](https://github.com/sillsdev/web-xforge/blob/master/CONTRIBUTING.md).

I know the meaning of the title might seem obvious to you, but very often there are two completely contradictory interpretations that can't be differentiated without knowing what the original problem was.

> Chapter audio only hides bottom bar if scripture text is shown

Upon reading this title, my first thought was that the bottom bar wasn't being hidden in a situation where it should, but it sounds like it's the exact opposite. Sometimes people create PRs that describe the problem (e.g. #1539), but you can't tell whether a title is describing the problem or the solution without context. On the other hand, if you always use imperative mood, there isn't nearly as much room for ambiguity, and it's easier to read a list of commit messages that have the same grammatical structure.

2024-12-12 17:33 UTC, RaymondLuong3 requested changes
I agree, the commit message would be better if it describe what was done to the repo. Something like "Fix bottom nav hidden if hide scripture text enabled" describes the problem that was resolved without being ambiguous. 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2905#-:-ODvuOte8AbG7di6xFHc:b-y3df1m)* status: all files reviewed, 1 unresolved discussion (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts` line 259 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2905#-ODvtfiaD6ntfKMZtx8t:-ODvtfiaD6ntfKMZtx8u:b-m4d79b) ([raw file](https://github.com/sillsdev/web-xforge/blob/e81ecf76c1ae1f43bff12dc5fd3be6eaca863cca/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts#L259)):*
> ```XML
>   }
> 
>   get textboxIsShown(): boolean {
> ```

Nit: This could be private.



_Code quote:_
```XML
  get textboxIsShown(): boolean {
```


<!-- Sent from Reviewable.io -->

2024-12-16 02:36 UTC, josephmyers reviewed
To be fair, the commit message does describe what was done to the repo. Nathaniel's complaint is that you could interpret that message differently, I guess as if my checkin were saying that is the problem.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2905#-:-OECJPDY1jKH5eudzRcn:banp1wr)* status: all files reviewed, 1 unresolved discussion (waiting on @josephmyers)



<!-- Sent from Reviewable.io -->

2024-12-16 02:49 UTC, josephmyers reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2905)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts` line 259 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2905#-ODvtfiaD6ntfKMZtx8t:-OECLUCz8Scjz6I0cXgK:bbm9wp8) ([raw file](https://github.com/sillsdev/web-xforge/blob/e81ecf76c1ae1f43bff12dc5fd3be6eaca863cca/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts#L259)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Nit: This could be private.
</blockquote></details>

You could, but I don't see a need to. The only thing I could think of is maybe API clutter, but we're way beyond that for this class.

Readonly properties like this are almost always valuable (or neutral) to expose. It's the modifiable fields, e.g. simple boolean flags, that can be harmful when exposed. It's impossible for this property to cause a bug (unless of course there's a bug in the logic here that I don't see).


<!-- Sent from Reviewable.io -->

2024-12-16 16:30 UTC, RaymondLuong3 approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2905)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts` line 259 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2905#-ODvtfiaD6ntfKMZtx8t:-OEFIB4mCaQraTdQ7xpP:b-pwo0ir) ([raw file](https://github.com/sillsdev/web-xforge/blob/e81ecf76c1ae1f43bff12dc5fd3be6eaca863cca/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts#L259)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

You could, but I don't see a need to. The only thing I could think of is maybe API clutter, but we're way beyond that for this class.

Readonly properties like this are almost always valuable (or neutral) to expose. It's the modifiable fields, e.g. simple boolean flags, that can be harmful when exposed. It's impossible for this property to cause a bug (unless of course there's a bug in the logic here that I don't see).
</blockquote></details>

That is a far point. Would it not be possible to assign the getter to be something else like `() => true`? and then the getter would not work? I assume not but typescript lets you do unexpected things sometimes =P


<!-- Sent from Reviewable.io -->

2024-12-16 21:01 UTC, josephmyers reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2905)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts` line 259 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2905#-ODvtfiaD6ntfKMZtx8t:-OEGGR1u1DYA7AEwwnfm:b82kxat) ([raw file](https://github.com/sillsdev/web-xforge/blob/e81ecf76c1ae1f43bff12dc5fd3be6eaca863cca/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts#L259)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

That is a far point. Would it not be possible to assign the getter to be something else like `() => true`? and then the getter would not work? I assume not but typescript lets you do unexpected things sometimes =P
</blockquote></details>

Yes, that would be really weird. Maybe too weird even for TS!


<!-- Sent from Reviewable.io -->

2024-12-18 19:45 UTC, merged