SF-3136 Upgrade to Quill v2
sillsdev/web-xforge pull request #2925
Opened 2024-12-22 22:51 UTC by siltomato

https://slab.com/blog/announcing-quill-2-0/
https://github.com/slab/quill/releases/tag/v2.0.0

Quill v1.3.7 (our current version) was released in September 2019, and it appears that all ongoing work, including bug fixes, is in the v2 branch.

2024-12-23 05:51 UTC, josephmyers requested changes
I've been playing around with this for the past hour or so, and I haven't seen any bugs with the upgrade, not even the highlight on restore bug I just fixed. And the code changes are much, much cleaner than I was expecting. Good job!

> Reviewed 36 of 36 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2925#-:-OEm3NC12Xk9LhJjHw_B:b8ebpdn)* status: all files reviewed, 1 unresolved discussion (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts` line 729 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2925#-OElt_AD5iLH5UUjLku0:-OElt_AD5iLH5UUjLku1:b-p1a7to) ([raw file](https://github.com/sillsdev/web-xforge/blob/1bca82f5094ecc2fa90120cae2168fa8f3f208b5/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts#L729)):*
> ```XML
>         this.quill.scrollingContainer.scrollTop = scrollTop;
>         this.quill.focus();
>       }, 1);
> ```

This appears to still work as before, without all this extra code. Good job simplifying!
___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts` line 39 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2925#-OElqe_FAW1DqssE1qD1:-OElqe_G9Td1CQCxbZjm:bongkot) ([raw file](https://github.com/sillsdev/web-xforge/blob/304001ad219e22cb872c28e085ed076b325115a3/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts#L39)):*
> ```XML
> 
>     if (typeof op.retain.length === 'number') {
>       return op.retain.length;
> ```

I'm not seeing any mention of the `.length` format in their docs, though that may not mean much. It's all `{ retain: 5 }`. Did they add this as a new possibility? How do I get here with a breakpoint?


<!-- Sent from Reviewable.io -->

2024-12-23 18:02 UTC, siltomato reviewed
Thanks, hopefully it'll be a smooth upgrade.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2925#-:-OEoeqBv9qJ2PBJZMITC:b-bzyr8g)* status: 35 of 36 files reviewed, 1 unresolved discussion (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts` line 39 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/2925#-OElqe_FAW1DqssE1qD1:-OEoe1ja1csw04XcwaMP:b-d597ms) ([raw file](https://github.com/sillsdev/web-xforge/blob/304001ad219e22cb872c28e085ed076b325115a3/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts#L39)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

I'm not seeing any mention of the `.length` format in their docs, though that may not mean much. It's all `{ retain: 5 }`. Did they add this as a new possibility? How do I get here with a breakpoint?
</blockquote></details>

Good catch.  The typescript def for `Op` threw me off, and I hallucinated a `length` prop from looking at the docs.

Changed to throw an error if the type of `retain` is not a number.


<!-- Sent from Reviewable.io -->

2024-12-26 00:49 UTC, josephmyers requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2925)* status: all files reviewed, 2 unresolved discussions (waiting on @siltomato)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts` line 854 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2925#-OF-QZcDBowPQ4BUDZfI:-OF-QZcE66AoEz8Ualv1:b-lw0luu) ([raw file](https://github.com/sillsdev/web-xforge/blob/b511e1e29bbeeb406270f080ffeda237cec904c7/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts#L854)):*
> ```XML
>         }
>       } else if (op.retain != null) {
>         curIndex += op.retain as number;
> ```

Did you have a reason for changing this? It should use the method you created for retain, so that we maintain consistent behavior:
`curIndex += getRetainCount(op);`


<!-- Sent from Reviewable.io -->

2024-12-27 19:39 UTC, siltomato reviewed
Also added null coalesce to 0 in some places for the returned result of `getRetainCount`.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2925#-:-OF8bv92EqejpGRkI07T:b-rjappp)* status: 32 of 36 files reviewed, 2 unresolved discussions (waiting on @josephmyers)

___
*[`src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts` line 854 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/2925#-OF-QZcDBowPQ4BUDZfI:-OF8blR77-kJEEZktEJe:b-i92ln7) ([raw file](https://github.com/sillsdev/web-xforge/blob/b511e1e29bbeeb406270f080ffeda237cec904c7/src/SIL.XForge.Scripture/ClientApp/src/app/shared/text/quill-scripture.ts#L854)):*
<details><summary><i>Previously, josephmyers wrote…</i></summary><blockquote>

Did you have a reason for changing this? It should use the method you created for retain, so that we maintain consistent behavior:
`curIndex += getRetainCount(op);`
</blockquote></details>

No reason.  Just forgot to change it back when I was deciding whether to scrap the function.


<!-- Sent from Reviewable.io -->

2024-12-30 02:18 UTC, josephmyers approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/2925#-:-OFKLwse3GzkdVGXvzrj:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @siltomato)



<!-- Sent from Reviewable.io -->

2025-01-02 23:44 UTC, merged