SF-978 - Cache audio on answers when played
sillsdev/web-xforge pull request #800
Opened 2020-09-14 02:07 UTC by nigel-wells

- Added `updateAnswerFileCache` to the question doc so it can be called when required
- Cache answer audio on question activation
- Cache answer audio on remote changes to a question currently being viewed
- Cache answer audio when saving an answer
- Moved update file cache subscription to now take place when a realtime doc updates offline data
- Changed realtime doc for `updateOfflineData` to `protected` so that it can be expanded in child classes
- Updated realtime query to emit the specific document that has remotely changed
- Added `get` and `getAll` to file service
- Updated checking tests to reset `mockedFileService` for each test so that `verify` is valid per test rather than over all tests
- Created tests for ensuring answer audio is cached

There was a point on the Jira task when a `user is unlikely to revisit the answer`. This can be covered in a future task that will introduce a settings page around what gets cached for offline use and what should be deleted and when.

### Acceptance tests
- _Checker_ adds an answer with audio and the audio is cached
- _Checker_ removes audio from answer and the audio is removed from cache
- _Checker_ deletes an answer with audio and the audio is removed from cache
- _Checker_ adds an answer with audio. _Admin_ does not view the question containing the answer so no audio is cached for the answer
- _Checker_ adds an answer with audio. _Admin_ views the question containing the answer and the audio is cached
- _Checker_ adds an answer with audio. _Admin_ views the question containing the answer and the audio is cached. _Checker_ removes audio from answer and audio is removed from cache for both the _Checker_ and the _Admin_
- _Checker_ adds an answer with audio. _Admin_ views the question containing the answer and the audio is cached. _Checker_ deletes their answer and audio is removed from cache for both the _Checker_ and the _Admin_
- _Checker_ adds an answer with audio. _Admin_ views the question containing the answer and the audio is cached. _Admin_ deletes the checkers answer and audio is removed from cache for both the _Checker_ and the _Admin_

2020-09-23 20:18 UTC, RaymondLuong3 reviewed
Can you rebase this branch onto master, and then it should be all ready for review.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/800#-:-MHwbFBGDBQVCeDDVWYx:bf49wvy)* status: 0 of 7 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-23 22:16 UTC, RaymondLuong3 requested changes
I rebased this onto the latest master. There are a few questions to address, but looks pretty good.

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/800#-:-MHx1K2Z7HDI19gsaEHb:bmxwewl)* status: all files reviewed, 5 unresolved discussions (waiting on @nigel-wells)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, line 353 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/800#-MHwzxElEd6WGlKidZZb:-MHwzxElEd6WGlKidZZc:b-ofqy7v) ([raw file](https://github.com/sillsdev/web-xforge/blob/409e5f3419ce5b606ac30a1ffffdb9065f033c28/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts#L353)):*
> ```
> this.questionsRemoteChangesSub = this.subscribe(this.questionsQuery.remoteDocChanges$, (qd: QuestionDoc)
> ```
If an answer on a question doc gets removed, `this.questionsQuery.remoteDocChanges` will not fire. We may have to keep the subscription the way it was, and call `updateAnswerFileCache()` on the question doc that is currently in view.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, line 629 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/800#-MHx17drCXuN15i2jxtF:-MHx17drCXuN15i2jxtG:b-okvazj) ([raw file](https://github.com/sillsdev/web-xforge/blob/409e5f3419ce5b606ac30a1ffffdb9065f033c28/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts#L629)):*
> ```
> if (this.pwaService.isOnline) {
> ```
Should this also update the file cache too?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, line 1305 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/800#-MHx0Cnl5KfiYF67hHrV:-MHx0Cnl5KfiYF67hHrW:b-9s16hl) ([raw file](https://github.com/sillsdev/web-xforge/blob/409e5f3419ce5b606ac30a1ffffdb9065f033c28/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts#L1305)):*
> ```
> it('update answer audio cache on remote update to question', fakeAsync(() => {
> ```
There may be an easy test we can add to test if `updateAnswerFileCache()` gets called if an answer with audio is removed remotely.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/models/question-doc.ts, line 68 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/800#-MHwwb936rzuwfhbPQxQ:-MHwwb936rzuwfhbPQxR:b-oez5nn) ([raw file](https://github.com/sillsdev/web-xforge/blob/409e5f3419ce5b606ac30a1ffffdb9065f033c28/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/question-doc.ts#L68)):*
> ```
> protected async updateOfflineData(force: boolean = false): Promise<void> {
> ```
Since this is mostly concerned with audio data, I would rename this `updateAnswerAudioCache` or something similar.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/models/question-doc.ts, line 75 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/800#-MHwwFTN72pQ6v61filF:-MHwwFTN72pQ6v61filG:b-861aub) ([raw file](https://github.com/sillsdev/web-xforge/blob/409e5f3419ce5b606ac30a1ffffdb9065f033c28/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/question-doc.ts#L75)):*
> ```
> this.data!.answers.find(a => a === answer) == null)
> ```
I would compare `answer.Id` with `a.Id` instead of comparing the objects.


<!-- Sent from Reviewable.io -->

2020-09-23 22:21 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/800)* status: all files reviewed, 5 unresolved discussions (waiting on @nigel-wells)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, line 353 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/800#-MHwzxElEd6WGlKidZZb:-MHx2QuT6Ed3QWosHJRE:bydezf0) ([raw file](https://github.com/sillsdev/web-xforge/blob/409e5f3419ce5b606ac30a1ffffdb9065f033c28/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts#L353)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> this.questionsRemoteChangesSub = this.subscribe(this.questionsQuery.remoteDocChanges$, (qd: QuestionDoc)
> ```
If an answer on a question doc gets removed, `this.questionsQuery.remoteDocChanges` will not fire. We may have to keep the subscription the way it was, and call `updateAnswerFileCache()` on the question doc that is currently in view.
</blockquote></details>

Actually, `this.questionsQuery.remoteDocChanges` may still fire if an answer is removed, so this may not be a problem.


<!-- Sent from Reviewable.io -->

2020-09-24 15:22 UTC, RaymondLuong3 reviewed
I saw two issues today. The first is that if a checker user is offline and they edit an answer that already has audio, the audio is unavailable in the answer form. The second is that if a checker user deletes audio from an answer while offline, when returning online I saw an error box and the deletion date remains in indexedDB.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/800#-:-MI-gqMg5hse3WJtEP78:bq187zk)* status: all files reviewed, 5 unresolved discussions (waiting on @nigel-wells)



<!-- Sent from Reviewable.io -->

2020-09-25 02:27 UTC, nigel-wells reviewed
Thanks for looking at this and doing the rebase. 

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/800#-:-MI24SSGC1q9k2ZDlo0U:b-jm54dq)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, line 353 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/800#-MHwzxElEd6WGlKidZZb:-MI1-8Fp4ys8Mr-Saex-:btco5zu) ([raw file](https://github.com/sillsdev/web-xforge/blob/409e5f3419ce5b606ac30a1ffffdb9065f033c28/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts#L353)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

Actually, `this.questionsQuery.remoteDocChanges` may still fire if an answer is removed, so this may not be a problem.
</blockquote></details>

Yes if an answer is removed the question doc itself remains so will trigger a remote change. 
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts, line 629 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/800#-MHx17drCXuN15i2jxtF:-MI11D36A9nhGJTDXj-p:b-3dl5b1) ([raw file](https://github.com/sillsdev/web-xforge/blob/409e5f3419ce5b606ac30a1ffffdb9065f033c28/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.ts#L629)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> if (this.pwaService.isOnline) {
> ```
Should this also update the file cache too?
</blockquote></details>

The general file cache is already updated for docs (and questions) so no need to trigger it again i.e. when `updateOfflineData()` is triggered. Answers were different as we only wanted to cache them if a question with answer audio was specifically viewed.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts, line 1305 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/800#-MHx0Cnl5KfiYF67hHrV:-MI24PuNExjRyFomb0x8:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/409e5f3419ce5b606ac30a1ffffdb9065f033c28/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking.component.spec.ts#L1305)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> it('update answer audio cache on remote update to question', fakeAsync(() => {
> ```
There may be an easy test we can add to test if `updateAnswerFileCache()` gets called if an answer with audio is removed remotely.
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/models/question-doc.ts, line 68 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/800#-MHwwb936rzuwfhbPQxQ:-MI0z5Tk1iEoaq1LBtdy:b-40w1vk) ([raw file](https://github.com/sillsdev/web-xforge/blob/409e5f3419ce5b606ac30a1ffffdb9065f033c28/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/question-doc.ts#L68)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> protected async updateOfflineData(force: boolean = false): Promise<void> {
> ```
Since this is mostly concerned with audio data, I would rename this `updateAnswerAudioCache` or something similar.
</blockquote></details>

This function is used to extend the core function in all realtime docs when dealing with offline data i.e. `realtime-doc.ts`. I decided to simply extend that functionality as I figured that is essentially what we're dealing with here but specifically in the context of question docs.


<!-- Sent from Reviewable.io -->

2020-09-25 02:45 UTC, nigel-wells reviewed
Ah, just saw your other comments about error boxes - will take a look.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/800#-:-MI28WppCb7eCZF2jB8C:b-3qu256)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2020-09-25 02:53 UTC, nigel-wells reviewed
I've just tried out both of those scenarios and didn't get any errors for either of them - can you still replicate it? Let me know what the error is and that might help.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/800#-:-MI2ABe05wtYiXZ-2S5H:bc0lbcj)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2020-09-25 19:51 UTC, RaymondLuong3 reviewed
Here are the steps I used to reproduce the first issue.
1. Add a answer with audio to a question, then navigate to the overview page.
2. Stop the backend.
3. Navigate to project home. There I could already see that the audio was unavailable.

For some reason it all worked if I shut off the backend while viewing the question. Weird. The second issue wasn't reproducible.

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/800#-:-MI5nmP69fu6Cr2uloKv:blxmaih)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2020-09-27 19:30 UTC, nigel-wells reviewed
I've just tried again in Chrome and Firefox and still couldn't reproduce. Can you check again and see if the audio file has been added to indexdb prior to navigating to the overview page? Are you able to do a video for me so I can better see what might be happening?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/800#-:-MIG1X0e7cdLS2FQiha3:b-55rxn2)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2020-09-28 15:51 UTC, RaymondLuong3 approved these changes
So I couldn't reproduce the issue today. Maybe it just took my system so time for all the moving dependencies to be up to date. I approve.

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/800#-:-MIKP2MLBMbVy_ckjeWR:bjoiuce)* status: all files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/models/question-doc.ts, line 68 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/800#-MHwwb936rzuwfhbPQxQ:-MIKOwuh9XzhjTyBISjW:b-m5yqyg) ([raw file](https://github.com/sillsdev/web-xforge/blob/409e5f3419ce5b606ac30a1ffffdb9065f033c28/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/question-doc.ts#L68)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

This function is used to extend the core function in all realtime docs when dealing with offline data i.e. `realtime-doc.ts`. I decided to simply extend that functionality as I figured that is essentially what we're dealing with here but specifically in the context of question docs.
</blockquote></details>

Ok, that seems reasonable to me.


<!-- Sent from Reviewable.io -->

2020-09-28 15:52 UTC, RaymondLuong3 approved these changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/800)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-09-29 08:43 UTC, merged