SF-1072 Connect: Do not connect PT project twice
sillsdev/web-xforge pull request #822
Opened 2020-09-30 15:13 UTC by marksvc

- Disallow in backend.
- I didn't find a great preexisting exception to use and used
  ArgumentOutOfRangeException.
- Report problem in front-end for the exceptional circumstance.
- command-service.ts would receive a response back from
  this.http.post() that was not a thrown error but a response with an
  error. Throwing that makes it be treated similarly.
- connect-project.component.ts:
  - Catch errors from projectService.onlineCreate(). If the error
    looks like the already-connected problem, inform the user to just
    retry, or report if it keeps happening, and re-query the paratext
    projects.
  - Pass the error to errorHandler.handleError() to re-use its email
    reporting capability, and to log this situation to bugsnag.

2020-09-30 15:21 UTC, marksvc commented
Here is a 1 minute animation showing the fix.

![double-connect-fix](https://user-images.githubusercontent.com/7265309/94705467-553de300-02fe-11eb-9962-0d9824ecd337.gif)

2020-09-30 22:17 UTC, RaymondLuong3 requested changes
Just a few comments below, but looks pretty good.

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/822#-:-MIW4qpc78LSQc4G7Fp9:bkkd2qp)* status: all files reviewed, 7 unresolved discussions (waiting on @marksvc)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts, line 197 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/822#-MIVya959NbNxXj5dV3H:-MIVya959NbNxXj5dV3I:b-hijcwc) ([raw file](https://github.com/sillsdev/web-xforge/blob/4f312e1dae2485148f394f1265e9e0939408ccb3/src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts#L197)):*
> ```
> this.translocoService.translate('start.problem_already_connected'
> ```
This string should be under the connect-project component
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts, line 201 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/822#-MIW3_tx5TUaprkT9Gv5:-MIW3_tx5TUaprkT9Gv6:b-kyiylk) ([raw file](https://github.com/sillsdev/web-xforge/blob/4f312e1dae2485148f394f1265e9e0939408ccb3/src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts#L201)):*
> ```
> this.errorHandler.handleError(err);
> ```
Why does this need to be handled by an `ErrorHandler`? Could we just display a dialog that says that the project is already connected?
___
*[src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json, line 294 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/822#-MIVzp8J8SQ1q7MGMGN8:-MIVzp8J8SQ1q7MGMGN9:bfomi3z) ([raw file](https://github.com/sillsdev/web-xforge/blob/4f312e1dae2485148f394f1265e9e0939408ccb3/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json#L294)):*
> ```
> Original error message: "
> ```
I would start this on a new line.
___
*[src/SIL.XForge.Scripture/Services/SFProjectService.cs, line 113 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/822#-MIW0rG605dgiTmLEGiF:-MIW0rG605dgiTmLEGiG:bwnj821) ([raw file](https://github.com/sillsdev/web-xforge/blob/4f312e1dae2485148f394f1265e9e0939408ccb3/src/SIL.XForge.Scripture/Services/SFProjectService.cs#L113)):*
> ```
> throw new ArgumentOutOfRangeException(nameof(settings),
> ```
What about throwing an `InvalidOperationException`? I don't think the message is necessary, but it's not an issue for me.
___
*[test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs, line 540 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/822#-MIW1YhfBYPGjUTKcqnS:-MIW1YhfBYPGjUTKcqnT:bgkwpgc) ([raw file](https://github.com/sillsdev/web-xforge/blob/4f312e1dae2485148f394f1265e9e0939408ccb3/test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs#L540)):*
> ```
> Assert.That(env.RealtimeService.GetRepository<SFProject>().Query().Count(),
>                 Is.EqualTo(projectCount + 1), "increased");
> ```
That message could say "should have increased."
___
*[test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs, line 558 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/822#-MIW1xa_6zr9jfyc2Cx3:-MIW1xa_6zr9jfyc2Cx4:buvge4u) ([raw file](https://github.com/sillsdev/web-xforge/blob/4f312e1dae2485148f394f1265e9e0939408ccb3/test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs#L558)):*
> ```
> Assert.That(env.RealtimeService.GetRepository<SFProject>().Query().Count(),
>                 Is.EqualTo(projectCount), "not increase");
> ```
That message could say "should not have changed"
___
*[test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs, line 730 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/822#-MIW2Hnc0d_Q9Itl55WV:-MIW2Hnc0d_Q9Itl55WW:b-qnemnv) ([raw file](https://github.com/sillsdev/web-xforge/blob/4f312e1dae2485148f394f1265e9e0939408ccb3/test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs#L730)):*
> ```
> new ParatextProject{
> ```
Move the brace to a new line to be consistent.


<!-- Sent from Reviewable.io -->

2020-10-02 18:05 UTC, marksvc reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/822)* status: all files reviewed, 5 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts, line 197 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/822#-MIVya959NbNxXj5dV3H:-MIa7aIh37UhE-p0AM1v:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/4f312e1dae2485148f394f1265e9e0939408ccb3/src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts#L197)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> this.translocoService.translate('start.problem_already_connected'
> ```
This string should be under the connect-project component
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts, line 201 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/822#-MIW3_tx5TUaprkT9Gv5:-MIa7izb-bYgS7XsGxWW:b-t113ur) ([raw file](https://github.com/sillsdev/web-xforge/blob/4f312e1dae2485148f394f1265e9e0939408ccb3/src/SIL.XForge.Scripture/ClientApp/src/app/connect-project/connect-project.component.ts#L201)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> this.errorHandler.handleError(err);
> ```
Why does this need to be handled by an `ErrorHandler`? Could we just display a dialog that says that the project is already connected?
</blockquote></details>

Yes! We could. And I had started off that way. In the dialog I said to try connecting again, and that if it keeps happening, to report an issue by clicking the question-mark icon and clicking 'Report an issue', and maybe there would be some special error number or something that they could enter into the message so it helps us identify what particular problem they are having. 

In the end I used our exception-handler-service, which displays a message box, records on bugsnag that someone had this unlikely problem, and helpfully has a Report-a-problem link ready to click on with a template message. 

So the ErrorHandler is like doing the dialog, but with these extras.
___
*[src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json, line 294 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/822#-MIVzp8J8SQ1q7MGMGN8:-MIeSZOB4gHKKcnUqN-M:be4lkyn) ([raw file](https://github.com/sillsdev/web-xforge/blob/4f312e1dae2485148f394f1265e9e0939408ccb3/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json#L294)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> Original error message: "
> ```
I would start this on a new line.
</blockquote></details>

After reworking the message a bit and what we show the user anyway, this line is gone. 
___
*[src/SIL.XForge.Scripture/Services/SFProjectService.cs, line 113 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/822#-MIW0rG605dgiTmLEGiF:-MIeS9XSEqTbMZxF0Ji-:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/4f312e1dae2485148f394f1265e9e0939408ccb3/src/SIL.XForge.Scripture/Services/SFProjectService.cs#L113)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> throw new ArgumentOutOfRangeException(nameof(settings),
> ```
What about throwing an `InvalidOperationException`? I don't think the message is necessary, but it's not an issue for me.
</blockquote></details>

Done.
___
*[test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs, line 730 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/822#-MIW2Hnc0d_Q9Itl55WV:-MIeST4R5Pd7-0AF9AD6:b-i21bbo) ([raw file](https://github.com/sillsdev/web-xforge/blob/4f312e1dae2485148f394f1265e9e0939408ccb3/test/SIL.XForge.Scripture.Tests/Services/SFProjectServiceTests.cs#L730)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> new ParatextProject{
> ```
Move the brace to a new line to be consistent.
</blockquote></details>

Thanks. Done.


<!-- Sent from Reviewable.io -->

2020-10-02 20:44 UTC, RaymondLuong3 approved these changes
One non-blocking comment.

> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/822#-:-MIf2kFpBLkGV86QJN3o:b-ommtmt)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc)

___
*[src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json, line 59 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/822#-MIf2XLVC1FTxwIF8Grm:-MIf2XLVC1FTxwIF8Grn:bq4gfz7) ([raw file](https://github.com/sillsdev/web-xforge/blob/79b967fae30becbc6a2a32879267df61184f1ac5/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L59)):*
> ```
> If it continues to be a problem, please report the issue so we can get it fixed.",
> ```
I don't think this is necessary, but if you decide to keep it, I would include the issues@scriptureforge.org email.


<!-- Sent from Reviewable.io -->

2020-10-02 21:08 UTC, marksvc reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/822)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json, line 59 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/822#-MIf2XLVC1FTxwIF8Grm:-MIf7J9u421EMCv9PRNT:b-6v7212) ([raw file](https://github.com/sillsdev/web-xforge/blob/79b967fae30becbc6a2a32879267df61184f1ac5/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json#L59)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> If it continues to be a problem, please report the issue so we can get it fixed.",
> ```
I don't think this is necessary, but if you decide to keep it, I would include the issues@scriptureforge.org email.
</blockquote></details>

That makes sense. I think we _shouldn't_ have users getting this message more than once at a time. But I don't want to just tell a user to keep trying again if there's actually something more fundamentally wrong that I haven't thought of yet.
An advantage of using the handleError() method is that right below this message, it will say "To report an issue, email scriptureforgeissues@sil". The email link comes with a template and everything, which is great, and much more helpful than just the text of the email address.


<!-- Sent from Reviewable.io -->

2020-10-02 21:09 UTC, merged