Show error message if a file could not be saved
sillsdev/web-xforge pull request #824
Opened 2020-10-01 18:17 UTC by RaymondLuong3

When a user's device is full, IndexedDB could abort a transaction with either a QuotaExceededError or a DataError. If this happens while uploading a file, we catch that an notify the user.

2020-10-02 18:16 UTC, marksvc approved these changes
I almost approve but would like to understand a bit more. 

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/824#-:-MIeWleDEu8d3Ie_4396:b-rmv7hw)* status: all files reviewed, 2 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/file.service.ts, line 256 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/824#-MIeW6FOBIPkXJ6WnBKd:-MIeW6FOBIPkXJ6WnBKe:brrgdxj) ([raw file](https://github.com/sillsdev/web-xforge/blob/e75b19059301bcef9edc8c385b7df72bc4e4ba69/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/file.service.ts#L256)):*
> ```
> by exceeding the browser's storage quota
> ```
Is this still true?
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/file.service.ts, line 259 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/824#-MIeWJvS6nPJarOIn_4R:-MIeWJvS6nPJarOIn_4S:b-n4toze) ([raw file](https://github.com/sillsdev/web-xforge/blob/e75b19059301bcef9edc8c385b7df72bc4e4ba69/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/file.service.ts#L259)):*
> ```XML
>    */
>   private async onCachingError(error: any): Promise<void> {
>     if (!(error instanceof DOMException)) {
> ```

Okay, so the change opens up onCachingError to now handle more than just QuotaExceededError, and so the message show to the user is now less specific. Is that right?


<!-- Sent from Reviewable.io -->

2020-10-02 19:44 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/824)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @marksvc)

___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/file.service.ts, line 256 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/824#-MIeW6FOBIPkXJ6WnBKd:-MIenXDy95uVBt4QN622:bv8dwr9) ([raw file](https://github.com/sillsdev/web-xforge/blob/e75b19059301bcef9edc8c385b7df72bc4e4ba69/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/file.service.ts#L256)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
> by exceeding the browser's storage quota
> ```
Is this still true?
</blockquote></details>

It's still true. Apparently browsers storage quotas don't always report the real-time value (chromium v81 did, v85 does not). but this method will be used primarily to detect storage quota exceeded.
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/file.service.ts, line 259 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/824#-MIeWJvS6nPJarOIn_4R:-MIepOrx2TYGwFuekPf_:bs1nzno) ([raw file](https://github.com/sillsdev/web-xforge/blob/e75b19059301bcef9edc8c385b7df72bc4e4ba69/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/file.service.ts#L259)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Okay, so the change opens up onCachingError to now handle more than just QuotaExceededError, and so the message show to the user is now less specific. Is that right?
</blockquote></details>

Yes, the message is now less specific. It will catch related errors in the event that the storage quota API isn't functioning in real-time.


<!-- Sent from Reviewable.io -->

2020-10-02 21:03 UTC, marksvc approved these changes
I think that exception-handling-service.ts and file.service.ts will be two _separate_ possible places for the error to be handled, rather than being handled by one and passed off to the other, is that so? Or does file.service.ts somehow process the problem, show the message dialog, and then it gets taken over later  by exception-handling-service.ts ?

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/824#-:-MIf6gH_CMjYYjAyVeUT:b-86sba5)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-02 21:25 UTC, RaymondLuong3 reviewed
There are lots of places where we call `Indexeddb-offline-store.put()` which will through errors if there is not more storage quota or free space on the device. `File.service.ts` will show the "failed to save.. " message if the device has no more space to cache a file, and will prompt the user to free up space. This is where we expect most people to hit if their device is almost full. So `file.service.ts` will handle the expected error that comes from trying to cache audio to a device low on storage, and `exception-handler.service.ts` handles the cases where an error occurs, but through the numerous places where `indexeddb-offline-store.put()` is called.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/824#-:-MIfATLS1fu9IMmua30y:bgujebv)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-03 15:48 UTC, irahopkinson requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/824)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/file.service.ts, line 264 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/824#-MIj80MM1b4_i8f406NE:-MIj80MM1b4_i8f406NF:b-tv815a) ([raw file](https://github.com/sillsdev/web-xforge/blob/f182a46e5180cddc6bee192202b3a66af72adccd/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/file.service.ts#L264)):*
> ```
> { message: error.message }
> ```
I'm really not keen on dumping an error message directly at a user. I'm even more unkeen because it can't be translated. What are the known possibilities for this error message or do we not know?


<!-- Sent from Reviewable.io -->

2020-10-05 17:58 UTC, RaymondLuong3 reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/824)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @irahopkinson and @marksvc)

___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/file.service.ts, line 264 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/824#-MIj80MM1b4_i8f406NE:-MIttavUDuKj_4YrnZ6f:b-mrciku) ([raw file](https://github.com/sillsdev/web-xforge/blob/f182a46e5180cddc6bee192202b3a66af72adccd/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/file.service.ts#L264)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> { message: error.message }
> ```
I'm really not keen on dumping an error message directly at a user. I'm even more unkeen because it can't be translated. What are the known possibilities for this error message or do we not know?
</blockquote></details>

I think you are right. It's not helpful for any reason to give that to the user. I'll take it out since it is unlikely for this message to occur except for when storage space is limited.


<!-- Sent from Reviewable.io -->

2020-10-05 19:23 UTC, marksvc approved these changes
Okay. Thanks for explaining.

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/824#-:-MIuBgYD1u8wo7shmLyt:b-1fvo68)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)



<!-- Sent from Reviewable.io -->

2020-10-05 19:23 UTC, marksvc approved these changes
I approve

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/824#-:-MIuD55l7ZHb-fQetyGV:b-8ul1in)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)



<!-- Sent from Reviewable.io -->

2020-10-06 04:26 UTC, irahopkinson approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r1, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/824#-:-MIw93NmEbN7aBtXq4HR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-06 05:46 UTC, merged