SF-1089 Set MockScrText.Settings.Guid
sillsdev/web-xforge pull request #827
Opened 2020-10-05 20:58 UTC by marksvc

- ParatextServiceTests.cs PutNotes test fails when VersionedText.cs
  VersionedText(ScrText) checks if ScrText Settings.Guid is empty, and
  if so calculates a new guid for it. It tries to write the info to a
  file but has trouble and crashes.
- I haven't fully compared the context of our MockScrText construction
  and how ScrText objects get constructed. But I do see that setting
  ScrText.Settings results in setting ScrText.CachedGuid to the value
  of Settings.Guid.
- Set ScrText.Settings.Guid when we set up a MockScrText with a known
  Guid so we don't crash in VersionedText.cs VersionedText(ScrText).

2020-10-05 21:31 UTC, RaymondLuong3 reviewed
Are you seeing a crash when `VersioningManager.Get(ScrText))` where it call `VersionedText.cs VersionedText(ScrText)`? That is where I crash. I can see why this would be different on linux and windows. It crashes with a "object reference not set to an instance of an object" presumably on `Hg.Default.IsRepository()`. I think we do need to mock out `VersioningManager`

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/827#-:-MIueDS62al8yIkkne3Z:b11glv2)* status: 0 of 1 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-05 22:52 UTC, marksvc reviewed
Yes, I agree now about mocking out VersioningManager.
I would like to take a look to see if we should still use this MockScrText patch, or not worry about it.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/827#-:-MIuxU42-cpl6NaXNJQ3:be065dd)* status: 0 of 1 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-06 09:03 UTC, irahopkinson requested changes
This change doesn't fix SF-1089 for me, although on Windows I may have some additional set up required.

As I mentioned in Slack:
SF-1089 is not even published at this point. Please leave it until after SF-1088 is complete, esp since @pmachapman  is now waiting on it. Do note that although SF-1089 is only a test failure not a functional failure, i.e. the code works even if the test doesn't.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/827#-:-MIx8Hy5-cQQPJzY3E0W:bavk6d2)* status: 0 of 1 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-06 21:53 UTC, marksvc commented
Sorry, this wasn't clear from the descriptions I included. This code was written to prevent the test from crashing rather than testing. It won't necessarily make the test pass.

2020-10-06 22:35 UTC, RaymondLuong3 approved these changes
This does not necessarily fix SF-1089, but it is a bug, and this might reveal issues in other tests. We should get it in.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/827#-:-MJ-24bY2TL5GbMj4BGe:b-99l8zf)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-06 22:50 UTC, marksvc commented
> might reveal issues in other tests
Good point. I want to wait until I have another look at the PutNotes test before advocating this along.

2020-10-07 20:12 UTC, marksvc commented
Okay, so this code doesn't 'fix' anything broken right now. But it may prevent a problem in the future. I revised the patch's comment and commit message to better reflect the new situation, and I return to proposing its inclusion.

2020-10-07 20:23 UTC, marksvc commented
(The bot is complaining about Delta.cs.)

2020-10-08 17:50 UTC, marksvc commented
(So github says that @irahopkinson has "requested changes" on the PR. I assume that isn't significant right now, but I am not in a hurry and will leave the PR in case Ira has something to add or get changed.)

2020-10-09 16:38 UTC, irahopkinson approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/827#-:-MJDAClACl0MWmGM71dK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-09 16:39 UTC, merged