SF-1009 Inform user when previewing audio is not available
sillsdev/web-xforge pull request #842
Opened 2020-10-16 22:17 UTC by RaymondLuong3

* tell user when an audio file cannot be preview as is the case for .wma files
* users can play the .wma file once uploaded and converted to a .mp3
* handle .ogg audio files by using the lastInvalids event emitter in firefox

2020-10-20 16:15 UTC, marksvc commented
:eyes:

2020-10-20 16:57 UTC, marksvc requested changes
Thanks for your work on this. See comments.

> Reviewed 6 of 6 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/842#-:-MK5wLr8C_c7_66rHPb-:bdfrsbr)* status: all files reviewed, 5 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, line 257 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/842#-MK5tYYs0VCuDOtU9H7g:-MK5tYYt3VRH_bPvmsdt:b3o482e) ([raw file](https://github.com/sillsdev/web-xforge/blob/15de42f0666e8758a495eb324c43244b8fcb4f51/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts#L257)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>     this.subscribe(this.pwaService.onlineStatus, async isOnline => {
>       if (isOnline) {
>         await this.questionDoc?.fileSyncPromise;
>         this.updateQuestionAudioUrl();
>       }
>     });
> ```
</details>


(So read my comment in file service first.)
So this might be written as

ngOnInit():void{
  this.applyTextAudioValidators();
  this.subscribe(this.fileService.fileSyncCompleted, ()=>this.updateQuestionAudioUrl());
}

Then each time the user comes online, and the frontend does a file sync, there will be an announcement made, and checking-answers component will hear about it and in response it will update what audio is available online or not online. 
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-combined/checking-audio-combined.component.ts, line 49 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/842#-MK5n8zXDiNrEsUSBeGX:-MK5n8zXDiNrEsUSBeGY:bcyih18) ([raw file](https://github.com/sillsdev/web-xforge/blob/dd47d5371b3d05a391b5832cea2d947be6a69ac1/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-combined/checking-audio-combined.component.ts#L49)):*
> ```XML
>     if (value.length > 0 && value[0].file.type === 'video/ogg') {
>       this.uploadAudioFile = value[0].file;
>       this.prepareAudioFileUpload();
> ```

That's unfortunate to have to handle this in the two different ways ( (fileChange)="prepareAudioFileUpload()" and [(lastInvalids)]="lastInvalids" ). Good job figuring this out.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.spec.ts, line 76 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/842#-MK5hFn0AD9GcC0Hj0li:-MK5hFn0AD9GcC0Hj0lj:b2o3zix) ([raw file](https://github.com/sillsdev/web-xforge/blob/dd47d5371b3d05a391b5832cea2d947be6a69ac1/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.spec.ts#L76)):*
> ```XML
> 
>   it('it can play blobs even when offline', async () => {
>     const template = `<app-checking-audio-player #player1 source="${audioFile}"></app-checking-audio-player>`;
> ```

What's the meaning of this change?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.spec.ts, line 99 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/842#-MK5hduJ4az-5D3ptmVi:-MK5hduJ4az-5D3ptmVj:b-p996xy) ([raw file](https://github.com/sillsdev/web-xforge/blob/dd47d5371b3d05a391b5832cea2d947be6a69ac1/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.spec.ts#L99)):*
> ```XML
>     expect(env.audioNotAvailableMessage).not.toBeNull();
>     expect(env.audioNotAvailableMessage.query(By.css('#error-load'))).not.toBeNull();
>   });
> ```

What do you think about also asserting that the play button is not present?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/models/question-doc.ts, line 18 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/842#-MK5vry958vaYnCA0eKM:-MK5vryA-WedoXwkDzz-:b41a607) ([raw file](https://github.com/sillsdev/web-xforge/blob/15de42f0666e8758a495eb324c43244b8fcb4f51/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/question-doc.ts#L18)):*
> ```XML
>   static readonly INDEX_PATHS = QUESTION_INDEX_PATHS;
> 
>   get fileSyncPromise(): Promise<void> | undefined {
> ```

(So I think this property would go away.)
___
*[src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json, line 186 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/842#-MK5lUnp0X8206-X_OSc:-MK5lUnp0X8206-X_OSd:b-4x98lt) ([raw file](https://github.com/sillsdev/web-xforge/blob/dd47d5371b3d05a391b5832cea2d947be6a69ac1/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json#L186)):*
> ```JSON
>     "audio_unavailable": "Audio unavailable.",
>     "audio_cannot_be_played": "This audio cannot be played while you are offline because it has not been downloaded. Connect to the internet to play.",
>     "audio_cannot_be_previewed": "The audio is in a format that cannot be previewed. Save any changes and connect to the internet to play."
> ```

We'll want to be careful not to make people think their audio format isn't _supported_. Just not playable yet in its current format.
(I don't have any suggested change tho)
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/file.service.ts, line 65 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/842#-MK5qRW463tpU5njFUIp:-MK5qRW463tpU5njFUIq:ba0k5su) ([raw file](https://github.com/sillsdev/web-xforge/blob/15de42f0666e8758a495eb324c43244b8fcb4f51/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/file.service.ts#L65)):*
> ```XML
>   init(realtimeService: RealtimeService): void {
>     this.subscribe(this.pwaService.onlineStatus, isOnline => {
>       this.fileSyncCompletePromise = new Promise<void>(async resolve => {
> ```

What do you think about restructuring this in this way:

(1) 

In the original code, refactor init() to move all the logic into its own async method.
So now we have
init(..):void {
  this.subscribe(onlineStatus, (isOnline:boolean)=>this.syncFiles(isOnline));
}
async syncFiles(isOnline:boolean):void{
  // Wait until logged..
  if (isOnline && (await ..
    ..
}
That makes it I think equivalent to what it was before, but refactored. 

Then change it to preserve the promise, like you have done, but to the refactored code:

fileSyncComplete?: Promise<void>;
init(..):void {
  this.subscribe(onlineStatus, (isOnline:boolean)=> {
    this.fileSyncComplete = this.syncFiles(isOnline);
  });
}
// And the syncFiles() method stays the same.

I think that should be the same as what you have, but with a bit cleaner structure. I don't think you should need to put in `new Promise<void>(.... resolve()` here,  but maybe I'm not understanding. 

(2) 

After looking at checking answers component again, I think you should change the exposed field from a Promise<void> to a Subject<void>. 
Then have init() listen for onlineStatus to change, and if it does change, then run this.syncFiles() (but not with await). 
At the end of syncFiles(), have it broadcast on the Subject<void> that a file sync was completed (so `this.fileSyncCompleted.next()`).

Subscribers who are interested in knowing when that happens, who have subscribed to this.fileSyncCompleted, can then do something in response. 


<!-- Sent from Reviewable.io -->

2020-10-20 17:33 UTC, marksvc reviewed
(Oh, or maybe EventEmitter or similar.)

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/842#-:-MK63UZL9TSk0ThWHq4D:b9xkmeo)* status: all files reviewed, 5 unresolved discussions (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2020-10-21 17:55 UTC, RaymondLuong3 reviewed
I went with your original suggestion.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/842#-:-MKBCXoP60DWkGBrrFBG:bedd15q)* status: 5 of 9 files reviewed, 5 unresolved discussions (waiting on @marksvc)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, line 257 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/842#-MK5tYYs0VCuDOtU9H7g:-MKBHakV5gkXL7O85hJ0:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/15de42f0666e8758a495eb324c43244b8fcb4f51/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts#L257)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

> ```
>     this.subscribe(this.pwaService.onlineStatus, async isOnline => {
>       if (isOnline) {
>         await this.questionDoc?.fileSyncPromise;
>         this.updateQuestionAudioUrl();
>       }
>     });
> ```

(So read my comment in file service first.)
So this might be written as

ngOnInit():void{
  this.applyTextAudioValidators();
  this.subscribe(this.fileService.fileSyncCompleted, ()=>this.updateQuestionAudioUrl());
}

Then each time the user comes online, and the frontend does a file sync, there will be an announcement made, and checking-answers component will hear about it and in response it will update what audio is available online or not online. 
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.spec.ts, line 76 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/842#-MK5hFn0AD9GcC0Hj0li:-MKBHczE8FANAEG1fx0j:bbfyols) ([raw file](https://github.com/sillsdev/web-xforge/blob/dd47d5371b3d05a391b5832cea2d947be6a69ac1/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.spec.ts#L76)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

What's the meaning of this change?
</blockquote></details>

There will be an error loading the `blob://` since it isn't a real source, so we needed to use a real source.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.spec.ts, line 99 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/842#-MK5hduJ4az-5D3ptmVi:-MKBHqqI4_QXoigvTFar:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/dd47d5371b3d05a391b5832cea2d947be6a69ac1/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.spec.ts#L99)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

What do you think about also asserting that the play button is not present?
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/core/models/question-doc.ts, line 18 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/842#-MK5vry958vaYnCA0eKM:-MKBHrxZ5PndQ3D4sSKv:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/15de42f0666e8758a495eb324c43244b8fcb4f51/src/SIL.XForge.Scripture/ClientApp/src/app/core/models/question-doc.ts#L18)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

(So I think this property would go away.)
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/file.service.ts, line 65 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/842#-MK5qRW463tpU5njFUIp:-MKBHuDp4jbZ_mZJwHjC:buioxco) ([raw file](https://github.com/sillsdev/web-xforge/blob/15de42f0666e8758a495eb324c43244b8fcb4f51/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/file.service.ts#L65)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

What do you think about restructuring this in this way:

(1) 

In the original code, refactor init() to move all the logic into its own async method.
So now we have
init(..):void {
  this.subscribe(onlineStatus, (isOnline:boolean)=>this.syncFiles(isOnline));
}
async syncFiles(isOnline:boolean):void{
  // Wait until logged..
  if (isOnline && (await ..
    ..
}
That makes it I think equivalent to what it was before, but refactored. 

Then change it to preserve the promise, like you have done, but to the refactored code:

fileSyncComplete?: Promise<void>;
init(..):void {
  this.subscribe(onlineStatus, (isOnline:boolean)=> {
    this.fileSyncComplete = this.syncFiles(isOnline);
  });
}
// And the syncFiles() method stays the same.

I think that should be the same as what you have, but with a bit cleaner structure. I don't think you should need to put in `new Promise<void>(.... resolve()` here,  but maybe I'm not understanding. 

(2) 

After looking at checking answers component again, I think you should change the exposed field from a Promise<void> to a Subject<void>. 
Then have init() listen for onlineStatus to change, and if it does change, then run this.syncFiles() (but not with await). 
At the end of syncFiles(), have it broadcast on the Subject<void> that a file sync was completed (so `this.fileSyncCompleted.next()`).

Subscribers who are interested in knowing when that happens, who have subscribed to this.fileSyncCompleted, can then do something in response. 



</blockquote></details>

Yes, I thought of doing that too, but also didn't think it was necessary. However, I like the idea of using an observable to emit when file sync is completed. I took both your suggestions.


<!-- Sent from Reviewable.io -->

2020-10-21 18:27 UTC, marksvc approved these changes
> Reviewed 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/842)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-21 20:40 UTC, merged