SF-1030 - Handle 404 responses for audio files
sillsdev/web-xforge pull request #861
Opened 2020-11-04 01:43 UTC by nigel-wells

- Allow all audio to be passed to the audio component
- Show relevant error tooltip based on status of audio source
- Amended translation for audio tooltips

For editing questions/answers I changed it to now send through the filename from the server rather than what was in cache. This allows the audio control to respond to the file actually being available and not just in cache.

There is now a state for loading audio in the component.

I have also renamed one of the translation keys to make it more appropriate - hopefully that doesn't mess too much up? The translation itself it is the same.

2020-11-10 11:24 UTC, irahopkinson requested changes
I started to review this and realise I don't know enough about how this all works to review it well. @raymondluong3 or @nateowami could you review this?

> Reviewed 9 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/861#-:-MLltN0q21GmTPrbrFgb:b-c1u443)* status: 9 of 16 files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json, line 187 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/861#-MLlqxzr2AsR4Y8XXMuC:-MLlqxzs5hvuLXI7OzdU:b-jvsqn0) ([raw file](https://github.com/sillsdev/web-xforge/blob/7ae0c617c1a3bee2925b2fc0e1916f8c1dea9b08/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json#L187)):*
> ```
> audio_cannot_be_played_offline
> ```
It's best not to do this for AFAICT this requires the whole item to need to be translated again in each language. Leave the orignal key and perhaps name the new key `audio_cannot_be_uploaded` or `audio_cannot_be_accessed`.


<!-- Sent from Reviewable.io -->

2020-11-10 20:59 UTC, RaymondLuong3 requested changes
Good work. Just a few changes needed.

> Reviewed 16 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/861#-:-MLnx2Sr8ar2DC8goz4C:b7d93mq)* status: all files reviewed, 4 unresolved discussions (waiting on @nigel-wells)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, line 522 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/861#-MLnowu73OPpCdg6pSB0:-MLnowu86J6bywIKeBSy:byhkioz) ([raw file](https://github.com/sillsdev/web-xforge/blob/7ae0c617c1a3bee2925b2fc0e1916f8c1dea9b08/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts#L522)):*
> ```
>     // default to the audioUrl to access the file on server if online or show the audio unavailable icon
>     // when offline and audio is not cached
> ```
This comment needs to be updated
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.html, line 14 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/861#-MLnsqU0Cb0tSFDatsH-:-MLnsqU0Cb0tSFDatsH0:b-1ncnya) ([raw file](https://github.com/sillsdev/web-xforge/blob/7ae0c617c1a3bee2925b2fc0e1916f8c1dea9b08/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.html#L14)):*
> ```
> <div *ngFor="let status of statuses">
> ```
Instead of looping through all the statuses, you could make statuses a `Map<string, string>` using the `AudioStatus` as a key, then get the value for the current `audioStatus`?
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.ts, line 102 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/861#-MLnrrk10l_wCPyE9rYq:-MLnrrk10l_wCPyE9rYr:bv9xm6p) ([raw file](https://github.com/sillsdev/web-xforge/blob/7ae0c617c1a3bee2925b2fc0e1916f8c1dea9b08/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.ts#L102)):*
> ```
>   get hasErrorState(): boolean {
>     return !(this.audioStatus === AudioStatus.Init || this.audioStatus === AudioStatus.Available);
>   }
> ```
This can be private.
___
*[src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json, line 186 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/861#-MLnva6l2xXqLJTuRwMx:-MLnva6l2xXqLJTuRwMy:bo94ie1) ([raw file](https://github.com/sillsdev/web-xforge/blob/7ae0c617c1a3bee2925b2fc0e1916f8c1dea9b08/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json#L186)):*
> ```
> it may need to removed and uploaded again."
> ```
How about a more specific message. "If this persists, please upload a new file."


<!-- Sent from Reviewable.io -->

2020-11-11 01:19 UTC, nigel-wells reviewed
@irahopkinson I've changed the translation key back to what it was previously - it doesn't actually look like the original string has been translated yet though.
@raymondluong3 I've made a few tweaks as per your suggestions.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/861#-:-MLorHU59VoOg_oTnKj5:b-6ho8d6)* status: 4 of 8 files reviewed, 4 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts, line 522 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/861#-MLnowu73OPpCdg6pSB0:-MLooKYC2nyHqxZbv2rM:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/7ae0c617c1a3bee2925b2fc0e1916f8c1dea9b08/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-answers.component.ts#L522)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
>     // default to the audioUrl to access the file on server if online or show the audio unavailable icon
>     // when offline and audio is not cached
> ```
This comment needs to be updated
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.html, line 14 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/861#-MLnsqU0Cb0tSFDatsH-:-MLopN7mEt5EjkQbmdFt:b-v3turs) ([raw file](https://github.com/sillsdev/web-xforge/blob/7ae0c617c1a3bee2925b2fc0e1916f8c1dea9b08/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.html#L14)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> <div *ngFor="let status of statuses">
> ```
Instead of looping through all the statuses, you could make statuses a `Map<string, string>` using the `AudioStatus` as a key, then get the value for the current `audioStatus`?
</blockquote></details>

Thanks for raising this - I was never quite happy with what I was doing there! I've taken another look and found simpler way to do it - seems obvious now :)
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.ts, line 102 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/861#-MLnrrk10l_wCPyE9rYq:-MLopj3b463t2Z9iIeDN:b-us6e16) ([raw file](https://github.com/sillsdev/web-xforge/blob/7ae0c617c1a3bee2925b2fc0e1916f8c1dea9b08/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-audio-player/checking-audio-player.component.ts#L102)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
>   get hasErrorState(): boolean {
>     return !(this.audioStatus === AudioStatus.Init || this.audioStatus === AudioStatus.Available);
>   }
> ```
This can be private.
</blockquote></details>

After refactoring the displaying of the error message I'm not using this in a template so it needs to be `public`
___
*[src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json, line 186 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/861#-MLnva6l2xXqLJTuRwMx:-MLorFVS1rdxXGZ3V2OP:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/7ae0c617c1a3bee2925b2fc0e1916f8c1dea9b08/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json#L186)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> it may need to removed and uploaded again."
> ```
How about a more specific message. "If this persists, please upload a new file."
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-12 06:11 UTC, irahopkinson reviewed
Its definitely been translated into Spanish and French since all those strings from that file have been translated. Possibly others as well but I haven't found a way in crowdin to look at the progress of a particular string.

> Reviewed 9 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/861#-:-MLv3HlfB329FoPs2Whg:b7h70tz)* status: 4 of 8 files reviewed, 4 unresolved discussions (waiting on @irahopkinson and @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2020-11-13 17:28 UTC, RaymondLuong3 approved these changes
> Reviewed 4 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/861)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-19 20:25 UTC, nigel-wells reviewed
Have rebased on `master` and run tests again. Anything else required on this before merging?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/861#-:-MMXAfXy4-aDT95LbI8c:b5b83kj)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-23 12:11 UTC, irahopkinson approved these changes
> Reviewed 4 of 16 files at r1, 4 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/861)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-23 12:11 UTC, merged