SF-1121 Don't show not-registered projects in connect list
sillsdev/web-xforge pull request #862
Opened 2020-11-04 19:38 UTC by marksvc

- We don't currently support connecting to a project that isn't listed
  in the PT Registry, like back translation projects can be.
- Omit such not-registered projects from the list returned by
  ParatextService GetProjectsAsync().

2020-11-05 09:40 UTC, irahopkinson requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/862)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc)

___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 220 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/862#-MLMieLD8OC4QptN2ME8:-MLMieLD8OC4QptN2ME9:b-35kpbk) ([raw file](https://github.com/sillsdev/web-xforge/blob/7702eede0d5b593caf52758f6d92ab1c6e76bae3/src/SIL.XForge.Scripture/Services/ParatextService.cs#L220)):*
> ```
> metadata.ProjectGuid == project.SendReceiveId
> ```
I'm failing to understand why this means that a project is not in the registry? It also makes code in `GetProjects` redundant (which is probably ok). However, given the code that is made redundant in `GetProjects`, my concern is that this will remove more projects than we want it to.


<!-- Sent from Reviewable.io -->

2020-11-06 22:51 UTC, marksvc reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/862)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 220 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/862#-MLMieLD8OC4QptN2ME8:-MLUeDju9TYvc4unZ6oj:b-yloqeg) ([raw file](https://github.com/sillsdev/web-xforge/blob/7702eede0d5b593caf52758f6d92ab1c6e76bae3/src/SIL.XForge.Scripture/Services/ParatextService.cs#L220)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> metadata.ProjectGuid == project.SendReceiveId
> ```
I'm failing to understand why this means that a project is not in the registry? It also makes code in `GetProjects` redundant (which is probably ok). However, given the code that is made redundant in `GetProjects`, my concern is that this will remove more projects than we want it to.
</blockquote></details>

Thank you. I agree, especially now that I have thought about SendReceiveAsync() more and that we had projects during migration that didn't have a full name available, and therefore must now have been in the PT Registry. 

Why it means that a project is not in the registry: 

remotePtProjects = ptRepoSource.GetRepositories() will likely end up in ParatextData InternetSharedRepositorySource GetRepositories(licenses), which fetches project hg repositories that are available to clone.

projectMetadata = ptRepoSource.GetProjectsMetaData() is a SF (not ParatextData) method in JwtInternetSharedRepositorySource, and will fetch projects from the Paratext Registry. 

So then 

remotePtProjects.RemoveAll( projects where 
  there isn't any projectMetadata item whose ProjectGuid matches the given project's SendReceiveId)

should remove from remotePtProjects all projects not in the registry. 
(Or I'm totally not correctly thinking about how the set logic works here, which is possible).


<!-- Sent from Reviewable.io -->

2020-11-06 22:52 UTC, marksvc commented
I converted the PR to a draft while I look into something.

2020-11-12 19:46 UTC, marksvc commented
I investigated and posted my findings and conclusion in a comment to SF-1121. I am marking this PR as ready for review.

2020-11-13 08:11 UTC, irahopkinson approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/862)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-13 08:28 UTC, merged