Add ability to import questions from Transcelerator
sillsdev/web-xforge pull request #863
Opened 2020-11-06 04:04 UTC by Nateowami

## Main dialog
![](https://user-images.githubusercontent.com/6140710/98307386-a000e980-1f93-11eb-9a4a-ab2793a80310.png)
## Confirmation dialog
![](https://user-images.githubusercontent.com/6140710/98307384-9f685300-1f93-11eb-9d68-6c14835d8c84.png)
## Importing status dialog
![](https://user-images.githubusercontent.com/6140710/98307393-a42d0700-1f93-11eb-9044-fdc25a274455.png)

2020-11-06 04:26 UTC, Nateowami reviewed
So, the tests in the RealtimeServer are failing, because it never occurred to me that I needed to run them. I'll work on fixing them. 

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/863#-:-MLQnGbc0Hpj9ssxnwLO:bdfv8fe)* status: 0 of 33 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-06 19:51 UTC, RaymondLuong3 reviewed
Amazing work! Most of my comments are simple fixes.

> Reviewed 33 of 33 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/863#-:-MLU611sA9SdrB5H_reb:b-ath5gv)* status: all files reviewed, 14 unresolved discussions (waiting on @Nateowami)

___
*[src/SIL.XForge/Services/TransceleratorService.cs, line 33 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/863#-MLU5B7t4G4uNcRqOJ3Z:-MLU5B7t4G4uNcRqOJ3_:bu9z5d0) ([raw file](https://github.com/sillsdev/web-xforge/blob/40eff87cb474053dd14b68680260573dbcba88e3/src/SIL.XForge/Services/TransceleratorService.cs#L33)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>         public bool HasQuestions(string paratextId)
>         {
>             return QuestionFiles(paratextId).Count() > 0;
>         }
> ```
</details>

I don't see a real advantage of having this method, since it is nearly as expensive as calling `TransceleratorService.Questions()`. This could just be removed.
___
*[src/SIL.XForge/Services/TransceleratorService.cs, line 41 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/863#-MLTntUoCYW6scwBGfxJ:-MLTntUoCYW6scwBGfxK:blne0yq) ([raw file](https://github.com/sillsdev/web-xforge/blob/40eff87cb474053dd14b68680260573dbcba88e3/src/SIL.XForge/Services/TransceleratorService.cs#L41)):*
> ```
> new int[] { 1, 1 }
> ```
You should be able to pull this value out into `appsettings.json` and then create a `TransceleratorOptions.cs` just like how you are using `SiteOptions` above.
___
*[src/SIL.XForge/Services/TransceleratorService.cs, line 73 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/863#-MLTp_BN6PYchdkBzn4I:-MLTp_BN6PYchdkBzn4J:b-asielp) ([raw file](https://github.com/sillsdev/web-xforge/blob/40eff87cb474053dd14b68680260573dbcba88e3/src/SIL.XForge/Services/TransceleratorService.cs#L73)):*
> ```
> _fileService.DirectoryExists(pathToFiles) ?
> ```
Nit: I've seen the question mark more often place on the next line.
___
*[src/SIL.XForge/Services/TransceleratorService.cs, line 91 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/863#-MLTqCPyEDjDz7Cx8gfp:-MLTqCPyEDjDz7Cx8gfq:b-pdp8tm) ([raw file](https://github.com/sillsdev/web-xforge/blob/40eff87cb474053dd14b68680260573dbcba88e3/src/SIL.XForge/Services/TransceleratorService.cs#L91)):*
> ```
> .DefaultIfEmpty("").SingleOrDefault();
> ```
So this means there is a possibility of an empty question if it's hasn't been translated. Do we handle that?
___
*[src/SIL.XForge/Services/TransceleratorService.cs, line 118 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/863#-MLTrVK66vPCP_I7YJwX:-MLTrVK66vPCP_I7YJwY:b-cyxzo7) ([raw file](https://github.com/sillsdev/web-xforge/blob/40eff87cb474053dd14b68680260573dbcba88e3/src/SIL.XForge/Services/TransceleratorService.cs#L118)):*
> ```
>  return versionStrings.Length >= numbersToSatisfy.Length;
> ```
So transcelerator version 1.1.1 would satisfy 1.1. Ok
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.html, line 8 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/863#-MLTst8D1WFr0GF3DSWA:-MLTst8D1WFr0GF3DSWB:b3lztpo) ([raw file](https://github.com/sillsdev/web-xforge/blob/40eff87cb474053dd14b68680260573dbcba88e3/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.html#L8)):*
> ```
>             <mdc-data-table>
>               <table mdcDataTableTable>
>                 <thead>
> ```
mdcDataTableTable - That's an unfortunate name.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts, line 154 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/863#-MLTwUGcEq4f2EiV0s8y:-MLTwUGcEq4f2EiV0s8z:b-v05fwb) ([raw file](https://github.com/sillsdev/web-xforge/blob/40eff87cb474053dd14b68680260573dbcba88e3/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts#L154)):*
> ```
>   get selectedCount() {
>     return this.questionList.filter(question => question.checked).length;
>   }
> ```
I would group getters below the constructor.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts, line 200 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/863#-MLTz5ys5iHp030jZcCK:-MLTz5ys5iHp030jZcCL:b-e5wfn3) ([raw file](https://github.com/sillsdev/web-xforge/blob/40eff87cb474053dd14b68680260573dbcba88e3/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts#L200)):*
> ```
>     for (const listItem of this.questionList) {
>       if (listItem.matchesFilter) {
> ```
could this be simplified to `for (const listItem of this.filteredList)`
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts, line 221 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/863#-MLU1KY6CgFzOj1PigbZ:-MLU1KY6CgFzOj1Pigb_:b-i3mmvi) ([raw file](https://github.com/sillsdev/web-xforge/blob/40eff87cb474053dd14b68680260573dbcba88e3/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts#L221)):*
> ```
> isBetweenRefs(ref: VerseRef, from: VerseRef | null, to?: VerseRef | null): boolean {
> ```
This can be private.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts, line 228 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/863#-MLU1Mev-YUnP8qfKV4c:-MLU1Mev-YUnP8qfKV4d:bwf739k) ([raw file](https://github.com/sillsdev/web-xforge/blob/40eff87cb474053dd14b68680260573dbcba88e3/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts#L228)):*
> ```
> async confirmEditsIfNecessary(changes: DialogListItem[]): Promise<void> {
> ```
This method can be private.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts, line 273 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/863#-MLU-Nb6CbIJ8UwIwAYO:-MLU-Nb6CbIJ8UwIwAYP:b-y7flky) ([raw file](https://github.com/sillsdev/web-xforge/blob/40eff87cb474053dd14b68680260573dbcba88e3/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts#L273)):*
> ```
> listItem.alreadyImportedQuestion.data &&
> ```
This should include checking != null
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts, line 277 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/863#-MLU-jEODaNqJ4x7HZnL:-MLU-jEODaNqJ4x7HZnM:b-9zqs1w) ([raw file](https://github.com/sillsdev/web-xforge/blob/40eff87cb474053dd14b68680260573dbcba88e3/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts#L277)):*
> ```
> op.set(q => q.text!, listItem.question.text).set(q => q.dateModified, currentDate)
> ```
Cool, I didn't realize you could chain operations like this.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-progress-dialog/import-questions-progress-dialog.component.html, line 5 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/863#-MLU2ieUEC51F8zj6l3e:-MLU2ieV7sAPeM3bySfH:b-jtk4yv) ([raw file](https://github.com/sillsdev/web-xforge/blob/40eff87cb474053dd14b68680260573dbcba88e3/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-progress-dialog/import-questions-progress-dialog.component.html#L5)):*
> ```
> <mdc-dialog-title>Importing {{ data.count }} questions...</mdc-dialog-title>
> ```
You will want to internationalize this title.
___
*[src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/non_checking_en.json, line 104 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/863#-MLU3ONa5HNaMo24qZMe:-MLU3ONa5HNaMo [...]

2020-11-06 23:30 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/863)* status: 30 of 33 files reviewed, 9 unresolved discussions (waiting on @RaymondLuong3)

___
*[src/SIL.XForge/Services/TransceleratorService.cs, line 33 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/863#-MLU5B7t4G4uNcRqOJ3Z:-MLU85vI8qyAvlrHM0mS:bo20dou) ([raw file](https://github.com/sillsdev/web-xforge/blob/40eff87cb474053dd14b68680260573dbcba88e3/src/SIL.XForge/Services/TransceleratorService.cs#L33)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
>         public bool HasQuestions(string paratextId)
>         {
>             return QuestionFiles(paratextId).Count() > 0;
>         }
> ```
I don't see a real advantage of having this method, since it is nearly as expensive as calling `TransceleratorService.Questions()`. This could just be removed.
</blockquote></details>

It's exposed as an API method for determining whether to show the button to open the dialog. We _could_ have the front end fetch questions and check the length of returned array, but that requires sending a _lot_ more data to the front end. Additionally, I don't think this is anywhere near as expensive. All it does enumerate files in a directory and filter for those that match a fairly simple regex. `TransceleratorService.Questions()` opens those (potentially huge) files, parses the XML, and manipulates it to create a list of questions for the front end. In most cases the user will not click the button, and just knowing whether to show it will be sufficient. `TransceleratorService.Questions()` is also far more likely to throw an error, since there are far more places for things to go wrong.
___
*[src/SIL.XForge/Services/TransceleratorService.cs, line 41 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/863#-MLTntUoCYW6scwBGfxJ:-MLU9h2G9aihebMLlR4d:blafsfz) ([raw file](https://github.com/sillsdev/web-xforge/blob/40eff87cb474053dd14b68680260573dbcba88e3/src/SIL.XForge/Services/TransceleratorService.cs#L41)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> new int[] { 1, 1 }
> ```
You should be able to pull this value out into `appsettings.json` and then create a `TransceleratorOptions.cs` just like how you are using `SiteOptions` above.
</blockquote></details>

I don't really see a reason for putting this in a settings file, since it's more a property of the surrounding code than anything else. Tom Bogle added the ID attribute to each question node for the sake of Scripture Forge, and a new version of Transcelerator was released. The schema version when this change was introduce was bumped to 1.1, and so this code, before reading properties that might not exist, checks that the schema version is at least 1.1, since that's what it was written to work with. The only reason we might change this value is because we change the lines that follow to make more assumptions about what the XML document will contain.
___
*[src/SIL.XForge/Services/TransceleratorService.cs, line 73 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/863#-MLTp_BN6PYchdkBzn4I:-MLUBX5P69cmvzL5CBYq:b-qu6n94) ([raw file](https://github.com/sillsdev/web-xforge/blob/40eff87cb474053dd14b68680260573dbcba88e3/src/SIL.XForge/Services/TransceleratorService.cs#L73)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> _fileService.DirectoryExists(pathToFiles) ?
> ```
Nit: I've seen the question mark more often place on the next line.
</blockquote></details>

Good point. Done.
___
*[src/SIL.XForge/Services/TransceleratorService.cs, line 91 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/863#-MLTqCPyEDjDz7Cx8gfp:-MLUBmIO9XKj63w9qx1a:bhpfwd6) ([raw file](https://github.com/sillsdev/web-xforge/blob/40eff87cb474053dd14b68680260573dbcba88e3/src/SIL.XForge/Services/TransceleratorService.cs#L91)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
> .DefaultIfEmpty("").SingleOrDefault();
> ```
So this means there is a possibility of an empty question if it's hasn't been translated. Do we handle that?
</blockquote></details>

We use this both for the question text and the answer text. The only way we could end up with the default is if `nodes.Where(node => lang.Equals(node.Attributes["xml:lang"].Value))` ended up with length 0, meaning there is no node matching a given language. I doubt Transcelerator would generate such a file, but it seemed better to default to an empty string than to throw an exception, especially since it could be the answer text, which we're not doing anything with anyway (perhaps I should just rip the example answer out of the model).

I would assume users can have empty questions (I wouldn't expect Transcelerator to throw an error dialog at a user saying "you may not leave this field until you type at least one character in it"). Therefore, the possibility of empty questions probably exists already. I suppose we could choose to hide them. Right now we treat them as any other question and let the user do with them as they want.
___
*[src/SIL.XForge/Services/TransceleratorService.cs, line 118 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/863#-MLTrVK66vPCP_I7YJwX:-MLUDgzm7zy9VNUJCMW9:bdvfqbb) ([raw file](https://github.com/sillsdev/web-xforge/blob/40eff87cb474053dd14b68680260573dbcba88e3/src/SIL.XForge/Services/TransceleratorService.cs#L118)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
>  return versionStrings.Length >= numbersToSatisfy.Length;
> ```
So transcelerator version 1.1.1 would satisfy 1.1. Ok
</blockquote></details>

I'll add a comment where we check the version above, that it's a schema version, not the version of Transcelerator. (But the schema is defined by Transcelerator, so they're related).
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.html, line 8 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/863#-MLTst8D1WFr0GF3DSWA:-MLUDxqwBkQWn0mgeWLv:bo6apac) ([raw file](https://github.com/sillsdev/web-xforge/blob/40eff87cb474053dd14b68680260573dbcba88e3/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.html#L8)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
>             <mdc-data-table>
>               <table mdcDataTableTable>
>                 <thead>
> ```
mdcDataTableTable - That's an unfortunate name.
</blockquote></details>

Indeed.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts, line 154 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/863#-MLTwUGcEq4f2EiV0s8y:-MLUkKLRBscOKXBirSyi:b-qu6n94) ([raw file](https://github.com/sillsdev/web-xforge/blob/40eff87cb474053dd14b68680260573dbcba88e3/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts#L154)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
>   get selectedCount() {
>     return this.questionList.filter(question => question.checked).length;
>   }
> ```
I would group getters below the constructor.
</blockquote></details>

Good point. Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts, line 200 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/863#-MLTz5ys5iHp030jZcCK:-MLUjbJqDU8R-KJES7C4:boj1qgt) ([raw file](https://github.com/sillsdev/web-xforge/blob/40eff87cb474053dd14b68680260573dbcba88e3/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts#L200)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary> [...]

2020-11-07 03:26 UTC, Nateowami reviewed
@raymondluong3 I've made a number of changes relating to verse ranges, which I had missed earlier.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/863#-:-MLVjLNK8mnymlQJ5q3N:bqydzqh)* status: 28 of 33 files reviewed, 9 unresolved discussions (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2020-11-09 16:21 UTC, irahopkinson requested changes
> Reviewed 28 of 33 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/863)* status: all files reviewed, 15 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)

___
*[src/SIL.XForge/Services/TransceleratorService.cs, line 11 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/863#-MLhaNB72LQB7L6Cqw9m:-MLhaNBABDPmtn2nJmzm:berkshz) ([raw file](https://github.com/sillsdev/web-xforge/blob/a4a06cbe5592a5c0c68360a11acbc48a1f736963/src/SIL.XForge/Services/TransceleratorService.cs#L11)):*
> ```
> public class TransceleratorQuestion
> ```
This would typically go in its own file in `..\Models\`.
___
*[src/SIL.XForge/Services/TransceleratorService.cs, line 23 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/863#-MLhaq_42lVZXZbKaF_M:-MLhaq_59dny5Ed_aFuL:bbhtpu8) ([raw file](https://github.com/sillsdev/web-xforge/blob/a4a06cbe5592a5c0c68360a11acbc48a1f736963/src/SIL.XForge/Services/TransceleratorService.cs#L23)):*
> ```
> TransceleratorService
> ```
Any reason this is here rather than `src\SIL.XForge.Scripture` (which is where I would expect it to be since it is SF specific)?
___
*[src/SIL.XForge/Services/TransceleratorService.cs, line 41 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/863#-MLhbm8wES4rMsL8gKJf:-MLhbm8x2uASxpaMcr3m:b5m5e1w) ([raw file](https://github.com/sillsdev/web-xforge/blob/a4a06cbe5592a5c0c68360a11acbc48a1f736963/src/SIL.XForge/Services/TransceleratorService.cs#L41)):*
> ```
> decalred
> ```
nit: typo
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts, line 198 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/863#-MLhn1-Q9AUNGct4V4Mo:-MLhn1-R73zXHjuU1RwG:b-r6hmo0) ([raw file](https://github.com/sillsdev/web-xforge/blob/a4a06cbe5592a5c0c68360a11acbc48a1f736963/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts#L198)):*
> ```
> console.error(e);
> ```
These look like debug changes. Seems like you should revert changes to this file.
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/command.service.ts, line 70 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/863#-MLhnWlC-kNGf4l9NBHy:-MLhnWlC-kNGf4l9NBHz:bnhze7t) ([raw file](https://github.com/sillsdev/web-xforge/blob/a4a06cbe5592a5c0c68360a11acbc48a1f736963/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/command.service.ts#L70)):*
> ```
>  as T
> ```
I'm not convinced the changes you made to this file are a good idea. Can you explain?
___
*[test/SIL.XForge.Tests/Services/TransceleratorServiceTests.cs, line 19 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/863#-MLhevSE-QlnistI9nrr:-MLhevSE-QlnistI9nrs:bmbquax) ([raw file](https://github.com/sillsdev/web-xforge/blob/a4a06cbe5592a5c0c68360a11acbc48a1f736963/test/SIL.XForge.Tests/Services/TransceleratorServiceTests.cs#L19)):*
> ```
> env.FileSystemService.DirectoryExists(Arg.Any<string>()).Returns(true);
> ```
I don't see why this needs to be declared twice?


<!-- Sent from Reviewable.io -->

2020-11-09 16:26 UTC, irahopkinson reviewed
Ensure the issue number SF-1084 is in the commit message.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/863#-:-MLhoty7CT2ThqcrhqHX:b-og9xir)* status: all files reviewed, 15 unresolved discussions (waiting on @Nateowami and @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2020-11-09 17:17 UTC, RaymondLuong3 approved these changes
I installed Transcelerator 1.5.4 and tried to import questions with it. It looks like version 1.5.4 changes the transcelerator filename, so the option to import is not up to date. On my machine, it becomes "Translations of Checking Questions.xml". This can be addressed in a follow-up commit, but just pointing that out here. I approve once Ira's comments are addressed.

> Reviewed 4 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/863#-:-MLhyS4410ARHLoYNxAS:bj7lxs9)* status: all files reviewed, 7 unresolved discussions (waiting on @Nateowami)

___
*[src/SIL.XForge/Services/TransceleratorService.cs, line 33 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/863#-MLU5B7t4G4uNcRqOJ3Z:-MLhthNy7ugLFmaVE0V8:b-l6advu) ([raw file](https://github.com/sillsdev/web-xforge/blob/40eff87cb474053dd14b68680260573dbcba88e3/src/SIL.XForge/Services/TransceleratorService.cs#L33)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

It's exposed as an API method for determining whether to show the button to open the dialog. We _could_ have the front end fetch questions and check the length of returned array, but that requires sending a _lot_ more data to the front end. Additionally, I don't think this is anywhere near as expensive. All it does enumerate files in a directory and filter for those that match a fairly simple regex. `TransceleratorService.Questions()` opens those (potentially huge) files, parses the XML, and manipulates it to create a list of questions for the front end. In most cases the user will not click the button, and just knowing whether to show it will be sufficient. `TransceleratorService.Questions()` is also far more likely to throw an error, since there are far more places for things to go wrong.
</blockquote></details>

That's a good explanation. I hadn't considered that more often than not a user would not use the import button when visiting the overview page. Thanks.
___
*[src/SIL.XForge/Services/TransceleratorService.cs, line 91 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/863#-MLTqCPyEDjDz7Cx8gfp:-MLhuPEAAup45VtYADGS:bce6jfl) ([raw file](https://github.com/sillsdev/web-xforge/blob/40eff87cb474053dd14b68680260573dbcba88e3/src/SIL.XForge/Services/TransceleratorService.cs#L91)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

We use this both for the question text and the answer text. The only way we could end up with the default is if `nodes.Where(node => lang.Equals(node.Attributes["xml:lang"].Value))` ended up with length 0, meaning there is no node matching a given language. I doubt Transcelerator would generate such a file, but it seemed better to default to an empty string than to throw an exception, especially since it could be the answer text, which we're not doing anything with anyway (perhaps I should just rip the example answer out of the model).

I would assume users can have empty questions (I wouldn't expect Transcelerator to throw an error dialog at a user saying "you may not leave this field until you type at least one character in it"). Therefore, the possibility of empty questions probably exists already. I suppose we could choose to hide them. Right now we treat them as any other question and let the user do with them as they want.
</blockquote></details>

I agree, it is better to show an empty question rather than throwing an error.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts, line 235 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/863#-MLhxLjo4Xvws5DB8LEv:-MLhxLjo4Xvws5DB8LEw:b8ahtkq) ([raw file](https://github.com/sillsdev/web-xforge/blob/a4a06cbe5592a5c0c68360a11acbc48a1f736963/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts#L235)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>               doc.verseRef.bookNum !== verseRefData.bookNum ||
>               doc.verseRef.chapterNum !== verseRefData.chapterNum ||
>               doc.verseRef.verseNum !== verseRefData.verseNum ||
>               doc.verseRef.verse !== verseRefData.verse)
> ```
</details>

This could be more clear with something like this `toVerseRef(doc.verseRef).BBBCCCVVV !== toVerseRef(verseRefData).BBBCCCVVV`


<!-- Sent from Reviewable.io -->

2020-11-09 17:38 UTC, Nateowami reviewed
@raymondluong3 You have to confirm translations and tell Transcelerator to export files for Scripture Forge. The file you're seeing is used internally by Transcelerator and ignored by Scripture Forge. I assume you didn't get the import button? In Transcelerator the option is something like File > Export questions for Scripture Forge.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/863#-:-MLi3rRmCQoc7rNZpGn-:bco8if5)* status: all files reviewed, 6 unresolved discussions (waiting on @Nateowami)



<!-- Sent from Reviewable.io -->

2020-11-09 18:15 UTC, RaymondLuong3 requested changes
Yes you are right. I must not have click the Generate Scripture Forge Files options. I am able to import the translated questions. 

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/863#-:-MLiBZhx5ZbwKn7cpzgH:b-3rl5pk)* status: all files reviewed, 7 unresolved discussions (waiting on @Nateowami)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts, line 276 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/863#-MLiCZ657TqXbKiv6fZQ:-MLiCZ66-QkmhIbjefGH:bxkllhe) ([raw file](https://github.com/sillsdev/web-xforge/blob/a4a06cbe5592a5c0c68360a11acbc48a1f736963/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts#L276)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>       verse:
>         // TODO Right now ignoring end chapter and verse if it's in a different chapter, since we don't yet support that
>         q.startChapter === q.endChapter && q.startVerse !== q.endVerse ? q.startVerse + '-' + q.endVerse : ''
>     };
> ```
</details>

You will want to set verse to undefined instead of the empty string. When you set it to the empty string, the checking component will not correctly set question icon and highlight for the question.


<!-- Sent from Reviewable.io -->

2020-11-09 19:35 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/863)* status: 27 of 33 files reviewed, 7 unresolved discussions (waiting on @irahopkinson and @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts, line 235 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/863#-MLhxLjo4Xvws5DB8LEv:-MLiE1EB50lS6-BI7URv:bgj31rm) ([raw file](https://github.com/sillsdev/web-xforge/blob/a4a06cbe5592a5c0c68360a11acbc48a1f736963/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts#L235)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
>               doc.verseRef.bookNum !== verseRefData.bookNum ||
>               doc.verseRef.chapterNum !== verseRefData.chapterNum ||
>               doc.verseRef.verseNum !== verseRefData.verseNum ||
>               doc.verseRef.verse !== verseRefData.verse)
> ```
This could be more clear with something like this `toVerseRef(doc.verseRef).BBBCCCVVV !== toVerseRef(verseRefData).BBBCCCVVV`
</blockquote></details>

Thanks. Done (with a slight needed change).
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts, line 276 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/863#-MLiCZ657TqXbKiv6fZQ:-MLiEU2vCmq6xZR837BB:b-i21bbo) ([raw file](https://github.com/sillsdev/web-xforge/blob/a4a06cbe5592a5c0c68360a11acbc48a1f736963/src/SIL.XForge.Scripture/ClientApp/src/app/checking/import-questions-dialog/import-questions-dialog.component.ts#L276)):*
<details><summary><i>Previously, RaymondLuong3 (Raymond Luong) wrote…</i></summary><blockquote>

> ```
>       verse:
>         // TODO Right now ignoring end chapter and verse if it's in a different chapter, since we don't yet support that
>         q.startChapter === q.endChapter && q.startVerse !== q.endVerse ? q.startVerse + '-' + q.endVerse : ''
>     };
> ```
You will want to set verse to undefined instead of the empty string. When you set it to the empty string, the checking component will not correctly set question icon and highlight for the question.
</blockquote></details>

Thanks. Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts, line 198 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/863#-MLhn1-Q9AUNGct4V4Mo:-MLiMid141PbNe_bENa5:be6wjnq) ([raw file](https://github.com/sillsdev/web-xforge/blob/a4a06cbe5592a5c0c68360a11acbc48a1f736963/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts#L198)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> console.error(e);
> ```
These look like debug changes. Seems like you should revert changes to this file.
</blockquote></details>

I made these changes because at present the error is basically dropped and the user can't determine what the cause was, even if the user is a developer. Most errors are sent to our error handler where they are logged and then reported. I was running into this error a lot and didn't like that I couldn't see the cause. I think this should be a permanent change, but perhaps should be in a different PR.
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/command.service.ts, line 70 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/863#-MLhnWlC-kNGf4l9NBHy:-MLiJs189zV8finUPkYC:b-nwxiia) ([raw file](https://github.com/sillsdev/web-xforge/blob/a4a06cbe5592a5c0c68360a11acbc48a1f736963/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/command.service.ts#L70)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
>  as T
> ```
I'm not convinced the changes you made to this file are a good idea. Can you explain?
</blockquote></details>

I only partially remember the reason for this, but for some reason if I revert it now, nothing breaks (I don't think that was the case at the time I wrote it, which seems odd). Reverted.
___
*[src/SIL.XForge/Services/TransceleratorService.cs, line 11 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/863#-MLhaNB72LQB7L6Cqw9m:-MLi8r7j-ITCWGt5GV8b:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/a4a06cbe5592a5c0c68360a11acbc48a1f736963/src/SIL.XForge/Services/TransceleratorService.cs#L11)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> public class TransceleratorQuestion
> ```
This would typically go in its own file in `..\Models\`.
</blockquote></details>

Done.
___
*[src/SIL.XForge/Services/TransceleratorService.cs, line 23 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/863#-MLhaq_42lVZXZbKaF_M:-MLiCJQS4pWuNaoY6mT8:bbmtq0m) ([raw file](https://github.com/sillsdev/web-xforge/blob/a4a06cbe5592a5c0c68360a11acbc48a1f736963/src/SIL.XForge/Services/TransceleratorService.cs#L23)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> TransceleratorService
> ```
Any reason this is here rather than `src\SIL.XForge.Scripture` (which is where I would expect it to be since it is SF specific)?
</blockquote></details>

Thanks. Moved it.
___
*[test/SIL.XForge.Tests/Services/TransceleratorServiceTests.cs, line 19 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/863#-MLhevSE-QlnistI9nrr:-MLiCcLi-g5qVQylgkqj:b9cql6i) ([raw file](https://github.com/sillsdev/web-xforge/blob/a4a06cbe5592a5c0c68360a11acbc48a1f736963/test/SIL.XForge.Tests/Services/TransceleratorServiceTests.cs#L19)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> env.FileSystemService.DirectoryExists(Arg.Any<string>()).Returns(true);
> ```
I don't see why this needs to be declared twice?
</blockquote></details>

Thanks. Fixed.


<!-- Sent from Reviewable.io -->

2020-11-09 20:08 UTC, RaymondLuong3 approved these changes
> Reviewed 8 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/863)* status: all files reviewed, 5 unresolved discussions (waiting on @irahopkinson)



<!-- Sent from Reviewable.io -->

2020-11-10 09:14 UTC, irahopkinson approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 7 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/863#-:-MLlQaCj5RgQsO7dvGGY:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts, line 198 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/863#-MLhn1-Q9AUNGct4V4Mo:-MLlO8SS8pWxqLMC9_jg:b-6rssz) ([raw file](https://github.com/sillsdev/web-xforge/blob/a4a06cbe5592a5c0c68360a11acbc48a1f736963/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts#L198)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I made these changes because at present the error is basically dropped and the user can't determine what the cause was, even if the user is a developer. Most errors are sent to our error handler where they are logged and then reported. I was running into this error a lot and didn't like that I couldn't see the cause. I think this should be a permanent change, but perhaps should be in a different PR.
</blockquote></details>

Ok, and I'm fine with them being in this PR. Perhaps a comment then.


<!-- Sent from Reviewable.io -->

2020-11-10 09:15 UTC, merged