SF-1156 - Migrate IndexedDB
sillsdev/web-xforge pull request #895
Opened 2020-12-16 03:30 UTC by nigel-wells

- Forces users from beta to master website unless loaded via iframe
- Checks to see if user has completed migration from beta and displays a dialog
- After migration is completed the user is removed from Mongo

## Summary
This migration is really just a way to programmatically force users to the `master` site and then load up the old `beta` in the background. When the `beta` site loads it will then proceed to subscribe to all realtime documents found in IndexDB. Part of the subscription process is to check for pending operations and send them through to the server. Once all subscriptions are finished the migration is complete. Any pending operations will then appear as remote changes on the `master` site.

## Notes
- Users will not be required to login again unless they were already logged out. As both `beta` and `master` are using the same `auth0` portal it will take care of logging in across two separate domains
- If the `beta` site iframe hasn't loaded then it will refresh the iframe every 10 seconds until it loads - users can not proceed until the migration takes place
- The dialog will only appear if a users ID is in the `beta_migration` collection - new users will not have to go through the process
- Once all users have been removed from the `beta_migration` collection the beta virtual host can be safely shutdown and a permanent redirect setup from `beta` to `master` - all migration code can then be removed as well

## Prerequisite
The following needs to be run from the Mongo console to get the `beta_collection` setup with all the current users:
```
db.createCollection("beta_migration");
var betaMigration = db.getCollection("beta_migration");
db.getCollection("users").find().forEach(function(doc) {
    betaMigration.insert({"_id": doc._id});
});
```

## Setup
Please note that if you run through the full setup and load the main `localhost:5000` site, the migration will complete and the user will be removed from the migration list. If you need to test again then you'll need to run the Mongo commands above again.

1. Complete prerequisite
2. Startup `beta` backend: `dotnet watch run --start-ng-serve=listen environment=DevelopmentBeta`
3. Startup `beta` frontend: `ng serve --configuration=developmentBeta`
4. Startup the `master` backend: `dotnet watch run --start-ng-serve=listen environment=Development`
5. Startup the `master` frontend: `ng serve`

## Acceptance tests
- Complete steps 1, 2, & 3 from the setup
- Open a browser to `beta.localhost:9000` and login if required
- Shutdown the `beta` backend (step 2) so that it is now operating in offline mode
- Make changes to any part of the system that deals with realtime documents i.e. texts, questions, users, etc.
- Close the browser down 
- Complete steps 2, 4, & 5 from the setup
- Open a browser to `localhost:5000` and login if required
- A dialog should appear and attempt to connect to `beta.localhost:9000` in the background. All going well it will zip through the progress steps and then close the dialog
- Check for any additions/edits/deletions made on `beta.locatlhost:9000` have appeared correctly on `localhost:5000`

2020-12-17 10:05 UTC, irahopkinson reviewed
I've done a partial review here based on looking at the merge of SF-1155. We probably need to get that fully sorted out on`master` first and then squash a bunch of your changes here and rebase.

> Reviewed 28 of 32 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/895#-:-MOjnyyX86kNtnRzSs9I:b-wv52af)* status: 28 of 32 files reviewed, 12 unresolved discussions (waiting on @nigel-wells)

___
*[src/SIL.XForge/DataAccess/DataAccessServiceCollectionExtensions.cs, line 43 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/895#-MOjzJ4W8l6cXQP64a4B:-MOjzJ4X4lgaT6sEhPkM:bzdygf) ([raw file](https://github.com/sillsdev/web-xforge/blob/6b02cd70bf160c6e0c6533a4ca8c3e595c5c12cd/src/SIL.XForge/DataAccess/DataAccessServiceCollectionExtensions.cs#L43)):*
> ```
> beta_migration
> ```
This actually a list of users. Perhaps it would be better named "users_beta_migration"?
___
*[src/SIL.XForge.Scripture/appsettings.json, line 13 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/895#-MOjnbBh7vTLTci3ijr8:-MOjnbBh7vTLTci3ijr9:btwn3u7) ([raw file](https://github.com/sillsdev/web-xforge/blob/6b02cd70bf160c6e0c6533a4ca8c3e595c5c12cd/src/SIL.XForge.Scripture/appsettings.json#L13)):*
> ```
> "Beta": false,
> ```
I'm not seeing this set to `true` anywhere. Is this used?
___
*[src/SIL.XForge.Scripture/appsettings.json, line 27 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/895#-MOjmnCA-AIHMISl2kJ3:-MOjmnCA-AIHMISl2kJ4:b-2hxcso) ([raw file](https://github.com/sillsdev/web-xforge/blob/6b02cd70bf160c6e0c6533a4ca8c3e595c5c12cd/src/SIL.XForge.Scripture/appsettings.json#L27)):*
> ```
> 9003
> ```
We want to end up with non-beta on the original port so revert the change to this line. That probably means you need to change the corresponding setting as well.
___
*[src/SIL.XForge.Scripture/appsettings.DevelopmentBeta.json, line 25 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/895#-MOjnGMH2_CXl7PfieKX:-MOjnGMH2_CXl7PfieKY:b-s9jouc) ([raw file](https://github.com/sillsdev/web-xforge/blob/6b02cd70bf160c6e0c6533a4ca8c3e595c5c12cd/src/SIL.XForge.Scripture/appsettings.DevelopmentBeta.json#L25)):*
> ```
> 5003
> ```
We want to end up with non-beta on the original port so revert the change to this line. That probably means you need to change the corresponding setting as well.
___
*[src/SIL.XForge.Scripture/appsettings.Testing.json, line 10 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/895#-MOjko1R1aOf3CJ7YVHC:-MOjko1R1aOf3CJ7YVHD:btphsde) ([raw file](https://github.com/sillsdev/web-xforge/blob/6b02cd70bf160c6e0c6533a4ca8c3e595c5c12cd/src/SIL.XForge.Scripture/appsettings.Testing.json#L10)):*
> ```
> "Origin": "http://beta.localhost:9000",
> ```
This is not `appsettings.TestingBeta.json`. Revert changes to this file.
___
*[src/SIL.XForge.Scripture/hosting.Testing.json, line 2 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/895#-MOjl34M9hJ3vB8ckx6a:-MOjl34M9hJ3vB8ckx6b:b-mj5du8) ([raw file](https://github.com/sillsdev/web-xforge/blob/6b02cd70bf160c6e0c6533a4ca8c3e595c5c12cd/src/SIL.XForge.Scripture/hosting.Testing.json#L2)):*
> ```
> "urls": "http://beta.localhost:9000"
> ```
This is not `hosting.TestingBeta.json`. Revert changes to this file.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts, line 111 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/895#-MOk2Nz-8rlrC8npfEPb:-MOk2Nz-8rlrC8npfEPc:b-g4rpg1) ([raw file](https://github.com/sillsdev/web-xforge/blob/6b02cd70bf160c6e0c6533a4ca8c3e595c5c12cd/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L111)):*
> ```
> indexOf(environment.masterUrl) === -1
> ```
Use `include` to make this more readable.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts, line 9 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/895#-MOk6WAK2O9_1qQr4kuX:-MOk6WAK2O9_1qQr4kuY:b6dwjm5) ([raw file](https://github.com/sillsdev/web-xforge/blob/6b02cd70bf160c6e0c6533a4ca8c3e595c5c12cd/src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts#L9)):*
> ```
> /beta-migration-dialog/
> ```
Could be overkill to put the dialog in its own folder when there is a total of 2 components. Not a problem though.
___
*[src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json, line 25 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/895#-MOk7-wU8n6Fz7-cVreZ:-MOk7-wU8n6Fz7-cVre_:bgcgbog) ([raw file](https://github.com/sillsdev/web-xforge/blob/6b02cd70bf160c6e0c6533a4ca8c3e595c5c12cd/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json#L25)):*
> ```
> "beta_migration"
> ```
The migration code will likely get removed before this gets translated and shipped, but maybe not.
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts, line 292 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/895#-MOk8hjr50d4P3sZxP0y:-MOk8hjr50d4P3sZxP0z:b-2ddi42) ([raw file](https://github.com/sillsdev/web-xforge/blob/6b02cd70bf160c6e0c6533a4ca8c3e595c5c12cd/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts#L292)):*
> ```
> error: any
> ```
This is unused and therefore the 2 changes above are also unnecessary.
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts, line 331 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/895#-MOk8qJW4zBrJePx6pt7:-MOk8qJW4zBrJePx6pt8:b-cmsciv) ([raw file](https://github.com/sillsdev/web-xforge/blob/6b02cd70bf160c6e0c6533a4ca8c3e595c5c12cd/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts#L331)):*
> ```
> reject(err);
> ```
This looks like a debugging code and should be removed.
___
*[src/SIL.XForge.Scripture/DataAccess/SFDataAccessApplicationBuilderExtensions.cs, line 1 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/895#-MOk0P9YBXY-OIOwVobp:-MOk0P9YBXY-OIOwVobq:b-w0birs) ([raw file](https://github.com/sillsdev/web-xforge/blob/6b02cd70bf160c6e0c6533a4ca8c3e595c5c12cd/src/SIL.XForge.Scripture/DataAccess/SFDataAccessApplicationBuilderExtensions.cs#L1)):*
> ```
> using SIL.XForge.Models;
> ```
This change doesn't seem necessary. Revert this.
___
*[src/SIL.XForge.Scripture/Properties/launchSettings.json, line 6 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/895#-MOk0fhz2Ebp4J1ivnc5:-MOk0fhz2Ebp4J1ivnc6:b3pookz) ([raw file](https://github.com/sillsdev/web-xforge/blob/6b02cd70bf160c6e0c6533a4ca8c3e595c5c12cd/src/SIL.XForge.Scripture/Properties/launchSettings.json#L6)):*
> ```
> beta.localhost:9000
> ```
Are changes to this file strictly needed? If they are we need to remember to change them back later. Perhaps we need to group any revert-able changes in their own commit at the head of the branch.


<!-- Sent from Reviewable.io -->

2020-12-18 08:42 UTC, irahopkinson reviewed
I finished looking at the rest of the files now. Great job on getting this running!

My last question is around making sure we don't call the RT server on the Beta site even from the backend. We really don't want that ever to occur as corrupting Mongo ShareDB data would be bad. Have you tested for that (e.g. adding break points on the backend to see if you ever hit them)? It might be safer to just to use a flag to not start the beta RT server.

> Reviewed 4 of 32 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/895#-:-MOozb099B4_gQME7_cU:bz8r23q)* status: all files reviewed, 13 unresolved discussions (waiting on @nigel-wells)

___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/beta-migration/beta-migration-dialog/beta-migration-dialog.component.html, line 13 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/895#-MOoq1MG0auk5IACJVgw:-MOoq1MG0auk5IACJVgx:b-xx1s33) ([raw file](https://github.com/sillsdev/web-xforge/blob/6b02cd70bf160c6e0c6533a4ca8c3e595c5c12cd/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/beta-migration/beta-migration-dialog/beta-migration-dialog.component.html#L13)):*
> ```
> *ngIf="progress === 100"
> ```
nit: safer to use `>==`.


<!-- Sent from Reviewable.io -->

2020-12-20 22:58 UTC, nigel-wells reviewed
On dev machines we call `pullAuthUserProfile` after login which then immedately writes to the RT server. I've been able to exclude that call on dev machines and can then not start the RT server at all inside of `Startup.cs`. Out of interest, if somehow something did get updated is it really that bad? Any changes inside of Mongo will make there way through to the `master` site anyway as they all share the same data at the end of the day

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/895#-:-MP1JR9e6q4z8T4MEoeT:b-cty3ek)* status: 0 of 47 files reviewed, 13 unresolved discussions (waiting on @irahopkinson)

___
*[src/SIL.XForge/DataAccess/DataAccessServiceCollectionExtensions.cs, line 43 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/895#-MOjzJ4W8l6cXQP64a4B:-MP0uyZx7c_cNvwd4Rl7:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/6b02cd70bf160c6e0c6533a4ca8c3e595c5c12cd/src/SIL.XForge/DataAccess/DataAccessServiceCollectionExtensions.cs#L43)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> beta_migration
> ```
This actually a list of users. Perhaps it would be better named "users_beta_migration"?
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/appsettings.json, line 13 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/895#-MOjnbBh7vTLTci3ijr8:-MP0ypcH0htAxT4Jfwaz:b-rzjvpe) ([raw file](https://github.com/sillsdev/web-xforge/blob/6b02cd70bf160c6e0c6533a4ca8c3e595c5c12cd/src/SIL.XForge.Scripture/appsettings.json#L13)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> "Beta": false,
> ```
I'm not seeing this set to `true` anywhere. Is this used?
</blockquote></details>

Thought it might be useful when I first started to know if the backend was running the beta version to avoid/allow certain things to happen. I'll see if I can use this in relation to your RT server comments.
___
*[src/SIL.XForge.Scripture/appsettings.json, line 27 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/895#-MOjmnCA-AIHMISl2kJ3:-MP0zK446kvcX2q4QTKO:bn5u24i) ([raw file](https://github.com/sillsdev/web-xforge/blob/6b02cd70bf160c6e0c6533a4ca8c3e595c5c12cd/src/SIL.XForge.Scripture/appsettings.json#L27)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> 9003
> ```
We want to end up with non-beta on the original port so revert the change to this line. That probably means you need to change the corresponding setting as well.
</blockquote></details>

It should be `5003`
___
*[src/SIL.XForge.Scripture/appsettings.DevelopmentBeta.json, line 25 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/895#-MOjnGMH2_CXl7PfieKX:-MP0zbCZDQ8RtQDyEP23:b-kxl99l) ([raw file](https://github.com/sillsdev/web-xforge/blob/6b02cd70bf160c6e0c6533a4ca8c3e595c5c12cd/src/SIL.XForge.Scripture/appsettings.DevelopmentBeta.json#L25)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> 5003
> ```
We want to end up with non-beta on the original port so revert the change to this line. That probably means you need to change the corresponding setting as well.
</blockquote></details>

This should be 9003 - though I see other commits are changing this to zero now...
___
*[src/SIL.XForge.Scripture/appsettings.Testing.json, line 10 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/895#-MOjko1R1aOf3CJ7YVHC:-MP0vLAP5SMX08fwTsF_:b4huiy1) ([raw file](https://github.com/sillsdev/web-xforge/blob/6b02cd70bf160c6e0c6533a4ca8c3e595c5c12cd/src/SIL.XForge.Scripture/appsettings.Testing.json#L10)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> "Origin": "http://beta.localhost:9000",
> ```
This is not `appsettings.TestingBeta.json`. Revert changes to this file.
</blockquote></details>

#copyandpaste #thatswhywehavecodereview
___
*[src/SIL.XForge.Scripture/hosting.Testing.json, line 2 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/895#-MOjl34M9hJ3vB8ckx6a:-MP0viWRAur2cfFABSLv:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/6b02cd70bf160c6e0c6533a4ca8c3e595c5c12cd/src/SIL.XForge.Scripture/hosting.Testing.json#L2)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> "urls": "http://beta.localhost:9000"
> ```
This is not `hosting.TestingBeta.json`. Revert changes to this file.
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts, line 111 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/895#-MOk2Nz-8rlrC8npfEPb:-MP0vsTx1Por9_N3nhVQ:b-ss2ka) ([raw file](https://github.com/sillsdev/web-xforge/blob/6b02cd70bf160c6e0c6533a4ca8c3e595c5c12cd/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L111)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> indexOf(environment.masterUrl) === -1
> ```
Use `include` to make this more readable.
</blockquote></details>

I knew there was another one but couldn't remember!
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts, line 9 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/895#-MOk6WAK2O9_1qQr4kuX:-MP0vx69DadblPLlinXz:be4sngp) ([raw file](https://github.com/sillsdev/web-xforge/blob/6b02cd70bf160c6e0c6533a4ca8c3e595c5c12cd/src/SIL.XForge.Scripture/ClientApp/src/app/app.module.ts#L9)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> /beta-migration-dialog/
> ```
Could be overkill to put the dialog in its own folder when there is a total of 2 components. Not a problem though.
</blockquote></details>

Decided to have them separate as the dialog is used by `master` and the other is used by `beta` inside the iframe.
___
*[src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json, line 25 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/895#-MOk7-wU8n6Fz7-cVreZ:-MP0w6072wDevv_yEYAF:b-x6cgxk) ([raw file](https://github.com/sillsdev/web-xforge/blob/6b02cd70bf160c6e0c6533a4ca8c3e595c5c12cd/src/SIL.XForge.Scripture/ClientApp/src/assets/i18n/checking_en.json#L25)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> "beta_migration"
> ```
The migration code will likely get removed before this gets translated and shipped, but maybe not.
</blockquote></details>

Probably but wanted to avoid hard coding the strings which would also look wrong in review ;)
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts, line 292 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/895#-MOk8hjr50d4P3sZxP0y:-MP0wgFf4Eyf-rWE1-yR:b-93t9yb) ([raw file](https://github.com/sillsdev/web-xforge/blob/6b02cd70bf160c6e0c6533a4ca8c3e595c5c12cd/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts#L292)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> error: any
> ```
This is unused and therefore the 2 changes above are also unnecessary.
</blockquote></details>

Whoops - I was checking something for Nathaniel and clearly didn't remove it.
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts, line 331 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/895#-MOk8qJW4zBrJePx6pt7:-MP0wkGU9cU5OPilBK4q:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/6b02cd70bf160c6e0c6533a4ca8c3e595c5c12cd/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts#L331)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> reject(err);
> ```
This looks like a debugging code and should be removed.
</blockquote></details>

Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/beta-migration/beta-migration-dialog/beta-migration-dialog.component.html, line 13 at  [...]

2021-03-03 06:29 UTC, irahopkinson requested changes
Looking good. Just 3 comments left.

Thanks for that last change to allow testing. If that can be used in production then I think we are all set to go. For example if it all turns to custard on QA we can just enable this and carry on with Beta only until we figure things out.

> Reviewed 24 of 24 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/895#-:-MUqkcdg62e6sDbOpAHK:b-1x4oq5)* status: all files reviewed, 4 unresolved discussions (waiting on @irahopkinson and @nigel-wells)

___
*[src/SIL.XForge.Scripture/Startup.cs, line 177 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/895#-MUqhLjx4E9BGu6cegcq:-MUqhLjx4E9BGu6cegcr:b-tej98p) ([raw file](https://github.com/sillsdev/web-xforge/blob/934ae00d5ed80432479e1990a4adde53125db3c2/src/SIL.XForge.Scripture/Startup.cs#L177)):*
> ```
> // Allow beta to not load the realtime server - useful for testing
> ```
This comment doesn't seem quite correct. I think this would be more accurate "Don't use the realtime server on beta but allow it for testing" or something similar.
___
*[src/SIL.XForge.Scripture/Startup.cs, line 179 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/895#-MUqhs3WCfXagXP1LuNA:-MUqhs3WCfXagXP1LuNB:b-1la7qy) ([raw file](https://github.com/sillsdev/web-xforge/blob/934ae00d5ed80432479e1990a4adde53125db3c2/src/SIL.XForge.Scripture/Startup.cs#L179)):*
> ```
> disable-realtime-server
> ```
I think I would prefer this to be named `disable-beta-realtime-server` since it won't do anything on non-beta.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts, line 113 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/895#-MUqiSRm3bgo8O-xebIS:-MUqiSRm3bgo8O-xebIT:bre3meg) ([raw file](https://github.com/sillsdev/web-xforge/blob/934ae00d5ed80432479e1990a4adde53125db3c2/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L113)):*
> ```
>  // window.location.href = environment.masterUrl + window.location.pathname;
> ```
How come this is commented out? If its not needed then remove the code or add a comment to explain.


<!-- Sent from Reviewable.io -->

2021-03-03 06:50 UTC, irahopkinson requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/895)* status: all files reviewed, 5 unresolved discussions (waiting on @irahopkinson and @nigel-wells)

___
*[src/SIL.XForge.Scripture/Startup.cs, line 179 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/895#-MUqq7BgEhBcsVBVGgf6:-MUqq7BgEhBcsVBVGgf7:b-pfoh1q) ([raw file](https://github.com/sillsdev/web-xforge/blob/934ae00d5ed80432479e1990a4adde53125db3c2/src/SIL.XForge.Scripture/Startup.cs#L179)):*
> ```
> (siteOptions.Value.Beta && Configuration.GetValue<string>("disable-realtime-server") != "yes")
> ```
Err... did you test the setup steps. If its Beta it will be off so we can only enable here. I think this logic needs to be `(siteOptions.Value.Beta && Configuration.GetValue<string>("enable-beta-realtime-server") == "yes")`


<!-- Sent from Reviewable.io -->

2021-03-03 07:00 UTC, irahopkinson reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/895)* status: all files reviewed, 5 unresolved discussions (waiting on @irahopkinson and @nigel-wells)

___
*[src/SIL.XForge.Scripture/Startup.cs, line 179 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/895#-MUqq7BgEhBcsVBVGgf6:-MUqsOEH5TykvwO9qOMf:bddprc0) ([raw file](https://github.com/sillsdev/web-xforge/blob/934ae00d5ed80432479e1990a4adde53125db3c2/src/SIL.XForge.Scripture/Startup.cs#L179)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> (siteOptions.Value.Beta && Configuration.GetValue<string>("disable-realtime-server") != "yes")
> ```
Err... did you test the setup steps. If its Beta it will be off so we can only enable here. I think this logic needs to be `(siteOptions.Value.Beta && Configuration.GetValue<string>("enable-beta-realtime-server") == "yes")`
</blockquote></details>

Actually I think I just fake myself out there. That doesn't change the logic at all. But perhaps its easier to understand?


<!-- Sent from Reviewable.io -->

2021-03-03 21:18 UTC, nigel-wells reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/895)* status: 32 of 33 files reviewed, 4 unresolved discussions (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/Startup.cs, line 177 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/895#-MUqhLjx4E9BGu6cegcq:-MUttLbnD-YPPWjFKFYZ:bebv90k) ([raw file](https://github.com/sillsdev/web-xforge/blob/934ae00d5ed80432479e1990a4adde53125db3c2/src/SIL.XForge.Scripture/Startup.cs#L177)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> // Allow beta to not load the realtime server - useful for testing
> ```
This comment doesn't seem quite correct. I think this would be more accurate "Don't use the realtime server on beta but allow it for testing" or something similar.
</blockquote></details>

It's actually the other way around - unless I'm being back to front again. We always want the realtime server to load except beta now has an option of not loading it. I'll reverse the logic as per your other notes if you feel that's easier to understand.
___
*[src/SIL.XForge.Scripture/Startup.cs, line 179 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/895#-MUqq7BgEhBcsVBVGgf6:-MUtu3f3AczjfBR54bQK:b-ynir3y) ([raw file](https://github.com/sillsdev/web-xforge/blob/934ae00d5ed80432479e1990a4adde53125db3c2/src/SIL.XForge.Scripture/Startup.cs#L179)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Actually I think I just fake myself out there. That doesn't change the logic at all. But perhaps its easier to understand?
</blockquote></details>

As per above comments, I've reversed it around to be "enable" rather than "disable"
___
*[src/SIL.XForge.Scripture/Startup.cs, line 179 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/895#-MUqhs3WCfXagXP1LuNA:-MUtu_Uj5dvFPuCC8xDg:b-o9n3zm) ([raw file](https://github.com/sillsdev/web-xforge/blob/934ae00d5ed80432479e1990a4adde53125db3c2/src/SIL.XForge.Scripture/Startup.cs#L179)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> disable-realtime-server
> ```
I think I would prefer this to be named `disable-beta-realtime-server` since it won't do anything on non-beta.
</blockquote></details>

Changed to `enable-beta-realtime-server` as per other feedback.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts, line 113 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/895#-MUqiSRm3bgo8O-xebIS:-MUts3P3A9fOVgdBI8YA:b-5624mi) ([raw file](https://github.com/sillsdev/web-xforge/blob/934ae00d5ed80432479e1990a4adde53125db3c2/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L113)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
>  // window.location.href = environment.masterUrl + window.location.pathname;
> ```
How come this is commented out? If its not needed then remove the code or add a comment to explain.
</blockquote></details>

Ah yes I completely forgot about doing that before Christmas! This step is actually something we don't want enabled until all testing is finished otherwise you can't test adding content from the beta site as you'll immediately get redirected. Perhaps I should shift this in to its own PR?


<!-- Sent from Reviewable.io -->

2021-03-04 04:00 UTC, irahopkinson approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/895)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts, line 113 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/895#-MUqiSRm3bgo8O-xebIS:-MUvNnNR3ck-abkHF8cX:b-at3vy9) ([raw file](https://github.com/sillsdev/web-xforge/blob/934ae00d5ed80432479e1990a4adde53125db3c2/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L113)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Ah yes I completely forgot about doing that before Christmas! This step is actually something we don't want enabled until all testing is finished otherwise you can't test adding content from the beta site as you'll immediately get redirected. Perhaps I should shift this in to its own PR?
</blockquote></details>

OK so we will need the code un-commented when we ship to QA and Live, right? A comment to that affect would be fine here.


<!-- Sent from Reviewable.io -->

2021-03-04 04:29 UTC, nigel-wells reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/895)* status: 32 of 33 files reviewed, all discussions resolved (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts, line 113 at r3](https://reviewable.io/reviews/sillsdev/web-xforge/895#-MUqiSRm3bgo8O-xebIS:-MUvUfWXD-oUZkseJwSy:bx7yy82) ([raw file](https://github.com/sillsdev/web-xforge/blob/934ae00d5ed80432479e1990a4adde53125db3c2/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L113)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

OK so we will need the code un-commented when we ship to QA and Live, right? A comment to that affect would be fine here.
</blockquote></details>

Well, I imagine you'd initially want to test QA with the current logic and, once that is confirmed as ok, make another release to QA to ensure the redirect works from beta to non-beta.


<!-- Sent from Reviewable.io -->

2021-03-04 04:34 UTC, nigel-wells reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/895)* status: 32 of 33 files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts, line 112 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/895#-MUvUyRNCM7O_RrUKT1Z:-MUvUyRNCM7O_RrUKT1_:b-m7wrxs) ([raw file](https://github.com/sillsdev/web-xforge/blob/c7290c7718d8873d968b62a497550a161e2c3bc2/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L112)):*
> ```XML
>       if (this.isAppOnline && !this.isAppLoading) {
>         // Redirect to the master site unless the referrer was the master site
>         if (environment.beta && document.referrer.includes(environment.masterUrl)) {
> ```

Reading this line now, and the comment above, it sounds the opposite again - perhaps I'm dyslexic? The comment is correct but the code checks beta and redirects if the referrer was master. I believe it should be and the referrer is NOT master then redirect to master. I was sure I tested it at the time but it was last year...


<!-- Sent from Reviewable.io -->

2021-03-04 04:40 UTC, irahopkinson approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/895#-:-MUvUZydEbDZZdJE5xV-:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @nigel-wells)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts, line 112 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/895#-MUvUyRNCM7O_RrUKT1Z:-MUvX7mr3dXejG0S7Lm4:b-bd0rjb) ([raw file](https://github.com/sillsdev/web-xforge/blob/c7290c7718d8873d968b62a497550a161e2c3bc2/src/SIL.XForge.Scripture/ClientApp/src/app/app.component.ts#L112)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Reading this line now, and the comment above, it sounds the opposite again - perhaps I'm dyslexic? The comment is correct but the code checks beta and redirects if the referrer was master. I believe it should be and the referrer is NOT master then redirect to master. I was sure I tested it at the time but it was last year...
</blockquote></details>

Since it doesn't yet do anything and we are only merging to `develop`, I'm going to merge it as is. The PR that uncomments it will need to make sure the logic is correct.


<!-- Sent from Reviewable.io -->

2021-03-04 04:43 UTC, merged