SF-798 Remove user docs and project associations
sillsdev/web-xforge pull request #896
Opened 2020-12-16 20:39 UTC by marksvc

This PR is broken into two commits. The first commit adds some tests and makes some changes to allow for testing. Its commit message is:

SF-798 First add tests and prepare for delete-user implementation

- Add comments.
- Introduce IRealtimeServer to allow mocking.
- Add early-crash argument checking to some methods. This should be
the commit's only behavioural change.
- Expose RemoveUserFromProjectAsync() as internal for unit testing.
- Add tests for existing functionality.
- ProjectServiceTests Sites are expanded to be consistent with
TestProject documents, for these or follow-up tests.

The second commit makes the actual changes for SF-798. Some items to point out are:

- ProjectService RemoveUserAsync() can silently fail if there are
  simultaneous requests. So wrap in a mutex.
- When a sysadmin deletes a user, SF runs UserService
  DeleteAsync(), which calls:
  - ProjectService.RemoveUserFromAllProjectsAsync()
    which calls RemoveUserCoreAsync() for each user doc Sites.Projects
      which calls RemoveUserFromProjectAsync().
  - RealtimeService.DeleteUserAsync(), removing docs from collections
    users, user_secrets, sf_project_user_configs,
    o_users, and o_sf_project_user_configs.
  - And no longer userDoc.DeleteAsync(), which shouldn't be needed
    now.
- RealtimeService DeleteUserAsync() removes docs that are matched by
  '_id' or 'd'. Some of these matches are for the whole field. Some
  matches are just for the ending part of the field (for example a
  sf_project_user_configs, which uses an _id of the format
  project_id:user_id. Further, some collections have corresponding o_
  OT collections, and some do not. How to match the '_id' and 'd', and
  whether there is a corresponding o_ OT collection, is collected in
  an anonymous type that makes use of a Location enum.
  Location.Beginning is included in the enum for completeness.
- The knowledge for what collections to look in, and how to match
  documents to ids, can be defined per-application, and here is done
  in SFRealtimeServiceCollectionExtensions.cs.
- RealtimeService.cs: `foreach.. AddDocConfig(userDataDoc)` may not
  have been necessary, but looked like it could be helpful.

2020-12-19 03:47 UTC, irahopkinson requested changes
Now that this branch is testng without errors, it also needs to be moved before review.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/896#-:-MOt5riRAY6sSxF0NMwv:bs9iuv1)* status: 0 of 42 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-01-06 20:13 UTC, marksvc commented
I rebased the branch onto the adjusted master branch. It's ready for review.

2021-01-09 08:50 UTC, irahopkinson requested changes
This looks fine generally - have only one blocking comment. However I would like @ddaspit to look at it as it does cut into some architectual considerations.

> Reviewed 7 of 13 files at r1, 15 of 15 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/896#-:-MQaKC5p8rf84_v1xh_w:bdug2vj)* status: all files reviewed, 5 unresolved discussions (waiting on @marksvc)

___
*[src/SIL.XForge/Realtime/RealtimeService.cs, line 136 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/896#-MQa44Dr96WQVgo4mjYa:-MQa44Dr96WQVgo4mjYb:b-efewvu) ([raw file](https://github.com/sillsdev/web-xforge/blob/d37a96819bb363995c5dd0c9377b412890621e8e/src/SIL.XForge/Realtime/RealtimeService.cs#L136)):*
> ```
> HasOt
> ```
nit: according to our MS style guide, in C# we honor 2 letter acronyms but not 3+ letter acronyms.
___
*[src/SIL.XForge/Realtime/RealtimeService.cs, line 144 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/896#-MQa5BDi80egkIiBtxx8:-MQa5BDi80egkIiBtxx9:b-i6f2lz) ([raw file](https://github.com/sillsdev/web-xforge/blob/d37a96819bb363995c5dd0c9377b412890621e8e/src/SIL.XForge/Realtime/RealtimeService.cs#L144)):*
> ```
> if (collection.TokenLocationInId == Location.Whole)
> ```
Shouldn't this be a case structure?
___
*[src/SIL.XForge.Scripture/Realtime/SFRealtimeServiceCollectionExtensions.cs, line 32 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/896#-MQaChp_6AGuBgSR5UE2:-MQaChpa5Z1EbwfxFaoK:b-z7igdx) ([raw file](https://github.com/sillsdev/web-xforge/blob/d37a96819bb363995c5dd0c9377b412890621e8e/src/SIL.XForge.Scripture/Realtime/SFRealtimeServiceCollectionExtensions.cs#L32)):*
> ```
> new DocConfig("user_secrets", typeof(UserSecret), null),
> ```
I thought we had talked about not removing from this collection? Isn't it needed for sync? @ddaspit can you confirm also?
___
*[src/SIL.XForge.Scripture/Services/SFServiceCollectionExtensions.cs, line 20 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/896#-MQaDAny3MEDVigNKQPE:-MQaDAny3MEDVigNKQPF:bbqo145) ([raw file](https://github.com/sillsdev/web-xforge/blob/d37a96819bb363995c5dd0c9377b412890621e8e/src/SIL.XForge.Scripture/Services/SFServiceCollectionExtensions.cs#L20)):*
> ```
> // When UserService requests an IProjectService, satisfy it with the SFProjectService.
> ```
This comment seems unecessary.
___
*[test/SIL.XForge.Tests/Services/UserServiceTests.cs, line 198 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/896#-MQaF59rCU6CVBZvwG67:-MQaF59rCU6CVBZvwG68:bgsh505) ([raw file](https://github.com/sillsdev/web-xforge/blob/d37a96819bb363995c5dd0c9377b412890621e8e/test/SIL.XForge.Tests/Services/UserServiceTests.cs#L198)):*
> ```
> MockAuthService
> ```
nit: I'm not sure it is necessary to add `Mock` to this name. The above 2 are also mocks without it in the name. In fact everything is a mock apart from the service being tested, as should be expected.


<!-- Sent from Reviewable.io -->

2021-01-09 08:58 UTC, irahopkinson reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/896)* status: all files reviewed, 6 unresolved discussions (waiting on @marksvc)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-owner/checking-owner.component.ts, line 32 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/896#-MQaM8rf4_XZ9I3zE2mF:-MQaM8riCgBW-esAi3u0:bz93mob) ([raw file](https://github.com/sillsdev/web-xforge/blob/d37a96819bb363995c5dd0c9377b412890621e8e/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-owner/checking-owner.component.ts#L32)):*
> ```
> return this.translocoService.translate('checking.unknown_author');
> ```
Does this cover everywhere another users name could show up? Question, answers, comments?


<!-- Sent from Reviewable.io -->

2021-01-11 04:33 UTC, ddaspit requested changes
> Reviewed 7 of 13 files at r1, 15 of 15 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/896)* status: all files reviewed, 11 unresolved discussions (waiting on @irahopkinson and @marksvc)

___
*[src/SIL.XForge/Realtime/MemoryRealtimeService.cs, line 41 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/896#-MQjf_BvDmB_VEgSebbz:-MQjf_BvDmB_VEgSebc-:b-cv8v8r) ([raw file](https://github.com/sillsdev/web-xforge/blob/d37a96819bb363995c5dd0c9377b412890621e8e/src/SIL.XForge/Realtime/MemoryRealtimeService.cs#L41)):*
> ```Smalltalk
>         /// Count of calls to DeleteUserAsync(), for tests.
>         /// </summary>
>         internal int callCountDeleteUserAsync = 0;
> ```

Since this is externally accessible, I would make this a property.
___
*[src/SIL.XForge/Services/ProjectService.cs, line 97 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/896#-MQjbEmr4I9TUFPnATnR:-MQjbEmr4I9TUFPnATnS:bstp5ui) ([raw file](https://github.com/sillsdev/web-xforge/blob/d37a96819bb363995c5dd0c9377b412890621e8e/src/SIL.XForge/Services/ProjectService.cs#L97)):*
> ```Smalltalk
>                 // Use a mutex, since disassociating a user and a project can be incomplete if there are two
>                 // simultaneous requests regarding two different projects and the same user.
>                 await _userRemoveProjectMutex.WaitAsync();
> ```

This doesn't seem like it should be necessary. Can you give me more details about why a lock is needed?
___
*[src/SIL.XForge/Services/UserService.cs, line 155 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/896#-MQjf2jwAdU0FyHNVmnp:-MQjf2jwAdU0FyHNVmnq:buged16) ([raw file](https://github.com/sillsdev/web-xforge/blob/d37a96819bb363995c5dd0c9377b412890621e8e/src/SIL.XForge/Services/UserService.cs#L155)):*
> ```Smalltalk
>             }
> 
>             await _projectService.RemoveUserFromAllProjectsAsync(curUserId, userId);
> ```

You never submit a delete op for the user doc, i.e. call `IDocument.DeleteAsync()`.
___
*[src/SIL.XForge.Scripture/Realtime/SFRealtimeServiceCollectionExtensions.cs, line 31 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/896#-MQjdVmg0oqumWbQ_zi4:-MQjdVmh-VzxHgdnGT_K:bo2qpfb) ([raw file](https://github.com/sillsdev/web-xforge/blob/d37a96819bb363995c5dd0c9377b412890621e8e/src/SIL.XForge.Scripture/Realtime/SFRealtimeServiceCollectionExtensions.cs#L31)):*
> ```Smalltalk
>                     o.UserDataDocs.AddRange(new[]
>                     {
>                         new DocConfig("users", typeof(User)),
> ```

It looks like you are following the same pattern as project docs, which is a good idea. If you look at the `ProjectDataDocs` property, it includes real-time collections that are associated with a project, but it does not include the collection for the actual project docs. That is defined by the `ProjectDoc` property. You should do the same for the `UserDataDocs`, which means that you should not include the `users` doc config. The `users` doc config is defined by the `UserDoc` property.
___
*[src/SIL.XForge.Scripture/Realtime/SFRealtimeServiceCollectionExtensions.cs, line 32 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/896#-MQaChp_6AGuBgSR5UE2:-MQjcDikDH9igKGmvN59:bxexgh5) ([raw file](https://github.com/sillsdev/web-xforge/blob/d37a96819bb363995c5dd0c9377b412890621e8e/src/SIL.XForge.Scripture/Realtime/SFRealtimeServiceCollectionExtensions.cs#L32)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> new DocConfig("user_secrets", typeof(UserSecret), null),
> ```
I thought we had talked about not removing from this collection? Isn't it needed for sync? @ddaspit can you confirm also?
</blockquote></details>

@irahopkinson, you are thinking of the `SyncUsers` property in the `SFProjectSecret` class. In any case, I would not include this as a user data doc. These are specifically referring to real-time (ShareDB) docs. `UserSecret` docs are not real-time. I would just delete the `UserSecret` doc in `UserService.DeleteAsync()`. 
___
*[src/SIL.XForge.Scripture/Realtime/SFRealtimeServiceCollectionExtensions.cs, line 35 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/896#-MQjeist4pMOVJcs-jqp:-MQjeisu-2rHVWnmVbtQ:b-n57010) ([raw file](https://github.com/sillsdev/web-xforge/blob/d37a96819bb363995c5dd0c9377b412890621e8e/src/SIL.XForge.Scripture/Realtime/SFRealtimeServiceCollectionExtensions.cs#L35)):*
> ```Smalltalk
>                         new DocConfig("sf_project_user_configs", typeof(SFProjectUserConfig))
>                     });
>                     o.UserDataDocsIdLocation = new Dictionary<string, Location>
> ```

With the changes suggested above, I don't think `UserDataDocsIdLocation` is necessary anymore.


<!-- Sent from Reviewable.io -->

2021-01-11 07:21 UTC, ddaspit reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/896)* status: all files reviewed, 13 unresolved discussions (waiting on @irahopkinson and @marksvc)

___
*[src/SIL.XForge/Services/ProjectService.cs, line 86 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/896#-MQkJVi1DaA_ftHP2wiu:-MQkJVi22Ct2g2C_lmVO:b-ont05a) ([raw file](https://github.com/sillsdev/web-xforge/blob/d37a96819bb363995c5dd0c9377b412890621e8e/src/SIL.XForge/Services/ProjectService.cs#L86)):*
> ```Smalltalk
>         /// Disassociate user projectUserId from project projectId, without checking permissions.
>         /// </summary>
>         private async Task RemoveUserCoreAsync(string curUserId, string projectId, string projectUserId)
> ```

You should pass in the connection object from the calling method instead of creating a new one.
___
*[src/SIL.XForge/Services/UserService.cs, line 140 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/896#-MQkJDEj-lG48Zd4EnlL:-MQkJDEj-lG48Zd4EnlM:b-1u61uj) ([raw file](https://github.com/sillsdev/web-xforge/blob/d37a96819bb363995c5dd0c9377b412890621e8e/src/SIL.XForge/Services/UserService.cs#L140)):*
> ```Smalltalk
>             if (string.IsNullOrEmpty(curUserId))
>             {
>                 throw new ArgumentException("", nameof(curUserId));
> ```

These should probably be `ArgumentNullException`s.


<!-- Sent from Reviewable.io -->

2021-01-11 09:16 UTC, ddaspit reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/896)* status: all files reviewed, 13 unresolved discussions (waiting on @irahopkinson and @marksvc)

___
*[src/SIL.XForge/Services/ProjectService.cs, line 97 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/896#-MQjbEmr4I9TUFPnATnR:-MQkiNji3KnOIeQj73Zf:b-ibm6n) ([raw file](https://github.com/sillsdev/web-xforge/blob/d37a96819bb363995c5dd0c9377b412890621e8e/src/SIL.XForge/Services/ProjectService.cs#L97)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

This doesn't seem like it should be necessary. Can you give me more details about why a lock is needed?
</blockquote></details>

I have tried to reproduce the problem that necessitated the lock, but I haven't be able to. I removed the lock and tried to delete a user that is a member of multiple projects and it seemed to work fine. It would be great if you could outline the steps to reproduce the issue. 


<!-- Sent from Reviewable.io -->

2021-01-18 23:04 UTC, marksvc reviewed
Thanks guys. 

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/896#-:-MRMfncT2v4WCrn1WwIC:bnx2ess)* status: 10 of 22 files reviewed, 12 unresolved discussions (waiting on @ddaspit and @irahopkinson)

___
*[src/SIL.XForge/Realtime/MemoryRealtimeService.cs, line 41 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/896#-MQjf_BvDmB_VEgSebbz:-MR6eDNB5L6PXcOUGefH:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/d37a96819bb363995c5dd0c9377b412890621e8e/src/SIL.XForge/Realtime/MemoryRealtimeService.cs#L41)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Since this is externally accessible, I would make this a property.
</blockquote></details>

Done.
___
*[src/SIL.XForge/Realtime/RealtimeService.cs, line 51 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/896#-MRMExH67MllK1sXTcwi:-MRMExH67MllK1sXTcwj:b-obb81s) ([raw file](https://github.com/sillsdev/web-xforge/blob/d37a96819bb363995c5dd0c9377b412890621e8e/src/SIL.XForge/Realtime/RealtimeService.cs#L51)):*
> ```Smalltalk
>             foreach (DocConfig userDataDoc in options.UserDataDocs)
>             {
>                 AddDocConfig(userDataDoc);
> ```

I put this in, based on how these objects were being noted and made lookup-able. But is there any use to doing this? I see that it could conceivably get used by other parts of the code. But it obviously wasn't necessary so far. 
___
*[src/SIL.XForge/Realtime/RealtimeService.cs, line 136 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/896#-MQa44Dr96WQVgo4mjYa:-MRLqMVFDPCqpn_9HsZB:bx7pexv) ([raw file](https://github.com/sillsdev/web-xforge/blob/d37a96819bb363995c5dd0c9377b412890621e8e/src/SIL.XForge/Realtime/RealtimeService.cs#L136)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> HasOt
> ```
nit: according to our MS style guide, in C# we honor 2 letter acronyms but not 3+ letter acronyms.
</blockquote></details>

Done. I am having trouble finding that style guide, or that specific point in the style guides that I was looking at. Can you point me to this resource?
___
*[src/SIL.XForge/Realtime/RealtimeService.cs, line 144 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/896#-MQa5BDi80egkIiBtxx8:-MRMBbQe182QuioFLC91:bcub70c) ([raw file](https://github.com/sillsdev/web-xforge/blob/d37a96819bb363995c5dd0c9377b412890621e8e/src/SIL.XForge/Realtime/RealtimeService.cs#L144)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> if (collection.TokenLocationInId == Location.Whole)
> ```
Shouldn't this be a case structure?
</blockquote></details>

Yes, thank you. But now removed.
___
*[src/SIL.XForge/Services/ProjectService.cs, line 86 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/896#-MQkJVi1DaA_ftHP2wiu:-MRMCBfj3FXpqj7vFqCk:b-wtkc5h) ([raw file](https://github.com/sillsdev/web-xforge/blob/d37a96819bb363995c5dd0c9377b412890621e8e/src/SIL.XForge/Services/ProjectService.cs#L86)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You should pass in the connection object from the calling method instead of creating a new one.
</blockquote></details>

Yes, thank you.
___
*[src/SIL.XForge/Services/ProjectService.cs, line 97 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/896#-MQjbEmr4I9TUFPnATnR:-MRMaRU-AxMDZYLaS2K0:b-cqhoph) ([raw file](https://github.com/sillsdev/web-xforge/blob/d37a96819bb363995c5dd0c9377b412890621e8e/src/SIL.XForge/Services/ProjectService.cs#L97)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

I have tried to reproduce the problem that necessitated the lock, but I haven't be able to. I removed the lock and tried to delete a user that is a member of multiple projects and it seemed to work fine. It would be great if you could outline the steps to reproduce the issue. 
</blockquote></details>

Sure. And it's not regarding deleting a user who is a member of multiple projects. It's about simultaneous requests to disassociate a user from different projects. (In other words, PT-Admin-Bob requests to remove user Charlie from ProjectAlpha. At the exact same time, PT-Admin-Julie requests to remove user Charlie from ProjectBravo.)

In RemoveUserFromProject(), a userDoc is examined and its Data.Sites[].Projects is manipulated by the index of where a project is in the Projects list.
If there are two simultaneous requests that both do
```cs
IDocument<User> userDoc = await GetUserDocAsync(projectUserId, conn);
await RemoveUserFromProjectAsync(conn, projectDoc, userDoc);
```
then the `userDoc` in each case could contain the original list of Projects before either is passed to `RemoveUserFromProjectAsync`. 

So let's say, from the example given earlier in this message, that after each PT Admin makes the removal request, each gets as far as assigning to userDoc but doesn't yet call `RemoveUserFromProjectAsync()`. 
Then PT-Admin-Bob's request runs `RemoveUserFromProjectAsync()` to remove Charlie from ProjectAlpha.
Then PT-Admin-Julie's request runs `RemoveUserFromProjectAsync()`. When this happens, the userDoc passed to `RemoveUserFromProjectAsync()` still contains ProjectAlpha in the user doc Data.Sites[].Projects list. This causes the IndexOf() call to give potentially the wrong result:
```cs
int index = userDoc.Data.Sites[siteId].Projects.IndexOf(projectDoc.Id);
```
And then we attempt to remove an item from the Projects list using the wrong location:
```cs
op.Remove(u => u.Sites[siteId].Projects, index);
```

I wrote a unit test that sets up the problem and included it. If you comment out 
```cs
await _userRemoveProjectMutex.WaitAsync();
``` 
and 
```cs
_userRemoveProjectMutex.Release();
```
you can see test RemoveUserAsync_NoRaceFailure begin to fail. (Or, it is on my computer. The very nature of the race could mean it won't necessarily fail each time or for everyone.)

I tried reproducing this in a couple web browser windows, where two project user lists were shown and I attempted to quickly request that the user be disassociated from the first item in the user's sites.sf.projects list, and immediately request, in the other browser window, that the user be disassociated from the second item in the list. But I can't click fast enough. Maybe two people could try reproducing it with two machines. 

It seems that IConnection.FetchAsync<>() (called from GetUserDocAsync) needs to be called each time a fresh, up-to-date doc is required. 
___
*[src/SIL.XForge/Services/UserService.cs, line 140 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/896#-MQkJDEj-lG48Zd4EnlL:-MRMBMwq7sKtru8kf98y:b-896fix) ([raw file](https://github.com/sillsdev/web-xforge/blob/d37a96819bb363995c5dd0c9377b412890621e8e/src/SIL.XForge/Services/UserService.cs#L140)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

These should probably be `ArgumentNullException`s.
</blockquote></details>

Done.
___
*[src/SIL.XForge/Services/UserService.cs, line 155 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/896#-MQjf2jwAdU0FyHNVmnp:-MRLqoqf1SRYxoEfYgbE:beaeom7) ([raw file](https://github.com/sillsdev/web-xforge/blob/d37a96819bb363995c5dd0c9377b412890621e8e/src/SIL.XForge/Services/UserService.cs#L155)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You never submit a delete op for the user doc, i.e. call `IDocument.DeleteAsync()`.
</blockquote></details>

Right. That's on purpose because I am going to remove the user doc and its OTs in RealtimeService.DeleteUserAsync(). So any trace of whether we do or don't also call `IDocument.DeleteAsync()` on the user doc, will presumably be lost, making it meaningless to call DeleteAsync on the user doc. But maybe I don't have an accurate understanding. How will it help to first do 
```cs
                IDocument<User> userDoc = await conn.FetchAsy [...]

2021-01-19 02:48 UTC, irahopkinson reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/896)* status: 10 of 22 files reviewed, 9 unresolved discussions (waiting on @ddaspit, @irahopkinson, and @RaymondLuong3)

___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-owner/checking-owner.component.ts, line 32 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/896#-MQaM8rf4_XZ9I3zE2mF:-MRNUnsn-GLl9h-hz15A:b6brjxt) ([raw file](https://github.com/sillsdev/web-xforge/blob/d37a96819bb363995c5dd0c9377b412890621e8e/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-owner/checking-owner.component.ts#L32)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Answers - yes
Comments - yes

I'm not sure how to see the author name of a Question. If that's possible, maybe you can give me some pointers.

It looks like a user's display name can also be used in the filename of a recording (displayName + '.webm' in checking-audio-recorder.component.ts). I tried making a recording and playing with that a bit but it wasn't clear how this might be exposed. The resulting file name in /var/lib/scriptureforge/audio/foo/ is an .mp3 file that doesn't contain the user display name anyway, so I'm not sure if I did the right thing actually.

It looks like other usages of a user's display name, in our project's code, should be things that would only work for an existing user.

</blockquote></details>

Questions, answers and comments all inherit from `OwnedData` which contains and `ownerRef` string.
It sounds like the audio filename shouldn't be a problem but you could check with @raymondluong3.


<!-- Sent from Reviewable.io -->

2021-01-19 03:53 UTC, ddaspit requested changes
> Reviewed 12 of 12 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/896)* status: all files reviewed, 3 unresolved discussions (waiting on @marksvc and @RaymondLuong3)

___
*[src/SIL.XForge/Realtime/RealtimeService.cs, line 51 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/896#-MRMExH67MllK1sXTcwi:-MRNkbyt0ZyUveYOX_xC:bv65r9g) ([raw file](https://github.com/sillsdev/web-xforge/blob/d37a96819bb363995c5dd0c9377b412890621e8e/src/SIL.XForge/Realtime/RealtimeService.cs#L51)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

I put this in, based on how these objects were being noted and made lookup-able. But is there any use to doing this? I see that it could conceivably get used by other parts of the code. But it obviously wasn't necessary so far. 
</blockquote></details>

This is the correct. `UserDataDocs` is used so that SIL.XForge doesn't have to know about any of the SF real-time docs.
___
*[src/SIL.XForge/Services/ProjectService.cs, line 97 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/896#-MQjbEmr4I9TUFPnATnR:-MRNdKNDAqjzUElTKJuh:blrz9nr) ([raw file](https://github.com/sillsdev/web-xforge/blob/d37a96819bb363995c5dd0c9377b412890621e8e/src/SIL.XForge/Services/ProjectService.cs#L97)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Sure. And it's not regarding deleting a user who is a member of multiple projects. It's about simultaneous requests to disassociate a user from different projects. (In other words, PT-Admin-Bob requests to remove user Charlie from ProjectAlpha. At the exact same time, PT-Admin-Julie requests to remove user Charlie from ProjectBravo.)

In RemoveUserFromProject(), a userDoc is examined and its Data.Sites[].Projects is manipulated by the index of where a project is in the Projects list.
If there are two simultaneous requests that both do
```cs
IDocument<User> userDoc = await GetUserDocAsync(projectUserId, conn);
await RemoveUserFromProjectAsync(conn, projectDoc, userDoc);
```
then the `userDoc` in each case could contain the original list of Projects before either is passed to `RemoveUserFromProjectAsync`. 

So let's say, from the example given earlier in this message, that after each PT Admin makes the removal request, each gets as far as assigning to userDoc but doesn't yet call `RemoveUserFromProjectAsync()`. 
Then PT-Admin-Bob's request runs `RemoveUserFromProjectAsync()` to remove Charlie from ProjectAlpha.
Then PT-Admin-Julie's request runs `RemoveUserFromProjectAsync()`. When this happens, the userDoc passed to `RemoveUserFromProjectAsync()` still contains ProjectAlpha in the user doc Data.Sites[].Projects list. This causes the IndexOf() call to give potentially the wrong result:
```cs
int index = userDoc.Data.Sites[siteId].Projects.IndexOf(projectDoc.Id);
```
And then we attempt to remove an item from the Projects list using the wrong location:
```cs
op.Remove(u => u.Sites[siteId].Projects, index);
```

I wrote a unit test that sets up the problem and included it. If you comment out 
```cs
await _userRemoveProjectMutex.WaitAsync();
``` 
and 
```cs
_userRemoveProjectMutex.Release();
```
you can see test RemoveUserAsync_NoRaceFailure begin to fail. (Or, it is on my computer. The very nature of the race could mean it won't necessarily fail each time or for everyone.)

I tried reproducing this in a couple web browser windows, where two project user lists were shown and I attempted to quickly request that the user be disassociated from the first item in the user's sites.sf.projects list, and immediately request, in the other browser window, that the user be disassociated from the second item in the list. But I can't click fast enough. Maybe two people could try reproducing it with two machines. 

It seems that IConnection.FetchAsync<>() (called from GetUserDocAsync) needs to be called each time a fresh, up-to-date doc is required. 
</blockquote></details>

The problem you describe should not be possible with ShareDB. ShareDB is specifically designed to handle concurrent edits to the same document. Here is how this scenario works:

1. PT-Admin-Bob requests to remove user Charlie from ProjectAlpha and PT-Admin-Julie requests to remove user Charlie from ProjectBravo at the same time. They both attempt to update the same version of the user doc (version 1).
2. Arbitrarily, PT-Admin-Bob's request is received first.
3. The project id is properly removed from the user doc.
4. The doc version is incremented to 2.
5. PT-Admin-Julie's request is received second.
6. ShareDB realizes that PT-Admin-Julie's op is on an older version of the doc (version 1).
7. ShareDB transforms the PT-Admin-Julie's op according to all of the ops that have occurred since the doc version that PT-Admin-Julie is working on. This means that the index in PT-Admin-Julie's op is updated to reflect that a project id was removed by PT-Admin-Bob's op.
8. The transformed op is applied to the latest version (2) of the doc and the correct project id is removed.
9 The doc version is incremented to 3.

You are only able to reproduce this problem in unit tests, because the mock real-time service does not fully implement concurrent editing of docs. Ultimately, this means that the lock is not necessary. I hope all of that makes sense.
___
*[src/SIL.XForge/Services/UserService.cs, line 155 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/896#-MQjf2jwAdU0FyHNVmnp:-MRNWDtVCCs-Q2JZRYTI:bcfihxw) ([raw file](https://github.com/sillsdev/web-xforge/blob/d37a96819bb363995c5dd0c9377b412890621e8e/src/SIL.XForge/Services/UserService.cs#L155)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Right. That's on purpose because I am going to remove the user doc and its OTs in RealtimeService.DeleteUserAsync(). So any trace of whether we do or don't also call `IDocument.DeleteAsync()` on the user doc, will presumably be lost, making it meaningless to call DeleteAsync on the user doc. But maybe I don't have an accurate understanding. How will it help to first do 
```cs
                IDocument<User> userDoc = await conn.FetchAsync<User>(userId);
                await userDoc.DeleteAsync();
```
before 
```cs
await _realtimeService.DeleteUserAsync(userId);
```
?
</blockquote></details>

If you submit a delete op, then the client will be notified that the user was deleted and can properly handle the situation in real-time.  For example, triggering a redirect back to the landing page.


<!-- Sent from Reviewable.io -->

2021-01-19 06:10 UTC, irahopkinson reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/896)* status: all files reviewed, 3 unresolved discussions (waiting on @marksvc and @RaymondLuong3)

___
*[src/SIL.XForge/Realtime/RealtimeService.cs, line 136 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/896#-MQa44Dr96WQVgo4mjYa:-MROFI8n7TgO_RJi3PUt:b-6i0vyu) ([raw file](https://github.com/sillsdev/web-xforge/blob/d37a96819bb363995c5dd0c9377b412890621e8e/src/SIL.XForge/Realtime/RealtimeService.cs#L136)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Done. I am having trouble finding that style guide, or that specific point in the style guides that I was looking at. Can you point me to this resource?
</blockquote></details>

Many that I found don't specifically point it out either but you can see it inherent in their example code. I got Damien to point me to this one that he/we have been using that goes into this level of detail https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions


<!-- Sent from Reviewable.io -->

2021-01-19 22:58 UTC, marksvc reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/896)* status: all files reviewed, 3 unresolved discussions (waiting on @ddaspit and @RaymondLuong3)

___
*[src/SIL.XForge/Realtime/RealtimeService.cs, line 136 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/896#-MQa44Dr96WQVgo4mjYa:-MRRhNEZ-cPzICbQl8_M:b-ucfknh) ([raw file](https://github.com/sillsdev/web-xforge/blob/d37a96819bb363995c5dd0c9377b412890621e8e/src/SIL.XForge/Realtime/RealtimeService.cs#L136)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Many that I found don't specifically point it out either but you can see it inherent in their example code. I got Damien to point me to this one that he/we have been using that goes into this level of detail https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions
</blockquote></details>

Thanks!
___
*[src/SIL.XForge/Services/ProjectService.cs, line 97 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/896#-MQjbEmr4I9TUFPnATnR:-MRRhoTR6GjWh8ozJt2s:byv4k5l) ([raw file](https://github.com/sillsdev/web-xforge/blob/d37a96819bb363995c5dd0c9377b412890621e8e/src/SIL.XForge/Services/ProjectService.cs#L97)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

The problem you describe should not be possible with ShareDB. ShareDB is specifically designed to handle concurrent edits to the same document. Here is how this scenario works:

1. PT-Admin-Bob requests to remove user Charlie from ProjectAlpha and PT-Admin-Julie requests to remove user Charlie from ProjectBravo at the same time. They both attempt to update the same version of the user doc (version 1).
2. Arbitrarily, PT-Admin-Bob's request is received first.
3. The project id is properly removed from the user doc.
4. The doc version is incremented to 2.
5. PT-Admin-Julie's request is received second.
6. ShareDB realizes that PT-Admin-Julie's op is on an older version of the doc (version 1).
7. ShareDB transforms the PT-Admin-Julie's op according to all of the ops that have occurred since the doc version that PT-Admin-Julie is working on. This means that the index in PT-Admin-Julie's op is updated to reflect that a project id was removed by PT-Admin-Bob's op.
8. The transformed op is applied to the latest version (2) of the doc and the correct project id is removed.
9 The doc version is incremented to 3.

You are only able to reproduce this problem in unit tests, because the mock real-time service does not fully implement concurrent editing of docs. Ultimately, this means that the lock is not necessary. I hope all of that makes sense.
</blockquote></details>

Great. Thank you for the explanation. I removed the mutex.
___
*[src/SIL.XForge/Services/UserService.cs, line 155 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/896#-MQjf2jwAdU0FyHNVmnp:-MRRjgPv7whNOSvjHAAL:bkdqlgp) ([raw file](https://github.com/sillsdev/web-xforge/blob/d37a96819bb363995c5dd0c9377b412890621e8e/src/SIL.XForge/Services/UserService.cs#L155)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

If you submit a delete op, then the client will be notified that the user was deleted and can properly handle the situation in real-time.  For example, triggering a redirect back to the landing page.
</blockquote></details>

Ah ha, yes. Thank you. Done.
___
*[src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-owner/checking-owner.component.ts, line 32 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/896#-MQaM8rf4_XZ9I3zE2mF:-MRRpd0pEaAeHbT8xUbV:b4homow) ([raw file](https://github.com/sillsdev/web-xforge/blob/d37a96819bb363995c5dd0c9377b412890621e8e/src/SIL.XForge.Scripture/ClientApp/src/app/checking/checking/checking-answers/checking-owner/checking-owner.component.ts#L32)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

Questions, answers and comments all inherit from `OwnedData` which contains and `ownerRef` string.
It sounds like the audio filename shouldn't be a problem but you could check with @raymondluong3.
</blockquote></details>

Looking thru some TS and C# code makes me think we drop the original filename and create a new filename based on things like user ID when saving it on the server. I'm asking Raymond what he thinks.


<!-- Sent from Reviewable.io -->

2021-01-20 09:49 UTC, ddaspit requested changes
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/896)* status: all files reviewed, 2 unresolved discussions (waiting on @marksvc and @RaymondLuong3)

___
*[src/SIL.XForge/Services/ProjectService.cs, line 24 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/896#-MRUBb5t6-Kv-8KB7u8n:-MRUBb5t6-Kv-8KB7u8o:buua2r0) ([raw file](https://github.com/sillsdev/web-xforge/blob/f85fa905d3f070fa2b20384e147cf7eaef995a14/src/SIL.XForge/Services/ProjectService.cs#L24)):*
> ```Smalltalk
>     {
>         private readonly IAudioService _audioService;
>         private readonly SemaphoreSlim _userRemoveProjectMutex = new SemaphoreSlim(1, 1);
> ```

You forgot to remove the mutex.


<!-- Sent from Reviewable.io -->

2021-01-20 18:54 UTC, marksvc reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/896)* status: all files reviewed, 2 unresolved discussions (waiting on @ddaspit and @RaymondLuong3)

___
*[src/SIL.XForge/Services/ProjectService.cs, line 24 at r4](https://reviewable.io/reviews/sillsdev/web-xforge/896#-MRUBb5t6-Kv-8KB7u8n:-MRW8RQQ9UKri_q3TNOz:bb6un1j) ([raw file](https://github.com/sillsdev/web-xforge/blob/f85fa905d3f070fa2b20384e147cf7eaef995a14/src/SIL.XForge/Services/ProjectService.cs#L24)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

You forgot to remove the mutex.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-01-21 02:41 UTC, ddaspit approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/896#-:-MRXoPWICMM2s7zZyKVB:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @RaymondLuong3)



<!-- Sent from Reviewable.io -->

2021-01-21 07:45 UTC, irahopkinson requested changes
Thanks for this, however a TC test is failing. You'll also want to rebase since one of the test files has changed on master.

> Reviewed 8 of 12 files at r3, 3 of 4 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/896#-:-MRYtZUO87bkJFEeoTbL:b-ishu6f)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc)

___
*[test/SIL.XForge.Tests/Services/ProjectServiceTests.cs, line 258 at r5](https://reviewable.io/reviews/sillsdev/web-xforge/896#-MRYqmk1ACNNnnFX0M_g:-MRYqmk1ACNNnnFX0M_h:bxncl6o) ([raw file](https://github.com/sillsdev/web-xforge/blob/9148e16fde6390b6176a174c2276d1d5357b0d17/test/SIL.XForge.Tests/Services/ProjectServiceTests.cs#L258)):*
> ```Smalltalk
>             Assert.That(env.GetUser(userToDisassociate).Sites[SiteId].Projects, Does.Not.Contain(Project01));
>             Assert.That(env.GetProject(Project02).UserRoles, Does.Not.ContainKey(userToDisassociate));
>             Assert.That(env.GetUser(userToDisassociate).Sites[SiteId].Projects, Does.Not.Contain(Project02));
> ```

This line is failing on TC but it seems to pass locally. You'll likely need to login to the build agent and diagnose there. Let me know if you need help diagnosing this.


<!-- Sent from Reviewable.io -->

2021-01-21 18:29 UTC, marksvc reviewed
I am able to get the same test failure on my workstation. Unfortunately, it's failing because of the race condition. If I re-introduce a mutex, it no longer fails on my machine. A simple way forward may be to just make the calls to RemoveUserCoreAsync() run in sequence rather than in parallel. I applied this in a revision. 

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/896#-:-MRa8K6G47OHBb4oaupO:b-dai2oh)* status: 21 of 22 files reviewed, 1 unresolved discussion (waiting on @ddaspit and @irahopkinson)



<!-- Sent from Reviewable.io -->

2021-01-22 02:57 UTC, irahopkinson approved these changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/896)* status: all files reviewed, 1 unresolved discussion (waiting on @marksvc)

___
*[src/SIL.XForge/Services/ProjectService.cs, line 109 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/896#-MRbkOv_2yy7TY9Xa12L:-MRbkOv_2yy7TY9Xa12M:buyi4vu) ([raw file](https://github.com/sillsdev/web-xforge/blob/99d4cde4d65c770ba82f2257e8bc4460507e7efd/src/SIL.XForge/Services/ProjectService.cs#L109)):*
> ```
>                 // The removals can be processed in parallel in production, but for unit tests, MemoryRealtimeService
>                 // does not fully implement concurrent editing of docs, so run them in a sequence.
> ```
It's usually a bad idea to compromise production in order to enable tests. Why do you think its justified here? How can you change the tests to work around the limitations of the MemoryRealtimeService? Can something be done to fix this in MemoryRealtimeService?

Since we probably don't want to just remove the test line in order to not compromise production code, and we probably don't want to take the time to fix MemoryRealtimeService right now (which we could do by running ShareDB with a memory Mongo), and given the time difference between parallel and serial here is probably not user notice-able, and this isn't even user-facing (just SysAdmins), then this is the best solution. Well done, lets merge it.


<!-- Sent from Reviewable.io -->

2021-01-22 02:58 UTC, merged

2021-01-25 18:36 UTC, marksvc reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/896)* status: all files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[src/SIL.XForge/Services/ProjectService.cs, line 109 at r6](https://reviewable.io/reviews/sillsdev/web-xforge/896#-MRbkOv_2yy7TY9Xa12L:-MRugVjH3XNhB5IxQuWr:b-uw71vt) ([raw file](https://github.com/sillsdev/web-xforge/blob/99d4cde4d65c770ba82f2257e8bc4460507e7efd/src/SIL.XForge/Services/ProjectService.cs#L109)):*
> then this is the best solution. Well done, lets merge it.

Thank you. I wasn't sure if the earlier questions were something you wanted me to think thru and/or discuss. I haven't implemented anything but I did have a look around to see what I might be able to do as I considered the different questions, which I answer below:

Justified - Because it would be an unrecognizable performance degradation, and with behaviour that was either the same, or potentially better (if our C# or ShareDB isn't as concurrent as we thought). And we gain the unit test.

> How can you change the tests to work around the limitations of the MemoryRealtimeService? 

Right. Maybe we could use do something like mock IConnection, have it return a specific project doc and  user  doc that take note of the calls to IDocument.SubmitJson0OpAsync() and assert that appropriate operations were given by ProjectService such that the right things would have been done.  (Which would be unfortunate since we already have MemoryRealtimeService and MemoryRepository to let us check outcomes without needing to do this kind of thing.)
There may also be a Task-related setting where we can specify in the unit test that tasks should be executed in sequence rather than in parallel.
We could mock Task (and probably make a mess).

> Can something be done to fix this in MemoryRealtimeService?

Yes. I had a look around in some of the files in Realtime today. I think the right place to change the behaviour would be after the ops are fully built. (So we would let `op.Remove(u => u.Sites[siteId].Projects, index);` continue to use the same `index` value that is presently not concurrently compatible.) I see that MemoryDocument SubmitOpAsync() calls `MemoryRealtimeService.Server.ApplyOpAsync(OTTypeName, Data, op)` but then it's a bit confusing since it looks like it starts to use a real RealtimeService, so I would need to study it more to understand what it's doing.

Damien had described some of  ShareDB's relevant behaviour as:
> ShareDB realizes that PT-Admin-Julie's op is on an older version of the doc (version 1).
> ShareDB transforms the PT-Admin-Julie's op according to all of the ops that have occurred since the doc version that PT-Admin-Julie is working on. This means that the index in PT-Admin-Julie's op is updated to reflect that a project id was removed by PT-Admin-Bob's op.
> The transformed op is applied to the latest version (2) of the doc and the correct project id is removed.

There may be simpler ways to go about it for unit tests. But we'd want to talk about whether we should put in the effort.

And I see you noted it could be done "by running ShareDB with a memory Mongo", so a solution may be to just arrange different pieces together.


<!-- Sent from Reviewable.io -->