SF-1153 Increase capacity of TimeEditActive
sillsdev/web-xforge pull request #959
Opened 2021-02-18 17:41 UTC by marksvc

- This value in ms could overflow if only 32-bit.
===
So will this change to the  model need any sort of migration?

2021-02-19 15:33 UTC, irahopkinson requested changes
Its really good that you found that a really large number was being put into this property as the first cause of this problem. I understand that took quite a bit of work. However if we merge this first (assuming my comments below can be satisfied) then that will just mask this problem. I would prefer we get to the root of this problem rather than patch it with this PR. Keep asking 'why' until you get to the root cause. To that end, SF-1210 is not really needed because we need to solve it here.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/959#-:-MTuto_HChSYb_mv2NFQ:b9oi3pe)* status: all files reviewed, 2 unresolved discussions (waiting on @marksvc)

___
*[src/SIL.XForge.Scripture/Models/TranslateMetrics.cs, line 27 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/959#-MTusspeAKI2au6OGOTm:-MTusspeAKI2au6OGOTn:b2klpqa) ([raw file](https://github.com/sillsdev/web-xforge/blob/42f4d51a1afd1cc07f1b3b084369c10575557260/src/SIL.XForge.Scripture/Models/TranslateMetrics.cs#L27)):*
> ```
> int
> ```
So how long is a 32-bit ms? I calculate it as about 3.2 years. Do you think a user can actively edit non-stop for anywhere near that long?
___
*[src/SIL.XForge.Scripture/Models/TranslateMetrics.cs, line 28 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/959#-MTutFHR7LfvfCXEmYBm:-MTutFHR7LfvfCXEmYBn:bgrkq9n) ([raw file](https://github.com/sillsdev/web-xforge/blob/b0d75424aa55bf07c1c47eaeb5ae140fc5fe0f33/src/SIL.XForge.Scripture/Models/TranslateMetrics.cs#L28)):*
> ```
> Int64
> ```
My first concern here is will this go into Mongo? How does Mongo store this? Does our C# to Mongo mapper handle `Int64`?


<!-- Sent from Reviewable.io -->

2021-02-19 22:05 UTC, marksvc reviewed
Yeah, I wasn't wanting to just make the problem be ignored, but it seemed that we really needed to increase the capacity of the TimeEditActive field. But I longer think so, which I discuss below.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/959#-:-MTwJ4A70ZqvmhqHEf1A:b-2r69hs)* status: all files reviewed, 2 unresolved discussions (waiting on @irahopkinson and @marksvc)

___
*[src/SIL.XForge.Scripture/Models/TranslateMetrics.cs, line 27 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/959#-MTusspeAKI2au6OGOTm:-MTwA6G4BBSPEzCqYwFi:b-7v9b23) ([raw file](https://github.com/sillsdev/web-xforge/blob/42f4d51a1afd1cc07f1b3b084369c10575557260/src/SIL.XForge.Scripture/Models/TranslateMetrics.cs#L27)):*
<details><summary><i>Previously, irahopkinson (Ira Hopkinson) wrote…</i></summary><blockquote>

> ```
> int
> ```
So how long is a 32-bit ms? I calculate it as about 3.2 years. Do you think a user can actively edit non-stop for anywhere near that long?
</blockquote></details>

So if I do (2^32)/1000/60/60 I get 1193 hours. So if a user edits SF for 8 hours a day they can hit the limit after 149 days. If there are 4 people collaborating, they can do it faster. That would be a lot of usage. However, as I look at the rest of the object I can see that since it specifies SessionId, UserRef, and ChapterNum, I am thinking this model object may only be recording usage data for a particular short period of time, rather than the aggregate usage over a longer period of time. 

I'm looking over translate-metric-session.ts to see how it's using TranslateMetrics objects. It looks like it may be common to create new metrics and send them. And for the same SessionId as well. So I withdraw my concern. 

I will write a couple class comments from what I have learned so far. 


<!-- Sent from Reviewable.io -->

2021-02-20 02:58 UTC, irahopkinson requested changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/959)* status: all files reviewed, 2 unresolved discussions (waiting on @marksvc)

___
*[src/SIL.XForge.Scripture/Models/TranslateMetrics.cs, line 27 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/959#-MTusspeAKI2au6OGOTm:-MTxM-jT8KBwFQThMGPl:b-f6j62r) ([raw file](https://github.com/sillsdev/web-xforge/blob/42f4d51a1afd1cc07f1b3b084369c10575557260/src/SIL.XForge.Scripture/Models/TranslateMetrics.cs#L27)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

So if I do (2^32)/1000/60/60 I get 1193 hours. So if a user edits SF for 8 hours a day they can hit the limit after 149 days. If there are 4 people collaborating, they can do it faster. That would be a lot of usage. However, as I look at the rest of the object I can see that since it specifies SessionId, UserRef, and ChapterNum, I am thinking this model object may only be recording usage data for a particular short period of time, rather than the aggregate usage over a longer period of time. 

I'm looking over translate-metric-session.ts to see how it's using TranslateMetrics objects. It looks like it may be common to create new metrics and send them. And for the same SessionId as well. So I withdraw my concern. 

I will write a couple class comments from what I have learned so far. 
</blockquote></details>

Yep your calculation is right at 1193 hours (it was late last night when I tried). And this is for active edit time, i.e. if you stop typing for a few seconds (depending on its timeout value that I think is adjustable) then it considers your active edit to be over. I don't think anyone could actively edit for 24/7 for 49 days.


<!-- Sent from Reviewable.io -->

2021-02-24 21:02 UTC, marksvc commented
(I am working on a fix that takes into account Mobile Safari)

2021-03-01 18:32 UTC, marksvc commented
This PR was re-worked.

2021-03-03 09:44 UTC, irahopkinson approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> thanks for persisting with this.

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/959#-:-MUrSgiVAA7sCciE7rRy:bikzmdl)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-03-03 10:19 UTC, merged