SF-1181b Fix 401 error on connect project page
sillsdev/web-xforge pull request #973
Opened 2021-03-10 00:06 UTC by Nateowami

This isn't a very elegant solution, but I'm really not sure which abstraction layer should be responsible for checking whether we should proceed. One option is to allow an exception to be thrown, then catch it high up the stack. That doesn't seem very elegant either.

I would welcome arguments/reasons for why this should be done differently.

2021-03-10 15:37 UTC, Nateowami reviewed
@irahopkinson When a user visits the connect project page it tries to fetch resources. If the user does not have user secrets, it causes an error. This is the issue the testers were running into.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/973#-:-MVRm0dyA9fBi3J1K0dN:bsexnzx)* status: 0 of 1 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-03-11 04:12 UTC, ddaspit requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/973)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[src/SIL.XForge.Scripture/Controllers/ParatextController.cs, line 64 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/973#-MVUU1-WBfcuXdB6p73b:-MVUU1-WBfcuXdB6p73c:b-g5trpt) ([raw file](https://github.com/sillsdev/web-xforge/blob/93780f8bb56914bf0179ec4c56e672c450d5dc7d/src/SIL.XForge.Scripture/Controllers/ParatextController.cs#L64)):*
> ```Smalltalk
>         public async Task<ActionResult<Dictionary<string, string>>> ResourcesAsync()
>         {
>             Attempt<UserSecret> attempt = await _userSecrets.TryGetAsync(_userAccessor.UserId);
> ```

We do have a `DataNotFoundException` that would be appropriate. There are examples where the `ParatextService` throws that exception, the controller catches it, and returns the appropriate status code.


<!-- Sent from Reviewable.io -->

2021-03-11 22:05 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/973)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ddaspit)

___
*[src/SIL.XForge.Scripture/Controllers/ParatextController.cs, line 64 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/973#-MVUU1-WBfcuXdB6p73b:-MVYHckKEQkWvVosdR6r:b60801s) ([raw file](https://github.com/sillsdev/web-xforge/blob/93780f8bb56914bf0179ec4c56e672c450d5dc7d/src/SIL.XForge.Scripture/Controllers/ParatextController.cs#L64)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

We do have a `DataNotFoundException` that would be appropriate. There are examples where the `ParatextService` throws that exception, the controller catches it, and returns the appropriate status code.
</blockquote></details>

Thanks. I think this is much better. I also fixed a related issue where the throwing of an exception caused the semaphore to not be released.


<!-- Sent from Reviewable.io -->

2021-03-16 03:14 UTC, ddaspit reviewed
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/973)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami)

___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 864 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/973#-MVt0UFeENmkUFjMmTWc:-MVt0UFeENmkUFjMmTWd:b6ha71l) ([raw file](https://github.com/sillsdev/web-xforge/blob/8132317cdad70aaf541853e2aa9691d8ab8d34c3/src/SIL.XForge.Scripture/Services/ParatextService.cs#L864)):*
> ```Smalltalk
>                 return new ParatextAccessLock(semaphore, userSecret);
>             }
>             catch
> ```

It would be better to use a `finally` block here instead of `catch`.


<!-- Sent from Reviewable.io -->

2021-03-16 03:28 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/973)* status: all files reviewed, 1 unresolved discussion (waiting on @ddaspit)

___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 864 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/973#-MVt0UFeENmkUFjMmTWc:-MVt3kKgAJP69U9HVoA_:b-h1ihdd) ([raw file](https://github.com/sillsdev/web-xforge/blob/8132317cdad70aaf541853e2aa9691d8ab8d34c3/src/SIL.XForge.Scripture/Services/ParatextService.cs#L864)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

It would be better to use a `finally` block here instead of `catch`.
</blockquote></details>

A `finally` block would always execute. This needs to execute only when an exception is thrown and the user will not have the opportunity to release the semaphore.


<!-- Sent from Reviewable.io -->

2021-03-16 07:54 UTC, ddaspit approved these changes
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/973)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Nateowami)

___
*[src/SIL.XForge.Scripture/Services/ParatextService.cs, line 864 at r2](https://reviewable.io/reviews/sillsdev/web-xforge/973#-MVt0UFeENmkUFjMmTWc:-MVu0PEVE3QcWD8hvQHv:b9c7emw) ([raw file](https://github.com/sillsdev/web-xforge/blob/8132317cdad70aaf541853e2aa9691d8ab8d34c3/src/SIL.XForge.Scripture/Services/ParatextService.cs#L864)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

A `finally` block would always execute. This needs to execute only when an exception is thrown and the user will not have the opportunity to release the semaphore.
</blockquote></details>

I see. The semaphore is supposed to released when `ParatextAccessLock` is disposed. This code ensures that it is released if an exception is thrown before the `ParatextAccessLock` is created. 


<!-- Sent from Reviewable.io -->

2021-03-16 14:48 UTC, merged