SF-1238 - Unauthorized error after 2 hours
sillsdev/web-xforge pull request #992
Opened 2021-03-24 01:53 UTC by nigel-wells

- Adjusted http intercept handler to ensure the user is authenticated before adding access token to the header

This fix will ensure no requests to the backend will be made unless the user is authenticated with a valid access token that hasn't expired. Any requests made while there is an expired token will await auth0 (via `checkSession`) before it proceeds. This all happens silently.

2021-03-24 04:07 UTC, ddaspit requested changes
It might also be good to adjust the scheduled renewal to renew the token prior to the token expiring rather than waiting until it is expired. Maybe 30 seconds or something like that. It would help to make this less likely to be needed.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/992#-:-MWXOxsc1-hoE8lE4oTA:b-cpwe1s)* status: all files reviewed, 2 unresolved discussions (waiting on @nigel-wells)

___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth-http-interceptor.ts, line 31 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/992#-MWXOGya1PFu0G0CtuG0:-MWXOGyb-6VZR6YMw3rT:b-k2m7tg) ([raw file](https://github.com/sillsdev/web-xforge/blob/79aa4e98c5c0bacdaf4e253bb3ee52fb49853983/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth-http-interceptor.ts#L31)):*
> ```XML
>       headers: req.headers.set('Authorization', 'Bearer ' + this.authService.accessToken)
>     });
>     return next.handle(authReq).toPromise();
> ```

It looks like you missed an `await` here.
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts, line 156 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/992#-MWXOR8c6FcRqspL1cA0:-MWXOR8d0K2VH8Lp3htv:b-ghtkdc) ([raw file](https://github.com/sillsdev/web-xforge/blob/79aa4e98c5c0bacdaf4e253bb3ee52fb49853983/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts#L156)):*
> ```XML
>   async isAuthenticated(): Promise<boolean> {
>     if (!this.hasExpired) {
>       await this.renewTokens();
> ```

What happens if a scheduled renewal is already in-flight? I wonder if they could step on each other.


<!-- Sent from Reviewable.io -->

2021-03-24 19:34 UTC, Nateowami submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/992)* status: all files reviewed, 2 unresolved discussions (waiting on @ddaspit and @nigel-wells)

___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth-http-interceptor.ts, line 31 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/992#-MWXOGya1PFu0G0CtuG0:-MW_Sb1UADX9qBJ0Eliw:b-pvnrbw) ([raw file](https://github.com/sillsdev/web-xforge/blob/79aa4e98c5c0bacdaf4e253bb3ee52fb49853983/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth-http-interceptor.ts#L31)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

It looks like you missed an `await` here.
</blockquote></details>

I think returning a promise is sufficient. Since there's nothing more that needs to be done in this method, it doesn't need to be awaited. Unless I'm missing something?


<!-- Sent from Reviewable.io -->

2021-03-25 01:16 UTC, nigel-wells reviewed
@ddaspit I believe most occurrences occur if someone has closed their browser down and then open it back up after the token has expired in which case forcing an earlier expiry won't help. That said, 30 seconds will help avoid any inflight issues if a backend request was made followed by the token immediately expiring so I've added it in anyway.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/992#-:-MWavDynAfxq2dGJY-cp:bypuhwc)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @ddaspit)

___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth-http-interceptor.ts, line 31 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/992#-MWXOGya1PFu0G0CtuG0:-MWawBkx3lCwgtFUpbPQ:b-8zs2fo) ([raw file](https://github.com/sillsdev/web-xforge/blob/79aa4e98c5c0bacdaf4e253bb3ee52fb49853983/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth-http-interceptor.ts#L31)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

I think returning a promise is sufficient. Since there's nothing more that needs to be done in this method, it doesn't need to be awaited. Unless I'm missing something?
</blockquote></details>

Yes a promise is enough as`intercept` expects an Observable  so we convert the promise into an observable to be returned.
___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts, line 156 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/992#-MWXOR8c6FcRqspL1cA0:-MWautxi07eC6b0dEZTI:b4l81wk) ([raw file](https://github.com/sillsdev/web-xforge/blob/79aa4e98c5c0bacdaf4e253bb3ee52fb49853983/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth.service.ts#L156)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

What happens if a scheduled renewal is already in-flight? I wonder if they could step on each other.
</blockquote></details>

Have added a promise to ensure this doesn't happen now


<!-- Sent from Reviewable.io -->

2021-03-25 05:44 UTC, ddaspit approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/992#-:-MWbu8eIA_5ydLv6dbZf:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami and @nigel-wells)

___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth-http-interceptor.ts, line 31 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/992#-MWXOGya1PFu0G0CtuG0:-MWbqr0U2XWZnUpTgxxE:b9xhmfl) ([raw file](https://github.com/sillsdev/web-xforge/blob/79aa4e98c5c0bacdaf4e253bb3ee52fb49853983/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth-http-interceptor.ts#L31)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Yes a promise is enough as`intercept` expects an Observable  so we convert the promise into an observable to be returned.
</blockquote></details>

Although simply returning the promise without awaiting is a slight performance optimization. Generally, I think it is a good idea to `await` all async functions/promises in an `async` function. There are two potential "gotchas" if you don't.
1. It can make debugging more difficult, since the stack trace won't include the method that returns the promise without awaiting.
2. The method won't behave as most would expect if a `try-catch` were later added to the method. An exception thrown by the promise won't be caught in the method.

Once we move from tslint to eslint, we could use the [return-await](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/return-await.md) rule to avoid gotcha 2. Until then, I think it would be good to avoid returning promises from `async` functions.  I won't block you if you feel that the optimization benefit outweighs the gotchas.


<!-- Sent from Reviewable.io -->

2021-03-25 11:43 UTC, daveh551 commented
Damien,

 

Allow me to introduce myself – I’m new to the project.

 

I’m a professional software developer, with about 45 years – give or take – experience. My recent experience (last 15 years or so) has been with the Microsoft .NET stack.  I’ve recently (last 2 years) gotten some exposure to Angular and JavaScript, and also to F#.

 

My development environment has been Visual Studio.  Ira tells me that you have some experience with that, and might be able to give me some pointers on how to set it up.  I’ve cloned the web-xforge repo.  When I press F5, it kicks off an ng serve command window and then opens a browser, but the browser usually gets a timeout exception saying that the Angular CLI didn’t respond in the expected time.

 

Thanks for you help.  I look forward to getting up to speed to the point where, hopefully, I can make a contribution.

 

Dave Hanna

(214) 799-6823

***@***.*** ***@***.***> 

 

From: Damien Daspit ***@***.***> 
Sent: Thursday, March 25, 2021 12:45 AM
To: sillsdev/web-xforge ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [sillsdev/web-xforge] SF-1238 - Unauthorized error after 2 hours (#992)

 

@ddaspit approved this pull request.

 <https://u8515854.ct.sendgrid.net/ls/click?upn=lcdVWvjgLfD6zkXdbbMojjkySVVvEyWeSUY3qQcfhBG75b2y9aHsg5yARJtPND4Anm2Lg-2FN-2BZ8iasWpVgR4YR8d41-2Fij2O-2Fd-2B3BjaHv4Cu8PjkaBbXR4PO-2B6-2BCsO5WeCcZY0S0mg-2BzXGjYSv9wo-2FONMGIOzPJ8z3uNT8kRcyn6Bz0jj2y5xsP2t80sbHqS5-2FL1KZO1avZxIZrAGz55yOEswdRB6yhMDNSimGRgFONd8-3DSuRz_U31jt5HgHBh7k3Grc5s4l-2BZlri748JIz9rbCwrB5mFAutt0I8jQ5FmU9g6YFFSuSzQ-2Bpr0ZiXeaHZm1PtVJT7qVez6YHxZtyZ9S-2Fvn3wTJlps1gTemhahMVrphe4hBvd6DbHxw5lSFnb9ytrDgfbgWq1uB-2FsXSRF31cIEq1XrdY6Z4RuXi-2FeHtQ0Jo4dB-2BXI2bAUS1WeklxQK-2F0Y76xM0LduyH301W4YePOf-2BdvM6P8wnjN0etwFQk0VmRLHcVYdbMh-2BKDO2sibu2oUmeZuMNXe5f9hDE6ClZY56bWq94uE-3D> 

Reviewed 1 of 1 files at r2.
Reviewable <https://u8515854.ct.sendgrid.net/ls/click?upn=lcdVWvjgLfD6zkXdbbMojoAqhnAVd6lIqnj4-2FWzfMBgG4CDGtlstXUh84iNtewrkGm-2BTulr-2Fns2MO-2FEiXFElR5s-2BniM0uNi6yN395uDP0EsB0FQQBMV4EnYA6dlK8574CopP_U31jt5HgHBh7k3Grc5s4l-2BZlri748JIz9rbCwrB5mFAutt0I8jQ5FmU9g6YFFSuSzQ-2Bpr0ZiXeaHZm1PtVJT7qVez6YHxZtyZ9S-2Fvn3wTJlps1gTemhahMVrphe4hBvdeIqMPsLpUiWZ77RY1l5CumofnX9SPOroDQsEet8dDkgG8lXVTpeaYFNMWhqWWTwXgIjfMvvabLXm-2B5B5BtErY0dJXQEPHE-2BsYmRgSBd2SBzAVwHl1O9V5W4Y6uoNwotXPR210Folo9xAQOCp3c3bnxccd0Eo4i-2FywqRXByPwsTs-3D>  status: all files reviewed, 1 unresolved discussion (waiting on @Nateowami <https://u8515854.ct.sendgrid.net/ls/click?upn=lcdVWvjgLfD6zkXdbbMojijIMQ-2BL1hH-2BUpkqxAIXcrh3Uh4DV-2FHdnEwXgRwqT3MoP3dY_U31jt5HgHBh7k3Grc5s4l-2BZlri748JIz9rbCwrB5mFAutt0I8jQ5FmU9g6YFFSuSzQ-2Bpr0ZiXeaHZm1PtVJT7qVez6YHxZtyZ9S-2Fvn3wTJlps1gTemhahMVrphe4hBvdLbcuqAzfnT0fZwzcnfMX07uhJV-2FVHFanIPDber4P1fmSxU00Uzd3JWhJggNPzEbTVan-2FEj5-2F53g3KHfAC7vxePuye1JsMfOgxOmWiCZ4BTrmsNLB3j9UYJ12p8wTrwiI9igWTvu8dJLP7ZN6Mw0KcqyIt52-2FJcCIuUDQ4IjZvJM-3D>  and @nigel-wells <https://u8515854.ct.sendgrid.net/ls/click?upn=lcdVWvjgLfD6zkXdbbMojo33P81YHGoM51gvUjjiCTZTOGBlWY-2FXVXhF-2BQvSA-2BvOMrkw_U31jt5HgHBh7k3Grc5s4l-2BZlri748JIz9rbCwrB5mFAutt0I8jQ5FmU9g6YFFSuSzQ-2Bpr0ZiXeaHZm1PtVJT7qVez6YHxZtyZ9S-2Fvn3wTJlps1gTemhahMVrphe4hBvdpfz4bPY1lFiGnUsCjSVTfeHTwgidH06lQlQCwrSDsKgEpGWRoZ50ITX5alh8rjvjLxRCsT4u2-2FukBC-2FuzBVEAitwWzFxrG5Ox2vDrs4Ff793stNnseZrgCWru9FckPFQiTMOnJ5YUKYh2wFRIn4t4Kf8ol3HFkInvA-2BqehcxNQQ-3D> )

  _____  

src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth-http-interceptor.ts, line 31 at r1 <https://u8515854.ct.sendgrid.net/ls/click?upn=lcdVWvjgLfD6zkXdbbMojoAqhnAVd6lIqnj4-2FWzfMBgG4CDGtlstXUh84iNtewrkL0K32ZYd8ZWJ6a4iwuoszE03Shbysl2lL8Rn8wltMayE7D8z7CVLDSo2KrQGy5qQjXZgi3Ok1JkBf8XVYBY1jg-3D-3Dgi79_U31jt5HgHBh7k3Grc5s4l-2BZlri748JIz9rbCwrB5mFAutt0I8jQ5FmU9g6YFFSuSzQ-2Bpr0ZiXeaHZm1PtVJT7qVez6YHxZtyZ9S-2Fvn3wTJlps1gTemhahMVrphe4hBvd70-2B10z07I9tgSBq3t-2Fdp9rf4DtNInPFskdRmPLRwyXyF1hc-2FI5GRyIvZL4USWY79JEu7JQbXenipJxj2Zrtcv6cENdcT-2Bpkq43Mf0oz8bvys-2BGeb5HNa1iHGqQRXldP69hoKrorosdFDC9w6qbk3LiV-2Be-2BLt-2FCSnT9fyAPug5zY-3D>  (raw file <https://u8515854.ct.sendgrid.net/ls/click?upn=lcdVWvjgLfD6zkXdbbMojgrdVx8Zjjrmv72m-2F0fMdP9lg9sFFgsSWoZ61GTxzNG-2BDyjkb-2FvmU5r8FFE2f0s8Zz4nkSV-2B1I3KbOxdaJMOwTDqrCEY-2BOgtrCybHEsf1-2B-2BRTgzHY1EpRNLoXaFjWopgMprMC9-2BUPttgjwyBb-2Foyvoax-2Fi-2F4pVfTWSNyr49x6MOmtc5DcR1-2FwnV8SpQjQDE0IPlKKbEVG-2BzgxX9jAnZ-2B-2BSY-3DHP18_U31jt5HgHBh7k3Grc5s4l-2BZlri748JIz9rbCwrB5mFAutt0I8jQ5FmU9g6YFFSuSzQ-2Bpr0ZiXeaHZm1PtVJT7qVez6YHxZtyZ9S-2Fvn3wTJlps1gTemhahMVrphe4hBvdMV8b3g5TL9poNPq4ri6cB0CfocrRRq8JIm22Tt5WQgDTIObfNS57vOs3TKwQSvQKBVGK4-2FVjM7G5sJEayIyjsArFBACmd0VBDvIaKS6zidayhDWP0xq3i9Rlz7JfE2Se2T-2FagsyS7TLBjgDt9aBg-2FkcAR-2BG-2By-2FyiyqMqA-2F83ZuI-3D> ):

Previously, nigel-wells (Nigel Wells) wrote…

Yes a promise is enough asintercept expects an Observable so we convert the promise into an observable to be returned.

Although simply returning the promise without awaiting is a slight performance optimization. Generally, I think it is a good idea to await all async functions/promises in an async function. There are two potential "gotchas" if you don't.

1.	It can make debugging more difficult, since the stack trace won't include the method that returns the promise without awaiting.
2.	The method won't behave as most would expect if a try-catch were later added to the method. An exception thrown by the promise won't be caught in the method.

Once we move from tslint to eslint, we could use the return-await <https://u8515854.ct.sendgrid.net/ls/click?upn=lcdVWvjgLfD6zkXdbbMojof68O1wZZodkIUdx-2Be-2FDzj8a2sDzdVCizDEOP2808l4ATeh42AYqHuAacg969iTJEFWCOSdzrtlTFtNkC3QogOalWWfckSUIv8CFJChFL-2B-2FOcTTtUXyZ-2FHBHlZ-2BFCXGV3br94179W0Q3uoXyNKTa8s-3DyVpa_U31jt5HgHBh7k3Grc5s4l-2BZlri748JIz9rbCwrB5mFAutt0I8jQ5FmU9g6YFFSuSzQ-2Bpr0ZiXeaHZm1PtVJT7qVez6YHxZtyZ9S-2Fvn3wTJlps1gTemhahMVrphe4hBvdLNEzfqcl3OutK4qfmrAuqiJU5hxop8ilrtKUzb9SVgKnJrn1J4AvG7fT-2BT25ufL-2B5TKsfoSkSL7eENX1-2FyWQFY3N5-2BdD0-2BmehNlW20KmFbGOhAw2Ub-2FGbtxd5hcy96QebDb2n-2BBCXhbod89vIPrqsUnYW2SxW40u-2BduAHUKoSyQ-3D>  rule to avoid gotcha 2. Until then, I think it would be good to avoid returning promises from async functions. I won't block you if you feel that the optimization benefit outweighs the gotchas.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub <https://u8515854.ct.sendgrid.net/ls/click?upn=lcdVWvjgLfD6zkXdbbMojgrdVx8Zjjrmv72m-2F0fMdP8ma3L0oBc8vjX3JoiCcUZlZ4rikwOhYp0k-2FlkrVmOjIq-2BTz840amaLlb3ky0yRjsF5Xe5f3LSJFgLkIVXOYR4b8y7v_U31jt5HgHBh7k3Grc5s4l-2BZlri748JIz9rbCwrB5mFAutt0I8jQ5FmU9g6YFFSuSzQ-2Bpr0ZiXeaHZm1PtVJT7qVez6YHxZtyZ9S-2Fvn3wTJlps1gTemhahMVrphe4hBvd8W35VtahpdVGlm-2BF8eIHmuxH2qnikL5oBcs-2FVapMCNBqNrpUwj199GilIJ3P5tFhc-2F8Akc9IDazHgPOfGHfqDeh8cv-2BCyU7767KuZosSAtiq-2BIMCTdjo0micZ3gUApxNsNzrX7y4eAccmg10sSnxwFRqTAt9sy1jxdR9Af-2BaxAM-3D> , or unsubscribe <https://u8515854.ct.sendgrid.net/ls/click?upn=lcdVWvjgLfD6zkXdbbMojjKSQ-2FzQTGOQJA3jb2X3IXIlOwvoGue-2BYyMd-2FIZGZHSo2-2BfmTx11v6xC5nBLrMUg1WAVZIq1AYoa8JLKU6twvHvCNf936s5S7SRZAh9Nis34avYYRBo7lemqi07DpTZqbw-3D-3DZZdF_U31jt5HgHBh7k3Grc5s4l-2BZlri748JIz9rbCwrB5mFAutt0I8jQ5FmU9g6YFFSuSzQ-2Bpr0ZiXeaHZm1PtVJT7qVez6YHxZtyZ9S-2Fvn3wTJlps1gTemhahMVrphe4hBvd4V-2FQsElDJJB4NM65N1XSL7HFPF45BRLxDYYBdMNdHQwuk2GfQKa-2FCdZbnGrqK35GSs3M7qP9FTVka5Mku2oE7FKlanO8nn2evbwrn5srRd7lEhZ9XkNBudb4pRu8KXblOFNLD7n-2Bt-2BBIJU700JAXle1XN-2BaMlxaN9f5mXrB-2B8-2F0-3D> .

2021-03-25 20:58 UTC, nigel-wells reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/992)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ddaspit and @Nateowami)

___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth-http-interceptor.ts, line 31 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/992#-MWXOGya1PFu0G0CtuG0:-MWf4UT80jwB1-Ke-ho6:b-21la5a) ([raw file](https://github.com/sillsdev/web-xforge/blob/79aa4e98c5c0bacdaf4e253bb3ee52fb49853983/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth-http-interceptor.ts#L31)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

Although simply returning the promise without awaiting is a slight performance optimization. Generally, I think it is a good idea to `await` all async functions/promises in an `async` function. There are two potential "gotchas" if you don't.
1. It can make debugging more difficult, since the stack trace won't include the method that returns the promise without awaiting.
2. The method won't behave as most would expect if a `try-catch` were later added to the method. An exception thrown by the promise won't be caught in the method.

Once we move from tslint to eslint, we could use the [return-await](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/return-await.md) rule to avoid gotcha 2. Until then, I think it would be good to avoid returning promises from `async` functions.  I won't block you if you feel that the optimization benefit outweighs the gotchas.

</blockquote></details>

Makes sense. I think I'm missing something here sorry. This class is implementing `HttpInterceptor` which requires the `intercept()` method to return an `Observable`. This means I can't add `async` in order to `await this.handle()` as that would then return a `Promise`. With `this.handle` being an async function it has to return a promise which is why the `.toPromise()` is added at the end. The promise is then turned back in to an Observable in the `intercept` method to be returned. Happy to change it but you'll need to provide me with some code or point me to a tutorial as I'm not quite sure how to do the await you're after?


<!-- Sent from Reviewable.io -->

2021-03-26 00:37 UTC, Nateowami reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/992)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ddaspit and @nigel-wells)

___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth-http-interceptor.ts, line 31 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/992#-MWXOGya1PFu0G0CtuG0:-MWfxOoL6sEhw73M-lm3:bhp89zz) ([raw file](https://github.com/sillsdev/web-xforge/blob/79aa4e98c5c0bacdaf4e253bb3ee52fb49853983/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth-http-interceptor.ts#L31)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Makes sense. I think I'm missing something here sorry. This class is implementing `HttpInterceptor` which requires the `intercept()` method to return an `Observable`. This means I can't add `async` in order to `await this.handle()` as that would then return a `Promise`. With `this.handle` being an async function it has to return a promise which is why the `.toPromise()` is added at the end. The promise is then turned back in to an Observable in the `intercept` method to be returned. Happy to change it but you'll need to provide me with some code or point me to a tutorial as I'm not quite sure how to do the await you're after?
</blockquote></details>

@nigel-wells I think it's `return await next.handle(authReq).toPromise();`

That would still be returning a promise.


<!-- Sent from Reviewable.io -->

2021-03-26 00:44 UTC, nigel-wells reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/992)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ddaspit and @Nateowami)

___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth-http-interceptor.ts, line 31 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/992#-MWXOGya1PFu0G0CtuG0:-MWfz4jM-4D8JhZNHnnQ:bqkn7zp) ([raw file](https://github.com/sillsdev/web-xforge/blob/79aa4e98c5c0bacdaf4e253bb3ee52fb49853983/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth-http-interceptor.ts#L31)):*
<details><summary><i>Previously, Nateowami (Nathaniel Paulus) wrote…</i></summary><blockquote>

@nigel-wells I think it's `return await next.handle(authReq).toPromise();`

That would still be returning a promise.
</blockquote></details>

Ah, is it `toPromise()` that the `await` relates to rather than the `handle` method?


<!-- Sent from Reviewable.io -->

2021-03-26 01:16 UTC, nigel-wells reviewed
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/992)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ddaspit and @Nateowami)

___
*[src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth-http-interceptor.ts, line 31 at r1](https://reviewable.io/reviews/sillsdev/web-xforge/992#-MWXOGya1PFu0G0CtuG0:-MWg5GeHAdHUAzoNImr0:b-b0xvue) ([raw file](https://github.com/sillsdev/web-xforge/blob/79aa4e98c5c0bacdaf4e253bb3ee52fb49853983/src/SIL.XForge.Scripture/ClientApp/src/xforge-common/auth-http-interceptor.ts#L31)):*
<details><summary><i>Previously, nigel-wells (Nigel Wells) wrote…</i></summary><blockquote>

Ah, is it `toPromise()` that the `await` relates to rather than the `handle` method?
</blockquote></details>

I've added it in, test, and it still works.


<!-- Sent from Reviewable.io -->

2021-03-26 03:29 UTC, irahopkinson approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/web-xforge/992#-:-MWgZx-m-OKVDLX6CUeC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nigel-wells)



<!-- Sent from Reviewable.io -->

2021-03-26 03:30 UTC, merged